Repository rust-lang/rust, pull requests merged in 2018-10, with the labels that each got.

#54675 rust: Add a `-C default-linker-libraries` option
  src/librustc/session/config.rs
  src/librustc_codegen_llvm/back/link.rs
Labels: S-waiting-on-bors

#53784 Document that slices cannot be larger than `isize::MAX` bytes
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#54308 Better user experience when attempting to call associated functions with dot notation
  src/librustc_resolve/lib.rs
  src/test/ui/resolve/issue-22692.rs
  src/test/ui/resolve/issue-22692.stderr
Labels: S-waiting-on-bors

#54488 in which we include attributes in unused `extern crate` suggestion spans
  src/librustc_typeck/check_unused.rs
  src/test/ui/rust-2018/issue-54400-unused-extern-crate-attr-span.fixed
  src/test/ui/rust-2018/issue-54400-unused-extern-crate-attr-span.rs
  src/test/ui/rust-2018/issue-54400-unused-extern-crate-attr-span.stderr
Labels: S-waiting-on-bors

#54544 Indicate how to move value out of Box in docs.
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#54623 Added help message for `impl_trait_in_bindings` feature gate
  src/librustc/hir/lowering.rs
  src/test/ui/feature-gates/feature-gate-impl_trait_in_bindings.stderr
  src/test/ui/impl-trait/where-allowed.stderr
Labels: S-waiting-on-bors

#54676 Remove `-Z disable_ast_check_for_mutation_in_guard`
  src/librustc/session/config.rs
  src/librustc/ty/context.rs
  src/test/run-pass/issues/issue-24535-allow-mutable-borrow-in-match-guard.rs
  src/test/ui/issues/issue-27282-reborrow-ref-mut-in-guard.rs
  src/test/ui/nll/match-guards-partially-borrow.rs
Labels: S-waiting-on-bors

#54679 Improve bug! message for impossible case in Relate
  src/librustc/ty/relate.rs
Labels: S-waiting-on-bors

#54681 Rename sanitizer runtime libraries on OSX
  src/bootstrap/compile.rs
  src/build_helper/lib.rs
  src/librustc_asan/build.rs
  src/librustc_tsan/build.rs
Labels: S-waiting-on-bors

#54708 Make ./x.py help <cmd> invoke ./x.py <cmd> -h on its own
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#54713 Add nightly check for tool_lints warning
  src/librustc/lint/levels.rs
Labels: S-waiting-on-bors

#54701 normalize param-env type-outlives predicates last
  src/librustc/infer/mod.rs
  src/librustc/traits/mod.rs
  src/test/run-pass/issue-54467.rs
Labels: S-waiting-on-bors, beta-nominated

#54269 #53840: Consolidate pattern check errors
  src/librustc_mir/hair/pattern/check_match.rs
  src/test/ui/issue-53840.rs
  src/test/ui/issue-53840.stderr
Labels: S-waiting-on-bors

#54458 Allow both explicit and elided lifetimes in the same impl header
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/impl-header-lifetime-elision/explicit-and-elided-same-header.rs
Labels: S-waiting-on-bors

#54699 Re-export `getopts` so custom drivers can reference it.
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#54605 resolve: Disambiguate a subset of conflicts "macro_rules" vs "macro name in module"
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/macros.rs
  src/test/ui/imports/macros.stderr
  src/test/ui/macros/ambiguity-legacy-vs-modern.rs
  src/test/ui/macros/ambiguity-legacy-vs-modern.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#53523 Add doc for impl From for Std Error
  src/libstd/error.rs
Labels: S-waiting-on-bors

#54746 simplify some unused lints code
  src/librustc_lint/unused.rs
Labels: S-waiting-on-bors

#54761 Make spec_extend use for_each()
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#54769 Fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#54773 Update a FIXME in memory.rs
  src/librustc_mir/interpret/memory.rs
Labels: S-waiting-on-bors

#54777 abolish ICE when pretty-printing async block
  src/libsyntax/print/pprust.rs
  src/test/pretty/issue-54752-async-block.rs
Labels: S-waiting-on-bors

#54780 Remove duplicate predicates in `explicit_predicates_of`
  src/librustc_typeck/collect.rs
  src/test/ui/chalkify/lower_env1.stderr
Labels: S-waiting-on-bors

#54788 A handful of cleanups for rustc/mir
  src/librustc/mir/interpret/value.rs
  src/librustc/mir/mod.rs
  src/librustc/mir/mono.rs
  src/librustc/mir/tcx.rs
Labels: S-waiting-on-author

#54795 remove padding from multiline format string label
  src/libfmt_macros/lib.rs
  src/test/ui/if/ifmt-bad-arg.rs
  src/test/ui/if/ifmt-bad-arg.stderr
Labels: S-waiting-on-bors

#52121 Merge `proc_macro_` expansion feature gates as `proc_macro_hygiene`
  src/libsyntax/ext/expand.rs
  src/libsyntax/feature_gate.rs
  src/test/compile-fail-fulldeps/proc-macro/attr-invalid-exprs.rs
  src/test/compile-fail-fulldeps/proc-macro/attr-stmt-expr.rs
  src/test/compile-fail-fulldeps/proc-macro/lints_in_proc_macros.rs
  src/test/compile-fail-fulldeps/proc-macro/proc-macro-gates.rs
  src/test/run-pass-fulldeps/auxiliary/cond_plugin.rs
  src/test/run-pass-fulldeps/auxiliary/hello_macro.rs
  src/test/run-pass-fulldeps/auxiliary/proc_macro_def.rs
  src/test/run-pass-fulldeps/macro-quote-cond.rs
  src/test/run-pass-fulldeps/macro-quote-test.rs
  src/test/run-pass-fulldeps/proc-macro/attr-stmt-expr.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/count_compound_ops.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/hygiene_example_codegen.rs
  src/test/run-pass-fulldeps/proc-macro/bang-macro.rs
  src/test/run-pass-fulldeps/proc-macro/call-site.rs
  src/test/run-pass-fulldeps/proc-macro/count_compound_ops.rs
  src/test/run-pass-fulldeps/proc-macro/hygiene_example.rs
  src/test/run-pass-fulldeps/proc-macro/negative-token.rs
  src/test/run-pass-fulldeps/proc_macro.rs
  src/test/ui-fulldeps/lifetimes.rs
  src/test/ui-fulldeps/proc-macro/macro-use-bang.rs
  src/test/ui-fulldeps/proc-macro/multispan.rs
  src/test/ui-fulldeps/proc-macro/parent-source-spans.rs
  src/test/ui-fulldeps/proc-macro/three-equals.rs
Labels: S-waiting-on-bors

#54078 Expand the documentation for the `std::sync` module
  src/libstd/sync/mod.rs
Labels: S-waiting-on-bors

#54781 Add examples to `TyKind::FnDef` and `TyKind::FnPtr` docs
  src/librustc/ty/sty.rs
Labels: S-waiting-on-bors

#54804 add suggestion for inverted function parameters
  src/libsyntax/parse/parser.rs
  src/test/ui/parser/inverted-parameters.rs
  src/test/ui/parser/inverted-parameters.stderr
Labels: S-waiting-on-bors

#54812 Regression test for #32382.
  src/test/ui/nll/issue-32382-index-assoc-type-with-lifetime.rs
Labels: S-waiting-on-bors

#54833 make `Parser::parse_foreign_item()` return a foreign item or error
  src/libsyntax/ext/expand.rs
  src/libsyntax/parse/parser.rs
  src/test/parse-fail/duplicate-visibility.rs
  src/test/ui/macros/issue-54441.rs
  src/test/ui/macros/issue-54441.stderr
Labels: S-waiting-on-bors

#54834 rustdoc: overflow:auto doesn't work nicely on small screens
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#54838 Fix typo in src/libsyntax/parse/parser.rs
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#54851 Fix a regression in 1.30 by reverting #53564
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#54853 Remove unneccessary error from test, revealing NLL error.
  src/test/ui/issues/issue-13058.nll.stderr
  src/test/ui/issues/issue-13058.rs
  src/test/ui/issues/issue-13058.stderr
Labels: S-waiting-on-bors

#54813 Fix two UI tests with locale-dependent output
  src/test/ui/extern/external-doc-error.rs
  src/test/ui/extern/external-doc-error.stderr
  src/test/ui/macros/macros-nonfatal-errors.rs
  src/test/ui/macros/macros-nonfatal-errors.stderr
Labels: S-waiting-on-bors

#53517 Add doc for impl From for Error
  src/libstd/io/error.rs
Labels: S-waiting-on-bors

#54609 Add the library search box on the 404 page
  src/doc/not_found.md
Labels: S-waiting-on-bors

#54700 Clarify docs for when binary_search has many matches.
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#54847 Cleanup: remove graphviz::IntoCow
  src/libgraphviz/lib.rs
  src/librustc/cfg/graphviz.rs
  src/librustc_borrowck/graphviz.rs
  src/librustc_incremental/assert_dep_graph.rs
  src/librustc_mir/borrow_check/nll/region_infer/graphviz.rs
  src/librustc_mir/dataflow/graphviz.rs
Labels: S-waiting-on-bors

#54865 Backport 1.29.2 release notes to master
  RELEASES.md
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#54871 Remove unnecessary comma in `libstd/thread/mod.rs` doc comment
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#54613 liballoc: mark str.to_owned() and String::from(&str) as #[inline].
  src/liballoc/str.rs
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#54831 NLL is missing struct field suggestion
  src/librustc_mir/borrow_check/mutability_errors.rs
  src/test/ui/did_you_mean/issue-38147-2.nll.stderr
  src/test/ui/did_you_mean/issue-38147-3.nll.stderr
Labels: A-NLL, S-waiting-on-bors

#54732 LocalWaker and Waker cleanups
  src/libcore/task/wake.rs
Labels: S-waiting-on-bors

#54747 codegen_llvm: verify that inline assembly operands are scalars
  src/librustc_codegen_llvm/diagnostics.rs
  src/librustc_codegen_llvm/mir/statement.rs
  src/test/ui/inline-asm-bad-operand.rs
  src/test/ui/inline-asm-bad-operand.stderr
Labels: S-waiting-on-bors

#54893 Fix internal compiler error on malformed match arm pattern.
  src/libsyntax/parse/parser.rs
  src/test/ui/resolve/issue-54379.rs
  src/test/ui/resolve/issue-54379.stderr
Labels: S-waiting-on-bors

#54850 Fix #54707 - parse_trait_item_ now handles interpolated blocks as function body decls
  src/libsyntax/parse/parser.rs
  src/test/run-pass/macros/macro-as-fn-body.rs
Labels: S-waiting-on-bors

#54755 Documents reference equality by address (#54197)
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#54825 NLL says "borrowed content" instead of more precise "dereference of raw pointer"
  src/librustc_mir/borrow_check/move_errors.rs
  src/test/ui/borrowck/borrowck-move-from-unsafe-ptr.nll.stderr
  src/test/ui/issues/issue-20801.nll.stderr
Labels: A-NLL, S-waiting-on-bors

#54860 Add doc comments about safest way to initialize a vector of zeros
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#54891 Fix tracking issue for Once::is_completed
  src/libstd/sync/once.rs
Labels: S-waiting-on-bors

#54913 doc fix: it's auto traits that make for automatic implementations
  src/libstd/panic.rs
Labels: S-waiting-on-bors

#54920 Fix handling of #[must_use] on unit and uninhabited types
  src/librustc_lint/unused.rs
  src/test/ui/lint/must_use-unit.rs
  src/test/ui/lint/must_use-unit.stderr
Labels: S-waiting-on-bors

#54932 A handful of random string-related improvements
  src/build_helper/lib.rs
  src/librustc_errors/diagnostic.rs
Labels: S-waiting-on-bors

#54936 impl Eq+Hash for TyLayout
  src/librustc_mir/interpret/operand.rs
  src/librustc_target/abi/mod.rs
Labels: S-waiting-on-bors

#54950 std: Synchronize global allocator on wasm32
  src/liballoc_system/lib.rs
Labels: S-waiting-on-bors

#54956 "(using ..." doesn't have the matching ")"
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#54958 add a macro for static (compile-time) assertions
  src/librustc/macros.rs
  src/librustc/middle/region.rs
  src/librustc/ty/context.rs
Labels: S-waiting-on-bors

#54967 Remove incorrect span for second label inner macro invocation
  src/libsyntax/parse/parser.rs
  src/test/ui/macros/issue-54441.stderr
Labels: S-waiting-on-bors

#54983 Fix slice's benchmarks
  src/liballoc/benches/slice.rs
Labels: S-waiting-on-bors

#55019 [beta] Bump bootstrap compiler to 1.29.2
  src/stage0.txt
Labels: S-waiting-on-bors

#54945 Point to variable in `asm!` macro when failing borrowck
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/middle/expr_use_visitor.rs
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/asm/asm-out-assign-imm.nll.stderr
  src/test/ui/asm/asm-out-assign-imm.stderr
  src/test/ui/borrowck/borrowck-asm.ast.nll.stderr
  src/test/ui/borrowck/borrowck-asm.ast.stderr
  src/test/ui/borrowck/borrowck-asm.mir.stderr
Labels: S-waiting-on-bors

#54951 std: Implement TLS for wasm32-unknown-unknown
  src/libstd/Cargo.toml
  src/libstd/sys/wasm/mutex_atomics.rs
  src/libstd/sys/wasm/thread.rs
  src/libstd/sys/wasm/thread_local_atomics.rs
  src/libstd/thread/local.rs
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#55003 `#[must_use]` for associated functions is supposed to actually work
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/librustc_lint/unused.rs
  src/test/run-pass/resolve-pseudo-shadowing.rs
  src/test/ui/fn_must_use.rs
  src/test/ui/fn_must_use.stderr
Labels: S-waiting-on-bors

#55049 doc: fix sentence structure in std::fmt
  src/liballoc/fmt.rs
Labels: S-waiting-on-bors

#55015 Support underscore as constant name
  src/libsyntax/feature_gate.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/feature-gate-underscore_const_names.rs
  src/test/ui/feature-gate-underscore_const_names.stderr
  src/test/ui/underscore_const_names.rs
Labels: S-waiting-on-bors

#55055 bump bootstrap compiler to rustc beta 2018-10-13
  src/stage0.txt
Labels: S-waiting-on-bors

#55046 [mir-inlining] Don't inline virtual calls
  src/librustc_mir/transform/inline.rs
  src/test/mir-opt/inline-trait-method.rs
Labels: S-waiting-on-bors

#55008 Cleanup rustc/driver
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
  src/librustc_driver/pretty.rs
  src/librustc_driver/profile/mod.rs
  src/librustc_driver/profile/trace.rs
Labels: S-waiting-on-bors

#54917 Unused result warning: "X which must" ↦ "X that must"
  src/doc/rustc/src/lints/listing/warn-by-default.md
  src/libcore/iter/mod.rs
  src/librustc_lint/unused.rs
  src/test/ui/conditional-compilation/cfg-attr-multi-true.rs
  src/test/ui/conditional-compilation/cfg-attr-multi-true.stderr
  src/test/ui/fn_must_use.stderr
  src/test/ui/lint/must-use-ops.stderr
  src/test/ui/lint/must_use-unit.stderr
  src/test/ui/unused/unused-result.rs
  src/test/ui/unused/unused-result.stderr
Labels: S-waiting-on-bors

#54991 add test for #23189
  src/test/ui/issues/issue-23189.rs
  src/test/ui/issues/issue-23189.stderr
Labels: S-waiting-on-bors

#55025 Add missing lifetime fragment specifier to error message.
  src/libsyntax/ext/tt/macro_rules.rs
  src/test/ui/issues/issue-21356.stderr
  src/test/ui/macros/macro-invalid-fragment-spec.stderr
  src/test/ui/unused/unused-macro-with-bad-frag-spec.stderr
Labels: S-waiting-on-bors

#55047 doc: make core::fmt::Error example more simple
  src/libcore/fmt/mod.rs
Labels: S-waiting-on-bors

#55048 Don't collect to vectors where unnecessary
  src/librustc/hir/lowering.rs
  src/librustc_traits/lowering.rs
  src/librustc_typeck/check/demand.rs
Labels: S-waiting-on-bors

#55062 Make EvalContext::step public again
  src/librustc_mir/interpret/step.rs
Labels: S-waiting-on-bors

#55066 Fix incorrect link in println! documentation
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#55081 Deduplicate tests
  src/test/ui/lifetimes/lifetime-errors/ex3-both-anon-regions-both-are-structs-4.nll.stderr
  src/test/ui/lifetimes/lifetime-errors/ex3-both-anon-regions-both-are-structs-4.rs
  src/test/ui/lifetimes/lifetime-errors/ex3-both-anon-regions-both-are-structs-4.stderr
  src/test/ui/lint/lint-group-style.rs
  src/test/ui/lint/lint-group-style.stderr
Labels: S-waiting-on-bors

#55088 Update rustc documentation link
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#54486 Added graphviz visualization for obligation forests.
  src/Cargo.lock
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/obligation_forest/graphviz.rs
  src/librustc_data_structures/obligation_forest/mod.rs
Labels: S-waiting-on-bors

#55135 NLL: Fix migrate mode issue by not buffering lints.
  src/librustc_mir/borrow_check/mod.rs
Labels: S-waiting-on-bors

#54646 improve documentation on std::thread::sleep
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#54964 Run both lldb and gdb tests
  src/bootstrap/test.rs
  src/test/debuginfo/lexical-scope-with-macro.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#55031 Improve verify_llvm_ir config option
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/ci/run.sh
  src/librustc/build.rs
  src/librustc/session/mod.rs
Labels: S-waiting-on-bors

#55050 doc std::fmt: the Python inspiration is already mentioned in precedin…
  src/liballoc/fmt.rs
Labels: S-waiting-on-bors

#55077 rustdoc: Use dyn keyword when rendering dynamic traits
  src/librustdoc/html/format.rs
  src/test/rustdoc/assoc-consts.rs
  src/test/rustdoc/inline_cross/issue-32881.rs
  src/test/rustdoc/test-parens.rs
Labels: S-waiting-on-bors

#55080 Detect if access to localStorage is forbidden by the user's browser
  src/librustdoc/html/static/storage.js
Labels: S-waiting-on-bors

#55090 regression test for move out of borrow via pattern
  src/test/ui/borrowck/issue-54597-reject-move-out-of-borrow-via-pat.rs
  src/test/ui/borrowck/issue-54597-reject-move-out-of-borrow-via-pat.stderr
Labels: A-NLL, S-waiting-on-bors

#55102 resolve: Do not skip extern prelude during speculative resolution
  src/librustc_resolve/lib.rs
  src/test/run-pass/extern/extern-prelude-no-speculative.rs
  src/test/ui/impl-trait/auxiliary/extra-item.rs
  src/test/ui/impl-trait/extra-item.rs
  src/test/ui/impl-trait/extra-item.stderr
Labels: S-waiting-on-author, beta-nominated

#55104 Add test for #34229
  src/test/ui/issues/issue-34229.rs
  src/test/ui/issues/issue-34229.stderr
Labels: S-waiting-on-bors

#55111 [Rustc Book] Explain --cfg's arguments
  src/doc/rustc/src/command-line-arguments.md
Labels: S-waiting-on-bors

#55127 Remove HybridBitSet::dummy
  src/librustc_data_structures/bit_set.rs
Labels: S-waiting-on-bors

#55128 Fix LLVMRustInlineAsmVerify return type mismatch
  src/librustc_codegen_llvm/builder.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
Labels: S-waiting-on-bors

#55142 miri: layout should not affect CTFE checks (outside of validation)
  src/librustc_mir/interpret/operand.rs
Labels: S-waiting-on-bors

#55161 [librustdoc] Disable spellcheck for search field
  src/librustdoc/html/layout.rs
Labels: S-waiting-on-bors

#54580 Add slice::rchunks(), rchunks_mut(), rchunks_exact() and rchunks_exact_mut()
  src/liballoc/lib.rs
  src/liballoc/slice.rs
  src/liballoc/tests/lib.rs
  src/liballoc/tests/slice.rs
  src/libcore/slice/mod.rs
  src/libcore/tests/lib.rs
  src/libcore/tests/slice.rs
Labels: S-waiting-on-bors, T-libs

#54300 Updated RELEASES.md for 1.30.0
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted

#55013 [NLL] Propagate bounds from generators
  src/librustc_mir/borrow_check/nll/region_infer/mod.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/borrow_check/nll/universal_regions.rs
  src/test/ui/generator/generator-region-requirements.ast.stderr
  src/test/ui/generator/generator-region-requirements.nll.stderr
  src/test/ui/generator/generator-region-requirements.rs
Labels: A-NLL, S-waiting-on-bors

#55169 Add a `copysign` function to f32 and f64
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#55178 Stabilize slice::chunks_exact(), chunks_exact_mut(), rchunks(), rchunks_mut(), rchunks_exact(), rchunks_exact_mut()
  src/liballoc/lib.rs
  src/liballoc/slice.rs
  src/liballoc/tests/lib.rs
  src/libcore/slice/mod.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, relnotes

#55007 Help suggests non-existent package std::os::ext::process::CommandExt
  src/librustc/ty/item_path.rs
  src/test/ui/issues/issue-39175.rs
  src/test/ui/issues/issue-39175.stderr
Labels: S-waiting-on-bors

#55014 Prefer unwrap_or_else to unwrap_or in case of function calls/allocations
  src/bootstrap/config.rs
  src/build_helper/lib.rs
  src/librustc/hir/lowering.rs
  src/librustc/lint/levels.rs
  src/librustc/lint/mod.rs
  src/librustc/traits/auto_trait.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/ty/context.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/back/rpath.rs
  src/librustc_codegen_llvm/llvm/archive_ro.rs
  src/librustc_codegen_llvm/llvm/diagnostic.rs
  src/librustc_codegen_utils/link.rs
  src/librustc_driver/driver.rs
  src/librustc_errors/diagnostic_builder.rs
  src/librustc_metadata/locator.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/borrow_check/mutability_errors.rs
  src/librustc_mir/borrow_check/nll/mod.rs
  src/librustc_mir/interpret/cast.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/librustc_resolve/resolve_imports.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/libstd/build.rs
  src/libstd/sys/redox/args.rs
  src/libstd/sys/unix/process/process_unix.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/source_map.rs
  src/libsyntax/tokenstream.rs
Labels: S-waiting-on-bors

#55073 rustc: Fix (again) simd vectors by-val in ABI
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_llvm/build.rs
  src/rustllvm/DemoteSimd.cpp
  src/test/run-make/simd-argument-promotion-thwarted/Makefile
  src/test/run-make/simd-argument-promotion-thwarted/t1.rs
  src/test/run-make/simd-argument-promotion-thwarted/t2.rs
  src/test/run-make/simd-argument-promotion-thwarted/t3.rs
Labels: S-waiting-on-bors

#55203 Write an initial version of the `program_clauses` callback
  src/librustc_traits/chalk_context.rs
  src/librustc_traits/lowering/environment.rs
  src/librustc_traits/lowering/mod.rs
Labels: S-waiting-on-bors

#55213 ignore target folders
  src/tools/tidy/src/lib.rs
Labels: S-waiting-on-bors

#55126 improve search tabs look
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#55224 Use a keyword in raw identifier example
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#55231 pick a reference issue for absolute-paths future incompatibility info
  src/librustc_lint/lib.rs
  src/test/ui-fulldeps/rust-2018/suggestions-not-always-applicable.stderr
  src/test/ui/rust-2018/edition-lint-fully-qualified-paths.stderr
  src/test/ui/rust-2018/edition-lint-nested-empty-paths.stderr
  src/test/ui/rust-2018/edition-lint-nested-paths.stderr
  src/test/ui/rust-2018/edition-lint-paths.stderr
  src/test/ui/rust-2018/extern-crate-rename.stderr
  src/test/ui/rust-2018/extern-crate-submod.stderr
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#55281 Revert "rustc: Fix (again) simd vectors by-val in ABI"
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_llvm/build.rs
  src/rustllvm/DemoteSimd.cpp
  src/test/run-make/simd-argument-promotion-thwarted/Makefile
  src/test/run-make/simd-argument-promotion-thwarted/t1.rs
  src/test/run-make/simd-argument-promotion-thwarted/t2.rs
  src/test/run-make/simd-argument-promotion-thwarted/t3.rs
Labels: S-waiting-on-bors

#53507 Add doc for impl From for Waker
  src/libcore/task/wake.rs
Labels: S-waiting-on-bors

#53931 Gradually expanding libstd's keyword documentation
  src/libstd/keyword_docs.rs
Labels: S-waiting-on-bors

#54965 update tcp stream documentation
  src/libstd/net/tcp.rs
Labels: S-waiting-on-bors

#54977 Accept `Option<Box<$t:ty>>` in macro argument
  src/libsyntax/ext/tt/macro_rules.rs
  src/test/run-pass/macros/issue-25274.rs
Labels: S-waiting-on-bors

#55138 in which unused-parens suggestions heed what the user actually wrote
  src/librustc_lint/unused.rs
  src/test/ui/lint/suggestions.rs
  src/test/ui/lint/suggestions.stderr
Labels: S-waiting-on-bors

#55200 Documents `From` implementations for `Stdio`
  src/libstd/process.rs
Labels: S-waiting-on-bors

#55247 Clarified code example in char primitive doc
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#55251 Fix a typo in the documentation of RangeInclusive
  src/libcore/ops/range.rs
Labels: S-waiting-on-bors

#55253 only issue "variant of the expected type" suggestion for enums
  src/librustc_typeck/check/demand.rs
  src/test/ui/did_you_mean/issue-42764.rs
  src/test/ui/did_you_mean/issue-42764.stderr
Labels: S-waiting-on-bors

#55254 Correct trailing ellipsis in name_from_pat
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors

#55269 fix typos in various places
  src/bootstrap/bootstrap.py
  src/etc/lldb_rust_formatters.py
  src/liballoc/collections/btree/map.rs
  src/libcore/alloc.rs
  src/libcore/intrinsics.rs
  src/libcore/pin.rs
  src/libcore/ptr.rs
  src/librustc/hir/def_id.rs
  src/librustc/mir/interpret/mod.rs
  src/librustc/mir/mod.rs
  src/librustc/traits/error_reporting.rs
  src/librustc_codegen_llvm/builder.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/diagnostics.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_passes/ast_validation.rs
  src/librustc_target/abi/mod.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/coherence/builtin.rs
  src/libstd/sync/mod.rs
  src/libstd/sync/once.rs
  src/libsyntax/config.rs
  src/test/run-pass/issues/issue-18804/main.rs
  src/test/ui/block-result/unexpected-return-on-unit.rs
  src/test/ui/conditional-compilation/cfg-attr-multi-false.rs
  src/test/ui/nll/issue-21232-partial-init-and-use.rs
  src/test/ui/nll/issue-52059-report-when-borrow-and-drop-conflict.rs
  src/test/ui/resolve/token-error-correct-2.rs
  src/test/ui/resolve/token-error-correct-3.rs
  src/test/ui/resolve/token-error-correct.rs
  src/test/ui/rfc-2497-if-let-chains/syntax-ambiguity-2015.rs
  src/test/ui/rfc-2497-if-let-chains/syntax-ambiguity-2015.stderr
  src/test/ui/rfc-2497-if-let-chains/syntax-ambiguity-2018.rs
  src/test/ui/rfc-2497-if-let-chains/syntax-ambiguity-2018.stderr
  src/test/ui/rust-2018/edition-lint-infer-outlives.fixed
  src/test/ui/rust-2018/edition-lint-infer-outlives.rs
  src/test/ui/specialization/issue-52050.rs
  src/tools/tidy/src/pal.rs
Labels: S-waiting-on-bors

#55282 Remove redundant clone
  src/librustc/hir/print.rs
  src/librustc/ich/caching_codemap_view.rs
  src/librustc/traits/project.rs
  src/librustc/ty/sty.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/libsyntax/fold.rs
Labels: S-waiting-on-bors

#55285 Do some copy editing on the release notes
  RELEASES.md
Labels: S-waiting-on-bors, beta-accepted

#55296 Set RUST_BACKTRACE=0 for rustdoc-ui/failed-doctest-output.rs
  src/test/rustdoc-ui/failed-doctest-output.rs
  src/test/rustdoc-ui/failed-doctest-output.stdout
Labels: S-waiting-on-author

#55306 Regression test for #54478.
  src/test/rustdoc/issue-54478-demo-allocator.rs
Labels: S-waiting-on-bors

#55328 Fix doc for new copysign functions
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#55340 Operands no longer appear in places
  src/librustc/mir/mod.rs
Labels: S-waiting-on-bors

#55345 Remove is_null
  src/librustc/mir/interpret/value.rs
Labels: S-waiting-on-bors

#55348 Update RELEASES.md after destabilization of non_modrs_mods
  RELEASES.md
Labels: S-waiting-on-bors, beta-nominated

#55362 Remove `cargo new --edition` from release notes.
  RELEASES.md
Labels: S-waiting-on-bors

#54921 Add line numbers option to rustdoc
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#55167 Add a "cheap" mode for `compute_missing_ctors`.
  src/librustc_mir/hair/pattern/_match.rs
Labels: S-waiting-on-bors

#55258 Fix Rustdoc ICE when checking blanket impls
  src/librustc/infer/combine.rs
  src/librustc/infer/equate.rs
  src/librustc/traits/select.rs
  src/librustdoc/clean/blanket_impl.rs
  src/test/rustdoc/issue-55001.rs
Labels: S-waiting-on-bors

#55271 Unimplement ExactSizeIterator for MIR traversing iterators
  src/librustc/mir/traversal.rs
Labels: S-waiting-on-bors

#55301 List allowed tokens after macro fragments
  src/libsyntax/ext/tt/macro_rules.rs
  src/test/ui/macros/macro-follow.stderr
  src/test/ui/macros/macro-followed-by-seq-bad.stderr
  src/test/ui/macros/macro-input-future-proofing.stderr
  src/test/ui/unused/unused-macro-with-follow-violation.stderr
Labels: S-waiting-on-author

#55302 Extend the impl_stable_hash_for! macro for miri.
  src/librustc/macros.rs
  src/librustc_mir/interpret/snapshot.rs
Labels: S-waiting-on-author

#55325 Fix link to macros chapter
  RELEASES.md
Labels: S-waiting-on-bors

#55343 rustbuild: fix remap-debuginfo when building a release
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#55346 Shrink `Statement`.
  src/librustc/mir/mod.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/build/expr/as_place.rs
  src/librustc_mir/build/matches/mod.rs
Labels: S-waiting-on-bors

#55358 Remove redundant clone (2)
  src/bootstrap/dist.rs
  src/bootstrap/test.rs
  src/librustc/infer/outlives/obligations.rs
  src/librustc/infer/region_constraints/mod.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/project.rs
  src/librustc/ty/context.rs
  src/librustc_borrowck/borrowck/mod.rs
  src/librustc_borrowck/borrowck/move_data.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_utils/link.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_target/spec/mod.rs
  src/librustc_typeck/check/autoderef.rs
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/render.rs
  src/librustdoc/lib.rs
  src/librustdoc/test.rs
  src/libsyntax/ext/tt/macro_rules.rs
  src/libsyntax/ext/tt/transcribe.rs
  src/libsyntax/test.rs
  src/libsyntax_ext/deriving/cmp/partial_ord.rs
  src/libsyntax_ext/deriving/custom.rs
Labels: S-waiting-on-bors

#55370 Update mailmap for estebank
  .mailmap
Labels: S-waiting-on-bors

#55375 Typo fixes in configure_cmake comments
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#55378 rustbuild: use configured linker to build boostrap
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#55379 validity: assert that unions are non-empty
  src/librustc_mir/interpret/validity.rs
Labels: S-waiting-on-bors

#55383 Use `SmallVec` for the queue in `coerce_unsized`.
  src/librustc_typeck/check/coercion.rs
Labels: S-waiting-on-bors

#55053 Add option to run all tests, again
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#55192 Fix ordering of nested modules in non-mod.rs mods
  src/libsyntax/parse/parser.rs
  src/test/ui/non_modrs_mods_and_inline_mods/non_modrs_mods_and_inline_mods.rs
  src/test/ui/non_modrs_mods_and_inline_mods/x.rs
  src/test/ui/non_modrs_mods_and_inline_mods/x/y/z/mod.rs
Labels: S-waiting-on-bors, beta-nominated

#55148 Implement FromStr for PathBuf
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#55185 path suggestions in Rust 2018 should point out the change in semantics
  src/librustc_resolve/error_reporting.rs
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/rust-2018/local-path-suggestions-2018.stderr
Labels: S-waiting-on-bors, beta-nominated

#55191 Fix sub-variant doc display
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#55252 Add MaybeUninit::new
  src/libcore/lib.rs
  src/libcore/mem.rs
Labels: B-unstable, S-waiting-on-bors, T-libs
