Repository rust-lang/rust, pull requests merged in 2018-06, with the labels that each got.

#51096 Register outlives predicates from queries the right way around.
  src/librustc_traits/util.rs
  src/test/ui/nll/normalization-bounds-error.rs
  src/test/ui/nll/normalization-bounds-error.stderr
  src/test/ui/nll/normalization-bounds.rs
Labels: S-waiting-on-bors

#51181 Add std/core to prelude if extern_prelude enabled
  src/librustc_resolve/lib.rs
  src/test/run-pass/extern-prelude-core.rs
  src/test/run-pass/extern-prelude-std.rs
Labels: S-waiting-on-bors

#51264 Make the OOM hook return `()` rather than `!`
  src/libstd/alloc.rs
Labels: S-waiting-on-bors

#51163 Simplify HashMap layout calculation by using Layout
  src/libcore/alloc.rs
  src/libstd/collections/hash/table.rs
Labels: S-waiting-on-bors

#51152 Replace `if` with `if and only if` in the definition dox of `Sync`
  src/libcore/marker.rs
Labels: S-waiting-on-bors

#51262 Add missing whitespace in num example
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#51272 Remove feature flag from fs::read_to_string example
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#51286 Pull 1.26.2 release notes into master
  RELEASES.md
Labels: S-waiting-on-bors

#51270 fs: copy: Add EPERM to fallback error conditions
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#51274 also check `let` arms and nested patterns for mutable borrows
  src/librustc/middle/mem_categorization.rs
  src/librustc_passes/rvalue_promotion.rs
  src/test/ui/borrowck/promote-ref-mut-in-let-issue-46557.nll.stderr
  src/test/ui/borrowck/promote-ref-mut-in-let-issue-46557.rs
  src/test/ui/borrowck/promote-ref-mut-in-let-issue-46557.stderr
Labels: S-waiting-on-bors, beta-nominated

#50167 Add as_nanos function to Duration
  src/libcore/time.rs
Labels: S-waiting-on-bors, T-libs

#50919 Provide more context for what the {f32,f64}::EPSILON values represent.
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
Labels: S-waiting-on-bors

#51124 Reword {ptr,mem}::replace docs.
  src/libcore/mem.rs
  src/libcore/ptr.rs
Labels: S-waiting-on-bors

#51147 Stabilize SliceIndex trait.
  src/liballoc/lib.rs
  src/liballoc/slice.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#51291 Fix typos of ‘ambiguous’
  src/librustc/traits/project.rs
  src/librustc/traits/query/normalize.rs
Labels: S-waiting-on-bors

#51302 Permit building rustdoc without compiler artifacts
  src/bootstrap/test.rs
  src/test/rustdoc/rustc-macro-crate.rs
Labels: S-waiting-on-bors

#50953 Add attributes for trait and methods as well
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/test/rustdoc/trait-attributes.rs
Labels: S-waiting-on-bors

#51143 Specify that packed types must derive, not implement, Copy
  src/librustc_mir/transform/check_unsafety.rs
  src/test/ui/deriving-with-repr-packed.rs
  src/test/ui/deriving-with-repr-packed.stderr
Labels: S-waiting-on-bors

#51226 Make Layout's align a NonZeroUsize
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#51297 Fix run button style
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#51306 impl Default for &mut str
  src/liballoc/tests/str.rs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#51313 use type name in E0599 enum variant suggestion
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/issue-23217.stderr
  src/test/ui/issue-28971.stderr
Labels: S-waiting-on-bors

#51288 Remove rustdoc-specific is_import field from HIR
  src/librustc/hir/def.rs
  src/librustc/ich/impls_hir.rs
  src/librustc_metadata/decoder.rs
  src/librustc_resolve/macros.rs
  src/librustc_resolve/resolve_imports.rs
  src/librustdoc/visit_lib.rs
Labels: S-waiting-on-bors

#51323 Generate br for all two target SwitchInts
  src/librustc_codegen_llvm/mir/block.rs
Labels: S-waiting-on-bors

#51326 Various minor slice iterator cleanups
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#51329 Remove the unused `-Z trans-time-graph` flag.
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#51151 Move slice::exact_chunks directly above exact_chunks_mut for more con…
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#51340 Optimize layout calculations in HashMap
  src/libstd/collections/hash/table.rs
Labels: S-waiting-on-bors

#51242 Suggest not mutably borrowing a mutable reference
  src/librustc_borrowck/borrowck/mod.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/borrowck/mut-borrow-of-mut-ref.nll.stderr
  src/test/ui/borrowck/mut-borrow-of-mut-ref.rs
  src/test/ui/borrowck/mut-borrow-of-mut-ref.stderr
  src/test/ui/did_you_mean/issue-31424.stderr
Labels: S-waiting-on-bors

#51324 Also prevent overflow in debug builds
  src/librustc_errors/emitter.rs
Labels: S-waiting-on-bors

#50852 Add doc comment to hiding portions of code example
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#51183 Update rustdoc book to suggest using Termination trait instead of hidden ‘foo’ function
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#51255 Fix confusing error message for sub_instant
  src/libstd/sys/redox/time.rs
  src/libstd/sys/unix/time.rs
Labels: S-waiting-on-bors

#51256 Fix crate-name option in rustdoc
  src/librustdoc/core.rs
  src/test/rustdoc/invalid.crate.name.rs
Labels: S-waiting-on-bors

#51343 test: Ignore some problematic tests on sparc and sparc64
  src/test/codegen/abi-main-signature-16bit-c-int.rs
  src/test/codegen/fastcall-inreg.rs
  src/test/codegen/repr-transparent-aggregates-2.rs
  src/test/codegen/stack-probes.rs
  src/test/codegen/x86_mmx.rs
  src/test/compile-fail/asm-bad-clobber.rs
  src/test/compile-fail/asm-in-bad-modifier.rs
  src/test/compile-fail/asm-misplaced-option.rs
  src/test/compile-fail/asm-out-no-modifier.rs
  src/test/compile-fail/asm-out-read-uninit.rs
  src/test/compile-fail/borrowck/borrowck-asm.rs
  src/test/run-pass/stack-probes-lto.rs
  src/test/run-pass/stack-probes.rs
  src/test/ui/asm-out-assign-imm.rs
  src/test/ui/asm-out-assign-imm.stderr
  src/test/ui/target-feature-wrong.rs
  src/test/ui/target-feature-wrong.stderr
Labels: S-waiting-on-bors

#51358 Tests that #39963 is fixed on MIR borrowck
  src/test/run-pass/borrowck/borrowck-multiple-borrows-interior-boxes.rs
Labels: S-waiting-on-bors

#51333 Reexport fmt::Alignment into std
  src/liballoc/fmt.rs
  src/libcore/fmt/mod.rs
Labels: S-waiting-on-bors

#51360 Suggest parentheses when a struct literal needs them
  src/librustc_resolve/lib.rs
  src/test/ui/error-codes/E0423.rs
  src/test/ui/error-codes/E0423.stderr
Labels: S-waiting-on-bors

#51394 Use scope tree depths to speed up `nearest_common_ancestor`.
  src/librustc/middle/region.rs
  src/librustc_driver/test.rs
Labels: S-waiting-on-bors

#51396 Make the size of Option<NonZero*> a documented guarantee.
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, final-comment-period

#51412 Avoid useless Vec clones in pending_obligations().
  src/librustc/traits/engine.rs
  src/librustc/traits/fulfill.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_typeck/check/closure.rs
Labels: S-waiting-on-bors

#51427 compiletest: autoremove duplicate .nll.* files (#51204)
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#51436 Do not require stage 2 compiler for rustdoc
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#51437 rustbuild: generate full list of dependencies for metadata
  src/bootstrap/lib.rs
  src/bootstrap/metadata.rs
Labels: S-waiting-on-bors

#51359 [fuchsia] Migrate from launchpad to fdio_spawn_etc
  src/libstd/build.rs
  src/libstd/sys/unix/process/process_fuchsia.rs
  src/libstd/sys/unix/process/zircon.rs
Labels: S-waiting-on-bors

#51400 Increase number of usages of `u8` in weird expressions u8 test
  src/test/run-pass/weird-exprs.rs
Labels: S-waiting-on-bors

#51439 Fix spelling error in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#51441 Document size_of for 128-bit integers
  src/libcore/mem.rs
Labels: S-waiting-on-bors

#51265 crate-ify and delete unused code from syntax::parse
  src/libsyntax/lib.rs
  src/libsyntax/parse/attr.rs
  src/libsyntax/parse/common.rs
  src/libsyntax/parse/lexer/comments.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/lexer/tokentrees.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
Labels: S-waiting-on-bors

#51320 Stabilize Iterator::step_by
  src/liballoc/tests/lib.rs
  src/libcore/iter/iterator.rs
  src/libcore/iter/mod.rs
  src/libcore/tests/lib.rs
  src/test/run-pass/range_inclusive.rs
  src/test/run-pass/sync-send-iterators-in-libcore.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#51079 Stabilize entry-or-default
  src/doc/unstable-book/src/library-features/entry-or-default.md
  src/liballoc/btree/map.rs
  src/librustc/lib.rs
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#51200 Stabilize iterator_repeat_with
  src/libcore/iter/mod.rs
  src/libcore/iter/sources.rs
  src/libcore/lib.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, relnotes

#51474 add some docs to `From` conversions
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#51475 Fix error codes
  src/librustc/diagnostics.rs
  src/librustc/hir/check_attr.rs
  src/librustc/hir/lowering.rs
  src/librustc/infer/anon_types/mod.rs
  src/librustc_typeck/check/generator_interior.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/diagnostics.rs
  src/test/compile-fail/edition-raw-pointer-method-2018.rs
  src/test/compile-fail/rfc-2008-non-exhaustive/invalid-attribute.rs
  src/test/ui/impl-trait/region-escape-via-bound.rs
  src/test/ui/impl-trait/region-escape-via-bound.stderr
Labels: S-waiting-on-bors

#51461 Update E0423 description
  src/librustc_resolve/diagnostics.rs
Labels: S-waiting-on-bors

#51423 Improve docs for slice::from_raw_parts
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, T-libs

#51467 create separate dep-nodes for predicates_of and explicit_predicates_of
  src/librustc/dep_graph/dep_node.rs
  src/librustc/ty/maps/mod.rs
  src/librustc/ty/maps/plumbing.rs
  src/test/incremental/issue-51409.rs
Labels: S-waiting-on-bors

#51480 Enable fall through past $:lifetime matcher
  src/libsyntax/ext/tt/macro_parser.rs
  src/test/compile-fail/macro-non-lifetime.rs
  src/test/run-pass/macro-first-set.rs
Labels: S-waiting-on-bors

#51478 Add #[doc(inline)] in std::task
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#51490 Long diagnostic for E0541
  src/libsyntax/diagnostic_list.rs
Labels: S-waiting-on-bors

#50617 Fix extern prelude failure in rustdoc
  src/librustc/session/config.rs
  src/librustc_resolve/lib.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors

#51498 Make parse_ident public
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51505 Regenerate character tables for Unicode 11
  src/libcore/unicode/printable.rs
  src/libcore/unicode/tables.rs
Labels: S-waiting-on-bors

#51508 Make span_fatal and parse_block public
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51507 Removed incorrect release note.
  RELEASES.md
Labels: S-waiting-on-bors

#51261 Updated RELEASES.md for 1.27.0
  RELEASES.md
Labels: C-enhancement, S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#51502 Make parse_seq_to_end and parse_path public
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51510 Long diagnostic for E0538
  src/libsyntax/diagnostic_list.rs
Labels: S-waiting-on-bors

#51527 Don't auto-hide inherent impls even if `rustdoc-collapse == true`.
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, T-rustdoc

#51531 Remove stray commented one use statement
  src/librustc_typeck/astconv.rs
Labels: S-waiting-on-bors

#51539 Update README.md
  README.md
Labels: S-waiting-on-bors

#51532 Improve core::task::TaskObj
  src/liballoc/boxed.rs
  src/libcore/task.rs
Labels: S-waiting-on-bors

#51542 Removed various update-reference and update-all-references scripts
  src/test/rustfix/update-all-references.sh
  src/test/rustfix/update-references.sh
  src/test/ui-fulldeps/update-all-references.sh
  src/test/ui-fulldeps/update-references.sh
  src/test/ui/update-all-references.sh
  src/test/ui/update-references.sh
Labels: S-waiting-on-bors

#51565 Fix the recent spurious breakage on AppVeyor.
  src/ci/docker/x86_64-gnu-tools/checktools.sh
Labels: S-waiting-on-bors

#50296 Add error message for using >= 65535 hashes for raw string literal escapes
  src/libsyntax/parse/lexer/mod.rs
Labels: S-waiting-on-bors, T-lang

#51462 Refactor: Rename ExistentialPredicate::cmp to ExistentialPredicate::stable_cmp
  src/librustc/ty/context.rs
  src/librustc/ty/sty.rs
  src/librustc_typeck/astconv.rs
Labels: S-waiting-on-bors

#51411 Speed up obligation forest code
  src/librustc/traits/fulfill.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_data_structures/obligation_forest/test.rs
Labels: S-waiting-on-bors

#51550 rustc: rename ty::maps to ty::query.
  src/README.md
  src/librustc/dep_graph/graph.rs
  src/librustc/hir/mod.rs
  src/librustc/lint/mod.rs
  src/librustc/middle/const_val.rs
  src/librustc/middle/reachable.rs
  src/librustc/middle/region.rs
  src/librustc/middle/resolve_lifetime.rs
  src/librustc/traits/mod.rs
  src/librustc/ty/context.rs
  src/librustc/ty/erase_regions.rs
  src/librustc/ty/layout.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/query/README.md
  src/librustc/ty/query/config.rs
  src/librustc/ty/query/job.rs
  src/librustc/ty/query/keys.rs
  src/librustc/ty/query/mod.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc/ty/query/plumbing.rs
  src/librustc/ty/query/values.rs
  src/librustc/ty/util.rs
  src/librustc_borrowck/borrowck/mod.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/back/symbol_export.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_codegen_utils/symbol_names.rs
  src/librustc_driver/driver.rs
  src/librustc_driver/test.rs
  src/librustc_incremental/persist/dirty_clean.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/lib.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_passes/lib.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_privacy/lib.rs
  src/librustc_traits/lib.rs
  src/librustc_typeck/check/method/mod.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/lib.rs
  src/librustc_typeck/outlives/mod.rs
  src/librustc_typeck/variance/mod.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: S-waiting-on-bors

#51562 Stabilize #[repr(transparent)]
  src/doc/unstable-book/src/language-features/repr-transparent.md
  src/liballoc/lib.rs
  src/libcore/lib.rs
  src/librustc/diagnostics.rs
  src/librustc_typeck/diagnostics.rs
  src/libsyntax/feature_gate.rs
  src/test/codegen/repr-transparent-aggregates-1.rs
  src/test/codegen/repr-transparent-aggregates-2.rs
  src/test/codegen/repr-transparent-aggregates-3.rs
  src/test/codegen/repr-transparent-sysv64.rs
  src/test/codegen/repr-transparent.rs
  src/test/compile-fail/repr-transparent-other-items.rs
  src/test/compile-fail/repr-transparent-other-reprs.rs
  src/test/compile-fail/repr-transparent.rs
  src/test/ui/feature-gate-repr_transparent.rs
  src/test/ui/feature-gate-repr_transparent.stderr
  src/test/ui/lint-ctypes.rs
Labels: S-waiting-on-bors, relnotes

#51591 Remove `?` macro separator compatibility note from 1.27 release notes
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#51593 [beta] Rollup backports
  RELEASES.md
Labels: S-waiting-on-bors

#51584 rustdoc: process cross-crate glob re-exports
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/inline_cross/auxiliary/cross-glob.rs
  src/test/rustdoc/inline_cross/cross-glob.rs
Labels: S-waiting-on-bors

#51558 Fix my comment on editions
  src/libsyntax_pos/edition.rs
Labels: S-waiting-on-bors

#51594 rustc_codegen_llvm: don't treat i1 as signed, even for #[repr(i8)] enums.
  src/librustc_codegen_llvm/mir/place.rs
  src/librustc_codegen_llvm/mir/rvalue.rs
  src/test/run-pass/issue-51582.rs
Labels: S-waiting-on-bors

#51466 Add Ref/RefMut map_split method
  src/libcore/cell.rs
  src/libcore/tests/cell.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-lang, T-libs

#51392 test: Ignore some problematic tests on powerpc and powerpc64*
  src/test/codegen/repr-transparent-aggregates-2.rs
  src/test/codegen/stack-probes.rs
  src/test/codegen/x86_mmx.rs
  src/test/compile-fail/asm-bad-clobber.rs
  src/test/compile-fail/asm-in-bad-modifier.rs
  src/test/compile-fail/asm-misplaced-option.rs
  src/test/compile-fail/asm-out-no-modifier.rs
  src/test/compile-fail/asm-out-read-uninit.rs
  src/test/compile-fail/borrowck/borrowck-asm.rs
  src/test/ui/asm-out-assign-imm.rs
  src/test/ui/asm-out-assign-imm.stderr
  src/test/ui/target-feature-wrong.rs
  src/test/ui/target-feature-wrong.stderr
Labels: S-waiting-on-bors

#51549 Follow up to #51508, make parse_block public instead parse_block_expr
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51552 Minor language change to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#51555 Removed two unused variables in os.rs
  src/libstd/sys/redox/os.rs
Labels: S-waiting-on-bors

#51404 impl Hash for !
  src/libcore/hash/mod.rs
Labels: S-waiting-on-bors, T-libs

#51605 Fixed minor error in Compiler Error Index, E0603.
  src/librustc_resolve/diagnostics.rs
Labels: S-waiting-on-bors

#50894 Stabilize std::path::Path::ancestors
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#51620 Stable release 1.27.0
  src/ci/run.sh
  src/stage0.txt
Labels: S-waiting-on-bors

#51627 Dummy commit to attempt to recreate prerelease artifacts
  src/stage0.txt
Labels: S-waiting-on-bors, S-waiting-on-review

#50383 Add ability to apply custom derive to union types.
  src/libsyntax_ext/deriving/custom.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/derive-union.rs
  src/test/run-pass-fulldeps/proc-macro/derive-union.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period

#51081 Use String, not &str in some collection examples
  src/libstd/collections/hash/map.rs
  src/libstd/collections/hash/set.rs
Labels: S-waiting-on-bors, T-doc

#51367 Use quiet tests by default
  config.toml.example
  src/bootstrap/config.rs
  src/bootstrap/configure.py
  src/bootstrap/test.rs
  src/ci/run.sh
Labels: S-waiting-on-bors

#51543 Rename OOM to allocation error
  src/liballoc/alloc.rs
  src/liballoc/arc.rs
  src/liballoc/raw_vec.rs
  src/liballoc/rc.rs
  src/libcore/alloc.rs
  src/libstd/alloc.rs
  src/libstd/collections/hash/table.rs
  src/test/run-pass/allocator-alloc-one.rs
  src/test/run-pass/realloc-16687.rs
  src/test/run-pass/regions-mock-codegen.rs
Labels: A-allocators, P-high, S-waiting-on-bors, T-libs, disposition-merge, final-comment-period

#51631 Fix links in RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors, T-release

#51644 Remove erroneous example of main as a non-Result function.
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#51651 Fix variable name in E0502 double borrow error
  src/librustc_mir/borrow_check/error_reporting.rs
  src/test/ui/nll/issue-51268.rs
  src/test/ui/nll/issue-51268.stderr
Labels: S-waiting-on-bors

#51601 Specialize StepBy<Range(Inclusive)>
  src/libcore/iter/mod.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#51686 yet another "old borrowck" bug around match default bindings
  src/librustc/middle/expr_use_visitor.rs
  src/librustc/middle/mem_categorization.rs
  src/test/ui/borrowck/issue-51415.nll.stderr
  src/test/ui/borrowck/issue-51415.rs
  src/test/ui/borrowck/issue-51415.stderr
Labels: S-waiting-on-bors

#51158 Mention spec and indented blocks in doctest docs
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#51629 Do not consume semicolon twice while parsing local statement
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51637 Update zx_cprng_draw_new on Fuchsia
  src/libstd/sys/unix/rand.rs
Labels: S-waiting-on-bors

#51664 make more libsyntax methods public
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51666 Disable probestack when GCOV profiling is being used
  src/librustc_codegen_llvm/attributes.rs
Labels: S-waiting-on-bors

#51703 Recognize the extra "LLVM tools versions" argument to build-manifest.
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#51681 Support future deprecation for rustc_deprecated
  src/librustc/middle/stability.rs
  src/test/compile-fail/auxiliary/lint_stability.rs
  src/test/compile-fail/lint-stability.rs
Labels: S-waiting-on-bors

#51482 Greatly improve tables display in docs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#51697 Add label to lint for lifetimes used once
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/single-use-lifetime/fn-types.stderr
  src/test/ui/single-use-lifetime/one-use-in-fn-argument-in-band.stderr
  src/test/ui/single-use-lifetime/one-use-in-fn-argument.stderr
  src/test/ui/single-use-lifetime/one-use-in-inherent-impl-header.stderr
  src/test/ui/single-use-lifetime/one-use-in-inherent-method-argument.stderr
  src/test/ui/single-use-lifetime/one-use-in-inherent-method-return.stderr
  src/test/ui/single-use-lifetime/one-use-in-trait-method-argument.stderr
  src/test/ui/single-use-lifetime/two-uses-in-inherent-method-argument-and-return.stderr
Labels: S-waiting-on-bors

#51724 Re-pub some items whose visibilities were recently reduced.
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#51696 Accept `TyError` in patterns to avoid ICE on bad input
  src/librustc_mir/hair/pattern/mod.rs
  src/test/ui/issue-50585.rs
  src/test/ui/issue-50585.stderr
Labels: S-waiting-on-bors

#51723 Accept `TyError` in `analyze_closure` to avoid ICE
  src/librustc_typeck/check/upvar.rs
  src/test/ui/issue-51714.rs
  src/test/ui/issue-51714.stderr
Labels: S-waiting-on-bors

#51653 Option::get_or_insert(_with): Replace unreachable! with unreachable_unchecked
  src/libcore/option.rs
Labels: S-waiting-on-bors

#51740 Fix error code numbers
  src/librustc/diagnostics.rs
  src/librustc/hir/lowering.rs
  src/test/ui/async-fn-multiple-lifetimes.stderr
  src/test/ui/no-args-non-move-async-closure.stderr
Labels: S-waiting-on-bors

#51733 Fix an ICE when matching over const slices
  src/librustc_mir/hair/pattern/_match.rs
  src/test/run-pass/issue-51655.rs
Labels: S-waiting-on-bors

#51785 Use fstatat64 where available
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors, T-libs, beta-accepted

#51790 [beta] Rollup backports
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#50630 Fix possibly endless loop in ReadDir iterator
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#51613 Obligation forest cleanup
  src/librustc_data_structures/obligation_forest/mod.rs
Labels: S-waiting-on-bors

#51104 add `dyn ` to display of dynamic (trait) types
  src/librustc/util/ppaux.rs
  src/test/compile-fail/cross-borrow-trait.rs
  src/test/compile-fail/destructure-trait-ref.rs
  src/test/compile-fail/dst-bad-assign-3.rs
  src/test/compile-fail/dst-bad-assign.rs
  src/test/compile-fail/fn-trait-formatting.rs
  src/test/compile-fail/issue-13033.rs
  src/test/compile-fail/issue-20939.rs
  src/test/compile-fail/issue-32963.rs
  src/test/compile-fail/issue-41139.rs
  src/test/compile-fail/issue-5153.rs
  src/test/compile-fail/kindck-send-object.rs
  src/test/compile-fail/kindck-send-object1.rs
  src/test/compile-fail/kindck-send-object2.rs
  src/test/compile-fail/map-types.rs
  src/test/compile-fail/non-interger-atomic.rs
  src/test/compile-fail/object-does-not-impl-trait.rs
  src/test/compile-fail/object-safety-by-value-self-use.rs
  src/test/compile-fail/privacy/associated-item-privacy-type-binding.rs
  src/test/compile-fail/private-inferred-type.rs
  src/test/compile-fail/trait-item-privacy.rs
  src/test/compile-fail/traits-repeated-supertrait-ambig.rs
  src/test/compile-fail/trivial_casts.rs
  src/test/compile-fail/type-mismatch-same-crate-name.rs
  src/test/compile-fail/type-parameter-defaults-referencing-Self-ppaux.rs
  src/test/run-pass/issue-21058.rs
  src/test/ui/anonymous-higher-ranked-lifetime.stderr
  src/test/ui/arbitrary-self-types-not-object-safe.stderr
  src/test/ui/cast-to-unsized-trait-object-suggestion.stderr
  src/test/ui/const-unsized.stderr
  src/test/ui/did_you_mean/bad-assoc-ty.stderr
  src/test/ui/error-codes/E0033-teach.stderr
  src/test/ui/error-codes/E0033.stderr
  src/test/ui/error-codes/E0657.stderr
  src/test/ui/fat-ptr-cast.stderr
  src/test/ui/feature-gate-trivial_bounds.stderr
  src/test/ui/fmt/send-sync.stderr
  src/test/ui/in-band-lifetimes/impl/dyn-trait.stderr
  src/test/ui/in-band-lifetimes/mismatched_trait_impl-2.stderr
  src/test/ui/issue-17441.rs
  src/test/ui/issue-17441.stderr
  src/test/ui/issue-20692.stderr
  src/test/ui/lint-ctypes.rs
  src/test/ui/lint-ctypes.stderr
  src/test/ui/lub-glb/old-lub-glb-object.stderr
  src/test/ui/mismatched_types/cast-rfc0401.stderr
  src/test/ui/mismatched_types/issue-19109.stderr
  src/test/ui/mismatched_types/trait-bounds-cant-coerce.stderr
  src/test/ui/nll/ty-outlives/projection-no-regions-closure.stderr
  src/test/ui/nll/ty-outlives/ty-param-closure-outlives-from-return-type.stderr
  src/test/ui/resolve/issue-5035-2.stderr
  src/test/ui/span/borrowck-object-mutability.nll.stderr
  src/test/ui/suggestions/confuse-field-and-method/issue-2392.stderr
  src/test/ui/trivial-bounds-inconsistent-sized.stderr
  src/test/ui/trivial-bounds-inconsistent.stderr
  src/test/ui/underscore-lifetime/dyn-trait-underscore.stderr
  src/test/ui/unsized-enum2.stderr
Labels: S-waiting-on-bors

#51153 Link panic and compile_error docs
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#51642 Fix unknown windows build
  src/libstd/sys/mod.rs
Labels: S-waiting-on-bors

#51730 New safe associated functions for PinMut
  src/libcore/mem.rs
  src/libcore/option.rs
  src/libstd/future.rs
  src/libstd/panic.rs
Labels: S-waiting-on-bors

#51769 Update broken rustc-guide links
  src/librustc/infer/canonical.rs
  src/librustc/infer/higher_ranked/mod.rs
  src/librustc/infer/lexical_region_resolve/README.md
  src/librustc/infer/region_constraints/README.md
  src/librustc/middle/region.rs
  src/librustc/mir/mod.rs
  src/librustc/traits/coherence.rs
  src/librustc/traits/mod.rs
  src/librustc/traits/select.rs
  src/librustc/traits/specialize/mod.rs
  src/librustc/ty/sty.rs
  src/librustc_borrowck/borrowck/README.md
Labels: S-waiting-on-bors

#51786 Remove unnecessary stat64 pointer casts
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#51788 Fix typo
  src/libsyntax_pos/hygiene.rs
Labels: S-waiting-on-bors

#51789 Don't ICE when performing `lower_pattern_unadjusted` on a `TyError`
  src/librustc_mir/hair/pattern/mod.rs
  src/test/ui/issue-50577.rs
  src/test/ui/issue-50577.stderr
Labels: S-waiting-on-bors

#51791 Minify css
  src/Cargo.lock
  src/librustdoc/Cargo.toml
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#51678 Combine all builtin late lints
  src/librustc/lint/context.rs
  src/librustc/lint/mod.rs
  src/librustc_lint/lib.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors

#51725 Do not build LLVM tools for any of the tools
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#51756 Haiku: set stack size to 16 MB on Haiku, use 32 MB on other platforms
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors

#51773 Don't inspect the generated existential type items
  src/librustc_typeck/collect.rs
  src/test/ui/error-codes/E0657.rs
  src/test/ui/error-codes/E0657.stderr
  src/test/ui/impl-trait/auto-trait-leak.rs
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/impl_trait_projections.rs
  src/test/ui/impl_trait_projections.stderr
Labels: S-waiting-on-bors

#51598 Optimize sum of Durations by using custom function
  src/libcore/tests/time.rs
  src/libcore/time.rs
Labels: S-waiting-on-bors

#51835 Stabilize to_bytes and from_bytes for integers.
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, relnotes

#51356 Make opaque::Encoder append-only and make it infallible
  src/librustc/ich/fingerprint.rs
  src/librustc/ty/codec.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc_codegen_llvm/back/wasm.rs
  src/librustc_incremental/persist/file_format.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_metadata/encoder.rs
  src/librustc_metadata/index.rs
  src/libserialize/leb128.rs
  src/libserialize/lib.rs
  src/libserialize/opaque.rs
  src/test/run-pass-fulldeps/issue-11881.rs
Labels: S-waiting-on-bors, S-waiting-on-perf

#51850 [fuchsia] Update zx_cprng_draw to target semantics
  src/libstd/sys/unix/rand.rs
Labels: S-waiting-on-bors

#51852 Don't use `ParamEnv::reveal_all()` if there is a real one available
  src/librustc_mir/interpret/const_eval.rs
  src/test/ui/const-eval/ice-generic-assoc-const.rs
Labels: S-waiting-on-bors, beta-nominated

#49987 Add str::split_ascii_whitespace.
  src/liballoc/lib.rs
  src/liballoc/str.rs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, T-libs

#51658 Only do sanity check with debug assertions on
  src/librustc/traits/query/normalize.rs
Labels: S-waiting-on-bors

#51799 Lower case some feature gate error messages
  src/libsyntax/feature_gate.rs
  src/test/compile-fail-fulldeps/proc-macro/macros-in-extern.rs
  src/test/compile-fail/macros-in-extern.rs
  src/test/ui/feature-gate-macro_at_most_once_rep.rs
  src/test/ui/feature-gate-macro_at_most_once_rep.stderr
  src/test/ui/feature-gate-macros_in_extern.rs
  src/test/ui/feature-gate-macros_in_extern.stderr
  src/test/ui/feature-gate-unsized_tuple_coercion.rs
  src/test/ui/feature-gate-unsized_tuple_coercion.stderr
Labels: S-waiting-on-bors

#51800 Add a compiletest header for edition
  src/test/compile-fail/edition-raw-pointer-method-2015.rs
  src/test/compile-fail/edition-raw-pointer-method-2018.rs
  src/test/compile-fail/rfc-2126-extern-absolute-paths/non-existent-1.rs
  src/test/compile-fail/rfc-2126-extern-absolute-paths/non-existent-2.rs
  src/test/compile-fail/rfc-2126-extern-absolute-paths/non-existent-3.rs
  src/test/compile-fail/rfc-2126-extern-absolute-paths/single-segment.rs
  src/test/run-pass/async-await.rs
  src/test/run-pass/auxiliary/edition-kw-macro-2015.rs
  src/test/run-pass/auxiliary/edition-kw-macro-2018.rs
  src/test/run-pass/edition-keywords-2015-2015.rs
  src/test/run-pass/edition-keywords-2015-2018.rs
  src/test/run-pass/edition-keywords-2018-2015.rs
  src/test/run-pass/edition-keywords-2018-2018.rs
  src/test/run-pass/rfc-2126-extern-absolute-paths/basic.rs
  src/test/run-pass/rfc-2126-extern-absolute-paths/test.rs
  src/test/ui/async-fn-multiple-lifetimes.rs
  src/test/ui/auxiliary/edition-kw-macro-2015.rs
  src/test/ui/auxiliary/edition-kw-macro-2018.rs
  src/test/ui/edition-keywords-2015-2015-expansion.rs
  src/test/ui/edition-keywords-2015-2015-parsing.rs
  src/test/ui/edition-keywords-2015-2018-expansion.rs
  src/test/ui/edition-keywords-2015-2018-parsing.rs
  src/test/ui/edition-keywords-2018-2015-expansion.rs
  src/test/ui/edition-keywords-2018-2015-parsing.rs
  src/test/ui/edition-keywords-2018-2018-expansion.rs
  src/test/ui/edition-keywords-2018-2018-parsing.rs
  src/test/ui/feature-gate-async-await-2015-edition.rs
  src/test/ui/feature-gate-async-await.rs
  src/test/ui/feature-gate-async-await.stderr
  src/test/ui/lint-anon-param-edition.fixed
  src/test/ui/lint-anon-param-edition.rs
  src/test/ui/no-args-non-move-async-closure.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#51824 Fix the error reference for LocalKey::try_with
  src/libstd/thread/local.rs
Labels: S-waiting-on-bors

#51842 Document that Layout::from_size_align does not allow align=0
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#51630 Optimize RefCell refcount tracking
  src/libcore/cell.rs
  src/test/compile-fail/not-panic-safe-2.rs
  src/test/compile-fail/not-panic-safe-3.rs
  src/test/compile-fail/not-panic-safe-4.rs
  src/test/compile-fail/not-panic-safe-6.rs
Labels: S-waiting-on-bors

#51765 Use assert_eq! in copy_from_slice
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#51822 Provide existing ref suggestions for more E0308 errors
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/suggestions/str-array-assignment.stderr
Labels: S-waiting-on-bors

#51839 Detect overflows of non u32 shifts
  src/librustc_mir/interpret/operator.rs
  src/test/ui/const-eval/shift_overflow.rs
  src/test/ui/const-eval/shift_overflow.stderr
Labels: S-waiting-on-bors
