Repository rust-lang/rust, pull requests merged in 2018-02, with the labels that each got.

#47790 derive PartialEq and Eq for `ParseCharError`
  src/libcore/char.rs
Labels: S-waiting-on-bors, T-libs

#47854 Create a directory for --out-dir if it does not already exist
  src/librustc_driver/driver.rs
Labels: S-waiting-on-bors, T-compiler

#48047 Fix ICE for mismatched args on target without span
  src/librustc/traits/error_reporting.rs
  src/test/ui/mismatched_types/closure-arg-count.rs
  src/test/ui/mismatched_types/closure-arg-count.stderr
Labels: S-waiting-on-bors

#48051 rustdoc: Hide `-> ()` in cross crate inlined Fn* bounds
  src/librustdoc/clean/simplify.rs
  src/test/rustdoc/auxiliary/unit-return.rs
  src/test/rustdoc/unit-return.rs
Labels: S-waiting-on-bors

#48059 rustbuild: Pass `ccache` to build scripts
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#48064 intra-doc-links: bail early for linky things
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors

#48080 Hide theme button under menu in mobile mode and fix top margin issue …
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#48086 Fix visitation order of calls so that it matches execution order. Fixes #48048
  src/librustc/hir/intravisit.rs
  src/test/ui/generator/issue-48048.rs
  src/test/ui/generator/issue-48048.stderr
Labels: S-waiting-on-author

#48098 ci: Actually bootstrap on i686 dist
  src/bootstrap/dist.rs
  src/ci/docker/dist-i686-linux/Dockerfile
Labels: S-waiting-on-bors

#48100 Add fetch_nand to atomics
  src/libcore/sync/atomic.rs
  src/libcore/tests/atomic.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors

#48107 fix typo: substract -> subtract
  src/libcore/ops/arith.rs
  src/test/ui/mismatched_types/binops.rs
  src/test/ui/mismatched_types/binops.stderr
Labels: S-waiting-on-bors

#48120 fix typos in src/{bootstrap,ci,etc,lib{backtrace,core,fmt_macros}}
  src/bootstrap/builder.rs
  src/bootstrap/lib.rs
  src/bootstrap/test.rs
  src/ci/docker/dist-x86_64-netbsd/build-netbsd-toolchain.sh
  src/etc/installer/msi/rust.wxs
  src/etc/platform-intrinsics/generator.py
  src/etc/test-float-parse/runtests.py
  src/libbacktrace/ltmain.sh
  src/libbacktrace/macho.c
  src/libcore/macros.rs
  src/libfmt_macros/lib.rs
Labels: S-waiting-on-bors

#48124 Explain unusual debugging code in librustc
  src/librustc_resolve/resolve_imports.rs
Labels: S-waiting-on-bors

#47286 Update RELEASES.md for 1.24.0
  RELEASES.md
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#47657 Emit data::Impl in save-analysis
  src/Cargo.lock
  src/librustc_save_analysis/Cargo.toml
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/json_dumper.rs
  src/librustc_save_analysis/lib.rs
Labels: S-waiting-on-bors

#47614 Fix oversized loads on x86_64 SysV FFI calls
  src/librustc_trans/cabi_x86_64.rs
  src/test/codegen/abi-x86_64_sysv.rs
  src/test/codegen/repr-transparent-sysv64.rs
  src/test/codegen/repr-transparent.rs
Labels: S-waiting-on-bors

#48144 Compiletest: delete the compiled program once its test is done.
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#48161 Prepare stable release for 1.24.0
  src/ci/run.sh
Labels: S-waiting-on-review

#47804 Optimized error reporting for recursive requirements #47720
  src/librustc/traits/error_reporting.rs
  src/test/ui/recursive-requirements.rs
  src/test/ui/recursive-requirements.stderr
Labels: S-waiting-on-bors, T-compiler

#47784 rustc: Add the ability to not run dsymutil
  src/librustc/session/config.rs
  src/librustc_trans/back/link.rs
Labels: S-waiting-on-bors

#47846 Work around LLVM OCAML binding installation failure
  src/bootstrap/native.rs
Labels: A-rustbuild, S-waiting-on-bors

#48005 Unimplement Send/Sync for ::env::{Args,ArgsOs,Vars,VarsOs}
  src/libstd/env.rs
Labels: S-waiting-on-bors, T-libs

#48033 Show better warning for trying to cast non-u8 scalar to char
  src/librustc_lint/types.rs
  src/test/ui/cast_char.rs
  src/test/ui/cast_char.stderr
Labels: S-waiting-on-bors

#48035 Early exit for empty HashMap (issue #38880)
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#48065 Apply optimization from #44355 to retain
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#48114 Upgrade the Travis CI macOS images for testing from Xcode 8.3 to 9.2.
  .travis.yml
Labels: S-waiting-on-bors

#48130 Correct a few stability attributes
  src/libcore/num/mod.rs
  src/libcore/ptr.rs
  src/libcore/time.rs
  src/libstd/io/cursor.rs
  src/libstd/path.rs
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-author

#48133 typo: correct endianess to endianness (this also changes function names!)
  src/librustc_mir/interpret/memory.rs
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-author

#48151 Update ops range example to avoid confusion between indexes and values.
  src/libcore/ops/range.rs
Labels: S-waiting-on-bors

#48154 Continue parsing function after finding `...` arg
  src/libsyntax/parse/parser.rs
  src/test/ui/invalid-variadic-function.rs
  src/test/ui/invalid-variadic-function.stderr
Labels: S-waiting-on-bors

#48162 Handle path prefix mapping in a more stable way when computing the crate hash
  src/librustc/hir/map/collector.rs
  src/librustc/hir/map/mod.rs
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#48163 rustc: Persist LLVM's `Linker` in Fat LTO
  src/librustc_llvm/build.rs
  src/librustc_llvm/ffi.rs
  src/librustc_trans/back/lto.rs
  src/rustllvm/Linker.cpp
  src/rustllvm/RustWrapper.cpp
Labels: S-waiting-on-bors

#48165 Update compiletest's `read2` function
  src/tools/compiletest/src/read2.rs
Labels: S-waiting-on-bors

#48167 Remove allocation from width of character function.
  src/libsyntax/codemap.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#48181 incr.comp.: Run cache directory garbage collection before loading dep-graph.
  src/librustc_driver/driver.rs
  src/librustc_incremental/lib.rs
  src/librustc_incremental/persist/fs.rs
  src/librustc_incremental/persist/mod.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#48186 Add note about Cargo cwd change to release notes
  RELEASES.md
Labels: S-waiting-on-bors

#48210 Clarified why `Sized` bound not implicit on trait's implicit `Self` type.
  src/libcore/marker.rs
Labels: S-waiting-on-bors

#47906 Add a `fatal_cycle` attribute for queries which indicates that they will cause a fatal error on query cycles
  src/librustc/ty/maps/mod.rs
  src/librustc/ty/maps/plumbing.rs
Labels: S-waiting-on-bors, T-compiler

#47926 add transform for uniform array move out
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/uniform_array_move_out.rs
  src/librustc_mir/util/patch.rs
  src/test/compile-fail/borrowck/borrowck-move-out-from-array.rs
  src/test/mir-opt/uniform_array_move_out.rs
  src/test/run-pass/dynamic-drop.rs
Labels: S-waiting-on-bors

#47956 This is the ideal FileType on Windows. You may not like it, but this is what peak performance looks like.
  src/libstd/sys/windows/ext/fs.rs
  src/libstd/sys/windows/fs.rs
Labels: I-nominated, O-windows, S-waiting-on-bors, T-libs

#48234 Remove "empty buffer" doc in read_until
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#48239 Fix condvar example
  src/libstd/sync/condvar.rs
Labels: S-waiting-on-bors

#48243 spelling fix in comment
  src/libcore/str/pattern.rs
Labels: S-waiting-on-bors

#48260 [doc] Add link to yield_now
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#48284 Remove unneeded string allocations
  src/libsyntax/codemap.rs
Labels: S-waiting-on-bors

#48286 Clarify contiguity of Vec's elements.
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#47408 Don't promote to 'static the result of dereferences.
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_passes/consts.rs
Labels: I-nominated, S-waiting-on-bors, T-lang, final-comment-period, relnotes

#47544 Relax termination_trait's error bound
  src/libstd/termination.rs
  src/test/compile-fail/rfc-1937-termination-trait/termination-trait-main-wrong-type.rs
  src/test/compile-fail/rfc-1937-termination-trait/termination-trait-not-satisfied.rs
  src/test/run-fail/rfc-1937-termination-trait/termination-trait-for-result-box-error_err.rs
  src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-empty.rs
  src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-i32.rs
  src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-result-box-error_ok.rs
  src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-result.rs
  src/test/run-pass/termination-trait-for-result-box-error_ok.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#48194 Doc test command
  src/bootstrap/flags.rs
  src/bootstrap/lib.rs
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#48273 Add a warning to File about mutability.
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#48282 Fix spelling in core::iter::repeat_with: s/not/note
  src/libcore/iter/sources.rs
Labels: S-waiting-on-bors, T-doc

#48312 Unify 'Platform-specific behavior' documentation headings.
  src/libstd/net/tcp.rs
  src/libstd/net/udp.rs
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#47379 Derive std::cmp::Reverse as Copy or Clone
  src/libcore/cmp.rs
Labels: S-waiting-on-bors, T-libs, final-comment-period, relnotes

#48314 Fix broken documentation link.
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors

#48325 Mark doc examples w/ `extern` blocks as `ignore`.
  src/libstd/ffi/c_str.rs
Labels: I-nominated, S-waiting-on-bors

#48352 Update .mailmap with my real name
  .mailmap
Labels: S-waiting-on-bors

#48354 Add missing link for read_line
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#48360 Fix count usize link typo in docs
  src/libcore/iter/iterator.rs
Labels: S-waiting-on-bors

#48382 Fix rustdoc test ICE
  src/librustdoc/html/markdown.rs
  src/test/rustdoc/issue-48377.rs
Labels: S-waiting-on-bors, beta-nominated

#48397 Take 2^5 as examples in document of pow()
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, T-doc

#48487 Split MinGW tests into two builders on AppVeyor
  appveyor.yml
Labels: S-waiting-on-bors

#47933 Do not run the default panic hook inside procedural macros.
  src/Cargo.lock
  src/libproc_macro/lib.rs
  src/librustc/Cargo.toml
  src/librustc/lib.rs
  src/librustc/util/common.rs
  src/librustc_driver/driver.rs
  src/test/ui-fulldeps/proc-macro/load-panic.rs
  src/test/ui-fulldeps/proc-macro/load-panic.stderr
Labels: S-waiting-on-bors

#48072 Fix nested impl trait lifetimes
  src/librustc/middle/resolve_lifetime.rs
  src/test/run-pass/impl-trait/lifetimes.rs
Labels: S-waiting-on-bors

#48123 detect wrong number of args when type-checking a closure
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/mod.rs
  src/librustc_typeck/check/closure.rs
  src/test/ui/mismatched_types/closure-arg-count-expected-type-issue-47244.rs
  src/test/ui/mismatched_types/closure-arg-count-expected-type-issue-47244.stderr
Labels: S-waiting-on-bors

#48157 Add Iterator::try_for_each
  src/libcore/iter/iterator.rs
Labels: S-waiting-on-bors, T-libs

#48219 lookup exported symbols only when needed.
  src/librustc_trans/back/lto.rs
  src/librustc_trans/back/write.rs
Labels: S-waiting-on-bors

#48429 update tracking issue for nll
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#48436 Small grammar fix to docs for String::new()
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#48438 [docs] Minor wording changes to drain_filter docs
  src/liballoc/linked_list.rs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#48185 incr.comp.: Don't keep RefCells in on-disk-cache borrowed in order to allow for recursive invocations.
  src/librustc/ty/maps/on_disk_cache.rs
Labels: S-waiting-on-bors

#48206 incr.comp.: Store DepNode colors in a dense array instead of a hashmap.
  src/librustc/dep_graph/graph.rs
  src/librustc/dep_graph/prev.rs
  src/librustc/ty/maps/plumbing.rs
Labels: S-waiting-on-bors

#48232 mir: Gather move at SwitchInt, Assert terminators
  src/librustc_mir/dataflow/move_paths/builder.rs
Labels: S-waiting-on-bors

#48246 Avoid ICE in arg mistmatch error for tuple variants
  src/librustc/traits/error_reporting.rs
  src/test/ui/issue-47706.rs
  src/test/ui/issue-47706.stderr
Labels: S-waiting-on-bors

#48258 save-analysis: power through bracket mis-counts
  src/librustc_save_analysis/span_utils.rs
Labels: S-waiting-on-bors

#48317 unused_unsafe: don't label irrelevant fns
  src/librustc_mir/transform/check_unsafety.rs
  src/test/compile-fail/issue-48131.rs
Labels: S-waiting-on-bors

#48356 When encountering invalid token after `unsafe`, mention `{`
  src/libsyntax/parse/parser.rs
  src/test/ui/unsafe-block-without-braces.rs
  src/test/ui/unsafe-block-without-braces.stderr
Labels: S-waiting-on-bors

#48402 rustc_data_structures: add missing #[inline].
  src/librustc_data_structures/bitslice.rs
  src/librustc_data_structures/indexed_vec.rs
Labels: S-waiting-on-bors

#47689 Fix borrow checker unsoundness with unions
  src/test/ui/issue-45157.rs
  src/test/ui/issue-45157.stderr
Labels: S-waiting-on-bors

#48110 Stabilize Box::leak
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors, T-libs, final-comment-period, relnotes

#48392 Handle custom diagnostic for `&str + String`
  src/librustc_typeck/check/op.rs
  src/test/ui/span/issue-39018.rs
  src/test/ui/span/issue-39018.stderr
Labels: S-waiting-on-bors

#48441 Fix parsing of extern paths in types and poly-traits
  src/libsyntax/parse/parser.rs
  src/test/run-pass/rfc-2126-extern-absolute-paths/auxiliary/xcrate.rs
  src/test/run-pass/rfc-2126-extern-absolute-paths/extern.rs
Labels: S-waiting-on-bors

#48448 reset default binding mode when we pass through a `&` pattern
  src/librustc_typeck/check/_match.rs
  src/test/run-pass/rfc-2005-default-binding-mode/reset-mode.rs
Labels: S-waiting-on-bors

#48490 Implement multiple patterns with `|` in `if let` and `while let` (RFC 2175)
  src/librustc/hir/lowering.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/libsyntax/ast.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/visit.rs
  src/test/run-pass/rfc-2175-or-if-while-let/basic.rs
  src/test/ui/feature-gate-if_while_or_patterns.rs
  src/test/ui/feature-gate-if_while_or_patterns.stderr
Labels: S-waiting-on-bors

#48499 Fix capitalisation in Path#file_name's docs
  src/libstd/path.rs
Labels: S-waiting-on-bors

#48503 Remove directory `src/rt`
  src/bootstrap/native.rs
  src/test/auxiliary/rust_test_helpers.c
Labels: S-waiting-on-bors

#47970 Add Condvar APIs not susceptible to spurious wake
  src/libstd/sync/condvar.rs
Labels: S-waiting-on-bors, T-libs

#48235 Make ".e0" not parse as 0.0
  src/libcore/num/dec2flt/parse.rs
  src/libcore/tests/num/dec2flt/mod.rs
Labels: S-waiting-on-bors, T-libs, final-comment-period, relnotes

#48281 Add powerpc-unknown-netbsd target
  src/bootstrap/native.rs
  src/librustc_back/target/mod.rs
  src/librustc_back/target/powerpc_unknown_netbsd.rs
Labels: S-waiting-on-bors

#48302 Move macro-at-most-once-rep-ambig test to ui test
  src/test/ui/macros/macro-at-most-once-rep-ambig.rs
  src/test/ui/macros/macro-at-most-once-rep-ambig.stderr
Labels: S-waiting-on-bors

#48362 rustbuild: Restore Config.libdir_relative
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#48369 Rename rdrnd target feature to rdrand
  src/librustc_trans/llvm_util.rs
Labels: S-waiting-on-bors

#48489 bootstrap: Add openssl configuration for x86_64-unknown-linux-gnux32
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#48491 test: Fix s390x-unknown-linux-gnu atomic-lock-free test not run for systemz
  src/test/run-make/atomic-lock-free/Makefile
Labels: S-waiting-on-bors

#48494 Workaround abort(2) on compilation error on FreeBSD.
  src/librustc_back/target/freebsd_base.rs
Labels: S-waiting-on-bors

#48517 Added error-format flag to x.py.
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#48529 Fixes docs for ASCII functions to no longer claim U+0021 is '@'.
  src/libcore/num/mod.rs
  src/libstd/ascii.rs
  src/libstd_unicode/char.rs
Labels: S-waiting-on-bors

#48455 [beta] Encode linker arguments as UTF-16 on MSVC platforms
  src/librustc_trans/back/link.rs
  src/test/run-make/long-linker-command-lines-cmd-exe/foo.rs
  src/test/run-make/long-linker-command-lines/foo.rs
Labels: S-waiting-on-bors

#48379 [beta] temporarily disable rust-lang/rust#46833 due to rust-lang/rust#48251
  src/librustc_mir/build/mod.rs
  src/test/run-pass/abort-on-c-abi.rs
Labels: S-waiting-on-review

#48454 [beta] Backport "Fix rustdoc test ICE"
  src/librustdoc/html/markdown.rs
  src/test/rustdoc/issue-48377.rs
Labels: S-waiting-on-review

#48576 Bring back ParamEnv deduplication
  src/librustc/traits/project.rs
Labels: S-waiting-on-bors

#48266 Report non-standard compile flags on ICE
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#48321 Add non-panicking variants of pow for integer types
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, T-libs

#48365 RefCell: document panics in Clone, PartialEq, PartialOrd, Ord.
  src/libcore/cell.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#48450 Stabilize [T]::rotate_{left,right}
  src/liballoc/benches/lib.rs
  src/liballoc/lib.rs
  src/liballoc/slice.rs
  src/liballoc/tests/lib.rs
  src/libcore/slice/mod.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, final-comment-period, relnotes

#48473 Fix auto trait impl rustdoc ice
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/auto-impl-for-trait.rs
Labels: S-waiting-on-bors

#48488 Handle gdb command failure gracefully in compiletest
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors

#48497 Restrict the Termination impls to simplify stabilization
  src/libstd/process.rs
  src/test/run-pass/rfc-1937-termination-trait/termination-trait-for-exitcode.rs
Labels: S-waiting-on-bors

#48541 Ensure main() always has external linkage
  src/librustc_mir/monomorphize/item.rs
  src/test/run-pass/inlined-main.rs
Labels: S-waiting-on-bors

#48548 Encode linker arguments as UTF-16 on MSVC platforms
  src/librustc_trans/back/link.rs
  src/test/run-make/long-linker-command-lines-cmd-exe/foo.rs
  src/test/run-make/long-linker-command-lines/foo.rs
Labels: S-waiting-on-bors

#48558 Fix error-format to properly send JSON to stdout
  src/bootstrap/compile.rs
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#48565 rustc: Rename `bmi` feature to `bmi1`
  src/librustc_trans/llvm_util.rs
Labels: S-waiting-on-bors
