Repository rust-lang/rust, pull requests merged in 2018-09, with the labels that each got.

#53755 fix u32 steps_between for 16-bit systems
  src/libcore/iter/range.rs
  src/test/run-pass/issue-48006.rs
Labels: S-waiting-on-bors

#53622 cleanup: Add main functions to some UI tests
  src/test/ui/enum/enum-discrim-autosizing.rs
  src/test/ui/enum/enum-discrim-autosizing.stderr
  src/test/ui/gated-bad-feature.rs
  src/test/ui/gated-bad-feature.stderr
  src/test/ui/hygiene/generate-mod.rs
  src/test/ui/hygiene/generate-mod.stderr
  src/test/ui/hygiene/no_implicit_prelude.rs
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/imports/import-glob-circular.rs
  src/test/ui/imports/import-glob-circular.stderr
  src/test/ui/imports/import-loop-2.rs
  src/test/ui/imports/import-loop-2.stderr
  src/test/ui/invalid_crate_type_syntax.rs
  src/test/ui/invalid_crate_type_syntax.stderr
  src/test/ui/issues/issue-38715.rs
  src/test/ui/issues/issue-38715.stderr
  src/test/ui/issues/issue-42755.rs
  src/test/ui/issues/issue-42755.stderr
  src/test/ui/issues/issue-43784-associated-type.rs
  src/test/ui/issues/issue-43784-associated-type.stderr
  src/test/ui/issues/issue-43784-supertrait.rs
  src/test/ui/issues/issue-43784-supertrait.stderr
  src/test/ui/macros/macro-use-bad-args-1.rs
  src/test/ui/macros/macro-use-bad-args-1.stderr
  src/test/ui/macros/macro-use-bad-args-2.rs
  src/test/ui/macros/macro-use-bad-args-2.stderr
  src/test/ui/nested-ty-params.rs
  src/test/ui/nested-ty-params.stderr
  src/test/ui/repr/repr-transparent-other-items.rs
  src/test/ui/repr/repr-transparent-other-items.stderr
  src/test/ui/repr/repr-transparent-other-reprs.rs
  src/test/ui/repr/repr-transparent-other-reprs.stderr
  src/test/ui/repr/repr-transparent.rs
  src/test/ui/repr/repr-transparent.stderr
  src/test/ui/resolve/resolve-unknown-trait.rs
  src/test/ui/resolve/resolve-unknown-trait.stderr
  src/test/ui/resolve_self_super_hint.rs
  src/test/ui/resolve_self_super_hint.stderr
  src/test/ui/specialization/defaultimpl/validation.rs
  src/test/ui/specialization/defaultimpl/validation.stderr
  src/test/ui/tuple/tuple-struct-fields/test.rs
  src/test/ui/tuple/tuple-struct-fields/test.stderr
  src/test/ui/unresolved/unresolved-import.rs
  src/test/ui/unresolved/unresolved-import.stderr
  src/test/ui/user-defined-macro-rules.rs
  src/test/ui/user-defined-macro-rules.stderr
  src/test/ui/wasm-custom-section-relocations.rs
  src/test/ui/wasm-custom-section-relocations.stderr
Labels: S-waiting-on-bors

#53769 Also link Clippy repo in the CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: S-waiting-on-author

#53774 Add rust-gdbgui script.
  src/etc/rust-gdbgui
Labels: S-waiting-on-bors

#53781 bench: libcore: fix build failure of any.rs benchmark (use "dyn Any")
  src/libcore/benches/any.rs
Labels: S-waiting-on-bors

#53782 Make Arc cloning mechanics clearer in module docs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#53790 Add regression test for issue #52060
  src/test/ui/issues/issue-52060.rs
  src/test/ui/issues/issue-52060.stderr
Labels: S-waiting-on-bors

#53801 Prevent duplicated impl on foreign types
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#53533 Add Error::source method per RFC 2504.
  src/libstd/error.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#53815 refactor match guard
  src/librustc/cfg/construct.rs
  src/librustc/hir/intravisit.rs
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/hir/print.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/middle/expr_use_visitor.rs
  src/librustc/middle/liveness.rs
  src/librustc/middle/region.rs
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_mir/hair/mod.rs
  src/librustc_mir/hair/pattern/check_match.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_typeck/check/_match.rs
  src/libsyntax/ast.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/visit.rs
Labels: S-waiting-on-bors

#53897 Replace check() + bump() with eat()
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#53599 use char pattern for single-character splits: a.split("x") -> a.split('x')
  src/libcore/str/mod.rs
  src/librustc_incremental/assert_module_sources.rs
  src/librustdoc/theme.rs
Labels: S-waiting-on-bors

#53725 Reduce number of syscalls in `rand`
  src/libstd/sys/unix/rand.rs
Labels: S-waiting-on-bors

#53838 save-analysis: record info for the types in `where` clauses
  src/librustc_save_analysis/dump_visitor.rs
Labels: S-waiting-on-bors

#53883 miri engine: make sure we do not copy unsized data
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#53927 A few cleanups and minor improvements to save_analysis
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/sig.rs
  src/librustc_save_analysis/span_utils.rs
Labels: S-waiting-on-bors

#53928 Link to more detailed docs in `slice::from_raw_parts_mut`
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#53952 [beta] update backtrace-sys to 0.1.24
  src/Cargo.lock
Labels: S-waiting-on-bors

#53944 [beta] Properly prevent the promotion of unstable const fns
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_passes/rvalue_promotion.rs
  src/test/ui/const-eval/dont_promote_unstable_const_fn.nll.stderr
  src/test/ui/const-eval/dont_promote_unstable_const_fn.rs
  src/test/ui/const-eval/dont_promote_unstable_const_fn.stderr
  src/test/ui/consts/const-eval/auxiliary/stability.rs
  src/test/ui/consts/const-eval/dont_promote_unstable_const_fn_cross_crate.nll.stderr
  src/test/ui/consts/const-eval/dont_promote_unstable_const_fn_cross_crate.rs
  src/test/ui/consts/const-eval/dont_promote_unstable_const_fn_cross_crate.stderr
Labels: S-waiting-on-bors

#53027 Allow to check if sync::Once is already initialized
  src/libstd/sync/once.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#53878 rustc: Prepare the `atomics` feature for wasm
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_target/spec/wasm32_unknown_unknown.rs
Labels: S-waiting-on-bors

#53962 ThinLTO: Don't keep files open after mmaping them.
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
Labels: S-waiting-on-bors

#53955 rustbuild: Tweak LLVM distribution layout
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#53707 rustc_typeck: turn `where Type:,` into a WF(Type) predicate, instead of ignoring it.
  src/librustc_typeck/collect.rs
  src/librustdoc/clean/mod.rs
  src/test/ui/chalkify/lower_trait_where_clause.rs
  src/test/ui/chalkify/lower_trait_where_clause.stderr
  src/test/ui/wf/wf-fn-where-clause.rs
  src/test/ui/wf/wf-fn-where-clause.stderr
Labels: S-waiting-on-bors

#53978 [beta]: Remove `#[repr(transparent)]` from atomics
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#54005 rustc_resolve: allow `use crate_name;` under `uniform_paths`.
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/resolve_imports.rs
  src/test/run-pass/redundant.rs
  src/test/ui/rust-2018/uniform-paths/redundant.stderr
Labels: S-waiting-on-bors

#54018 Ship libLLVM.dylib on OSX
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#53299 Updated core/macros.rs to note it works in a no_std environment.
  src/libcore/macros.rs
Labels: S-waiting-on-bors

#53376 Cross reference io::copy and fs::copy in docs.
  src/libstd/fs.rs
  src/libstd/io/util.rs
Labels: S-waiting-on-bors, T-doc

#53455 Individual docs for {from,to}_*_bytes
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#53550 librustc_lint: In recursion warning, change 'recurring' to 'recursing'
  src/doc/rustc/src/lints/listing/warn-by-default.md
  src/librustc_lint/builtin.rs
  src/test/ui/issues/issue-8727.rs
  src/test/ui/issues/issue-8727.stderr
  src/test/ui/lint/lint-unconditional-recursion.rs
  src/test/ui/lint/lint-unconditional-recursion.stderr
Labels: S-waiting-on-bors

#53946 Clarify `ManuallyDrop` docs
  src/libcore/mem.rs
Labels: S-waiting-on-bors

#53948 Minimized clippy test from when NLL disabled two-phase borrows
  src/test/ui/borrowck/two-phase-surprise-no-conflict.ast.stderr
  src/test/ui/borrowck/two-phase-surprise-no-conflict.nll.stderr
  src/test/ui/borrowck/two-phase-surprise-no-conflict.no2pb.stderr
  src/test/ui/borrowck/two-phase-surprise-no-conflict.rs
Labels: A-NLL, S-waiting-on-bors

#53966 A few cleanups and minor improvements to mir/dataflow
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_mir/dataflow/impls/borrows.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
Labels: S-waiting-on-bors

#53967 propagate build.python into cmake
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#53979 Remove `#[repr(transparent)]` from atomics
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors, beta-accepted

#51366 stabilize #[panic_handler]
  src/libstd/lib.rs
  src/libsyntax/feature_gate.rs
  src/test/compile-fail/auxiliary/some-panic-impl.rs
  src/test/compile-fail/panic-handler-twice.rs
  src/test/run-make-fulldeps/issue-51671/app.rs
  src/test/run-make-fulldeps/panic-impl-transitive/panic-impl-provider.rs
  src/test/ui/consts/const-eval/const_panic_libcore_main.rs
  src/test/ui/consts/const-eval/const_panic_libcore_main.stderr
  src/test/ui/feature-gates/feature-gate-panic-handler.rs
  src/test/ui/feature-gates/feature-gate-panic-handler.stderr
  src/test/ui/panic-handler/auxiliary/some-panic-impl.rs
  src/test/ui/panic-handler/panic-handler-bad-signature-1.rs
  src/test/ui/panic-handler/panic-handler-bad-signature-1.stderr
  src/test/ui/panic-handler/panic-handler-bad-signature-2.rs
  src/test/ui/panic-handler/panic-handler-bad-signature-2.stderr
  src/test/ui/panic-handler/panic-handler-bad-signature-3.rs
  src/test/ui/panic-handler/panic-handler-bad-signature-3.stderr
  src/test/ui/panic-handler/panic-handler-bad-signature-4.rs
  src/test/ui/panic-handler/panic-handler-bad-signature-4.stderr
  src/test/ui/panic-handler/panic-handler-duplicate.rs
  src/test/ui/panic-handler/panic-handler-duplicate.stderr
  src/test/ui/panic-handler/panic-handler-requires-panic-info.rs
  src/test/ui/panic-handler/panic-handler-std.rs
  src/test/ui/panic-handler/panic-handler-std.stderr
  src/test/ui/panic_implementation-closures.rs
Labels: S-waiting-on-bors, relnotes

#53932 [NLL] Remove base_place
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/borrowck/borrowck-box-insensitivity.nll.stderr
  src/test/ui/borrowck/borrowck-box-insensitivity.rs
Labels: A-NLL, S-waiting-on-bors

#53942 Rewrite `precompute_borrows_out_of_scope` for fewer hash table lookups.
  src/librustc_mir/dataflow/impls/borrows.rs
Labels: A-NLL, S-waiting-on-bors

#53973 Have rust-lldb look for the rust-enabled lldb
  src/bootstrap/dist.rs
  src/etc/rust-lldb
Labels: S-waiting-on-bors

#53981 Implement initializer() for FileDesc
  src/libstd/sys/unix/fd.rs
Labels: S-waiting-on-bors

#53987 rustbuild: allow configuring llvm version suffix
  config.toml.example
  src/bootstrap/config.rs
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#53993 rustc_resolve: don't record uniform_paths canaries as reexports.
  src/librustc_resolve/resolve_imports.rs
  src/test/run-pass/uniform-paths/auxiliary/issue-53691.rs
  src/test/run-pass/uniform-paths/issue-53691.rs
Labels: S-waiting-on-bors

#54050 Update `petgraph` dependency to 0.4.13 to fix build with nightly
  src/Cargo.lock
  src/bootstrap/Cargo.toml
Labels: S-waiting-on-bors

#53903 Optimize miri checking of integer array/slices
  src/librustc/ich/impls_ty.rs
  src/librustc/mir/interpret/error.rs
  src/librustc/mir/interpret/mod.rs
  src/librustc/mir/interpret/value.rs
  src/librustc/ty/structural_impls.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-bors

#53988 rustc_resolve: only prepend CrateRoot to a non-keyword segment.
  src/librustc_resolve/build_reduced_graph.rs
  src/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-absolute.rs
Labels: S-waiting-on-bors

#53565 #53359: putting multiple unresolved import on single line
  src/librustc_resolve/lib.rs
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/dollar-crate/dollar-crate-is-keyword-2.stderr
  src/test/ui/issue-53565.rs
  src/test/ui/issue-53565.stderr
Labels: S-waiting-on-bors

#54000 Allow named lifetimes in async functions.
  src/librustc/hir/map/def_collector.rs
  src/test/run-pass/async-await.rs
Labels: A-async-await, S-waiting-on-bors

#54093 Feature gate non-builtin attributes in inner attribute position
  src/libsyntax/ext/expand.rs
  src/libsyntax/feature_gate.rs
  src/test/compile-fail-fulldeps/proc-macro/attribute-with-error.rs
  src/test/compile-fail-fulldeps/proc-macro/issue-41211.rs
  src/test/compile-fail-fulldeps/proc-macro/proc-macro-gates.rs
  src/test/ui/feature-gate/issue-43106-gating-of-bench.rs
  src/test/ui/span/issue-36530.rs
  src/test/ui/span/issue-36530.stderr
Labels: S-waiting-on-bors

#54092 Don't compute padding of braces unless they are unmatched
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/lexer/tokentrees.rs
Labels: S-waiting-on-bors

#54117 [stable] 1.29.0 stable release
  src/ci/run.sh
Labels: S-waiting-on-bors, S-waiting-on-review

#51159 First step towards `u128` instead of `Const` in `PatternKind::Range`
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
Labels: S-waiting-on-bors

#53703 Document .0 to unpack integer from Wrapping
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#53777 Implemented map_or_else for Result<T, E>
  src/libcore/result.rs
Labels: S-waiting-on-bors, T-libs

#54031 A few cleanups and minor improvements to rustc_passes
  src/librustc_passes/ast_validation.rs
  src/librustc_passes/hir_stats.rs
  src/librustc_passes/loops.rs
  src/librustc_passes/mir_stats.rs
  src/librustc_passes/rvalue_promotion.rs
Labels: S-waiting-on-bors

#54046 Update documentation for fill_buf in std::io::BufRead
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#54064 `&CStr`, not `CStr`, is the counterpart of `&str`
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors

#54073 docs: Use dollar sign for all bash prompts
  README.md
  src/bootstrap/README.md
  src/doc/rustc/src/lints/index.md
  src/doc/rustc/src/lints/levels.md
Labels: S-waiting-on-bors

#54074 simplify ordering for Kind
  src/librustc/ty/subst.rs
Labels: S-waiting-on-bors

#54085 Remove documentation about proc_macro being bare-bones
  src/libproc_macro/lib.rs
Labels: S-waiting-on-bors

#54087 rustdoc: Remove generated blanket impls from trait pages
  src/librustdoc/html/render.rs
  src/test/rustdoc/auxiliary/issue-53689.rs
  src/test/rustdoc/issue-53689.rs
Labels: S-waiting-on-bors

#54106 Reexport CheckLintNameResult
  src/librustc/lint/mod.rs
Labels: S-waiting-on-bors

#54107 Fix typos in libstd hash map
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#54142 Recover proper regression test for issue #16278.
  src/test/run-pass/.gitattributes
  src/test/ui/run-pass/issues/.gitattributes
  src/test/ui/run-pass/issues/issue-16278.rs
Labels: S-waiting-on-bors

#53829 Add rustc SHA to released DWARF debuginfo
  config.toml.example
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/cc_detect.rs
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
  src/bootstrap/test.rs
  src/ci/run.sh
  src/libstd/build.rs
  src/test/ui/consts/const-size_of-cycle.rs
  src/test/ui/impl-trait/impl-generic-mismatch.rs
  src/test/ui/impl-trait/impl-generic-mismatch.stderr
Labels: S-waiting-on-bors

#53950 Allow for opting out of ThinLTO and clean up LTO related cli flag handling.
  src/librustc/session/config.rs
  src/librustc/session/mod.rs
  src/librustc_codegen_llvm/back/link.rs
  src/librustc_codegen_llvm/back/linker.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/test/run-make-fulldeps/codegen-options-parsing/Makefile
  src/test/run-make-fulldeps/lto-smoke/Makefile
Labels: S-waiting-on-bors, T-compiler, disposition-merge, final-comment-period

#53976 Replace unwrap calls in example by expect
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors

#54070 Add Error::description soft-deprecation to RELEASES
  RELEASES.md
Labels: S-waiting-on-bors

#54076 miri loop detector hashing
  src/librustc_mir/const_eval.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/snapshot.rs
  src/librustc_mir/interpret/step.rs
Labels: S-waiting-on-bors

#54119 Add some unit tests for find_best_match_for_name
  src/libsyntax/util/lev_distance.rs
Labels: S-waiting-on-bors

#54147 Add a test that tries to modify static memory at compile-time
  src/test/ui/consts/const-eval/mod-static-with-const-fn.rs
  src/test/ui/consts/const-eval/mod-static-with-const-fn.stderr
Labels: S-waiting-on-bors

#54150 Updated 1.29 release notes with --document-private-items flag
  RELEASES.md
Labels: S-waiting-on-bors, stable-accepted, stable-nominated

#54163 Update stage 0 to latest beta
  src/stage0.txt
Labels: S-waiting-on-bors

#54170 COMPILER_TESTS.md has been moved
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#53218 Add a implementation of `From` for converting `&'a Option<T>` into `Option<&'a T>`
  src/libcore/option.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#54024 Fix compiling some rustc crates to wasm
  src/librustc_data_structures/flock.rs
  src/librustc_errors/lock.rs
Labels: S-waiting-on-bors

#54173 Suggest valid crate type if invalid crate type is found
  src/librustc/lint/builtin.rs
  src/librustc_driver/driver.rs
  src/test/ui/invalid/invalid-crate-type.rs
  src/test/ui/invalid/invalid-crate-type.stderr
Labels: S-waiting-on-bors

#54194 Remove println!() statement from HashMap unit test
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#54203 Fix the stable release of os_str_str_ref_eq
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors

#54207 re-mark the never docs as unstable
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors, T-doc, beta-nominated

#54080 Addressed #53692
  src/librustc_typeck/check/mod.rs
  src/test/ui/issue-53692.rs
  src/test/ui/issue-53692.stderr
Labels: S-waiting-on-bors

#54201 rustc_resolve: don't treat uniform_paths canaries as ambiguities unless they resolve to distinct Def's.
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/run-pass/uniform-paths/basic-nested.rs
  src/test/ui/run-pass/uniform-paths/basic.rs
Labels: S-waiting-on-bors

#54069 resolve: Introduce two sub-namespaces in macro namespace
  src/librustc_resolve/macros.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/derive-helper-shadowed-2.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/derive-helper-shadowed.rs
  src/test/ui-fulldeps/proc-macro/derive-helper-shadowed.rs
  src/test/ui/issues/issue-11692-2.rs
  src/test/ui/issues/issue-11692-2.stderr
  src/test/ui/macros/macro-path-prelude-fail-3.rs
  src/test/ui/macros/macro-path-prelude-fail-3.stderr
  src/test/ui/macros/macro-path-prelude-fail-4.rs
  src/test/ui/macros/macro-path-prelude-fail-4.stderr
Labels: S-waiting-on-bors, T-lang

#52896 Add inspection and setter methods to proc_macro::Diagnostic.
  src/libproc_macro/diagnostic.rs
  src/libproc_macro/lib.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/multispan.rs
  src/test/ui-fulldeps/proc-macro/multispan.rs
  src/test/ui-fulldeps/proc-macro/multispan.stderr
Labels: S-waiting-on-bors

#53527 Add option to run all tests
  src/libtest/lib.rs
Labels: I-nominated, S-waiting-on-bors, T-dev-tools

#53754 stabilize slice_align_to
  src/libcore/slice/mod.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#54209 Partially revert 674a5db "Fix undesirable fallout [from macro modularization]"
  src/test/ui/run-pass/macros/macro-comma-support.rs
Labels: S-waiting-on-bors

#54213 De-overlap the lifetimes of `flow_inits` and `flow_{un,ever_}inits`.
  src/librustc_mir/borrow_check/mod.rs
Labels: A-NLL, S-waiting-on-bors

#54244 Add a small search box to seach Rust's standary library
  src/doc/index.md
Labels: S-waiting-on-bors

#53461 resolve: Do not error on access to proc macros imported with `#[macro_use]`
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/attr_proc_macro.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/bang_proc_macro.rs
  src/test/ui-fulldeps/proc-macro/macro-use-attr.rs
  src/test/ui-fulldeps/proc-macro/macro-use-bang.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period

#53910 Move std::os::raw::c_void into libcore and re-export in libstd
  src/libcore/ffi.rs
  src/libcore/lib.rs
  src/libstd/ffi/mod.rs
  src/libstd/os/raw/mod.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#54247 Improve output if no_lookup_host_duplicates test fails
  src/libstd/sys_common/net.rs
Labels: S-waiting-on-bors

#54277 Temporarily prohibit proc macro attributes placed after derives
  src/librustc_resolve/macros.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/ptr.rs
  src/libsyntax_ext/test.rs
  src/test/compile-fail-fulldeps/proc-macro/proc-macro-attributes.rs
  src/test/ui-fulldeps/attribute-order-restricted.rs
  src/test/ui-fulldeps/attribute-order-restricted.stderr
  src/test/ui-fulldeps/proc-macro/derive-helper-shadowing.rs
  src/test/ui-fulldeps/proc-macro/derive-helper-shadowing.stderr
Labels: S-waiting-on-bors

#54314 [beta] Prepare the 1.30.0 release
  src/ci/run.sh
  src/stage0.txt
Labels: S-waiting-on-bors, S-waiting-on-review

#53522 Add doc for impl From for Addr
  src/libstd/net/addr.rs
Labels: S-waiting-on-bors

#54097 rustdoc: Remove namespace for keywords
  src/librustdoc/html/render.rs
  src/test/rustdoc/keyword.rs
Labels: S-waiting-on-bors

#54205 Add treat-err-as-bug flag in rustdoc
  src/test/rustdoc-ui/treat-err-as-bug.rs
  src/test/rustdoc-ui/treat-err-as-bug.stderr
Labels: S-waiting-on-bors

#54225 Regression test for rust-lang/rust#53675.
  src/test/ui/issues/issue-53675-a-test-called-panic.rs
Labels: S-waiting-on-bors

#54232 add `-Z dont-buffer-diagnostics`
  src/librustc/session/config.rs
  src/librustc/session/mod.rs
  src/librustc_errors/diagnostic_builder.rs
  src/librustc_errors/lib.rs
Labels: S-waiting-on-bors

#54311 Remove README with now-out-of-date docs about docs.
  src/doc/README.md
Labels: S-waiting-on-bors

#54313 OsStr: Document that it's not NUL terminated
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors

#54101 Fix camel case type warning for types with trailing underscores
  src/librustc_lint/nonstandard_style.rs
  src/test/ui/lint/issue-54099-camel-case-underscore-types.rs
  src/test/ui/lint/lint-non-camel-case-types.rs
  src/test/ui/lint/lint-non-camel-case-types.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, final-comment-period

#54174 Fix `thread` `park`/`unpark` synchronization
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#54211 Split `Liveness::users` into three.
  src/librustc/middle/liveness.rs
Labels: S-waiting-on-bors

#54301 Update some `*-sys` dependencies of Cargo/RLS
  src/Cargo.lock
Labels: S-waiting-on-bors

#54255 Inspect parents paths when checking for moves
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/dataflow/move_paths/mod.rs
  src/test/ui/nll/issue-52669.rs
  src/test/ui/nll/issue-52669.stderr
  src/test/ui/nll/move-subpaths-moves-root.rs
  src/test/ui/nll/move-subpaths-moves-root.stderr
Labels: A-NLL, S-waiting-on-bors

#54397 [stable] std: Check for overflow in `str::repeat`
  RELEASES.md
  src/bootstrap/channel.rs
  src/liballoc/slice.rs
  src/liballoc/str.rs
Labels: S-waiting-on-bors

#52813 Duration div mul extras
  src/libcore/time.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#53470 Warn about metadata loader errors
  src/librustc_metadata/locator.rs
Labels: S-waiting-on-bors

#54233 Remove LLVM 3.9 workaround.
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
Labels: S-waiting-on-bors

#54257 Switch wasm math symbols to their original names
  src/libstd/sys/wasm/cmath.rs
Labels: S-waiting-on-bors

#54258 Enable fatal warnings for the wasm32 linker
  src/librustc_codegen_llvm/back/linker.rs
Labels: S-waiting-on-bors

#54290 Switch linker for aarch64-pc-windows-msvc from LLD to MSVC
  src/librustc_target/spec/aarch64_pc_windows_msvc.rs
Labels: S-waiting-on-bors

#54295 A few cleanups and minor improvements to rustc/traits
  src/librustc/traits/auto_trait.rs
  src/librustc/traits/codegen/mod.rs
  src/librustc/traits/coherence.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/fulfill.rs
  src/librustc/traits/mod.rs
  src/librustc/traits/object_safety.rs
  src/librustc/traits/on_unimplemented.rs
  src/librustc/traits/project.rs
  src/librustc/traits/query/dropck_outlives.rs
  src/librustc/traits/query/normalize.rs
  src/librustc/traits/select.rs
  src/librustc/traits/specialize/mod.rs
  src/librustc/traits/specialize/specialization_graph.rs
  src/librustc/traits/structural_impls.rs
  src/librustc/traits/util.rs
  src/librustc/ty/trait_def.rs
  src/librustc_typeck/check/closure.rs
Labels: S-waiting-on-bors

#54298 miri: correctly compute expected alignment for field
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#54337 Remove unneeded clone() from tests in librustdoc
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#54346 rustc: future-proof error reporting for polymorphic constants in types.
  src/librustc/traits/error_reporting.rs
Labels: S-waiting-on-bors

#54362 Pass --batch to gdb
  .travis.yml
Labels: S-waiting-on-bors

#54367 Add regression test for thread local static mut borrows
  src/test/ui/nll/borrowck-thread-local-static-mut-borrow-outlives-fn.rs
Labels: A-NLL, S-waiting-on-bors

#54398 [beta] std: Check for overflow in `str::repeat`
  src/liballoc/slice.rs
  src/liballoc/str.rs
Labels: S-waiting-on-bors

#54399 std: Check for overflow in `str::repeat`
  src/liballoc/slice.rs
  src/liballoc/str.rs
Labels: S-waiting-on-bors, beta-accepted, stable-accepted

#54443 [beta] Update the `libgit2-sys` crate
  src/Cargo.lock
Labels: S-waiting-on-bors

#54261 Make `dyn` a keyword in the 2018 edition
  src/librustc_lint/builtin.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
  src/libsyntax_pos/symbol.rs
  src/test/ui/rust-2018/dyn-keyword.fixed
  src/test/ui/rust-2018/dyn-keyword.rs
  src/test/ui/rust-2018/dyn-keyword.stderr
  src/test/ui/rust-2018/dyn-trait-compatibility.rs
  src/test/ui/rust-2018/dyn-trait-compatibility.stderr
Labels: S-waiting-on-bors

#54280 remove (more) CAS API from Atomic* types where not natively supported
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-author

#54323 rustbuild: drop color handling
  src/bootstrap/bin/rustc.rs
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors, T-infra, beta-accepted, beta-nominated

#54370 Improve handling of type bounds in `bit_set.rs`.
  src/librustc/traits/select.rs
  src/librustc_data_structures/bit_set.rs
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/monomorphize/collector.rs
  src/libserialize/serialize.rs
Labels: S-waiting-on-bors

#54371 add -Zui-testing to rustdoc
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/test/rustdoc-ui/deny-intra-link-resolution-failure.stderr
  src/test/rustdoc-ui/deprecated-attrs.stderr
  src/test/rustdoc-ui/intra-doc-alias-ice.stderr
  src/test/rustdoc-ui/intra-links-warning.stderr
Labels: S-waiting-on-bors

#54374 Make 'proc_macro::MultiSpan' public.
  src/libproc_macro/lib.rs
Labels: S-waiting-on-bors

#54402 Use no_default_libraries for all NetBSD flavors
  src/librustc_target/spec/netbsd_base.rs
  src/librustc_target/spec/x86_64_rumprun_netbsd.rs
Labels: S-waiting-on-bors

#54409 Detect `for _ in in bar {}` typo
  src/libsyntax/parse/parser.rs
  src/test/ui/did_you_mean/issue-54109-and_instead_of_ampersands.stderr
  src/test/ui/parser/if-in-in.rs
  src/test/ui/parser/if-in-in.stderr
Labels: S-waiting-on-bors

#54412 add applicability to span_suggestion call
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/mod.rs
Labels: S-waiting-on-bors

#54415 parser: Tweak function parameter parsing to avoid rollback on succesfull path
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#54420 Compress `Liveness` data some more.
  src/librustc/middle/liveness.rs
Labels: S-waiting-on-bors

#54422 Simplify slice's first(_mut) and last(_mut) with get
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#54446 Unify christianpoveda's emails
  .mailmap
Labels: S-waiting-on-bors

#54325 incr.comp.: Allow for more fine-grained testing of CGU reuse and use it to test incremental ThinLTO.
  src/librustc/dep_graph/cgu_reuse_tracker.rs
  src/librustc/dep_graph/mod.rs
  src/librustc/ich/mod.rs
  src/librustc/session/mod.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_incremental/assert_module_sources.rs
  src/libsyntax/feature_gate.rs
  src/test/incremental/remove-private-item-cross-crate/main.rs
  src/test/incremental/thinlto/cgu_invalidated_via_import.rs
  src/test/incremental/thinlto/independent_cgus_dont_affect_each_other.rs
Labels: S-waiting-on-bors

#54339 Remove spawning from task::Context
  src/liballoc/boxed.rs
  src/libcore/future/future.rs
  src/libcore/future/future_obj.rs
  src/libcore/future/mod.rs
  src/libcore/task/context.rs
  src/libcore/task/mod.rs
  src/libcore/task/spawn.rs
  src/libcore/task/wake.rs
  src/libstd/future.rs
  src/libstd/macros.rs
  src/libstd/panic.rs
  src/test/run-pass/async-await.rs
  src/test/run-pass/futures-api.rs
Labels: S-waiting-on-bors

#54495 Improve error message for E0424
  src/librustc_resolve/lib.rs
  src/test/ui/error-codes/E0424.stderr
  src/test/ui/resolve/issue-2356.stderr
  src/test/ui/resolve/unresolved_static_type_field.stderr
Labels: S-waiting-on-bors

#54430 Update musl to 1.1.20.
  src/ci/docker/scripts/musl.sh
Labels: S-waiting-on-bors

#54411 Make "await" a pseudo-edition keyword
  src/librustc_lint/builtin.rs
  src/librustc_lint/diagnostics.rs
  src/librustc_lint/lib.rs
  src/test/ui/await-keyword/2015-edition-no-warnings-with-feature-gate.rs
  src/test/ui/await-keyword/2015-edition-warning.fixed
  src/test/ui/await-keyword/2015-edition-warning.rs
  src/test/ui/await-keyword/2015-edition-warning.stderr
  src/test/ui/await-keyword/2018-edition-error.rs
  src/test/ui/await-keyword/2018-edition-error.stderr
  src/test/ui/await-keyword/2018-edition-no-error-with-feature-gate.rs
  src/test/ui/await-keyword/post_expansion_error.rs
  src/test/ui/await-keyword/post_expansion_error.stderr
Labels: S-waiting-on-bors

#53518 Add doc for impl From in char_convert
  src/libcore/char/convert.rs
Labels: S-waiting-on-bors

#54281 Search box
  src/doc/index.md
Labels: S-waiting-on-author

#54368 Reduce code block sides padding
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#54498 The project moved under the Mozilla umbrella
  src/doc/unstable-book/src/compiler-flags/profile.md
Labels: S-waiting-on-bors

#54518 resolve: Do not block derive helper resolutions on single import resolutions
  src/librustc_resolve/macros.rs
  src/test/compile-fail-fulldeps/proc-macro/proc-macro-attributes.rs
  src/test/ui-fulldeps/custom-derive/auxiliary/plugin.rs
  src/test/ui-fulldeps/custom-derive/helper-attr-blocked-by-import-ambig.rs
  src/test/ui-fulldeps/custom-derive/helper-attr-blocked-by-import-ambig.stderr
  src/test/ui-fulldeps/custom-derive/helper-attr-blocked-by-import.rs
  src/test/ui-fulldeps/proc-macro/derive-helper-shadowing.stderr
Labels: S-waiting-on-bors, beta-nominated

#54522 Fixed three small typos.
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#54529 aarch64-pc-windows-msvc: Don't link libpanic_unwind to libtest.
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#54539 Fix js error
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#54557 incr.comp.: Don't automatically enable -Zshare-generics for incr. comp. builds.
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#54558 Improvements to finding LLVM's FileCheck
  config.toml.example
  src/bootstrap/config.rs
  src/bootstrap/configure.py
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors
