Repository rust-lang/rust, pull requests merged in 2018-11, with the labels that each got.

#55550 [beta] Update the boostrap compiler
  src/Cargo.lock
  src/stage0.txt
Labels: S-waiting-on-bors

#55581 [beta] Fix wrong validation clasisfication of `Option<&T>::Some` values
  src/librustc_mir/interpret/validity.rs
  src/test/ui/consts/const-validation-fail-55455.rs
  src/test/ui/consts/promoted-validation-55454.rs
Labels: S-waiting-on-bors

#55280 Add libproc_macro to rust-src distribution
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#55469 Regression tests for issue #54477.
  src/test/run-pass/issues/issue-54477-reduced-2.rs
Labels: S-waiting-on-bors

#55504 Use vec![x; n] instead of iter::repeat(x).take(n).collect()
  src/librustc/mir/interpret/mod.rs
  src/librustc/traits/error_reporting.rs
Labels: S-waiting-on-bors

#55522 use String::from() instead of format!() macro to construct Strings.
  src/librustc/hir/map/mod.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/libsyntax/ext/expand.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors

#55536 Pass suggestions as impl Iterator instead of Vec
  src/librustc_errors/diagnostic.rs
  src/librustc_errors/diagnostic_builder.rs
  src/librustc_resolve/lib.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#55542 syntax: improve a few allocations
  src/libsyntax/ext/expand.rs
  src/libsyntax_ext/deriving/generic/mod.rs
Labels: S-waiting-on-bors

#55558 Tweak `MatcherPos::matches`
  src/libsyntax/ext/tt/macro_parser.rs
Labels: S-waiting-on-author

#55561 Fix double_check tests on big-endian targets
  src/test/ui/consts/const-eval/double_check.rs
  src/test/ui/consts/const-eval/double_check2.rs
  src/test/ui/consts/const-eval/double_check2.stderr
Labels: S-waiting-on-bors

#55573 Make sure the `aws` executable is in $PATH on macOS
  .travis.yml
Labels: S-waiting-on-bors

#55574 Use `SmallVec` within `MoveData`.
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/dataflow/move_paths/mod.rs
Labels: S-waiting-on-bors

#55578 Made doc example of `impl Default for …` use `-> Self` instead of explicit self type
  src/libcore/default.rs
Labels: S-waiting-on-bors

#55582 Remove unused import copy from publish_toolstate.py
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#55359 Fixes #46775 -- don't mutate the process's environment in Command::exec
  src/libstd/sys/unix/process/process_common.rs
  src/libstd/sys/unix/process/process_unix.rs
  src/test/run-pass/command-exec.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated, stable-nominated

#54718 add an appveyor config for aarch64-pc-windows-msvc
  appveyor.yml
Labels: S-waiting-on-bors

#55363 Bump cargo-vendor version
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors, T-infra

#55555 Make `-Z ls` list the actual filename of external dependencies
  src/librustc_metadata/decoder.rs
Labels: S-waiting-on-bors

#55567 add test for deriving Debug on uninhabited enum
  src/test/ui/derive-uninhabited-enum-38885.rs
  src/test/ui/derive-uninhabited-enum-38885.stderr
Labels: S-waiting-on-bors

#55568 test that rustdoc doesn't overflow on a big enum
  src/test/rustdoc/auxiliary/enum_primitive.rs
  src/test/rustdoc/no-stack-overflow-25295.rs
Labels: S-waiting-on-bors

#55598 publish-toolstate: ping maintainers when a tool builds again
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#55665 rustc_target: pass contexts by reference, not value.
  src/librustc/lint/context.rs
  src/librustc/middle/intrinsicck.rs
  src/librustc/mir/interpret/mod.rs
  src/librustc/mir/interpret/value.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/ty/layout.rs
  src/librustc/ty/util.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/mir/constant.rs
  src/librustc_lint/types.rs
  src/librustc_mir/hair/cx/mod.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/interpret/cast.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/interpret/traits.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_target/abi/call/aarch64.rs
  src/librustc_target/abi/call/amdgpu.rs
  src/librustc_target/abi/call/arm.rs
  src/librustc_target/abi/call/asmjs.rs
  src/librustc_target/abi/call/mips.rs
  src/librustc_target/abi/call/mips64.rs
  src/librustc_target/abi/call/mod.rs
  src/librustc_target/abi/call/powerpc.rs
  src/librustc_target/abi/call/powerpc64.rs
  src/librustc_target/abi/call/s390x.rs
  src/librustc_target/abi/call/sparc.rs
  src/librustc_target/abi/call/sparc64.rs
  src/librustc_target/abi/call/x86.rs
  src/librustc_target/abi/call/x86_64.rs
  src/librustc_target/abi/mod.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#55106 Use lld directly for Fuchsia target
  src/bootstrap/bin/rustc.rs
  src/bootstrap/configure.py
  src/bootstrap/lib.rs
  src/ci/docker/dist-various-2/Dockerfile
  src/librustc_target/spec/aarch64_fuchsia.rs
  src/librustc_target/spec/fuchsia_base.rs
  src/librustc_target/spec/x86_64_fuchsia.rs
Labels: S-waiting-on-bors

#55490 resolve: Fix ICE in macro import error recovery
  src/librustc_resolve/macros.rs
  src/test/ui/imports/issue-55457.rs
  src/test/ui/imports/issue-55457.stderr
Labels: S-waiting-on-bors

#55597 std: Enable usage of `thread_local!` through imports
  src/libstd/thread/local.rs
  src/test/run-pass/thread-local-not-in-prelude.rs
Labels: S-waiting-on-bors

#55621 Add precision for create_dir function
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#55644 ci: Add Dockerfile for dist-powerpcspe-linux
  src/ci/docker/disabled/dist-powerpcspe-linux/Dockerfile
Labels: S-waiting-on-bors

#55664 Make "all possible cases" help message uniform with existing help messages
  src/librustc_mir/hair/pattern/check_match.rs
  src/test/ui/error-codes/E0004-2.stderr
  src/test/ui/issues/issue-3096-1.stderr
  src/test/ui/issues/issue-3096-2.stderr
  src/test/ui/uninhabited/uninhabited-matches-feature-gated.stderr
Labels: S-waiting-on-bors

#55689 miri: binary_op_val -> binary_op_imm
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/interpret/operator.rs
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-bors

#55703 Update `configure --help` (via configure.py) to reflect decoupling of debug+optimize
  src/bootstrap/configure.py
Labels: S-waiting-on-bors

#55377 Slight copy-editing for `std::cell::Cell` docs
  src/libcore/cell.rs
Labels: S-waiting-on-bors

#55441 Remove unused re import in gdb_rust_pretty_printing
  src/etc/gdb_rust_pretty_printing.py
Labels: S-waiting-on-bors

#55453 Choose predicates without inference variables over those with them
  src/librustc/traits/auto_trait.rs
  src/test/rustdoc/issue-54705.rs
Labels: S-waiting-on-bors

#55501 Make `process_obligations`' computation of `completed` optional.
  src/librustc/traits/fulfill.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_data_structures/obligation_forest/test.rs
Labels: S-waiting-on-bors

#55510 Fix feature gate only being checked on first repr attr.
  src/libsyntax/attr/mod.rs
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gates/feature-gate-repr-simd.rs
  src/test/ui/feature-gates/feature-gate-repr-simd.stderr
  src/test/ui/feature-gates/feature-gate-repr_packed.rs
  src/test/ui/feature-gates/feature-gate-repr_packed.stderr
Labels: S-waiting-on-bors

#55609 Run name-anon-globals after LTO passes as well
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/test/ui/issue-51947.rs
Labels: S-waiting-on-bors

#55692 -C remark: fix incorrect warning about requiring "--debuginfo" instead of "-C debuginfo=n"
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#55702 Add `aarch64-pc-windows-msvc` to deployed targets
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#55730 Use trait impl method span when type param mismatch is due to impl Trait
  src/librustc_typeck/check/compare_method.rs
  src/test/ui/issues/type-arg-mismatch-due-to-impl-trait.rs
  src/test/ui/issues/type-arg-mismatch-due-to-impl-trait.stderr
Labels: S-waiting-on-bors

#55734 refactor: use shorthand fields
  src/liballoc/string.rs
  src/libpanic_unwind/dwarf/mod.rs
  src/libpanic_unwind/seh64_gnu.rs
  src/librustc/infer/resolve.rs
  src/librustc/infer/type_variable.rs
  src/librustc/infer/unify_key.rs
  src/librustc/middle/stability.rs
  src/librustc/mir/mod.rs
  src/librustc/mir/tcx.rs
  src/librustc/traits/project.rs
  src/librustc/traits/select.rs
  src/librustc/ty/_match.rs
  src/librustc/ty/fold.rs
  src/librustc_codegen_llvm/llvm/mod.rs
  src/librustc_codegen_llvm/mir/analyze.rs
  src/librustc_codegen_utils/symbol_names_test.rs
  src/librustc_data_structures/flock.rs
  src/librustc_data_structures/svh.rs
  src/librustc_lint/types.rs
  src/librustc_metadata/encoder.rs
  src/librustc_mir/build/scope.rs
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/impls/storage_liveness.rs
  src/librustc_mir/hair/pattern/check_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/simplify.rs
  src/librustc_mir/transform/simplify_branches.rs
  src/librustc_passes/ast_validation.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/json_dumper.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/coherence/orphan.rs
  src/librustc_typeck/coherence/unsafety.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/impl_wf_check.rs
  src/librustdoc/clean/mod.rs
  src/libstd/collections/hash/map.rs
  src/libstd/fs.rs
  src/libstd/io/util.rs
  src/libstd/sync/mpsc/mod.rs
  src/libstd/sys/cloudabi/time.rs
  src/libstd/sys/redox/fd.rs
  src/libstd/sys/redox/fs.rs
  src/libstd/sys/redox/syscall/error.rs
  src/libstd/sys/redox/thread.rs
  src/libstd/sys/redox/time.rs
  src/libstd/sys/unix/fd.rs
  src/libstd/sys/unix/fs.rs
  src/libstd/sys/unix/time.rs
  src/libstd/sys/windows/process.rs
  src/libstd/sys/windows/time.rs
  src/libstd/sys_common/poison.rs
  src/libstd/sys_common/wtf8.rs
  src/libsyntax/ext/source_util.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#55187 Remove targets from the manifest that are not built on travis
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#55366 Add tracking issue for Layout methods (and some API changes)
  src/liballoc/lib.rs
  src/libcore/alloc.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, proposed-final-comment-period, relnotes

#55576 Clarify error message for -C opt-level
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#55633 Support memcpy/memmove with differing src/dst alignment
  src/librustc_codegen_llvm/abi.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/builder.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_codegen_llvm/mir/block.rs
  src/librustc_codegen_llvm/mir/operand.rs
  src/rustllvm/RustWrapper.cpp
  src/test/codegen/packed.rs
  src/test/codegen/stores.rs
Labels: S-waiting-on-bors

#55659 rustc: Delete grouping logic from the musl target
  src/librustc_target/spec/linux_musl_base.rs
Labels: S-waiting-on-bors

#55736 Elide anon lifetimes in conflicting impl note
  src/librustc/traits/specialize/mod.rs
  src/test/ui/coherence/coherence-impls-copy.stderr
  src/test/ui/e0119/issue-28981.stderr
Labels: S-waiting-on-bors

#55739 Consume optimization fuel from the MIR inliner
  src/librustc_mir/transform/inline.rs
Labels: S-waiting-on-bors

#55742 Avoid panic when matching function call
  src/librustc_typeck/check/_match.rs
  src/test/ui/match/match-fn-call.rs
  src/test/ui/match/match-fn-call.stderr
Labels: S-waiting-on-bors

#55753 borrow_set: remove a helper function and a clone it uses
  src/librustc_mir/borrow_check/borrow_set.rs
Labels: S-waiting-on-bors

#55755 Improve creation of 3 IndexVecs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc_mir/shim.rs
Labels: S-waiting-on-bors

#55758 [regression - rust2018]: unused_mut lint false positives on nightly
  src/librustc/mir/mod.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/used_muts.rs
  src/test/ui/nll/issue-55344.rs
Labels: S-waiting-on-bors

#55760 Remove intermediate font specs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#55761 mir: remove a hacky recursive helper function
  src/librustc_mir/transform/promote_consts.rs
Labels: S-waiting-on-bors

#55774 wasm32-unknown-emscripten expects the rust_eh_personality symbol
  src/libpanic_abort/lib.rs
Labels: S-waiting-on-bors

#55777 Use `Lit` rather than `P<Lit>` in `ast::ExprKind`.
  src/librustc/hir/lowering.rs
  src/libsyntax/ast.rs
  src/libsyntax/ext/base.rs
  src/libsyntax/ext/build.rs
  src/libsyntax/ext/quote.rs
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#55783 Deprecate mpsc channel selection
  src/libstd/macros.rs
  src/libstd/sync/mpsc/mod.rs
  src/libstd/sync/mpsc/select.rs
  src/test/run-pass/issues/issue-13494.rs
Labels: S-waiting-on-bors

#55788 rustc: Request ansi colors if stderr isn't a tty
  src/librustc_errors/emitter.rs
Labels: S-waiting-on-bors

#55823 [beta] Make sure the installed `awscli` is found on macOS.
  .travis.yml
Labels: S-waiting-on-bors

#55717 Bubble up an overflow error so that rustdoc can ignore it
  src/librustc/traits/project.rs
  src/test/ui/issues/issue-23122-2.stderr
Labels: S-waiting-on-bors, beta-accepted, beta-nominated, stable-accepted

#55650 Implement rotate using funnel shift on LLVM >= 7
  src/libcore/intrinsics.rs
  src/libcore/num/mod.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_codegen_llvm/mir/mod.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_typeck/check/intrinsic.rs
Labels: S-waiting-on-bors

#55630 resolve: Filter away macro prelude in modules with `#[no_implicit_prelude]` on 2018 edition
  src/librustc/session/mod.rs
  src/librustc_resolve/macros.rs
  src/test/ui/hygiene/no_implicit_prelude-2018.rs
  src/test/ui/hygiene/no_implicit_prelude-2018.stderr
  src/test/ui/hygiene/no_implicit_prelude.rs
Labels: S-waiting-on-bors, T-lang, beta-nominated, disposition-merge, final-comment-period

#55745 Convert `outlives_components`' return value to a `SmallVec` outparam.
  src/librustc/infer/opaque_types/mod.rs
  src/librustc/infer/outlives/obligations.rs
  src/librustc/infer/outlives/verify.rs
  src/librustc/traits/util.rs
  src/librustc/ty/outlives.rs
  src/librustc/ty/sty.rs
  src/librustc_mir/transform/cleanup_post_borrowck.rs
  src/librustc_traits/implied_outlives_bounds.rs
  src/librustc_typeck/outlives/utils.rs
Labels: S-waiting-on-bors

#55764 Fix Rc/Arc allocation layout
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#55799 Removed unneeded instance of `// revisions` from a lint test
  src/test/ui/lint/lint-unused-mut-variables.nll.stderr
  src/test/ui/lint/lint-unused-mut-variables.rs
  src/test/ui/lint/lint-unused-mut-variables.stderr
Labels: S-waiting-on-bors

#55801 NLL: Update box insensitivity test
  src/test/ui/borrowck/borrowck-box-insensitivity.ast.stderr
  src/test/ui/borrowck/borrowck-box-insensitivity.mir.stderr
  src/test/ui/borrowck/borrowck-box-insensitivity.rs
Labels: S-waiting-on-bors

#55802 Don't inline virtual calls (take 2)
  src/librustc_mir/transform/inline.rs
  src/test/mir-opt/inline-trait-method_2.rs
Labels: S-waiting-on-bors

#55816 Use `SmallVec` to avoid allocations in `from_decimal_string`.
  src/Cargo.lock
  src/librustc_apfloat/Cargo.toml
  src/librustc_apfloat/ieee.rs
  src/librustc_apfloat/lib.rs
Labels: S-waiting-on-author

#55819 Typecheck patterns of all match arms first, so we get types for bindings
  src/librustc_typeck/check/_match.rs
  src/test/ui/typeck/issue-55810-must-typeck-match-pats-before-guards.rs
Labels: S-waiting-on-author, beta-accepted, beta-nominated

#55822 ICE with #![feature(nll)] and elided lifetimes
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/test/ui/nll/issue-55394.rs
  src/test/ui/nll/issue-55394.stderr
Labels: S-waiting-on-bors

#55828 Add missing `rustc_promotable` attribute to unsigned `min_value` and `max_value`
  src/libcore/num/mod.rs
  src/test/ui/consts/auxiliary/promotable_const_fn_lib.rs
  src/test/ui/consts/promote_fn_calls.rs
  src/test/ui/consts/promote_fn_calls_std.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#55839 Fix docstring spelling mistakes
  src/libcore/macros.rs
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#55844 Fix documentation typos.
  src/libcore/alloc.rs
  src/libcore/future/future.rs
  src/libcore/lib.rs
  src/libcore/mem.rs
  src/libcore/ptr.rs
  src/libstd/ffi/c_str.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#55845 Set BINARYEN_TRAP_MODE=clamp
  src/librustc_target/spec/wasm32_unknown_emscripten.rs
Labels: S-waiting-on-bors

#55856 rustdoc: refactor: move all static-file include!s into a single module
  src/librustdoc/config.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static_files.rs
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors

#55525 Make `MatcherPos::stack` a `SmallVec`.
  src/libsyntax/ext/tt/macro_parser.rs
Labels: S-waiting-on-bors

#55701 Fix emission of niche-filling discriminant values
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/test/codegen/enum-debug-niche-2.rs
Labels: S-waiting-on-bors

#55604 Avoid the Box in `TyCtxt::associated_items`.
  src/librustc/traits/specialize/specialization_graph.rs
  src/librustc/ty/mod.rs
Labels: S-waiting-on-bors

#55052 Use read_unaligned instead of read in transmute_copy
  src/libcore/mem.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, final-comment-period

#55136 Remove short doc where it starts with a codeblock
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render.rs
  src/test/rustdoc/doc-cfg.rs
  src/test/rustdoc/short-docblock-codeblock.rs
Labels: S-waiting-on-bors

#55711 Format BtreeMap::range_mut example
  src/liballoc/collections/btree/map.rs
Labels: S-waiting-on-bors

#55722 impl_stable_hash_for: support enums and tuple structs with generic parameters
  src/librustc/ich/impls_mir.rs
  src/librustc/ich/impls_ty.rs
  src/librustc/macros.rs
Labels: S-waiting-on-bors

#55754 Avoid converting bytes to UTF-8 strings to print, just pass bytes to stdout/err
  src/libstd/process.rs
Labels: S-waiting-on-bors

#55804 rustdoc: don't inline `pub use some_crate` unless directly asked to
  src/doc/rustdoc/src/the-doc-attribute.md
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/inline_cross/auxiliary/use_crate.rs
  src/test/rustdoc/inline_cross/auxiliary/use_crate_2.rs
  src/test/rustdoc/inline_cross/use_crate.rs
  src/test/rustdoc/src-links-external.rs
Labels: S-waiting-on-bors, T-rustdoc, beta-nominated

#55837 Make PhantomData #[structural_match]
  src/libcore/lib.rs
  src/libcore/marker.rs
  src/test/ui/rfc1445/phantom-data-is-structurally-matchable.rs
Labels: A-typesystem, S-waiting-on-bors, T-lang, relnotes

#55840 Fix TLS errors when downloading stage0
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#55858 Small fixes on code blocks in rustdoc
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#55863 Fix a typo in std::panic
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#55870 Fix typos.
  src/bootstrap/compile.rs
  src/etc/lldb_batchmode.py
  src/libcore/str/mod.rs
  src/librustc/infer/outlives/obligations.rs
  src/librustc/mir/mod.rs
  src/librustc/mir/traversal.rs
  src/librustc/ty/query/plumbing.rs
  src/librustc_apfloat/ieee.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_codegen_utils/linker.rs
  src/librustc_incremental/persist/fs.rs
  src/librustc_mir/borrow_check/location.rs
  src/librustc_mir/borrow_check/nll/region_infer/values.rs
  src/librustc_typeck/check/mod.rs
  src/libsyntax/ext/tt/macro_parser.rs
  src/libsyntax/ext/tt/quoted.rs
  src/test/run-pass-fulldeps/dropck_tarena_sound_drop.rs
  src/test/ui/feature-gate/issue-43106-gating-of-proc_macro_derive.rs
  src/tools/compiletest/src/header.rs
Labels: S-waiting-on-bors

#55874 string: Add documentation for `From` impls
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#55879 save-analysis: Don't panic for macro-generated use globs
  src/librustc_save_analysis/dump_visitor.rs
Labels: S-waiting-on-bors

#55882 Reference count `crate_inherent_impls`s return value.
  src/librustc/ty/query/mod.rs
  src/librustc_typeck/coherence/inherent_impls.rs
Labels: S-waiting-on-bors

#55889 global allocators: add a few comments
  src/liballoc/alloc.rs
  src/libstd/alloc.rs
Labels: S-waiting-on-bors

#55896 Document optimizations enabled by FusedIterator
  src/libcore/iter/traits.rs
Labels: S-waiting-on-bors

#55905 Change `Lit::short_name` to `Lit::literal_name`.
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
Labels: S-waiting-on-bors

#55908 Fix their/there grammar nit
  src/README.md
Labels: S-waiting-on-bors

#52153 chalk lowering rule: ProjectionEq-Normalize
  src/librustc_traits/lowering/mod.rs
  src/test/ui/chalkify/lower_trait.stderr
Labels: S-waiting-on-bors, T-lang

#55934 Switch AppVeyor builds to the GCE cloud
  appveyor.yml
Labels: S-waiting-on-bors

#55947 xLTO: Don't pass --plugin-opt=thin to LLD. That's not supported anymore.
  src/librustc_codegen_utils/linker.rs
Labels: S-waiting-on-bors, beta-nominated

#54906 Reattach all grandchildren when constructing specialization graph.
  src/librustc/traits/specialize/specialization_graph.rs
  src/test/compile-fail/specialization/issue-50452.rs
  src/test/run-pass/specialization/issue-50452.rs
Labels: S-waiting-on-bors

#55211 Add BufWriter::buffer method
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors

#55507 Add link to std::mem::size_of to size_of intrinsic documentation
  src/libcore/intrinsics.rs
Labels: S-waiting-on-bors

#55530 Speed up String::from_utf16
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#55556 Use `Mmap` to open the rmeta file.
  src/Cargo.lock
  src/librustc_metadata/Cargo.toml
  src/librustc_metadata/lib.rs
  src/librustc_metadata/locator.rs
Labels: S-waiting-on-bors

#55622 NetBSD: link libstd with librt in addition to libpthread
  src/libstd/build.rs
Labels: S-waiting-on-bors

#55778 Wrap some query results in `Lrc`.
  src/librustc/infer/outlives/verify.rs
  src/librustc/traits/object_safety.rs
  src/librustc/traits/specialize/mod.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/query/mod.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_traits/lowering/mod.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/outlives/explicit.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/simplify.rs
Labels: S-waiting-on-bors

#55865 Unix RwLock: avoid racy access to write_locked
  src/libstd/sys/unix/rwlock.rs
Labels: S-waiting-on-bors

#55901 fix various typos in doc comments
  src/liballoc/collections/btree/node.rs
  src/liballoc/raw_vec.rs
  src/libcore/num/f32.rs
  src/libcore/task/wake.rs
  src/libproc_macro/lib.rs
  src/librustc/dep_graph/cgu_reuse_tracker.rs
  src/librustc/hir/def.rs
  src/librustc/infer/canonical/canonicalizer.rs
  src/librustc/infer/canonical/query_response.rs
  src/librustc/infer/canonical/substitute.rs
  src/librustc/infer/error_reporting/nice_region_error/outlives_closure.rs
  src/librustc/infer/higher_ranked/mod.rs
  src/librustc/infer/mod.rs
  src/librustc/infer/type_variable.rs
  src/librustc/lint/levels.rs
  src/librustc/session/config.rs
  src/librustc/traits/query/dropck_outlives.rs
  src/librustc/ty/fold.rs
  src/librustc/ty/layout.rs
  src/librustc/ty/mod.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_codegen_utils/symbol_names.rs
  src/librustc_data_structures/graph/scc/mod.rs
  src/librustc_data_structures/owning_ref/mod.rs
  src/librustc_data_structures/sorted_map.rs
  src/librustc_driver/lib.rs
  src/librustc_incremental/persist/dirty_clean.rs
  src/librustc_lint/builtin.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/borrow_check/places_conflict.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/hair/mod.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustdoc/config.rs
  src/libstd/alloc.rs
  src/libstd/collections/hash/map.rs
  src/libstd/keyword_docs.rs
  src/libstd/net/ip.rs
  src/libstd/process.rs
  src/libstd/sys/redox/fd.rs
  src/libstd/sys/redox/syscall/call.rs
  src/libstd/sys/unix/fd.rs
  src/libstd/thread/mod.rs
  src/libsyntax/tokenstream.rs
  src/libsyntax_ext/deriving/generic/mod.rs
Labels: S-waiting-on-bors

#55926 Change sidebar selector to fix compatibility with docs.rs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#55930 A handful of hir tweaks
  src/librustc/hir/mod.rs
Labels: S-waiting-on-bors

#55936 save-analysis: be even more aggressive about ignorning macro-generated defs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/span_utils.rs
Labels: S-waiting-on-bors

#56017 std: Add debugging for a failing test on appveyor
  src/libstd/time.rs
Labels: S-waiting-on-bors

#55564 test/linkage-visibility: Ignore on musl targets
  src/test/run-pass-fulldeps/auxiliary/linkage-visibility.rs
Labels: S-waiting-on-bors

#55827 A few tweaks to iterations/collecting
  src/librustc/cfg/graphviz.rs
  src/librustc/hir/lowering.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/libserialize/hex.rs
  src/libsyntax_ext/deriving/generic/mod.rs
Labels: S-waiting-on-bors

#55857 remove unused dependency
  src/Cargo.lock
  src/librustc_data_structures/Cargo.toml
Labels: S-waiting-on-bors

#55862 in which the E0618 "expected function" diagnostic gets a makeover
  src/librustc_typeck/check/callee.rs
  src/test/ui/block-result/issue-20862.stderr
  src/test/ui/empty/empty-struct-unit-expr.stderr
  src/test/ui/error-codes/E0618.stderr
  src/test/ui/issues/issue-10969.stderr
  src/test/ui/issues/issue-18532.stderr
  src/test/ui/issues/issue-20714.stderr
  src/test/ui/issues/issue-21701.stderr
  src/test/ui/issues/issue-22468.stderr
  src/test/ui/issues/issue-26237.rs
  src/test/ui/issues/issue-26237.stderr
  src/test/ui/issues/issue-45965.stderr
  src/test/ui/issues/issue-46771.stderr
  src/test/ui/issues/issue-5100.stderr
  src/test/ui/parse-error-correct.stderr
  src/test/ui/resolve/privacy-enum-ctor.stderr
  src/test/ui/suggestions/issue-51055-missing-semicolon-between-call-and-tuple.rs
  src/test/ui/suggestions/issue-51055-missing-semicolon-between-call-and-tuple.stderr
Labels: S-waiting-on-bors

#55867 do not panic just because cargo failed
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#55919 core/tests/num: Simplify `test_int_from_str_overflow()` test code
  src/libcore/tests/num/mod.rs
Labels: S-waiting-on-bors

#55949 ty: return impl Iterator from Predicate::walk_tys
  src/librustc/ty/mod.rs
Labels: S-waiting-on-bors

#55953 #53488 Refactoring UpvarId
  src/librustc/ich/impls_ty.rs
  src/librustc/infer/error_reporting/mod.rs
  src/librustc/infer/error_reporting/note.rs
  src/librustc/middle/expr_use_visitor.rs
  src/librustc/middle/mem_categorization.rs
  src/librustc/ty/context.rs
  src/librustc/ty/mod.rs
  src/librustc/util/ppaux.rs
  src/librustc_borrowck/borrowck/gather_loans/mod.rs
  src/librustc_borrowck/borrowck/gather_loans/move_error.rs
  src/librustc_borrowck/borrowck/mod.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_typeck/check/upvar.rs
  src/librustc_typeck/check/writeback.rs
Labels: S-waiting-on-bors

#55962 rustdoc: properly calculate spans for intra-doc link resolution errors
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/intra-link-span-ice-55723.rs
  src/test/rustdoc-ui/intra-link-span-ice-55723.stderr
Labels: S-waiting-on-bors

#55963 Stress test for MPSC
  src/test/run-pass/mpsc_stress.rs
Labels: S-waiting-on-bors

#55968 Clean up some non-mod-rs stuff.
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
  src/test/run-pass/non_modrs_mods/foors_mod.rs
  src/test/run-pass/non_modrs_mods/foors_mod/inline/somename.rs
  src/test/run-pass/non_modrs_mods/modrs_mod/inline/somename.rs
  src/test/run-pass/non_modrs_mods/modrs_mod/mod.rs
  src/test/run-pass/non_modrs_mods/non_modrs_mods.rs
  src/test/ui/invalid-module-declaration/invalid-module-declaration.rs
  src/test/ui/missing_non_modrs_mod/foo_inline.rs
  src/test/ui/missing_non_modrs_mod/missing_non_modrs_mod.rs
  src/test/ui/missing_non_modrs_mod/missing_non_modrs_mod_inline.rs
  src/test/ui/missing_non_modrs_mod/missing_non_modrs_mod_inline.stderr
  src/test/ui/non_modrs_mods/foors_mod.rs
  src/test/ui/non_modrs_mods/foors_mod/compiletest-ignore-dir
  src/test/ui/non_modrs_mods/foors_mod/inner_foors_mod.rs
  src/test/ui/non_modrs_mods/foors_mod/inner_foors_mod/innest.rs
  src/test/ui/non_modrs_mods/foors_mod/inner_modrs_mod/innest.rs
  src/test/ui/non_modrs_mods/foors_mod/inner_modrs_mod/mod.rs
  src/test/ui/non_modrs_mods/modrs_mod/compiletest-ignore-dir
  src/test/ui/non_modrs_mods/modrs_mod/inner_foors_mod.rs
  src/test/ui/non_modrs_mods/modrs_mod/inner_foors_mod/innest.rs
  src/test/ui/non_modrs_mods/modrs_mod/inner_modrs_mod/innest.rs
  src/test/ui/non_modrs_mods/modrs_mod/inner_modrs_mod/mod.rs
  src/test/ui/non_modrs_mods/modrs_mod/mod.rs
  src/test/ui/non_modrs_mods/some_crazy_attr_mod_dir/arbitrary_name.rs
  src/test/ui/non_modrs_mods/some_crazy_attr_mod_dir/compiletest-ignore-dir
  src/test/ui/non_modrs_mods/some_crazy_attr_mod_dir/inner_modrs_mod/innest.rs
  src/test/ui/non_modrs_mods/some_crazy_attr_mod_dir/inner_modrs_mod/mod.rs
Labels: S-waiting-on-bors

#56011 Replace data.clone() by Arc::clone(&data) in mutex doc.
  src/libstd/sync/mutex.rs
Labels: S-waiting-on-bors

#56012 avoid shared ref in UnsafeCell::get
  src/libcore/cell.rs
Labels: S-waiting-on-bors

#56016 Add VecDeque::resize_with
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors

#56027 docs: Add missing backtick in object_safety.rs docs
  src/librustc/traits/object_safety.rs
Labels: S-waiting-on-bors

#56043 remove "approx env bounds" if we already know from trait
  src/librustc/infer/outlives/obligations.rs
  src/test/ui/nll/ty-outlives/issue-55756.rs
Labels: S-waiting-on-bors, beta-nominated

#56059 Increase `Duration` approximate equal threshold to 1us
  src/libstd/time.rs
Labels: S-waiting-on-bors

#56060 save-analysis: fallback to using path id
  src/librustc_save_analysis/lib.rs
Labels: S-waiting-on-bors

#55971 Ignore non-semantic tokens for 'probably_eq' streams.
  src/libsyntax/parse/token.rs
  src/libsyntax/tokenstream.rs
  src/test/ui-fulldeps/proc-macro/auxiliary/span-preservation.rs
  src/test/ui-fulldeps/proc-macro/span-preservation.rs
  src/test/ui-fulldeps/proc-macro/span-preservation.stderr
Labels: S-waiting-on-bors

#56081 Add temporary renames to manifests for rustfmt/clippy
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#55678 Updated RELEASES.md for 1.31.0
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#56117 resolve: Make "empty import canaries" invisible from other crates
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/auxiliary/issue-55811.rs
  src/test/ui/imports/issue-55811.rs
Labels: S-waiting-on-bors, beta-nominated

#56065 Replace the ICEing on const fn loops with an error
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/test/ui/consts/min_const_fn/loop_ice.rs
  src/test/ui/consts/min_const_fn/loop_ice.stderr
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#56147 resolve: Fix some asserts in import validation
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/auxiliary/issue-56125.rs
  src/test/ui/imports/issue-56125.rs
  src/test/ui/imports/issue-56125.stderr
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#53918 Doc total order requirement of sort(_unstable)_by
  src/liballoc/slice.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#55367 lint if a private item has doctests
  src/librustc/lint/builtin.rs
  src/librustdoc/core.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/private_items_doc_tests.rs
  src/test/rustdoc-ui/private-item-doc-test.rs
  src/test/rustdoc-ui/private-item-doc-test.stderr
Labels: S-waiting-on-bors

#55485 Return &T / &mut T in ManuallyDrop Deref(Mut) impl
  src/libcore/mem.rs
Labels: S-waiting-on-bors

#55784 Clarifying documentation for collections::hash_map::Entry::or_insert
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#55961 Fix VecDeque pretty-printer
  src/etc/gdb_rust_pretty_printing.py
  src/test/debuginfo/pretty-std-collections.rs
Labels: S-waiting-on-bors

#55980 Suggest on closure args count mismatching with pipe span
  src/librustc/traits/error_reporting.rs
  src/test/ui/mismatched_types/closure-arg-count.rs
  src/test/ui/mismatched_types/closure-arg-count.stderr
Labels: S-waiting-on-bors

#56002 fix #55972: Erroneous self arguments on bare functions emit subpar compilation error
  src/libsyntax/parse/parser.rs
  src/test/ui/invalid-self-argument/bare-fn-start.rs
  src/test/ui/invalid-self-argument/bare-fn-start.stderr
  src/test/ui/invalid-self-argument/bare-fn.rs
  src/test/ui/invalid-self-argument/bare-fn.stderr
  src/test/ui/invalid-self-argument/trait-fn.rs
  src/test/ui/invalid-self-argument/trait-fn.stderr
Labels: S-waiting-on-bors

#56063 Update any.rs documentation using keyword dyn
  src/libcore/any.rs
Labels: S-waiting-on-bors

#56078 Fix error message for `-C panic=xxx`.
  src/librustc/session/config.rs
  src/test/ui/panic-runtime/bad-panic-flag1.rs
  src/test/ui/panic-runtime/bad-panic-flag1.stderr
  src/test/ui/panic-runtime/bad-panic-flag2.rs
  src/test/ui/panic-runtime/bad-panic-flag2.stderr
Labels: S-waiting-on-bors

#56126 core/benches/num: Add `from_str/from_str_radix()` benchmarks
  src/libcore/benches/num/mod.rs
Labels: S-waiting-on-bors

#53586 Move Cargo.{toml,lock} to the repository root directory.
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  src/bootstrap/bootstrap.py
  src/bootstrap/dist.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/test/rustdoc-ui/failed-doctest-output.stdout
  src/tools/tidy/src/deps.rs
  src/tools/tidy/src/extdeps.rs
  src/tools/tidy/src/lib.rs
Labels: S-waiting-on-bors

#55767 Disable some pretty-printers when gdb is rust-enabled
  src/etc/gdb_rust_pretty_printing.py
  src/test/debuginfo/gdb-pretty-struct-and-enums.rs
Labels: S-waiting-on-bors

#55838 Fix #[cfg] for step impl on ranges
  src/libcore/iter/range.rs
Labels: S-waiting-on-bors

#55945 Ensure that the argument to `static_assert` is a `bool`
  src/librustc_data_structures/macros.rs
Labels: S-waiting-on-bors

#56022 When popping in CTFE, perform validation before jumping to next statement to have a better span for the error
  src/librustc_mir/interpret/eval_context.rs
Labels: S-waiting-on-bors
