Repository rust-lang/rust, pull requests merged in 2018-04, with the labels that each got.

#49527 Handle fast-submodules option correctly
  src/bootstrap/bootstrap.py
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#49522 Rename fs::read_string to read_to_string and stabilize
  src/librustc/util/common.rs
  src/librustdoc/html/render.rs
  src/libstd/fs.rs
Labels: C-enhancement, S-waiting-on-bors, T-libs

#49545 proc_macro: Tweak doc comments and negative literals
  src/libproc_macro/lib.rs
  src/test/compile-fail-fulldeps/proc-macro/auxiliary/attributes-included.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/negative-token.rs
  src/test/run-pass-fulldeps/proc-macro/negative-token.rs
Labels: S-waiting-on-bors

#49418 Clarify network byte order conversions for integer / IP address conversions.
  src/libstd/net/ip.rs
Labels: S-waiting-on-bors

#49478 Fix escaped backslash in windows file not found message
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#49549 Remove filetime dep from build_helper
  src/Cargo.lock
  src/bootstrap/compile.rs
  src/build_helper/Cargo.toml
  src/build_helper/lib.rs
Labels: S-waiting-on-bors

#49571 Update drop.rs
  src/libcore/ops/drop.rs
Labels: S-waiting-on-bors

#49574 Stabilize `std::process::id()`
  src/libstd/process.rs
Labels: S-waiting-on-bors

#49580 Use Alloc and Layout from core::heap.
  src/liballoc/arc.rs
  src/liballoc/boxed.rs
  src/liballoc/btree/node.rs
  src/liballoc/raw_vec.rs
  src/liballoc/rc.rs
  src/liballoc_jemalloc/lib.rs
  src/liballoc_system/lib.rs
  src/libstd/collections/hash/map.rs
  src/libstd/collections/hash/table.rs
Labels: S-waiting-on-bors

#49590 Bump to 1.27.0
  src/Cargo.lock
  src/bootstrap/channel.rs
  src/tools/linkchecker/main.rs
Labels: S-waiting-on-bors

#49098 Add Iterator::find_map
  src/libcore/iter/iterator.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors

#48647 Update sccache to its master branch
  .travis.yml
  appveyor.yml
  src/ci/docker/dist-various-1/Dockerfile
  src/ci/docker/run.sh
  src/ci/docker/scripts/sccache.sh
Labels: S-waiting-on-bors

#48333 Remove all unstable placement features
  src/grammar/parser-lalr.y
  src/liballoc/binary_heap.rs
  src/liballoc/boxed.rs
  src/liballoc/lib.rs
  src/liballoc/linked_list.rs
  src/liballoc/tests/binary_heap.rs
  src/liballoc/tests/lib.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/liballoc/vec.rs
  src/liballoc/vec_deque.rs
  src/libcore/ops/mod.rs
  src/libcore/ops/place.rs
  src/librustc/hir/lowering.rs
  src/librustc/ich/impls_syntax.rs
  src/librustc_lint/unused.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/lib.rs
  src/librustc_typeck/diagnostics.rs
  src/libstd/collections/hash/map.rs
  src/libstd/collections/hash/table.rs
  src/libstd/lib.rs
  src/libsyntax/ast.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/util/parser.rs
  src/libsyntax/visit.rs
  src/libsyntax_pos/hygiene.rs
  src/test/compile-fail/issue-14084.rs
  src/test/compile-fail/placement-expr-unsafe.rs
  src/test/compile-fail/placement-expr-unstable.rs
  src/test/parse-fail/assoc-oddities-1.rs
  src/test/pretty/stmt_expr_attributes.rs
  src/test/run-pass-fulldeps/ast_stmt_expr_attr.rs
  src/test/run-pass-fulldeps/pprust-expr-roundtrip.rs
  src/test/run-pass/new-box-syntax.rs
  src/test/run-pass/placement-in-syntax.rs
  src/test/ui/feature-gate-placement-expr.rs
  src/test/ui/feature-gate-placement-expr.stderr
Labels: S-waiting-on-bors, T-lang, final-comment-period

#48851 Stabilize attributes on generic parameters
  src/liballoc/lib.rs
  src/libarena/lib.rs
  src/librustc_typeck/diagnostics.rs
  src/libstd/lib.rs
  src/libsyntax/feature_gate.rs
  src/test/compile-fail/attrs-with-no-formal-in-generics-1.rs
  src/test/compile-fail/attrs-with-no-formal-in-generics-2.rs
  src/test/compile-fail/synthetic-param.rs
  src/test/mir-opt/end_region_destruction_extents_1.rs
  src/test/run-pass/attr-on-generic-formals.rs
  src/test/run-pass/auxiliary/dropck_eyepatch_extern_crate.rs
  src/test/run-pass/dropck-eyepatch-reorder.rs
  src/test/run-pass/dropck-eyepatch.rs
  src/test/ui/dropck/auxiliary/dropck_eyepatch_extern_crate.rs
  src/test/ui/dropck/dropck-eyepatch-implies-unsafe-impl.rs
  src/test/ui/dropck/dropck-eyepatch-implies-unsafe-impl.stderr
  src/test/ui/dropck/dropck-eyepatch-reorder.rs
  src/test/ui/dropck/dropck-eyepatch-reorder.stderr
  src/test/ui/dropck/dropck-eyepatch.rs
  src/test/ui/dropck/dropck-eyepatch.stderr
  src/test/ui/feature-gate-custom_attribute2.rs
  src/test/ui/feature-gate-custom_attribute2.stderr
  src/test/ui/feature-gate-generic_param_attrs.stderr
  src/test/ui/feature-gate-may-dangle.rs
  src/test/ui/feature-gate-may-dangle.stderr
  src/test/ui/generic-param-attrs.rs
  src/test/ui/nll/drop-may-dangle.rs
  src/test/ui/nll/drop-no-may-dangle.rs
  src/test/ui/nll/drop-no-may-dangle.stderr
Labels: S-waiting-on-bors, T-lang, relnotes

#48658 Add a generic CAS loop to std::sync::Atomic*
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors, T-libs

#49345 RFC 2008 non-exhaustive enums/structs: Finishing Touches
  src/librustc/diagnostics.rs
  src/librustc/hir/check_attr.rs
  src/test/compile-fail/rfc-2008-non-exhaustive/invalid-attribute.rs
Labels: S-waiting-on-bors

#49432 Flush executables to disk after linkage
  src/librustc_trans/back/link.rs
Labels: S-waiting-on-bors

#49496 Add more vec![... ; n] optimizations
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#49667 Add more features to rust_2018_preview
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#49674 ci: Remove x86_64-gnu-incremental builder
  .travis.yml
  src/ci/docker/x86_64-gnu-incremental/Dockerfile
Labels: S-waiting-on-bors

#49350 Expand macros in `extern {}` blocks
  src/librustc/hir/lowering.rs
  src/librustc/hir/map/def_collector.rs
  src/librustc_passes/ast_validation.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/sig.rs
  src/libsyntax/ast.rs
  src/libsyntax/ext/base.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/placeholders.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/visit.rs
  src/libsyntax_ext/deriving/custom.rs
  src/test/compile-fail-fulldeps/auxiliary/macro_crate_test.rs
  src/test/compile-fail-fulldeps/proc-macro/auxiliary/test-macros.rs
  src/test/compile-fail-fulldeps/proc-macro/macros-in-extern.rs
  src/test/compile-fail/macros-in-extern.rs
  src/test/parse-fail/duplicate-visibility.rs
  src/test/parse-fail/extern-no-fn.rs
  src/test/run-pass-fulldeps/auxiliary/macro_crate_test.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/test-macros.rs
  src/test/run-pass-fulldeps/proc-macro/macros-in-extern.rs
  src/test/run-pass/macros-in-extern.rs
  src/test/ui/feature-gate-macros_in_extern.rs
  src/test/ui/feature-gate-macros_in_extern.stderr
Labels: S-waiting-on-bors

#49686 typos
  src/libstd/lib.rs
  src/libstd/panic.rs
  src/libstd/sys/windows/pipe.rs
Labels: S-waiting-on-bors

#49697 Give a name to every CI job.
  .travis.yml
  appveyor.yml
  src/ci/docker/run.sh
  src/ci/run.sh
Labels: S-waiting-on-bors

#49705 Filter out missing components from manifests
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#49335 Remove unneeded trait implementations titles
  src/librustdoc/html/render.rs
  src/test/rustdoc/unneeded-trait-implementations-title.rs
Labels: S-waiting-on-bors

#49064 rustdoctest: suppress the default allow(unused) under --display-warnings
  src/librustdoc/markdown.rs
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#49623 update mdbook
  src/Cargo.lock
  src/tools/rustbook/Cargo.toml
Labels: S-waiting-on-bors, relnotes

#49222 Print query stack on ICEs
  src/librustc/ty/maps/plumbing.rs
  src/librustc/util/common.rs
  src/librustc_errors/lib.rs
Labels: S-waiting-on-bors

#49503 Inject the `compiler_builtins` crate whenever the `core` crate is injected
  src/Cargo.lock
  src/liballoc/Cargo.toml
  src/liballoc_jemalloc/Cargo.toml
  src/liballoc_system/Cargo.toml
  src/libpanic_abort/Cargo.toml
  src/libpanic_unwind/Cargo.toml
  src/libprofiler_builtins/Cargo.toml
  src/librustc_asan/Cargo.toml
  src/librustc_lsan/Cargo.toml
  src/librustc_msan/Cargo.toml
  src/librustc_tsan/Cargo.toml
  src/libstd/lib.rs
  src/libstd_unicode/Cargo.toml
  src/libsyntax/print/pprust.rs
  src/libsyntax/std_inject.rs
  src/libunwind/Cargo.toml
  src/rustc/dlmalloc_shim/Cargo.toml
  src/rustc/libc_shim/Cargo.toml
Labels: S-waiting-on-bors

#49510 Fix anchor position on fields
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#49652 Fix anchors issue when everything is collapsed
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/storage.js
Labels: S-waiting-on-bors

#49702 std: Inline some Termination-related methods
  src/libstd/process.rs
  src/libstd/sys/unix/process/process_common.rs
  src/libstd/sys/windows/process.rs
Labels: S-waiting-on-bors

#49731 add THUMB targets to rustup manifest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#49742 Using X headings instead of 0.X #49739
  src/doc/index.md
Labels: S-waiting-on-bors

#49750 bootstrap: Remove the fast path
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#49661 Bump the bootstrap compiler to 1.26.0 beta
  src/bootstrap/lib.rs
  src/bootstrap/tool.rs
  src/liballoc/benches/lib.rs
  src/liballoc/lib.rs
  src/liballoc/tests/lib.rs
  src/libcore/cmp.rs
  src/libcore/intrinsics.rs
  src/libcore/lib.rs
  src/libcore/macros.rs
  src/libcore/panicking.rs
  src/libcore/tests/lib.rs
  src/libpanic_unwind/gcc.rs
  src/libpanic_unwind/lib.rs
  src/libpanic_unwind/seh64_gnu.rs
  src/libpanic_unwind/windows.rs
  src/libproc_macro/lib.rs
  src/librustc/lib.rs
  src/librustc_apfloat/lib.rs
  src/librustc_apfloat/tests/ieee.rs
  src/librustc_borrowck/lib.rs
  src/librustc_const_math/lib.rs
  src/librustc_data_structures/lib.rs
  src/librustc_errors/lib.rs
  src/librustc_incremental/lib.rs
  src/librustc_lint/lib.rs
  src/librustc_metadata/lib.rs
  src/librustc_mir/lib.rs
  src/librustc_traits/lib.rs
  src/librustc_trans/lib.rs
  src/librustc_trans_utils/lib.rs
  src/librustc_typeck/lib.rs
  src/librustdoc/lib.rs
  src/libserialize/lib.rs
  src/libstd/lib.rs
  src/libstd/panicking.rs
  src/libsyntax/lib.rs
  src/libsyntax_pos/lib.rs
  src/libunwind/libunwind.rs
  src/stage0.txt
Labels: S-waiting-on-bors

#49672 Fix another circular deps link args issue
  src/librustc/middle/weak_lang_items.rs
  src/librustc_trans/base.rs
  src/librustc_trans/lib.rs
  src/test/run-make-fulldeps/std-core-cycle/Makefile
Labels: S-waiting-on-bors

#49704 Fix regression in defaults #49344
  src/librustc_typeck/check/wfcheck.rs
  src/test/run-pass/defaults-well-formedness.rs
Labels: S-waiting-on-bors

#49752 [incremental] Hash `Allocation`s
  src/librustc/ich/impls_ty.rs
  src/test/incremental/issue-49595/auxiliary/lit_a.rs
  src/test/incremental/issue-49595/auxiliary/lit_b.rs
  src/test/incremental/issue-49595/issue_49595.rs
Labels: S-waiting-on-bors, beta-nominated

#49758 miri: Make write_discriminant_value public
  src/librustc_mir/interpret/eval_context.rs
Labels: S-waiting-on-bors

#49759 rustbuild: Fix setting initial cargo
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#49771 Don't default to stage 1 with incremental
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#49774 configure.py --tools should set a list instead of a string
  src/bootstrap/configure.py
Labels: S-waiting-on-bors

#49770 Remove mention of CsvDumper
  src/librustc_save_analysis/dump_visitor.rs
Labels: S-waiting-on-bors

#49673 Correct a few stability attributes
  src/libcore/ascii.rs
  src/libcore/iter/range.rs
  src/libcore/panic.rs
  src/libstd/env.rs
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#49778 rustbuild: canonicalize prefix `install_sh`
  src/bootstrap/install.rs
Labels: S-waiting-on-bors

#49811 std: Be sure to modify atomics in tests
  src/libcore/tests/atomic.rs
Labels: S-waiting-on-bors

#49386 Add tcx in item_body_nested_bodies
  src/librustc_metadata/cstore_impl.rs
  src/librustc_metadata/decoder.rs
Labels: S-waiting-on-bors

#49681 Stabilize take_set_limit
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors, relnotes

#48270 Replace `structurally_resolved_type` in casts check.
  src/librustc_typeck/check/cast.rs
  src/librustc_typeck/check/mod.rs
  src/test/run-pass/cast.rs
  src/test/ui/order-dependent-cast-inference.rs
  src/test/ui/order-dependent-cast-inference.stderr
Labels: S-waiting-on-bors, T-lang

#49575 Stabilize `Option::filter`.
  src/libcore/option.rs
  src/librustc_typeck/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#49614 in which the non-shorthand patterns lint keeps its own counsel in macros
  src/librustc_lint/builtin.rs
  src/test/run-pass/issue-49588-non-shorthand-field-patterns-in-pattern-macro.rs
Labels: S-waiting-on-bors

#49734 proc_macro: Generalize `FromIterator` impl
  src/libproc_macro/lib.rs
Labels: S-waiting-on-bors

#49781 add regression test for #16223 (NLL): use of collaterally moved value
  src/test/ui/nll/issue-16223.rs
Labels: S-waiting-on-bors

#49795 Properly look for uninhabitedness of variants in niche-filling check
  src/librustc/ty/layout.rs
  src/test/run-pass/type-sizes.rs
Labels: S-waiting-on-bors

#49809 Stop emitting color codes on TERM=dumb
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#49849 Add --enable-debug flag to musl CI build script
  src/ci/docker/scripts/musl.sh
Labels: S-waiting-on-bors

#49856 Do not uppercase-lint #[no_mangle] statics
  src/librustc_lint/bad_style.rs
  src/test/compile-fail/lint-non-uppercase-statics.rs
Labels: S-waiting-on-bors

#49857 Fix "fp" target feature for AArch64
  src/librustc_trans/llvm_util.rs
Labels: S-waiting-on-bors

#49863 fixed typo
  src/tools/compiletest/src/header.rs
Labels: S-waiting-on-bors

#49551 Deprecate offset_to; switch core&alloc to using offset_from instead
  src/liballoc/lib.rs
  src/liballoc/vec.rs
  src/libcore/ptr.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#49360 Run rustfmt on build_helper
  src/build_helper/lib.rs
Labels: S-waiting-on-bors

#49800 traits: Implement interning for Goal and Clause
  src/librustc/traits/mod.rs
  src/librustc/traits/structural_impls.rs
  src/librustc/ty/context.rs
  src/librustc/ty/maps/mod.rs
  src/librustc_traits/lowering.rs
Labels: S-waiting-on-bors

#49830 Fix ICE by disallowing `impl Trait` in unsupported position
  src/librustc/hir/lowering.rs
  src/test/compile-fail/issue-47715.rs
Labels: S-waiting-on-bors, beta-nominated

#49326 macros: Remove matching on "complex" nonterminals requiring AST comparisons
  src/libsyntax/parse/token.rs
  src/test/ui/macros/nonterminal-matching.rs
  src/test/ui/macros/nonterminal-matching.stderr
Labels: S-waiting-on-bors, T-lang

#49396 Make OnDiskCache thread-safer
  src/librustc/ty/context.rs
  src/librustc/ty/maps/on_disk_cache.rs
Labels: S-waiting-on-bors

#49289 Make --emit=metadata output metadata regardless of link
  src/librustc_trans/back/link.rs
Labels: S-waiting-on-bors

#49465 Add docs for the test crate with the std docs
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors, T-doc, beta-nominated

#49852 proc_macro: Avoid cached TokenStream more often
  src/libsyntax/parse/token.rs
  src/libsyntax/tokenstream.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/modify-ast.rs
  src/test/run-pass-fulldeps/proc-macro/modify-ast.rs
Labels: S-waiting-on-bors

#49866 Cross-compile builder to Windows for PRs on Travis
  .travis.yml
  src/ci/docker/mingw-check/Dockerfile
Labels: S-waiting-on-bors

#49871 Add to_bytes and from_bytes to primitive integers
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, T-libs

#49876 Don't inject clippy into rls on stable/beta
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#49886 Ignore copyright year when generating deriving span tests
  src/etc/generate-deriving-span-tests.py
Labels: S-waiting-on-bors

#49908 Fix test failure in src/tools/rustdoc-themes when rust.rpath = false
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#49913 Use InternedString rather than Name for RegionParameterDef
  src/librustc/infer/mod.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/sty.rs
  src/librustc/util/ppaux.rs
  src/librustc_driver/test.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/collect.rs
  src/librustdoc/clean/auto_trait.rs
Labels: S-waiting-on-bors

#49915 [doc] note the special type inference handling for shift ops
  src/libcore/ops/bit.rs
Labels: S-waiting-on-bors

#49916 improve Atomic*::fetch_update docs
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#49922 Remove -Zmiri debugging option
  src/bootstrap/bin/rustc.rs
  src/bootstrap/test.rs
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#49843 [beta] Backport fix for regression in defaults
  src/librustc_typeck/check/wfcheck.rs
  src/test/run-pass/defaults-well-formedness.rs
Labels: S-waiting-on-bors

#49850 core: Inline `From<AllocErr> for CollectionAllocErr`
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#49880 [beta] [incremental] Hash `Allocation`s
  src/librustc/ich/impls_ty.rs
  src/test/incremental/issue-49595/auxiliary/lit_a.rs
  src/test/incremental/issue-49595/auxiliary/lit_b.rs
  src/test/incremental/issue-49595/issue_49595.rs
Labels: S-waiting-on-bors

#49884 core: Remove panics from some `Layout` methods
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#49885 Fix unsoundness bug in functions input references
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/test/ui/issue-48803.rs
  src/test/ui/issue-48803.stderr
Labels: S-waiting-on-bors

#49963 stabilize fetch_nand
  src/libcore/sync/atomic.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors

#48945 Replace manual iterator exhaust with for_each(drop)
  src/liballoc/btree/map.rs
  src/liballoc/linked_list.rs
  src/liballoc/vec.rs
  src/liballoc/vec_deque.rs
  src/librustc_data_structures/array_vec.rs
  src/libstd/collections/hash/table.rs
Labels: S-waiting-on-bors, T-libs

#49606 Prevent broken pipes causing ICEs
  src/librustc_driver/lib.rs
  src/librustdoc/lib.rs
  src/libstd/sys/unix/mod.rs
  src/rustc/rustc.rs
Labels: S-waiting-on-bors

#49646 Use box syntax instead of Box::new in Mutex::remutex on Windows
  src/libstd/sys/windows/mutex.rs
Labels: S-waiting-on-bors, T-libs

#49647 Remove `underscore_lifetimes` and `match_default_bindings` from active feature list
  src/librustc_trans/lib.rs
  src/librustc_typeck/lib.rs
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#49931 Fix incorrect span in `&mut` suggestion
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/nll/issue-47388.stderr
Labels: S-waiting-on-bors

#49965 Remove warning about f64->f32 cast being potential UB
  src/librustc_typeck/check/demand.rs
Labels: S-waiting-on-bors

#49994 Remove unnecessary indentation in rustdoc book codeblock.
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#50012 Don't look for cc/cxx when testing with bogus targets
  src/bootstrap/sanity.rs
Labels: S-waiting-on-bors

#50013 Remove no longer necessary comparison to Vec::splice.
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#50032 rustdoc: Don't include private paths in all.html
  src/librustdoc/html/render.rs
  src/test/rustdoc/all.rs
Labels: S-waiting-on-bors

#49972 Remove uses of Build across Builder steps
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/dist.rs
  src/bootstrap/doc.rs
  src/bootstrap/install.rs
  src/bootstrap/native.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/bootstrap/util.rs
Labels: S-waiting-on-bors

#49981 Properly handle ranges of signed enums using both extremums (fixes #49973)
  src/librustc/ty/layout.rs
  src/test/run-pass/issue-49973.rs
Labels: S-waiting-on-bors, beta-nominated

#49993 Change the hashcounts in raw `Lit` variants from usize to u16.
  src/libproc_macro/quote.rs
  src/libsyntax/ast.rs
  src/libsyntax/ext/build.rs
  src/libsyntax/ext/quote.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/token.rs
  src/libsyntax/print/pprust.rs
Labels: S-waiting-on-bors

#50006 Reorder injection of std to get better compilation error
  src/libsyntax/std_inject.rs
  src/test/ui/issue-49851/compiler-builtins-error.rs
  src/test/ui/issue-49851/compiler-builtins-error.stderr
Labels: S-waiting-on-bors

#50022 Only emit save-analysis data for `cargo build` tasks
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#50048 rustc_trans: also check dominators for SSA values in mir::analyze
  src/librustc_trans/mir/analyze.rs
  src/librustc_trans/mir/mod.rs
Labels: S-waiting-on-bors

#49949 Sign extend constants in range patterns
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/mod.rs
  src/test/ui/const-eval/const_signed_pat.rs
Labels: S-waiting-on-bors, beta-nominated

#48553 atomic: remove 'Atomic*' from Debug output
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#50051 Lazily evaluate EvalErrorKind::*.into() calls.
  src/librustc_mir/interpret/eval_context.rs
Labels: S-waiting-on-bors

#49991 Remove HIR inlining
  src/librustc/dep_graph/dep_node.rs
  src/librustc/hir/map/mod.rs
  src/librustc/ich/impls_cstore.rs
  src/librustc/middle/cstore.rs
  src/librustc/ty/maps/config.rs
  src/librustc/ty/maps/mod.rs
  src/librustc/ty/maps/plumbing.rs
  src/librustc_metadata/astencode.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_metadata/decoder.rs
  src/librustc_metadata/encoder.rs
  src/librustc_metadata/isolated_encoder.rs
  src/librustc_metadata/lib.rs
  src/librustc_metadata/schema.rs
  src/librustdoc/clean/inline.rs
Labels: S-waiting-on-bors

#50052 Avoid allocating when parsing \u{...} literals.
  src/libsyntax/parse/mod.rs
Labels: S-waiting-on-bors

#50058 Added build disk usage information
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#50083 wasm: Increase default stack size to 1MB
  src/librustc_trans/back/linker.rs
Labels: S-waiting-on-bors

#50104 Disable auto-detection of libxml2 when compiling llvm.
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#50114 Fix bad merge in #49991
  src/librustc_metadata/encoder.rs
Labels: S-waiting-on-bors

#50117 must explicitly request file name when using with_file_name.
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#50088 Tweak some stabilizations in libstd
  src/liballoc/btree/map.rs
  src/liballoc/str.rs
  src/librustdoc/test.rs
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors, T-libs, beta-accepted, beta-nominated

#50089 [beta] Tweak some stabilizations in libstd
  src/liballoc/btree/map.rs
  src/liballoc/str.rs
  src/librustdoc/test.rs
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#50076 Fix Iter exhaustion in prove_predicates when debug is on
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
Labels: S-waiting-on-bors

#50093 rustc: Always emit `uwtable` on Android
  src/librustc_back/target/android_base.rs
  src/librustc_back/target/mod.rs
  src/librustc_back/target/windows_base.rs
  src/librustc_back/target/windows_msvc_base.rs
  src/librustc_trans/base.rs
  src/test/codegen/nounwind.rs
Labels: S-waiting-on-bors

#50109 Implement Copy for std::alloc::Layout
  src/libcore/alloc.rs
Labels: S-waiting-on-bors, T-libs

#50123 Do not test RLS/Rustfmt if build failed
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#50152 parser: Do not override syntactic context for dummy spans
  src/libsyntax/parse/parser.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/issue-50061.rs
  src/test/run-pass-fulldeps/proc-macro/issue-50061.rs
Labels: S-waiting-on-bors

#50171 Update MDBook
  src/Cargo.lock
  src/tools/rustbook/Cargo.toml
Labels: S-waiting-on-bors

#50129 Clean up `IsolatedEncoder::encode_info_for_impl_item()` a bit
  src/librustc_metadata/encoder.rs
Labels: S-waiting-on-bors

#49372 Better error message when trying to write default impls
  src/librustc_passes/ast_validation.rs
Labels: S-waiting-on-bors

#50175 [beta] Backport - Improve assertion in Query::force().
  src/librustc/ty/maps/plumbing.rs
Labels: S-waiting-on-bors

#49368 Feature gate where clauses on associated types
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gate-generic_associated_types.rs
  src/test/ui/feature-gate-generic_associated_types.stderr
Labels: S-waiting-on-bors, T-lang, beta-nominated

#48989 Make signature of Path::strip_prefix accept non-references
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-libs, proposed-final-comment-period

#49461 std: Child::kill() returns error if process has already exited
  src/libstd/process.rs
Labels: S-waiting-on-bors, T-libs

#49906 Stabilize `std::hint::unreachable_unchecked`.
  src/libcore/hint.rs
  src/libcore/intrinsics.rs
  src/libcore/lib.rs
  src/libcore/macros.rs
  src/libcore/mem.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors, relnotes

#49985 don't see issue #0
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gate/issue-49983-see-issue-0.rs
  src/test/ui/feature-gate/issue-49983-see-issue-0.stderr
Labels: S-waiting-on-bors

#50118 fix search bar bug
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#50174 Use FxHashMap in syntax_pos::symbol::Interner::intern.
  src/libsyntax_pos/symbol.rs
Labels: S-waiting-on-bors

#49911 Don't allow #[should_panic] with non-() tests
  src/libsyntax/test.rs
  src/test/ui/rfc-1937-termination-trait/termination-trait-in-test-should-panic.rs
  src/test/ui/rfc-1937-termination-trait/termination-trait-in-test-should-panic.stderr
  src/test/ui/rfc-1937-termination-trait/termination-trait-in-test.rs
Labels: S-waiting-on-bors, T-compiler

#50079 Android abstract unix domain sockets AddressKind correction
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors

#50134 make rustdoc test follow the jobserver limit of threads
  src/librustc/session/mod.rs
  src/librustc_trans/back/write.rs
Labels: S-waiting-on-bors

#49321 Introduce compile-pass
  src/test/run-pass/compiletest-skip-trans.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#50131 Allow crate:: in local paths
  src/librustc_resolve/lib.rs
  src/test/compile-fail/rfc-2126-crate-paths/crate-path-non-absolute.rs
  src/test/compile-fail/rfc-2126-crate-paths/keyword-crate-as-identifier.rs
  src/test/run-pass/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs
Labels: S-waiting-on-bors

#50072 Allow variant discriminant initializers to refer to other initializer…
  src/librustc/ty/mod.rs
  src/librustc_mir/hair/cx/expr.rs
  src/test/ui/const-eval/enum_discr.rs
  src/test/ui/issue-23302-1.stderr
  src/test/ui/issue-23302-2.stderr
  src/test/ui/issue-36163.stderr
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated

#50177 mark std::str::replace(,n) as #[must_use]
  src/liballoc/lib.rs
  src/liballoc/str.rs
Labels: S-waiting-on-author

#50207 Hash EntryKind::AssociatedConst const data
  src/librustc_metadata/schema.rs
Labels: S-waiting-on-bors

#50214 Js improvements
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#50219 Added missing `.` in docs.
  src/liballoc/arc.rs
Labels: S-waiting-on-bors, T-doc

#50248 [beta] Backport #50072
  src/librustc/ty/mod.rs
  src/librustc_mir/hair/cx/expr.rs
  src/test/ui/const-eval/enum_discr.rs
  src/test/ui/issue-23302-1.stderr
  src/test/ui/issue-23302-2.stderr
  src/test/ui/issue-36163.rs
  src/test/ui/issue-36163.stderr
Labels: S-waiting-on-bors

#50254 [beta] Remove dependency on `parking_lot`
  src/Cargo.lock
  src/ci/docker/x86_64-gnu-debug/Dockerfile
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/lib.rs
Labels: S-waiting-on-bors

#49420 Use ScalarPair for tagged enums
  src/librustc/ty/layout.rs
  src/test/codegen/align-struct.rs
  src/test/codegen/function-arguments.rs
  src/test/codegen/lifetime_start_end.rs
Labels: S-waiting-on-bors

#49894 Rename InternedString to LocalInternedString and introduce a new thread-safe InternedString
  src/librustc/hir/lowering.rs
  src/librustc/hir/map/def_collector.rs
  src/librustc/hir/map/definitions.rs
  src/librustc/ich/impls_syntax.rs
  src/librustc/lib.rs
  src/librustc/traits/on_unimplemented.rs
  src/librustc/ty/context.rs
  src/librustc/ty/item_path.rs
  src/librustc/ty/maps/values.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/sty.rs
  src/librustc/util/ppaux.rs
  src/librustc_driver/test.rs
  src/librustc_incremental/assert_module_sources.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_metadata/decoder.rs
  src/librustc_mir/build/expr/into.rs
  src/librustc_mir/interpret/const_eval.rs
  src/librustc_mir/monomorphize/item.rs
  src/librustc_mir/monomorphize/partitioning.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_trans/back/symbol_export.rs
  src/librustc_trans/base.rs
  src/librustc_trans/callee.rs
  src/librustc_trans/common.rs
  src/librustc_trans/consts.rs
  src/librustc_trans/context.rs
  src/librustc_trans/debuginfo/metadata.rs
  src/librustc_trans/debuginfo/mod.rs
  src/librustc_trans/debuginfo/namespace.rs
  src/librustc_trans/debuginfo/type_names.rs
  src/librustc_trans/intrinsic.rs
  src/librustc_trans/mir/block.rs
  src/librustc_trans/trans_item.rs
  src/librustc_trans_utils/symbol_names.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/intrinsic.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/collect.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
  src/libsyntax_pos/symbol.rs
Labels: S-waiting-on-bors

#50222 Bump bootstrap compiler to 2018-04-24
  src/stage0.txt
Labels: S-waiting-on-bors

#50227 Fix ICE with erroneous `impl Trait` in a trait impl
  src/librustc_typeck/check/compare_method.rs
  src/test/compile-fail/impl-trait/impl-generic-mismatch.rs
Labels: S-waiting-on-bors

#50229 Add setting to go to item if there is only one result
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#50231 Add more doc aliases
  src/libcore/cmp.rs
  src/libcore/fmt/mod.rs
  src/libcore/ops/bit.rs
  src/libcore/ops/deref.rs
  src/libcore/ops/range.rs
Labels: S-waiting-on-bors

#50246 Make dump_{alloc,allocs,local}() no-ops when tracing is disabled.
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#50137 Remove hack around comparisons of i1 values (fixes #40980)
  src/librustc_trans/mir/rvalue.rs
Labels: S-waiting-on-bors

#50192 Add some utilities to `libsyntax`
  src/libproc_macro/lib.rs
  src/libsyntax_pos/hygiene.rs
  src/libsyntax_pos/lib.rs
Labels: S-waiting-on-bors

#50251 rustc: Disable threads in LLD for wasm
  src/librustc_trans/back/linker.rs
Labels: S-waiting-on-bors
