Repository rust-lang/rust, pull requests merged in 2018-08, with the labels that each got.

#52756 rustc: Disallow machine applicability in foreign macros
  src/librustc/lint/mod.rs
  src/librustc_errors/diagnostic_builder.rs
  src/test/ui-fulldeps/rust-2018/auxiliary/suggestions-not-always-applicable.rs
  src/test/ui-fulldeps/rust-2018/suggestions-not-always-applicable.fixed
  src/test/ui-fulldeps/rust-2018/suggestions-not-always-applicable.rs
  src/test/ui-fulldeps/rust-2018/suggestions-not-always-applicable.stderr
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#52340 Document From trait implementations for OsStr, OsString, CString, and CStr
  src/libstd/ffi/c_str.rs
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors

#52771 Clarify thread::park semantics
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#52778 Improve readability of serialize.rs
  src/libserialize/serialize.rs
Labels: S-waiting-on-bors

#52810 [NLL] Don't make "fake" match variables mutable
  src/librustc_mir/build/matches/mod.rs
  src/test/ui/nll/extra-unused-mut.rs
Labels: S-waiting-on-bors

#52822 Fix From<LocalWaker>
  src/libcore/task/wake.rs
Labels: S-waiting-on-bors

#52824 Fix -Wpessimizing-move warnings in rustllvm/PassWrapper
  src/rustllvm/PassWrapper.cpp
Labels: S-waiting-on-bors

#52825 Make sure #47772 does not regress
  src/test/codegen/slice-position-bounds-check.rs
Labels: S-waiting-on-bors

#52831 remove references to AUTHORS.txt file
  COPYRIGHT
  src/doc/man/rustdoc.1
Labels: S-waiting-on-bors

#52842 update comment
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#52846 Add timeout to use of `curl` in bootstrap.py.
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#52853 Improve bootstrap help on stages
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#52859 Use Vec::extend in SmallVec::extend when applicable
  src/librustc_data_structures/small_vec.rs
Labels: S-waiting-on-bors

#52867 releases.md: fix 2 typos
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#52870 Implement Unpin for FutureObj and LocalFutureObj
  src/libcore/future/future_obj.rs
Labels: S-waiting-on-bors

#52876 run-pass/const-endianness: negate before to_le()
  src/test/run-pass/const-endianess.rs
Labels: S-waiting-on-bors

#52878 Fix wrong issue number in the test name
  src/test/ui/nll/issue-52113.rs
  src/test/ui/nll/issue-52113.stderr
Labels: S-waiting-on-bors

#52883 Include lifetime in mutability suggestion in NLL messages
  src/librustc_mir/borrow_check/mutability_errors.rs
  src/test/ui/did_you_mean/issue-39544.nll.stderr
  src/test/ui/span/borrowck-borrow-overloaded-auto-deref-mut.nll.stderr
  src/test/ui/span/borrowck-borrow-overloaded-deref-mut.nll.stderr
  src/test/ui/span/mut-arg-hint.nll.stderr
  src/test/ui/trivial-bounds-inconsistent-copy-reborrow.nll.stderr
Labels: S-waiting-on-bors

#52888 Use suggestions for shell format arguments
  src/libsyntax_ext/format_foreign.rs
  src/test/ui/macros/format-foreign.rs
  src/test/ui/macros/format-foreign.stderr
  src/test/ui/macros/format-unused-lables.stderr
Labels: S-waiting-on-bors

#52907 NLL: On "cannot move out of type" error, print original before rewrite
  src/librustc_mir/borrow_check/move_errors.rs
  src/test/ui/borrowck/borrowck-move-error-with-note.nll.stderr
  src/test/ui/borrowck/borrowck-move-out-of-vec-tail.nll.stderr
  src/test/ui/borrowck/borrowck-vec-pattern-nesting.nll.stderr
  src/test/ui/borrowck/issue-51415.nll.stderr
  src/test/ui/codemap_tests/overlapping_spans.nll.stderr
  src/test/ui/issue-12567.nll.stderr
  src/test/ui/nll/move-errors.stderr
Labels: S-waiting-on-bors

#52914 Only run the sparc-abi test on sparc
  src/test/codegen/sparc-struct-abi.rs
Labels: S-waiting-on-bors

#52918 Backport 1.27.2 release notes
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#52929 Update compatibility note for 1.28.0 to be correct
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#52474 rustc: Handle linker diagnostics from LLVM
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm/diagnostic.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/rustllvm/RustWrapper.cpp
  src/test/compile-fail/auxiliary/lto-duplicate-symbols1.rs
  src/test/compile-fail/auxiliary/lto-duplicate-symbols2.rs
  src/test/compile-fail/lto-duplicate-symbols.rs
Labels: S-waiting-on-bors

#51609 Treat gc=No characters as numeric
  src/libcore/char/methods.rs
  src/libcore/tests/char.rs
  src/libcore/unicode/tables.rs
  src/libcore/unicode/unicode.py
Labels: S-waiting-on-bors, T-libs

#52793 Add test for NLL: unexpected "free region `` does not outlive" error
  src/test/ui/issue-49824.nll.stderr
  src/test/ui/issue-49824.rs
  src/test/ui/issue-49824.stderr
Labels: S-waiting-on-bors

#52809 Add test for unexpected region for local data ReStatic
  src/test/ui/issue-49579.rs
Labels: S-waiting-on-bors

#52834 [NLL] Allow conflicting borrows of promoted length zero arrays
  src/librustc_mir/borrow_check/places_conflict.rs
  src/test/ui/nll/promotable-mutable-zst-doesnt-conflict.rs
Labels: S-waiting-on-bors

#52854 fix memrchr in miri
  src/libcore/slice/memchr.rs
Labels: S-waiting-on-bors

#52899 tests/ui: Add missing mips{64} ignores
  src/test/ui/asm-out-assign-imm.nll.stderr
  src/test/ui/asm-out-assign-imm.rs
  src/test/ui/asm-out-assign-imm.stderr
  src/test/ui/target-feature-gate.rs
  src/test/ui/target-feature-gate.stderr
  src/test/ui/target-feature-wrong.rs
  src/test/ui/target-feature-wrong.stderr
Labels: S-waiting-on-bors

#52908 Use SetLenOnDrop in Vec::truncate()
  src/liballoc/vec.rs
  src/test/codegen/vec-clear.rs
Labels: S-waiting-on-bors

#52915 Don't count MIR locals as borrowed after StorageDead when finding locals live across a yield terminator
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/transform/generator.rs
  src/test/run-pass/generator/yield-in-initializer.rs
Labels: S-waiting-on-bors

#52926 rustc: Trim down the `rust_2018_idioms` lint group
  src/librustc_lint/lib.rs
  src/test/ui/rust-2018/macro-use-warned-against.rs
  src/test/ui/rust-2018/macro-use-warned-against.stderr
Labels: S-waiting-on-bors

#52930 rustc_resolve: record single-segment extern crate import resolutions.
  src/librustc_resolve/resolve_imports.rs
  src/test/compile-fail/auxiliary/issue-52489.rs
  src/test/compile-fail/issue-52489.rs
Labels: S-waiting-on-bors

#52939 Make io::Read::read_to_end consider io::Take::limit
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#52942 Another SmallVec.extend optimization
  src/librustc_data_structures/small_vec.rs
Labels: S-waiting-on-bors

#52947 1.27 actually added the `armv5te-unknown-linux-musleabi` target
  RELEASES.md
Labels: S-waiting-on-bors

#52954 async can begin expressions
  src/libsyntax/parse/token.rs
  src/test/ui/async-matches-expr.rs
Labels: S-waiting-on-bors

#52847 Don't commit thread stack on Windows
  src/libstd/sys/windows/c.rs
  src/libstd/sys/windows/thread.rs
Labels: S-waiting-on-bors, relnotes

#52906 enable jemalloc assertions when configured to do so
  src/liballoc_jemalloc/build.rs
Labels: S-waiting-on-bors

#52975 NLL migration in the 2018 edition needs two-phase borrows too!
  src/librustc/ty/context.rs
  src/test/ui/borrowck/issue-52967-edition-2018-needs-two-phase-borrows.rs
Labels: S-waiting-on-bors

#52949 Switch to bootstrapping from 1.29 beta
  src/bootstrap/channel.rs
  src/liballoc/lib.rs
  src/liballoc/task.rs
  src/libcore/alloc.rs
  src/libcore/intrinsics.rs
  src/libcore/manually_drop_stage0.rs
  src/libcore/mem.rs
  src/libcore/sync/atomic.rs
  src/librustc/hir/lowering.rs
  src/librustc/ich/impls_syntax.rs
  src/libstd/alloc.rs
  src/libstd/macros.rs
  src/libsyntax_pos/hygiene.rs
  src/stage0.txt
  src/test/ui/macros/trace-macro.stderr
Labels: S-waiting-on-bors

#52925 check_const: use the same ParamEnv as codegen for statics
  src/librustc_lint/builtin.rs
Labels: S-waiting-on-bors

#52887 Disable debug sections when optimization flags is set for LLD.
  src/librustc_codegen_llvm/back/linker.rs
Labels: S-waiting-on-bors

#52973 NLL mentions lifetimes that are not included in printed span(s).
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/test/ui/impl-trait/static-return-lifetime-infered.nll.stderr
  src/test/ui/issue-10291.nll.stderr
  src/test/ui/issue-52213.nll.stderr
  src/test/ui/nll/closure-requirements/region-lbr-named-does-not-outlive-static.stderr
  src/test/ui/nll/mir_check_cast_closure.stderr
  src/test/ui/nll/mir_check_cast_unsize.stderr
  src/test/ui/nll/ty-outlives/projection-one-region-closure.stderr
  src/test/ui/nll/ty-outlives/projection-one-region-trait-bound-closure.stderr
  src/test/ui/nll/ty-outlives/projection-two-region-trait-bound-closure.stderr
Labels: S-waiting-on-bors

#53035 travis: Attempt to debug shutdowns
  .travis.yml
Labels: S-waiting-on-bors

#52997 data_structures: make TinyList more readable and optimize remove(_)
  src/librustc_data_structures/tiny_list.rs
Labels: S-waiting-on-bors

#52332 dead-code lint: say "constructed" for structs
  src/librustc/middle/dead.rs
  src/test/compile-fail/lint-dead-code-1.rs
  src/test/compile-fail/lint-dead-code-3.rs
  src/test/ui/span/macro-span-replacement.rs
  src/test/ui/span/macro-span-replacement.stderr
  src/test/ui/span/unused-warning-point-at-signature.rs
  src/test/ui/span/unused-warning-point-at-signature.stderr
Labels: S-waiting-on-bors

#53045 Fix NLL migration mode so that reports region errors when necessary.
  src/librustc/infer/error_reporting/mod.rs
  src/test/ui/borrowck/issue-45983.ast.stderr
  src/test/ui/borrowck/issue-45983.migrate.stderr
  src/test/ui/borrowck/issue-45983.nll.stderr
  src/test/ui/borrowck/issue-45983.rs
Labels: S-waiting-on-bors, beta-nominated

#53115 Disable some nice region errors in NLL mode.
  src/librustc/infer/error_reporting/nice_region_error/mod.rs
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/mod.rs
  src/test/compile-fail/nll/where_clauses_in_functions.rs
  src/test/compile-fail/nll/where_clauses_in_structs.rs
  src/test/ui/in-band-lifetimes/mismatched.nll.stderr
  src/test/ui/lifetime-errors/ex1-return-one-existing-name-if-else-using-impl.nll.stderr
  src/test/ui/lifetime-errors/ex1-return-one-existing-name-return-type-is-anon.nll.stderr
  src/test/ui/lifetime-errors/ex1-return-one-existing-name-self-is-anon.nll.stderr
  src/test/ui/lifetime-errors/ex2b-push-no-existing-names.nll.stderr
  src/test/ui/lifetime-errors/ex2c-push-inference-variable.nll.stderr
  src/test/ui/lifetime-errors/ex2d-push-inference-variable-2.nll.stderr
  src/test/ui/lifetime-errors/ex2e-push-inference-variable-3.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-2.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-3.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs-2.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs-3.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs-4.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs-earlybound-regions.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs-latebound-regions.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-both-are-structs.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-latebound-regions.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-one-is-struct-2.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-one-is-struct-3.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-one-is-struct-4.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-one-is-struct.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-return-type-is-anon.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-self-is-anon.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-using-fn-items.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-using-impl-items.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions-using-trait-objects.nll.stderr
  src/test/ui/lifetime-errors/ex3-both-anon-regions.nll.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-ref.rs
  src/test/ui/nll/closure-requirements/propagate-approximated-ref.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-val.rs
  src/test/ui/nll/closure-requirements/propagate-approximated-val.stderr
  src/test/ui/nll/closure-requirements/region-lbr1-does-not-outlive-ebr2.rs
  src/test/ui/nll/closure-requirements/region-lbr1-does-not-outlive-ebr2.stderr
  src/test/ui/nll/issue-52113.rs
  src/test/ui/nll/issue-52113.stderr
Labels: S-waiting-on-bors

#53134 More debugging for travis shutting down
  .travis.yml
Labels: S-waiting-on-bors

#52885 Remove some unused method arguments from typeck
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/coherence/builtin.rs
Labels: S-waiting-on-bors

#52886 cleanup: Remove `Def::GlobalAsm`
  src/librustc/hir/def.rs
  src/librustc/hir/map/mod.rs
  src/librustc/ich/impls_hir.rs
  src/librustc_metadata/decoder.rs
  src/librustc_save_analysis/lib.rs
Labels: S-waiting-on-bors

#53028 Building librustc_codegen_llvm in a separate directory
  src/Cargo.lock
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/lib.rs
  src/librustc_codegen_llvm/Cargo.toml
Labels: S-waiting-on-bors

#53052 fixed broken links to char
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#53060 Change rustdoc style so fully qualified name does not overlap src link
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#53068 Rename Executor trait to Spawn
  src/liballoc/boxed.rs
  src/libcore/task/context.rs
  src/libcore/task/mod.rs
  src/libcore/task/spawn.rs
  src/test/run-pass/async-await.rs
  src/test/run-pass/futures-api.rs
Labels: S-waiting-on-bors

#53093 Enable macros to pass $:literal to another macro
  src/libsyntax/parse/token.rs
  src/test/run-pass/issue-52169.rs
Labels: S-waiting-on-bors

#53107 Remove references to `StaticMutex` which got removed a while ago
  src/librustc_mir/diagnostics.rs
  src/libstd/sync/once.rs
  src/libstd/sys/unix/mutex.rs
Labels: S-waiting-on-bors

#53135 Rust 2018: Disable catch_expr, not targeted for 2018 edition
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#53139 set emit_debug_gdb_scripts: false for riscv32imac-unknown-none target
  src/librustc_target/spec/riscv32imac_unknown_none_elf.rs
Labels: S-waiting-on-bors

#52911 Add HirId to VisibilityKind::Restricted
  src/librustc/hir/intravisit.rs
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/lint/context.rs
  src/librustc/lint/mod.rs
  src/librustc/middle/dead.rs
  src/librustc/middle/resolve_lifetime.rs
  src/librustc/middle/stability.rs
  src/librustc_lint/builtin.rs
  src/librustc_passes/hir_stats.rs
  src/librustc_privacy/lib.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
Labels: S-waiting-on-bors

#52993 rustc: Tweak visibility of some lang items
  src/librustc/middle/reachable.rs
  src/librustc_allocator/expand.rs
  src/librustc_codegen_llvm/allocator.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_mir/monomorphize/partitioning.rs
  src/test/run-make/wasm-symbols-not-exported/Makefile
  src/test/run-make/wasm-symbols-not-exported/bar.rs
  src/test/run-make/wasm-symbols-not-exported/foo.rs
  src/test/run-make/wasm-symbols-not-exported/verify-exported-symbols.js
Labels: S-waiting-on-bors

#53088 [NLL] Use span of the closure args in free region errors
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/test/ui/error-codes/E0621-does-not-trigger-for-closures.nll.stderr
  src/test/ui/issue-40510-1.nll.stderr
  src/test/ui/issue-40510-3.nll.stderr
  src/test/ui/issue-49824.nll.stderr
  src/test/ui/nll/issue-48238.stderr
Labels: S-waiting-on-bors

#53100 Fix improper_ctypes lint for individual foreign items
  src/librustc_lint/types.rs
  src/test/ui/lint-ctypes.rs
Labels: S-waiting-on-bors

#52773 Avoid unnecessary pattern matching against Option and Result
  src/librustc/traits/auto_trait.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/query/outlives_bounds.rs
  src/librustc/traits/select.rs
  src/librustc/ty/instance.rs
  src/librustc_errors/emitter.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/json_dumper.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/core.rs
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/markdown.rs
  src/libsyntax/test.rs
  src/libsyntax_ext/env.rs
Labels: S-waiting-on-bors

#53082 Fix doc link (again)
  src/libcore/marker.rs
  src/test/ui/const-unsized.stderr
  src/test/ui/error-codes/E0277.stderr
  src/test/ui/feature-gate-trivial_bounds.stderr
  src/test/ui/generator/sized-yield.stderr
  src/test/ui/issue-14366.stderr
  src/test/ui/issue-15756.stderr
  src/test/ui/issue-17651.stderr
  src/test/ui/issue-18107.stderr
  src/test/ui/issue-18919.stderr
  src/test/ui/issue-20005.stderr
  src/test/ui/issue-20433.stderr
  src/test/ui/issue-20605.stderr
  src/test/ui/issue-22874.stderr
  src/test/ui/issue-23281.stderr
  src/test/ui/issue-24446.stderr
  src/test/ui/issue-27060-2.stderr
  src/test/ui/issue-27078.stderr
  src/test/ui/issue-35988.stderr
  src/test/ui/issue-38954.stderr
  src/test/ui/issue-41229-ref-str.stderr
  src/test/ui/issue-42312.stderr
  src/test/ui/issue-5883.stderr
  src/test/ui/mismatched_types/cast-rfc0401.stderr
  src/test/ui/resolve/issue-5035-2.stderr
  src/test/ui/str-array-assignment.stderr
  src/test/ui/trait-suggest-where-clause.stderr
  src/test/ui/trivial-bounds-leak.stderr
  src/test/ui/union/union-sized-field.stderr
  src/test/ui/unsized-enum2.stderr
Labels: S-waiting-on-bors

#53094 Automatically expand section if url id point to one of its component
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#53106 atomic ordering docs
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#53110 Account for --remap-path-prefix in save-analysis
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/span_utils.rs
Labels: S-waiting-on-bors

#53116 NetBSD: fix signedess of char
  src/libstd/os/raw/mod.rs
Labels: S-waiting-on-bors

#53183 Suggest comma when missing in macro call
  src/libsyntax/ext/tt/macro_rules.rs
  src/libsyntax/tokenstream.rs
  src/test/ui/macros/missing-comma.rs
  src/test/ui/macros/missing-comma.stderr
Labels: S-waiting-on-bors

#53207 Add individual docs for rotate_{left, right}
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#53215 Slightly refactor syntax_ext/format
  src/libsyntax_ext/format.rs
Labels: S-waiting-on-bors

#53217 inline some short functions
  src/libcore/cmp.rs
  src/libcore/option.rs
  src/libcore/result.rs
Labels: S-waiting-on-bors

#53222 A few cleanups for rustc_target
  src/librustc_target/abi/call/mips64.rs
  src/librustc_target/abi/call/mod.rs
  src/librustc_target/abi/call/x86_64.rs
  src/librustc_target/abi/mod.rs
  src/librustc_target/spec/abi.rs
  src/librustc_target/spec/apple_base.rs
  src/librustc_target/spec/apple_ios_base.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#53131 NLL says something "does not live long enough" when talking about a (thread-local) static
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/diagnostics.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/test/compile-fail/borrowck/borrowck-thread-local-static-borrow-outlives-fn.rs
  src/test/ui/issue-17954.ast.stderr
  src/test/ui/issue-17954.mir.stderr
  src/test/ui/issue-17954.nll.stderr
  src/test/ui/issue-17954.rs
  src/test/ui/issue-17954.stderr
Labels: S-waiting-on-bors

#52895 run-pass/simd-intrinsic-float-minmax: Force use of qNaN on Mips
  src/test/run-pass/simd-intrinsic-float-minmax.rs
Labels: S-waiting-on-bors

#53335 rustc_resolve: crates only exist in the type namespace.
  src/librustc_resolve/resolve_imports.rs
  src/test/run-pass/issue-53333.rs
Labels: S-waiting-on-bors

#53208 Don't panic on std::env::vars() when env is null.
  src/libstd/sys/unix/os.rs
  src/test/run-pass/env-null-vars.rs
Labels: S-waiting-on-bors

#53226 driver: set the syntax edition in phase 1
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
  src/librustdoc/test.rs
  src/test/rustdoc/async-fn.rs
Labels: S-waiting-on-bors

#53233 targets: aarch64: Add bare-metal aarch64 target
  src/librustc_target/spec/aarch64_unknown_none.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#53239 rustc_codegen_llvm: Restore the closure env alloca hack for LLVM 5.
  src/librustc_codegen_llvm/mir/mod.rs
Labels: S-waiting-on-bors, beta-nominated

#53246 A few cleanups
  src/libfmt_macros/lib.rs
  src/libgraphviz/lib.rs
  src/librustc_apfloat/ieee.rs
  src/librustc_target/spec/mod.rs
  src/libserialize/hex.rs
  src/libserialize/json.rs
  src/libserialize/leb128.rs
  src/libterm/terminfo/mod.rs
  src/libterm/terminfo/parm.rs
  src/libterm/win.rs
Labels: S-waiting-on-bors

#53257 Idiomatic improvements to IP method
  src/libstd/net/ip.rs
Labels: S-waiting-on-bors

#53274 Remove statics field from CodegenCx
  src/librustc_codegen_llvm/consts.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/mono_item.rs
Labels: S-waiting-on-bors

#53290 Make LLVM emit assembly comments with -Z asm-comments
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/rustllvm/PassWrapper.cpp
Labels: S-waiting-on-bors

#53317 Mark prior failure to avoid ICE
  src/librustc_typeck/check/mod.rs
  src/test/ui/issue-53251.rs
  src/test/ui/issue-53251.stderr
Labels: S-waiting-on-bors

#52936 Document #39364 – Panic in mpsc::Receiver::recv_timeout
  src/libstd/sync/mpsc/mod.rs
Labels: S-waiting-on-bors

#53133 Record adjustments and original type for expressions in the generator interior
  src/librustc_typeck/check/generator_interior.rs
  src/test/run-pass/generator/issue-52398.rs
Labels: S-waiting-on-bors

#53237 Export WASM table by default
  src/librustc_codegen_llvm/back/linker.rs
Labels: S-waiting-on-bors

#52453 improve diagnostics for tests with custom return values
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#53271 use ? to simplify `TransitiveRelation.maybe_map`
  src/librustc_data_structures/transitive_relation.rs
Labels: S-waiting-on-bors

#53279 Extend documentation of `rustc_on_unimplemented`
  src/doc/unstable-book/src/language-features/on-unimplemented.md
Labels: S-waiting-on-bors

#53342 fix error for unsized packed struct field
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/mod.rs
  src/librustc/traits/structural_impls.rs
  src/librustc_typeck/check/wfcheck.rs
  src/test/ui/issues/issue-27060-2.stderr
Labels: S-waiting-on-bors

#53344 Add doc examples for std::alloc::{alloc,alloc_zeroed}.
  src/liballoc/alloc.rs
Labels: S-waiting-on-bors

#53368 Ignore test that fails on stage1
  src/test/ui/macros/macros-nonfatal-errors.rs
  src/test/ui/macros/macros-nonfatal-errors.stderr
Labels: S-waiting-on-bors

#53388 Fix links' color
  src/Cargo.lock
  src/librustdoc/Cargo.toml
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#53396 Fix since of Iterator::flatten to be a proper semver
  src/libcore/iter/iterator.rs
  src/libcore/iter/mod.rs
Labels: S-waiting-on-bors

#53289 A few cleanups and minor improvements for the lexer
  src/libsyntax/parse/lexer/comments.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/lexer/tokentrees.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
Labels: S-waiting-on-bors

#53295 Various changes to `rustc_on_unimplemented`
  src/librustc/traits/on_unimplemented.rs
  src/test/ui/error-codes/E0232.stderr
  src/test/ui/on-unimplemented/bad-annotation.rs
  src/test/ui/on-unimplemented/bad-annotation.stderr
Labels: S-waiting-on-bors

#53173 Start adding an `aarch64-pc-windows-msvc` target
  src/libpanic_unwind/dummy.rs
  src/libpanic_unwind/lib.rs
  src/libpanic_unwind/macros.rs
  src/librustc_target/spec/aarch64_pc_windows_msvc.rs
  src/librustc_target/spec/mod.rs
  src/libstd/sys/windows/backtrace/mod.rs
  src/libstd/sys/windows/c.rs
  src/libstd/sys/windows/mod.rs
Labels: S-waiting-on-bors

#53256 Don't accept non-string literals for the format string in writeln
  src/libcore/macros.rs
  src/test/ui/macros/issue-30143.rs
  src/test/ui/macros/issue-30143.stderr
Labels: S-waiting-on-bors

#52946 Documented impl From on line 367 of libserialize/json.rs
  src/libserialize/json.rs
Labels: S-waiting-on-bors

#53313 Two small improvements
  src/librustc_apfloat/ieee.rs
  src/libserialize/json.rs
Labels: S-waiting-on-bors

#53360 Addressed #51602
  src/libsyntax/parse/parser.rs
  src/test/ui/issue-51602.rs
  src/test/ui/issue-51602.stderr
Labels: S-waiting-on-bors

#53377 std: Use target_pointer_width for BACKTRACE_ELF_SIZE
  src/Cargo.lock
  src/libstd/build.rs
Labels: S-waiting-on-bors, beta-nominated

#53399 Tidy: ignore non-Markdown files when linting for the Unstable Book
  src/tools/tidy/src/unstable_book.rs
Labels: S-waiting-on-bors

#53397 Visit all attributes for feature collection
  src/librustc/middle/lib_features.rs
Labels: S-waiting-on-bors

#53383 Speed up NLL with HybridIdxSetBuf.
  src/librustc_data_structures/indexed_set.rs
  src/librustc_mir/dataflow/at_location.rs
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/transform/rustc_peek.rs
Labels: S-waiting-on-bors

#52858 Implement Iterator::size_hint for Elaborator.
  src/librustc/traits/util.rs
Labels: S-waiting-on-bors

#53321 Fix usage of `wasm_target_feature`
  src/librustc_typeck/collect.rs
Labels: S-waiting-on-bors

#53326 [nll] add regression test for issue #27868
  src/test/ui/nll/issue-27868.rs
  src/test/ui/nll/issue-27868.stderr
Labels: S-waiting-on-bors

#53347 rustc_resolve: don't allow paths starting with `::crate`.
  src/Cargo.lock
  src/doc/unstable-book/src/language-features/crate-in-paths.md
  src/doc/unstable-book/src/language-features/extern-absolute-paths.md
  src/librustc/Cargo.toml
  src/librustc_resolve/lib.rs
  src/librustc_traits/Cargo.toml
  src/test/run-pass/rfc-2126-crate-paths/crate-path-absolute.rs
  src/test/run-pass/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs
  src/test/ui/feature-gates/feature-gate-crate_in_paths.rs
  src/test/ui/feature-gates/feature-gate-crate_in_paths.stderr
  src/test/ui/rfc-2126-crate-paths/crate-path-non-absolute.rs
  src/test/ui/rfc-2126-crate-paths/crate-path-non-absolute.stderr
  src/test/ui/rfc-2126-crate-paths/keyword-crate-as-identifier.rs
  src/test/ui/rfc-2126-crate-paths/keyword-crate-as-identifier.stderr
  src/test/ui/rust-2018/edition-lint-paths.fixed
  src/test/ui/rust-2018/edition-lint-paths.rs
Labels: S-waiting-on-bors, T-lang

#53357 Pretty print btreemap for GDB
  src/etc/debugger_pretty_printers_common.py
  src/etc/gdb_rust_pretty_printing.py
  src/test/debuginfo/pretty-std-collections.rs
Labels: S-waiting-on-bors

#53358 `{to,from}_{ne,le,be}_bytes` for unsigned integer types
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#53406 Do not suggest conversion method that is already there
  src/librustc_typeck/check/mod.rs
  src/test/ui/issues/issue-53348.rs
  src/test/ui/issues/issue-53348.stderr
Labels: S-waiting-on-bors

#53434 wasm: Remove --strip-debug argument to LLD
  src/librustc_codegen_llvm/back/linker.rs
Labels: S-waiting-on-bors

#53437 Set more llvm function attributes for __rust_try
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/callee.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/mono_item.rs
Labels: S-waiting-on-bors

#53286 Do not generate assumes for plain integer casts
  src/librustc_codegen_llvm/mir/rvalue.rs
  src/librustc_target/abi/mod.rs
  src/test/codegen/no-assumes-on-casts.rs
Labels: S-waiting-on-bors

#53436 std: stop backtracing when the frames are full
  src/libstd/sys/cloudabi/backtrace.rs
  src/libstd/sys/redox/backtrace/tracing.rs
  src/libstd/sys/unix/backtrace/tracing/gcc_s.rs
Labels: S-waiting-on-bors

#52592 Use the new Entry::or_default method where possible.
  src/bootstrap/sanity.rs
  src/bootstrap/tool.rs
  src/librustc/hir/lowering.rs
  src/librustc/lint/mod.rs
  src/librustc/middle/resolve_lifetime.rs
  src/librustc/session/config.rs
  src/librustc/traits/auto_trait.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/specialize/specialization_graph.rs
  src/librustc/ty/context.rs
  src/librustc/ty/inhabitedness/mod.rs
  src/librustc/ty/trait_def.rs
  src/librustc_borrowck/borrowck/unused.rs
  src/librustc_borrowck/dataflow.rs
  src/librustc_codegen_llvm/back/symbol_export.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_data_structures/graph/test.rs
  src/librustc_metadata/encoder.rs
  src/librustc_metadata/locator.rs
  src/librustc_mir/borrow_check/borrow_set.rs
  src/librustc_mir/dataflow/impls/borrows.rs
  src/librustc_mir/monomorphize/partitioning.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_resolve/check_unused.rs
  src/librustc_resolve/lib.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/op.rs
  src/librustc_typeck/coherence/inherent_impls.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/simplify.rs
  src/librustdoc/html/render.rs
  src/librustdoc/lib.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/tt/macro_rules.rs
  src/tools/tidy/src/deps.rs
  src/tools/tidy/src/errors.rs
Labels: S-waiting-on-bors

#53248 skip trivial `Sized` predicates
  src/librustc/traits/query/type_op/prove_predicate.rs
  src/librustc/ty/sty.rs
Labels: S-waiting-on-bors

#53316 52985: cause cycle err on inf trait normalization
  src/librustc/traits/query/normalize.rs
  src/test/ui/existential_types/no_inferrable_concrete_type.rs
  src/test/ui/existential_types/no_inferrable_concrete_type.stderr
Labels: S-waiting-on-bors

#53236 Stabilise raw_identifiers feature
  src/librustc_lint/builtin.rs
  src/libsyntax/diagnostic_list.rs
  src/libsyntax/feature_gate.rs
  src/test/run-pass/auxiliary/edition-kw-macro-2015.rs
  src/test/run-pass/edition-keywords-2015-2015.rs
  src/test/run-pass/edition-keywords-2015-2018.rs
  src/test/run-pass/rfc-2151-raw-identifiers/attr.rs
  src/test/run-pass/rfc-2151-raw-identifiers/basic.rs
  src/test/run-pass/rfc-2151-raw-identifiers/items.rs
  src/test/run-pass/rfc-2151-raw-identifiers/macros.rs
  src/test/ui/E0705.rs
  src/test/ui/E0705.stderr
  src/test/ui/editions/auxiliary/edition-kw-macro-2015.rs
  src/test/ui/editions/edition-keywords-2015-2015-expansion.rs
  src/test/ui/editions/edition-keywords-2015-2015-parsing.rs
  src/test/ui/editions/edition-keywords-2015-2015-parsing.stderr
  src/test/ui/editions/edition-keywords-2015-2018-expansion.rs
  src/test/ui/editions/edition-keywords-2015-2018-expansion.stderr
  src/test/ui/editions/edition-keywords-2015-2018-parsing.rs
  src/test/ui/editions/edition-keywords-2015-2018-parsing.stderr
  src/test/ui/feature-gates/feature-gate-raw-identifiers.rs
  src/test/ui/feature-gates/feature-gate-raw-identifiers.stderr
  src/test/ui/raw/raw-literal-keywords.rs
  src/test/ui/raw/raw-literal-keywords.stderr
  src/test/ui/raw/raw-literal-self.rs
  src/test/ui/raw/raw-literal-self.stderr
  src/test/ui/rust-2018/async-ident-allowed.stderr
  src/test/ui/rust-2018/async-ident.fixed
  src/test/ui/rust-2018/async-ident.rs
  src/test/ui/rust-2018/async-ident.stderr
Labels: S-waiting-on-bors, T-lang, relnotes

#53030 Updated RELEASES.md for 1.29.0
  RELEASES.md
Labels: S-waiting-on-bors, beta-nominated

#53104 expand the documentation on the `Unpin` trait
  src/libcore/marker.rs
Labels: S-waiting-on-bors

#53213 Stabilize IP associated constants
  src/libstd/net/ip.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#53329 Replace usages of ptr::offset with ptr::{add,sub}.
  src/liballoc/alloc.rs
  src/liballoc/boxed.rs
  src/liballoc/collections/btree/node.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/raw_vec.rs
  src/liballoc/rc.rs
  src/liballoc/slice.rs
  src/liballoc/string.rs
  src/liballoc/sync.rs
  src/liballoc/vec.rs
  src/liballoc_system/lib.rs
  src/libarena/lib.rs
  src/libcore/intrinsics.rs
  src/libcore/marker.rs
  src/libcore/ptr.rs
  src/libcore/slice/memchr.rs
  src/libcore/slice/mod.rs
  src/libcore/slice/rotate.rs
  src/libcore/slice/sort.rs
  src/libcore/str/mod.rs
  src/libpanic_unwind/dwarf/mod.rs
  src/librustc_data_structures/array_vec.rs
  src/librustc_data_structures/small_vec.rs
  src/libstd/collections/hash/table.rs
  src/libstd/sys/windows/pipe.rs
  src/libstd/sys_common/wtf8.rs
  src/test/run-pass/method-mut-self-modifies-mut-slice-lvalue.rs
  src/test/run-pass/realloc-16687.rs
  src/test/run-pass/running-with-no-runtime.rs
Labels: S-waiting-on-bors

#53363 add individual docs to `core::num::NonZero*`
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#53370 Stabilize macro_vis_matcher
  src/doc/unstable-book/src/language-features/macro-vis-matcher.md
  src/doc/unstable-book/src/language-features/plugin.md
  src/librustc/lib.rs
  src/librustc_data_structures/lib.rs
  src/librustc_lint/lib.rs
  src/librustc_mir/lib.rs
  src/libstd/lib.rs
  src/libsyntax/ext/tt/macro_rules.rs
  src/libsyntax/feature_gate.rs
  src/test/compile-fail-fulldeps/auxiliary/lint_for_crate.rs
  src/test/compile-fail-fulldeps/auxiliary/lint_group_plugin_test.rs
  src/test/compile-fail-fulldeps/auxiliary/lint_plugin_test.rs
  src/test/run-pass-fulldeps/auxiliary/lint_for_crate.rs
  src/test/run-pass-fulldeps/proc-macro/auxiliary/issue-40001-plugin.rs
  src/test/run-pass/macro-first-set.rs
  src/test/run-pass/macro-pub-matcher.rs
  src/test/ui-fulldeps/auxiliary/lint_group_plugin_test.rs
  src/test/ui-fulldeps/auxiliary/lint_plugin_test.rs
  src/test/ui-fulldeps/auxiliary/lint_tool_test.rs
  src/test/ui/feature-gates/feature-gate-macro-vis-matcher.rs
  src/test/ui/feature-gates/feature-gate-macro-vis-matcher.stderr
  src/test/ui/issues/issue-42755.rs
  src/test/ui/lint/unreachable_pub-pub_crate.rs
  src/test/ui/lint/unreachable_pub.rs
Labels: S-waiting-on-bors, relnotes

#53405 restore the page title after escaping out of a search
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#53452 Change target triple used to check for lldb in build-manifest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#53462 Document Box::into_raw returns non-null ptr
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#53465 Remove LinkMeta struct
  src/librustc/middle/cstore.rs
  src/librustc/ty/context.rs
  src/librustc_codegen_llvm/back/link.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_codegen_utils/link.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_metadata/encoder.rs
Labels: S-waiting-on-bors

#53521 syntax: Optimize some literal parsing
  src/libsyntax/parse/mod.rs
Labels: S-waiting-on-bors

#53540 Moved issue-53157.rs into src/test/ui/consts/const-eval/
  src/test/ui/consts/const-eval/issue-53157.rs
Labels: S-waiting-on-bors

#53551 Avoid some Place clones.
  src/librustc_mir/borrow_check/mod.rs
Labels: S-waiting-on-bors

#53444 Only fetch lib_features when there are unknown feature attributes
  src/librustc/middle/lib_features.rs
  src/librustc/middle/stability.rs
Labels: S-waiting-on-bors

#53439 Generate blanket implementations for reexported items as well
  src/librustdoc/clean/blanket_impl.rs
  src/test/rustdoc/blanket-reexport-item.rs
Labels: S-waiting-on-bors

#53477 Exec gdb/lldb in rust-{gdb/lldb} wrapper scripts
  src/etc/rust-gdb
  src/etc/rust-lldb
Labels: S-waiting-on-bors

#53509 resolve: Reject some inaccessible candidates sooner during import resolution
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/issue-53140.rs
Labels: S-waiting-on-bors, beta-nominated

#53516 resolve: Continue search in outer scopes after applying derive resolution fallback
  src/librustc_resolve/lib.rs
  src/test/ui-fulldeps/proc-macro/generate-mod.rs
  src/test/ui-fulldeps/proc-macro/generate-mod.stderr
Labels: S-waiting-on-bors, beta-nominated

#53524 Buffer LLVM's object output stream
  src/rustllvm/PassWrapper.cpp
Labels: S-waiting-on-bors

#53536 fix array drop glue: properly turn raw ptr into reference
  src/librustc_mir/util/elaborate_drops.rs
Labels: S-waiting-on-bors

#53418 Mark some suggestions as MachineApplicable
  src/librustc_borrowck/borrowck/unused.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check_unused.rs
Labels: S-waiting-on-bors

#53431 Moved some feature gate ui tests to correct location
  src/test/ui/feature-gates/feature-gate-rustc-attrs-1.rs
  src/test/ui/feature-gates/feature-gate-rustc-attrs-1.stderr
  src/test/ui/feature-gates/feature-gate-uniform-paths.rs
  src/test/ui/feature-gates/feature-gate-uniform-paths.stderr
  src/test/ui/feature-gates/feature-gate-unrestricted-attribute-tokens.rs
  src/test/ui/feature-gates/feature-gate-unrestricted-attribute-tokens.stderr
Labels: S-waiting-on-bors

#53442 Update version of rls-data used with save-analysis
  src/Cargo.lock
  src/librustc_save_analysis/Cargo.toml
Labels: S-waiting-on-bors

#53504 Set applicability for more suggestions.
  src/librustc_borrowck/borrowck/gather_loans/move_error.rs
  src/librustc_passes/ast_validation.rs
  src/librustc_resolve/macros.rs
  src/librustc_typeck/check/callee.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
  src/libsyntax_ext/format.rs
Labels: S-waiting-on-bors

#53541 Fix missing impl trait display as ret type
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/impl-everywhere.rs
Labels: S-waiting-on-bors, T-compiler
