Repository rust-lang/rust, pull requests merged in 2018-03, with the labels that each got.

#48355 restore Subslice move out from array after elaborate drops and borrowck
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/uniform_array_move_out.rs
  src/test/mir-opt/uniform_array_move_out.rs
Labels: S-waiting-on-bors

#48359 Implement --remap-path-prefix
  src/doc/man/rustc.1
  src/doc/unstable-book/src/compiler-flags/remap-path-prefix.md
  src/libproc_macro/lib.rs
  src/librustc/session/config.rs
  src/librustc_metadata/encoder.rs
  src/libsyntax/codemap.rs
  src/libsyntax_pos/lib.rs
  src/test/codegen/remap_path_prefix/auxiliary/remap_path_prefix_aux.rs
  src/test/codegen/remap_path_prefix/main.rs
  src/test/incremental/remapped_paths_cc/auxiliary/extern_crate.rs
Labels: S-waiting-on-bors, relnotes

#48420 Add std::path::Path::ancestors
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-libs

#48603 Minor grammatical/style fix in docs.
  src/libcore/iter/iterator.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#48446 Remove E0245; improve E0404
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/lib.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/diagnostics.rs
  src/test/ui/error-codes/E0404.rs
  src/test/ui/error-codes/E0404.stderr
Labels: S-waiting-on-bors

#48570 Add AArch64 features to whitelist
  src/librustc_trans/attributes.rs
  src/librustc_trans/llvm_util.rs
Labels: S-waiting-on-bors

#48572 rustc: Tweak funclet cleanups of ffi functions
  src/librustc_trans/mir/mod.rs
  src/test/run-make/longjmp-across-rust/Makefile
  src/test/run-make/longjmp-across-rust/foo.c
  src/test/run-make/longjmp-across-rust/main.rs
Labels: S-waiting-on-bors

#48610 Add regression test for #48551
  src/test/run-pass/issue-48551.rs
Labels: S-waiting-on-bors

#48626 Fix link to rustc guide in README.md
  README.md
Labels: S-waiting-on-bors

#48666 Revert "correct subtle bug in the type variable code"
  src/librustc/infer/type_variable.rs
Labels: S-waiting-on-bors

#48259 Stabilize Unsafe Pointer Methods
  src/libcore/ptr.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#48328 Clarify "It is an error to..." wording for zero-duration behaviors.
  src/libstd/net/tcp.rs
  src/libstd/net/udp.rs
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors

#48628 impl Default + Hash for ::core::cmp::Reverse
  src/libcore/cmp.rs
Labels: S-waiting-on-bors, T-libs

#48641 rustc: More stable hashes of command line arguments
  src/librustc/session/config.rs
  src/test/run-make/reproducible-build/Makefile
  src/test/run-make/reproducible-build/reproducible-build.rs
Labels: S-waiting-on-author

#48600 Remove --host and --target arguments to configure in Dockerfiles
  src/ci/docker/arm-android/Dockerfile
  src/ci/docker/armhf-gnu/Dockerfile
  src/ci/docker/asmjs/Dockerfile
  src/ci/docker/disabled/aarch64-gnu/Dockerfile
  src/ci/docker/disabled/dist-aarch64-android/Dockerfile
  src/ci/docker/disabled/dist-armv7-android/Dockerfile
  src/ci/docker/disabled/dist-i686-android/Dockerfile
  src/ci/docker/disabled/dist-x86_64-android/Dockerfile
  src/ci/docker/disabled/dist-x86_64-dragonfly/Dockerfile
  src/ci/docker/disabled/dist-x86_64-haiku/Dockerfile
  src/ci/docker/disabled/dist-x86_64-redox/Dockerfile
  src/ci/docker/disabled/wasm32-exp/Dockerfile
  src/ci/docker/disabled/wasm32/Dockerfile
  src/ci/docker/dist-aarch64-linux/Dockerfile
  src/ci/docker/dist-android/Dockerfile
  src/ci/docker/dist-arm-linux/Dockerfile
  src/ci/docker/dist-armhf-linux/Dockerfile
  src/ci/docker/dist-armv7-linux/Dockerfile
  src/ci/docker/dist-i586-gnu-i586-i686-musl/Dockerfile
  src/ci/docker/dist-i686-freebsd/Dockerfile
  src/ci/docker/dist-i686-linux/Dockerfile
  src/ci/docker/dist-mips-linux/Dockerfile
  src/ci/docker/dist-mips64-linux/Dockerfile
  src/ci/docker/dist-mips64el-linux/Dockerfile
  src/ci/docker/dist-mipsel-linux/Dockerfile
  src/ci/docker/dist-powerpc-linux/Dockerfile
  src/ci/docker/dist-powerpc64-linux/Dockerfile
  src/ci/docker/dist-powerpc64le-linux/Dockerfile
  src/ci/docker/dist-s390x-linux/Dockerfile
  src/ci/docker/dist-various-1/Dockerfile
  src/ci/docker/dist-various-2/Dockerfile
  src/ci/docker/dist-x86_64-freebsd/Dockerfile
  src/ci/docker/dist-x86_64-linux/Dockerfile
  src/ci/docker/dist-x86_64-musl/Dockerfile
  src/ci/docker/dist-x86_64-netbsd/Dockerfile
  src/ci/docker/wasm32-unknown/Dockerfile
Labels: S-waiting-on-bors

#48630 rustbuild: Pass `ccache` to build scripts
  src/bootstrap/builder.rs
  src/ci/run.sh
Labels: S-waiting-on-bors

#48587 Make TransitiveRelation thread safe. Avoid locking by using get_mut in some cases
  src/librustc_data_structures/transitive_relation.rs
Labels: S-waiting-on-bors

#48736 Include stdsimd in rust-src component
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#48730 [beta] Remove allocation from width of character function.
  src/libsyntax/codemap.rs
Labels: S-waiting-on-bors

#48403 Fix spelling s/casted/cast/
  src/libcore/char.rs
  src/librustc_lint/types.rs
  src/libsyntax/parse/parser.rs
  src/test/run-pass/extern-types-pointer-cast.rs
  src/test/ui/cast_char.rs
  src/test/ui/cast_char.stderr
  src/test/ui/issue-22644.stderr
  src/test/ui/issue-42954.stderr
Labels: S-waiting-on-bors

#48474 New Cell docs
  src/libcore/cell.rs
Labels: S-waiting-on-bors

#48507 Add new warning for CStr::from_ptr
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors, T-doc

#48546 Raw string error note
  src/libsyntax/parse/lexer/mod.rs
  src/test/ui/raw_string.rs
  src/test/ui/raw_string.stderr
Labels: S-waiting-on-bors

#48590 doc: no need for the reference
  src/libcore/iter/iterator.rs
Labels: S-waiting-on-bors, T-doc

#48727 Refactor contrived match.
  src/librustc_mir/transform/lower_128bit.rs
Labels: S-waiting-on-bors

#48732 Remove useless powerpc64 entry from ARCH_TABLE
  src/test/codegen/abi-main-signature-16bit-c-int.rs
  src/test/codegen/fastcall-inreg.rs
  src/test/codegen/global_asm.rs
  src/test/codegen/global_asm_include.rs
  src/test/codegen/global_asm_x2.rs
  src/test/codegen/repr-transparent-aggregates-1.rs
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors

#48753 Remove a couple of `isize` references from hashmap docs
  src/libstd/collections/hash/map.rs
  src/libstd/collections/hash/set.rs
Labels: S-waiting-on-bors

#48754 while let all the things
  src/librustc/hir/print.rs
  src/librustc/middle/reachable.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/libstd/sys_common/wtf8.rs
  src/libsyntax_ext/format.rs
  src/libsyntax_pos/lib.rs
Labels: S-waiting-on-bors

#48761 Remove seemingly unused sugarise-doc-comments Python script.
  src/etc/sugarise-doc-comments.py
Labels: S-waiting-on-bors

#48642 Update env_logger to 0.5.4
  src/Cargo.lock
  src/librustc_driver/Cargo.toml
  src/librustc_driver/lib.rs
  src/librustc_trans/Cargo.toml
  src/librustdoc/lib.rs
  src/tools/compiletest/Cargo.toml
  src/tools/compiletest/src/main.rs
  src/tools/linkchecker/main.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-review

#48511 Add resource-suffix option for rustdoc
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/storage.js
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors

#48651 Fixed #48425 : Various functions taking a `TyCtxt` and a `Span` should be taking a `TyCtxtAt`
  src/librustc/ty/layout.rs
  src/librustc/ty/util.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_trans/common.rs
  src/librustc_trans/context.rs
Labels: S-waiting-on-bors

#48778 Fix save-analysis generation crash with invalid tuple access
  src/librustc_save_analysis/dump_visitor.rs
  src/test/run-make/save-analysis-fail/foo.rs
Labels: S-waiting-on-bors

#48787 Stabilize option_ref_mut_cloned
  src/libcore/option.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#48798 Update compiletest's dependencies
  src/Cargo.lock
  src/tools/compiletest/Cargo.toml
  src/tools/compiletest/src/json.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/read2.rs
Labels: S-waiting-on-bors

#48802 Remove unused 'src/etc/ziggurat_tables.py' Python script.
  src/etc/ziggurat_tables.py
Labels: S-waiting-on-bors

#48809 appveyor: Shard more slow MSVC builders
  appveyor.yml
  src/bootstrap/mk/Makefile.in
  src/ci/run.sh
Labels: S-waiting-on-bors

#48832 appveyor: Fix a switched condition for cargotest
  src/bootstrap/mk/Makefile.in
Labels: S-waiting-on-bors

#48292 Implement FromStr for PathBuf
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-libs, final-comment-period, relnotes

#48738 Add a potential cause raising `ParseIntError`.
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#48752 rustc: Fix ICE with `#[target_feature]` on module
  src/librustc/hir/check_attr.rs
  src/librustc_typeck/collect.rs
  src/test/ui/target-feature-wrong.rs
  src/test/ui/target-feature-wrong.stderr
Labels: S-waiting-on-bors

#48789 Fix sidebar horizontal scroll
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#48527 in which parentheses are suggested for should-have-been-tuple-patterns
  src/libsyntax/parse/parser.rs
  src/test/ui/did_you_mean/issue-48492-tuple-destructure-missing-parens.rs
  src/test/ui/did_you_mean/issue-48492-tuple-destructure-missing-parens.stderr
Labels: S-waiting-on-bors

#48588 rustc: Migrate to `termcolor` crate from `term`
  src/Cargo.lock
  src/librustc_errors/Cargo.toml
  src/librustc_errors/emitter.rs
  src/librustc_errors/lib.rs
Labels: S-waiting-on-bors

#48856 Modify part of `line!` documentation.
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#48857 Modify part of `column!` documentation.
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#48757 rustbuild: Fix MSBuild location of `llvm-config.exe`
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/doc.rs
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#48901 rustbuild: Pass `-j1` to OpenSSL `make install`
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#48691 Move PROFQ_CHAN to a Session field
  src/librustc/dep_graph/graph.rs
  src/librustc/ich/hcx.rs
  src/librustc/ich/mod.rs
  src/librustc/session/mod.rs
  src/librustc/ty/maps/plumbing.rs
  src/librustc/util/common.rs
  src/librustc_data_structures/stable_hasher.rs
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
  src/librustc_driver/profile/mod.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_trans/back/link.rs
  src/librustc_trans/back/lto.rs
  src/librustc_trans/back/write.rs
  src/librustc_trans/base.rs
  src/librustc_trans/lib.rs
  src/librustc_typeck/lib.rs
Labels: S-waiting-on-bors

#48799 travis: Upgrade OSX builders
  .travis.yml
  src/test/debuginfo/lexical-scope-with-macro.rs
  src/test/run-make/long-linker-command-lines/Makefile
  src/test/run-make/reproducible-build/Makefile
  src/test/run-make/reproducible-build/linker.rs
Labels: S-waiting-on-bors

#48938 test: Forcibly remove MAKEFLAGS in compiletest
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#48201 rephrase UnsafeCell doc
  src/libcore/cell.rs
Labels: S-waiting-on-bors, T-doc

#48480 Clarify interfaction between File::set_len and file cursor
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#48631 Remember state of top-level collapse toggle widget
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#48705 Update Feature Request instructions
  CONTRIBUTING.md
Labels: S-waiting-on-bors, T-core, T-doc

#48824 Propagating upstream code of conduct changes
  CODE_OF_CONDUCT.md
Labels: S-waiting-on-bors

#48877 Add missing urls
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#48880 tidy: Add a check for stray `.stderr` and `.stdout` files in UI test directories
  src/test/ui/lifetime-errors/ex3-both-anon-regions-4.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-to-empty.stderr
  src/test/ui/resolve-error.stderr
  src/test/ui/span/loan-extend.stderr
  src/tools/tidy/src/lib.rs
  src/tools/tidy/src/main.rs
  src/tools/tidy/src/ui_tests.rs
Labels: S-waiting-on-bors

#48898 Remove auto trait implementation section when empty
  src/librustdoc/html/render.rs
  src/test/rustdoc/empty-section.rs
Labels: S-waiting-on-author

#48934 Fix hygene issue when deriving Debug
  src/libsyntax_ext/deriving/debug.rs
  src/test/run-pass/issue-42453.rs
Labels: S-waiting-on-bors

#48954 Add missing links
  src/libcore/fmt/mod.rs
Labels: S-waiting-on-bors

#48958 Update the rls-rustc package
  src/Cargo.lock
Labels: S-waiting-on-bors

#48811 Remove syntax and syntax_pos thread locals
  src/Cargo.lock
  src/librustc/session/config.rs
  src/librustc_driver/lib.rs
  src/librustc_driver/test.rs
  src/librustdoc/clean/cfg.rs
  src/librustdoc/lib.rs
  src/librustdoc/test.rs
  src/libsyntax/Cargo.toml
  src/libsyntax/attr.rs
  src/libsyntax/fold.rs
  src/libsyntax/lib.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/test_snippet.rs
  src/libsyntax/tokenstream.rs
  src/libsyntax_pos/Cargo.toml
  src/libsyntax_pos/hygiene.rs
  src/libsyntax_pos/lib.rs
  src/libsyntax_pos/span_encoding.rs
  src/libsyntax_pos/symbol.rs
  src/test/run-fail-fulldeps/qquote.rs
  src/test/run-make/issue-19371/foo.rs
  src/test/run-pass-fulldeps/ast_stmt_expr_attr.rs
  src/test/run-pass-fulldeps/issue-35829.rs
  src/test/run-pass-fulldeps/pprust-expr-roundtrip.rs
  src/test/run-pass-fulldeps/qquote.rs
  src/tools/error_index_generator/main.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors

#48765 Add info message for -Wall command
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#48831 Fix blink when main theme is selected
  src/librustdoc/html/static/storage.js
Labels: S-waiting-on-bors

#48964 tweak code fences in the rustdoc book
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#48966 Speed up SVH computation by using Fingerprint::combine()
  src/librustc/hir/map/collector.rs
Labels: S-waiting-on-bors

#48970 Add missing examples
  src/libcore/fmt/mod.rs
Labels: S-waiting-on-bors

#48971 Move librustc_typeck READMEs to rustc guide
  src/librustc_typeck/README.md
  src/librustc_typeck/check/method/README.md
  src/librustc_typeck/check/method/mod.rs
  src/librustc_typeck/variance/README.md
  src/librustc_typeck/variance/mod.rs
  src/librustc_typeck/variance/terms.rs
Labels: S-waiting-on-bors

#48981 rustc: Don't invoke `lld` with an `@`-file
  src/librustc_trans/back/command.rs
  src/librustc_trans/back/link.rs
Labels: S-waiting-on-bors

#48988 Add a test for #48070
  src/test/ui/nll/issue-48070.rs
Labels: S-waiting-on-bors

#48991 Clarify usage message for --remap-path-prefix.
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#48993 fix #48816 don't print help on indirect compiler ICE
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#48853 Improve `AddrParseError` documentation.
  src/libstd/net/parser.rs
Labels: S-waiting-on-bors, T-doc

#48892 rustbuild: Remove ThinLTO-related configuration
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
  src/bootstrap/configure.py
  src/ci/run.sh
Labels: S-waiting-on-bors

#48922 Implement import renaming with `_` (RFC 2166)
  src/libsyntax/feature_gate.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/feature-gate-underscore-imports.rs
  src/test/ui/feature-gate-underscore-imports.stderr
  src/test/ui/rfc-2166-underscore-imports/basic.rs
  src/test/ui/rfc-2166-underscore-imports/basic.stderr
Labels: S-waiting-on-bors

#48957 Dedupe rand
  src/Cargo.lock
  src/librustc_back/Cargo.toml
  src/librustc_incremental/Cargo.toml
Labels: S-waiting-on-bors

#48959 rustc: Start a custom cabi module for wasm32
  src/librustc_trans/abi.rs
  src/librustc_trans/cabi_wasm32.rs
  src/librustc_trans/lib.rs
Labels: S-waiting-on-bors

#48961 Rustdoc: example of use of assertions
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#48965 rustc: Add `sha` to the x86 feature whitelist
  src/librustc_trans/llvm_util.rs
Labels: S-waiting-on-bors

#48972 Move librustdoc readme to rustc guide
  src/librustdoc/README.md
Labels: S-waiting-on-bors

#49007 Some tweaks to "type parameters from outer function" diagnostic
  src/librustc_resolve/lib.rs
  src/libsyntax/codemap.rs
  src/test/ui/error-codes/E0401.rs
  src/test/ui/error-codes/E0401.stderr
Labels: S-waiting-on-bors

#49024 rustc_trans: fix small aggregate returns for big-endian mips64 FFI
  src/librustc_trans/cabi_mips64.rs
Labels: S-waiting-on-bors

#49037 Coherence diagnostic tweaks
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/coherence/orphan.rs
  src/test/ui/codemap_tests/empty_span.stderr
  src/test/ui/coherence-impls-copy.stderr
  src/test/ui/e0119/complex-impl.stderr
  src/test/ui/e0119/issue-28981.stderr
  src/test/ui/error-codes/E0117.stderr
  src/test/ui/error-codes/E0206.stderr
  src/test/ui/error-codes/E0328.rs
  src/test/ui/error-codes/E0328.stderr
Labels: S-waiting-on-bors

#49042 Remove unnecessary "`" in error message E0307 (invalid self type).
  src/librustc_typeck/check/wfcheck.rs
  src/test/ui/span/issue-27522.stderr
Labels: S-waiting-on-bors

#49049 Unstabilize FusedIterator for Flatten since Flatten is unstable
  src/libcore/iter/mod.rs
Labels: S-waiting-on-bors, T-libs

#49050 setting ABORTING_MALLOC=0 for asmjs backend
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/librustc_back/target/asmjs_unknown_emscripten.rs
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#48818 Properly handle collecting default impls of methods with lifetime parameters.
  src/librustc_mir/monomorphize/collector.rs
  src/test/compile-fail/issue-47309.rs
Labels: S-waiting-on-bors

#49088 incr.comp.: Make sanity check in try_mark_green() aware of error conditions.
  src/librustc/dep_graph/graph.rs
Labels: S-waiting-on-bors

#48943 Support extra-verbose builds
  src/bootstrap/bootstrap.py
  src/bootstrap/builder.rs
  src/bootstrap/flags.rs
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#48960 resolve `'_` in `dyn Trait` just like ordinary elision
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/underscore-lifetime/dyn-trait-underscore.rs
  src/test/ui/underscore-lifetime/dyn-trait-underscore.stderr
Labels: S-waiting-on-bors

#49055 rustbuild: Add more MinGW libraries to ship
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#49057 Faster submodule updating
  config.toml.example
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#49077 Checks for unknown attributes before aborting due to unresolved macros
  src/librustc_driver/driver.rs
  src/test/ui/issue-49074.rs
  src/test/ui/issue-49074.stderr
Labels: S-waiting-on-bors

#49082 Remove deprecated unstable alloc::heap::EMPTY constant
  src/liballoc/heap.rs
Labels: S-waiting-on-bors

#49083 Only generate miri backtraces if explicitly requested
  src/librustc/mir/interpret/error.rs
Labels: S-waiting-on-bors

#48978 Add hexadecimal formatting of integers with fmt::Debug
  src/liballoc/fmt.rs
  src/libcore/fmt/mod.rs
  src/libcore/fmt/num.rs
  src/libcore/tests/fmt/num.rs
  src/libfmt_macros/lib.rs
Labels: S-waiting-on-bors

#49091 extend stable hasher to support `CanonicalTy`
  src/librustc/ich/impls_ty.rs
  src/librustc/macros.rs
  src/librustc/traits/query/dropck_outlives.rs
  src/test/incremental/issue-49043.rs
Labels: S-waiting-on-bors

#49079 Cleanup metadata and incremental cache processing of constants
  src/librustc/mir/interpret/mod.rs
  src/librustc/ty/maps/on_disk_cache.rs
  src/librustc_metadata/decoder.rs
  src/librustc_metadata/encoder.rs
  src/test/incremental/static_refering_to_other_static/issue-49081.rs
Labels: S-waiting-on-bors

#46518 Improve documentation for Borrow
  src/libcore/borrow.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#48810 Implement Integer methods for Wrapping
  src/libcore/num/wrapping.rs
Labels: S-waiting-on-bors

#49004 Cache the specialization_graph query
  src/librustc/traits/specialize/specialization_graph.rs
  src/librustc/ty/fast_reject.rs
  src/librustc/ty/maps/config.rs
  src/librustc/ty/maps/on_disk_cache.rs
  src/librustc/ty/maps/plumbing.rs
Labels: S-waiting-on-bors

#49092 Replace many of the last references to readmes
  src/librustc/dep_graph/README.md
  src/librustc/infer/higher_ranked/mod.rs
  src/librustc/infer/lexical_region_resolve/README.md
  src/librustc/infer/region_constraints/README.md
  src/librustc/infer/region_constraints/mod.rs
  src/librustc/middle/liveness.rs
  src/librustc/middle/region.rs
  src/librustc/mir/mod.rs
  src/librustc/ty/sty.rs
  src/librustc_back/README.md
  src/librustc_borrowck/borrowck/README.md
  src/librustc_driver/README.md
  src/librustc_trans/README.md
  src/libsyntax/README.md
Labels: S-waiting-on-bors

#49099 Use associated consts for GenericRadix base and prefix
  src/libcore/fmt/num.rs
Labels: S-waiting-on-bors

#49104 improve error message of inner attribute syntax
  src/libsyntax/parse/attr.rs
  src/test/ui/issue-49040.rs
  src/test/ui/issue-49040.stderr
Labels: S-waiting-on-bors

#49125 rustbuild: Ship libsynchronization
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#49139 Add BufReader::buffer
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors, T-libs

#49152 Fix events handling in rustdoc
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-author

#49157 Do not suggest `.into()` in `const`s
  src/librustc_typeck/check/demand.rs
  src/test/ui/suggestions/const-type-mismatch.rs
  src/test/ui/suggestions/const-type-mismatch.stderr
Labels: S-waiting-on-author

#49161 Docs: fix incorrect copy-paste for new `X?` in formatting strings
  src/liballoc/fmt.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#49176 config.toml.example: thinlto bootstrap was removed
  config.toml.example
Labels: S-waiting-on-bors

#49184 Update beta to version with fixed FreeBSD support from #49023.
  src/stage0.txt
Labels: S-waiting-on-bors

#49217 Apply temporary fix of travis-ci/dpl#788.
  .travis.yml
Labels: S-waiting-on-bors

#49200 Encode/decode extern statics in metadata and incremental cache
  src/librustc/mir/interpret/mod.rs
  src/librustc/ty/maps/on_disk_cache.rs
  src/librustc_metadata/encoder.rs
  src/test/incremental/extern_static/issue-49153.rs
Labels: S-waiting-on-bors

#49094 ci: Print out how long each step takes on CI
  config.toml.example
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
  src/ci/run.sh
Labels: S-waiting-on-bors

#48374 Update RELEASES.md for 1.25.0
  RELEASES.md
Labels: S-waiting-on-bors, T-release

#48596 Add warning for invalid start of code blocks in rustdoc
  src/librustdoc/html/markdown.rs
  src/librustdoc/markdown.rs
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#49029 Make Atomic doc examples specific to each type
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors, T-doc

#49069 Convert SerializedDepGraph to be a struct-of-arrays
  src/librustc/dep_graph/graph.rs
  src/librustc/dep_graph/prev.rs
  src/librustc/dep_graph/serialized.rs
  src/librustc_data_structures/indexed_vec.rs
  src/librustc_incremental/persist/save.rs
Labels: S-waiting-on-bors

#49093 Update submodules in parallel
  src/ci/init_repo.sh
Labels: S-waiting-on-bors

#49105 Add an example of lossy decoding to str::Utf8Error docs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#49109 Deprecate the AsciiExt trait in favor of inherent methods
  src/libcore/tests/ascii.rs
  src/libstd/ascii.rs
  src/libstd/sys/windows/process.rs
  src/libstd/sys_common/wtf8.rs
  src/test/run-pass/issue-10683.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#49140 Allow test target to pass without installing
  src/test/run-make/tools.mk
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#49188 Put `#[macro_use] extern crate <crate>` before fn main() in doctests
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#49189 Fix automatic urls with backticks
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/markdown.rs
  src/test/rustdoc/check-styled-link.rs
Labels: S-waiting-on-bors

#49209 Run the `run-make` tests last, so more tests run on Windows when `make` is unavailable
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#49231 fix vector fmin/fmax non-fast/fast intrinsics NaN handling
  src/librustc_trans/builder.rs
Labels: S-waiting-on-bors

#49234 dpl 1.9.5 has been released, revert #49217.
  .travis.yml
Labels: S-waiting-on-bors

#49210 Fix the conversion between bit representations and i128 representations
  src/librustc/ty/layout.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/util.rs
  src/test/run-pass/ctfe/signed_enum_discr.rs
Labels: S-waiting-on-bors

#49102 Remove core::fmt::num::Decimal
  src/libcore/fmt/num.rs
Labels: S-waiting-on-bors

#49160 Reduce the diagnostic spam when multiple fields are missing in pattern
  src/librustc_typeck/check/_match.rs
  src/test/compile-fail/struct-pat-derived-error.rs
  src/test/ui/error-codes/E0026-teach.stderr
  src/test/ui/error-codes/E0026.stderr
  src/test/ui/missing-fields-in-struct-pattern.rs
  src/test/ui/missing-fields-in-struct-pattern.stderr
  src/test/ui/numeric-fields.stderr
  src/test/ui/type-check/issue-41314.stderr
  src/test/ui/union/union-fields-2.stderr
Labels: S-waiting-on-author

#49169 Document only-X test header
  src/test/COMPILER_TESTS.md
Labels: S-waiting-on-bors

#49272 Use GNU version of fgrep/egrep tool if available
  src/etc/cat-and-grep.sh
Labels: S-waiting-on-bors

#49295 Add test for issue-48238
  src/test/ui/nll/issue-48238.rs
  src/test/ui/nll/issue-48238.stderr
Labels: S-waiting-on-bors

#49311 Use the same RUSTFLAGS for building and testing `bootstrap`
  src/bootstrap/test.rs
Labels: A-build, A-rustbuild, S-waiting-on-bors

#49076 Fix Issue #48345, is_file, is_dir, and is_symlink note mutual exclusion
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#49089 rustbuild: Tweak where timing information goes
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors

#49120 Add a CI job for parallel rustc using x.py check
  config.toml.example
  src/bootstrap/configure.py
  src/ci/docker/x86_64-gnu-debug/Dockerfile
  src/ci/run.sh
Labels: S-waiting-on-bors

#49121 Stabilise FromUtf8Error::as_bytes
  src/liballoc/string.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#49122 Add a -Z flag for LLVM align attributes on arguments
  src/librustc/session/config.rs
  src/librustc_trans/abi.rs
Labels: S-waiting-on-bors

#49194 Make resuming generators unsafe instead of the creation of immovable generators
  src/doc/unstable-book/src/language-features/generators.md
  src/liballoc/boxed.rs
  src/libcore/ops/generator.rs
  src/librustc_mir/diagnostics.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/test/run-pass/dynamic-drop.rs
  src/test/run-pass/generator/conditional-drop.rs
  src/test/run-pass/generator/control-flow.rs
  src/test/run-pass/generator/drop-env.rs
  src/test/run-pass/generator/issue-44197.rs
  src/test/run-pass/generator/iterator-count.rs
  src/test/run-pass/generator/live-upvar-across-yield.rs
  src/test/run-pass/generator/nested_generators.rs
  src/test/run-pass/generator/panic-drops.rs
  src/test/run-pass/generator/panic-safe.rs
  src/test/run-pass/generator/resume-after-return.rs
  src/test/run-pass/generator/smoke.rs
  src/test/run-pass/generator/static-generators.rs
  src/test/run-pass/generator/xcrate-reachable.rs
  src/test/run-pass/generator/xcrate.rs
  src/test/ui/generator/borrowing.rs
  src/test/ui/generator/borrowing.stderr
  src/test/ui/generator/dropck.rs
  src/test/ui/generator/sized-yield.rs
  src/test/ui/generator/sized-yield.stderr
  src/test/ui/generator/unsafe-immovable.rs
  src/test/ui/generator/unsafe-immovable.stderr
  src/test/ui/generator/yield-while-iterating.rs
  src/test/ui/generator/yield-while-local-borrowed.rs
  src/test/ui/generator/yield-while-ref-reborrowed.rs
Labels: S-waiting-on-bors

#49203 Bump racer and home
  src/Cargo.lock
Labels: S-waiting-on-bors

#49235 Cargo fmt libtest
  src/libtest/formatters/json.rs
  src/libtest/formatters/pretty.rs
  src/libtest/formatters/terse.rs
  src/libtest/lib.rs
  src/libtest/stats.rs
Labels: S-waiting-on-bors

#49254 Fixed clockwise/counter-clockwise in atan2 documentation in f32 and f64 and included that it returns radians
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#49273 Fix DefKey lookup for proc-macro crates.
  src/librustc_metadata/decoder.rs
Labels: S-waiting-on-bors, beta-accepted

#49290 Allow installing rustfmt without config.extended
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#49312 Fix IE11 search
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#49314 Remove getopts leftover from tree
  src/libgetopts/lib.rs
Labels: S-waiting-on-bors

#49284 ci: Don't use Travis caches for docker images
  .travis.yml
  src/ci/docker/run.sh
Labels: S-waiting-on-bors

#49315 Reduce scope of unsafe block in sun_path_offset
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors
