Repository rust-lang/rust, pull requests merged in 2018-12, with the labels that each got.

#55275 experiment: Support aliasing local crate root in extern prelude
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_typeck/check_unused.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/feature-gates/feature-gate-extern_crate_self.rs
  src/test/ui/feature-gates/feature-gate-extern_crate_self.stderr
  src/test/ui/imports/extern-crate-self-fail.rs
  src/test/ui/imports/extern-crate-self-fail.stderr
  src/test/ui/imports/extern-crate-self-pass.rs
Labels: A-rust-2018-preview, S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period

#56396 tests: Simplify VaList run-make test
  src/test/run-make-fulldeps/c-link-to-rust-va-list-fn/checkrust.rs
  src/test/run-make-fulldeps/c-link-to-rust-va-list-fn/test.c
Labels: S-waiting-on-bors

#56378 arena: speed up TypedArena::clear and improve common patterns
  src/libarena/lib.rs
Labels: S-waiting-on-bors

#56394 Deal with EINTR in net timeout tests
  src/libstd/net/tcp.rs
  src/libstd/net/udp.rs
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors

#55010 Add template parameter debuginfo to generic types
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/rustllvm/RustWrapper.cpp
  src/test/codegen/generic-debug.rs
  src/test/debuginfo/associated-types.rs
  src/test/debuginfo/generic-method-on-generic-struct.rs
  src/test/debuginfo/generic-struct.rs
  src/test/debuginfo/generic-tuple-style-enum.rs
  src/test/debuginfo/method-on-generic-struct.rs
Labels: S-waiting-on-bors

#56141 [std] Osstr len clarity
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors, T-doc

#56395 Stabilize dbg!(...)
  src/libstd/macros.rs
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior.rs
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-feature-gate.rs
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-feature-gate.stderr
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.nll.stderr
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.rs
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.stderr
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-requires-debug.rs
  src/test/ui/rfc-2361-dbg-macro/dbg-macro-requires-debug.stderr
Labels: S-waiting-on-bors, relnotes

#56401 Move VecDeque::resize_with out of the impl<T:Clone> block
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors

#56402 Improve the unstable book example for #[marker] trait
  src/doc/unstable-book/src/language-features/marker-trait-attr.md
Labels: S-waiting-on-bors

#56412 Update tracking issue for `extern_crate_self`
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gates/feature-gate-extern_crate_self.stderr
Labels: S-waiting-on-bors

#56416 Remove unneeded body class selector
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#56419 Remove some uses of try!
  src/bootstrap/doc.rs
  src/bootstrap/util.rs
  src/libcore/macros.rs
  src/librustc_incremental/persist/fs.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_target/spec/mod.rs
  src/libstd/fs.rs
  src/libstd/sys/windows/stdio.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax_ext/format_foreign.rs
Labels: S-waiting-on-bors

#56432 Update issue number of `shrink_to` methods to point the tracking issue
  src/liballoc/collections/binary_heap.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/string.rs
  src/liballoc/vec.rs
  src/libstd/collections/hash/map.rs
  src/libstd/collections/hash/set.rs
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors

#56433 Add description about `crate` for parse_visibility's comment
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#56438 Remove not used `DotEq` token
  src/librustc/ich/impls_syntax.rs
  src/librustdoc/html/highlight.rs
  src/libsyntax/ext/quote.rs
  src/libsyntax/parse/token.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax_ext/proc_macro_server.rs
Labels: S-waiting-on-bors

#56455 Stable 1.31.0 release
  src/ci/run.sh
Labels: S-waiting-on-bors

#56467 Bump stack size to 32MB
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors, beta-nominated

#55871 codegen_llvm_back: improve allocations
  src/librustc_codegen_llvm/back/link.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/rpath.rs
  src/librustc_codegen_ssa/back/symbol_export.rs
Labels: S-waiting-on-bors

#56524 Update promoted master for beta channel
  src/ci/run.sh
  src/stage0.txt
Labels: S-waiting-on-bors

#51753 Document `From` implementations
  src/libstd/path.rs
Labels: S-waiting-on-bors, T-doc

#55563 Improve no result found sentence in doc search
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#56119 Utilize `?` instead of `return None`.
  src/libcore/str/mod.rs
  src/librustc/middle/region.rs
  src/librustc/session/search_paths.rs
  src/librustc_incremental/persist/work_product.rs
  src/librustc_mir/borrow_check/prefixes.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/render.rs
  src/libstd/sys/windows/path.rs
  src/test/run-pass/impl-trait/example-calendar.rs
  src/tools/compiletest/src/errors.rs
  src/tools/compiletest/src/header.rs
  src/tools/linkchecker/main.rs
Labels: S-waiting-on-bors

#56372 Refer to the second borrow as the "second borrow" in E0501.rs
  src/librustc_borrowck/borrowck/check_loans.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/test/ui/E0501.ast.nll.stderr
  src/test/ui/E0501.mir.stderr
  src/test/ui/borrowck/borrowck-insert-during-each.nll.stderr
  src/test/ui/generator/yield-while-ref-reborrowed.nll.stderr
  src/test/ui/nll/closure-borrow-spans.stderr
Labels: S-waiting-on-bors

#56424 Mention raw-ident syntax
  src/libcore/macros.rs
Labels: S-waiting-on-bors

#56456 Handle existential types in dead code analysis
  src/librustc/middle/dead.rs
  src/test/ui/existential_types/private_unused.rs
Labels: S-waiting-on-bors

#56466 data_structures: remove tuple_slice
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/tuple_slice.rs
Labels: S-waiting-on-bors

#56476 Fix invalid line number match
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#56497 cleanup: remove static lifetimes from consts in libstd
  src/libstd/env.rs
  src/libstd/ffi/c_str.rs
  src/libstd/keyword_docs.rs
  src/libstd/sys/cloudabi/shims/env.rs
  src/libstd/sys/redox/env.rs
  src/libstd/sys/redox/path.rs
  src/libstd/sys/redox/process.rs
  src/libstd/sys/unix/env.rs
  src/libstd/sys/unix/path.rs
  src/libstd/sys/unix/process/process_unix.rs
  src/libstd/sys/wasm/env.rs
  src/libstd/sys/wasm/path.rs
  src/libstd/sys/windows/env.rs
  src/libstd/sys/windows/os.rs
  src/libstd/sys/windows/path.rs
  src/libstd/sys_common/wtf8.rs
Labels: S-waiting-on-bors

#56498 Fix line numbers display
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#56441 rustbuild: Fix issues with compiler docs
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors

#56446 pass the parameter environment to `traits::find_associated_item`
  src/librustc/traits/specialize/mod.rs
  src/librustc/traits/structural_impls.rs
  src/librustc/ty/instance.rs
  src/test/run-pass/issue-55380.rs
Labels: S-waiting-on-bors

#56500 cleanup: remove static lifetimes from consts
  src/liballoc/string.rs
  src/libcore/fmt/mod.rs
  src/libcore/unicode/printable.rs
  src/librustc/dep_graph/dep_node.rs
  src/librustc/hir/print.rs
  src/librustc/ich/mod.rs
  src/librustc/session/config.rs
  src/librustc/session/filesearch.rs
  src/librustc/util/common.rs
  src/librustc_codegen_ssa/back/symbol_export.rs
  src/librustc_codegen_utils/symbol_names.rs
  src/librustc_incremental/assert_module_sources.rs
  src/librustc_incremental/persist/file_format.rs
  src/librustc_incremental/persist/fs.rs
  src/librustc_metadata/schema.rs
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_mir/diagnostics.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_target/spec/mod.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/parse/attr.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
  src/libsyntax_ext/asm.rs
  src/libsyntax_ext/global_asm.rs
  src/libsyntax_ext/proc_macro_decls.rs
  src/libsyntax_pos/edition.rs
Labels: S-waiting-on-author

#56525 Avoid extra copy and syscall in std::env::current_exe
  src/libstd/sys/unix/os.rs
Labels: S-waiting-on-bors

#56528 Remove unused dependency (rustc_lint -> rustc_mir)
  Cargo.lock
  src/librustc_lint/Cargo.toml
  src/librustc_lint/lib.rs
Labels: S-waiting-on-bors

#56548 Optimized string FromIterator + Extend impls
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#56553 Don't print the profiling summary to stdout when -Zprofile-json is set
  src/librustc/session/mod.rs
  src/librustc_driver/driver.rs
Labels: S-waiting-on-bors

#54271 Unsupport `#[derive(Trait)]` sugar for `#[derive_Trait]` legacy plugin attributes
  src/librustc_driver/driver.rs
  src/librustc_plugin/registry.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/libsyntax/ext/base.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax_ext/lib.rs
  src/test/compile-fail/proc-macro/derive-still-gated.rs
  src/test/run-pass-fulldeps/auxiliary/custom_derive_plugin.rs
  src/test/run-pass-fulldeps/custom-derive-partial-eq.rs
  src/test/run-pass-fulldeps/custom-derive-partial-eq.stderr
  src/test/run-pass-fulldeps/derive-totalsum-attr.rs
  src/test/run-pass-fulldeps/derive-totalsum.rs
  src/test/run-pass-fulldeps/issue-40663.rs
  src/test/ui/feature-gates/feature-gate-custom_derive.rs
  src/test/ui/feature-gates/feature-gate-custom_derive.stderr
  src/test/ui/issues/issue-32655.rs
  src/test/ui/issues/issue-32655.stderr
Labels: S-waiting-on-bors

#56000 Add Armv8-M Mainline targets
  src/librustc_target/spec/mod.rs
  src/librustc_target/spec/thumb_base.rs
  src/librustc_target/spec/thumbv8m_main_none_eabi.rs
  src/librustc_target/spec/thumbv8m_main_none_eabihf.rs
Labels: S-waiting-on-bors

#56250 Introduce ptr::hash for references
  src/libcore/ptr.rs
Labels: S-waiting-on-bors

#56516 Replace usages of `..i + 1` ranges with `..=i`.
  src/liballoc/collections/vec_deque.rs
  src/liballoc/tests/binary_heap.rs
  src/liballoc/tests/btree/map.rs
  src/liballoc/tests/str.rs
  src/liballoc/tests/vec_deque.rs
  src/librustc/hir/map/hir_id_validator.rs
  src/librustc/mir/mod.rs
  src/librustc_apfloat/ieee.rs
  src/librustc_errors/emitter.rs
  src/librustc_incremental/persist/fs.rs
  src/librustc_mir/borrow_check/nll/region_infer/values.rs
  src/librustc_mir/build/matches/mod.rs
  src/librustc_resolve/lib.rs
  src/librustdoc/html/render.rs
  src/libstd/collections/hash/map.rs
  src/libstd/io/buffered.rs
  src/libstd/io/mod.rs
  src/libstd/sys/windows/process.rs
  src/libsyntax/util/lev_distance.rs
Labels: S-waiting-on-bors

#56555 Send textual profile data to stderr, not stdout
  src/librustc/util/profiling.rs
Labels: S-waiting-on-bors

#56561 Fix bug in from_key_hashed_nocheck
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#56574 Fix a stutter in the docs for slice::exact_chunks
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#56487 Discard LLVM modules earlier when performing ThinLTO
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/traits/write.rs
Labels: S-waiting-on-bors

#56566 codegen_utils, driver: fix clippy errors
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_driver/lib.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: S-waiting-on-bors

#56258 use top level `fs` functions where appropriate
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
  src/bootstrap/dist.rs
  src/bootstrap/doc.rs
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
  src/bootstrap/sanity.rs
  src/bootstrap/test.rs
  src/libcore/convert.rs
  src/librustc/infer/lexical_region_resolve/graphviz.rs
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustdoc/html/render.rs
  src/librustdoc/theme.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/source_util.rs
  src/libsyntax/source_map.rs
  src/tools/build-manifest/src/main.rs
  src/tools/cargotest/main.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
  src/tools/error_index_generator/main.rs
  src/tools/tidy/src/bins.rs
  src/tools/tidy/src/cargo.rs
  src/tools/tidy/src/deps.rs
  src/tools/tidy/src/extdeps.rs
  src/tools/tidy/src/features.rs
Labels: S-waiting-on-bors

#56583 update vergen
  Cargo.lock
Labels: S-waiting-on-bors

#56597 Improve the usage message for `-Z dump-mir`.
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#56599 codegen: Fix va_list - aarch64 iOS/Windows
  src/libcore/ffi.rs
  src/librustc_codegen_llvm/va_arg.rs
Labels: S-waiting-on-bors

#56602 Fix the just-introduced ptr::hash docs
  src/libcore/ptr.rs
Labels: S-waiting-on-bors

#56620 resolve: Reduce some clutter in import ambiguity errors
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/issue-56125.rs
  src/test/ui/imports/issue-56125.stderr
Labels: S-waiting-on-bors

#56621 Add missing comma in Generators
  src/doc/unstable-book/src/language-features/generators.md
Labels: S-waiting-on-bors

#56632 Reduce the number of syn versions compiled from 4 to 2
  Cargo.lock
  src/tools/rustc-workspace-hack/Cargo.toml
Labels: S-waiting-on-bors

#56616 Encode `TraitAlias` as if they were `Trait`
  src/librustc_metadata/encoder.rs
  src/test/ui/run-pass/traits/trait-alias.rs
Labels: S-waiting-on-bors

#56644 Fix security link in CONTRIBUTING to its new place
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#56463 slice: tweak concat & join
  src/liballoc/slice.rs
Labels: S-waiting-on-bors, T-libs

#56369 Remove `tokenstream::Delimited`.
  src/librustc/hir/lowering.rs
  src/librustc/ich/impls_syntax.rs
  src/librustc_lint/builtin.rs
  src/libsyntax/ast.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/quote.rs
  src/libsyntax/ext/tt/quoted.rs
  src/libsyntax/ext/tt/transcribe.rs
  src/libsyntax/fold.rs
  src/libsyntax/parse/lexer/tokentrees.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/tokenstream.rs
  src/libsyntax/visit.rs
  src/libsyntax_ext/proc_macro_server.rs
Labels: S-waiting-on-bors

#56157 expand thread::park explanation
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#56491 emit error with span for empty asserts
  src/libsyntax_ext/assert.rs
  src/test/ui/macros/assert.rs
  src/test/ui/macros/assert.stderr
Labels: S-waiting-on-bors

#56633 Fix right arrow size for crate filter
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#56641 fix span for invalid number of parameters in trait method
  src/librustc_typeck/check/compare_method.rs
  src/test/ui/error-codes/E0050.stderr
  src/test/ui/trait-method-number-parameters.rs
  src/test/ui/trait-method-number-parameters.stderr
  src/test/ui/traits/trait-impl-different-num-params.stderr
Labels: S-waiting-on-bors

#56656 Fix typo
  src/liballoc/string.rs
Labels: S-waiting-on-bors

#56661 Add regression test for ICE
  src/test/ui/issue-55846.rs
Labels: S-waiting-on-bors

#53497 Test with gdb8.2 and add debuginfo printing function call test
  src/test/debuginfo/function-call.rs
Labels: S-waiting-on-bors

#56010 fix intra-link resolution spans in block comments
  src/librustdoc/clean/mod.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/.gitattributes
  src/test/rustdoc-ui/intra-links-warning-crlf.rs
  src/test/rustdoc-ui/intra-links-warning-crlf.stderr
  src/test/rustdoc-ui/intra-links-warning.rs
  src/test/rustdoc-ui/intra-links-warning.stderr
Labels: S-waiting-on-bors

#56039 SortedMap upgrades
  src/librustc_data_structures/sorted_map.rs
Labels: S-waiting-on-bors

#56735 Fix gpg signing in manifest builder
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#55992 Expand std::pin module docs and rename std::pin::Pinned to PhantomPinned
  src/libcore/marker.rs
  src/libcore/pin.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, final-comment-period

#55982 rustc: Switch `extern` functions to abort by default on panic
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/callee.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/declare.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/mono_item.rs
  src/librustc_mir/build/mod.rs
  src/test/codegen/nounwind-extern.rs
  src/test/run-pass/abort-on-c-abi.rs
  src/test/run-pass/extern/extern-call-deep.rs
Labels: S-waiting-on-bors, relnotes

#56783 Add `--pinentry-mode=loopback` to deployment script
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#56351 Stabilize `linker-flavor` flag.
  src/doc/rustc/src/codegen-options/index.md
  src/doc/unstable-book/src/compiler-flags/linker-flavor.md
  src/librustc/session/config.rs
  src/librustc_codegen_ssa/back/link.rs
  src/test/compile-fail/issue-10755.rs
  src/test/compile-fail/nolink-with-link-args.rs
  src/test/ui/feature-gates/feature-gate-linker-flavor.rs
  src/test/ui/feature-gates/feature-gate-linker-flavor.stderr
Labels: S-waiting-on-bors, T-compiler, disposition-merge, final-comment-period, relnotes

#56562 Update libc version required by rustc
  src/librustc_codegen_ssa/Cargo.toml
Labels: S-waiting-on-author, T-libs, beta-accepted, beta-nominated, stable-nominated

#56609 Unconditionally emit the target-cpu LLVM attribute.
  src/librustc_codegen_llvm/attributes.rs
Labels: S-waiting-on-bors

#56637 rustdoc: Fix local reexports of proc macros
  src/librustdoc/html/render.rs
  src/librustdoc/visit_ast.rs
  src/test/rustdoc/proc-macro.rs
Labels: S-waiting-on-bors

#56658 Add non-panicking `maybe_new_parser_from_file` variant
  src/libsyntax/parse/mod.rs
Labels: S-waiting-on-bors

#56695 Fix irrefutable matches on integer ranges
  src/librustc_mir/build/matches/simplify.rs
  src/test/ui/pattern/irrefutable-exhaustive-integer-binding.rs
Labels: S-waiting-on-bors

#56699 Use a `newtype_index!` within `Symbol`.
  src/libsyntax/parse/token.rs
  src/libsyntax_pos/lib.rs
  src/libsyntax_pos/symbol.rs
Labels: S-waiting-on-bors

#56702 [self-profiler] Add column for percent of total time
  src/librustc/util/profiling.rs
Labels: S-waiting-on-bors

#56709 Remove unneeded extra chars to reduce search-index size
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#56744 specialize: remove Boxes used by Children::insert
  src/librustc/traits/specialize/specialization_graph.rs
Labels: S-waiting-on-bors

#56748 Update panic message to be clearer about env-vars
  src/libstd/panicking.rs
  src/test/run-make-fulldeps/libtest-json/output.json
  src/test/run-pass/multi-panic.rs
  src/test/rustdoc-ui/failed-doctest-output.stdout
Labels: S-waiting-on-bors

#56749 x86: Add the `adx` target feature to whitelist
  src/librustc_codegen_llvm/llvm_util.rs
Labels: S-waiting-on-bors

#56756 Disable btree pretty-printers on older gdbs
  src/etc/gdb_rust_pretty_printing.py
  src/test/debuginfo/pretty-std-collections.rs
Labels: S-waiting-on-bors

#56572 Contexually dependent error message for E0424 when value is assigned to "self"
  src/librustc_resolve/lib.rs
  src/test/ui/error-codes/E0424.rs
  src/test/ui/error-codes/E0424.stderr
Labels: S-waiting-on-bors

#56825 std: Activate compiler_builtins `mem` feature for no_std targets
  src/bootstrap/compile.rs
  src/liballoc/Cargo.toml
Labels: S-waiting-on-bors

#56584 2018 edition - confusing error message when declaring unnamed parameters
  src/libsyntax/parse/parser.rs
  src/test/ui/anon-params-denied-2018.stderr
Labels: S-waiting-on-bors

#56725 fix rust-lang/rust issue #50583
  src/ci/docker/dist-various-1/Dockerfile
Labels: S-waiting-on-bors

#56731 Add missing urls in ffi module docs
  src/libstd/ffi/mod.rs
Labels: S-waiting-on-bors

#56738 Fix private_no_mangle_fns message grammar
  src/librustc_lint/lib.rs
  src/test/ui/lint/lint-unexported-no-mangle.stderr
Labels: S-waiting-on-bors

#56746 Add test of current behavior (infer free region within closure body)
  src/test/ui/regions/issue-56537-closure-uses-region-from-container.rs
Labels: A-NLL, A-closures, A-lifetimes, S-waiting-on-bors

#56747 target: remove Box returned by get_targets
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#56751 Allow ptr::hash to accept fat pointers
  src/libcore/ptr.rs
Labels: S-waiting-on-bors

#56755 Account for `impl Trait` when suggesting lifetime
  src/librustc/infer/error_reporting/mod.rs
  src/test/ui/suggestions/suggest-impl-trait-lifetime.fixed
  src/test/ui/suggestions/suggest-impl-trait-lifetime.rs
  src/test/ui/suggestions/suggest-impl-trait-lifetime.stderr
Labels: S-waiting-on-bors

#56758 Add short emoji status to toolstate updates
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#56769 Add x86_64-unknown-uefi target
  src/librustc_target/spec/mod.rs
  src/librustc_target/spec/uefi_base.rs
  src/librustc_target/spec/x86_64_unknown_uefi.rs
Labels: S-waiting-on-bors

#56792 Bootstrap: Add testsuite for compiletest tool
  src/bootstrap/builder.rs
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#56808 Fixes broken links
  src/doc/rustc/src/targets/built-in.md
  src/doc/rustc/src/targets/index.md
  src/doc/unstable-book/src/language-features/unsized-locals.md
Labels: S-waiting-on-bors

#56809 Fix docs path to PermissionsExt
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#56679 overhaul external doc attribute diagnostics
  src/libsyntax/ext/expand.rs
  src/test/ui/extern/auxiliary/invalid-utf8.txt
  src/test/ui/extern/external-doc-error.rs
  src/test/ui/extern/external-doc-error.stderr
Labels: S-waiting-on-bors

#56691 fix install broken link
  README.md
Labels: S-waiting-on-bors

#56710 Always set the RDRAND and RDSEED features on SGX
  src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs
Labels: S-waiting-on-bors

#56713 Test capacity of ZST vector
  src/liballoc/tests/vec.rs
Labels: S-waiting-on-bors

#56847 Revert merge of #56758 - Manishearth:emoji-status-toolstate
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#56600 bootstrap: fix edition
  src/bootstrap/Cargo.toml
  src/bootstrap/builder.rs
  src/bootstrap/cache.rs
  src/bootstrap/cc_detect.rs
  src/bootstrap/channel.rs
  src/bootstrap/check.rs
  src/bootstrap/clean.rs
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
  src/bootstrap/dist.rs
  src/bootstrap/doc.rs
  src/bootstrap/flags.rs
  src/bootstrap/install.rs
  src/bootstrap/job.rs
  src/bootstrap/lib.rs
  src/bootstrap/metadata.rs
  src/bootstrap/native.rs
  src/bootstrap/sanity.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/bootstrap/util.rs
Labels: S-waiting-on-bors

#56764 mir-opt: Make SimplifyCfg collapse goto chains starting from bb0
  src/librustc_mir/transform/simplify.rs
  src/test/mir-opt/simplify_cfg.rs
Labels: S-waiting-on-bors

#56833 Provide -isysroot with sdkroot for ios builds
  src/librustc_target/spec/apple_ios_base.rs
Labels: S-waiting-on-bors

#56904 Remove Cycle::try_fold override
  src/libcore/iter/mod.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#56303 Stabilize `underscore_imports`
  src/librustc_mir/lib.rs
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gates/feature-gate-underscore-imports.rs
  src/test/ui/feature-gates/feature-gate-underscore-imports.stderr
  src/test/ui/rfc-2166-underscore-imports/auxiliary/underscore-imports.rs
  src/test/ui/rfc-2166-underscore-imports/basic.rs
  src/test/ui/rfc-2166-underscore-imports/basic.stderr
  src/test/ui/rfc-2166-underscore-imports/duplicate.rs
  src/test/ui/rfc-2166-underscore-imports/unused-2018.rs
  src/test/ui/rfc-2166-underscore-imports/unused-2018.stderr
  src/test/ui/rust-2018/future-proofing-locals.rs
  src/test/ui/rust-2018/uniform-paths/macro-rules.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#56819 [beta] rustdoc: fix line numbers display for [src] pages
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#56893 [beta] Revert "Update CI-clang to 7.0.0 for Linux dists."
  src/ci/docker/dist-i686-linux/Dockerfile
  src/ci/docker/dist-x86_64-linux/Dockerfile
  src/ci/docker/dist-x86_64-linux/build-clang.sh
  src/ci/docker/scripts/musl.sh
Labels: S-waiting-on-bors

#56397 Search other library paths when loking for link objects
  src/librustc_codegen_llvm/back/link.rs
  src/test/run-make-fulldeps/libs-search-path/Makefile
  src/test/run-make-fulldeps/libs-search-path/empty.rs
Labels: S-waiting-on-bors

#56741 treat ref-to-raw cast like a reborrow: do a special kind of retag
  src/librustc/ich/impls_mir.rs
  src/librustc/mir/mod.rs
  src/librustc/mir/visit.rs
  src/librustc_codegen_ssa/mir/statement.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/nll/invalidation.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/dataflow/impls/borrows.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/interpret/cast.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/add_retag.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir/transform/remove_noop_landing_pads.rs
  src/librustc_mir/transform/rustc_peek.rs
  src/test/mir-opt/retag.rs
Labels: S-waiting-on-bors

#56813 Always run rustc in a thread
  src/librustc_driver/lib.rs
  src/libstd/rt.rs
  src/libstd/sys/cloudabi/thread.rs
  src/libstd/sys/redox/thread.rs
  src/libstd/sys/sgx/thread.rs
  src/libstd/sys/unix/thread.rs
  src/libstd/sys/wasm/thread.rs
  src/libstd/sys/windows/thread.rs
Labels: S-waiting-on-bors

#57033 Remove "visited" set from inhabitedness checking (fix perf regression)
  src/librustc/ty/inhabitedness/mod.rs
Labels: S-waiting-on-bors

#56862 stop treating trait objects from #[fundamental] traits as fundamental
  src/librustc/traits/coherence.rs
  src/test/ui/coherence/auxiliary/coherence_fundamental_trait_lib.rs
  src/test/ui/coherence/coherence-fundamental-trait-objects.rs
  src/test/ui/coherence/coherence-fundamental-trait-objects.stderr
Labels: S-waiting-on-bors

#56802 Add DoubleEndedIterator::nth_back
  src/libcore/iter/mod.rs
  src/libcore/iter/traits.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors

#56909 static eval: Do not ICE on layout size overflow
  src/librustc_mir/const_eval.rs
  src/test/ui/issues/issue-56762.rs
  src/test/ui/issues/issue-56762.stderr
Labels: S-waiting-on-bors

#56914 Ignore ui/target-feature-gate on sparc, sparc64, powerpc, powerpc64 and powerpc64le
  src/test/ui/target-feature-gate.rs
  src/test/ui/target-feature-gate.stderr
Labels: S-waiting-on-bors

#56933 Add --progress to git submodule commands in x.py
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#56941 deny intra-doc link resolution failures in libstd
  src/liballoc/lib.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/libcore/lib.rs
  src/libcore/mem.rs
  src/libcore/slice/mod.rs
  src/libstd/io/buffered.rs
  src/libstd/io/error.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#56945 Fix rustdoc-js tests
  src/tools/rustdoc-js/tester.js
Labels: S-waiting-on-bors

#56967 Replace current crate's searchIndex when regenerating
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#56970 Mem uninit doc ptr drop
  src/libcore/mem.rs
Labels: S-waiting-on-bors

#56973 make basic CTFE tracing available on release builds
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/step.rs
Labels: S-waiting-on-bors

#56979 Adding unwinding support for x86_64_fortanix_unknown_sgx target.
  src/libpanic_unwind/lib.rs
  src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs
  src/libstd/sys/sgx/abi/entry.S
  src/libstd/sys/sgx/rwlock.rs
  src/libunwind/lib.rs
Labels: S-waiting-on-bors

#56981 miri: allocation is infallible
  src/librustc_mir/const_eval.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/traits.rs
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-bors

#56984 A few tweaks to dropck_outlives
  src/librustc/traits/query/dropck_outlives.rs
Labels: S-waiting-on-bors

#56989 Fix compiletest `trim` deprecation warnings
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#56992 suggest similar lint names for unknown lints
  src/librustc/lint/context.rs
  src/librustc/lint/levels.rs
  src/test/ui/lint/lint-unknown-lint-cmdline.rs
  src/test/ui/lint/lint-unknown-lint-cmdline.stderr
  src/test/ui/lint/lint-unknown-lint.rs
  src/test/ui/lint/lint-unknown-lint.stderr
  src/test/ui/lint/not_found.stderr
Labels: S-waiting-on-bors

#57002 Stabilize Vec(Deque)::resize_with
  src/liballoc/collections/vec_deque.rs
  src/liballoc/vec.rs
  src/librustc_data_structures/lib.rs
Labels: S-waiting-on-bors, relnotes

#57027 Optimize away a move
  src/librustc/ty/query/plumbing.rs
Labels: S-waiting-on-bors

#57034 Inline tweaks
  src/librustc/ty/context.rs
  src/librustc/ty/query/plumbing.rs
  src/librustc_data_structures/lib.rs
  src/libserialize/opaque.rs
  src/libstd/collections/hash/table.rs
Labels: S-waiting-on-bors

#57039 Update migrate warning wording.
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/borrowck/borrowck-anon-fields-variant.nll.stderr
  src/test/ui/borrowck/borrowck-describe-lvalue.ast.nll.stderr
  src/test/ui/borrowck/borrowck-migrate-to-nll.edition.stderr
  src/test/ui/borrowck/borrowck-migrate-to-nll.zflag.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.nll.stderr
  src/test/ui/consts/min_const_fn/min_const_fn_dyn.nll.stderr
  src/test/ui/issues/issue-40510-1.nll.stderr
  src/test/ui/issues/issue-40510-3.nll.stderr
  src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.ast.stderr
  src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.migrate.stderr
  src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.nll.stderr
  src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.rs
  src/test/ui/issues/issue-49824.nll.stderr
  src/test/ui/nll/match-guards-always-borrow.ast.nll.stderr
  src/test/ui/thread-local-in-ctfe.nll.stderr
Labels: S-waiting-on-bors

#57040 Fix feature gate to point to 1.32.0 for `path_from_str`
  src/libstd/path.rs
Labels: S-waiting-on-bors

#57050 Fixed typo in HashMap documentation
  src/libstd/collections/hash/map.rs
Labels: S-waiting-on-bors

#57052 Fix stabilization version numbers (exhaustive_integer_patterns + macro_literal_matcher)
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#56892 rustc: Update Clang used to build LLVM on Linux
  src/ci/docker/dist-x86_64-linux/build-clang.sh
Labels: S-waiting-on-bors

#56342 Improve docs for collecting into `Option`s
  src/libcore/option.rs
Labels: S-waiting-on-bors

#56917 Simplify MIR generation for logical operations
  src/librustc_mir/build/expr/into.rs
Labels: S-waiting-on-bors

#56964 Remove `TokenStream::JointTree`.
  src/libsyntax/parse/lexer/tokentrees.rs
  src/libsyntax/tokenstream.rs
  src/libsyntax_ext/proc_macro_server.rs
Labels: S-waiting-on-bors

#57032 fix deprecation warnings in liballoc benches
  Cargo.lock
  src/liballoc/Cargo.toml
  src/liballoc/benches/btree/map.rs
  src/liballoc/benches/lib.rs
  src/liballoc/benches/slice.rs
  src/liballoc/benches/str.rs
Labels: S-waiting-on-bors

#57053 Fix alignment for array indexing
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/test/codegen/issue-56927.rs
  src/test/codegen/packed.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#57062 Fix a comment
  src/librustc_mir/monomorphize/collector.rs
Labels: S-waiting-on-bors

#55470 box: Add documentation for `From` impls
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#56242 Add missing link in docs
  src/libcore/iter/iterator.rs
Labels: S-waiting-on-bors

#56972 Show platform-specific modules in `std::os` when building those platforms
  src/libstd/os/mod.rs
Labels: S-waiting-on-review

#56986 rustc: Move jemalloc from rustc_driver to rustc
  Cargo.lock
  src/librustc_driver/Cargo.toml
  src/librustc_driver/lib.rs
  src/rustc/Cargo.toml
  src/rustc/rustc.rs
Labels: S-waiting-on-bors

#57021 Enable emission of alignment attrs for pointer params
  src/librustc/session/config.rs
  src/librustc_codegen_llvm/abi.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/test/codegen/function-arguments.rs
Labels: S-waiting-on-bors

#57074 Fix recursion limits
  src/librustc_codegen_ssa/lib.rs
  src/librustc_lint/lib.rs
  src/librustc_passes/lib.rs
  src/librustc_plugin/lib.rs
  src/librustc_resolve/lib.rs
  src/libsyntax_ext/lib.rs
Labels: S-waiting-on-bors

#57085 librustc_codegen_llvm: Don't eliminate empty structs in C ABI on linux-sparc64
  src/librustc_codegen_llvm/abi.rs
Labels: S-waiting-on-author
