Repository rust-lang/rust, pull requests merged in 2019-07, with the labels that each got.

#62062 Use a more efficient iteration order for forward dataflow
  src/librustc_mir/dataflow/mod.rs
Labels: S-waiting-on-bors

#62063 Use a more efficient iteration order for backward dataflow
  src/librustc_mir/util/liveness.rs
Labels: S-waiting-on-bors

#62224 rustdoc: remove unused derives and variants
  src/librustdoc/clean/cfg.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/doctree.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/item_type.rs
  src/librustdoc/html/render.rs
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors

#62239 Fix a typo
  src/libcore/char/methods.rs
Labels: S-waiting-on-bors

#62241 Always parse 'async unsafe fn' + properly ban in 2015
  src/librustc_passes/ast_validation.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/async-await/async-await.rs
  src/test/ui/async-await/edition-deny-async-fns-2015.rs
  src/test/ui/async-await/edition-deny-async-fns-2015.stderr
  src/test/ui/async-await/no-unsafe-async.rs
  src/test/ui/async-await/no-unsafe-async.stderr
Labels: S-waiting-on-bors

#62248 before_exec actually will only get deprecated with 1.37
  RELEASES.md
Labels: S-waiting-on-bors

#62267 Revert "implicit `Option`-returning doctests"
  src/doc/rustdoc/src/documentation-tests.md
  src/librustdoc/test.rs
  src/test/rustdoc/process-termination.rs
Labels: S-waiting-on-bors, merged-by-bors

#62279 ci: explicitly disable CRLF conversion on Windows
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors, merged-by-bors

#62064 nth_back for chunks_exact
  src/libcore/slice/mod.rs
  src/libcore/tests/slice.rs
Labels: S-waiting-on-bors

#62128 Adjust warning of -C extra-filename with -o.
  src/librustc_interface/util.rs
Labels: S-waiting-on-bors

#62161 Add missing links for TryFrom docs
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#62183 std: Move a process test out of libstd
  src/libstd/process.rs
  src/test/run-pass/command-uid-gid.rs
Labels: S-waiting-on-bors

#62186 Add missing type urls in Into trait
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#62196 Add Vec::leak
  src/liballoc/vec.rs
Labels: S-waiting-on-bors, T-libs

#62199 import gdb for explicit access to gdb.current_objfile()
  src/etc/gdb_load_rust_pretty_printers.py
Labels: S-waiting-on-bors

#62229 Enable intptrcast for explicit casts
  src/librustc_mir/interpret/cast.rs
Labels: S-waiting-on-bors

#62250 Improve box clone doctests to ensure the documentation is valid
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#62255 Switch tracking issue for `#![feature(slice_patterns)]`
  src/doc/unstable-book/src/language-features/slice-patterns.md
  src/librustc_typeck/check/_match.rs
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gates/feature-gate-slice-patterns.stderr
Labels: S-waiting-on-bors

#62285 Fix michaelwoerister's mailmap
  .mailmap
Labels: S-waiting-on-bors

#62304 HashMap is UnwindSafe
  src/libstd/collections/hash/map.rs
  src/libstd/panic.rs
Labels: A-collections, S-waiting-on-bors, T-libs, T-release, beta-nominated, regression-from-stable-to-beta

#62319 Fix mismatching Kleene operators
  src/libcore/tests/ascii.rs
  src/libcore/tests/pattern.rs
Labels: S-waiting-on-bors

#62327 Fixed document bug, those replaced each other
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#62173 rename InterpretCx -> InterpCx
  src/librustc/mir/interpret/error.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/interpret/cast.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/mod.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/operator.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/interpret/traits.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/interpret/visitor.rs
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-bors

#62240 wfcheck: resolve the type-vars in `AdtField` types
  src/librustc_typeck/check/wfcheck.rs
  src/test/run-pass/packed/packed-with-inference-vars-issue-61402.rs
Labels: S-waiting-on-bors

#62252 Update mem::replace example to not be identical to mem::take
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#62268 Clean up inherent_impls
  src/librustc_typeck/coherence/inherent_impls.rs
Labels: S-waiting-on-bors

#62287 Use link attributes on extern "C" blocks with llvm-libuwind
  src/libunwind/build.rs
  src/libunwind/libunwind.rs
Labels: S-waiting-on-bors

#62295 miri realloc: do not require giving old size+align
  src/librustc_mir/interpret/memory.rs
Labels: S-waiting-on-bors

#62297 refactor check_for_substitution
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
Labels: S-waiting-on-bors

#62316 When possible without changing semantics, implement Iterator::last in terms of DoubleEndedIterator::next_back for types in liballoc and libcore.
  src/liballoc/boxed.rs
  src/liballoc/collections/binary_heap.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/collections/linked_list.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/string.rs
  src/libcore/ascii.rs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#62337 Fix bucket in CPU usage script
  src/etc/cpu-usage-over-time-plot.sh
Labels: S-waiting-on-bors

#62344 simplify Option::get_or_insert
  src/libcore/option.rs
Labels: S-waiting-on-bors

#62346 enable a few more tests in Miri and update the comment for others
  src/liballoc/tests/vec.rs
  src/libcore/tests/fmt/mod.rs
  src/libcore/tests/ptr.rs
  src/libcore/tests/slice.rs
Labels: S-waiting-on-bors

#62351 remove bogus example from drop_in_place
  src/libcore/ptr/mod.rs
Labels: S-waiting-on-bors

#61392 Use a single CtxtInterners
  src/librustc/ty/context.rs
Labels: S-waiting-on-bors, merged-by-bors

#62150 Implement mem::{zeroed,uninitialized} in terms of MaybeUninit.
  src/libcore/intrinsics.rs
  src/libcore/mem/mod.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_typeck/check/intrinsic.rs
  src/test/run-pass/intrinsics/intrinsic-uninit.rs
  src/test/ui/init-unsafe.rs
  src/test/ui/init-unsafe.stderr
Labels: S-waiting-on-bors

#62169 Derive which queries to save using the proc macro
  src/librustc/query/mod.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc_macros/src/query.rs
Labels: S-waiting-on-bors

#62238 Fix code block information icon position
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors, T-rustdoc

#62323 Clarify unaligned fields in ptr::{read,write}_unaligned
  src/libcore/ptr/mod.rs
Labels: S-waiting-on-bors

#62371 Add tracking issue for Box::into_pin
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#62383 Improve error span for async type inference error
  src/librustc_typeck/check/generator_interior.rs
  src/test/ui/async-await/async-error-span.rs
  src/test/ui/async-await/async-error-span.stderr
Labels: S-waiting-on-bors

#62388 Break out of the correct number of scopes in loops
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/build/scope.rs
  src/test/ui/async-await/await-unsize.rs
  src/test/ui/loops/loop-break-unsize.rs
Labels: S-waiting-on-bors

#62193 Create async version of the dynamic-drop test
  src/test/run-pass/drop/dynamic-drop-async.rs
Labels: S-waiting-on-bors

#62380 rustc_target: avoid negative register counts in the SysV x86_64 ABI.
  src/librustc_target/abi/call/x86_64.rs
  src/test/auxiliary/rust_test_helpers.c
  src/test/run-pass/abi-sysv64-arg-passing.rs
  src/test/run-pass/abi/issues/issue-62350-sysv-neg-reg-counts.rs
Labels: S-waiting-on-bors

#62381 Fix a typo in Write::write_vectored docs
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#62390 Update README.md
  README.md
Labels: S-waiting-on-bors

#62396 remove Scalar::is_null_ptr
  src/librustc/mir/interpret/value.rs
Labels: S-waiting-on-bors

#62406 Lint on invalid values passed to x.py --warnings
  src/bootstrap/config.rs
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#62414 Remove last use of mem::uninitialized in SGX
  src/libstd/sys/sgx/mod.rs
Labels: S-waiting-on-bors

#62151 Update linked OpenSSL version
  Cargo.lock
Labels: S-waiting-on-bors

#62257 forward read_c_str method from Memory to Alloc
  src/librustc_mir/interpret/memory.rs
Labels: S-waiting-on-bors

#62377 Add test for ICE #62375
  src/test/ui/issues/issue-62375.rs
  src/test/ui/issues/issue-62375.stderr
Labels: S-waiting-on-bors

#61862 Make the Weak::{into,as}_raw methods
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#62436 normalize use of backticks/lowercase in compiler messages for librustc_mir
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/hair/pattern/check_match.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/copy_prop.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/instcombine.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/test/ui/bind-by-move/bind-by-move-no-guards.stderr
  src/test/ui/borrowck/borrowck-mutate-in-guard.nll.stderr
  src/test/ui/borrowck/borrowck-mutate-in-guard.stderr
  src/test/ui/consts/const_let_refutable.nll.stderr
  src/test/ui/consts/const_let_refutable.stderr
  src/test/ui/consts/min_const_fn/allow_const_fn_ptr.stderr
  src/test/ui/consts/min_const_fn/bad_const_fn_body_ice.stderr
  src/test/ui/consts/min_const_fn/cast_errors.stderr
  src/test/ui/consts/min_const_fn/cmp_fn_pointers.stderr
  src/test/ui/consts/min_const_fn/loop_ice.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.nll.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.stderr
  src/test/ui/consts/min_const_fn/min_const_fn_dyn.nll.stderr
  src/test/ui/consts/min_const_fn/min_const_fn_dyn.stderr
  src/test/ui/consts/min_const_fn/min_const_fn_fn_ptr.stderr
  src/test/ui/consts/min_const_fn/min_const_fn_libstd_stability.stderr
  src/test/ui/consts/min_const_fn/min_const_unsafe_fn_libstd_stability.stderr
  src/test/ui/consts/min_const_fn/min_const_unsafe_fn_libstd_stability2.stderr
  src/test/ui/consts/min_const_fn/mutable_borrow.stderr
  src/test/ui/consts/single_variant_match_ice.stderr
  src/test/ui/derives/deriving-with-repr-packed.rs
  src/test/ui/derives/deriving-with-repr-packed.stderr
  src/test/ui/error-codes/E0008.stderr
  src/test/ui/error-codes/E0301.stderr
  src/test/ui/issues/issue-37550.stderr
  src/test/ui/rfc-0107-bind-by-move-pattern-guards/feature-gate.no_gate.stderr
  src/test/ui/unsafe/ranged_ints2_const.stderr
Labels: S-waiting-on-bors

#61990 First question mark in doctest
  src/libcore/macros.rs
Labels: S-waiting-on-bors

#62379 Add missing links in Option documentation
  src/libcore/option.rs
Labels: S-waiting-on-bors

#62438 rustbuild: Cleanup global lint settings
  src/bootstrap/bin/rustc.rs
Labels: S-waiting-on-bors

#62455 name the trait in ambiguous-associated-items fully qualified suggestion
  src/librustc_typeck/astconv.rs
  src/test/ui/type-alias-enum-variants/enum-variant-priority-lint-ambiguous_associated_items.stderr
Labels: S-waiting-on-bors

#61883 `non_ascii_idents` lint (part of RFC 2457)
  src/librustc_lint/lib.rs
  src/librustc_lint/non_ascii_idents.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-non-ascii-idents.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-non-ascii-idents.stderr
Labels: S-waiting-on-bors

#62286 Check if the archive has already been added to avoid duplicates
  src/librustc_codegen_llvm/back/archive.rs
Labels: S-waiting-on-bors

#62435 Use const generics for array impls [part 1]
  src/libcore/array.rs
  src/libcore/lib.rs
  src/test/ui/const-generics/array-impls/core-traits-impls-length-32.rs
  src/test/ui/const-generics/array-impls/core-traits-no-impls-length-33.rs
  src/test/ui/const-generics/array-impls/core-traits-no-impls-length-33.stderr
  src/test/ui/const-generics/broken-mir-2.rs
  src/test/ui/const-generics/broken-mir-2.stderr
  src/test/ui/const-generics/derive-debug-array-wrapper.rs
  src/test/ui/const-generics/derive-debug-array-wrapper.stderr
Labels: S-waiting-on-bors, merged-by-bors

#62026 Final nail in `rand 0.4` coffin
  Cargo.lock
Labels: S-waiting-on-bors, merged-by-bors

#62356 Implement Option::contains and Result::contains
  src/libcore/option.rs
  src/libcore/result.rs
Labels: S-waiting-on-bors

#62462 Document `while` keyword
  src/libstd/keyword_docs.rs
Labels: S-waiting-on-bors

#62472 Normalize use of backticks in compiler messages p2
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/generator_interior.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/regionck.rs
  src/librustc_typeck/check/writeback.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/error_codes.rs
  src/librustc_typeck/variance/solve.rs
  src/test/ui/feature-gates/feature-gate-simd-ffi.stderr
  src/test/ui/inference/inference_unstable.stderr
  src/test/ui/target-feature-wrong.rs
  src/test/ui/target-feature-wrong.stderr
Labels: S-waiting-on-bors

#62477 Re-add bootstrap attribute to libunwind for llvm-libunwind feature
  src/libunwind/build.rs
  src/libunwind/libunwind.rs
Labels: S-waiting-on-bors

#62478 normalize use of backticks for compiler messages in librustc_codegen
  src/librustc_codegen_llvm/asm.rs
  src/librustc_codegen_llvm/builder.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_codegen_utils/link.rs
  src/test/ui/crate-name-mismatch.rs
  src/test/ui/crate-name-mismatch.stderr
  src/test/ui/duplicate/dupe-symbols-7.stderr
Labels: S-waiting-on-bors

#62374 [beta] Swap to stable release
  src/stage0.txt
Labels: S-waiting-on-bors, merged-by-bors

#62366 Add float conversions to and from bytes
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
Labels: S-waiting-on-bors, merged-by-bors

#62473 Only call the closure parameter of Iterator::is_sorted_by_key once per item
  src/libcore/iter/traits/iterator.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#62090 typeck: merge opaque type inference logic
  src/librustc/infer/opaque_types/mod.rs
  src/librustc_typeck/check/writeback.rs
  src/test/ui/impl-trait/issue-55872-1.rs
  src/test/ui/impl-trait/issue-55872-1.stderr
  src/test/ui/impl-trait/issue-55872-2.rs
  src/test/ui/impl-trait/issue-55872-2.stderr
  src/test/ui/impl-trait/issue-55872.rs
  src/test/ui/impl-trait/issue-55872.stderr
Labels: S-waiting-on-bors

#62403 Replace SliceConcatExt trait with inherent methods and SliceConcat helper trait
  src/liballoc/prelude/v1.rs
  src/liballoc/slice.rs
  src/liballoc/str.rs
  src/libstd/prelude/mod.rs
  src/libstd/prelude/v1.rs
Labels: S-waiting-on-bors, T-libs

#62494 Remove unused dependencies
  Cargo.lock
  src/librustc_codegen_ssa/Cargo.toml
  src/librustc_driver/Cargo.toml
  src/librustc_interface/Cargo.toml
Labels: S-waiting-on-bors

#62450 Raise the default recursion limit to 128
  src/librustc/middle/recursion_limit.rs
  src/test/rustdoc/deep-structures.rs
  src/test/ui/dropck/dropck_no_diverge_on_nonregular_1.stderr
  src/test/ui/dropck/dropck_no_diverge_on_nonregular_2.stderr
  src/test/ui/dropck/dropck_no_diverge_on_nonregular_3.stderr
  src/test/ui/error-codes/E0275.stderr
  src/test/ui/infinite/infinite-autoderef.stderr
  src/test/ui/infinite/infinite-instantiation.stderr
  src/test/ui/infinite/infinite-macro-expansion.stderr
  src/test/ui/issues/issue-16098.stderr
  src/test/ui/issues/issue-18400.stderr
  src/test/ui/issues/issue-20413.stderr
  src/test/ui/issues/issue-23122-2.stderr
  src/test/ui/issues/issue-8727.stderr
  src/test/ui/recursion/recursion.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#62470 Prevent shrinking of "crate select" element on Firefox
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#62515 cli: make help output for -l and -L consistent
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#62520 Regression test for issue 42574.
  src/test/ui/nll/issue-42574-diagnostic-in-nested-closure.rs
  src/test/ui/nll/issue-42574-diagnostic-in-nested-closure.stderr
Labels: S-waiting-on-bors

#62527 clarify that debug_assert does not completely omits the code
  src/libcore/macros.rs
Labels: S-waiting-on-bors

#62535 ci: Configure $CI_JOB_NAME correctly
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors

#62541 Add spastorino for rustc-guide toolstate
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#61853 Emit warning when trying to use PGO in conjunction with unwinding on …
  src/librustc/session/mod.rs
Labels: S-waiting-on-bors

#62283 Target::arch can take more than listed options
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#62564 Ensure that checkout is with \n line endings
  .azure-pipelines/steps/install-windows-build-deps.yml
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors, merged-by-bors

#62275 rustc_mir: treat DropAndReplace as Drop + Assign in qualify_consts.
  src/librustc_mir/transform/qualify_consts.rs
  src/test/ui/consts/const-eval/const_let.rs
  src/test/ui/consts/const-eval/const_let.stderr
Labels: S-waiting-on-bors

#62481 Use `fold` in `Iterator::last` default implementation
  src/libcore/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#62493 #62357: doc(ptr): add example for {read,write}_unaligned
  src/libcore/ptr/mod.rs
Labels: S-waiting-on-bors

#61665 core: check for pointer equality when comparing Eq slices
  src/libcore/slice/mod.rs
Labels: I-nominated, S-waiting-on-author, T-libs

#61923 Prerequisites from dep graph refactoring #2
  src/librustc/dep_graph/graph.rs
Labels: S-waiting-on-bors

#62425 filedesc: don't use ioctl(FIOCLEX) on Linux
  src/libstd/sys/unix/fd.rs
Labels: S-waiting-on-bors

#62519 Regression test for HRTB bug (issue 30786).
  src/test/ui/hrtb/issue-30786.migrate.stderr
  src/test/ui/hrtb/issue-30786.nll.stderr
  src/test/ui/hrtb/issue-30786.rs
Labels: S-waiting-on-bors

#62557 Fix typo in libcore/intrinsics.rs
  src/libcore/intrinsics.rs
Labels: S-waiting-on-bors

#62549 Update cargo-vendor usage
  CONTRIBUTING.md
  README.md
  src/bootstrap/bootstrap.py
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors, merged-by-bors

#61462 [rustdoc] Fix storage usage when disabled
  src/librustdoc/html/static/storage.js
Labels: S-waiting-on-bors, merged-by-bors

#61535 Coherence test when a generic type param has a default value from an associated type
  src/test/run-pass/coherence/auxiliary/re_rebalance_coherence_lib.rs
  src/test/run-pass/coherence/re-rebalance-coherence-default-generic-associated-type.rs
Labels: S-waiting-on-bors

#62274 rustc_mir: follow FalseUnwind's real_target edge in qualify_consts.
  src/librustc_mir/transform/qualify_consts.rs
  src/test/compile-fail/const-fn-error.rs
  src/test/compile-fail/issue-52443.rs
  src/test/ui/consts/const-eval/infinite_loop.rs
  src/test/ui/consts/const-eval/infinite_loop.stderr
  src/test/ui/consts/const-eval/issue-52442.rs
  src/test/ui/consts/const-eval/issue-52442.stderr
  src/test/ui/consts/const-eval/issue-52475.rs
  src/test/ui/consts/const-eval/issue-52475.stderr
  src/test/ui/consts/const-eval/issue-62272.rs
  src/test/ui/consts/const-labeled-break.rs
  src/test/ui/consts/const-labeled-break.stderr
Labels: S-waiting-on-bors

#62453 in which we suggest anonymizing single-use lifetimes in paths
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/single-use-lifetime/one-use-in-fn-argument.rs
  src/test/ui/single-use-lifetime/one-use-in-fn-argument.stderr
Labels: S-waiting-on-bors

#62578 Add test for #49919
  src/test/ui/issues/issue-49919.rs
  src/test/ui/issues/issue-49919.stderr
Labels: S-waiting-on-bors

#62595 Document that the crate keyword refers to the project root
  src/libstd/keyword_docs.rs
Labels: S-waiting-on-bors

#62599 move mem::uninitialized deprecation back by 1 release, to 1.39
  RELEASES.md
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#62605 Emit dropped unemitted errors to aid in ICE debugging
  src/librustc_errors/diagnostic_builder.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/util/parser_testing.rs
Labels: S-waiting-on-bors, T-compiler

#62577 Add an AtomicCell abstraction
  Cargo.lock
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/sync.rs
Labels: S-waiting-on-bors

#62604 Handle errors during error recovery gracefully
  src/libsyntax/parse/parser.rs
  src/test/ui/parser/issue-62546.rs
  src/test/ui/parser/issue-62546.stderr
Labels: S-waiting-on-bors, beta-nominated

#62636 rustbuild: Improve assert about building tools once
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors

#62584 rustc_codegen_ssa: fix range check in codegen_get_discr.
  src/librustc_codegen_ssa/mir/place.rs
  src/test/run-pass/issues/issue-61696.rs
Labels: S-waiting-on-bors, merged-by-bors

#62560 ci: add a pr builder to test tools when submodules are updated
  .azure-pipelines/pr.yml
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors, merged-by-bors

#62331 Fix leak when early returning out of `box` syntax
  src/librustc_mir/build/expr/as_rvalue.rs
  src/test/mir-opt/issue-62289.rs
Labels: S-waiting-on-bors, merged-by-bors

#62464 Add missing urls for osstr
  src/libstd/ffi/os_str.rs
Labels: S-waiting-on-bors, merged-by-bors

#62610 Fix miri error in into_inner() of CString
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors, merged-by-bors

#62643 Do not emit type errors after parse error in last statement of block
  src/libsyntax/parse/parser.rs
  src/test/ui/obsolete-in-place/bad.rs
  src/test/ui/obsolete-in-place/bad.stderr
  src/test/ui/parser/issue-19096.rs
  src/test/ui/parser/issue-19096.stderr
  src/test/ui/parser/raw/raw-literal-keywords.rs
  src/test/ui/parser/raw/raw-literal-keywords.stderr
  src/test/ui/resolve/token-error-correct-3.rs
  src/test/ui/resolve/token-error-correct-3.stderr
Labels: S-waiting-on-bors, merged-by-bors

#62674 RustIntrinsic and PlatformIntrinsic are also the same ABI as Rust
  src/librustc_mir/interpret/terminator.rs
Labels: S-waiting-on-bors, merged-by-bors

#62405 Remove never_type feature requirement for exhaustive patterns
  src/librustc_mir/build/matches/simplify.rs
  src/test/ui/uninhabited/exhaustive-wo-nevertype-issue-51221.rs
Labels: S-waiting-on-bors

#62491 Fix Pin urls in Option documentation
  src/libcore/option.rs
Labels: S-waiting-on-bors

#62533 Add missing links for CannotReallocInPlace type
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#62634 Less unsafe in the array example of MaybeUninit docs
  src/libcore/mem/maybe_uninit.rs
Labels: S-waiting-on-bors

#62639 Make VaListImpl<'f> invariant over the 'f lifetime
  src/libcore/ffi.rs
  src/test/ui/c-variadic/variadic-ffi-4.nll.stderr
  src/test/ui/c-variadic/variadic-ffi-4.rs
  src/test/ui/c-variadic/variadic-ffi-4.stderr
Labels: S-waiting-on-bors

#62662 add spaces in front of trait requirements in libcore/cell.rs
  src/libcore/cell.rs
Labels: S-waiting-on-bors

#62668 Fix #62660
  src/libsyntax/parse/parser.rs
  src/test/ui/parser/issue-62660.rs
  src/test/ui/parser/issue-62660.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated, stable-nominated

#62673 miri validation: better error messages for dangling references
  src/librustc_mir/interpret/validity.rs
  src/test/ui/consts/const-eval/ub-ref.stderr
  src/test/ui/consts/const-eval/union-ub-fat-ptr.stderr
Labels: S-waiting-on-bors

#62680 Actually call `visit_block_entry` in `DataflowResultsConsumer`
  src/librustc_mir/dataflow/mod.rs
Labels: S-waiting-on-bors

#62685 Add info about undefined behavior to as_ref suggestions
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/issues/issue-21596.stderr
Labels: S-waiting-on-bors

#62689 Fix typo in RawWaker::new documentation
  src/libcore/task/wake.rs
Labels: S-waiting-on-bors

#62698 SGX target: don't pretend to be GNU/Linux to LLVM
  src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs
Labels: S-waiting-on-bors

#62322 Add a query to get the `promoted`s for a `mir::Body`
  src/librustc/query/mod.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/util/pretty.rs
Labels: S-waiting-on-bors, merged-by-bors

#62666 Cancel unemitted diagnostics during error recovery
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#62683 Chapter for `param_attrs`
  src/doc/unstable-book/src/language-features/param-attrs.md
Labels: S-waiting-on-bors

#62693 ci: Remove Travis/AppVeyor configuration
  .travis.yml
  appveyor.yml
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/bootstrap/util.rs
  src/ci/docker/README.md
  src/ci/docker/run.sh
  src/ci/docker/x86_64-gnu-tools/repo.sh
  src/ci/init_repo.sh
  src/ci/run.sh
  src/ci/shared.sh
Labels: S-waiting-on-bors

#62702 normalize use of backticks in compiler messages for libsyntax_ext
  src/libsyntax_ext/deriving/clone.rs
  src/libsyntax_ext/test.rs
  src/test/ui/test-attr-non-associated-functions.rs
  src/test/ui/test-attr-non-associated-functions.stderr
  src/test/ui/test-on-macro.stderr
Labels: S-waiting-on-bors

#62703 normalize use of backticks in compiler messages for libsyntax/parse
  src/libsyntax/parse/attr.rs
  src/libsyntax/parse/diagnostics.rs
  src/libsyntax/parse/lexer/mod.rs
  src/test/ui/issues/issue-22644.stderr
  src/test/ui/issues/issue-34255-1.stderr
  src/test/ui/lifetime_starts_expressions.stderr
  src/test/ui/parser/recover-from-bad-variant.stderr
  src/test/ui/type/type-ascription-instead-of-statement-end.stderr
Labels: S-waiting-on-bors

#62722 ci: Bump time limit of tools builder on PRs
  .azure-pipelines/pr.yml
Labels: S-waiting-on-bors

#61339 Optimize pointer alignment in utf8 validation
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#62757 ci: fix LinuxTools PR builder missing environment variables
  .azure-pipelines/pr.yml
Labels: S-waiting-on-bors, merged-by-bors

#62669 Suggest assoc type on type not found in trait method definition
  src/librustc_resolve/lib.rs
  src/test/ui/suggestions/assoc-type-in-method-return.rs
  src/test/ui/suggestions/assoc-type-in-method-return.stderr
Labels: S-waiting-on-bors, merged-by-bors

#62671 Check for lldb existences
  src/etc/rust-lldb
Labels: S-waiting-on-bors, merged-by-bors

#61926 Fix hyperlinks in From impls between Vec and VecDeque
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors

#62615 Only error about MSVC + PGO + unwind if we're generating code
  src/librustc/session/mod.rs
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated

#62712 Update the help message on error for self type
  src/librustc_typeck/check/wfcheck.rs
  src/test/ui/feature-gates/feature-gate-arbitrary-self-types.stderr
  src/test/ui/feature-gates/feature-gate-arbitrary_self_types-raw-pointer.stderr
  src/test/ui/issues/issue-56806.stderr
  src/test/ui/span/issue-27522.stderr
  src/test/ui/ufcs/ufcs-explicit-self-bad.stderr
Labels: S-waiting-on-bors

#62728 Fix repeated wording in slice documentation
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#62732 Remove last use of mem::uninitialized from std::io::util
  src/libstd/io/util.rs
Labels: S-waiting-on-bors

#62740 Add missing link to Infallible in TryFrom doc
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#62745 update data_layout and features for armv7-wrs-vxworks
  src/librustc_target/spec/arm_wrs_vxworks.rs
  src/librustc_target/spec/armv7_wrs_vxworks.rs
Labels: S-waiting-on-bors

#62749 Document link_section arbitrary bytes
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#62752 Disable Z3 in LLVM build
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#62761 Test case for #62506 to make sure we don't regress.
  src/test/ui/generator/issue-62506-two_awaits.rs
Labels: S-waiting-on-review

#62774 Disable simd_select_bitmask test on big endian
  src/test/run-pass/simd/simd-intrinsic-generic-select.rs
Labels: S-waiting-on-bors

#62778 Emit artifact notifications for dependency files
  src/librustc_interface/passes.rs
Labels: S-waiting-on-bors

#62694 rustc_typeck: improve diagnostics for -> _ fn return type
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/collect.rs
  src/test/ui/error-codes/E0121.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.stderr
  src/test/ui/typeck/typeck_type_placeholder_item_help.rs
  src/test/ui/typeck/typeck_type_placeholder_item_help.stderr
Labels: S-waiting-on-bors, merged-by-bors

#62679 Add an `after_expansion` callback in the driver
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#62690 azure: Prepare configuration for 4-core machines
  .azure-pipelines/steps/install-windows-build-deps.yml
  .azure-pipelines/steps/run.yml
  Cargo.lock
  src/ci/docker/run.sh
  src/ci/run.sh
Labels: S-waiting-on-bors, merged-by-bors

#62710 Specific error for positional args after named args in `format!()`
  src/libsyntax_ext/format.rs
  src/test/ui/if/ifmt-bad-arg.rs
  src/test/ui/if/ifmt-bad-arg.stderr
  src/test/ui/macros/format-parse-errors.rs
  src/test/ui/macros/format-parse-errors.stderr
Labels: S-waiting-on-bors, merged-by-bors

#62789 Update pulldown-cmark version
  Cargo.lock
  src/librustdoc/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors
