Repository rust-lang/rust, pull requests merged in 2019-02, with the labels that each got.

#58002 Add suggestions to deprecation lints
  src/libcore/lib.rs
  src/libcore/sync/atomic.rs
  src/librustc/ich/impls_syntax.rs
  src/librustc/middle/stability.rs
  src/libsyntax/attr/builtin.rs
  src/test/ui/deprecation/atomic_initializers.fixed
  src/test/ui/deprecation/atomic_initializers.rs
  src/test/ui/deprecation/atomic_initializers.stderr
Labels: S-waiting-on-bors

#58040 Fix grammar in E0283 explanation
  src/librustc/diagnostics.rs
Labels: S-waiting-on-bors

#58049 Fix typo
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors

#57978 Fix bug in integer range matching
  src/librustc_mir/build/matches/simplify.rs
  src/test/ui/match-on-negative-integer-ranges.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#58060 targets: aarch64-unknown-none: Add +strict-align
  src/librustc_target/spec/aarch64_unknown_none.rs
Labels: S-waiting-on-bors

#58048 Stabilize std::error::Error::type_id
  src/libstd/error.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#58047 Stabilize split_ascii_whitespace
  src/liballoc/lib.rs
  src/liballoc/str.rs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#58079 hir: add HirId to main Hir nodes
  src/librustc/hir/check_attr.rs
  src/librustc/hir/intravisit.rs
  src/librustc/hir/lowering.rs
  src/librustc/hir/map/mod.rs
  src/librustc/hir/mod.rs
  src/librustc/hir/pat_util.rs
  src/librustc/hir/print.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/middle/liveness.rs
  src/librustc/traits/error_reporting.rs
  src/librustc_borrowck/borrowck/gather_loans/gather_moves.rs
  src/librustc_lint/builtin.rs
  src/librustc_lint/nonstandard_style.rs
  src/librustc_metadata/encoder.rs
  src/librustc_mir/borrow_check/mutability_errors.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/hair/pattern/check_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_typeck/check/_match.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/collect.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors

#58062 Rename iter::unfold to iter::from_fn and remove explicit state
  src/libcore/iter/mod.rs
  src/libcore/iter/sources.rs
Labels: S-waiting-on-bors

#57922 Update visibility of intermediate use items.
  src/libcore/iter/adapters/mod.rs
  src/libcore/iter/traits/mod.rs
  src/librustc/hir/def.rs
  src/librustc/middle/privacy.rs
  src/librustc_privacy/lib.rs
  src/libstd/sys/mod.rs
  src/test/ui/issues/issue-57410-1.rs
  src/test/ui/issues/issue-57410.rs
Labels: S-waiting-on-bors

#58081 Transition liballoc to Rust 2018
  src/liballoc/alloc.rs
  src/liballoc/benches/btree/map.rs
  src/liballoc/benches/slice.rs
  src/liballoc/borrow.rs
  src/liballoc/boxed.rs
  src/liballoc/boxed_test.rs
  src/liballoc/collections/binary_heap.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/node.rs
  src/liballoc/collections/btree/search.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/collections/linked_list.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/fmt.rs
  src/liballoc/prelude.rs
  src/liballoc/raw_vec.rs
  src/liballoc/rc.rs
  src/liballoc/slice.rs
  src/liballoc/str.rs
  src/liballoc/string.rs
  src/liballoc/sync.rs
  src/liballoc/task.rs
  src/liballoc/tests/arc.rs
  src/liballoc/tests/binary_heap.rs
  src/liballoc/tests/btree/map.rs
  src/liballoc/tests/btree/set.rs
  src/liballoc/tests/lib.rs
  src/liballoc/tests/rc.rs
  src/liballoc/tests/slice.rs
  src/liballoc/tests/str.rs
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#58095 Transition cargotest to Rust 2018
  src/tools/cargotest/Cargo.toml
  src/tools/cargotest/main.rs
Labels: S-waiting-on-bors

#57973 Add suggestion for duplicated import.
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/resolve_imports.rs
  src/libsyntax/ast.rs
  src/test/ui/double-type-import.stderr
  src/test/ui/error-codes/E0430.stderr
  src/test/ui/imports/duplicate.stderr
  src/test/ui/issues/auxiliary/issue-52891.rs
  src/test/ui/issues/issue-26886.stderr
  src/test/ui/issues/issue-45829/import-twice.stderr
  src/test/ui/issues/issue-52891.fixed
  src/test/ui/issues/issue-52891.rs
  src/test/ui/issues/issue-52891.stderr
  src/test/ui/proc-macro/shadow.stderr
  src/test/ui/resolve/resolve-conflict-import-vs-import.stderr
  src/test/ui/unresolved/unresolved-extern-mod-suggestion.stderr
  src/test/ui/use/use-mod.stderr
  src/test/ui/use/use-paths-as-items.stderr
Labels: S-waiting-on-bors

#58001 proc_macro: make `TokenStream::from_streams` pre-allocate its vector.
  src/libsyntax/tokenstream.rs
Labels: S-waiting-on-bors, T-compiler

#58096 Transition linkchecker to 2018 edition
  src/tools/linkchecker/Cargo.toml
  src/tools/linkchecker/main.rs
Labels: S-waiting-on-bors

#58106 libfmt_macros => 2018
  src/libfmt_macros/Cargo.toml
  src/libfmt_macros/lib.rs
Labels: S-waiting-on-bors

#58107 libgraphviz => 2018
  src/libgraphviz/Cargo.toml
  src/libgraphviz/lib.rs
Labels: S-waiting-on-bors

#58108 Add NVPTX target to a build manifest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#58109 librustc_privacy => 2018
  src/librustc_privacy/Cargo.toml
  src/librustc_privacy/lib.rs
Labels: S-waiting-on-bors

#58112 libpanic_abort => 2018
  src/libpanic_abort/Cargo.toml
  src/libpanic_abort/lib.rs
Labels: S-waiting-on-bors

#58114 Transition tidy and unstable-book-gen to 2018 edition
  src/tools/tidy/src/main.rs
  src/tools/tidy/src/unstable_book.rs
  src/tools/unstable-book-gen/Cargo.toml
  src/tools/unstable-book-gen/src/main.rs
Labels: S-waiting-on-bors

#58116 Include the span of attributes of the lhs to the span of the assignment expression
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors

#58117 Transition rustdoc-theme to 2018 edition
  src/tools/rustdoc-themes/Cargo.toml
  src/tools/rustdoc-themes/main.rs
Labels: S-waiting-on-bors

#58128 libunwind => 2018
  src/libunwind/Cargo.toml
  src/libunwind/lib.rs
  src/libunwind/libunwind.rs
Labels: S-waiting-on-bors

#58139 hir: add more HirId methods
  src/librustc/hir/map/mod.rs
Labels: S-waiting-on-bors

#58141 Remove weasel word in docs for iter's take_while()
  src/libcore/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#58142 Remove stray FIXME
  src/libstd/sys/sgx/rwlock.rs
Labels: S-waiting-on-bors

#58145 Add #[must_use] to core::task::Poll
  src/libcore/task/poll.rs
Labels: S-waiting-on-bors

#58169 Update contributor name in .mailmap
  .mailmap
Labels: S-waiting-on-bors

#58172 update split docs
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#58186 Add Rustlings to the doc index
  src/doc/index.md
Labels: S-waiting-on-bors

#57851 Don't try to clean predicates involving ReErased
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors

#58058 rustdoc: don't try to get a DefId for a Def that doesn't have one
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/visit_ast.rs
  src/test/rustdoc/use-attr.rs
Labels: S-waiting-on-bors

#56123 Add a forever unstable opt-out of const qualification checks
  src/librustc/session/config.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/test/ui/consts/miri_unleashed/assoc_const.rs
  src/test/ui/consts/miri_unleashed/assoc_const.stderr
  src/test/ui/consts/miri_unleashed/assoc_const_2.rs
  src/test/ui/consts/miri_unleashed/assoc_const_2.stderr
  src/test/ui/consts/miri_unleashed/feature-gate-unleash_the_miri_inside_of_you.rs
  src/test/ui/consts/miri_unleashed/feature-gate-unleash_the_miri_inside_of_you.stderr
Labels: S-waiting-on-bors, T-compiler

#58125 libsyntax => 2018
  src/libsyntax/Cargo.toml
  src/libsyntax/ast.rs
  src/libsyntax/attr/builtin.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/config.rs
  src/libsyntax/diagnostics/metadata.rs
  src/libsyntax/diagnostics/plugin.rs
  src/libsyntax/early_buffered_lints.rs
  src/libsyntax/entry.rs
  src/libsyntax/ext/base.rs
  src/libsyntax/ext/build.rs
  src/libsyntax/ext/derive.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/placeholders.rs
  src/libsyntax/ext/source_util.rs
  src/libsyntax/ext/tt/macro_parser.rs
  src/libsyntax/ext/tt/macro_rules.rs
  src/libsyntax/ext/tt/quoted.rs
  src/libsyntax/ext/tt/transcribe.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/json.rs
  src/libsyntax/lib.rs
  src/libsyntax/mut_visit.rs
  src/libsyntax/parse/attr.rs
  src/libsyntax/parse/classify.rs
  src/libsyntax/parse/lexer/comments.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/lexer/tokentrees.rs
  src/libsyntax/parse/lexer/unicode_chars.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/token.rs
  src/libsyntax/print/pp.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/ptr.rs
  src/libsyntax/show_span.rs
  src/libsyntax/source_map.rs
  src/libsyntax/std_inject.rs
  src/libsyntax/test.rs
  src/libsyntax/test_snippet.rs
  src/libsyntax/tokenstream.rs
  src/libsyntax/util/lev_distance.rs
  src/libsyntax/util/node_count.rs
  src/libsyntax/util/parser.rs
  src/libsyntax/util/parser_testing.rs
  src/libsyntax/visit.rs
Labels: S-waiting-on-bors

#58119 libproc_macro => 2018
  src/libproc_macro/Cargo.toml
  src/libproc_macro/bridge/buffer.rs
  src/libproc_macro/bridge/client.rs
  src/libproc_macro/bridge/mod.rs
  src/libproc_macro/bridge/rpc.rs
  src/libproc_macro/bridge/server.rs
  src/libproc_macro/diagnostic.rs
  src/libproc_macro/lib.rs
  src/libproc_macro/quote.rs
Labels: S-waiting-on-bors

#58123 Avoid some bounds checks in binary_heap::{PeekMut,Hole}
  src/liballoc/collections/binary_heap.rs
Labels: S-waiting-on-bors

#58124 libsyntax_pos => 2018
  src/libsyntax_pos/Cargo.toml
  src/libsyntax_pos/analyze_source_file.rs
  src/libsyntax_pos/edition.rs
  src/libsyntax_pos/hygiene.rs
  src/libsyntax_pos/lib.rs
  src/libsyntax_pos/span_encoding.rs
  src/libsyntax_pos/symbol.rs
Labels: S-waiting-on-bors

#58133 libsyntax_ext => 2018
  src/libsyntax_ext/Cargo.toml
  src/libsyntax_ext/asm.rs
  src/libsyntax_ext/assert.rs
  src/libsyntax_ext/cfg.rs
  src/libsyntax_ext/compile_error.rs
  src/libsyntax_ext/concat.rs
  src/libsyntax_ext/concat_idents.rs
  src/libsyntax_ext/deriving/bounds.rs
  src/libsyntax_ext/deriving/clone.rs
  src/libsyntax_ext/deriving/cmp/eq.rs
  src/libsyntax_ext/deriving/cmp/ord.rs
  src/libsyntax_ext/deriving/cmp/partial_eq.rs
  src/libsyntax_ext/deriving/cmp/partial_ord.rs
  src/libsyntax_ext/deriving/custom.rs
  src/libsyntax_ext/deriving/debug.rs
  src/libsyntax_ext/deriving/decodable.rs
  src/libsyntax_ext/deriving/default.rs
  src/libsyntax_ext/deriving/encodable.rs
  src/libsyntax_ext/deriving/generic/mod.rs
  src/libsyntax_ext/deriving/generic/ty.rs
  src/libsyntax_ext/deriving/hash.rs
  src/libsyntax_ext/deriving/mod.rs
  src/libsyntax_ext/diagnostics.rs
  src/libsyntax_ext/env.rs
  src/libsyntax_ext/format.rs
  src/libsyntax_ext/format_foreign.rs
  src/libsyntax_ext/global_asm.rs
  src/libsyntax_ext/lib.rs
  src/libsyntax_ext/log_syntax.rs
  src/libsyntax_ext/proc_macro_decls.rs
  src/libsyntax_ext/proc_macro_impl.rs
  src/libsyntax_ext/proc_macro_server.rs
  src/libsyntax_ext/test.rs
  src/libsyntax_ext/test_case.rs
  src/libsyntax_ext/trace_macros.rs
Labels: S-waiting-on-bors

#58136 Improve error message and docs for non-UTF-8 bytes in stdio on Windows
  src/libstd/io/stdio.rs
  src/libstd/sys/windows/stdio.rs
Labels: S-waiting-on-bors

#58192 Do not ICE in codegen when using a extern_type static
  src/librustc_codegen_ssa/mir/place.rs
  src/test/run-make-fulldeps/static-extern-type/Makefile
  src/test/run-make-fulldeps/static-extern-type/define-foo.c
  src/test/run-make-fulldeps/static-extern-type/use-foo.rs
Labels: S-waiting-on-bors

#58210 Make an assert debug-only in `find_constraint_paths_between_regions`.
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/mod.rs
Labels: S-waiting-on-bors

#58217 librustc_tsan => 2018
  src/librustc_tsan/Cargo.toml
  src/librustc_tsan/build.rs
  src/librustc_tsan/lib.rs
Labels: S-waiting-on-bors

#58218 librustc_msan => 2018
  src/librustc_msan/Cargo.toml
  src/librustc_msan/build.rs
  src/librustc_msan/lib.rs
Labels: S-waiting-on-bors

#58219 librustc_asan => 2018
  src/librustc_asan/Cargo.toml
  src/librustc_asan/build.rs
  src/librustc_asan/lib.rs
Labels: S-waiting-on-bors

#58220 libprofiler_builtins => 2018
  src/libprofiler_builtins/Cargo.toml
  src/libprofiler_builtins/build.rs
  src/libprofiler_builtins/lib.rs
Labels: S-waiting-on-bors

#58223 librustc_lsan => 2018
  src/librustc_lsan/Cargo.toml
  src/librustc_lsan/build.rs
  src/librustc_lsan/lib.rs
Labels: S-waiting-on-bors

#58225 librustc_fs_util => 2018
  src/librustc_fs_util/Cargo.toml
  src/librustc_fs_util/lib.rs
Labels: S-waiting-on-bors

#58228 librustc_plugin => 2018
  src/librustc_plugin/Cargo.toml
  src/librustc_plugin/diagnostics.rs
  src/librustc_plugin/lib.rs
  src/librustc_plugin/load.rs
Labels: S-waiting-on-bors

#58236 librustc_resolve => 2018
  src/librustc_resolve/Cargo.toml
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/check_unused.rs
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/error_reporting.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/librustc_resolve/resolve_imports.rs
Labels: S-waiting-on-bors

#58237 Fix broken grammar in iter::from_fn() docs
  src/libcore/iter/sources.rs
Labels: S-waiting-on-bors

#58239 librustc_apfloat => 2018
  src/librustc_apfloat/Cargo.toml
  src/librustc_apfloat/ieee.rs
  src/librustc_apfloat/lib.rs
  src/librustc_apfloat/ppc.rs
  src/librustc_apfloat/tests/ieee.rs
  src/librustc_apfloat/tests/ppc.rs
Labels: S-waiting-on-bors

#58240 librustc_errors => 2018
  src/librustc_errors/Cargo.toml
  src/librustc_errors/diagnostic.rs
  src/librustc_errors/diagnostic_builder.rs
  src/librustc_errors/emitter.rs
  src/librustc_errors/lib.rs
  src/librustc_errors/snippet.rs
  src/librustc_errors/styled_buffer.rs
Labels: S-waiting-on-bors

#58241 librustc_llvm => 2018
  src/librustc_llvm/Cargo.toml
  src/librustc_llvm/build.rs
  src/librustc_llvm/lib.rs
Labels: S-waiting-on-bors

#58242 Document the one TyKind that isn't documented
  src/librustc/ty/sty.rs
Labels: S-waiting-on-bors

#58010 Move privacy checking later in the pipeline and make some passes run in parallel
  src/librustc/hir/mod.rs
  src/librustc/middle/liveness.rs
  src/librustc/session/mod.rs
  src/librustc_data_structures/sync.rs
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
  src/librustc_passes/rvalue_promotion.rs
  src/test/ui/error-codes/E0446.rs
  src/test/ui/error-codes/E0446.stderr
  src/test/ui/error-codes/E0451.rs
  src/test/ui/error-codes/E0451.stderr
  src/test/ui/functional-struct-update/functional-struct-update-respects-privacy.rs
  src/test/ui/privacy/private-in-public-warn.rs
  src/test/ui/privacy/private-in-public-warn.stderr
  src/test/ui/privacy/private-inferred-type.rs
Labels: S-waiting-on-bors

#57504 Re-enable history api on file:// protocol
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, T-rustdoc

#57884 Update minifier version
  Cargo.lock
  src/librustdoc/Cargo.toml
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#57954 rustdoc: remove blank unstable spans
  src/librustdoc/html/render.rs
  src/test/rustdoc/stability.rs
Labels: S-waiting-on-bors

#58028 Fix image link in the settings menu
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render.rs
  src/test/rustdoc/keyword.rs
Labels: S-waiting-on-bors

#58033 rustdoc: wrap stability tags in colored spans
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/rustdoc.css
  src/test/rustdoc/deprecated.rs
  src/test/rustdoc/inline_cross/macros.rs
  src/test/rustdoc/internal.rs
  src/test/rustdoc/issue-32374.rs
Labels: S-waiting-on-bors

#58086 [rustdoc] Improve file list display
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/source-script.js
Labels: S-waiting-on-bors

#58143 Sort elements in the sidebar
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#58146 Prevent automatic collapse of methods impl blocks
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#58150 Don't apply impl block collapse rules to trait impls
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#58185 Remove images' url to make it work even without internet connection
  src/liballoc/lib.rs
  src/libarena/lib.rs
  src/libcore/lib.rs
  src/libfmt_macros/lib.rs
  src/libgraphviz/lib.rs
  src/libpanic_abort/lib.rs
  src/libpanic_unwind/lib.rs
  src/libproc_macro/lib.rs
  src/librustc/lib.rs
  src/librustc_apfloat/lib.rs
  src/librustc_borrowck/lib.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/lib.rs
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_codegen_utils/lib.rs
  src/librustc_data_structures/lib.rs
  src/librustc_driver/lib.rs
  src/librustc_errors/lib.rs
  src/librustc_incremental/lib.rs
  src/librustc_lint/lib.rs
  src/librustc_llvm/lib.rs
  src/librustc_metadata/lib.rs
  src/librustc_passes/lib.rs
  src/librustc_plugin/lib.rs
  src/librustc_privacy/lib.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_target/lib.rs
  src/librustc_typeck/lib.rs
  src/librustdoc/lib.rs
  src/libserialize/lib.rs
  src/libstd/lib.rs
  src/libsyntax/lib.rs
  src/libsyntax_ext/lib.rs
  src/libsyntax_pos/lib.rs
  src/libterm/lib.rs
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#58213 Add embedded book to test such that checktools works
  src/bootstrap/test.rs
Labels: S-waiting-on-bors, merged-by-bors

#58294 fix rustdoc JS
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, merged-by-bors

#58161 Lower constant patterns with ascribed types.
  src/librustc_mir/hair/pattern/mod.rs
  src/test/ui/nll/issue-57960.rs
Labels: I-nominated, S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#58091 Transition compiletest to Rust 2018
  src/tools/compiletest/Cargo.toml
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/errors.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/json.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/read2.rs
  src/tools/compiletest/src/runtest.rs
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors

#58115 Transition rustdoc to 2018 edition
  src/tools/rustdoc/Cargo.toml
  src/tools/rustdoc/main.rs
Labels: S-waiting-on-bors

#58120 Transition build_helper to 2018 edition
  src/build_helper/Cargo.toml
  src/build_helper/lib.rs
Labels: S-waiting-on-bors

#58222 librustc_allocator => 2018
  src/librustc_allocator/Cargo.toml
  src/librustc_allocator/expand.rs
  src/librustc_allocator/lib.rs
Labels: S-waiting-on-bors

#58233 librustc_save_analysis => 2018
  src/librustc_save_analysis/Cargo.toml
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/json_dumper.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/sig.rs
  src/librustc_save_analysis/span_utils.rs
Labels: S-waiting-on-bors

#58245 librustc_lint => 2018
  src/librustc_lint/Cargo.toml
  src/librustc_lint/builtin.rs
  src/librustc_lint/diagnostics.rs
  src/librustc_lint/lib.rs
  src/librustc_lint/nonstandard_style.rs
  src/librustc_lint/types.rs
  src/librustc_lint/unused.rs
Labels: S-waiting-on-bors

#58247 librustc_passes => 2018
  src/librustc_passes/Cargo.toml
  src/librustc_passes/ast_validation.rs
  src/librustc_passes/diagnostics.rs
  src/librustc_passes/hir_stats.rs
  src/librustc_passes/lib.rs
  src/librustc_passes/loops.rs
  src/librustc_passes/rvalue_promotion.rs
Labels: S-waiting-on-bors

#58251 Transition librustc_traits to 2018 edition
  src/librustc_traits/Cargo.toml
  src/librustc_traits/chalk_context/mod.rs
  src/librustc_traits/chalk_context/program_clauses.rs
  src/librustc_traits/dropck_outlives.rs
  src/librustc_traits/evaluate_obligation.rs
  src/librustc_traits/implied_outlives_bounds.rs
  src/librustc_traits/lib.rs
  src/librustc_traits/lowering/mod.rs
  src/librustc_traits/normalize_erasing_regions.rs
  src/librustc_traits/normalize_projection_ty.rs
  src/librustc_traits/type_op.rs
Labels: S-waiting-on-bors

#58255 librustc_metadata => 2018
  src/librustc_metadata/Cargo.toml
  src/librustc_metadata/creader.rs
  src/librustc_metadata/cstore.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_metadata/decoder.rs
  src/librustc_metadata/diagnostics.rs
  src/librustc_metadata/dynamic_lib.rs
  src/librustc_metadata/encoder.rs
  src/librustc_metadata/index.rs
  src/librustc_metadata/index_builder.rs
  src/librustc_metadata/isolated_encoder.rs
  src/librustc_metadata/lib.rs
  src/librustc_metadata/locator.rs
  src/librustc_metadata/native_libs.rs
  src/librustc_metadata/schema.rs
Labels: S-waiting-on-bors

#58256 librustc_cratesio_shim => 2018
  src/librustc_cratesio_shim/Cargo.toml
  src/librustc_cratesio_shim/src/lib.rs
Labels: S-waiting-on-bors

#58259 librustc_codegen_utils => 2018
  src/librustc_codegen_utils/Cargo.toml
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_codegen_utils/lib.rs
  src/librustc_codegen_utils/link.rs
  src/librustc_codegen_utils/symbol_names.rs
Labels: S-waiting-on-bors

#58260 librustc_borrowck => 2018
  src/librustc_borrowck/Cargo.toml
  src/librustc_borrowck/borrowck/check_loans.rs
  src/librustc_borrowck/borrowck/gather_loans/gather_moves.rs
  src/librustc_borrowck/borrowck/gather_loans/lifetime.rs
  src/librustc_borrowck/borrowck/gather_loans/mod.rs
  src/librustc_borrowck/borrowck/gather_loans/move_error.rs
  src/librustc_borrowck/borrowck/gather_loans/restrictions.rs
  src/librustc_borrowck/borrowck/mod.rs
  src/librustc_borrowck/borrowck/move_data.rs
  src/librustc_borrowck/borrowck/unused.rs
  src/librustc_borrowck/dataflow.rs
  src/librustc_borrowck/graphviz.rs
  src/librustc_borrowck/lib.rs
Labels: S-waiting-on-bors

#58261 librustc_incremental => 2018
  src/librustc_incremental/Cargo.toml
  src/librustc_incremental/assert_dep_graph.rs
  src/librustc_incremental/lib.rs
  src/librustc_incremental/persist/dirty_clean.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_incremental/persist/mod.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_incremental/persist/work_product.rs
Labels: S-waiting-on-bors

#58275 libcore, liballoc: disable tests in Miri
  src/liballoc/tests/arc.rs
  src/liballoc/tests/binary_heap.rs
  src/liballoc/tests/btree/mod.rs
  src/liballoc/tests/heap.rs
  src/liballoc/tests/rc.rs
  src/liballoc/tests/slice.rs
  src/liballoc/tests/str.rs
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/libcore/tests/cell.rs
  src/libcore/tests/fmt/mod.rs
  src/libcore/tests/hash/mod.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/num/mod.rs
  src/libcore/tests/option.rs
  src/libcore/tests/ptr.rs
  src/libcore/tests/result.rs
  src/libcore/tests/slice.rs
  src/libcore/tests/time.rs
Labels: S-waiting-on-bors

#58285 error_index_generator => 2018
  src/tools/error_index_generator/Cargo.toml
  src/tools/error_index_generator/main.rs
Labels: S-waiting-on-bors

#58312 librustc_data_structures => 2018
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/bit_set.rs
  src/librustc_data_structures/fingerprint.rs
  src/librustc_data_structures/flock.rs
  src/librustc_data_structures/graph/dominators/mod.rs
  src/librustc_data_structures/graph/implementation/mod.rs
  src/librustc_data_structures/graph/implementation/tests.rs
  src/librustc_data_structures/graph/scc/mod.rs
  src/librustc_data_structures/graph/scc/test.rs
  src/librustc_data_structures/graph/test.rs
  src/librustc_data_structures/indexed_vec.rs
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/obligation_forest/graphviz.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_data_structures/owning_ref/mod.rs
  src/librustc_data_structures/ptr_key.rs
  src/librustc_data_structures/snapshot_map/mod.rs
  src/librustc_data_structures/sorted_map.rs
  src/librustc_data_structures/stable_hasher.rs
  src/librustc_data_structures/svh.rs
  src/librustc_data_structures/sync.rs
  src/librustc_data_structures/tiny_list.rs
  src/librustc_data_structures/transitive_relation.rs
  src/librustc_data_structures/vec_linked_list.rs
  src/librustc_data_structures/work_queue.rs
Labels: S-waiting-on-bors

#57184 Deny warnings in libcore and libstd
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors, merged-by-bors

#58207 Make `intern_lazy_const` actually intern its argument.
  src/librustc/mir/mod.rs
  src/librustc/traits/project.rs
  src/librustc/traits/query/normalize.rs
  src/librustc/ty/codec.rs
  src/librustc/ty/context.rs
  src/librustc/ty/structural_impls.rs
  src/librustc_mir/build/expr/as_rvalue.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/build/misc.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_mir/hair/cx/mod.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#58065 Factor out error reporting from `smart_resolve_path_fragment` fn
  src/librustc_resolve/error_reporting.rs
  src/librustc_resolve/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#58339 Add EmbeddedBook to test list in bootstrap
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors, merged-by-bors

#58151 Partially HirId-ify rustc
  src/librustc/infer/error_reporting/mod.rs
  src/librustc/infer/error_reporting/note.rs
  src/librustc/middle/reachable.rs
  src/librustc/middle/resolve_lifetime.rs
  src/librustc/traits/error_reporting.rs
  src/librustc/traits/util.rs
  src/librustc/ty/item_path.rs
  src/librustc/ty/mod.rs
  src/librustc/util/ppaux.rs
Labels: S-waiting-on-bors, merged-by-bors

#57740 Use `to_ne_bytes` for converting IPv4Addr to octets
  src/libstd/net/ip.rs
Labels: S-waiting-on-bors, T-libs

#57926 Tiny expansion to docs for `core::convert`.
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#58157 Add Cargo.lock automatically adding message
  Cargo.lock
Labels: S-waiting-on-bors

#58203 rustdoc: display sugared return types for async functions
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render.rs
  src/test/rustdoc/async-fn.rs
Labels: S-waiting-on-bors

#58262 Add #[must_use] message to Fn* traits
  src/libcore/ops/function.rs
Labels: S-waiting-on-bors

#58295 std::sys::unix::stdio: explain why we do into_raw
  src/libstd/sys/unix/stdio.rs
Labels: S-waiting-on-bors

#58297 Cleanup JS a bit
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#58317 Some writing improvement, conciseness of intro
  src/doc/rustdoc/src/unstable-features.md
Labels: S-waiting-on-bors

#58324 miri: give non-generic functions a stable address
  src/librustc/mir/interpret/mod.rs
Labels: S-waiting-on-bors

#58332 operand-to-place copies should never be overlapping
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#58345 When there are multiple filenames, print what got interpreted as filenames
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#58346 rpath computation: explain why we pop()
  src/librustc_codegen_llvm/back/rpath.rs
Labels: S-waiting-on-bors

#58352 miri value visitor: use `?` in macro
  src/librustc_mir/interpret/visitor.rs
Labels: S-waiting-on-bors

#58152 Partially HirIdify mir
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/borrow_check/move_errors.rs
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/var_name.rs
  src/librustc_mir/borrow_check/nll/universal_regions.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/hair/cx/block.rs
  src/librustc_mir/monomorphize/collector.rs
Labels: S-waiting-on-bors, merged-by-bors

#58153 Partially Hiridify typeck
  src/librustc/hir/map/mod.rs
  src/librustc_metadata/encoder.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/check/dropck.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/upvar.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/check/writeback.rs
  src/librustc_typeck/coherence/builtin.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/variance/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#58180 Fix span for closure return type when annotated.
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/test/ui/nll/issue-58053.rs
  src/test/ui/nll/issue-58053.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58105 libarena => 2018
  src/libarena/Cargo.toml
  src/libarena/lib.rs
Labels: S-waiting-on-bors

#58111 libterm => 2018
  src/libterm/Cargo.toml
  src/libterm/lib.rs
  src/libterm/terminfo/mod.rs
  src/libterm/terminfo/parm.rs
  src/libterm/terminfo/parser/compiled.rs
  src/libterm/win.rs
Labels: S-waiting-on-bors

#58287 rustc-std-workspace-core => 2018
  src/tools/rustc-std-workspace-core/Cargo.toml
  src/tools/rustc-std-workspace-core/lib.rs
Labels: S-waiting-on-bors

#58288 rustc-workspace-hack => 2018
  src/tools/rustc-workspace-hack/Cargo.toml
Labels: S-waiting-on-bors

#58300 librustc_typeck => 2018
  src/librustc_typeck/Cargo.toml
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/_match.rs
  src/librustc_typeck/check/cast.rs
  src/librustc_typeck/check/closure.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/dropck.rs
  src/librustc_typeck/check/generator_interior.rs
  src/librustc_typeck/check/intrinsic.rs
  src/librustc_typeck/check/method/confirm.rs
  src/librustc_typeck/check/method/mod.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/regionck.rs
  src/librustc_typeck/check/upvar.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/check/writeback.rs
  src/librustc_typeck/check_unused.rs
  src/librustc_typeck/coherence/inherent_impls_overlap.rs
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/constrained_type_params.rs
  src/librustc_typeck/impl_wf_check.rs
  src/librustc_typeck/lib.rs
  src/librustc_typeck/outlives/explicit.rs
  src/librustc_typeck/outlives/implicit_infer.rs
  src/librustc_typeck/outlives/mod.rs
  src/librustc_typeck/variance/terms.rs
Labels: S-waiting-on-bors

#58313 Use `?` in librustc macros
  src/librustc/macros.rs
  src/librustc/mir/visit.rs
Labels: S-waiting-on-bors

#58322 librustc_codegen_ssa => 2018
  src/librustc_codegen_ssa/Cargo.toml
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/lto.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_codegen_ssa/callee.rs
  src/librustc_codegen_ssa/common.rs
  src/librustc_codegen_ssa/glue.rs
  src/librustc_codegen_ssa/lib.rs
  src/librustc_codegen_ssa/meth.rs
  src/librustc_codegen_ssa/mir/analyze.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_codegen_ssa/mir/mod.rs
  src/librustc_codegen_ssa/mir/operand.rs
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_codegen_ssa/mir/statement.rs
  src/librustc_codegen_ssa/mono_item.rs
  src/librustc_codegen_ssa/traits/asm.rs
  src/librustc_codegen_ssa/traits/builder.rs
  src/librustc_codegen_ssa/traits/consts.rs
  src/librustc_codegen_ssa/traits/debuginfo.rs
  src/librustc_codegen_ssa/traits/intrinsic.rs
  src/librustc_codegen_ssa/traits/type_.rs
  src/librustc_codegen_ssa/traits/write.rs
Labels: S-waiting-on-bors

#58342 Revert removed #![feature(nll)]
  src/libfmt_macros/lib.rs
  src/libgraphviz/lib.rs
  src/libpanic_abort/lib.rs
  src/libproc_macro/lib.rs
  src/libprofiler_builtins/lib.rs
  src/librustc_allocator/lib.rs
  src/librustc_apfloat/lib.rs
  src/librustc_asan/lib.rs
  src/librustc_errors/lib.rs
  src/librustc_llvm/lib.rs
  src/librustc_lsan/lib.rs
  src/librustc_msan/lib.rs
  src/librustc_plugin/lib.rs
  src/librustc_privacy/lib.rs
  src/librustc_resolve/lib.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_tsan/lib.rs
  src/libsyntax/lib.rs
  src/libsyntax_ext/lib.rs
  src/libsyntax_pos/lib.rs
  src/libunwind/lib.rs
Labels: S-waiting-on-bors

#58367 Remove two dead functions.
  src/librustc/infer/mod.rs
  src/librustc/ty/fold.rs
Labels: S-waiting-on-bors

#58382 docs: remove "experimental" wording from std::os::unix
  src/libstd/sys/unix/ext/mod.rs
Labels: S-waiting-on-bors

#57388 use ignore directives for run-make tests
  src/test/run-make-fulldeps/c-dynamic-dylib/Makefile
  src/test/run-make-fulldeps/c-dynamic-rlib/Makefile
  src/test/run-make-fulldeps/c-link-to-rust-staticlib/Makefile
  src/test/run-make-fulldeps/cdylib-fewer-symbols/Makefile
  src/test/run-make-fulldeps/compiler-rt-works-on-mingw/Makefile
  src/test/run-make-fulldeps/dep-info-spaces/Makefile
  src/test/run-make-fulldeps/dep-info/Makefile
  src/test/run-make-fulldeps/emit-stack-sizes/Makefile
  src/test/run-make-fulldeps/fpic/Makefile
  src/test/run-make-fulldeps/include_bytes_deps/Makefile
  src/test/run-make-fulldeps/intrinsic-unreachable/Makefile
  src/test/run-make-fulldeps/issue-24445/Makefile
  src/test/run-make-fulldeps/issue-26006/Makefile
  src/test/run-make-fulldeps/issue-36710/Makefile
  src/test/run-make-fulldeps/issue-37839/Makefile
  src/test/run-make-fulldeps/issue-37893/Makefile
  src/test/run-make-fulldeps/issue-51671/Makefile
  src/test/run-make-fulldeps/libs-search-path/Makefile
  src/test/run-make-fulldeps/libs-through-symlinks/Makefile
  src/test/run-make-fulldeps/linker-output-non-utf8/Makefile
  src/test/run-make-fulldeps/min-global-align/Makefile
  src/test/run-make-fulldeps/no-integrated-as/Makefile
  src/test/run-make-fulldeps/pgo-gen-lto/Makefile
  src/test/run-make-fulldeps/pgo-gen/Makefile
  src/test/run-make-fulldeps/prune-link-args/Makefile
  src/test/run-make-fulldeps/relro-levels/Makefile
  src/test/run-make-fulldeps/rustdoc-io-error/Makefile
  src/test/run-make-fulldeps/sanitizer-leak/Makefile
  src/test/run-make-fulldeps/sanitizer-memory/Makefile
  src/test/run-make-fulldeps/symbol-visibility/Makefile
  src/test/run-make-fulldeps/symlinked-extern/Makefile
  src/test/run-make-fulldeps/symlinked-libraries/Makefile
  src/test/run-make-fulldeps/symlinked-rlib/Makefile
  src/test/run-make-fulldeps/target-cpu-native/Makefile
  src/test/run-make-fulldeps/use-extern-for-plugins/Makefile
  src/test/run-make-fulldeps/used/Makefile
  src/test/run-make-fulldeps/windows-spawn/Makefile
  src/test/run-make/thumb-none-cortex-m/Makefile
  src/test/run-make/thumb-none-qemu/Makefile
  src/test/run-make/wasm-custom-section/Makefile
  src/test/run-make/wasm-custom-sections-opt/Makefile
  src/test/run-make/wasm-export-all-symbols/Makefile
  src/test/run-make/wasm-import-module/Makefile
  src/test/run-make/wasm-panic-small/Makefile
  src/test/run-make/wasm-symbols-not-exported/Makefile
  src/test/run-make/wasm-symbols-not-imported/Makefile
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors, merged-by-bors

#57693 Doc rewording
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#57815 Speed up the fast path for assert_eq! and assert_ne!
  src/libcore/macros.rs
Labels: S-waiting-on-bors

#58034 Stabilize the time_checked_add feature
  src/libstd/time.rs
Labels: S-waiting-on-bors, T-libs, needs-fcp, relnotes

#58166 allow shorthand syntax for deprecation reason
  src/libsyntax/attr/builtin.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/feature_gate.rs
  src/test/rustdoc/deprecated.rs
  src/test/ui/deprecation/deprecation-sanity.rs
  src/test/ui/deprecation/deprecation-sanity.stderr
  src/test/ui/deprecation/invalid-literal.rs
  src/test/ui/deprecation/invalid-literal.stderr
Labels: S-waiting-on-bors, T-lang, relnotes

#58200 fix str mutating through a ptr derived from &self
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#58289 impl iter() for dyn Error
  src/libstd/error.rs
Labels: S-waiting-on-bors

#58404 use Ubuntu keyserver for CloudABI ports
  src/ci/docker/dist-various-2/build-cloudabi-toolchain.sh
Labels: S-waiting-on-bors

#58405 Remove some dead code from libcore
  src/libcore/lib.rs
Labels: S-waiting-on-bors

#58235 SGX target: simplify usercall internals
  src/libstd/lib.rs
  src/libstd/sys/sgx/abi/entry.S
  src/libstd/sys/sgx/abi/mod.rs
  src/libstd/sys/sgx/abi/panic.rs
  src/libstd/sys/sgx/abi/usercalls/mod.rs
  src/libstd/sys/sgx/abi/usercalls/raw.rs
  src/libstd/sys/sgx/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#58238 Fixes rustdoc in stage 0, stage 1
  src/bootstrap/builder.rs
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors, merged-by-bors

#56951 Automatically open an issue when a tool breaks
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors, T-compiler, T-dev-tools, T-infra, disposition-merge, finished-final-comment-period, merged-by-bors

#58167 HirId-ify hir::BodyId
  src/librustc/hir/map/mod.rs
  src/librustc/hir/mod.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/infer/error_reporting/need_type_info.rs
  src/librustc/infer/mod.rs
  src/librustc/infer/opaque_types/mod.rs
  src/librustc/infer/outlives/env.rs
  src/librustc/infer/outlives/obligations.rs
  src/librustc/traits/auto_trait.rs
  src/librustc/traits/mod.rs
  src/librustc/traits/query/outlives_bounds.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/wf.rs
  src/librustc_borrowck/borrowck/mod.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_privacy/lib.rs
  src/librustc_traits/implied_outlives_bounds.rs
  src/librustc_traits/normalize_projection_ty.rs
  src/librustc_traits/type_op.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/autoderef.rs
  src/librustc_typeck/check/closure.rs
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/check/dropck.rs
  src/librustc_typeck/check/intrinsic.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/regionck.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/check/writeback.rs
  src/librustc_typeck/coherence/builtin.rs
  src/librustc_typeck/lib.rs
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors

#58381 Only suggest imports if not imported.
  src/librustc_resolve/error_reporting.rs
  src/librustc_resolve/lib.rs
  src/test/ui/issue-42944.rs
  src/test/ui/issue-42944.stderr
  src/test/ui/resolve/privacy-struct-ctor.stderr
Labels: S-waiting-on-bors

#58386 Fix #54242
  src/librustc/ty/query/plumbing.rs
  src/test/incremental/issue-54242.rs
Labels: S-waiting-on-bors

#58400 Fix rustc_driver swallowing errors when compilation is stopped
  src/librustc_driver/driver.rs
Labels: S-waiting-on-bors

#58420 target/uefi: clarify documentation
  src/librustc_target/spec/uefi_base.rs
  src/librustc_target/spec/x86_64_unknown_uefi.rs
Labels: S-waiting-on-bors

#57451 suggestion-diagnostics: as_ref improve snippet
  src/librustc_typeck/check/demand.rs
  src/test/ui/suggestions/as-ref.stderr
Labels: S-waiting-on-bors

#57856 Convert old first edition links to current edition one
  src/doc/guide-error-handling.md
  src/doc/guide-ownership.md
  src/doc/guide-pointers.md
  src/doc/guide-testing.md
  src/libcore/convert.rs
  src/libcore/marker.rs
  src/libcore/mem.rs
  src/libproc_macro/lib.rs
  src/librustc/diagnostics.rs
  src/librustc_metadata/diagnostics.rs
  src/librustc_mir/diagnostics.rs
  src/librustc_typeck/diagnostics.rs
  src/librustc_typeck/structured_errors.rs
  src/libstd/prelude/mod.rs
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#58258 Reduce the size of `hir::Expr`.
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_typeck/check/demand.rs
Labels: S-waiting-on-bors

#58308 Extract block to insert an intrinsic into its own function
  src/librustc_codegen_llvm/context.rs
Labels: S-waiting-on-bors

#58365 Add an option to print the status of incremental tasks / dep nodes after running them
  src/librustc/dep_graph/graph.rs
  src/librustc/session/config.rs
Labels: S-waiting-on-bors

#58371 Check user type annotations for range patterns.
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/build/matches/simplify.rs
  src/librustc_mir/hair/cx/block.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/test/ui/nll/issue-58299.rs
  src/test/ui/nll/issue-58299.stderr
Labels: S-waiting-on-bors

#58378 rustc: Implement incremental "fat" LTO
  src/librustc/session/mod.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/traits/write.rs
  src/rustllvm/PassWrapper.cpp
  src/test/incremental/lto.rs
Labels: S-waiting-on-bors

#58407 specify "upper camel case" in style lint
  src/librustc_lint/Cargo.toml
  src/librustc_lint/nonstandard_style.rs
  src/test/ui/lint/lint-group-nonstandard-style.rs
  src/test/ui/lint/lint-group-nonstandard-style.stderr
  src/test/ui/lint/lint-non-camel-case-types.rs
  src/test/ui/lint/lint-non-camel-case-types.stderr
  src/test/ui/utf8_idents.rs
  src/test/ui/utf8_idents.stderr
Labels: S-waiting-on-bors

#58449 Notify @topecongiro when the state of rustfmt has changed
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#58501 [beta] Fix `attempted .def_id() on invalid def: NonMacroAttr(Builtin)`
  src/librustc_typeck/check/method/suggest.rs
  src/librustdoc/visit_lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#58477 Fix the syntax error in publish_toolstate.py
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors, merged-by-bors

#58293 Remove code for updating copyright years in generate-deriving-span-tests
  src/etc/generate-deriving-span-tests.py
Labels: S-waiting-on-bors

#58306 Don't default on std crate when manipulating browser history
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#58359 librustc_mir: use ? in impl_snapshot_for! macro
  src/librustc_mir/interpret/snapshot.rs
Labels: S-waiting-on-bors

#58429 fix Box::into_unique effecitvely transmuting to a raw ptr
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#58438 Use posix_spawn_file_actions_addchdir_np when possible
  src/libstd/sys/unix/process/process_unix.rs
Labels: S-waiting-on-bors

#58440 Whitelist the ARM v6 target-feature
  src/librustc_codegen_llvm/llvm_util.rs
Labels: S-waiting-on-bors
