Repository rust-lang/rust, pull requests merged in 2019-06, with the labels that each got.

#61300 Update musl-cross-make to 0.9.8
  src/ci/docker/scripts/musl-toolchain.sh
Labels: S-waiting-on-bors, merged-by-bors

#60897 error: remove StringError from Debug output
  src/libstd/error.rs
Labels: S-waiting-on-bors

#61319 Swap order of `unsafe async fn` to `async unsafe fn`
  src/libsyntax/parse/parser.rs
  src/test/ui/async-await/async-await.rs
  src/test/ui/async-await/await-macro.rs
Labels: S-waiting-on-bors, T-lang

#61344 Add regression test for const generics ICE
  src/test/ui/const-generics/const-generic-array-wrapper.rs
  src/test/ui/const-generics/const-generic-array-wrapper.stderr
Labels: S-waiting-on-bors

#61359 Fix links in Deref documentation
  src/libcore/ops/deref.rs
Labels: S-waiting-on-bors

#61363 Stabilize iter_nth_back feature
  src/liballoc/lib.rs
  src/libcore/iter/traits/double_ended.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#61369 Fixed lifetime misspelling
  src/librustc_codegen_ssa/README.md
Labels: S-waiting-on-bors

#61374 Explicitly suggest 'type_ascription' feature
  src/libsyntax/parse/diagnostics.rs
  src/test/ui/issues/issue-22644.stderr
  src/test/ui/issues/issue-34255-1.stderr
  src/test/ui/lifetime_starts_expressions.stderr
  src/test/ui/parser/recover-from-bad-variant.stderr
  src/test/ui/type/type-ascription-instead-of-statement-end.stderr
Labels: S-waiting-on-bors

#61382 Fixed a typo in core::convert::AsMut
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#60145 std::net: Ipv4Addr and Ipv6Addr improvements
  src/libstd/net/ip.rs
Labels: S-waiting-on-bors, merged-by-bors

#60729 Expand dynamic drop tests for cases in #47949
  src/test/run-pass/drop/dynamic-drop.rs
Labels: S-waiting-on-bors

#61263 Don't generate div inside header (h4/h3/h...) elements
  src/librustdoc/html/render.rs
  src/test/rustdoc/trait-attributes.rs
Labels: S-waiting-on-bors

#61364 Stabilize reverse_bits feature
  src/libcore/lib.rs
  src/libcore/num/mod.rs
  src/libcore/num/wrapping.rs
  src/libcore/tests/lib.rs
  src/librustc_mir/lib.rs
  src/test/run-pass/const-int-conversion.rs
  src/test/ui/consts/const-int-conversion.rs
  src/test/ui/consts/const-int-conversion.stderr
Labels: S-waiting-on-bors, T-libs, relnotes

#61375 Make "panic did not include expected string" message consistent
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#61387 Remove ty::BrFresh and RegionConstraintCollector::new_bound
  src/librustc/ich/impls_ty.rs
  src/librustc/infer/error_reporting/mod.rs
  src/librustc/infer/region_constraints/mod.rs
  src/librustc/ty/print/pretty.rs
  src/librustc/ty/structural_impls.rs
  src/librustc/ty/sty.rs
  src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs
  src/librustc_typeck/astconv.rs
Labels: S-waiting-on-bors

#61389 Remove GlobalArenas and use Arena instead
  src/librustc/arena.rs
  src/librustc/query/mod.rs
  src/librustc/ty/context.rs
  src/librustc/ty/mod.rs
  src/librustc_metadata/cstore_impl.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_typeck/check/writeback.rs
  src/librustc_typeck/collect.rs
  src/libsyntax/attr/builtin.rs
Labels: S-waiting-on-bors

#61391 Doc comment fixes for `rustc::mir::interpret::InterpretCx`
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/validity.rs
Labels: S-waiting-on-bors

#61388 Bump hashbrown to 0.4.0
  Cargo.lock
  src/libstd/Cargo.toml
Labels: S-waiting-on-bors, T-libs, beta-accepted, beta-nominated, merged-by-bors

#61299 rustc_codegen_llvm: a couple builder niceties.
  src/librustc_codegen_llvm/builder.rs
  src/librustc_codegen_llvm/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#61423 codegen: change `$6d$` to `$u6d$`
  src/librustc_codegen_utils/symbol_names/legacy.rs
  src/test/ui/symbol-names/issue-60925.legacy.stderr
  src/test/ui/symbol-names/issue-60925.rs
Labels: S-waiting-on-bors

#61441 Tweak wording when encountering `fn` call in pattern
  src/librustc_typeck/check/_match.rs
  src/test/ui/fn-in-pat.stderr
  src/test/ui/issues/issue-55587.stderr
  src/test/ui/match/match-fn-call.stderr
Labels: S-waiting-on-bors

#61451 Fix missing semicolon in doc
  src/libstd/macros.rs
Labels: S-waiting-on-bors

#61458 Fix typo in AsRef doc
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#61008 Fix lines highlighting in rustdoc source view
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, merged-by-bors

#59033 Fix duplicated bounds printing in rustdoc
  src/librustdoc/html/format.rs
Labels: S-waiting-on-bors, merged-by-bors

#61135 Fix documentation of `Rc::make_mut` regarding `rc::Weak`.
  src/liballoc/rc.rs
Labels: S-waiting-on-bors

#61404 miri unsizing: fix projecting into a field of an operand
  src/librustc_mir/interpret/cast.rs
Labels: S-waiting-on-bors

#61419 Add an unusual-conversion example to to_uppercase
  src/liballoc/str.rs
Labels: S-waiting-on-bors

#61420 Succinctify splice docs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#61444 Suggest using `as_ref` on `*const T`
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/issues/issue-21596.rs
  src/test/ui/issues/issue-21596.stderr
Labels: S-waiting-on-bors

#61485 azure: retry s3 upload if it fails
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors

#61489 ci: Reenable step timings on AppVeyor
  src/ci/shared.sh
Labels: S-waiting-on-bors

#61496 Do not panic in tidy on unbalanced parentheses in cfg's
  src/tools/tidy/src/pal.rs
Labels: S-waiting-on-bors

#61497 Treat 0 as special value for codegen-units-std
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#61499 Add regression test for existential type ICE #53457
  src/test/ui/impl-trait/issues/infinite-impl-trait-issue-38064.rs
  src/test/ui/impl-trait/issues/infinite-impl-trait-issue-38064.stderr
  src/test/ui/impl-trait/issues/issue-21659-show-relevant-trait-impls-3.rs
  src/test/ui/impl-trait/issues/issue-21659-show-relevant-trait-impls-3.stderr
  src/test/ui/impl-trait/issues/issue-42479.rs
  src/test/ui/impl-trait/issues/issue-49376.rs
  src/test/ui/impl-trait/issues/issue-52128.rs
  src/test/ui/impl-trait/issues/issue-53457.rs
  src/test/ui/impl-trait/issues/issue-55608-captures-empty-region.rs
  src/test/ui/impl-trait/issues/issue-57464-unexpected-regions.rs
  src/test/ui/impl-trait/issues/issue-57979-deeply-nested-impl-trait-in-assoc-proj.rs
  src/test/ui/impl-trait/issues/issue-57979-deeply-nested-impl-trait-in-assoc-proj.stderr
  src/test/ui/impl-trait/issues/issue-57979-impl-trait-in-path.rs
  src/test/ui/impl-trait/issues/issue-57979-impl-trait-in-path.stderr
  src/test/ui/impl-trait/issues/issue-57979-nested-impl-trait-in-assoc-proj.rs
  src/test/ui/impl-trait/issues/issue-57979-nested-impl-trait-in-assoc-proj.stderr
  src/test/ui/impl-trait/issues/universal-issue-48703.rs
  src/test/ui/impl-trait/issues/universal-issue-48703.stderr
  src/test/ui/impl-trait/issues/universal-turbofish-in-method-issue-50950.rs
  src/test/ui/impl-trait/issues/universal-turbofish-in-method-issue-50950.stderr
Labels: S-waiting-on-bors

#61454 Fix integer overflow in rotate_left
  src/librustc_mir/interpret/intrinsics.rs
  src/test/run-pass/const-int-rotate.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#61069 Make MIR drop terminators borrow the dropped location
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
Labels: S-waiting-on-bors

#61453 Remove unneeded feature attr from atomic integers doctests
  src/libcore/sync/atomic.rs
  src/test/ui/consts/min_const_fn/min_const_fn_libstd.rs
Labels: S-waiting-on-bors, T-doc

#61523 Hide gen_future API from documentation
  src/libstd/future.rs
Labels: S-waiting-on-bors

#61502 std: Update dependency on `backtrace`
  Cargo.lock
  src/libstd/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#61503 Fix cfg(test) build for x86_64-fortanix-unknown-sgx
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#61534 Edit docs of ExitStatus
  src/libstd/process.rs
Labels: S-waiting-on-bors

#61538 Don't use GNU noexec stack note
  src/librustc_target/spec/netbsd_base.rs
Labels: O-netbsd, S-waiting-on-bors

#61546 azure: Fix some minor issues which have broken our configuration
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors

#61494 Utilize cfg(bootstrap) over cfg(stage0)
  src/bootstrap/bin/rustc.rs
  src/bootstrap/compile.rs
  src/libcore/intrinsics.rs
  src/libcore/num/mod.rs
  src/libcore/ptr/non_null.rs
Labels: S-waiting-on-bors, merged-by-bors

#61556 librustc_errors: Rename AnnotateRs -> AnnotateSnippet
  src/librustc/session/config.rs
  src/librustc/session/mod.rs
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_errors/emitter.rs
  src/librustc_errors/lib.rs
Labels: S-waiting-on-bors

#61557 rustbuild: Include `rustfmt` in deduplicated dependencies
  src/bootstrap/tool.rs
  src/tools/rustc-workspace-hack/Cargo.toml
Labels: S-waiting-on-bors

#61571 Escape HashMap with backticks in needs_drop docs
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#61585 Update .mailmap with my name
  .mailmap
Labels: S-waiting-on-bors

#61591 Update .mailmap
  .mailmap
Labels: S-waiting-on-bors

#61332 Remove asterisk suggestion for move errors in borrowck
  src/librustc_mir/borrow_check/move_errors.rs
  src/test/ui/access-mode-in-closures.stderr
  src/test/ui/borrowck/borrowck-issue-2657-2.stderr
  src/test/ui/borrowck/borrowck-move-error-with-note.stderr
  src/test/ui/borrowck/borrowck-move-from-unsafe-ptr.stderr
  src/test/ui/borrowck/borrowck-move-out-of-overloaded-deref.stderr
  src/test/ui/borrowck/issue-54597-reject-move-out-of-borrow-via-pat.stderr
  src/test/ui/issues/issue-20801.stderr
  src/test/ui/nll/cannot-move-block-spans.stderr
  src/test/ui/nll/move-errors.stderr
  src/test/ui/std-uncopyable-atomics.stderr
  src/test/ui/suggestions/dont-suggest-ref/simple.rs
  src/test/ui/suggestions/dont-suggest-ref/simple.stderr
Labels: S-waiting-on-bors

#61586 ci: Disable LLVM/debug assertions for asmjs builder
  src/ci/docker/asmjs/Dockerfile
Labels: S-waiting-on-bors

#61599 libcore/pin: Minor grammar corrections for module documentation
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#61603 Increases heap size available during testing for SGX
  src/libstd/Cargo.toml
Labels: S-waiting-on-bors

#61605 Fix slice const generic length display
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/const-generics/const-generic-slice.rs
Labels: S-waiting-on-bors

#61618 make the backtrace field of EvalError private
  src/librustc/mir/interpret/error.rs
Labels: S-waiting-on-bors

#61130 Add std::mem::take as suggested in #61129
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors

#61223 Document tuple's Ord behavior as sequential
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#61615 syntax: Treat error literals in more principled way
  src/librustc/hir/intravisit.rs
  src/librustc/ich/impls_syntax.rs
  src/librustc_mir/hair/constant.rs
  src/libsyntax/ast.rs
  src/libsyntax/mut_visit.rs
  src/libsyntax/parse/literal.rs
  src/libsyntax/print/pprust.rs
  src/libsyntax/visit.rs
  src/libsyntax_ext/concat.rs
  src/test/ui/extenv/issue-55897.rs
  src/test/ui/extenv/issue-55897.stderr
Labels: S-waiting-on-bors

#61621 Clarify when we run steps with ONLY_HOSTS
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#61627 Add regression test for #61452.
  src/test/ui/async-await/issue-61452.rs
  src/test/ui/async-await/issue-61452.stderr
Labels: S-waiting-on-bors

#61641 Revert "Make LocalAnalizer visitor iterate instead of recurse"
  src/librustc_codegen_ssa/mir/analyze.rs
Labels: S-waiting-on-bors

#61647 Use stable wrappers in f32/f64::signum
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#61620 Stabilize Cell::from_mut and as_slice_of_cells
  src/libcore/cell.rs
  src/test/run-pass/rfcs/rfc-1789-as-cell/from-mut.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors, relnotes

#61655 checktools: unify grepping the TOOLSTATE file
  src/ci/docker/x86_64-gnu-tools/checktools.sh
Labels: S-waiting-on-bors, merged-by-bors

#61646 Remove useless allocations in macro_rules follow logic.
  src/libsyntax/ext/tt/macro_rules.rs
Labels: S-waiting-on-bors

#61666 Add test for trait ICE
  src/test/ui/traits/trait-with-dst.rs
Labels: S-waiting-on-bors

#61677 Add examples for make_ascii_{uppercase, lowercase}
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#61691 Miri: disable a slow test
  src/libcore/tests/num/dec2flt/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#61706 Use Build::read_dir instead of fs::read_dir in Build::cp_r
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#61608 Add nested 'yield' expression to weird expressions test
  src/test/run-pass/weird-exprs.rs
Labels: S-waiting-on-bors, merged-by-bors

#59600 Replaced linear token counting macros with optimized implementation
  src/librustc/hir/map/definitions.rs
  src/libserialize/serialize.rs
Labels: S-waiting-on-bors

#61501 get rid of real_intrinsics module
  src/libcore/intrinsics.rs
Labels: S-waiting-on-bors

#61683 Haiku: the maximum stack size is 16 MB
  src/librustc_interface/util.rs
Labels: S-waiting-on-bors

#61052 Emit save analysis notifications
  src/librustc_save_analysis/lib.rs
  src/test/ui/save-analysis/emit-notifications.nll.stderr
  src/test/ui/save-analysis/emit-notifications.rs
  src/test/ui/save-analysis/emit-notifications.stderr
Labels: S-waiting-on-bors, merged-by-bors

#61492 Const qualification comments
  src/librustc_mir/transform/qualify_consts.rs
Labels: S-waiting-on-bors, merged-by-bors

#60463 Implement RFC 2645 (transparent enums and unions)
  src/doc/unstable-book/src/language-features/transparent-enums.md
  src/doc/unstable-book/src/language-features/transparent-unions.md
  src/librustc/hir/check_attr.rs
  src/librustc/ty/mod.rs
  src/librustc_lint/types.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/error_codes.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax_pos/symbol.rs
  src/test/codegen/repr-transparent-aggregates-1.rs
  src/test/codegen/repr-transparent-aggregates-2.rs
  src/test/codegen/repr-transparent-aggregates-3.rs
  src/test/codegen/repr-transparent.rs
  src/test/run-pass/structs-enums/enum-null-pointer-opt.rs
  src/test/ui/attr-usage-repr.rs
  src/test/ui/attr-usage-repr.stderr
  src/test/ui/error-codes/E0517.stderr
  src/test/ui/feature-gates/feature-gate-transparent_enums.rs
  src/test/ui/feature-gates/feature-gate-transparent_enums.stderr
  src/test/ui/feature-gates/feature-gate-transparent_unions.rs
  src/test/ui/feature-gates/feature-gate-transparent_unions.stderr
  src/test/ui/issues/issue-14309.stderr
  src/test/ui/issues/issue-16250.stderr
  src/test/ui/issues/issue-31769.rs
  src/test/ui/issues/issue-31769.stderr
  src/test/ui/issues/issue-43988.stderr
  src/test/ui/lint/lint-ctypes-enum.rs
  src/test/ui/lint/lint-ctypes-enum.stderr
  src/test/ui/lint/lint-ctypes.stderr
  src/test/ui/repr/repr-transparent-other-items.rs
  src/test/ui/repr/repr-transparent-other-items.stderr
  src/test/ui/repr/repr-transparent.rs
  src/test/ui/repr/repr-transparent.stderr
  src/test/ui/union/union-repr-c.stderr
Labels: S-waiting-on-bors, merged-by-bors

#61518 Add loops to doc list of things not stable in const fn
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/test/ui/consts/min_const_fn/min_const_fn.nll.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.rs
  src/test/ui/consts/min_const_fn/min_const_fn.stderr
  src/test/ui/consts/single_variant_match_ice.rs
  src/test/ui/consts/single_variant_match_ice.stderr
Labels: S-waiting-on-bors

#61550 Windows 10 SDK is also required now.
  README.md
Labels: S-waiting-on-bors

#61652 Mention slice patterns in array
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#61698 typeck: Fix const generic in repeat param ICE.
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/const-generics/issue-61336-1.rs
  src/test/ui/const-generics/issue-61336-1.stderr
  src/test/ui/const-generics/issue-61336.rs
  src/test/ui/const-generics/issue-61336.stderr
Labels: S-waiting-on-bors

#61707 Azure: retry failed awscli installs
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors

#61715 make sure make_ascii_lowercase actually leaves upper-case non-ASCII characters alone
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#61724 core: use memcmp optimization for 128 bit integer slices
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#61726 Use `for_each` in `Iterator::partition`
  src/libcore/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#61632 ci: Collect CPU usage statistics on Azure
  .azure-pipelines/steps/run.yml
  src/ci/cpu-usage-over-time.py
Labels: S-waiting-on-bors

#61671 implement nth_back for Range(Inclusive)
  src/libcore/iter/range.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#61688 is_fp and is_floating_point do the same thing, remove the former
  src/librustc/ty/sty.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#61705 Pass cflags rather than cxxflags to LLVM as CMAKE_C_FLAGS
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#60669 Allow attributes in formal function parameters
  src/librustc_data_structures/thin_vec.rs
  src/librustc_passes/ast_validation.rs
  src/libsyntax/ast.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/config.rs
  src/libsyntax/ext/build.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax/mut_visit.rs
  src/libsyntax/parse/attr.rs
  src/libsyntax/parse/diagnostics.rs
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/mod.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/visit.rs
  src/libsyntax_ext/deriving/generic/mod.rs
  src/libsyntax_pos/symbol.rs
  src/test/ui/parser/fn-arg-doc-comment.rs
  src/test/ui/parser/fn-arg-doc-comment.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-2018.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-2018.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-allowed.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-builtin-attrs.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-builtin-attrs.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-cfg.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-cfg.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-feature-gate.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-feature-gate.stderr
Labels: S-waiting-on-bors, merged-by-bors

#61587 ci: Disable LLVM/debug assertions for distcheck
  src/ci/docker/x86_64-gnu-distcheck/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#61612 Special-case literals in `parse_bottom_expr`.
  src/libsyntax/parse/parser.rs
Labels: S-waiting-on-bors, merged-by-bors

#61426 Use a single lifetime for MIR construction
  src/librustc/infer/mod.rs
  src/librustc_mir/build/block.rs
  src/librustc_mir/build/expr/as_constant.rs
  src/librustc_mir/build/expr/as_operand.rs
  src/librustc_mir/build/expr/as_place.rs
  src/librustc_mir/build/expr/as_rvalue.rs
  src/librustc_mir/build/expr/as_temp.rs
  src/librustc_mir/build/expr/into.rs
  src/librustc_mir/build/expr/stmt.rs
  src/librustc_mir/build/into.rs
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/build/matches/simplify.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/build/matches/util.rs
  src/librustc_mir/build/misc.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/build/scope.rs
  src/librustc_mir/hair/constant.rs
  src/librustc_mir/hair/cx/block.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_mir/hair/cx/mod.rs
  src/librustc_mir/hair/mod.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/hair/util.rs
Labels: S-waiting-on-bors, merged-by-bors

#60376 Stabilize Option::xor
  src/libcore/option.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#61629 Hygienize macros in the standard library
  src/liballoc/macros.rs
  src/libcore/macros.rs
  src/libstd/macros.rs
  src/test/ui/hygiene/no_implicit_prelude.rs
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/imports/local-modularized-tricky-fail-1.rs
  src/test/ui/imports/local-modularized-tricky-fail-1.stderr
Labels: S-waiting-on-bors

#61675 Include frame pointer for bare metal RISC-V targets
  src/librustc_target/spec/riscv32imac_unknown_none_elf.rs
  src/librustc_target/spec/riscv32imc_unknown_none_elf.rs
  src/librustc_target/spec/riscv64gc_unknown_none_elf.rs
  src/librustc_target/spec/riscv64imac_unknown_none_elf.rs
Labels: S-waiting-on-bors

#61750 Fix x.py install
  src/bootstrap/install.rs
Labels: S-waiting-on-bors

#61761 Add an alias for x86_64-sun-solaris target tuple
  src/librustc_target/spec/mod.rs
  src/tools/build-manifest/src/main.rs
Labels: A-rustbuild, S-waiting-on-bors

#61762 rustbuild: fix libtest_stamp
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#61763 ci: fix ci stats upload condition
  .azure-pipelines/steps/run.yml
Labels: S-waiting-on-bors

#61776 Fix typos in error_codes
  src/librustc/error_codes.rs
  src/test/ui/explain.stdout
Labels: S-waiting-on-bors

#61597 Bump dirs, rand and redox_users
  Cargo.lock
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, merged-by-bors

#61598 Handle index out of bound errors during const eval without panic
  src/librustc_mir/interpret/place.rs
  src/test/ui/consts/array-literal-index-oob.rs
  src/test/ui/consts/array-literal-index-oob.stderr
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated

#61720 std: Remove internal definitions of `cfg_if!` macro
  Cargo.lock
  src/libcore/hint.rs
  src/libcore/internal_macros.rs
  src/libpanic_unwind/Cargo.toml
  src/libpanic_unwind/lib.rs
  src/libpanic_unwind/macros.rs
  src/libstd/Cargo.toml
  src/libstd/lib.rs
  src/libstd/macros.rs
  src/libstd/os/mod.rs
  src/libstd/sys/mod.rs
  src/libstd/sys/wasm/mod.rs
  src/libstd/sys/wasm/thread.rs
  src/libstd/sys_common/mod.rs
  src/libunwind/Cargo.toml
  src/libunwind/lib.rs
  src/libunwind/libunwind.rs
  src/libunwind/macros.rs
Labels: S-waiting-on-bors

#61757 Deprecate ONCE_INIT in future 1.38 release
  src/librustc_metadata/dynamic_lib.rs
  src/libstd/sync/mod.rs
  src/libstd/sync/once.rs
  src/test/run-pass/issues/issue-39367.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#61791 Small cleanup in `check_pat_path`
  src/librustc_typeck/check/_match.rs
Labels: S-waiting-on-bors

#61772 ci: Enable toolstate tracking on Azure
  .azure-pipelines/auto.yml
  .azure-pipelines/master.yml
  .azure-pipelines/pr.yml
  .azure-pipelines/steps/run.yml
  src/ci/docker/run.sh
  src/ci/docker/x86_64-gnu-tools/repo.sh
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors, merged-by-bors

#61792 Add ui test for issue 51301
  src/test/ui/issues/issue-51301.rs
  src/test/ui/issues/issue-51301.stderr
Labels: A-mir, S-waiting-on-bors, merged-by-bors

#61803 typeck: small refactoring, add 'fn write_resolution'
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#61679 in which we decline to suggest the anonymous lifetime in declarations
  src/librustc/hir/lowering.rs
  src/test/ui/in-band-lifetimes/issue-61124-anon-lifetime-in-struct-declaration.rs
  src/test/ui/in-band-lifetimes/issue-61124-anon-lifetime-in-struct-declaration.stderr
Labels: S-waiting-on-bors, merged-by-bors

#61421 docs: Use String in Rc::into_raw examples
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors, merged-by-bors

#61785 note some safety concerns of raw-ptr-to-ref casts
  src/libcore/ptr/mod.rs
Labels: S-waiting-on-bors

#61805 typeck: Fix ICE for blocks in repeat expr count.
  src/librustc_typeck/astconv.rs
  src/test/ui/const-generics/issue-61336-2.rs
  src/test/ui/const-generics/issue-61336-2.stderr
Labels: S-waiting-on-bors

#61824 in which we decline to lint single-use lifetimes in `derive`d impls
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/single-use-lifetime/one-use-in-struct.rs
Labels: S-waiting-on-bors

#61844 Change `...` to `..=` where applicable
  src/libcore/benches/ascii.rs
  src/libcore/char/convert.rs
  src/libcore/char/methods.rs
  src/libcore/num/mod.rs
  src/librustc/hir/mod.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_target/abi/mod.rs
  src/libsyntax/ast.rs
  src/libsyntax/util/parser.rs
Labels: S-waiting-on-bors

#61854 Minor cosmetic improvements to accompany PR 61825
  src/librustc_typeck/check/_match.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#61828 make sure we use cfg-if as a std dependency
  src/libstd/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#61447 Add some Vec <-> VecDeque documentation
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors

#61704 Pass LLVM linker flags to librustc_llvm build
  src/bootstrap/compile.rs
  src/librustc_llvm/build.rs
Labels: S-waiting-on-bors

#61829 rustbuild: include llvm-libunwind in dist tarball
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#61869 Cleanup some new active feature gates
  src/libsyntax/feature_gate.rs
Labels: S-waiting-on-bors

#61881 librustc_codegen_llvm: Use repr(transparent) for bitflags over repr(C…
  src/librustc_codegen_llvm/llvm/ffi.rs
Labels: S-waiting-on-bors, merged-by-bors

#61892 weird-exprs: if if if if
  src/test/run-pass/weird-exprs.rs
Labels: S-waiting-on-bors, merged-by-bors

#58508 Add a RUSTC_TIME env var to time rust crates during bootstrap
  src/bootstrap/bin/rustc.rs
Labels: S-waiting-on-bors, merged-by-bors

#61702 test more variants of enum-int-casting
  src/test/run-pass/consts/const-enum-cast.rs
Labels: S-waiting-on-bors

#61885 Help LLVM better optimize slice::Iter(Mut)::len
  src/libcore/intrinsics.rs
  src/libcore/slice/mod.rs
  src/test/codegen/slice-iter-len-eq-zero.rs
Labels: S-waiting-on-bors

#61893 make `Weak::ptr_eq`s into methods
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#61908 don't ICE on large files
  src/libsyntax/source_map.rs
  src/libsyntax_pos/lib.rs
Labels: S-waiting-on-bors

#61864 Make use of `ptr::null(_mut)` instead of casting zero
  src/bootstrap/job.rs
  src/bootstrap/util.rs
  src/libarena/lib.rs
  src/libpanic_unwind/dummy.rs
  src/libpanic_unwind/seh.rs
  src/librustc_errors/lock.rs
  src/librustc_metadata/dynamic_lib.rs
  src/librustc_typeck/error_codes.rs
  src/libstd/sys/wasi/args.rs
  src/libstd/sys/wasm/thread_local_atomics.rs
  src/test/run-make-fulldeps/alloc-extern-crates/fakealloc.rs
  src/test/run-pass/cast.rs
  src/test/run-pass/cleanup-shortcircuit.rs
  src/test/run-pass/consts/const-block.rs
  src/test/run-pass/issues/issue-13259-windows-tcb-trash.rs
  src/test/run-pass/issues/issue-19001.rs
  src/test/run-pass/issues/issue-39367.rs
  src/test/run-pass/issues/issue-46069.rs
  src/test/run-pass/structs-enums/enum-null-pointer-opt.rs
  src/test/ui/casts-issue-46365.rs
  src/test/ui/consts/const-eval/ice-generic-assoc-const.rs
  src/test/ui/consts/min_const_fn/min_const_fn.rs
  src/test/ui/consts/min_const_fn/min_const_fn_unsafe.rs
  src/test/ui/derived-errors/issue-31997.rs
  src/test/ui/derived-errors/issue-31997.stderr
  src/test/ui/error-codes/E0605.rs
  src/test/ui/error-codes/E0607.rs
  src/test/ui/error-festival.rs
  src/test/ui/issues/issue-17458.rs
  src/test/ui/issues/issue-17458.stderr
  src/test/ui/issues/issue-20801.rs
  src/test/ui/issues/issue-22034.rs
  src/test/ui/mismatched_types/cast-rfc0401.rs
Labels: S-waiting-on-bors, merged-by-bors

#59625 Refactor C FFI variadics to more closely match their C counterparts, and add Clone implementation
  src/libcore/ffi.rs
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/ty/layout.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/va_arg.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/mir/mod.rs
  src/librustc_codegen_ssa/traits/intrinsic.rs
  src/librustc_lint/types.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_typeck/check/intrinsic.rs
  src/libstd/ffi/mod.rs
  src/test/auxiliary/rust_test_helpers.c
  src/test/codegen/c-variadic-copy.rs
  src/test/codegen/c-variadic-opt.rs
  src/test/codegen/c-variadic.rs
  src/test/run-make-fulldeps/c-link-to-rust-va-list-fn/checkrust.rs
  src/test/run-pass/variadic-ffi.rs
  src/test/ui/c-variadic/variadic-ffi-1.stderr
  src/test/ui/c-variadic/variadic-ffi-4.nll.stderr
  src/test/ui/c-variadic/variadic-ffi-4.rs
  src/test/ui/c-variadic/variadic-ffi-4.stderr
  src/test/ui/error-codes/E0617.rs
  src/test/ui/error-codes/E0617.stderr
  src/test/ui/symbol-names/impl1.rs
Labels: S-waiting-on-bors, merged-by-bors

#61505 Only show methods that appear in `impl` blocks in the Implementors sections of trait doc pages
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors, T-doc, T-rustdoc

#61701 move stray run-pass const tests into const/ folder
  src/test/run-pass/consts/assoc-const.rs
  src/test/run-pass/consts/bswap-const.rs
  src/test/run-pass/consts/chained-constants-stackoverflow.rs
  src/test/run-pass/consts/const-block-non-item-statement-3.rs
  src/test/run-pass/consts/const-block-non-item-statement.rs
  src/test/run-pass/consts/const-fn-type-name.rs
  src/test/run-pass/consts/const-int-conversion.rs
  src/test/run-pass/consts/const-int-overflowing.rs
  src/test/run-pass/consts/const-int-rotate.rs
  src/test/run-pass/consts/const-int-saturating-arith.rs
  src/test/run-pass/consts/const-int-sign.rs
  src/test/run-pass/consts/const-int-wrapping.rs
  src/test/run-pass/consts/const-needs_drop.rs
  src/test/run-pass/consts/deref_in_pattern.rs
  src/test/run-pass/consts/ice-48279.rs
  src/test/run-pass/consts/issue-37550.rs
  src/test/run-pass/consts/issue-broken-mir.rs
  src/test/run-pass/consts/locals-in-const-fn.rs
  src/test/run-pass/consts/match-const-fn-structs.rs
  src/test/run-pass/consts/mozjs-error.rs
  src/test/run-pass/consts/non-scalar-cast.rs
  src/test/run-pass/consts/promotion.rs
  src/test/run-pass/consts/references.rs
  src/test/run-pass/consts/repeat_match.rs
  src/test/run-pass/consts/return-in-const-fn.rs
  src/test/run-pass/consts/signed_enum_discr.rs
  src/test/run-pass/consts/transmute-const.rs
  src/test/run-pass/consts/tuple-struct-constructors.rs
Labels: S-waiting-on-bors

#61802 Make MaybeUninit #[repr(transparent)]
  src/libcore/lib.rs
  src/libcore/mem/maybe_uninit.rs
Labels: S-waiting-on-bors, T-lang

#61839 ci: Add a script for generating CPU usage graphs
  src/ci/cpu-usage-over-time.py
  src/etc/cpu-usage-over-time-plot.sh
Labels: S-waiting-on-bors

#61842 Remove unnecessary lift calls
  src/librustc/infer/canonical/canonicalizer.rs
  src/librustc/infer/canonical/mod.rs
  src/librustc/infer/canonical/query_response.rs
  src/librustc/infer/opaque_types/mod.rs
  src/librustc/middle/mem_categorization.rs
  src/librustc/traits/codegen/mod.rs
  src/librustc/traits/project.rs
  src/librustc/traits/query/normalize.rs
  src/librustc/traits/query/type_op/mod.rs
  src/librustc/traits/query/type_op/normalize.rs
  src/librustc/traits/specialize/mod.rs
  src/librustc/ty/error.rs
  src/librustc/ty/sty.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/nll/region_infer/mod.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/build/expr/as_rvalue.rs
  src/librustc_mir/dataflow/drop_flag_effects.rs
  src/librustc_mir/hair/constant.rs
  src/librustc_mir/hair/cx/mod.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_traits/normalize_erasing_regions.rs
Labels: S-waiting-on-bors

#61843 Turn down the myriad-closures test
  src/test/run-pass-fulldeps/myriad-closures.rs
Labels: S-waiting-on-bors

#61896 rustc_typeck: correctly compute `Substs` for `Res::SelfCtor`.
  src/librustc_typeck/check/mod.rs
  src/test/ui/issues/issue-57924.rs
  src/test/ui/issues/issue-57924.stderr
  src/test/ui/issues/issue-61882-2.rs
  src/test/ui/issues/issue-61882-2.stderr
  src/test/ui/issues/issue-61882.rs
  src/test/ui/issues/issue-61882.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#61938 create an issue for miri even in status test-fail
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#61941 Preserve generator and yield source for error messages
  src/librustc/cfg/construct.rs
  src/librustc/hir/intravisit.rs
  src/librustc/hir/lowering.rs
  src/librustc/hir/mod.rs
  src/librustc/hir/print.rs
  src/librustc/ich/impls_hir.rs
  src/librustc/infer/error_reporting/need_type_info.rs
  src/librustc/middle/expr_use_visitor.rs
  src/librustc/middle/liveness.rs
  src/librustc/middle/region.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_typeck/check/expr.rs
  src/librustc_typeck/check/generator_interior.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/async-await/unresolved_type_param.rs
  src/test/ui/async-await/unresolved_type_param.stderr
Labels: S-waiting-on-bors

#60667 Add functions for building raw slices to libcore
  src/libcore/ptr/mod.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, T-libs

#61547 Support `cfg` and `cfg_attr` on generic parameters
  src/libsyntax/config.rs
  src/libsyntax/ext/expand.rs
  src/test/ui/conditional-compilation/cfg-generic-params.rs
  src/test/ui/conditional-compilation/cfg-generic-params.stderr
  src/test/ui/issues/issue-51279.rs
  src/test/ui/issues/issue-51279.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#61940 Make Place::ty iterate
  src/librustc/mir/tcx.rs
Labels: S-waiting-on-bors

#60454 Add custom nth_back to Skip
  src/libcore/iter/adapters/mod.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#60772 Implement nth_back for slice::{Iter, IterMut}
  src/libcore/slice/mod.rs
  src/libcore/tests/slice.rs
Labels: S-waiting-on-bors

#61782 suggest tuple struct syntax
  src/librustc_typeck/check/expr.rs
  src/test/ui/issues/issue-4736.stderr
  src/test/ui/numeric/numeric-fields.stderr
Labels: S-waiting-on-bors

#61929 Fix Into trait docs links
  src/libcore/convert.rs
Labels: S-waiting-on-bors, merged-by-bors

#61998 rustc_mir: support type parameters by printing them as `_`.
  src/librustc_mir/interpret/intrinsics/type_name.rs
  src/test/run-pass/issues/issue-61894.rs
Labels: S-waiting-on-bors, merged-by-bors

#61900 implement Error::source for Box<T: Error>
  src/libstd/error.rs
Labels: S-waiting-on-bors

#61979 Implement Debug for PlaceBase
  src/librustc/mir/mod.rs
Labels: S-waiting-on-bors

#61981 Closures implement Copy and Clone, generators don't
  src/doc/unstable-book/src/language-features/generators.md
Labels: A-generators, C-cleanup, S-waiting-on-bors
