Repository rust-lang/rust, pull requests merged in 2019-09, with the labels that each got.

#63703 rustdoc: warn on empty doc test
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/invalid-syntax.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
Labels: S-waiting-on-bors, merged-by-bors

#64036 Kill borrows from assignments after generating new borrows
  src/librustc_mir/dataflow/impls/borrows.rs
  src/test/ui/nll/self-assign-ref-mut.rs
Labels: S-waiting-on-bors, merged-by-bors

#63410 Update BufWriter example to include call to flush()
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors

#64029 Account for rounding errors when deciding the diagnostic boundaries
  src/librustc_errors/emitter.rs
Labels: S-waiting-on-bors

#64032 rustdoc use -Ccodegen-units=1 by default for test compile
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#64039 Update sync condvar doc style
  src/libstd/sync/condvar.rs
Labels: S-waiting-on-bors

#64042 Fix word repetition in str documentation
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#63834 remove the unstable rustdoc parameter --linker
  src/bootstrap/bin/rustdoc.rs
  src/doc/rustdoc/src/unstable-features.md
  src/librustdoc/config.rs
  src/librustdoc/lib.rs
  src/librustdoc/test.rs
  src/test/run-make-fulldeps/tools.mk
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#63869 Fix build failure in case file doesn't exist
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors, merged-by-bors

#64058 librustc_errors: Extract sugg/subst handling into method
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_errors/emitter.rs
Labels: S-waiting-on-bors

#64071 use just one name when parameters and fields are the same
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors

#64104 Emit error on intrinsic to fn ptr casts
  src/librustc/infer/error_reporting/mod.rs
  src/librustc/ty/error.rs
  src/librustc/ty/structural_impls.rs
  src/librustc_typeck/check/cast.rs
  src/librustc_typeck/check/coercion.rs
  src/test/ui/reify-intrinsic.rs
  src/test/ui/reify-intrinsic.stderr
Labels: S-waiting-on-bors

#64046 [beta] Utilize released stable over dev-static
  src/stage0.txt
Labels: S-waiting-on-bors

#63166 Add Result::cloned{,_err} and Result::copied{,_err}
  src/libcore/result.rs
Labels: S-waiting-on-bors, merged-by-bors

#63549 Rev::rposition counts from the wrong end
  src/libcore/iter/adapters/mod.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#63985 Stabilize pin_into_inner in 1.39.0
  src/libcore/pin.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#64031 Harden `param_attrs` test wrt. usage of a proc macro `#[attr]`
  src/test/ui/rfc-2565-param-attrs/auxiliary/ident-mac.rs
  src/test/ui/rfc-2565-param-attrs/proc-macro-cannot-be-used.rs
  src/test/ui/rfc-2565-param-attrs/proc-macro-cannot-be-used.stderr
Labels: F-param_attrs, S-waiting-on-bors

#64043 Add some more tests for underscore imports
  src/test/ui/underscore-imports/auxiliary/duplicate.rs
  src/test/ui/underscore-imports/auxiliary/underscore-imports.rs
  src/test/ui/underscore-imports/basic.rs
  src/test/ui/underscore-imports/basic.stderr
  src/test/ui/underscore-imports/cycle.rs
  src/test/ui/underscore-imports/duplicate.rs
  src/test/ui/underscore-imports/intercrate.rs
  src/test/ui/underscore-imports/shadow.rs
  src/test/ui/underscore-imports/shadow.stderr
  src/test/ui/underscore-imports/unused-2018.rs
  src/test/ui/underscore-imports/unused-2018.stderr
Labels: S-waiting-on-bors

#64092 Update xLTO compatibility table in rustc book.
  src/doc/rustc/src/linker-plugin-lto.md
Labels: S-waiting-on-bors, T-compiler, T-doc, beta-nominated

#64120 Move path parsing earlier
  src/libsyntax/parse/parser/expr.rs
Labels: S-waiting-on-bors

#64123 Added warning around code with reference to uninit bytes
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#64128 unused_parens: account for or-patterns and `&(mut x)`
  src/librustc_lint/unused.rs
  src/test/ui/lint/issue-54538-unused-parens-lint.rs
  src/test/ui/lint/issue-54538-unused-parens-lint.stderr
Labels: F-or_patterns, S-waiting-on-bors

#64142 Fix doc links in `std::cmp` module
  src/libcore/cmp.rs
Labels: S-waiting-on-author

#64148 fix a few typos in comments
  src/librustc_llvm/build.rs
Labels: S-waiting-on-author

#63774 Fix `window.hashchange is not a function`
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, T-rustdoc

#64003 place: Passing `align` = `layout.align.abi`, when also passing `layout`
  src/librustc_codegen_llvm/builder.rs
  src/librustc_codegen_llvm/common.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/mir/mod.rs
  src/librustc_codegen_ssa/mir/operand.rs
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
Labels: S-waiting-on-bors

#64030 Fix unlock ordering in SGX synchronization primitives
  src/libstd/sys/sgx/condvar.rs
  src/libstd/sys/sgx/mutex.rs
  src/libstd/sys/sgx/rwlock.rs
  src/libstd/sys/sgx/waitqueue.rs
Labels: S-waiting-on-bors

#64051 Add x86_64-linux-kernel target
  src/librustc_target/spec/linux_kernel_base.rs
  src/librustc_target/spec/mod.rs
  src/librustc_target/spec/x86_64_linux_kernel.rs
Labels: S-waiting-on-bors

#64100 Fix const eval bug breaking run-pass tests in Miri
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#64157 Opaque type locations in error message for clarity.
  src/librustc/infer/error_reporting/mod.rs
  src/test/ui/suggestions/opaque-type-error.stderr
Labels: S-waiting-on-bors

#64156 Assume non-git LLVM is fresh if the stamp file exists
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#64174 Add missing code examples on Iterator trait
  src/libcore/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#64175 Fix invalid span generation when it should be div
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#64186 std: Improve downstream codegen in `Command::env`
  src/libstd/sys/cloudabi/shims/process.rs
  src/libstd/sys/sgx/process.rs
  src/libstd/sys/unix/process/mod.rs
  src/libstd/sys/unix/process/process_common.rs
  src/libstd/sys/vxworks/process/process_common.rs
  src/libstd/sys/wasi/process.rs
  src/libstd/sys/wasm/process.rs
  src/libstd/sys/windows/process.rs
  src/libstd/sys_common/process.rs
Labels: S-waiting-on-bors

#64190 fill metadata in rustc_lexer's Cargo.toml
  src/librustc_lexer/Cargo.toml
Labels: S-waiting-on-author

#64198 Add Fuchsia to actually_monotonic
  src/libstd/sys/unix/time.rs
Labels: S-waiting-on-author

#63565 Rust 2018: NLL migrate mode => hard error
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/borrowck/borrowck-migrate-to-nll.edition.stderr
  src/test/ui/borrowck/borrowck-migrate-to-nll.rs
  src/test/ui/borrowck/borrowck-migrate-to-nll.zflag.stderr
Labels: S-waiting-on-bors, T-lang, relnotes

#63969 Add missing examples for Option type
  src/libcore/option.rs
Labels: S-waiting-on-bors

#64067 Remove no-prefer-dynamic from valgrind tests
  src/test/run-pass-valgrind/cast-enum-with-dtor.rs
  src/test/run-pass-valgrind/cleanup-auto-borrow-obj.rs
  src/test/run-pass-valgrind/cleanup-stdin.rs
  src/test/run-pass-valgrind/down-with-thread-dtors.rs
  src/test/run-pass-valgrind/dst-dtor-1.rs
  src/test/run-pass-valgrind/dst-dtor-2.rs
  src/test/run-pass-valgrind/dst-dtor-3.rs
  src/test/run-pass-valgrind/dst-dtor-4.rs
  src/test/run-pass-valgrind/exit-flushes.rs
  src/test/run-pass-valgrind/osx-frameworks.rs
Labels: S-waiting-on-bors

#64166 Better way of conditioning the sanitizer builds
  src/bootstrap/compile.rs
  src/librustc_asan/build.rs
  src/librustc_lsan/build.rs
  src/librustc_msan/build.rs
  src/librustc_tsan/build.rs
Labels: S-waiting-on-bors

#64189 annotate-snippet emitter: Deal with multispans from macros, too
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_errors/emitter.rs
Labels: S-waiting-on-bors

#64206 annotate-snippet emitter: Update an issue number
  src/librustc_errors/annotate_snippet_emitter_writer.rs
Labels: S-waiting-on-bors

#64208 it's more pythonic to use 'is not None' in python files
  src/bootstrap/bootstrap.py
  src/libcore/unicode/printable.py
Labels: S-waiting-on-bors

#63927 Filter linkcheck spurious failure
  src/tools/rustbook/src/main.rs
Labels: S-waiting-on-bors

#64149 rustc_codegen_llvm: give names to non-alloca variable values.
  src/librustc_codegen_llvm/debuginfo/mod.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_codegen_ssa/mir/mod.rs
  src/librustc_codegen_ssa/mir/statement.rs
  src/librustc_codegen_ssa/traits/debuginfo.rs
  src/test/codegen/var-names.rs
Labels: S-waiting-on-bors

#64231 Move the HIR CFG to `rustc_ast_borrowck`
  src/librustc/lib.rs
  src/librustc_ast_borrowck/borrowck/mod.rs
  src/librustc_ast_borrowck/borrowck/move_data.rs
  src/librustc_ast_borrowck/cfg/construct.rs
  src/librustc_ast_borrowck/cfg/graphviz.rs
  src/librustc_ast_borrowck/cfg/mod.rs
  src/librustc_ast_borrowck/dataflow.rs
  src/librustc_ast_borrowck/graphviz.rs
  src/librustc_ast_borrowck/lib.rs
  src/librustc_driver/pretty.rs
Labels: S-waiting-on-bors

#64236 reduce visibility
  src/libsyntax/parse/parser.rs
  src/libsyntax/util/parser.rs
Labels: S-waiting-on-bors

#64240 Include compiler-rt in the source tarball
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors, T-release, beta-nominated

#64241 [doc] Added more prereqs and note about default directory
  README.md
Labels: S-waiting-on-bors

#64243 Move injection of attributes from command line to `libsyntax_ext`
  src/librustc_interface/passes.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/parse/attr.rs
  src/libsyntax_ext/cmdline_attrs.rs
  src/libsyntax_ext/lib.rs
Labels: S-waiting-on-bors

#64235 Upgrade env_logger to 0.6
  Cargo.lock
  src/librustc_driver/Cargo.toml
  src/tools/compiletest/Cargo.toml
Labels: S-waiting-on-bors

#64258 compiletest: Match suffixed environments
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors

#64052 Rename test locals to work around LLDB bug
  src/test/debuginfo/boxed-struct.rs
Labels: S-waiting-on-bors

#64229 Reduce span to function name in unreachable calls
  src/librustc_typeck/check/expr.rs
  src/test/ui/never-assign-dead-code.stderr
  src/test/ui/reachable/expr_call.stderr
  src/test/ui/reachable/expr_method.stderr
  src/test/ui/unreachable/unreachable-in-call.rs
  src/test/ui/unreachable/unreachable-in-call.stderr
Labels: S-waiting-on-bors

#64096 Fix regex replacement in theme detection
  src/librustdoc/html/static/storage.js
Labels: S-waiting-on-bors, merged-by-bors

#62205 Add Iterator comparison methods that take a comparison function
  src/libcore/iter/traits/iterator.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors

#64152 Use backtrace formatting from the backtrace crate
  Cargo.lock
  src/libstd/Cargo.toml
  src/libstd/panicking.rs
  src/libstd/sys_common/backtrace.rs
Labels: S-waiting-on-author

#64265 resolve: Mark more erroneous imports as used
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/imports/unresolved-imports-used.rs
  src/test/ui/imports/unresolved-imports-used.stderr
Labels: S-waiting-on-bors

#64267 rustdoc: fix diagnostic with mixed code block styles
  src/librustdoc/html/markdown.rs
  src/test/rustdoc-ui/invalid-syntax.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
Labels: S-waiting-on-bors

#63994 Refactor the `MirPass for QualifyAndPromoteConstants`
  src/librustc_mir/transform/qualify_consts.rs
Labels: S-waiting-on-bors, merged-by-bors

#64263 Replace "feature gated" wording with "unstable".
  src/librustc_metadata/native_libs.rs
  src/test/ui/attributes/obsolete-attr.rs
  src/test/ui/attributes/unknown-attr.rs
  src/test/ui/feature-gate/feature-gate-static-nobundle-2.rs
  src/test/ui/feature-gate/feature-gate-static-nobundle-2.stderr
  src/test/ui/feature-gates/feature-gate-is_sorted.rs
  src/test/ui/feature-gates/feature-gate-link_cfg.rs
  src/test/ui/feature-gates/feature-gate-link_cfg.stderr
  src/test/ui/feature-gates/feature-gate-static-nobundle.rs
  src/test/ui/feature-gates/feature-gate-static-nobundle.stderr
  src/test/ui/feature-gates/feature-gate-type_ascription.rs
  src/test/ui/proc-macro/resolve-error.rs
  src/test/ui/tool-attributes/tool-attributes-misplaced-1.rs
Labels: S-waiting-on-bors

#64288 use 'get_toml' instead of regular expression
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#63468 Resolve attributes in several places
  src/librustc/hir/map/def_collector.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/librustc_typeck/collect.rs
  src/libsyntax/ast.rs
  src/libsyntax/ext/base.rs
  src/libsyntax/ext/build.rs
  src/libsyntax/ext/expand.rs
  src/libsyntax/ext/placeholders.rs
  src/libsyntax/ext/proc_macro.rs
  src/libsyntax/mut_visit.rs
  src/libsyntax/parse/diagnostics.rs
  src/libsyntax/parse/parser.rs
  src/libsyntax/parse/parser/expr.rs
  src/libsyntax/parse/parser/generics.rs
  src/libsyntax/parse/parser/item.rs
  src/libsyntax/parse/parser/pat.rs
  src/libsyntax/print/pprust/tests.rs
  src/libsyntax_ext/deriving/generic/mod.rs
  src/test/ui/attrs-resolution-errors.rs
  src/test/ui/attrs-resolution-errors.stderr
  src/test/ui/attrs-resolution.rs
  src/test/ui/conditional-compilation/cfg-generic-params.rs
  src/test/ui/conditional-compilation/cfg-generic-params.stderr
  src/test/ui/feature-gates/feature-gate-custom_attribute2.rs
  src/test/ui/feature-gates/feature-gate-custom_attribute2.stderr
  src/test/ui/issues/issue-49934-errors.rs
  src/test/ui/issues/issue-49934-errors.stderr
  src/test/ui/issues/issue-49934.rs
  src/test/ui/issues/issue-49934.stderr
  src/test/ui/proc-macro/proc-macro-gates2.rs
  src/test/ui/proc-macro/proc-macro-gates2.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-builtin-attrs.rs
  src/test/ui/rfc-2565-param-attrs/param-attrs-builtin-attrs.stderr
  src/test/ui/rfc-2565-param-attrs/proc-macro-cannot-be-used.rs
  src/test/ui/rfc-2565-param-attrs/proc-macro-cannot-be-used.stderr
Labels: S-waiting-on-bors

#64121 Override `StepBy::{try_fold, try_rfold}`
  src/libcore/iter/adapters/mod.rs
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#64278 check git in bootstrap.py
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#64306 Fix typo in config.toml.example
  config.toml.example
Labels: S-waiting-on-bors

#64312 Unify escape usage
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#63806 Upgrade rand to 0.7
  Cargo.lock
  src/librustc_incremental/Cargo.toml
  src/libstd/Cargo.toml
  src/libstd/fs.rs
  src/libstd/tests/env.rs
Labels: S-waiting-on-bors

#64054 Always emit unresolved import errors and hide unused import lint
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/extenv/issue-55897.rs
  src/test/ui/extenv/issue-55897.stderr
  src/test/ui/imports/unresolved-imports-used.rs
  src/test/ui/imports/unresolved-imports-used.stderr
  src/test/ui/rust-2018/uniform-paths/deadlock.rs
  src/test/ui/rust-2018/uniform-paths/deadlock.stderr
Labels: S-waiting-on-bors

#64320 Update version of `rustc-std-workspace-*` crates
  Cargo.lock
  src/tools/rustc-std-workspace-alloc/Cargo.toml
  src/tools/rustc-std-workspace-core/Cargo.toml
  src/tools/rustc-std-workspace-std/Cargo.toml
Labels: S-waiting-on-bors

#64323 Always show backtrace on Fuchsia
  src/libstd/sys_common/backtrace.rs
Labels: S-waiting-on-bors

#64329 Switch rustdoc logging to RUSTDOC_LOG
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#63989 Add Yaah to clippy toolstain notification list
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#64256 test/c-variadic: Fix patterns on powerpc64
  src/test/codegen/c-variadic.rs
Labels: S-waiting-on-bors

#64292 lowering: extend temporary lifetimes around await
  src/librustc/hir/lowering/expr.rs
  src/test/ui/async-await/async-fn-nonsend.stderr
  src/test/ui/async-await/issue-63832-await-short-temporary-lifetime-1.rs
  src/test/ui/async-await/issue-63832-await-short-temporary-lifetime.rs
Labels: A-async-await, F-async_await, S-waiting-on-bors

#64311 lldb: avoid mixing "Hit breakpoint" message with other output.
  src/etc/lldb_batchmode.py
Labels: S-waiting-on-bors

#64330 Clarify E0507 to note Fn/FnMut relationship to borrowing
  src/librustc_mir/error_codes.rs
Labels: S-waiting-on-bors

#64331 Changed instant is earlier to instant is later
  src/libstd/time.rs
Labels: S-waiting-on-bors

#64344 rustc_mir: buffer -Zdump-mir output instead of pestering the kernel constantly.
  src/librustc_mir/util/pretty.rs
Labels: S-waiting-on-bors

#64060 Improve hygiene of `alloc::format!`
  src/liballoc/lib.rs
  src/liballoc/macros.rs
Labels: S-waiting-on-bors

#64072 Replace file_stem by file_name in rustdoc markdown
  src/librustdoc/markdown.rs
Labels: S-waiting-on-bors, T-rustdoc

#64129 vxWorks: set DEFAULT_MIN_STACK_SIZE to 256K and use min_stack to pass initial stack size to rtpSpawn
  src/libstd/sys/vxworks/fast_thread_local.rs
  src/libstd/sys/vxworks/process/process_vxworks.rs
  src/libstd/sys/vxworks/thread.rs
Labels: S-waiting-on-bors

#64188 rustc: Allow the cdylib crate type with wasm32-wasi
  src/librustc_target/spec/wasm32_wasi.rs
Labels: S-waiting-on-author

#64326 Fixed documentation within c_str::from_ptr
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors

#64349 documentation for AtomicPtr CAS operations
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#64154 std: Add a `backtrace` module
  src/libstd/backtrace.rs
  src/libstd/error.rs
  src/libstd/lib.rs
  src/libstd/sys_common/backtrace.rs
  src/test/ui/std-backtrace.rs
Labels: S-waiting-on-bors, merged-by-bors

#64334 Add i686-unknown-uefi target
  src/librustc_target/spec/i686_unknown_uefi.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors, relnotes

#64080 Be accurate on `format!` parse error expectations
  src/libsyntax_ext/format.rs
  src/test/ui/codemap_tests/bad-format-args.rs
  src/test/ui/codemap_tests/bad-format-args.stderr
  src/test/ui/type/ascription/issue-54516.rs
  src/test/ui/type/ascription/issue-54516.stderr
Labels: S-waiting-on-bors, merged-by-bors

#64425 typo fix
  src/librustc/hir/mod.rs
Labels: S-waiting-on-bors

#64423 Add self to .mailmap
  .mailmap
Labels: S-waiting-on-bors

#64420 Inline `mark_neighbours_as_waiting_from`.
  src/librustc_data_structures/obligation_forest/mod.rs
Labels: S-waiting-on-bors

#64422 Remove raw string literal quotes from error index descriptions
  src/tools/error_index_generator/build.rs
Labels: S-waiting-on-bors

#64393 declare EnvKey before use to fix build error
  src/libstd/sys/vxworks/process/mod.rs
  src/libstd/sys/vxworks/process/process_common.rs
Labels: S-waiting-on-bors

#64384 Trim rustc-workspace-hack
  Cargo.lock
  src/tools/rustc-workspace-hack/Cargo.toml
Labels: S-waiting-on-bors

#64378 Fix inconsistent link formatting.
  src/libstd/io/stdio.rs
Labels: S-waiting-on-bors

#64375 Fast path for vec.clear/truncate
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#64372 use randSecure and randABytes
  src/libstd/sys/vxworks/rand.rs
Labels: S-waiting-on-bors

#64374 Box `DiagnosticBuilder`.
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_errors/diagnostic_builder.rs
  src/librustc_errors/emitter.rs
  src/libsyntax/parse/mod.rs
Labels: S-waiting-on-bors

#63846 Added table containing the system calls used by Instant and SystemTime.
  src/libstd/time.rs
Labels: S-waiting-on-bors

#64406 Ban non-extern rust intrinsics
  src/librustc_typeck/check/mod.rs
  src/test/incremental/hashes/function_interfaces.rs
  src/test/incremental/hashes/trait_defs.rs
  src/test/ui/feature-gates/feature-gate-abi.rs
  src/test/ui/feature-gates/feature-gate-abi.stderr
  src/test/ui/feature-gates/feature-gate-intrinsics.rs
  src/test/ui/feature-gates/feature-gate-intrinsics.stderr
  src/test/ui/intrinsics-always-extern.rs
  src/test/ui/intrinsics-always-extern.stderr
Labels: S-waiting-on-bors

#64290 Provide a span if main function is not present in crate
  src/librustc/middle/entry.rs
  src/test/ui-fulldeps/hash-stable-is-unstable.rs
  src/test/ui-fulldeps/hash-stable-is-unstable.stderr
  src/test/ui/associated-type-bounds/inside-adt.rs
  src/test/ui/associated-type-bounds/inside-adt.stderr
  src/test/ui/conditional-compilation/cfg-attr-cfg-2.stderr
  src/test/ui/conditional-compilation/cfg-in-crate-1.stderr
  src/test/ui/continue-after-missing-main.nll.stderr
  src/test/ui/continue-after-missing-main.stderr
  src/test/ui/elided-test.stderr
  src/test/ui/error-codes/E0138.stderr
  src/test/ui/error-codes/E0601.rs
  src/test/ui/error-codes/E0601.stderr
  src/test/ui/issues/issue-46101.rs
  src/test/ui/issues/issue-46101.stderr
  src/test/ui/issues/issue-49040.rs
  src/test/ui/issues/issue-49040.stderr
  src/test/ui/issues/issue-60057.rs
  src/test/ui/issues/issue-60057.stderr
  src/test/ui/json-short.stderr
  src/test/ui/lifetime-before-type-params.rs
  src/test/ui/lifetime-before-type-params.stderr
  src/test/ui/main-wrong-location.rs
  src/test/ui/main-wrong-location.stderr
  src/test/ui/missing/missing-main.stderr
  src/test/ui/parser-recovery-1.rs
  src/test/ui/parser-recovery-1.stderr
  src/test/ui/parser/issue-2354.rs
  src/test/ui/parser/issue-2354.stderr
  src/test/ui/parser/lex-bad-char-literals-2.rs
  src/test/ui/parser/lex-bad-char-literals-2.stderr
  src/test/ui/parser/unclosed-delimiter-in-dep.stderr
  src/test/ui/parser/unclosed_delim_mod.rs
  src/test/ui/parser/unclosed_delim_mod.stderr
  src/test/ui/resolve/visibility-indeterminate.rs
  src/test/ui/resolve/visibility-indeterminate.stderr
  src/test/ui/tool-attributes/diagnostic_item.rs
  src/test/ui/tool-attributes/diagnostic_item.stderr
  src/test/ui/type-alias-impl-trait/issue-60564.rs
  src/test/ui/type-alias-impl-trait/issue-60564.stderr
  src/test/ui/type/ascription/issue-34255-1.rs
  src/test/ui/type/ascription/issue-34255-1.stderr
Labels: S-waiting-on-bors

#61797 Stabilise weak_ptr_eq
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#64473 Use try_fold instead of manually carrying an accumulator
  src/librustc_mir/interpret/operand.rs
Labels: S-waiting-on-bors

#64475 simplify the initialization
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#64471 Warn on no_start, crate_id attribute use
  src/librustc_lint/builtin.rs
  src/test/ui/attributes/item-attributes.rs
  src/test/ui/feature-gate/issue-43106-gating-of-builtin-attrs.rs
  src/test/ui/feature-gate/issue-43106-gating-of-builtin-attrs.stderr
  src/test/ui/issues/issue-1251.rs
  src/test/ui/issues/issue-6919.rs
Labels: S-waiting-on-bors

#64463 resolve: Tweak some expected/found wording
  src/librustc_resolve/macros.rs
  src/test/ui/issues/issue-49934-errors.rs
  src/test/ui/issues/issue-49934-errors.stderr
Labels: S-waiting-on-bors

#64474 Permit impls referencing errors to overlap
  src/librustc/ty/mod.rs
  src/test/ui/coherence/conflicting-impl-with-err.rs
  src/test/ui/coherence/conflicting-impl-with-err.stderr
Labels: S-waiting-on-bors, merged-by-bors

#64472 Don't mark expression with attributes as not needing parentheses
  src/librustc_lint/unused.rs
  src/test/ui/lint/issue-54538-unused-parens-lint.rs
  src/test/ui/lint/issue-54538-unused-parens-lint.stderr
Labels: S-waiting-on-bors

#63872 Document platform-specific behavior of the iterator returned by std::fs::read_dir
  src/libstd/fs.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#64383 Improve BTreeSet::Intersection::size_hint
  src/liballoc/collections/btree/set.rs
  src/liballoc/tests/btree/set.rs
Labels: S-waiting-on-bors, merged-by-bors

#64381 Upgrade parking_lot and tempfile rustc dependencies
  Cargo.lock
  src/librustc/Cargo.toml
  src/librustc_codegen_ssa/Cargo.toml
  src/librustc_data_structures/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#64504 use println!() instead of println!("")
  src/librustc_codegen_llvm/lib.rs
  src/libstd/process.rs
  src/test/debuginfo/function-arg-initialization.rs
  src/test/ui/drop/dropck_legal_cycles.rs
  src/test/ui/for/for-c-in-str.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#64499 Use `Symbol` in two more functions.
  src/libsyntax/ext/tt/macro_rules.rs
Labels: S-waiting-on-bors

#64497 Don't print the "total" `-Ztime-passes` output if `--prints=...` is also given
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#64467 Hide diagnostics emitted during --cfg parsing
  src/librustc/session/config.rs
  src/test/ui/conditional-compilation/cfg-arg-invalid-6.rs
  src/test/ui/conditional-compilation/cfg-arg-invalid-6.stderr
Labels: S-waiting-on-bors

#64446 Fix build script sanitizer check.
  src/librustc_asan/build.rs
  src/librustc_lsan/build.rs
  src/librustc_msan/build.rs
  src/librustc_tsan/build.rs
Labels: S-waiting-on-bors

#64518 Use while let slice_pattern instead of carrying an index around
  src/librustc_mir/borrow_check/conflict_errors.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/build/matches/mod.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/util/alignment.rs
Labels: S-waiting-on-bors

#64509 Make some adjustments to the documentation for `std::convert::identity`
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#64357 `AdtDef` is an algebraic data type, not abstract data type
  src/librustc/ty/mod.rs
Labels: S-waiting-on-bors

#64530 Elide lifetimes in `Pin<&(mut) Self>`
  src/libcore/option.rs
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#64531 Use shorthand syntax in the self parameter of methods of Pin
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#64380 Update bundled OpenSSL to 1.1.1d
  Cargo.lock
Labels: S-waiting-on-bors

#64085 Tweak unsatisfied HRTB errors
  src/librustc/infer/error_reporting/nice_region_error/placeholder_error.rs
  src/test/ui/generator/auto-trait-regions.stderr
  src/test/ui/hrtb/due-to-where-clause.rs
  src/test/ui/hrtb/due-to-where-clause.stderr
  src/test/ui/hrtb/hrtb-cache-issue-54302.stderr
  src/test/ui/hrtb/issue-30786.migrate.stderr
  src/test/ui/hrtb/issue-30786.nll.stderr
  src/test/ui/hrtb/issue-30786.rs
  src/test/ui/issues/issue-54302-cases.stderr
  src/test/ui/issues/issue-54302.stderr
  src/test/ui/issues/issue-55731.stderr
Labels: S-waiting-on-bors

#64543 Revert #64451
  Cargo.lock
  src/bootstrap/dist.rs
  src/tools/build-manifest/Cargo.toml
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#64517 azure: Disable more LLVM/debug assertions in
  src/ci/azure-pipelines/auto.yml
  src/ci/docker/i686-gnu-nopt/Dockerfile
  src/ci/docker/i686-gnu/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#64541 document Miri error categories
  src/librustc/mir/interpret/error.rs
Labels: S-waiting-on-bors

#64544 build-manifest: re-add some comments
  src/bootstrap/dist.rs
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#64529 Add an example to Pin::as_mut
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#64502 avoid duplicate issues for Miri build failures
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#64505 Fix inconsistent link formatting
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#64436 improve Vec example soundness in mem::transmute docs
  src/libcore/intrinsics.rs
Labels: S-waiting-on-bors

#64429 Fix failure note `to_str` implementation
  src/librustc_errors/emitter.rs
  src/librustc_errors/lib.rs
  src/test/ui/json-short.stderr
  src/test/ui/lint/use_suggestion_json.stderr
Labels: S-waiting-on-bors

#64394 Shrink `SubregionOrigin`.
  src/librustc/infer/equate.rs
  src/librustc/infer/error_reporting/nice_region_error/placeholder_error.rs
  src/librustc/infer/error_reporting/note.rs
  src/librustc/infer/glb.rs
  src/librustc/infer/lub.rs
  src/librustc/infer/mod.rs
  src/librustc/infer/sub.rs
Labels: S-waiting-on-bors

#64283 Updated RELEASES.md for 1.38.0
  RELEASES.md
Labels: C-enhancement, S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#61626 Get rid of special const intrinsic query in favour of `const_eval`
  src/librustc/mir/interpret/error.rs
  src/librustc/query/mod.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/traits/intrinsic.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/interpret/intrinsics/type_name.rs
  src/librustc_mir/interpret/mod.rs
  src/librustc_mir/lib.rs
  src/test/compile-fail/issue-44415.rs
  src/test/ui/consts/const-size_of-cycle.stderr
  src/test/ui/issues/issue-44415.stderr
Labels: S-waiting-on-bors

#64528 Load proc macro metadata in the correct order.
  src/librustc_metadata/decoder.rs
  src/libsyntax_ext/proc_macro_harness.rs
  src/test/rustdoc/inline_cross/proc_macro.rs
Labels: S-waiting-on-bors

#64575 doc: Format some primitives examples
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#64578 Fix issue22656 with LLDB 8
  src/test/debuginfo/issue-22656.rs
Labels: S-waiting-on-bors

#64348 PR: documentation spin loop hint
  src/libcore/hint.rs
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#64207 Make rustc_mir::dataflow module pub (for clippy)
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/lib.rs
Labels: S-waiting-on-bors

#63630 Update installed compiler dependencies
  README.md
Labels: S-waiting-on-bors

#64613 rustbuild: Copy crate doc files fewer times
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors

#64606 Remove unnecessary `mut` in doc example
  src/libstd/process.rs
Labels: S-waiting-on-bors

#64611 rustbuild: Don't package libstd twice
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#64601 Fix backticks in documentation
  src/librustc/middle/region.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/libsyntax/source_map.rs
  src/test/ui/borrowck/two-phase-surprise-no-conflict.rs
Labels: S-waiting-on-bors

#64576 ci: split aws credentials in two separate users with scoped perms
  src/ci/azure-pipelines/auto.yml
  src/ci/azure-pipelines/master.yml
  src/ci/azure-pipelines/steps/run.yml
  src/ci/azure-pipelines/try.yml
Labels: S-waiting-on-bors, T-infra, beta-accepted, beta-nominated, merged-by-bors

#64553 azure: Convert Windows installations scripts to `bash`
  src/ci/azure-pipelines/steps/install-windows-build-deps.yml
Labels: S-waiting-on-bors, merged-by-bors

#64642 Fix the span used to suggest avoiding for-loop moves
  src/librustc_mir/borrow_check/conflict_errors.rs
  src/test/ui/issues/issue-64559.rs
  src/test/ui/issues/issue-64559.stderr
Labels: S-waiting-on-bors

#64641 Exempt extern "Rust" from improper_ctypes
  src/liballoc/alloc.rs
  src/libcore/panicking.rs
  src/librustc_lint/types.rs
  src/test/ui/issues/issue-64593.rs
Labels: S-waiting-on-bors

#64632 remove the extra comma after the match arm
  src/librustc_resolve/late/diagnostics.rs
Labels: S-waiting-on-bors
