Repository rust-lang/rust, pull requests merged in 2019-03, with the labels that each got.

#58689 Add unstable option to ignore should_panic tests
  src/libtest/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#58077 Add debug-info to access variables from generator state
  src/librustc_codegen_ssa/mir/mod.rs
  src/test/debuginfo/generators.rs
Labels: S-waiting-on-bors, merged-by-bors

#58464 Use the correct stderr when testing libstd
  src/libstd/io/impls.rs
  src/libstd/io/stdio.rs
  src/libstd/lib.rs
  src/libstd/panicking.rs
Labels: S-waiting-on-bors, merged-by-bors

#58780 ManuallyDrop != MaybeUninit
  src/libcore/mem.rs
Labels: S-waiting-on-bors

#58782 Replace `s` with `self` in docs for str methods taking self.
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#58785 allow specifying attributes for tool lints
  src/librustc/lint/mod.rs
  src/test/ui-fulldeps/auxiliary/lint_tool_test.rs
Labels: S-waiting-on-bors

#58802 Ensure `record_layout_for_printing()` is inlined.
  src/librustc/ty/layout.rs
Labels: S-waiting-on-bors

#58821 Fixed a syntax error in the pin docs
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#58830 tidy: deny(rust_2018_idioms)
  src/tools/tidy/src/deps.rs
  src/tools/tidy/src/features.rs
  src/tools/tidy/src/lib.rs
Labels: S-waiting-on-bors

#58832 Revert switching to GCP on AppVeyor
  appveyor.yml
Labels: S-waiting-on-bors

#58833 tools/rustbook: deny(rust_2018_idioms)
  src/tools/rustbook/src/main.rs
Labels: S-waiting-on-bors

#58835 tools/remote-test-{client,server}: deny(rust_2018_idioms)
  src/tools/remote-test-client/src/main.rs
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors

#58838 Fix typo in Vec#resize_with documentation
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#58842 Forbid duplicating Cargo as a dependency
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors

#58852 Update toolchain to build NetBSD release
  src/ci/docker/dist-x86_64-netbsd/Dockerfile
  src/ci/docker/dist-x86_64-netbsd/build-netbsd-toolchain.sh
Labels: S-waiting-on-bors

#58423 Relax Read bounds on a bunch of BufReader<R> methods
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, final-comment-period, merged-by-bors, relnotes

#58985 Fix segfaults in release build C-variadic fns
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/mir/mod.rs
  src/test/codegen/c-variadic-opt.rs
Labels: S-waiting-on-bors, merged-by-bors

#58080 Add FreeBSD armv6 and armv7 targets
  src/bootstrap/bootstrap.py
  src/librustc_target/spec/armv6_unknown_freebsd.rs
  src/librustc_target/spec/armv7_unknown_freebsd.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors, T-compiler, relnotes

#58269 Add librustc and libsyntax to rust-src distribution.
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#58369 Make the Entry API of HashMap<K, V> Sync and Send
  src/libstd/collections/hash/map.rs
  src/test/run-pass/threads-sendsync/sync-send-iterators-in-libcollections.rs
Labels: S-waiting-on-bors

#58861 Expand where negative supertrait specific error is shown
  src/libsyntax/parse/parser.rs
  src/test/ui/issues/issue-58857.rs
  src/test/ui/issues/issue-58857.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#58877 Suggest removal of `&` when borrowing macro and appropriate
  src/librustc_typeck/check/demand.rs
  src/test/ui/block-result/issue-5500.stderr
  src/test/ui/diverging-tuple-parts-39485.stderr
  src/test/ui/suggestions/format-borrow.rs
  src/test/ui/suggestions/format-borrow.stderr
Labels: S-waiting-on-bors

#58883 Suggest appropriate code for unused field when destructuring pattern
  src/librustc/middle/liveness.rs
  src/test/ui/suggestions/unused-closure-argument.rs
  src/test/ui/suggestions/unused-closure-argument.stderr
Labels: S-waiting-on-bors

#58891 Remove stray ` in the docs for the FromIterator implementation for Option
  src/libcore/option.rs
Labels: S-waiting-on-bors

#58893 race condition in thread local storage example
  src/libstd/thread/local.rs
Labels: S-waiting-on-bors

#58906 Monomorphize generator field types for debuginfo
  src/librustc_codegen_ssa/mir/mod.rs
  src/test/run-pass/generator/issue-58888.rs
Labels: S-waiting-on-bors

#58911 Regression test for #58435.
  src/test/run-pass/issues/issue-58435-ice-with-assoc-const.rs
Labels: S-waiting-on-bors, T-compiler

#58912 Regression test for #58813
  src/test/incremental/cyclic-trait-hierarchy.rs
Labels: S-waiting-on-bors

#58916 Fix release note problems noticed after merging.
  RELEASES.md
Labels: S-waiting-on-bors

#58918 Regression test added for an async ICE.
  src/test/run-pass/generator/issue-57084.rs
Labels: S-waiting-on-bors

#58921 Add an explicit test for issue #50582
  src/test/ui/issues/issue-50582.rs
  src/test/ui/issues/issue-50582.stderr
Labels: S-waiting-on-bors

#58926 Make the lifetime parameters of tcx consistent.
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/traits/backend.rs
Labels: S-waiting-on-bors

#58931 Elide invalid method receiver error when it contains TyErr
  src/librustc_typeck/check/wfcheck.rs
  src/test/ui/issues/issue-58712.rs
  src/test/ui/issues/issue-58712.stderr
Labels: S-waiting-on-bors

#58940 Remove JSBackend from config.toml
  config.toml.example
Labels: S-waiting-on-bors

#58950 Add self to mailmap
  .mailmap
Labels: S-waiting-on-bors

#58961 On incorrect cfg literal/identifier, point at the right span
  src/libsyntax/parse/attr.rs
  src/test/ui/conditional-compilation/cfg-attr-syntax-validation.rs
  src/test/ui/conditional-compilation/cfg-attr-syntax-validation.stderr
Labels: S-waiting-on-bors

#58963 libstd: implement Error::source for io::Error
  src/libstd/io/error.rs
Labels: S-waiting-on-bors

#59007 Add a test for invalid const arguments
  src/test/ui/const-generics/invalid-constant-in-args.rs
  src/test/ui/const-generics/invalid-constant-in-args.stderr
Labels: S-waiting-on-bors

#57882 overhaul unused doc comments lint
  src/libcore/num/mod.rs
  src/librustc/hir/mod.rs
  src/librustc/middle/region.rs
  src/librustc/ty/context.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/sty.rs
  src/librustc_data_structures/indexed_vec.rs
  src/librustc_lint/builtin.rs
  src/librustc_lint/lib.rs
  src/librustc_mir/borrow_check/nll/region_infer/values.rs
  src/librustc_mir/dataflow/move_paths/mod.rs
  src/libstd/io/stdio.rs
  src/test/ui/useless_comment.rs
  src/test/ui/useless_comment.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58518 Use early unwraps instead of bubbling up errors just to unwrap in the end
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
Labels: S-waiting-on-bors

#58629 rust-lldb: fix crash when printing empty string
  src/etc/lldb_rust_formatters.py
  src/test/debuginfo/empty-string.rs
Labels: S-waiting-on-bors

#58670 fixes rust-lang#52482
  src/librustc/ty/context.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_passes/rvalue_promotion.rs
  src/librustc_typeck/check/cast.rs
  src/librustc_typeck/check/writeback.rs
Labels: S-waiting-on-bors

#58676 look for python2 symlinks before bootstrap python
  config.toml.example
  src/bootstrap/sanity.rs
Labels: S-waiting-on-bors

#58924 Add as_slice() to slice::IterMut and vec::Drain
  src/liballoc/vec.rs
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#58990 Actually publish miri in the manifest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#59018 std: Delete a by-definition spuriously failing test
  src/libstd/net/tcp.rs
Labels: S-waiting-on-bors

#59045 Expose new_sub_parser_from_file
  src/libsyntax/parse/mod.rs
Labels: S-waiting-on-bors

#58498 use structured suggestions for E0432
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/librustc_resolve/resolve_imports.rs
  src/test/ui/extenv/issue-55897.stderr
  src/test/ui/import.rs
  src/test/ui/import.stderr
  src/test/ui/imports/issue-55457.stderr
  src/test/ui/inaccessible-test-modules.stderr
  src/test/ui/issues/issue-31212.stderr
  src/test/ui/issues/issue-8208.rs
  src/test/ui/issues/issue-8208.stderr
  src/test/ui/resolve_self_super_hint.rs
  src/test/ui/resolve_self_super_hint.stderr
  src/test/ui/rust-2018/issue-54006.stderr
  src/test/ui/rust-2018/local-path-suggestions-2015.stderr
  src/test/ui/rust-2018/local-path-suggestions-2018.stderr
  src/test/ui/unresolved/unresolved-import.rs
  src/test/ui/unresolved/unresolved-import.stderr
  src/test/ui/use/use-nested-groups-error.stderr
Labels: S-waiting-on-bors, merged-by-bors

#56732 Make the rustc driver and interface demand driven
  src/librustc/ich/impls_ty.rs
  src/librustc/session/config.rs
  src/librustc/session/mod.rs
  src/librustc/ty/context.rs
  src/librustc/ty/mod.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_utils/codegen_backend.rs
  src/librustc_data_structures/box_region.rs
  src/librustc_data_structures/lib.rs
  src/librustc_driver/driver.rs
  src/librustc_driver/lib.rs
  src/librustc_driver/pretty.rs
  src/librustc_driver/test.rs
  src/librustc_incremental/lib.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_incremental/persist/mod.rs
  src/librustc_interface/interface.rs
  src/librustc_interface/lib.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/queries.rs
  src/librustc_interface/util.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/def_ctor.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/simplify.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/librustdoc/markdown.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collapse_docs.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/private_items_doc_tests.rs
  src/librustdoc/passes/propagate_doc_cfg.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/passes/strip_priv_imports.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/passes/unindent_comments.rs
  src/librustdoc/test.rs
  src/librustdoc/visit_ast.rs
  src/librustdoc/visit_lib.rs
  src/rustc/rustc.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
  src/test/run-make-fulldeps/issue-19371/foo.rs
  src/test/run-pass-fulldeps/compiler-calls.rs
  src/test/rustdoc-ui/deny-intra-link-resolution-failure.stderr
  src/test/rustdoc-ui/deny-missing-docs-crate.stderr
  src/test/rustdoc-ui/deny-missing-docs-macro.stderr
  src/test/rustdoc-ui/doc-without-codeblock.stderr
  src/test/rustdoc-ui/failed-doctest-output.stdout
  src/test/rustdoc-ui/intra-doc-alias-ice.stderr
  src/test/rustdoc-ui/intra-link-span-ice-55723.stderr
  src/test/rustdoc-ui/lint-group.stderr
  src/test/rustdoc-ui/private-item-doc-test.stderr
  src/tools/rustdoc/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#59054 CI: Trim some tests from i686-gnu
  src/ci/docker/i686-gnu/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#58788 Make migrate mode work at item level granularity
  src/librustc/middle/expr_use_visitor.rs
  src/librustc_borrowck/borrowck/gather_loans/mod.rs
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/borrowck/issue-58776-borrowck-scans-children.ast.stderr
  src/test/ui/borrowck/issue-58776-borrowck-scans-children.migrate.stderr
  src/test/ui/borrowck/issue-58776-borrowck-scans-children.nll.stderr
  src/test/ui/borrowck/issue-58776-borrowck-scans-children.rs
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated, merged-by-bors

#58021 Fix fallout from #57667
  src/libsyntax/ptr.rs
Labels: S-waiting-on-bors, beta-nominated, merged-by-bors

#58829 librustc_interface: Update scoped-tls to 1.0
  Cargo.lock
  src/librustc_interface/Cargo.toml
Labels: S-waiting-on-bors

#58876 Parse lifetimes that start with a number and give specific error
  src/libsyntax/parse/lexer/mod.rs
  src/test/ui/parser/numeric-lifetime.rs
  src/test/ui/parser/numeric-lifetime.stderr
Labels: S-waiting-on-bors

#58908 Update rand version
  Cargo.lock
  src/librustc_incremental/Cargo.toml
Labels: S-waiting-on-bors

#58998 Fix documentation of from_ne_bytes and from_le_bytes
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#59056 Use lifetime contravariance to elide more lifetimes in core+alloc+std
  src/liballoc/boxed.rs
  src/liballoc/rc.rs
  src/liballoc/string.rs
  src/liballoc/vec.rs
  src/libcore/array.rs
  src/libcore/cmp.rs
  src/libcore/internal_macros.rs
  src/libcore/ptr.rs
  src/libstd/collections/hash/set.rs
  src/libstd/error.rs
  src/libstd/ffi/c_str.rs
  src/libstd/ffi/os_str.rs
  src/libstd/path.rs
  src/libstd/sys/cloudabi/shims/net.rs
  src/libstd/sys/redox/net/mod.rs
  src/libstd/sys/sgx/net.rs
  src/libstd/sys/unix/l4re.rs
  src/libstd/sys/wasm/net.rs
  src/libstd/sys_common/net.rs
Labels: S-waiting-on-bors, T-libs

#59057 Standardize `Range*` documentation
  src/libcore/ops/range.rs
Labels: S-waiting-on-bors

#59080 Fix incorrect links in librustc_codegen_llvm documentation
  src/librustc_codegen_llvm/debuginfo/doc.rs
Labels: S-waiting-on-bors

#59093 Remove precompute_in_scope_traits_hashes
  src/librustc/ty/context.rs
  src/librustc_incremental/persist/load.rs
Labels: S-waiting-on-bors

#59101 Reduces Code Repetitions like `!n >> amt`
  src/librustc/mir/interpret/mod.rs
Labels: S-waiting-on-bors

#59121 impl FromIterator for Result: Use assert_eq! instead of assert!
  src/libcore/result.rs
Labels: S-waiting-on-bors

#59129 Visit impl Trait for dead_code lint
  src/librustc/middle/dead.rs
  src/test/ui/lint/lint-dead-code-impl-trait.rs
  src/test/ui/lint/lint-dead-code-impl-trait.stderr
Labels: S-waiting-on-bors

#59130 Note that NonNull does not launder shared references for mutation
  src/libcore/ptr.rs
Labels: S-waiting-on-bors

#58349 resolve: Simplify import resolution for mixed 2015/2018 edition mode
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
  src/test/ui/editions/edition-imports-virtual-2015-ambiguity.rs
  src/test/ui/editions/edition-imports-virtual-2015-ambiguity.stderr
  src/test/ui/editions/edition-imports-virtual-2015-gated.rs
  src/test/ui/editions/edition-imports-virtual-2015-gated.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58488 Replace TimeLine LLVM profiling with the self profiler
  src/librustc/lib.rs
  src/librustc/util/profiling.rs
  src/librustc/util/time_graph.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/back/lto.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_codegen_ssa/traits/write.rs
  src/librustc_interface/passes.rs
  src/librustc_typeck/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#58855 std: Spin for a global malloc lock on wasm32
  src/libstd/sys/wasm/alloc.rs
Labels: S-waiting-on-bors

#58873 Fix "Auto-hide item methods documentation" setting
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#58938 core: ensure VaList passes improper_ctypes lint
  src/libcore/ffi.rs
Labels: S-waiting-on-bors

#58941 MIPS: add r6 support
  src/librustc_target/spec/mipsisa32r6_unknown_linux_gnu.rs
  src/librustc_target/spec/mipsisa32r6el_unknown_linux_gnu.rs
  src/librustc_target/spec/mipsisa64r6_unknown_linux_gnuabi64.rs
  src/librustc_target/spec/mipsisa64r6el_unknown_linux_gnuabi64.rs
  src/librustc_target/spec/mod.rs
  src/tools/build-manifest/src/main.rs
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors

#58949 SGX target: Expose thread id function in os module
  src/libstd/os/fortanix_sgx/mod.rs
  src/libstd/sys/sgx/abi/thread.rs
Labels: S-waiting-on-bors

#58959 Add release notes for PR #56243
  RELEASES.md
Labels: S-waiting-on-bors, beta-accepted, beta-nominated, stable-accepted, stable-nominated

#58976 Default to integrated `rust-lld` linker for UEFI targets
  src/librustc_target/spec/uefi_base.rs
Labels: S-waiting-on-bors

#59009 Fix SGX implementations of read/write_vectored.
  src/libstd/io/mod.rs
  src/libstd/sys/redox/net/tcp.rs
  src/libstd/sys/sgx/net.rs
Labels: S-waiting-on-bors

#59025 Fix generic argument lookup for Self
  src/librustc_typeck/check/mod.rs
  src/test/run-pass/issues/issue-57924.rs
Labels: S-waiting-on-bors

#59036 Fix ICE in MIR pretty printing
  src/librustc_mir/util/pretty.rs
  src/test/mir-opt/unusual-item-types.rs
Labels: S-waiting-on-bors

#59037 Avoid some common false positives in intra doc link checking
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: S-waiting-on-bors

#59079 add suggestions to invalid macro item error
  src/libsyntax/parse/parser.rs
  src/test/ui/issues/issue-10536.rs
  src/test/ui/issues/issue-10536.stderr
  src/test/ui/parser/macros-no-semicolon-items.rs
  src/test/ui/parser/macros-no-semicolon-items.stderr
Labels: S-waiting-on-bors

#59102 Consistent naming for duration_float methods and additional f32 methods
  src/libcore/time.rs
Labels: S-waiting-on-bors, T-libs

#59118 rustc: fix ICE when trait alias has bare Self
  src/librustc/hir/map/mod.rs
  src/test/ui/issues/issue-59029-1.rs
  src/test/ui/issues/issue-59029-1.stderr
  src/test/ui/issues/issue-59029-2.rs
Labels: S-waiting-on-bors

#59139 Unregress using scalar unions in constants.
  src/librustc_mir/const_eval.rs
  src/test/ui/consts/union_constant.rs
Labels: S-waiting-on-bors

#59146 Suggest return lifetime when there's only one named lifetime
  src/librustc/middle/resolve_lifetime.rs
  src/test/ui/suggestions/return-without-lifetime.rs
  src/test/ui/suggestions/return-without-lifetime.stderr
Labels: S-waiting-on-bors

#59147 Make std time tests more robust for platform differences
  src/libstd/time.rs
Labels: C-cleanup, S-waiting-on-bors, T-libs

#59152 Stabilize Range*::contains.
  src/libcore/ops/range.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_errors/lib.rs
  src/librustc_mir/lib.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#59156 [wg-async-await] Add regression test for #55809.
  src/test/run-pass/issue-55809.rs
Labels: S-waiting-on-bors

#59158 Revert "Don't generate minification variable if minification disabled"
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#59169 Add `-Z allow_features=...` flag
  src/librustc/session/config.rs
  src/librustc_interface/passes.rs
  src/libsyntax/config.rs
  src/libsyntax/diagnostic_list.rs
  src/libsyntax/feature_gate.rs
  src/test/ui/feature-gate/allow-features-empty.rs
  src/test/ui/feature-gate/allow-features-empty.stderr
  src/test/ui/feature-gate/allow-features.rs
  src/test/ui/feature-gate/allow-features.stderr
Labels: S-waiting-on-bors

#59173 bootstrap: Default to a sensible llvm-suffix.
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#59180 Use try blocks in rustc_codegen_ssa
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_codegen_ssa/lib.rs
Labels: S-waiting-on-bors

#59185 No old chestnuts in iter::repeat docs
  src/libcore/iter/sources.rs
Labels: S-waiting-on-bors

#59201 Remove restriction on isize/usize in repr(simd)
  src/librustc/ty/sty.rs
  src/test/run-pass/simd/simd-size-align.rs
  src/test/ui/simd-type.rs
  src/test/ui/simd-type.stderr
Labels: S-waiting-on-bors

#59204 Output diagnostic information for rustdoc
  src/bootstrap/bin/rustdoc.rs
Labels: S-waiting-on-bors

#59212 Add x86_64 musl host to the manifest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#59221 Option and Result: Add references to documentation of as_ref and as_mut
  src/libcore/option.rs
  src/libcore/result.rs
Labels: S-waiting-on-bors

#59231 Stabilize Option::copied
  src/libcore/option.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#59178 Revert the `LazyConst` PR
  src/librustc/mir/interpret/value.rs
  src/librustc/mir/mod.rs
  src/librustc/mir/visit.rs
  src/librustc/traits/project.rs
  src/librustc/traits/query/normalize.rs
  src/librustc/ty/codec.rs
  src/librustc/ty/context.rs
  src/librustc/ty/error.rs
  src/librustc/ty/flags.rs
  src/librustc/ty/fold.rs
  src/librustc/ty/inhabitedness/mod.rs
  src/librustc/ty/mod.rs
  src/librustc/ty/print/pretty.rs
  src/librustc/ty/relate.rs
  src/librustc/ty/structural_impls.rs
  src/librustc/ty/sty.rs
  src/librustc/ty/subst.rs
  src/librustc/ty/util.rs
  src/librustc/ty/walk.rs
  src/librustc/ty/wf.rs
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_codegen_ssa/mir/operand.rs
  src/librustc_mir/borrow_check/error_reporting.rs
  src/librustc_mir/borrow_check/mutability_errors.rs
  src/librustc_mir/borrow_check/nll/renumber.rs
  src/librustc_mir/borrow_check/nll/type_check/mod.rs
  src/librustc_mir/build/expr/as_rvalue.rs
  src/librustc_mir/build/matches/test.rs
  src/librustc_mir/build/misc.rs
  src/librustc_mir/build/mod.rs
  src/librustc_mir/const_eval.rs
  src/librustc_mir/hair/cx/expr.rs
  src/librustc_mir/hair/cx/mod.rs
  src/librustc_mir/hair/mod.rs
  src/librustc_mir/hair/pattern/_match.rs
  src/librustc_mir/hair/pattern/mod.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/monomorphize/item.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/erase_regions.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/qualify_consts.rs
  src/librustc_mir/transform/simplify_branches.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_traits/chalk_context/mod.rs
  src/librustc_traits/chalk_context/program_clauses.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/constrained_type_params.rs
  src/librustc_typeck/variance/constraints.rs
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#59047 resolve: Account for new importable entities
  src/librustc_resolve/build_reduced_graph.rs
  src/test/ui/rust-2018/uniform-paths/auxiliary/cross-crate.rs
  src/test/ui/rust-2018/uniform-paths/cross-crate.rs
  src/test/ui/rust-2018/uniform-paths/cross-crate.stderr
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated, merged-by-bors

#58994 Hide deprecation warnings inside derive expansions
  src/librustc/lint/mod.rs
  src/librustc/middle/stability.rs
  src/test/ui/deprecation/derive_on_deprecated.rs
  src/test/ui/deprecation/derive_on_deprecated_forbidden.rs
Labels: S-waiting-on-bors, beta-nominated, merged-by-bors

#58872 Adds help message in error for invalid `impl for T` syntax
  src/libsyntax/parse/parser.rs
  src/test/ui/issues/issue-56031.rs
  src/test/ui/issues/issue-56031.stderr
Labels: S-waiting-on-bors, merged-by-bors

#56348 Add todo!() macro
  src/libcore/macros.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors, T-libs

#57729 extra testing of how NLL handles wildcard type `_`
  src/test/ui/nll/user-annotations/issue-55748-pat-types-constrain-bindings.rs
  src/test/ui/nll/user-annotations/issue-55748-pat-types-constrain-bindings.stderr
Labels: S-waiting-on-bors

#58812 Clarify distinction between floor() and trunc()
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#58939 Fix a tiny error in documentation of std::pin.
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#59252 add self to mailmap
  .mailmap
Labels: S-waiting-on-bors

#59275 Replaced self-reflective explicit types with clearer `Self` or `Self::…` in stdlib docs
  src/libcore/cmp.rs
  src/libcore/iter/mod.rs
  src/libcore/iter/traits/collect.rs
  src/libcore/iter/traits/exact_size.rs
  src/libcore/ops/arith.rs
  src/libcore/ops/bit.rs
  src/libcore/ops/deref.rs
  src/libcore/ops/index.rs
Labels: S-waiting-on-bors

#59280 Stabilize refcell_map_split feature
  src/libcore/cell.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#59290 Run branch cleanup after copy prop
  src/librustc_mir/transform/mod.rs
  src/test/mir-opt/simplify_match.rs
Labels: S-waiting-on-bors

#59055 CI: Set job names.
  .travis.yml
  appveyor.yml
Labels: S-waiting-on-bors, T-infra

#59253 Calculate Docker cache hash precisely from Dockerfile's dependencies
  src/ci/docker/run.sh
Labels: S-waiting-on-bors

#59257 Update CI configuration for building Redox libraries
  src/ci/docker/disabled/dist-x86_64-redox/Dockerfile
  src/ci/docker/dist-various-1/install-x86_64-redox.sh
Labels: S-waiting-on-author, T-infra, beta-nominated, stable-nominated

#58897 Rework how bootstrap tools are built
  src/bootstrap/builder.rs
  src/bootstrap/dist.rs
  src/bootstrap/doc.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors, merged-by-bors

#58913 Add new test case for possible bug in BufReader
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors, merged-by-bors

#58927 Add default keyword handling in rustdoc
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render.rs
  src/test/rustdoc/default_trait_method.rs
Labels: S-waiting-on-bors, merged-by-bors

#58948 hygiene: Fix identifier comparison in impl overlap check
  src/librustc_typeck/coherence/inherent_impls_overlap.rs
  src/test/ui/specialization/specialization-overlap-hygiene.rs
  src/test/ui/specialization/specialization-overlap-hygiene.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58981 Point at coercion reason for `if` expressions without else clause if caused by return type
  src/librustc_typeck/check/mod.rs
  src/test/ui/if/if-without-else-as-fn-expr.rs
  src/test/ui/if/if-without-else-as-fn-expr.stderr
  src/test/ui/if/if-without-else-result.stderr
  src/test/ui/issues/issue-4201.stderr
  src/test/ui/issues/issue-50577.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58995 Refactor tools/build-mainfest
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#59035 When encountering `||{}()`, suggest the likely intended `(||{})()`
  src/librustc_typeck/check/callee.rs
  src/test/ui/suggestions/suggest-on-bare-closure-call.rs
  src/test/ui/suggestions/suggest-on-bare-closure-call.stderr
Labels: S-waiting-on-bors, merged-by-bors

#58953 Unify OsString/OsStr for byte-based implementations
  src/libstd/sys/cloudabi/mod.rs
  src/libstd/sys/redox/ext/ffi.rs
  src/libstd/sys/redox/mod.rs
  src/libstd/sys/sgx/ext/ffi.rs
  src/libstd/sys/sgx/mod.rs
  src/libstd/sys/sgx/os_str.rs
  src/libstd/sys/unix/ext/ffi.rs
  src/libstd/sys/unix/mod.rs
  src/libstd/sys/unix/os_str.rs
  src/libstd/sys/wasm/mod.rs
  src/libstd/sys/wasm/os_str.rs
  src/libstd/sys_common/mod.rs
  src/libstd/sys_common/os_str_bytes.rs
Labels: S-waiting-on-bors, merged-by-bors

#59172 Update and clean up several parts of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#59236 Rename miri component to miri-preview
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#59273 some small HIR doc improvements
  src/librustc/hir/mod.rs
Labels: S-waiting-on-bors

#59291 Make Option<ThreadId> no larger than ThreadId, with NonZeroU64
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors

#59297 convert field/method confusion help to suggestions
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/confuse-field-and-method/issue-18343.stderr
  src/test/ui/confuse-field-and-method/issue-2392.stderr
  src/test/ui/confuse-field-and-method/issue-32128.stderr
  src/test/ui/confuse-field-and-method/issue-33784.stderr
Labels: S-waiting-on-bors

#59304 Move some bench tests back from libtest
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#59309 Add messages for different verbosity levels. Output copy actions.
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#59322 Tweak incorrect escaped char diagnostic
  src/libsyntax/parse/lexer/mod.rs
  src/libsyntax/parse/parser.rs
  src/test/ui/parser/byte-literals.stderr
  src/test/ui/parser/byte-string-literals.stderr
  src/test/ui/parser/issue-23620-invalid-escapes.stderr
  src/test/ui/parser/lex-bad-char-literals-1.stderr
  src/test/ui/parser/lex-bare-cr-string-literal-doc-comment.stderr
  src/test/ui/parser/pat-tuple-3.stderr
  src/test/ui/parser/trailing-carriage-return-in-string.stderr
  src/test/ui/parser/wrong-escape-of-curly-braces.stderr
Labels: S-waiting-on-bors

#59323 use suggestions for "enum instead of variant" error
  src/librustc_resolve/error_reporting.rs
  src/test/ui/did_you_mean/issue-43871-enum-instead-of-variant.rs
  src/test/ui/did_you_mean/issue-43871-enum-instead-of-variant.stderr
  src/test/ui/glob-resolve1.stderr
  src/test/ui/resolve/privacy-enum-ctor.stderr
Labels: S-waiting-on-bors

#59329 cleanup: Remove compile-fail-fulldeps directory again
  src/test/compile-fail-fulldeps/auxiliary/lint_group_plugin_test.rs
Labels: S-waiting-on-bors

#59347 Move one test from run-make-fulldeps to ui
  src/test/run-make-fulldeps/extern-prelude/Makefile
  src/test/run-make-fulldeps/extern-prelude/basic.rs
  src/test/run-make-fulldeps/extern-prelude/relative-only.rs
  src/test/run-make-fulldeps/extern-prelude/shadow-mod.rs
  src/test/run-make-fulldeps/extern-prelude/shadow-prelude.rs
  src/test/ui/auxiliary/extern-prelude-vec.rs
  src/test/ui/auxiliary/extern-prelude.rs
  src/test/ui/extern-prelude-fail.rs
  src/test/ui/extern-prelude-fail.stderr
  src/test/ui/extern-prelude.rs
Labels: S-waiting-on-bors

#59360 Add tracking issue number for `seek_convenience`
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#58929 Elide object safety errors on non-existent trait function
  src/librustc/session/mod.rs
  src/librustc/traits/error_reporting.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/issues/issue-58734.rs
  src/test/ui/issues/issue-58734.stderr
Labels: S-waiting-on-bors, merged-by-bors

#59096 middle: replace NodeId with HirId in AccessLevels
  src/librustc/middle/dead.rs
  src/librustc/middle/privacy.rs
  src/librustc/middle/reachable.rs
  src/librustc/middle/stability.rs
  src/librustc_lint/builtin.rs
  src/librustc_privacy/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors, merged-by-bors

#59213 Track changes to robots.txt
  src/doc/robots.txt
Labels: S-waiting-on-bors, T-release

#59239 Remove inline assembly from hint::spin_loop
  src/libcore/hint.rs
Labels: S-waiting-on-bors

#59251 Use a valid name for graphviz graphs
  src/librustc_driver/pretty.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/rustc_peek.rs
  src/librustc_mir/util/graphviz.rs
  src/librustc_mir/util/mod.rs
  src/test/mir-opt/graphviz.rs
Labels: S-waiting-on-bors

#59296 Do not encode gensymed imports in metadata
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/resolve_imports.rs
  src/libsyntax_pos/symbol.rs
  src/test/ui/imports/auxiliary/gensymed.rs
  src/test/ui/imports/gensymed.rs
Labels: S-waiting-on-bors

#59377 Correct minimum system LLVM version in tests
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/test/codegen/enum-debug-clike.rs
  src/test/codegen/enum-debug-niche-2.rs
  src/test/codegen/enum-debug-niche.rs
  src/test/codegen/enum-debug-tagged.rs
  src/test/debuginfo/borrowed-enum.rs
  src/test/debuginfo/generic-enum-with-different-disr-sizes.rs
  src/test/debuginfo/generic-struct-style-enum.rs
  src/test/debuginfo/generic-tuple-style-enum.rs
  src/test/debuginfo/recursive-struct.rs
  src/test/debuginfo/struct-style-enum.rs
  src/test/debuginfo/tuple-style-enum.rs
  src/test/debuginfo/unique-enum.rs
Labels: S-waiting-on-bors

#59240 use the identifier span for missing struct field
  src/librustc_typeck/check/_match.rs
  src/test/ui/issues/issue-17800.stderr
  src/test/ui/issues/issue-51102.stderr
  src/test/ui/issues/issue-52717.stderr
  src/test/ui/numeric/numeric-fields.stderr
  src/test/ui/structs/struct-field-cfg.stderr
Labels: S-waiting-on-bors, merged-by-bors

#59242 make asm diagnostic instruction optional
  src/librustc_codegen_llvm/llvm/diagnostic.rs
  src/test/ui/issues/issue-23458.rs
  src/test/ui/issues/issue-23458.stderr
Labels: S-waiting-on-bors, merged-by-bors

#59256 Make meta-item API compatible with `LocalInternedString::get` soundness fix
  src/librustc/hir/check_attr.rs
  src/librustc/lint/levels.rs
  src/librustc/lint/mod.rs
  src/librustc/middle/lib_features.rs
  src/librustc/middle/stability.rs
  src/librustc/traits/on_unimplemented.rs
  src/librustc_incremental/persist/dirty_clean.rs
  src/librustc_lint/builtin.rs
  src/librustc_lint/unused.rs
  src/librustc_passes/layout_test.rs
  src/librustc_plugin/load.rs
  src/librustdoc/core.rs
  src/librustdoc/html/render.rs
  src/libsyntax/attr/builtin.rs
  src/libsyntax/attr/mod.rs
  src/libsyntax/feature_gate.rs
  src/libsyntax_ext/deriving/generic/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#59258 filter suggestions from extern prelude
  src/librustc_resolve/lib.rs
  src/test/ui/proc-macro/resolve-error.stderr
  src/test/ui/suggestions/auxiliary/foo.rs
  src/test/ui/suggestions/no-extern-crate-in-type.rs
  src/test/ui/suggestions/no-extern-crate-in-type.stderr
Labels: S-waiting-on-bors, merged-by-bors

#59136 SGX target: fix std unit tests
  src/libstd/Cargo.toml
  src/libstd/env.rs
  src/libstd/fs.rs
  src/libstd/net/addr.rs
  src/libstd/net/tcp.rs
  src/libstd/net/test.rs
  src/libstd/net/udp.rs
  src/libstd/path.rs
  src/libstd/process.rs
  src/libstd/sync/condvar.rs
  src/libstd/sync/mpsc/mod.rs
  src/libstd/sys/sgx/abi/mod.rs
  src/libstd/sys/sgx/abi/panic.rs
  src/libstd/sys/sgx/abi/tls.rs
  src/libstd/sys/sgx/abi/usercalls/alloc.rs
  src/libstd/sys/sgx/alloc.rs
  src/libstd/sys/sgx/args.rs
  src/libstd/sys/sgx/condvar.rs
  src/libstd/sys/sgx/net.rs
  src/libstd/sys/sgx/os.rs
  src/libstd/sys/sgx/rwlock.rs
  src/libstd/sys/sgx/stack_overflow.rs
  src/libstd/sys/sgx/thread.rs
  src/libstd/sys/sgx/waitqueue.rs
  src/libstd/thread/local.rs
  src/libstd/thread/mod.rs
  src/tools/tidy/src/pal.rs
Labels: S-waiting-on-bors, merged-by-bors

#59334 Update build instructions in README.md
  README.md
Labels: S-waiting-on-bors

#59389 replace redundant note in deprecation warning
  src/librustc/middle/stability.rs
  src/test/ui/deprecation/atomic_initializers.stderr
  src/test/ui/deprecation/suggestion.fixed
  src/test/ui/deprecation/suggestion.rs
  src/test/ui/deprecation/suggestion.stderr
Labels: S-waiting-on-bors

#59410 Clarify `{Ord,f32,f64}::clamp` docs a little
  src/libcore/cmp.rs
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#59419 Utilize `?` instead of `return None`.
  src/libcore/num/flt2dec/mod.rs
  src/librustc/traits/util.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#59026 Fix moving text in search tabs headers
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#59197 Exclude old book redirect stubs from search engines
  src/bootstrap/doc.rs
  src/doc/redirect.inc
Labels: S-waiting-on-bors

#59330 Improve the documentation for std::convert (From, Into, AsRef and AsMut)
  src/libcore/convert.rs
Labels: S-waiting-on-bors

#59424 Fix code block display in portability element in dark theme
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors
