Repository rust-lang/rust, pull requests merged in 2020-09, with the labels that each got.

#75931 Suggest `if let x = y` when encountering `if x = y`
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/error-codes/E0070.stderr
  src/test/ui/issues/issue-13407.stderr
  src/test/ui/rfc-2497-if-let-chains/disallowed-positions.stderr
  src/test/ui/suggestions/if-let-typo.rs
  src/test/ui/suggestions/if-let-typo.stderr
  src/test/ui/type/type-check/assignment-expected-bool.stderr
  src/test/ui/type/type-check/assignment-in-if.stderr
Labels: A-diagnostics, A-suggestion-diagnostics, S-waiting-on-bors, merged-by-bors

#76186 Rollup of 12 pull requests
  Cargo.lock
  README.md
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_error_codes/src/error_codes/E0764.md
  compiler/rustc_error_codes/src/error_codes/E0769.md
  compiler/rustc_lexer/Cargo.toml
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_middle/src/ty/walk.rs
  compiler/rustc_mir/src/monomorphize/partitioning/mod.rs
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
  library/alloc/src/borrow.rs
  library/core/src/cmp.rs
  library/std/src/env.rs
  src/librustdoc/Cargo.toml
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/cfg/tests.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/highlight/tests.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/strip_private.rs
  src/test/ui/consts/const-ordering.rs
  src/test/ui/consts/cow-is-borrowed.rs
Labels: A-spurious, S-waiting-on-bors, merged-by-bors, rollup

#76178 Update expect-test to 1.0
  Cargo.lock
  compiler/rustc_lexer/Cargo.toml
  src/librustdoc/Cargo.toml
  src/librustdoc/html/highlight/tests.rs
Labels: S-waiting-on-bors

#76172 Revert #75463
  library/core/src/cmp.rs
  src/test/ui/consts/const-ordering.rs
Labels: S-waiting-on-bors

#76166 Make `StringReader` private
  compiler/rustc_parse/src/lexer/mod.rs
  src/librustdoc/passes/check_code_block_syntax.rs
Labels: S-waiting-on-bors, WG-parselib

#76163 README: Adjust Linux and macOS support platform and architecture
  README.md
Labels: S-waiting-on-bors

#76161 Remove notrust in rustc_middle
  compiler/rustc_middle/src/ty/walk.rs
Labels: S-waiting-on-bors

#76154 Fix rustdoc strings indentation
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/cfg/tests.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/strip_private.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#76139 Make `cow_is_borrowed` methods const
  library/alloc/src/borrow.rs
  src/test/ui/consts/cow-is-borrowed.rs
Labels: S-waiting-on-bors

#76103 Clean up E0769
  compiler/rustc_error_codes/src/error_codes/E0769.md
Labels: S-waiting-on-bors

#76068 Avoid StringReader when checking code blocks for syntax errors
  src/librustdoc/passes/check_code_block_syntax.rs
Labels: C-cleanup, S-waiting-on-review, T-rustdoc, WG-parselib

#76059 Clean up E0764
  compiler/rustc_error_codes/src/error_codes/E0764.md
Labels: S-waiting-on-bors, T-doc

#76003 Adds two source span utility functions used in source-based coverage
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
Labels: S-waiting-on-bors

#76002 Fix `-Z instrument-coverage` on MSVC
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_mir/src/monomorphize/partitioning/mod.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
Labels: S-waiting-on-bors

#75945 Use `env::func()`, not 'the function env::func' in docs for std::env
  library/std/src/env.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#76047 rename get_{ref, mut} to assume_init_{ref,mut} in Maybeuninit
  library/core/src/fmt/float.rs
  library/core/src/mem/maybe_uninit.rs
  library/std/src/io/util.rs
  library/std/src/lazy.rs
Labels: S-waiting-on-bors, merged-by-bors

#76071 Make to_immediate/from_immediate configurable by backends
  compiler/rustc_codegen_llvm/src/builder.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_codegen_ssa/src/mir/operand.rs
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_codegen_ssa/src/traits/builder.rs
Labels: S-waiting-on-author, merged-by-bors

#75529 Eliminate some other bound checks when index comes from an enum
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  src/test/codegen/enum-bounds-check-derived-idx.rs
  src/test/codegen/enum-bounds-check-issue-13926.rs
  src/test/codegen/enum-bounds-check.rs
Labels: S-waiting-on-bors, merged-by-bors

#76197 Move ninja requirements to a dynamic check, when actually building
  src/bootstrap/builder/tests.rs
  src/bootstrap/config.rs
  src/bootstrap/lib.rs
  src/bootstrap/native.rs
  src/bootstrap/sanity.rs
Labels: A-rustbuild, S-waiting-on-bors, T-infra, merged-by-bors

#74559 Stabilize deque_make_contiguous
  library/alloc/src/collections/vec_deque.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, relnotes, to-announce

#76010 Run cfg-stripping on generic parameters before invoking derive macros
  compiler/rustc_expand/src/config.rs
  src/test/ui/proc-macro/issue-75930-derive-cfg.rs
  src/test/ui/proc-macro/issue-75930-derive-cfg.stdout
Labels: S-waiting-on-bors, merged-by-bors

#76231 Rollup of 14 pull requests
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_pretty/src/pprust.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0773.md
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_lexer/src/lib.rs
  compiler/rustc_mir/src/util/mod.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir/src/util/spanview.rs
  compiler/rustc_parse/src/parser/stmt.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  library/core/src/clone.rs
  library/core/src/iter/mod.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/macros/mod.rs
  library/core/src/panic.rs
  library/std/src/lib.rs
  library/std/src/net/ip.rs
  library/std/src/primitive_docs.rs
  src/doc/rustc/src/codegen-options/index.md
  src/doc/rustdoc/src/lints.md
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/themes/ayu.css
  src/test/mir-opt/spanview-block.rs
  src/test/mir-opt/spanview-statement.rs
  src/test/mir-opt/spanview-terminator.rs
  src/test/mir-opt/spanview_block.main.mir_map.0.html
  src/test/mir-opt/spanview_statement.main.mir_map.0.html
  src/test/mir-opt/spanview_terminator.main.mir_map.0.html
  src/test/rustdoc/index-page.rs
  src/test/ui/consts/std/net/ipv6.rs
  src/test/ui/macros/duplicate-builtin.rs
  src/test/ui/macros/duplicate-builtin.stderr
  src/test/ui/macros/unknown-builtin.rs
  src/test/ui/macros/unknown-builtin.stderr
  src/test/ui/parser/shebang/shebang-doc-comment.rs
  src/test/ui/parser/shebang/shebang-doc-comment.stderr
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#76221 Clean up header in `iter` docs for `for` loops
  library/core/src/iter/mod.rs
Labels: S-waiting-on-bors, T-doc

#76218 lexer: Tiny improvement to shebang detection
  compiler/rustc_lexer/src/lib.rs
  src/test/ui/parser/shebang/shebang-doc-comment.rs
  src/test/ui/parser/shebang/shebang-doc-comment.stderr
Labels: S-waiting-on-bors

#76212 Document lint missing_doc_code_examples is nightly-only
  src/doc/rustdoc/src/lints.md
Labels: S-waiting-on-bors, T-doc, T-rustdoc

#76207 # Move to intra-doc links for library/core/src/clone.rs
  library/core/src/clone.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#76206 Make all methods of `std::net::Ipv6Addr` const
  library/std/src/lib.rs
  library/std/src/net/ip.rs
  src/test/ui/consts/std/net/ipv6.rs
Labels: A-const-fn, S-waiting-on-bors, T-libs

#76201 Move to intra-doc links for library/core/src/panic.rs
  library/core/src/panic.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#76158 Stabilise link-self-contained option
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_session/src/options.rs
  src/doc/rustc/src/codegen-options/index.md
Labels: S-waiting-on-bors, relnotes

#76143 Give a better error message for duplicate built-in macros
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0773.md
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  src/test/ui/macros/duplicate-builtin.rs
  src/test/ui/macros/duplicate-builtin.stderr
  src/test/ui/macros/unknown-builtin.rs
  src/test/ui/macros/unknown-builtin.stderr
Labels: A-diagnostics, A-macros, A-resolve, S-waiting-on-bors, T-compiler

#76132 Factor out StmtKind::MacCall fields into `MacCallStmt` struct
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_pretty/src/pprust.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_parse/src/parser/stmt.rs
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
Labels: S-waiting-on-bors

#76126 Use "Fira Sans" for crate list font
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/themes/ayu.css
  src/test/rustdoc/index-page.rs
Labels: S-waiting-on-bors, T-rustdoc

#76099 Add info about `!` and `impl Trait`
  library/std/src/primitive_docs.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#76088 Add more examples to lexicographic cmp on Iterators.
  library/core/src/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#76074 Add new `-Z dump-mir-spanview` option
  compiler/rustc_mir/src/util/mod.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir/src/util/spanview.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  src/test/mir-opt/spanview-block.rs
  src/test/mir-opt/spanview-statement.rs
  src/test/mir-opt/spanview-terminator.rs
  src/test/mir-opt/spanview_block.main.mir_map.0.html
  src/test/mir-opt/spanview_statement.main.mir_map.0.html
  src/test/mir-opt/spanview_terminator.main.mir_map.0.html
Labels: S-waiting-on-bors

#74880 Add trailing comma support to matches macro
  library/core/src/macros/mod.rs
Labels: S-waiting-on-bors, T-libs

#76170 Remove trivia tokens
  compiler/rustc_ast/src/token.rs
  compiler/rustc_ast_pretty/src/pprust.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_parse/src/lexer/tokentrees.rs
  compiler/rustc_parse/src/lexer/unicode_chars.rs
  compiler/rustc_parse/src/lib.rs
Labels: S-waiting-on-bors, T-compiler, WG-parselib, merged-by-bors

#76216 compiler: use `OnceCell` from std
  Cargo.lock
  compiler/rustc_data_structures/Cargo.toml
  compiler/rustc_data_structures/src/jobserver.rs
  compiler/rustc_driver/Cargo.toml
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_feature/Cargo.toml
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_feature/src/lib.rs
  compiler/rustc_hir/Cargo.toml
  compiler/rustc_hir/src/lang_items.rs
  compiler/rustc_hir/src/lib.rs
  compiler/rustc_hir/src/weak_lang_items.rs
  compiler/rustc_interface/Cargo.toml
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/util.rs
Labels: S-waiting-on-bors, merged-by-bors

#76241 flt2dec: properly handle uninitialized memory
  library/core/benches/num/flt2dec/strategy/dragon.rs
  library/core/benches/num/flt2dec/strategy/grisu.rs
  library/core/src/fmt/float.rs
  library/core/src/num/flt2dec/mod.rs
  library/core/src/num/flt2dec/strategy/dragon.rs
  library/core/src/num/flt2dec/strategy/grisu.rs
  library/core/tests/num/flt2dec/mod.rs
  library/core/tests/num/flt2dec/random.rs
Labels: S-waiting-on-bors, merged-by-bors

#75960 Improve docs for the `const` keyword
  library/std/src/keyword_docs.rs
Labels: S-waiting-on-bors, T-doc, merged-by-bors

#76160 Improve recovery on malformed format call
  compiler/rustc_builtin_macros/src/format.rs
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/codemap_tests/bad-format-args.rs
  src/test/ui/codemap_tests/bad-format-args.stderr
  src/test/ui/fmt/incorrect-first-separator.stderr
  src/test/ui/fmt/incorrect-separator.rs
  src/test/ui/fmt/incorrect-separator.stderr
  src/test/ui/macros/missing-comma.rs
  src/test/ui/macros/missing-comma.stderr
  src/test/ui/parser/unicode-quote-chars.rs
  src/test/ui/parser/unicode-quote-chars.stderr
  src/tools/clippy/tests/ui/issue-3145.rs
  src/tools/clippy/tests/ui/issue-3145.stderr
Labels: S-waiting-on-bors, merged-by-bors

#76233 Avoid rehashing Fingerprint as a map key
  compiler/rustc_data_structures/src/fingerprint.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_data_structures/src/unhash.rs
  compiler/rustc_middle/src/ty/context.rs
Labels: I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#76261 Use intra-doc links in `core::marker`
  library/core/src/marker.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#76245 inliner: Avoid query cycles when optimizing generators
  compiler/rustc_mir/src/transform/inline.rs
  src/test/mir-opt/inline/inline-async.rs
Labels: S-waiting-on-bors

#76242 Read: adjust a FIXME reference
  library/std/src/io/util.rs
Labels: S-waiting-on-bors

#76243 Fix typos in vec try_reserve(_exact) docs
  library/alloc/src/collections/vec_deque.rs
  library/alloc/src/vec.rs
Labels: S-waiting-on-bors

#76204 Rename and expose LoopState as ControlFlow
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/mod.rs
  library/core/src/iter/traits/double_ended.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/ops/control_flow.rs
  library/core/src/ops/mod.rs
Labels: S-waiting-on-bors, T-libs

#76164 Link to slice pattern in array docs
  library/std/src/primitive_docs.rs
Labels: S-waiting-on-bors

#76120 Add `[T; N]::as_[mut_]slice`
  library/core/src/array/mod.rs
  library/core/tests/lib.rs
  library/core/tests/option.rs
  library/core/tests/result.rs
Labels: S-waiting-on-bors

#75150 Add a note for Ipv4Addr::to_ipv6_compatible
  library/std/src/net/ip.rs
Labels: S-waiting-on-bors, T-libs

#75971 Applied `#![deny(unsafe_op_in_unsafe_fn)]` in library/std/src/wasi
  library/std/src/sys/wasi/alloc.rs
  library/std/src/sys/wasi/args.rs
  library/std/src/sys/wasi/ext/fs.rs
  library/std/src/sys/wasi/ext/io.rs
  library/std/src/sys/wasi/ext/mod.rs
  library/std/src/sys/wasi/fd.rs
  library/std/src/sys/wasi/fs.rs
  library/std/src/sys/wasi/io.rs
  library/std/src/sys/wasi/net.rs
  library/std/src/sys/wasi/os.rs
  library/std/src/sys/wasi/pipe.rs
  library/std/src/sys/wasi/process.rs
  library/std/src/sys/wasi/stdio.rs
  library/std/src/sys/wasi/thread.rs
  library/std/src/sys/wasi/time.rs
Labels: S-waiting-on-bors, merged-by-bors

#76235 Convert many files to intra-doc links
  library/alloc/src/boxed.rs
  library/alloc/src/rc.rs
  library/alloc/src/sync.rs
  library/core/src/pin.rs
  library/std/src/ascii.rs
  library/std/src/fs.rs
  library/std/src/net/addr.rs
  library/std/src/net/ip.rs
  library/std/src/prelude/mod.rs
  library/std/src/sys/unix/ext/fs.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc, merged-by-bors

#70793 specialize some collection and iterator operations to run in-place
  library/alloc/benches/vec.rs
  library/alloc/src/collections/binary_heap.rs
  library/alloc/src/lib.rs
  library/alloc/src/vec.rs
  library/alloc/tests/binary_heap.rs
  library/alloc/tests/lib.rs
  library/alloc/tests/slice.rs
  library/alloc/tests/vec.rs
  library/core/src/iter/adapters/fuse.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/adapters/zip.rs
  library/core/src/iter/mod.rs
  library/core/src/iter/traits/marker.rs
  library/core/src/iter/traits/mod.rs
  src/test/ui/iterators/issue-58952-filter-type-length.rs
Labels: S-waiting-on-bors, libs-impl, merged-by-bors

#76004 Tools, tests, and experimenting with MIR-derived coverage counters
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir/src/transform/instrument_coverage.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  src/test/mir-opt/instrument_coverage.bar.InstrumentCoverage.diff
  src/test/mir-opt/instrument_coverage.main.InstrumentCoverage.diff
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-base/Makefile
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-base/expected_export_coverage.coverage_of_if_else.json
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-base/prettify_json.py
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-base/typical_show_coverage.coverage_of_if_else.txt
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-link-dead-code/Makefile
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-link-dead-code/expected_export_coverage.coverage_of_if_else.json
  src/test/run-make-fulldeps/instrument-coverage-cov-reports-link-dead-code/typical_show_coverage.coverage_of_if_else.txt
  src/test/run-make-fulldeps/instrument-coverage-llvm-ir-base/Makefile
  src/test/run-make-fulldeps/instrument-coverage-llvm-ir-base/filecheck.testprog.txt
  src/test/run-make-fulldeps/instrument-coverage-llvm-ir-base/testprog.rs
  src/test/run-make-fulldeps/instrument-coverage-llvm-ir-link-dead-code/Makefile
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-base/Makefile
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-base/expected_mir_dump.coverage_of_if_else/coverage_of_if_else.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-link-dead-code/Makefile
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-link-dead-code/expected_mir_dump.coverage_of_if_else/coverage_of_if_else.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/instrument-coverage/Makefile
  src/test/run-make-fulldeps/instrument-coverage/compiletest-ignore-dir
  src/test/run-make-fulldeps/instrument-coverage/coverage_of_if_else.rs
  src/test/run-make-fulldeps/instrument-coverage/coverage_tools.mk
  src/test/run-make-fulldeps/instrument-coverage/expected_export_coverage.json
  src/test/run-make-fulldeps/instrument-coverage/filecheck-patterns.txt
  src/test/run-make-fulldeps/instrument-coverage/typical_show_coverage.txt
Labels: S-waiting-on-bors, merged-by-bors

#75207 Add `slice::check_range`
  library/alloc/src/collections/vec_deque.rs
  library/alloc/src/lib.rs
  library/alloc/src/string.rs
  library/alloc/src/vec.rs
  library/core/src/slice/mod.rs
  library/core/tests/slice.rs
  src/tools/linkchecker/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#75655 Disable zlib in LLVM on Haiku
  src/librustc_llvm/build.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#76315 add `#[track_caller]` to `local_def_id_to_hir_id`
  compiler/rustc_hir/src/definitions.rs
Labels: S-waiting-on-bors, merged-by-bors

#76292 Respect `-Z proc-macro-backtrace` flag for panics inside libproc_macro
  library/proc_macro/src/bridge/client.rs
  src/test/ui-fulldeps/auxiliary/proc-macro-panic.rs
  src/test/ui-fulldeps/issue-76270-panic-in-libproc-macro.rs
  src/test/ui-fulldeps/issue-76270-panic-in-libproc-macro.stderr
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#75200 BTreeMap: introduce marker::ValMut and reserve Mut for unique access
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, merged-by-bors

#75173 Upgrade Chalk to 0.21
  Cargo.lock
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/traits/chalk.rs
  compiler/rustc_traits/Cargo.toml
  compiler/rustc_traits/src/chalk/db.rs
  compiler/rustc_traits/src/chalk/lowering.rs
  compiler/rustc_traits/src/chalk/mod.rs
  src/test/ui/chalkify/type_inference.rs
  src/test/ui/chalkify/type_inference.stderr
  src/test/ui/chalkify/type_wf.rs
  src/test/ui/chalkify/type_wf.stderr
Labels: S-waiting-on-bors, merged-by-bors

#75888 Add check for doc alias on assoc const in trait impl
  compiler/rustc_passes/src/check_attr.rs
  src/test/rustdoc-ui/doc-alias-assoc-const.rs
  src/test/rustdoc-ui/doc-alias-assoc-const.stderr
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#75584 do not apply DerefMut on union field
  compiler/rustc_typeck/src/check/place_op.rs
  src/test/ui/union/union-deref.rs
  src/test/ui/union/union-deref.stderr
Labels: S-waiting-on-bors, merged-by-bors

#76376 Rollup of 11 pull requests
  Cargo.lock
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/mir/interpret/allocation.rs
  compiler/rustc_middle/src/mir/interpret/mod.rs
  compiler/rustc_middle/src/mir/type_foldable.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_parse/src/lexer/tokentrees.rs
  compiler/rustc_parse/src/parser/mod.rs
  library/alloc/src/rc.rs
  library/alloc/src/rc/tests.rs
  library/alloc/src/vec.rs
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
  src/doc/unstable-book/src/language-features/ffi-const.md
  src/doc/unstable-book/src/language-features/ffi-pure.md
  src/librustdoc/clean/types.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/mir-opt/inline/inline-compatibility.rs
  src/test/mir-opt/inline/inline_compatibility.inlined_no_sanitize.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.inlined_target_feature.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.not_inlined_no_sanitize.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.not_inlined_target_feature.Inline.diff
  src/test/rustdoc/auxiliary/intra-link-pub-use.rs
  src/test/rustdoc/intra-link-disambiguators-removed.rs
  src/test/rustdoc/intra-link-pub-use.rs
  src/test/ui/mir/issue-76248.rs
  src/test/ui/type-alias-impl-trait/issue-72793.rs
Labels: S-waiting-on-bors, merged-by-bors

#76285 Move jointness censoring to proc_macro
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_parse/src/lexer/tokentrees.rs
  compiler/rustc_parse/src/parser/mod.rs
Labels: S-waiting-on-bors, WG-parselib

#76263 inliner: Check for codegen fn attributes compatibility
  compiler/rustc_mir/src/transform/inline.rs
  src/test/mir-opt/inline/inline-compatibility.rs
  src/test/mir-opt/inline/inline_compatibility.inlined_no_sanitize.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.inlined_target_feature.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.not_inlined_no_sanitize.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.not_inlined_target_feature.Inline.diff
Labels: S-waiting-on-bors

#76258 x.py check checks tests/examples/benches
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
Labels: A-rustbuild, S-waiting-on-bors

#76254 Fold length constant in Rvalue::Repeat
  compiler/rustc_middle/src/mir/type_foldable.rs
  src/test/ui/mir/issue-76248.rs
Labels: S-waiting-on-bors

#76082 Fix intra-doc links on pub re-exports
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/auxiliary/intra-link-pub-use.rs
  src/test/rustdoc/intra-link-pub-use.rs
Labels: A-intra-doc-links, C-bug, S-waiting-on-bors, T-rustdoc

#76078 Remove disambiguators from intra doc link text
  src/librustdoc/clean/types.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-link-disambiguators-removed.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc

#76060 Link vec doc to & reference
  library/alloc/src/vec.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#75994 `impl Rc::new_cyclic`
  library/alloc/src/rc.rs
  library/alloc/src/rc/tests.rs
Labels: S-waiting-on-bors

#75954 Unstable Book: add links to tracking issues for FFI features
  src/doc/unstable-book/src/language-features/ffi-const.md
  src/doc/unstable-book/src/language-features/ffi-pure.md
Labels: S-waiting-on-bors, T-doc

#75741 Refactor byteorder to std in rustc_middle
  Cargo.lock
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/mir/interpret/allocation.rs
  compiler/rustc_middle/src/mir/interpret/mod.rs
Labels: S-waiting-on-bors

#75695 Add a regression test for issue-72793
  src/test/ui/type-alias-impl-trait/issue-72793.rs
Labels: S-waiting-on-bors

#75428 Workarounds for copy_file_range issues
  library/std/src/sys/unix/fs.rs
Labels: S-waiting-on-bors, T-libs, libs-impl, merged-by-bors

#76217 rename MaybeUninit slice methods
  library/alloc/src/collections/btree/node.rs
  library/core/src/array/iter.rs
  library/core/src/array/mod.rs
  library/core/src/fmt/num.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/num/flt2dec/mod.rs
  library/core/src/num/flt2dec/strategy/dragon.rs
  library/core/src/num/flt2dec/strategy/grisu.rs
  library/core/src/slice/sort.rs
Labels: S-waiting-on-bors, merged-by-bors

#76307 Disable use of `--eh-frame-hdr` on wasm32.
  compiler/rustc_target/src/spec/wasm32_base.rs
Labels: S-waiting-on-bors, merged-by-bors

#76326 Fix rust.use-lld when linker is not set
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#76331 Account for version number in NtIdent hack
  compiler/rustc_ast/src/token.rs
  src/test/ui/proc-macro/group-compat-hack/group-compat-hack.rs
  src/test/ui/proc-macro/group-compat-hack/group-compat-hack.stdout
  src/test/ui/proc-macro/group-compat-hack/js-sys-0.3.17/src/lib.rs
  src/test/ui/proc-macro/group-compat-hack/time-macros-impl-0.1.0/src/lib.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#76370 Fix dropck issue of SyncOnceCell.
  library/std/src/lazy.rs
Labels: S-waiting-on-bors, T-libs, libs-impl, merged-by-bors

#76128 Use Arc::clone and Rc::clone in documentation
  library/core/src/pin.rs
  library/core/src/sync/atomic.rs
  library/std/src/collections/hash/map.rs
  library/std/src/sync/barrier.rs
  library/std/src/sync/condvar.rs
  library/std/src/sync/mutex.rs
  library/std/src/sync/rwlock.rs
  library/std/src/sys_common/poison.rs
Labels: S-waiting-on-bors, T-doc, merged-by-bors

#76067 MIR peephole optimize {Ne, Eq}(_1, false) into _1
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir/src/transform/instcombine.rs
  compiler/rustc_mir/src/transform/mod.rs
  src/test/mir-opt/equal_true.opt.InstCombine.diff
  src/test/mir-opt/equal_true.rs
  src/test/mir-opt/not_equal_false.opt.InstCombine.diff
  src/test/mir-opt/not_equal_false.rs
Labels: A-mir-opt, S-waiting-on-bors, T-compiler, merged-by-bors

#76390 debuginfo: Ignore HashMap .natvis tests before cdb 10.0.18362.1
  src/test/debuginfo/pretty-std-collections-hash.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#75949 Try to improve the documentation of `filter()` and `filter_map()`.
  library/core/src/iter/traits/iterator.rs
Labels: A-iterators, S-waiting-on-bors, T-doc, merged-by-bors

#76157 Update tracking issue for const_caller_location
  library/core/src/intrinsics.rs
  library/core/src/panic.rs
Labels: S-waiting-on-bors, merged-by-bors

#76229 Add missing link in README
  README.md
Labels: S-waiting-on-bors, merged-by-bors

#76422 Rollup of 18 pull requests
  compiler/rustc_ast/src/token.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_data_structures/src/graph/iterate/mod.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/lib.rs
  compiler/rustc_middle/src/traits/query.rs
  compiler/rustc_mir_build/src/lib.rs
  compiler/rustc_mir_build/src/lints.rs
  compiler/rustc_target/src/spec/avr_gnu_base.rs
  library/alloc/src/vec.rs
  library/alloc/tests/borrow.rs
  library/alloc/tests/lib.rs
  library/alloc/tests/vec.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/traits/double_ended.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/num/mod.rs
  library/core/src/ops/control_flow.rs
  library/core/src/slice/mod.rs
  library/core/tests/ascii.rs
  library/core/tests/nonzero.rs
  library/std/src/env.rs
  library/std/src/net/ip/tests.rs
  library/std/src/os/raw/mod.rs
  library/std/src/os/raw/tests.rs
  library/std/src/sys/unix/ext/fs.rs
  library/std/src/sys/vxworks/ext/fs.rs
  library/std/src/time.rs
  src/test/ui/array-slice-vec/slice-2.rs
  src/test/ui/array-slice-vec/vec-concat.rs
  src/test/ui/array-slice-vec/vec-growth.rs
  src/test/ui/array-slice-vec/vec-push.rs
  src/test/ui/array-slice-vec/vec-slice.rs
  src/test/ui/array-slice-vec/vec-to_str.rs
  src/test/ui/array-slice-vec/vec.rs
  src/test/ui/const-generics/min-and-full-same-time.rs
  src/test/ui/const-generics/min-and-full-same-time.stderr
  src/test/ui/consts/const-nonzero.rs
  src/test/ui/consts/cow-is-borrowed.rs
  src/test/ui/consts/is_ascii.rs
  src/test/ui/consts/std/net/ipv4.rs
  src/test/ui/consts/std/net/ipv6.rs
  src/test/ui/str/str-idx.stderr
  src/test/ui/str/str-mut-idx.stderr
  src/test/ui/try-block/try-block-in-return.rs
Labels: S-waiting-on-bors, merged-by-bors

#76364 Disable atomics on avr target.
  compiler/rustc_target/src/spec/avr_gnu_base.rs
Labels: O-AVR, S-waiting-on-bors

#76358 Minor grammar fix in doc comment for soft-deprecated methods
  library/core/src/num/mod.rs
Labels: S-waiting-on-bors

#76346 Docs: nlink example typo
  library/std/src/sys/unix/ext/fs.rs
  library/std/src/sys/vxworks/ext/fs.rs
Labels: S-waiting-on-bors

#76344 Improve docs for `std::env::args()`
  library/std/src/env.rs
Labels: S-waiting-on-bors, T-doc

#76340 Remove unused duplicated `trivial_dropck_outlives`
  compiler/rustc_middle/src/traits/query.rs
Labels: S-waiting-on-bors

#76338 add some intra-doc links to `Iterator`
  library/core/src/iter/traits/iterator.rs
Labels: A-intra-doc-links, A-iterators, S-waiting-on-bors, T-doc, T-libs

#76324 Move Vec slice UI tests in library
  library/alloc/tests/vec.rs
  src/test/ui/array-slice-vec/slice-2.rs
Labels: S-waiting-on-bors

#76318 Use ops::ControlFlow in rustc_data_structures::graph::iterate
  compiler/rustc_data_structures/src/graph/iterate/mod.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_mir_build/src/lib.rs
  compiler/rustc_mir_build/src/lints.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/traits/double_ended.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/ops/control_flow.rs
Labels: S-waiting-on-bors

#76312 time.rs: Make spelling of "Darwin" consistent
  library/std/src/time.rs
Labels: S-waiting-on-bors

#76309 Indent a note to make folding work nicer
  library/core/src/slice/mod.rs
  src/test/ui/str/str-idx.stderr
  src/test/ui/str/str-mut-idx.stderr
Labels: C-cleanup, S-waiting-on-bors, T-libs

#76305 Move various ui const tests to `library`
  library/alloc/tests/borrow.rs
  library/alloc/tests/lib.rs
  library/core/tests/ascii.rs
  library/core/tests/nonzero.rs
  src/test/ui/consts/const-nonzero.rs
  src/test/ui/consts/cow-is-borrowed.rs
  src/test/ui/consts/is_ascii.rs
Labels: A-testsuite, S-waiting-on-bors, T-libs

#76303 Link to `#capacity-and-reallocation` when using with_capacity
  library/alloc/src/vec.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#76302 Address review comments on `Peekable::next_if`
  library/core/src/iter/adapters/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-libs, libs-impl

#76299 Make `Ipv4Addr` and `Ipv6Addr` const tests unit tests under `library`
  library/std/src/net/ip/tests.rs
  src/test/ui/consts/std/net/ipv4.rs
  src/test/ui/consts/std/net/ipv6.rs
Labels: A-testsuite, S-waiting-on-bors, T-libs

#76293 Implementation of incompatible features error
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/lib.rs
  src/test/ui/const-generics/min-and-full-same-time.rs
  src/test/ui/const-generics/min-and-full-same-time.stderr
Labels: S-waiting-on-bors, requires-nightly

#76287 Remove an unnecessary allowed lint
  library/core/src/slice/mod.rs
  library/std/src/os/raw/mod.rs
  library/std/src/os/raw/tests.rs
Labels: C-cleanup, S-waiting-on-bors, T-libs

#76274 Allow try blocks as the argument to return expressions
  compiler/rustc_ast/src/token.rs
  src/test/ui/try-block/try-block-in-return.rs
Labels: A-parser, F-try_blocks, S-waiting-on-bors, T-compiler

#76273 Move some Vec UI tests into alloc unit tests
  library/alloc/tests/vec.rs
  src/test/ui/array-slice-vec/vec-concat.rs
  src/test/ui/array-slice-vec/vec-growth.rs
  src/test/ui/array-slice-vec/vec-push.rs
  src/test/ui/array-slice-vec/vec-slice.rs
  src/test/ui/array-slice-vec/vec-to_str.rs
  src/test/ui/array-slice-vec/vec.rs
Labels: A-testsuite, S-waiting-on-bors, T-libs

#76409 Remove unneeded `#[cfg(not(test))]` from libcore
  library/core/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#76368 Added str tests in library
  library/alloc/tests/string.rs
  src/test/ui/str-concat.rs
Labels: A-testsuite, S-waiting-on-bors, T-libs, merged-by-bors

#76395 Adjust documentation for slice_check_range
  library/core/src/slice/mod.rs
  src/doc/unstable-book/src/library-features/slice-check-range.md
Labels: S-waiting-on-bors, merged-by-bors

#74366 Implement Seek::stream_position() for BufReader
  library/std/src/io/buffered.rs
  library/std/src/io/buffered/tests.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#76044 Support dataflow problems on arbitrary lattices
  Cargo.lock
  compiler/rustc_index/src/bit_set.rs
  compiler/rustc_mir/Cargo.toml
  compiler/rustc_mir/src/dataflow/framework/cursor.rs
  compiler/rustc_mir/src/dataflow/framework/direction.rs
  compiler/rustc_mir/src/dataflow/framework/engine.rs
  compiler/rustc_mir/src/dataflow/framework/fmt.rs
  compiler/rustc_mir/src/dataflow/framework/graphviz.rs
  compiler/rustc_mir/src/dataflow/framework/lattice.rs
  compiler/rustc_mir/src/dataflow/framework/mod.rs
  compiler/rustc_mir/src/dataflow/framework/tests.rs
  compiler/rustc_mir/src/dataflow/framework/visitor.rs
  compiler/rustc_mir/src/dataflow/impls/borrowed_locals.rs
  compiler/rustc_mir/src/dataflow/impls/borrows.rs
  compiler/rustc_mir/src/dataflow/impls/init_locals.rs
  compiler/rustc_mir/src/dataflow/impls/liveness.rs
  compiler/rustc_mir/src/dataflow/impls/mod.rs
  compiler/rustc_mir/src/dataflow/impls/storage_liveness.rs
  compiler/rustc_mir/src/dataflow/mod.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/check_consts/resolver.rs
  compiler/rustc_mir/src/transform/rustc_peek.rs
  src/tools/clippy/clippy_lints/src/redundant_clone.rs
Labels: S-waiting-on-bors, merged-by-bors

#75138 Add derive macro for specifying diagnostics using attributes.
  Cargo.lock
  compiler/rustc_error_codes/src/error_codes/E0224.md
  compiler/rustc_macros/src/lib.rs
  compiler/rustc_macros/src/session_diagnostic.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_typeck/Cargo.toml
  compiler/rustc_typeck/src/astconv/generics.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/compare_method.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/intrinsic.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  compiler/rustc_typeck/src/coherence/builtin.rs
  compiler/rustc_typeck/src/collect.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  compiler/rustc_typeck/src/errors.rs
  compiler/rustc_typeck/src/lib.rs
  src/test/ui-fulldeps/session-derive-errors.rs
  src/test/ui-fulldeps/session-derive-errors.stderr
Labels: S-waiting-on-bors, merged-by-bors

#76210 Tracing update
  Cargo.lock
Labels: S-waiting-on-bors, merged-by-bors

#75585 Do not promote &mut of a non-ZST ever
  compiler/rustc_mir/src/transform/promote_consts.rs
  src/test/ui/consts/promote-no-mut.rs
  src/test/ui/consts/promote-no-mut.stderr
  src/test/ui/consts/promotion-mutable-ref.rs
Labels: S-waiting-on-bors, merged-by-bors

#76423 Make bootstrap build on beta
  src/bootstrap/bootstrap.py
  src/bootstrap/lib.rs
  src/bootstrap/tool.rs
Labels: A-rustbuild, S-waiting-on-bors, T-infra, merged-by-bors

#76308 Enable the SimplifyArmIdentity MIR optimization at mir-opt-level=1
  compiler/rustc_mir/src/transform/simplify_try.rs
  src/test/mir-opt/simplify_try_if_let.{{impl}}-append.SimplifyArmIdentity.diff
Labels: A-mir-opt, S-waiting-on-bors, merged-by-bors

#76332 Add rust-dev component to support rustc development
  src/bootstrap/builder.rs
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors, T-infra, merged-by-bors

#76402 Update linker-plugin-lto.md to contain up to rust 1.46
  src/doc/rustc/src/linker-plugin-lto.md
Labels: S-waiting-on-bors, T-doc

#76403 Fix documentation for TyCtxt::all_impls
  compiler/rustc_middle/src/ty/trait_def.rs
Labels: S-waiting-on-bors

#76401 Add help note to unconstrained const parameter
  compiler/rustc_typeck/src/impl_wf_check.rs
  src/test/ui/const-generics/issues/issue-68366.rs
  src/test/ui/const-generics/issues/issue-68366.stderr
Labels: A-const-generics, A-diagnostics, S-waiting-on-bors, T-compiler

#76396 Fix typo in tracking issue template
  .github/ISSUE_TEMPLATE/tracking_issue.md
Labels: S-waiting-on-bors

#76389 Fix HashMap visualizers in Visual Studio (Code)
  src/etc/natvis/libstd.natvis
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#76379 rustbuild: Remove `Mode::Codegen`
  src/bootstrap/builder.rs
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#76374 Improve ayu doc source line number contrast
  src/librustdoc/html/static/themes/ayu.css
Labels: A-rustdoc-themes, S-waiting-on-bors, T-rustdoc

#76355 remove public visibility previously needed for rustfmt
  compiler/rustc_expand/src/module.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#76162 Make duration_since documentation more clear
  library/std/src/time.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#76418 Move sections about contributing closer together in the README
  README.md
Labels: S-waiting-on-bors, T-doc, merged-by-bors

#76453 rustdoc: Fix font CSS for crate lists
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
Labels: C-bug, S-waiting-on-bors, T-rustdoc, merged-by-bors

#76463 Improve wording of E0607 explanation
  compiler/rustc_error_codes/src/error_codes/E0607.md
Labels: A-diagnostics, A-error-codes, C-enhancement, S-waiting-on-bors, merged-by-bors

#76406 Create E0774
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0774.md
  compiler/rustc_expand/src/expand.rs
  src/test/ui/derives/derive-on-trait-item-or-impl-item.stderr
  src/test/ui/derives/deriving-non-type.stderr
  src/test/ui/feature-gate/issue-43106-gating-of-derive.stderr
  src/test/ui/issues/issue-36617.stderr
  src/test/ui/issues/issue-43023.stderr
  src/test/ui/issues/issue-49934-errors.stderr
  src/test/ui/macros/trace_faulty_macros.stderr
  src/test/ui/malformed/issue-69341-malformed-derive-inert.stderr
  src/test/ui/proc-macro/attributes-on-modules-fail.stderr
  src/test/ui/proc-macro/macros-in-extern-derive.stderr
  src/test/ui/span/issue-43927-non-ADT-derive.stderr
Labels: A-diagnostics, A-error-codes, A-macros, S-waiting-on-bors, T-compiler, merged-by-bors

#76445 Make rustdoc output deterministic for UI tests
  src/test/rustdoc-ui/failed-doctest-output.rs
Labels: A-testsuite, S-waiting-on-bors, T-rustdoc, merged-by-bors

#73971 BTreeMap mutable iterators should not take any reference to visited nodes during iteration
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/search.rs
  library/alloc/src/lib.rs
Labels: S-waiting-on-bors, libs-impl, merged-by-bors

#74595 make `ConstEvaluatable` more strict
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_session/src/lint/builtin.rs
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  compiler/rustc_trait_selection/src/traits/fulfill.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/ui/const_evaluatable/associated-const.rs
  src/test/ui/const_evaluatable/function-call.rs
  src/test/ui/const_evaluatable/function-call.stderr
  src/test/ui/enum-discriminant/issue-70453-polymorphic-ctfe.rs
  src/test/ui/enum-discriminant/issue-70453-polymorphic-ctfe.stderr
  src/test/ui/impl-trait/issue-56445.rs
  src/test/ui/lazy_normalization_consts/issue-73980.rs
  src/test/ui/lazy_normalization_consts/issue-73980.stderr
Labels: I-nominated, S-waiting-on-bors, T-lang, merged-by-bors

#76523 Remove unused PlaceContext::NonUse(NonUseContext::Coverage)
  compiler/rustc_middle/src/mir/visit.rs
  compiler/rustc_mir/src/borrow_check/def_use.rs
  compiler/rustc_mir/src/dataflow/impls/init_locals.rs
Labels: S-waiting-on-bors

#76522 remove redundant clones
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_target/src/spec/windows_uwp_gnu_base.rs
Labels: S-waiting-on-bors

#76516 Enable GitHub Releases synchronization
  triagebot.toml
Labels: S-waiting-on-bors

#76515 SessionDiagnostic: Fix non-determinism in generated format string.
  compiler/rustc_macros/src/session_diagnostic.rs
Labels: A-reproducibility, S-waiting-on-bors, T-compiler

#76504 Capitalize safety comments
  compiler/rustc_data_structures/src/temp_dir.rs
  library/alloc/src/alloc.rs
  library/alloc/src/collections/vec_deque.rs
  library/core/src/future/mod.rs
  library/core/src/iter/adapters/fuse.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/adapters/zip.rs
  library/core/src/lazy.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/num/mod.rs
  library/core/src/pin.rs
  library/core/src/slice/mod.rs
  library/std/src/alloc.rs
  library/std/src/ffi/c_str.rs
  library/std/src/ffi/os_str.rs
  library/std/src/lazy.rs
  library/std/src/sys/windows/os_str.rs
  library/std/src/sys_common/os_str_bytes.rs
  src/test/ui/generator/static-generators.rs
Labels: S-waiting-on-bors

#76493 Remove a stray ignore-tidy-undocumented-unsafe
  library/core/src/ptr/unique.rs
Labels: C-cleanup, S-waiting-on-bors, T-libs

#76481 Convert repetitive target_pointer_width checks to const solution.
  library/alloc/src/collections/vec_deque.rs
Labels: C-cleanup, S-waiting-on-bors, T-libs

#76473 Add missed spaces to GCC-WARNING.txt
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#76465 Add a script to automatically update Rust/Clang versions in documentation
  src/doc/rustc/src/linker-plugin-lto.md
Labels: S-waiting-on-bors

#76430 Add align to rustc-attrs unstable book
  src/doc/unstable-book/src/language-features/rustc-attrs.md
Labels: S-waiting-on-bors

#76313 Improved the MIR spanview output
  compiler/rustc_mir/src/transform/instrument_coverage.rs
  compiler/rustc_mir/src/util/spanview.rs
  src/test/mir-opt/spanview_block.main.mir_map.0.html
  src/test/mir-opt/spanview_statement.main.mir_map.0.html
  src/test/mir-opt/spanview_terminator.main.mir_map.0.html
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-base/expected_mir_dump.coverage_of_if_else/coverage_of_if_else.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/instrument-coverage-mir-cov-html-link-dead-code/expected_mir_dump.coverage_of_if_else/coverage_of_if_else.main.-------.InstrumentCoverage.0.html
Labels: S-waiting-on-bors

#76141 Address review comments about config.toml from rustc-dev-guide PR
  config.toml.example
Labels: A-rustbuild, C-cleanup, S-waiting-on-bors

#75984 Improve unresolved use error message
  compiler/rustc_error_codes/src/error_codes/E0433.md
  compiler/rustc_resolve/src/lib.rs
  src/test/ui/attributes/register-attr-tool-prelude.rs
  src/test/ui/attributes/register-attr-tool-prelude.stderr
  src/test/ui/bad/bad-module.rs
  src/test/ui/bad/bad-module.stderr
  src/test/ui/coherence/conflicting-impl-with-err.stderr
  src/test/ui/derived-errors/issue-31997-1.stderr
  src/test/ui/dyn-trait-compatibility.rs
  src/test/ui/dyn-trait-compatibility.stderr
  src/test/ui/error-codes/E0433.stderr
  src/test/ui/export-fully-qualified.rs
  src/test/ui/export-fully-qualified.stderr
  src/test/ui/export2.rs
  src/test/ui/export2.stderr
  src/test/ui/extern-flag/multiple-opts.stderr
  src/test/ui/extern-flag/noprelude.stderr
  src/test/ui/hygiene/extern-prelude-from-opaque-fail.rs
  src/test/ui/hygiene/extern-prelude-from-opaque-fail.stderr
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/impl-trait/issue-72911.stderr
  src/test/ui/imports/extern-prelude-extern-crate-fail.rs
  src/test/ui/imports/extern-prelude-extern-crate-fail.stderr
  src/test/ui/issues/issue-33293.rs
  src/test/ui/issues/issue-33293.stderr
  src/test/ui/macros/builtin-prelude-no-accidents.rs
  src/test/ui/macros/builtin-prelude-no-accidents.stderr
  src/test/ui/macros/macro-inner-attributes.rs
  src/test/ui/macros/macro-inner-attributes.stderr
  src/test/ui/macros/macro_path_as_generic_bound.stderr
  src/test/ui/mod/mod_file_disambig.rs
  src/test/ui/mod/mod_file_disambig.stderr
  src/test/ui/parser/mod_file_not_exist.rs
  src/test/ui/parser/mod_file_not_exist.stderr
  src/test/ui/parser/mod_file_not_exist_windows.rs
  src/test/ui/parser/mod_file_not_exist_windows.stderr
  src/test/ui/pattern/pattern-error-continue.rs
  src/test/ui/pattern/pattern-error-continue.stderr
  src/test/ui/resolve/use_suggestion.stderr
  src/test/ui/rfc-2126-extern-absolute-paths/non-existent-1.stderr
  src/test/ui/suggestions/type-ascription-instead-of-path.rs
  src/test/ui/suggestions/type-ascription-instead-of-path.stderr
  src/test/ui/type-alias/issue-62263-self-in-atb.rs
  src/test/ui/type-alias/issue-62263-self-in-atb.stderr
  src/test/ui/type-alias/issue-62305-self-assoc-ty.rs
  src/test/ui/type-alias/issue-62305-self-assoc-ty.stderr
  src/test/ui/type/type-path-err-node-types.rs
  src/test/ui/type/type-path-err-node-types.stderr
  src/test/ui/unknown-tool-name.rs
  src/test/ui/unknown-tool-name.stderr
  src/test/ui/use/use-self-type.rs
  src/test/ui/use/use-self-type.stderr
Labels: A-diagnostics, A-resolve, S-waiting-on-bors, T-compiler

#75094 Add `-Z combine_cgu` flag
  compiler/rustc_codegen_llvm/src/back/lto.rs
  compiler/rustc_codegen_llvm/src/back/write.rs
  compiler/rustc_codegen_llvm/src/lib.rs
  compiler/rustc_codegen_ssa/src/back/write.rs
  compiler/rustc_codegen_ssa/src/traits/write.rs
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors

#76558 Rollup of 7 pull requests
  .gitignore
  Cargo.lock
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_codegen_llvm/Cargo.toml
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_graphviz/src/lib.rs
  compiler/rustc_llvm/Cargo.toml
  compiler/rustc_llvm/build.rs
  compiler/rustc_llvm/llvm-wrapper/.editorconfig
  compiler/rustc_llvm/llvm-wrapper/ArchiveWrapper.cpp
  compiler/rustc_llvm/llvm-wrapper/CoverageMappingWrapper.cpp
  compiler/rustc_llvm/llvm-wrapper/LLVMWrapper.h
  compiler/rustc_llvm/llvm-wrapper/Linker.cpp
  compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp
  compiler/rustc_llvm/llvm-wrapper/README
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
  compiler/rustc_llvm/src/lib.rs
  compiler/rustc_mir/src/dataflow/framework/engine.rs
  compiler/rustc_mir/src/util/graphviz.rs
  compiler/rustc_parse/src/lexer/tokentrees.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_session/src/options.rs
  config.toml.example
  library/alloc/src/collections/btree/mod.rs
  library/core/src/ptr/mod.rs
  library/std/Cargo.toml
  library/std/src/collections/hash/map.rs
  library/std/src/collections/hash/map/tests.rs
  library/std/src/collections/hash/set.rs
  library/std/src/collections/hash/set/tests.rs
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/native.rs
  src/etc/gdb_lookup.py
  src/etc/gdb_providers.py
  src/etc/lldb_lookup.py
  src/etc/lldb_providers.py
  src/etc/natvis/libstd.natvis
  src/test/mir-opt/graphviz.main.mir_map.0.dot
Labels: S-waiting-on-bors, merged-by-bors, rollup

#76556 Revert #76285
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_parse/src/lexer/tokentrees.rs
  compiler/rustc_parse/src/parser/mod.rs
Labels: S-waiting-on-bors

#76543 Document btree's unwrap_unchecked
  library/alloc/src/collections/btree/mod.rs
Labels: S-waiting-on-bors

#76500 Add -Zgraphviz_dark_mode and monospace font fix
  compiler/rustc_graphviz/src/lib.rs
  compiler/rustc_mir/src/dataflow/framework/engine.rs
  compiler/rustc_mir/src/util/graphviz.rs
  compiler/rustc_session/src/options.rs
  src/test/mir-opt/graphviz.main.mir_map.0.dot
Labels: A-mir, A-pretty, B-unstable, S-waiting-on-bors, T-compiler
