Repository rust-lang/rust, pull requests merged in 2020-06, with the labels that each got.

#72831 Rollup of 5 pull requests
  RELEASES.md
  src/libcore/slice/mod.rs
  src/libcore/tests/iter.rs
  src/librustc_trait_selection/traits/wf.rs
  src/librustdoc/html/static/main.js
  src/test/ui/associated-types/issue-72806.rs
  src/test/ui/associated-types/issue-72806.stderr
Labels: S-waiting-on-bors, merged-by-bors

#72830 Fix release notes for niche initialization change
  RELEASES.md
Labels: S-waiting-on-bors

#72829 Clarify terms in doc comments
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#72812 Miri tests: skip parts of test_char_range
  src/libcore/tests/iter.rs
Labels: S-waiting-on-bors

#72807 Avoid setting wrong obligation cause span of associated type mismatch
  src/librustc_trait_selection/traits/wf.rs
  src/test/ui/associated-types/issue-72806.rs
  src/test/ui/associated-types/issue-72806.stderr
Labels: S-waiting-on-bors

#72691 Fix escape key handling
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#72844 Rollup of 5 pull requests
  RELEASES.md
  src/libcore/ops/deref.rs
  src/librustc_error_codes/error_codes/E0622.md
  src/librustc_macros/src/query.rs
  src/librustc_middle/query/mod.rs
  src/librustc_query_system/query/config.rs
  src/librustc_trait_selection/traits/fulfill.rs
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-impl.stderr
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-trait-default.stderr
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-trait.stderr
  src/test/ui/consts/const-size_of-cycle.stderr
  src/test/ui/cycle-projection-based-on-where-clause.stderr
  src/test/ui/cycle-trait/cycle-trait-default-type-trait.stderr
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/infinite/infinite-tag-type-recursion.rs
  src/test/ui/infinite/infinite-tag-type-recursion.stderr
  src/test/ui/infinite/infinite-vec-type-recursion.stderr
  src/test/ui/issues/issue-21177.stderr
  src/test/ui/issues/issue-34373.stderr
  src/test/ui/recursion/issue-26548-recursion-via-normalize.rs
  src/test/ui/recursion/issue-26548-recursion-via-normalize.stderr
  src/test/ui/resolve/issue-23305.stderr
  src/test/ui/resolve/resolve-self-in-impl.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#72834 Rephrase term 'non-pointer type'
  src/libcore/ops/deref.rs
Labels: S-waiting-on-bors

#72832 RELEASES.md: Expand `cargo tree` note to mention `cargo tree -d`
  RELEASES.md
Labels: S-waiting-on-bors, relnotes

#72823 Add descriptions for all queries
  src/librustc_macros/src/query.rs
  src/librustc_middle/query/mod.rs
  src/librustc_query_system/query/config.rs
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-impl.stderr
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-trait-default.stderr
  src/test/ui/associated-consts/issue-24949-assoc-const-static-recursion-trait.stderr
  src/test/ui/consts/const-size_of-cycle.stderr
  src/test/ui/cycle-projection-based-on-where-clause.stderr
  src/test/ui/cycle-trait/cycle-trait-default-type-trait.stderr
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/infinite/infinite-tag-type-recursion.rs
  src/test/ui/infinite/infinite-tag-type-recursion.stderr
  src/test/ui/infinite/infinite-vec-type-recursion.stderr
  src/test/ui/issues/issue-21177.stderr
  src/test/ui/issues/issue-34373.stderr
  src/test/ui/recursion/issue-26548-recursion-via-normalize.rs
  src/test/ui/recursion/issue-26548-recursion-via-normalize.stderr
  src/test/ui/resolve/issue-23305.stderr
  src/test/ui/resolve/resolve-self-in-impl.stderr
Labels: S-waiting-on-bors

#72818 Clean up E0622 explanation
  src/librustc_error_codes/error_codes/E0622.md
Labels: S-waiting-on-bors

#72776 fulfill: try using SmallVec or Box for stalled_on
  src/librustc_trait_selection/traits/fulfill.rs
Labels: S-waiting-on-bors

#71192 Make TLS accesses explicit in MIR
  src/librustc_codegen_llvm/common.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/tcx.rs
  src/librustc_middle/mir/type_foldable.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/transform/check_consts/qualifs.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir_build/build/expr/as_place.rs
  src/librustc_mir_build/build/expr/as_rvalue.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/librustc_mir_build/build/expr/category.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/hair/cx/expr.rs
  src/librustc_mir_build/hair/mod.rs
  src/test/mir-opt/tls-access.rs
  src/test/mir-opt/tls-access/rustc.main.SimplifyCfg-final.after.mir
Labels: S-waiting-on-bors, merged-by-bors

#72883 [stable] 1.44 release
  RELEASES.md
  src/ci/run.sh
  src/librustc_expand/base.rs
  src/librustc_expand/expand.rs
  src/librustc_expand/module.rs
  src/librustc_expand/proc_macro_server.rs
  src/librustc_interface/passes.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_save_analysis/span_utils.rs
  src/librustc_span/lib.rs
  src/librustc_span/source_map.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/test.rs
Labels: S-waiting-on-bors, merged-by-bors

#72905 Rollup of 10 pull requests
  README.md
  src/libcore/macros/mod.rs
  src/libcore/mem/maybe_uninit.rs
  src/libcore/num/wrapping.rs
  src/librustc_builtin_macros/asm.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_error_codes/error_codes/E0637.md
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/ty/structural_impls.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_trait_selection/traits/mod.rs
  src/test/ui/asm/rustfix-asm.fixed
  src/test/ui/asm/rustfix-asm.rs
  src/test/ui/asm/rustfix-asm.stderr
  src/test/ui/consts/miri_unleashed/inline_asm.rs
  src/test/ui/consts/miri_unleashed/inline_asm.stderr
  src/test/ui/consts/miri_unleashed/tls.rs
  src/test/ui/consts/miri_unleashed/tls.stderr
  src/test/ui/feature-gates/feature-gate-asm.rs
  src/test/ui/feature-gates/feature-gate-asm.stderr
  src/test/ui/feature-gates/feature-gate-asm2.rs
  src/test/ui/feature-gates/feature-gate-asm2.stderr
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/dollar-crate.rs
  src/test/ui/proc-macro/dollar-crate.stderr
  src/test/ui/proc-macro/input-interpolated.rs
  src/test/ui/proc-macro/input-interpolated.stdout
  src/test/ui/suggestions/issue-72766.rs
  src/test/ui/suggestions/issue-72766.stderr
  src/tools/clippy/clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#72893 test miri-unleash TLS accesses
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/test/ui/consts/miri_unleashed/inline_asm.rs
  src/test/ui/consts/miri_unleashed/inline_asm.stderr
  src/test/ui/consts/miri_unleashed/tls.rs
  src/test/ui/consts/miri_unleashed/tls.stderr
Labels: S-waiting-on-bors

#72891 Add associated consts MIN/MAX for Wrapping<Int>
  src/libcore/num/wrapping.rs
Labels: S-waiting-on-bors

#72889 rustc: Remove the `--passive-segments` LLD flag on wasm
  src/librustc_codegen_ssa/back/linker.rs
Labels: S-waiting-on-bors

#72886 Remove allow missing_debug_implementations for MaybeUninit
  src/libcore/mem/maybe_uninit.rs
Labels: S-waiting-on-bors

#72880 Clean up E0637 explanation
  src/librustc_error_codes/error_codes/E0637.md
Labels: S-waiting-on-bors

#72827 changed *nix to Unix-like
  README.md
Labels: S-waiting-on-bors

#72825 Clarify errors and warnings about the transition to the new asm!
  src/libcore/macros/mod.rs
  src/librustc_builtin_macros/asm.rs
  src/test/ui/asm/rustfix-asm.fixed
  src/test/ui/asm/rustfix-asm.rs
  src/test/ui/asm/rustfix-asm.stderr
  src/test/ui/feature-gates/feature-gate-asm.rs
  src/test/ui/feature-gates/feature-gate-asm.stderr
  src/test/ui/feature-gates/feature-gate-asm2.rs
  src/test/ui/feature-gates/feature-gate-asm2.stderr
Labels: S-waiting-on-bors

#72822 remove trivial calls to mk_const
  src/librustc_middle/ty/structural_impls.rs
Labels: S-waiting-on-bors

#72795 Add a test for `$:ident` in proc macro input
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/dollar-crate.rs
  src/test/ui/proc-macro/dollar-crate.stderr
  src/test/ui/proc-macro/input-interpolated.rs
  src/test/ui/proc-macro/input-interpolated.stdout
Labels: S-waiting-on-bors

#72775 Return early to avoid ICE
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_trait_selection/traits/mod.rs
  src/test/ui/suggestions/issue-72766.rs
  src/test/ui/suggestions/issue-72766.stderr
  src/tools/clippy/clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-bors

#72672 Make remote-test-client and remote-test-server compatible with windows
  src/bootstrap/test.rs
  src/tools/compiletest/src/runtest.rs
  src/tools/remote-test-client/src/main.rs
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#72918 Rollup of 4 pull requests
  README.md
  RELEASES.md
  src/librustc_lexer/src/lib.rs
  src/librustc_lexer/src/tests.rs
  src/librustc_parse/lexer/mod.rs
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#72916 Update README.md
  README.md
Labels: S-waiting-on-bors

#72914 Minor: off-by-one error in RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors, beta-accepted, beta-nominated

#72888 Add a warning about infinite reading in read_(until|line)
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#72884 RawString error reporting cleanup
  src/librustc_lexer/src/lib.rs
  src/librustc_lexer/src/tests.rs
  src/librustc_parse/lexer/mod.rs
Labels: S-waiting-on-bors

#72935 Rollup of 5 pull requests
  src/liballoc/vec.rs
  src/librustc_mir/transform/instcombine.rs
  src/librustc_typeck/astconv.rs
  src/test/mir-opt/inline/issue-58867-inline-as-ref-as-mut/rustc.a.Inline.after.mir
  src/test/mir-opt/inline/issue-58867-inline-as-ref-as-mut/rustc.b.Inline.after.mir
  src/test/mir-opt/nrvo-simple/rustc.nrvo.RenameReturnPlace.diff
  src/test/ui-fulldeps/compiler-calls.rs
  src/test/ui-fulldeps/mod_dir_path_canonicalized.rs
  src/test/ui/suggestions/suggest-move-types.stderr
  src/test/ui/variance-iterators-in-libcore.rs
  src/tools/compiletest/src/header.rs
  src/tools/remote-test-client/src/main.rs
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#72921 Add assert to Vec with_capacity docs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#72902 Add a test to ensure Fuse stays covariant
  src/test/ui/variance-iterators-in-libcore.rs
Labels: S-waiting-on-bors

#72848 Correct generic parameter ordering in error note for E0747
  src/librustc_typeck/astconv.rs
  src/test/ui/suggestions/suggest-move-types.stderr
Labels: S-waiting-on-bors

#72820 InstCombine: Don't optimize `&mut *x` into `x`
  src/librustc_mir/transform/instcombine.rs
  src/test/mir-opt/inline/issue-58867-inline-as-ref-as-mut/rustc.a.Inline.after.mir
  src/test/mir-opt/inline/issue-58867-inline-as-ref-as-mut/rustc.b.Inline.after.mir
  src/test/mir-opt/nrvo-simple/rustc.nrvo.RenameReturnPlace.diff
Labels: S-waiting-on-bors

#72704 Remote testing fixes
  src/test/ui-fulldeps/compiler-calls.rs
  src/test/ui-fulldeps/mod_dir_path_canonicalized.rs
  src/tools/compiletest/src/header.rs
  src/tools/remote-test-client/src/main.rs
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors

#72746 Make libunwind build hermetic
  src/libunwind/build.rs
Labels: S-waiting-on-bors, merged-by-bors

#72948 Rollup of 5 pull requests
  src/doc/unstable-book/src/compiler-flags/control-flow-guard.md
  src/librustc_error_codes/error_codes/E0641.md
  src/librustc_metadata/creader.rs
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/confirmation.rs
  src/librustc_trait_selection/traits/select/mod.rs
  src/libstd/io/buffered.rs
  src/test/ui/unused-crate-deps/ignore-pathless-extern.rs
Labels: S-waiting-on-bors, merged-by-bors

#72942 clean up E0641 explanation
  src/librustc_error_codes/error_codes/E0641.md
Labels: S-waiting-on-bors

#72945 Updated documentation for Control Flow Guard
  src/doc/unstable-book/src/compiler-flags/control-flow-guard.md
Labels: S-waiting-on-bors

#72924 Stabilize `std::io::Buf{Reader, Writer}::capacity`
  src/libstd/io/buffered.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#72900 Don't count pathless --extern for unused-crate-dependencies warnings
  src/librustc_metadata/creader.rs
  src/test/ui/unused-crate-deps/ignore-pathless-extern.rs
Labels: S-waiting-on-bors

#72586 split select into submodules
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/confirmation.rs
  src/librustc_trait_selection/traits/select/mod.rs
Labels: S-waiting-on-bors

#72754 remove trivial `mk_predicate`s
  src/librustc_middle/ty/structural_impls.rs
Labels: S-waiting-on-bors, merged-by-bors

#72618 Make `SourceMap` available for early debug-printing of `Span`s
  src/librustc_interface/interface.rs
  src/librustc_span/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#72964 Bump libc dependency to latest version (0.2.71)
  Cargo.lock
Labels: S-waiting-on-bors

#72950 fix `AdtDef` docs
  src/librustc_middle/ty/mod.rs
Labels: S-waiting-on-bors

#72951 Add Camelid per request
  .mailmap
Labels: S-waiting-on-bors

#72923 Improve E0433, so that it suggests missing imports
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/late.rs
  src/librustc_resolve/lib.rs
  src/test/ui/derived-errors/issue-31997-1.stderr
  src/test/ui/error-codes/E0433.rs
  src/test/ui/error-codes/E0433.stderr
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/resolve/use_suggestion.rs
  src/test/ui/resolve/use_suggestion.stderr
Labels: S-waiting-on-bors

#72782 rustc_target: Remove `pre_link_args_crt`
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_target/spec/mod.rs
  src/librustc_target/spec/tests/tests_impl.rs
  src/librustc_target/spec/vxworks_base.rs
Labels: S-waiting-on-bors

#72995 Rollup of 5 pull requests
  .mailmap
  RELEASES.md
  src/liballoc/vec.rs
  src/librustc_trait_selection/opaque_types.rs
  src/libstd/os/linux/raw.rs
Labels: S-waiting-on-bors, merged-by-bors

#72990 Fix missing word in RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors

#72987 Add myself to mailmap
  .mailmap
Labels: S-waiting-on-bors

#72986 Add more assert to Vec with_capacity docs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#72971 Hexagon libstd: fix typo for c_ulonglong
  src/libstd/os/linux/raw.rs
Labels: S-waiting-on-bors

#72946 remove outdated fixme
  src/librustc_trait_selection/opaque_types.rs
Labels: S-waiting-on-bors

#72957 Bump bootstrap compiler to 1.45
  src/bootstrap/channel.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/libcore/intrinsics.rs
  src/libcore/marker.rs
  src/libcore/ops/try.rs
  src/libcore/panicking.rs
  src/libpanic_unwind/seh.rs
  src/libstd/panicking.rs
  src/libstd/sync/mpsc/shared.rs
  src/libstd/sync/mpsc/sync.rs
  src/libstd/sys/cloudabi/mod.rs
  src/libstd/sys/windows/mod.rs
  src/stage0.txt
  src/tools/clippy/clippy_lints/src/write.rs
Labels: S-waiting-on-bors, merged-by-bors

#73025 Rollup of 5 pull requests
  RELEASES.md
  src/liballoc/tests/vec.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0760.md
  src/librustc_hir/definitions.rs
  src/librustc_middle/hir/map/mod.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/asm/issue-72570.rs
  src/test/ui/asm/issue-72570.stderr
  src/test/ui/async-await/issue-61949-self-return-type.stderr
  src/test/ui/impl-trait/bound-normalization-fail.stderr
Labels: S-waiting-on-bors, merged-by-bors

#73019 add test for #72960
  src/test/ui/asm/issue-72570.rs
  src/test/ui/asm/issue-72570.stderr
Labels: S-waiting-on-bors

#73017 Use assert_eq for liballoc test
  src/liballoc/tests/vec.rs
Labels: S-waiting-on-bors

#73010 Update RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors

#72996 Remove unsused `NodeId` related APIs in hir map
  src/librustc_hir/definitions.rs
  src/librustc_middle/hir/map/mod.rs
Labels: S-waiting-on-bors

#72260 Spell out `Self` in async function return
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0760.md
  src/librustc_typeck/check/mod.rs
  src/test/ui/async-await/issue-61949-self-return-type.stderr
  src/test/ui/impl-trait/bound-normalization-fail.stderr
Labels: S-waiting-on-bors

#72982 resolve: Sort E0408 errors by Symbol str
  src/librustc_resolve/late.rs
  src/test/ui/borrowck/borrowck-asm.rs
  src/test/ui/borrowck/borrowck-asm.stderr
  src/test/ui/c-variadic/variadic-ffi-1.rs
  src/test/ui/c-variadic/variadic-ffi-1.stderr
  src/test/ui/cfg/conditional-compile-arch.rs
  src/test/ui/extern/extern-methods.rs
  src/test/ui/extern/extern-thiscall.rs
  src/test/ui/extern/extern-vectorcall.rs
  src/test/ui/feature-gates/feature-gate-abi-msp430-interrupt.rs
  src/test/ui/feature-gates/feature-gate-abi-msp430-interrupt.stderr
  src/test/ui/llvm-asm/llvm-asm-bad-clobber.rs
  src/test/ui/llvm-asm/llvm-asm-bad-clobber.stderr
  src/test/ui/llvm-asm/llvm-asm-in-bad-modifier.rs
  src/test/ui/llvm-asm/llvm-asm-in-bad-modifier.stderr
  src/test/ui/llvm-asm/llvm-asm-misplaced-option.rs
  src/test/ui/llvm-asm/llvm-asm-misplaced-option.stderr
  src/test/ui/llvm-asm/llvm-asm-out-assign-imm.rs
  src/test/ui/llvm-asm/llvm-asm-out-assign-imm.stderr
  src/test/ui/llvm-asm/llvm-asm-out-no-modifier.rs
  src/test/ui/llvm-asm/llvm-asm-out-no-modifier.stderr
  src/test/ui/llvm-asm/llvm-asm-out-read-uninit.rs
  src/test/ui/llvm-asm/llvm-asm-out-read-uninit.stderr
  src/test/ui/or-patterns/mismatched-bindings-async-fn.stderr
  src/test/ui/span/issue-39698.stderr
  src/test/ui/target-feature/gate.rs
  src/test/ui/target-feature/gate.stderr
  src/test/ui/target-feature/invalid-attribute.rs
  src/test/ui/target-feature/invalid-attribute.stderr
Labels: S-waiting-on-bors, merged-by-bors

#73073 Rollup of 3 pull requests
  src/libcore/time.rs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_target/spec/tests/tests_impl.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/clean/mod.rs
  src/tools/clippy/clippy_lints/src/future_not_send.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#72708 linker: Add a linker rerun hack for gcc versions not supporting -static-pie
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_target/spec/tests/tests_impl.rs
Labels: S-waiting-on-bors

#72508 Make `PolyTraitRef::self_ty` return `Binder<Ty>`
  src/librustc_middle/ty/sty.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/clean/mod.rs
  src/tools/clippy/clippy_lints/src/future_not_send.rs
Labels: S-waiting-on-bors

#71796 de-promote Duration::from_secs
  src/libcore/time.rs
Labels: S-waiting-on-bors

#73059 remove outdated comment
  src/librustc_middle/ty/sty.rs
Labels: S-waiting-on-bors

#73057 Clean up E0644 explanation
  src/librustc_error_codes/error_codes/E0644.md
Labels: S-waiting-on-bors

#72993 Count the beta prerelease number just from master
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#72989 Revert pr 71840
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_mir/util/graphviz.rs
  src/librustc_mir_build/build/block.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/build/matches/mod.rs
  src/librustc_mir_build/build/matches/test.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/build/scope.rs
  src/test/codegen/drop.rs
  src/test/mir-opt/basic_assignment/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/box_expr/rustc.main.ElaborateDrops.before.mir
  src/test/mir-opt/const-promotion-extern-static/rustc.BAR.PromoteTemps.diff
  src/test/mir-opt/const-promotion-extern-static/rustc.FOO.PromoteTemps.diff
  src/test/mir-opt/const_prop/boxes/rustc.main.ConstProp.diff
  src/test/mir-opt/generator-drop-cleanup/rustc.main-{{closure}}.generator_drop.0.mir
  src/test/mir-opt/generator-storage-dead-unwind/rustc.main-{{closure}}.StateTransform.before.mir
  src/test/mir-opt/graphviz/rustc.main.mir_map.0.dot
  src/test/mir-opt/inline/inline-into-box-place/32bit/rustc.main.Inline.diff
  src/test/mir-opt/inline/inline-into-box-place/64bit/rustc.main.Inline.diff
  src/test/mir-opt/issue-38669/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-41110/rustc.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue-41110/rustc.test.ElaborateDrops.after.mir
  src/test/mir-opt/issue-41697/32bit/rustc.{{impl}}-{{constant}}.SimplifyCfg-qualify-consts.after.mir
  src/test/mir-opt/issue-41697/64bit/rustc.{{impl}}-{{constant}}.SimplifyCfg-qualify-consts.after.mir
  src/test/mir-opt/issue-41888/rustc.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue-49232/rustc.main.mir_map.0.mir
  src/test/mir-opt/issue-62289/rustc.test.ElaborateDrops.before.mir
  src/test/mir-opt/loop_test/rustc.main.SimplifyCfg-qualify-consts.after.mir
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.ElaborateDrops.after.mir
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.SimplifyCfg-initial.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match.PromoteTemps.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match2.PromoteTemps.before.mir
  src/test/mir-opt/match_false_edges/rustc.main.PromoteTemps.before.mir
  src/test/mir-opt/nll/region-subtyping-basic/32bit/rustc.main.nll.0.mir
  src/test/mir-opt/nll/region-subtyping-basic/64bit/rustc.main.nll.0.mir
  src/test/mir-opt/no-drop-for-inactive-variant/rustc.unwrap.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/no-spurious-drop-after-call/rustc.main.ElaborateDrops.before.mir
  src/test/mir-opt/packed-struct-drop-aligned/32bit/rustc.main.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/packed-struct-drop-aligned/64bit/rustc.main.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/retag/rustc.main.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/simple-match/32bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simple-match/64bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simplify-arm/rustc.id_try.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-arm/rustc.id_try.SimplifyBranchSame.diff
  src/test/mir-opt/simplify_cfg/rustc.main.SimplifyCfg-early-opt.diff
  src/test/mir-opt/simplify_cfg/rustc.main.SimplifyCfg-initial.diff
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyArmIdentity.diff
  src/test/mir-opt/storage_live_dead_in_statics/rustc.XXX.mir_map.0.mir
  src/test/mir-opt/uniform_array_move_out/rustc.move_out_by_subslice.mir_map.0.mir
  src/test/mir-opt/uniform_array_move_out/rustc.move_out_from_end.mir_map.0.mir
  src/test/mir-opt/unusual-item-types/32bit/rustc.E-V-{{constant}}.mir_map.0.mir
  src/test/mir-opt/unusual-item-types/32bit/rustc.ptr-drop_in_place.std__vec__Vec_i32_.AddMovesForPackedDrops.before.mir
  src/test/mir-opt/unusual-item-types/32bit/rustc.{{impl}}-ASSOCIATED_CONSTANT.mir_map.0.mir
  src/test/mir-opt/unusual-item-types/64bit/rustc.E-V-{{constant}}.mir_map.0.mir
  src/test/mir-opt/unusual-item-types/64bit/rustc.ptr-drop_in_place.std__vec__Vec_i32_.AddMovesForPackedDrops.before.mir
  src/test/mir-opt/unusual-item-types/64bit/rustc.{{impl}}-ASSOCIATED_CONSTANT.mir_map.0.mir
  src/test/mir-opt/while-storage/rustc.while_loop.PreCodegen.after.mir
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#72810 validate basic sanity for TerminatorKind
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/transform/validate.rs
Labels: A-mir, S-waiting-on-bors

#73093 Rollup of 5 pull requests
  src/liballoc/vec.rs
  src/libcore/sync/atomic.rs
  src/librustc_codegen_ssa/mir/analyze.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_lint/levels.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/type_foldable.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/framework/direction.rs
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir/transform/remove_noop_landing_pads.rs
  src/librustc_mir/transform/simplify_branches.rs
  src/librustc_mir/transform/validate.rs
  src/librustc_mir_build/build/matches/util.rs
  src/librustc_mir_build/lints.rs
  src/librustc_session/lint.rs
  src/librustc_session/lint/builtin.rs
  src/librustc_ty/needs_drop.rs
  src/librustdoc/core.rs
  src/test/mir-opt/exponential-or/rustc.match_tuple.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-38669/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-49232/rustc.main.mir_map.0.mir
  src/test/mir-opt/loop_test/rustc.main.SimplifyCfg-qualify-consts.after.mir
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.SimplifyCfg-initial.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match.PromoteTemps.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match2.PromoteTemps.before.mir
  src/test/mir-opt/match_false_edges/rustc.main.PromoteTemps.before.mir
  src/test/mir-opt/match_test/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/nll/region-subtyping-basic/32bit/rustc.main.nll.0.mir
  src/test/mir-opt/nll/region-subtyping-basic/64bit/rustc.main.nll.0.mir
  src/test/mir-opt/simple-match/32bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simple-match/64bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simplify_cfg/rustc.main.SimplifyCfg-initial.diff
Labels: S-waiting-on-bors, merged-by-bors

#73063 Elide type on liballoc vec
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#72998 Mention that some atomic operations may not be available on some platforms
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#72970 Properly handle feature-gated lints
  src/librustc_lint/levels.rs
  src/librustc_session/lint.rs
  src/librustc_session/lint/builtin.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors

#72908 rename FalseEdges -> FalseEdge
  src/librustc_codegen_ssa/mir/analyze.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/type_foldable.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/framework/direction.rs
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir/transform/remove_noop_landing_pads.rs
  src/librustc_mir/transform/simplify_branches.rs
  src/librustc_mir/transform/validate.rs
  src/librustc_mir_build/build/matches/util.rs
  src/librustc_mir_build/lints.rs
  src/test/mir-opt/exponential-or/rustc.match_tuple.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-38669/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-49232/rustc.main.mir_map.0.mir
  src/test/mir-opt/loop_test/rustc.main.SimplifyCfg-qualify-consts.after.mir
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.SimplifyCfg-initial.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match.PromoteTemps.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match2.PromoteTemps.before.mir
  src/test/mir-opt/match_false_edges/rustc.main.PromoteTemps.before.mir
  src/test/mir-opt/match_test/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/nll/region-subtyping-basic/32bit/rustc.main.nll.0.mir
  src/test/mir-opt/nll/region-subtyping-basic/64bit/rustc.main.nll.0.mir
  src/test/mir-opt/simple-match/32bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simple-match/64bit/rustc.match_bool.mir_map.0.mir
  src/test/mir-opt/simplify_cfg/rustc.main.SimplifyCfg-initial.diff
Labels: A-mir, S-waiting-on-bors

#72764 Be more careful around ty::Error in generators
  src/librustc_mir/transform/generator.rs
  src/librustc_ty/needs_drop.rs
Labels: S-waiting-on-bors

#72952 run-make regression test for issue #70924.
  src/test/run-make-fulldeps/incr-add-rust-src-component/Makefile
  src/test/run-make-fulldeps/incr-add-rust-src-component/main.rs
Labels: S-waiting-on-bors, T-compiler

#72904 Order the Rust and C ABIs first to reduce test churn
  src/librustc_target/spec/abi.rs
  src/test/ui/codemap_tests/unicode.stderr
  src/test/ui/parser/issue-8537.stderr
  src/test/ui/symbol-names/basic.legacy.stderr
  src/test/ui/symbol-names/impl1.legacy.stderr
  src/test/ui/symbol-names/impl1.rs
  src/test/ui/symbol-names/issue-60925.legacy.stderr
Labels: S-waiting-on-bors, merged-by-bors

#73046 save_analysis: fix some ICEs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/test/ui/save-analysis/issue-73020.rs
  src/test/ui/save-analysis/issue-73020.stderr
  src/test/ui/save-analysis/issue-73022.rs
Labels: S-waiting-on-bors, merged-by-bors

#73115 Rollup of 10 pull requests
  Cargo.lock
  src/doc/unstable-book/src/compiler-flags/profile.md
  src/doc/unstable-book/src/library-features/default-free-fn.md
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
  src/libcore/default.rs
  src/librustc_error_codes/error_codes/E0646.md
  src/librustc_errors/Cargo.toml
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_expand/expand.rs
  src/librustc_expand/proc_macro_server.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/tests.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_session/options.rs
  src/libstd/ffi/c_str.rs
  src/libstd/keyword_docs.rs
  src/test/ui/annotate-snippet/auxiliary/multispan.rs
  src/test/ui/annotate-snippet/missing-type.stderr
  src/test/ui/annotate-snippet/multispan.rs
  src/test/ui/annotate-snippet/multispan.stderr
  src/test/ui/proc-macro/debug/dump-debug-span-debug.rs
  src/test/ui/proc-macro/debug/dump-debug-span-debug.stderr
  src/test/ui/resolve/issue-2356.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#73092 Clean up E0646
  src/librustc_error_codes/error_codes/E0646.md
Labels: S-waiting-on-bors

#73075 Add comments to `Resolve::get_module`
  src/librustc_resolve/build_reduced_graph.rs
Labels: S-waiting-on-bors

#73001 Free `default()` forwarding to `Default::default()`
  src/doc/unstable-book/src/library-features/default-free-fn.md
  src/libcore/default.rs
  src/test/ui/resolve/issue-2356.stderr
Labels: S-waiting-on-bors

#72963 Cstring `from_raw` and `into_raw` safety precisions
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors, T-libs

#72811 Liballoc impl
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#72799 Add `-Z span-debug` to allow for easier debugging of proc macros
  src/librustc_expand/expand.rs
  src/librustc_expand/proc_macro_server.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/test/ui/proc-macro/debug/dump-debug-span-debug.rs
  src/test/ui/proc-macro/debug/dump-debug-span-debug.stderr
Labels: S-waiting-on-bors

#72761 Added the documentation for the 'use' keyword
  src/libstd/keyword_docs.rs
Labels: S-waiting-on-bors

#72615 Fix documentation example for gcov profiling
  src/doc/unstable-book/src/compiler-flags/profile.md
Labels: S-waiting-on-bors

#72583 impl AsRef<[T]> for vec::IntoIter<T>
  src/liballoc/vec.rs
Labels: S-waiting-on-bors, S-waiting-on-fcp, T-libs, disposition-merge, finished-final-comment-period, relnotes

#72026 Update annotate-snippets-rs to 0.8.0
  Cargo.lock
  src/librustc_errors/Cargo.toml
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/test/ui/annotate-snippet/auxiliary/multispan.rs
  src/test/ui/annotate-snippet/missing-type.stderr
  src/test/ui/annotate-snippet/multispan.rs
  src/test/ui/annotate-snippet/multispan.stderr
Labels: S-waiting-on-bors

#72655 Enable LVI hardening for x86_64-fortanix-unknown-sgx
  Cargo.lock
  src/bootstrap/cc_detect.rs
  src/ci/docker/dist-various-2/Dockerfile
  src/ci/docker/dist-various-2/build-x86_64-fortanix-unknown-sgx-toolchain.sh
  src/ci/docker/dist-various-2/x86_64-fortanix-unknown-sgx-clang-wrap.sh
  src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs
  src/libstd/Cargo.toml
  src/libstd/sys/sgx/abi/entry.S
Labels: S-waiting-on-bors, merged-by-bors

#73138 Use shorthand linker strip arguments in order to support MacOS
  src/librustc_codegen_ssa/back/linker.rs
Labels: S-waiting-on-bors

#73124 Removed lifetime parameters from Explanation of E0207
  src/librustc_error_codes/error_codes/E0207.md
Labels: S-waiting-on-bors

#73118 Improve the wording in documentation of std::mem::drop
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#73090 Use `LocalDefId` directly in `Resolver::export_map`
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_middle/hir/exports.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_resolve/imports.rs
  src/librustc_resolve/lib.rs
Labels: S-waiting-on-bors

#73008 Update RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors

#72912 Add new E0758 error code
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0758.md
  src/librustc_parse/lexer/mod.rs
  src/test/ui/unterminated-comment.rs
  src/test/ui/unterminated-comment.stderr
  src/test/ui/unterminated-doc-comment.rs
  src/test/ui/unterminated-doc-comment.stderr
Labels: S-waiting-on-bors

#71842 doc: make impl block collapsible if it has an associated constant
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, T-rustdoc

#73153 Revert #71956
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/impls/init_locals.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/dataflow/impls/storage_liveness.rs
  src/librustc_mir/transform/generator.rs
  src/test/ui/async-await/async-fn-size-moved-locals.rs
  src/test/ui/async-await/issue-73137.rs
  src/test/ui/generator/size-moved-locals.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#72114 Rename traits::Vtable to ImplSource.
  src/librustc_infer/traits/mod.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/traits/mod.rs
  src/librustc_middle/traits/structural_impls.rs
  src/librustc_middle/ty/query/mod.rs
  src/librustc_mir/monomorphize/mod.rs
  src/librustc_trait_selection/traits/auto_trait.rs
  src/librustc_trait_selection/traits/codegen/mod.rs
  src/librustc_trait_selection/traits/fulfill.rs
  src/librustc_trait_selection/traits/mod.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/select/confirmation.rs
  src/librustc_trait_selection/traits/util.rs
  src/librustc_ty/instance.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#73190 Rollup of 8 pull requests
  .mailmap
  src/doc/unstable-book/src/compiler-flags/report-time.md
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
  src/libcore/slice/mod.rs
  src/librustc_arena/lib.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0583.md
  src/librustc_error_codes/error_codes/E0647.md
  src/librustc_error_codes/error_codes/E0761.md
  src/librustc_expand/module.rs
  src/librustc_mir/transform/validate.rs
  src/librustdoc/clean/types.rs
  src/libtest/cli.rs
  src/test/ui/mod/mod_file_disambig.stderr
Labels: S-waiting-on-bors, merged-by-bors

#73161 Add mailmap entry
  .mailmap
Labels: S-waiting-on-bors

#73149 typo: awailable -> available
  src/doc/unstable-book/src/compiler-flags/report-time.md
  src/libtest/cli.rs
Labels: S-waiting-on-bors

#73148 Fix a typo (size of the size)
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#73133 Enforce unwind invariants
  src/librustc_mir/transform/validate.rs
Labels: S-waiting-on-bors

#73123 Clean up E0647 explanation
  src/librustc_error_codes/error_codes/E0647.md
Labels: S-waiting-on-bors

#73122 Resolve E0584 conflict
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0583.md
  src/librustc_error_codes/error_codes/E0761.md
  src/librustc_expand/module.rs
  src/test/ui/mod/mod_file_disambig.stderr
Labels: S-waiting-on-bors

#73098 Add Item::is_fake for rustdoc
  src/librustdoc/clean/types.rs
Labels: S-waiting-on-bors

#72417 Remove `RawVec::reserve_in_place`.
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
  src/librustc_arena/lib.rs
Labels: S-waiting-on-bors

#73206 Rollup of 9 pull requests
  src/librustc_ast/ast.rs
  src/librustc_ast/mut_visit.rs
  src/librustc_ast_pretty/pprust.rs
  src/librustc_builtin_macros/deriving/generic/ty.rs
  src/librustc_lint/types.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_parse/parser/generics.rs
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/late/diagnostics.rs
  src/librustc_resolve/lib.rs
  src/librustc_target/spec/windows_gnu_base.rs
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/mod.rs
  src/librustc_trait_selection/traits/structural_match.rs
  src/test/ui/const-generics/issues/issue-72819-generic-in-const-eval.rs
  src/test/ui/const-generics/issues/issue-72819-generic-in-const-eval.stderr
  src/test/ui/derived-errors/issue-31997-1.stderr
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/impl-trait/auto-trait-leak.rs
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/issues/issue-17546.stderr
  src/test/ui/issues/issue-72839-error-overflow.rs
  src/test/ui/issues/issue-72839-error-overflow.stderr
  src/test/ui/lexical-scopes.stderr
  src/test/ui/lint/lint-ctypes-66202.rs
  src/test/ui/match/issue-72896.rs
  src/test/ui/no-implicit-prelude-nested.stderr
  src/test/ui/no-implicit-prelude.stderr
  src/test/ui/proc-macro/empty-where-clause.rs
  src/test/ui/proc-macro/empty-where-clause.stderr
  src/test/ui/proc-macro/mixed-site-span.stderr
  src/test/ui/resolve/use_suggestion.stderr
  src/test/ui/resolve/use_suggestion_placement.stderr
  triagebot.toml
Labels: S-waiting-on-bors, merged-by-bors

#73184 Reoder order in which MinGW libs are linked to fix recent breakage
  src/librustc_target/spec/windows_gnu_base.rs
Labels: S-waiting-on-bors, beta-nominated

#73157 Don't lose empty `where` clause when pretty-printing
  src/librustc_ast/ast.rs
  src/librustc_ast/mut_visit.rs
  src/librustc_ast_pretty/pprust.rs
  src/librustc_builtin_macros/deriving/generic/ty.rs
  src/librustc_parse/parser/generics.rs
  src/test/ui/proc-macro/empty-where-clause.rs
  src/test/ui/proc-macro/empty-where-clause.stderr
Labels: S-waiting-on-bors

#73070 Add regression test for const generic ICE in #72819
  src/test/ui/const-generics/issues/issue-72819-generic-in-const-eval.rs
  src/test/ui/const-generics/issues/issue-72819-generic-in-const-eval.stderr
Labels: S-waiting-on-bors

#73023 Remove noisy suggestion of hash_map
  src/librustc_resolve/diagnostics.rs
  src/test/ui/derived-errors/issue-31997-1.stderr
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/issues/issue-17546.stderr
  src/test/ui/no-implicit-prelude-nested.stderr
  src/test/ui/no-implicit-prelude.stderr
  src/test/ui/resolve/use_suggestion.stderr
  src/test/ui/resolve/use_suggestion_placement.stderr
Labels: S-waiting-on-bors

#73005 Don't create impl candidates when obligation contains errors
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/mod.rs
  src/test/ui/impl-trait/auto-trait-leak.rs
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/issues/issue-72839-error-overflow.rs
  src/test/ui/issues/issue-72839-error-overflow.stderr
Labels: S-waiting-on-bors, beta-nominated

#72897 normalize adt fields during structural match checking
  src/librustc_trait_selection/traits/structural_match.rs
  src/test/ui/match/issue-72896.rs
Labels: S-waiting-on-bors

#72890 improper ctypes: normalize return types and transparent structs
  src/librustc_lint/types.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/sty.rs
  src/test/ui/lint/lint-ctypes-66202.rs
Labels: S-waiting-on-bors

#72789 resolve: Do not suggest imports from the same module in which we are resolving
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/late/diagnostics.rs
  src/librustc_resolve/lib.rs
  src/test/ui/lexical-scopes.stderr
  src/test/ui/proc-macro/mixed-site-span.stderr
Labels: S-waiting-on-bors

#72706 Add windows group to triagebot
  triagebot.toml
Labels: S-waiting-on-bors

#71896 Relate existential associated types with variance Invariant
  src/librustc_middle/ty/relate.rs
  src/test/ui/coercion/coerce-expect-unsized-ascribed.stderr
  src/test/ui/issues/issue-20605.stderr
  src/test/ui/variance/variance-associated-types2.nll.stderr
  src/test/ui/variance/variance-associated-types2.rs
  src/test/ui/variance/variance-associated-types2.stderr
Labels: S-waiting-on-bors, merged-by-bors, relnotes

#73235 Rollup of 11 pull requests
  src/bootstrap/compile.rs
  src/doc/rustdoc/src/documentation-tests.md
  src/libcore/num/mod.rs
  src/librustc_ast/tokenstream.rs
  src/librustc_ast_lowering/expr.rs
  src/librustc_builtin_macros/asm.rs
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0642.md
  src/librustc_error_codes/error_codes/E0762.md
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_hir_pretty/lib.rs
  src/librustc_infer/infer/error_reporting/need_type_info.rs
  src/librustc_infer/infer/error_reporting/nice_region_error/trait_impl_difference.rs
  src/librustc_lexer/src/lib.rs
  src/librustc_middle/hir/map/mod.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/transform/check_packed_ref.rs
  src/librustc_mir/transform/nrvo.rs
  src/librustc_mir/transform/simplify_try.rs
  src/librustc_mir_build/build/matches/mod.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_parse/parser/diagnostics.rs
  src/librustc_parse/parser/mod.rs
  src/librustc_passes/intrinsicck.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/sig.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/auxiliary/intra-link-proc-macro-macro.rs
  src/test/rustdoc/intra-link-proc-macro.rs
  src/test/ui/consts/enum-discr-type-err.stderr
  src/test/ui/issues/issue-31910.stderr
  src/test/ui/issues/issue-72933-match-stack-overflow.rs
  src/test/ui/numeric/const-scope.stderr
  src/test/ui/parser/lex-bad-char-literals-4.stderr
  src/test/ui/parser/lex-bad-char-literals-7.stderr
  src/test/ui/repeat_count.rs
  src/test/ui/repeat_count.stderr
  triagebot.toml
Labels: S-waiting-on-bors, merged-by-bors

#73219 x.py: with --json-output, forward cargo's JSON
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#73208 Fix doctest template
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#73183 Support proc macros in intra doc link resolution
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/auxiliary/intra-link-proc-macro-macro.rs
  src/test/rustdoc/intra-link-proc-macro.rs
Labels: S-waiting-on-bors

#73181 Automatically prioritize unsoundness issues
  triagebot.toml
Labels: S-waiting-on-bors

#73172 Fix more clippy warnings
  src/librustc_ast/tokenstream.rs
  src/librustc_ast_lowering/expr.rs
  src/librustc_builtin_macros/asm.rs
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_infer/infer/error_reporting/need_type_info.rs
  src/librustc_infer/infer/error_reporting/nice_region_error/trait_impl_difference.rs
  src/librustc_lexer/src/lib.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/transform/check_packed_ref.rs
  src/librustc_mir/transform/nrvo.rs
  src/librustc_mir/transform/simplify_try.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_parse/parser/diagnostics.rs
  src/librustc_parse/parser/mod.rs
  src/librustc_passes/intrinsicck.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: S-waiting-on-bors

#73164 Add new E0762 error code
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0762.md
  src/librustc_parse/lexer/mod.rs
  src/test/ui/parser/lex-bad-char-literals-4.stderr
  src/test/ui/parser/lex-bad-char-literals-7.stderr
Labels: S-waiting-on-bors

#73155 save_analysis: better handle paths and functions signature
  src/librustc_hir_pretty/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_save_analysis/sig.rs
Labels: S-waiting-on-bors

#73080 doc/rustdoc: Fix incorrect external_doc feature flag
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#72976 Clean up E0642 explanation
  src/librustc_error_codes/error_codes/E0642.md
Labels: S-waiting-on-bors

#72941 Ensure stack when building MIR for matches
  src/librustc_mir_build/build/matches/mod.rs
  src/test/ui/issues/issue-72933-match-stack-overflow.rs
Labels: S-waiting-on-bors, beta-nominated

#72380 Fix `is_const_context`, update `check_for_cast`
  src/librustc_middle/hir/map/mod.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/consts/enum-discr-type-err.stderr
  src/test/ui/issues/issue-31910.stderr
  src/test/ui/numeric/const-scope.stderr
  src/test/ui/repeat_count.rs
  src/test/ui/repeat_count.stderr
Labels: S-waiting-on-bors

#73230 Suggest including unused asm arguments in a comment to avoid error
  src/doc/unstable-book/src/library-features/asm.md
  src/librustc_builtin_macros/asm.rs
  src/test/ui/asm/bad-template.rs
  src/test/ui/asm/bad-template.stderr
  src/test/ui/asm/parse-error.stderr
Labels: S-waiting-on-bors

#73207 Clean up E0648 explanation
  src/librustc_error_codes/error_codes/E0648.md
Labels: S-waiting-on-bors

#73169 Handle assembler warnings properly
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/llvm/diagnostic.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_errors/lib.rs
  src/librustc_session/session.rs
  src/rustllvm/RustWrapper.cpp
  src/test/ui/asm/srcloc.rs
  src/test/ui/asm/srcloc.stderr
Labels: S-waiting-on-bors

#73097 Try_run must only be used if toolstate is populated
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#73012 Show `SyntaxContext` in formatted `Span` debug output
  src/librustc_interface/callbacks.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/ty/print/pretty.rs
  src/librustc_mir/borrow_check/nll.rs
  src/librustc_mir/borrow_check/region_infer/dump_mir.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_span/lib.rs
  src/test/ui/proc-macro/debug/dump-debug-span-debug.stderr
Labels: S-waiting-on-bors

#72180 remove extra space from crate-level doctest names
  src/librustdoc/test.rs
  src/test/rustdoc-ui/doctest-output.rs
  src/test/rustdoc-ui/doctest-output.stdout
Labels: S-waiting-on-bors

#73259 Rollup of 7 pull requests
  src/libcore/sync/atomic.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0724.md
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/hair/cx/expr.rs
  src/librustc_mir_build/hair/mod.rs
  src/librustc_span/def_id.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/expr.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/op.rs
  src/libunwind/build.rs
  src/test/ui/asm/sym.rs
  src/test/ui/ffi_returns_twice.stderr
  src/test/ui/numeric/numeric-cast-binop.fixed
  src/test/ui/numeric/numeric-cast-binop.rs
  src/test/ui/numeric/numeric-cast-binop.stderr
  triagebot.toml
Labels: S-waiting-on-bors, merged-by-bors

#73254 Add comment about LocalDefId -> DefId
  src/librustc_span/def_id.rs
Labels: S-waiting-on-bors

#73247 Add various Zulip notifications for prioritization
  triagebot.toml
Labels: S-waiting-on-bors

#73195 Provide suggestion to convert numeric op LHS rather than unwrapping RHS
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/expr.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/op.rs
  src/test/ui/numeric/numeric-cast-binop.fixed
  src/test/ui/numeric/numeric-cast-binop.rs
  src/test/ui/numeric/numeric-cast-binop.stderr
Labels: S-waiting-on-bors

#73187 Remove missed `cfg(bootstrap)`
  src/libunwind/build.rs
Labels: S-waiting-on-bors

#73163 Add long error explanation for E0724
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0724.md
  src/test/ui/ffi_returns_twice.stderr
Labels: S-waiting-on-bors

#73036 std: Enable atomic.fence emission on wasm32
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#73033 Fix #[thread_local] statics as asm! sym operands
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/hair/cx/expr.rs
  src/librustc_mir_build/hair/mod.rs
  src/test/ui/asm/sym.rs
Labels: S-waiting-on-bors
