Repository rust-lang/rust, pull requests merged in 2020-04, with the labels that each got.

#70632 expand vec![] to Vec::new()
  src/liballoc/macros.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#70605 Add missing -lmsvcrt on mingw after -lpthread
  src/librustc_target/spec/windows_base.rs
Labels: S-waiting-on-bors

#70556 parse_and_disallow_postfix_after_cast: account for `ExprKind::Err`.
  src/librustc_parse/parser/expr.rs
  src/test/ui/parser/issue-70552-ascription-in-parens-after-call.rs
  src/test/ui/parser/issue-70552-ascription-in-parens-after-call.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#70081 add `unused_braces` lint
  src/libcore/array/iter.rs
  src/librustc_lint/early.rs
  src/librustc_lint/lib.rs
  src/librustc_lint/passes.rs
  src/librustc_lint/unused.rs
  src/librustc_macros/src/query.rs
  src/librustc_resolve/lib.rs
  src/libstd/sys/windows/handle.rs
  src/test/incremental/const-generics/issue-61516.rs
  src/test/ui/array-slice-vec/vec-fixed-length.rs
  src/test/ui/block-fn-coerce.rs
  src/test/ui/cleanup-rvalue-scopes.rs
  src/test/ui/coerce/coerce-expect-unsized.rs
  src/test/ui/coerce/coerce-overloaded-autoderef.rs
  src/test/ui/const-generics/issues/issue-62504.rs
  src/test/ui/const-generics/issues/issue-70125-2.rs
  src/test/ui/const-generics/unused_braces.rs
  src/test/ui/const-generics/unused_braces.stderr
  src/test/ui/consts/const-block.rs
  src/test/ui/expr-block-generic-unique1.rs
  src/test/ui/expr-block-generic-unique2.rs
  src/test/ui/expr-block-generic.rs
  src/test/ui/expr-block-unique.rs
  src/test/ui/expr-block.rs
  src/test/ui/expr-fn.rs
  src/test/ui/functions-closures/closure-inference.rs
  src/test/ui/functions-closures/closure-inference2.rs
  src/test/ui/intrinsics/intrinsic-move-val-cleanups.rs
  src/test/ui/issues/issue-23898.rs
  src/test/ui/issues/issue-28777.rs
  src/test/ui/lint/lint-unnecessary-parens.rs
  src/test/ui/lint/lint-unnecessary-parens.stderr
  src/test/ui/lint/unused_braces.rs
  src/test/ui/lint/unused_braces.stderr
  src/test/ui/lint/unused_parens_borrow.rs
  src/test/ui/lint/unused_parens_borrow.stderr
  src/test/ui/lint/unused_parens_remove_json_suggestion.stderr
  src/test/ui/range.rs
  src/test/ui/range_inclusive.rs
  src/test/ui/structs-enums/empty-tag.rs
  src/test/ui/type-alias-impl-trait/assoc-type-const.rs
  src/test/ui/unsized-locals/unsized-exprs-rpass.rs
  src/test/ui/weird-exprs.rs
  src/test/ui/zero-sized/zero-sized-tuple-struct.rs
Labels: F-const_generics, S-waiting-on-bors, T-lang

#68770 BTreeMap/BTreeSet: implement drain_filter
  src/liballoc/benches/btree/set.rs
  src/liballoc/benches/lib.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/tests/btree/map.rs
  src/liballoc/tests/btree/set.rs
  src/liballoc/tests/lib.rs
Labels: S-waiting-on-bors

#70414 Upgrade GCC to 8.3.0, glibc to 2.17.0 and crosstool-ng to 1.24.0 for dist-arm-linux and dist-armhf-linux
  src/ci/docker/README.md
  src/ci/docker/dist-arm-linux/Dockerfile
  src/ci/docker/dist-arm-linux/arm-linux-gnueabi.config
  src/ci/docker/dist-arm-linux/patches/glibc/ports-2.16.0/001-arm-libgcc_s_resume-used.patch
  src/ci/docker/dist-armhf-linux/Dockerfile
  src/ci/docker/dist-armhf-linux/arm-linux-gnueabihf.config
  src/ci/docker/dist-armhf-linux/patches/glibc/ports-2.16.0/001-arm-libgcc_s_resume-used.patch
  src/ci/docker/dist-armv7-linux/Dockerfile
  src/ci/docker/scripts/crosstool-ng-1.24.sh
Labels: S-waiting-on-bors, merged-by-bors

#70652 Add git repo address to unstable book
  src/doc/unstable-book/book.toml
Labels: S-waiting-on-bors

#70627 Use place directly its copy
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_mir/borrow_check/borrow_set.rs
  src/librustc_mir/borrow_check/constraint_generation.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/borrow_check/diagnostics/explain_borrow.rs
  src/librustc_mir/borrow_check/diagnostics/move_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_mir/borrow_check/invalidation.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/path_utils.rs
  src/librustc_mir/borrow_check/places_conflict.rs
  src/librustc_mir/borrow_check/used_muts.rs
  src/librustc_mir/dataflow/drop_flag_effects.rs
  src/librustc_mir/dataflow/framework/cursor.rs
  src/librustc_mir/dataflow/framework/engine.rs
  src/librustc_mir/dataflow/framework/mod.rs
  src/librustc_mir/dataflow/framework/tests.rs
  src/librustc_mir/dataflow/impls/borrowed_locals.rs
  src/librustc_mir/dataflow/impls/borrows.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/dataflow/impls/storage_liveness.rs
  src/librustc_mir/dataflow/move_paths/builder.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/add_moves_for_packed_drops.rs
  src/librustc_mir/transform/check_consts/resolver.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/transform/copy_prop.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir/transform/rustc_peek.rs
  src/librustc_mir/transform/simplify_try.rs
  src/librustc_mir/util/alignment.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_mir_build/build/block.rs
  src/librustc_mir_build/build/cfg.rs
  src/librustc_mir_build/build/expr/as_place.rs
  src/librustc_mir_build/build/expr/as_rvalue.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/build/expr/stmt.rs
  src/librustc_mir_build/build/into.rs
  src/librustc_mir_build/build/matches/mod.rs
  src/librustc_mir_build/build/matches/test.rs
  src/librustc_mir_build/build/misc.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/build/scope.rs
Labels: S-waiting-on-bors

#70591 Ensure LLVM is in the link path for "fulldeps" tests
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#70547 Add `can_unwind` field to `FnAbi`
  src/librustc_codegen_llvm/abi.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/callee.rs
  src/librustc_codegen_llvm/mono_item.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_target/abi/call/mod.rs
Labels: S-waiting-on-bors

#70522 Improve error messages for raw strings (#60762)
  src/librustc_lexer/src/lib.rs
  src/librustc_lexer/src/tests.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_parse/lib.rs
  src/librustc_parse/parser/diagnostics.rs
  src/test/ui/parser/raw-str-unbalanced.rs
  src/test/ui/parser/raw-str-unbalanced.stderr
  src/test/ui/parser/raw/raw-byte-string-eof.rs
  src/test/ui/parser/raw/raw-byte-string-eof.stderr
  src/test/ui/parser/raw/raw-byte-string-literals.rs
  src/test/ui/parser/raw/raw-byte-string-literals.stderr
  src/test/ui/parser/raw/raw-str-delim.rs
  src/test/ui/parser/raw/raw-str-delim.stderr
  src/test/ui/parser/raw/raw-str-in-macro-call.rs
  src/test/ui/parser/raw/raw-str-unbalanced.rs
  src/test/ui/parser/raw/raw-str-unbalanced.stderr
  src/test/ui/parser/raw/raw-str-unterminated.rs
  src/test/ui/parser/raw/raw-str-unterminated.stderr
  src/test/ui/parser/raw/raw-string-2.rs
  src/test/ui/parser/raw/raw-string-2.stderr
  src/test/ui/parser/raw/raw-string.rs
  src/test/ui/parser/raw/raw-string.stderr
Labels: S-waiting-on-bors

#70511 Add `-Z dump-mir-dataflow` flag for dumping dataflow results visualization
  src/librustc_interface/tests.rs
  src/librustc_mir/borrow_check/nll.rs
  src/librustc_mir/dataflow/framework/engine.rs
  src/librustc_mir/transform/dump_mir.rs
  src/librustc_mir/util/liveness.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_session/options.rs
Labels: S-waiting-on-bors

#70672 Rollup of 6 pull requests
  src/librustc_codegen_llvm/type_of.rs
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_error_codes/error_codes/E0468.md
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/traits/specialization_graph.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_mir/const_eval/error.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/const_eval/machine.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/interpret/intrinsics/caller_location.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/interpret/visitor.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_target/abi/call/mips64.rs
  src/librustc_target/abi/call/mod.rs
  src/librustc_target/abi/call/riscv.rs
  src/librustc_target/abi/mod.rs
  src/librustc_trait_selection/traits/mod.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_trait_selection/traits/util.rs
  src/librustc_ty/instance.rs
  src/librustc_ty/ty.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/consts/const-eval/validate_uninhabited_zsts.stderr
  src/test/ui/consts/miri_unleashed/abi-mismatch.stderr
  src/test/ui/consts/miri_unleashed/drop.stderr
  src/test/ui/consts/offset_from_ub.stderr
  src/test/ui/consts/uninhabited-const-issue-61744.stderr
  src/test/ui/specialization/issue-70442.rs
  src/tools/cargotest/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70662 compiletest: don't use `std::io::stdout()`, as it bypasses `set_print`.
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#70649 clean up E0468 explanation
  src/librustc_error_codes/error_codes/E0468.md
Labels: S-waiting-on-bors

#70626 cargotest: remove webrender
  src/tools/cargotest/main.rs
Labels: S-waiting-on-bors

#70616 rustc_target::abi: rename FieldPlacement to FieldsShape.
  src/librustc_codegen_llvm/type_of.rs
  src/librustc_codegen_ssa/mir/place.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/visitor.rs
  src/librustc_target/abi/call/mips64.rs
  src/librustc_target/abi/call/mod.rs
  src/librustc_target/abi/call/riscv.rs
  src/librustc_target/abi/mod.rs
Labels: S-waiting-on-bors

#70590 Miri: make backtrace function names and spans match up
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_mir/const_eval/error.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/const_eval/machine.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/interpret/intrinsics/caller_location.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/consts/const-eval/validate_uninhabited_zsts.stderr
  src/test/ui/consts/miri_unleashed/abi-mismatch.stderr
  src/test/ui/consts/miri_unleashed/drop.stderr
  src/test/ui/consts/offset_from_ub.stderr
  src/test/ui/consts/uninhabited-const-issue-61744.stderr
Labels: S-waiting-on-bors

#70535 Track the finalizing node in the specialization graph
  src/librustc_middle/traits/specialization_graph.rs
  src/librustc_trait_selection/traits/mod.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_trait_selection/traits/util.rs
  src/librustc_ty/instance.rs
  src/librustc_ty/ty.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/specialization/issue-70442.rs
Labels: F-associated_type_defaults, F-specialization, S-waiting-on-bors

#70362 Overhaul of the `AllocRef` trait to match allocator-wg's latest consens; Take 2
  src/liballoc/alloc.rs
  src/liballoc/alloc/tests.rs
  src/liballoc/boxed.rs
  src/liballoc/collections/btree/node.rs
  src/liballoc/lib.rs
  src/liballoc/raw_vec.rs
  src/liballoc/raw_vec/tests.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/liballoc/tests/heap.rs
  src/liballoc/vec.rs
  src/libcore/alloc.rs
  src/libcore/alloc/global.rs
  src/libcore/alloc/layout.rs
  src/libcore/alloc/mod.rs
  src/libstd/alloc.rs
  src/libstd/error.rs
  src/test/ui/allocator/custom.rs
  src/test/ui/allocator/xcrate-use.rs
  src/test/ui/realloc-16687.rs
  src/test/ui/regions/regions-mock-codegen.rs
Labels: S-waiting-on-bors, merged-by-bors

#70628 GHA: enable running multiple try builds at the same time
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
Labels: S-waiting-on-bors, merged-by-bors

#70681 Handle unterminated raw strings with no #s properly
  src/librustc_lexer/src/lib.rs
  src/librustc_lexer/src/tests.rs
  src/test/ui/parser/raw/issue-70677-panic-on-unterminated-raw-str-at-eof.rs
  src/test/ui/parser/raw/issue-70677-panic-on-unterminated-raw-str-at-eof.stderr
Labels: S-waiting-on-bors

#70678 Add missing markdown rust annotation
  src/doc/unstable-book/src/language-features/generators.md
Labels: S-waiting-on-bors

#70658 add `STILL_FURTHER_SPECIALIZABLE` flag
  src/librustc_middle/ty/flags.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_ty/instance.rs
Labels: S-waiting-on-bors

#70615 Renamed `PerDefTables` to `Tables`
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_metadata/rmeta/mod.rs
Labels: S-waiting-on-bors

#70421 parse: recover on `const fn()` / `async fn()`
  src/librustc_parse/parser/item.rs
  src/librustc_parse/parser/ty.rs
  src/test/ui/keyword/extern/keyword-extern-as-identifier-type.rs
  src/test/ui/keyword/extern/keyword-extern-as-identifier-type.stderr
  src/test/ui/parser/issue-63116.stderr
  src/test/ui/parser/recover-const-async-fn-ptr.rs
  src/test/ui/parser/recover-const-async-fn-ptr.stderr
Labels: S-waiting-on-bors

#70281 Implement Hash for Infallible
  src/libcore/convert/mod.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#70722 Rollup of 7 pull requests
  src/libcore/alloc/mod.rs
  src/libcore/convert/num.rs
  src/libcore/intrinsics.rs
  src/libcore/macros/mod.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/mod.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_mir/transform/simplify.rs
  src/librustc_typeck/check/intrinsic.rs
  src/librustc_typeck/collect/type_of.rs
  src/libstd/fs.rs
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads.rs
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify_try.rs
  src/test/ui/suggestions/const-no-type.rs
  src/test/ui/suggestions/const-no-type.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70716 Unerase regions in infer_placeholder_type
  src/librustc_typeck/collect/type_of.rs
  src/test/ui/suggestions/const-no-type.rs
  src/test/ui/suggestions/const-no-type.stderr
Labels: S-waiting-on-bors

#70708 Fix typo in u8::to_ascii_uppercase and u8::to_ascii_lowercase
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#70700 Expand on platform details of `include_xxx` macros
  src/libcore/macros/mod.rs
Labels: S-waiting-on-bors

#70694 Use Self over specific type in return position
  src/libstd/fs.rs
Labels: S-waiting-on-bors

#70691 Improve docs in `AllocRef`
  src/libcore/alloc/mod.rs
Labels: S-waiting-on-bors

#70595 Remove unused discriminant reads from MIR bodies
  src/librustc_mir/transform/simplify.rs
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads.rs
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify_try.rs
Labels: S-waiting-on-bors

#70487 Stabilize float::to_int_unchecked
  src/libcore/convert/num.rs
  src/libcore/intrinsics.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_typeck/check/intrinsic.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#70726 Rollup of 5 pull requests
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
  src/bootstrap/flags.rs
  src/ci/docker/dist-various-1/Dockerfile
  src/ci/docker/dist-various-1/install-aarch64-none-elf.sh
  src/doc/unstable-book/src/library-features/llvm-asm.md
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/mod.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/tools/build-manifest/src/main.rs
  src/tools/rustdoc-js-common/lib.js
  src/tools/rustdoc-js-std/tester.js
  src/tools/rustdoc-js/tester.js
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70715 Fix typo in operands section
  src/doc/unstable-book/src/library-features/llvm-asm.md
Labels: S-waiting-on-bors

#70698 bootstrap: add `--json-output` for rust-analyzer
  src/bootstrap/compile.rs
  src/bootstrap/config.rs
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#70224 Clean up rustdoc js testers
  src/tools/rustdoc-js-common/lib.js
  src/tools/rustdoc-js-std/tester.js
  src/tools/rustdoc-js/tester.js
Labels: S-waiting-on-bors

#68334 AArch64 bare-metal targets: Build rust-std
  src/ci/docker/dist-various-1/Dockerfile
  src/ci/docker/dist-various-1/install-aarch64-none-elf.sh
  src/tools/build-manifest/src/main.rs
Labels: O-ARM, S-waiting-on-author, T-compiler, WG-embedded, relnotes

#70731 Minor follow-up after renaming librustc(_middle)
  src/libcore/clone.rs
  src/libcore/marker.rs
  src/libcore/raw.rs
  src/librustc_infer/infer/lexical_region_resolve/graphviz.rs
  src/librustc_mir/borrow_check/region_infer/mod.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_passes/region.rs
  src/librustc_passes/stability.rs
  src/librustc_session/filesearch.rs
  src/librustc_session/lint.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_traits/implied_outlives_bounds.rs
  src/librustc_ty/instance.rs
  src/libstd/alloc.rs
Labels: S-waiting-on-bors

#70730 Fix link in task::Wake docs
  src/liballoc/task.rs
Labels: S-waiting-on-bors

#70728 Minor doc improvements on `AllocRef`
  src/libcore/alloc/mod.rs
Labels: S-waiting-on-bors

#70725 Avoid `.unwrap()`s on `.span_to_snippet(...)`s
  src/librustc_parse/parser/stmt.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/closure.rs
  src/librustc_typeck/check/op.rs
  src/test/ui/issues/issue-70724-add_type_neq_err_label-unwrap.rs
  src/test/ui/issues/issue-70724-add_type_neq_err_label-unwrap.stderr
Labels: S-waiting-on-bors

#70706 Minor cleanup in rustdoc --check-theme
  src/librustdoc/theme.rs
Labels: S-waiting-on-bors

#70742 [beta] backport 4 PRs
  src/librustc/ty/mod.rs
  src/librustc/ty/sty.rs
  src/librustc_parse/parser/expr.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/collect.rs
  src/libstd/sync/once.rs
  src/test/ui/did_you_mean/bad-assoc-ty.rs
  src/test/ui/did_you_mean/bad-assoc-ty.stderr
  src/test/ui/parser/issue-70552-ascription-in-parens-after-call.rs
  src/test/ui/parser/issue-70552-ascription-in-parens-after-call.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.rs
  src/test/ui/typeck/typeck_type_placeholder_item.stderr
Labels: S-waiting-on-bors, merged-by-bors

#70747 Rollup of 9 pull requests
  src/liballoc/slice.rs
  src/liballoc/str.rs
  src/libcore/cmp.rs
  src/libcore/fmt/mod.rs
  src/libcore/hint.rs
  src/libcore/intrinsics.rs
  src/libcore/iter/traits/iterator.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/mod.rs
  src/libcore/ops/range.rs
  src/libcore/ptr/const_ptr.rs
  src/libcore/ptr/mut_ptr.rs
  src/libcore/slice/mod.rs
  src/libcore/time.rs
  src/librustc_ast_lowering/item.rs
  src/librustc_codegen_llvm/consts.rs
  src/librustc_error_codes/error_codes/E0502.md
  src/librustc_infer/traits/mod.rs
  src/librustc_infer/traits/util.rs
  src/librustc_metadata/native_libs.rs
  src/librustc_mir/dataflow/graphviz.rs
  src/librustc_target/abi/mod.rs
  src/librustc_trait_selection/traits/util.rs
  src/libstd/f32.rs
  src/libstd/f64.rs
  src/libstd/sys/cloudabi/stack_overflow.rs
  src/libstd/sys/cloudabi/thread.rs
  src/libstd/sys/hermit/stack_overflow.rs
  src/libstd/sys/hermit/thread.rs
  src/libstd/sys/sgx/stack_overflow.rs
  src/libstd/sys/unix/thread.rs
  src/libstd/sys/vxworks/thread.rs
  src/libstd/sys/wasm/stack_overflow.rs
  src/libstd/sys/windows/thread.rs
  src/libstd/sys_common/thread.rs
  src/test/ui/async-await/issue-70594.rs
  src/test/ui/async-await/issue-70594.stderr
  src/test/ui/feature-gates/feature-gate-link_cfg.stderr
  src/test/ui/issues/issue-70673.rs
  src/test/ui/traits/impl_trait_as_trait_return_position.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70741 Add test for #59023
  src/test/ui/traits/impl_trait_as_trait_return_position.rs
Labels: S-waiting-on-bors

#70735 Clean up E0502 explanation
  src/librustc_error_codes/error_codes/E0502.md
Labels: S-waiting-on-bors

#70720 Place TLS initializers with relocations in .tdata
  src/librustc_codegen_llvm/consts.rs
  src/test/ui/issues/issue-70673.rs
Labels: S-waiting-on-bors

#70707 Remove unused graphviz emitter
  src/librustc_mir/dataflow/graphviz.rs
Labels: S-waiting-on-bors

#70641 Remove duplicated code in trait selection
  src/librustc_infer/traits/mod.rs
  src/librustc_infer/traits/util.rs
  src/librustc_trait_selection/traits/util.rs
Labels: S-waiting-on-bors

#70640 Hide `task_context` when lowering body
  src/librustc_ast_lowering/item.rs
  src/test/ui/async-await/issue-70594.rs
  src/test/ui/async-await/issue-70594.stderr
Labels: S-waiting-on-bors

#70597 Fix double-free and undefined behaviour in libstd::syn::unix::Thread::new
  src/libstd/sys/cloudabi/stack_overflow.rs
  src/libstd/sys/cloudabi/thread.rs
  src/libstd/sys/hermit/stack_overflow.rs
  src/libstd/sys/hermit/thread.rs
  src/libstd/sys/sgx/stack_overflow.rs
  src/libstd/sys/unix/thread.rs
  src/libstd/sys/vxworks/thread.rs
  src/libstd/sys/wasm/stack_overflow.rs
  src/libstd/sys/windows/thread.rs
  src/libstd/sys_common/thread.rs
Labels: S-waiting-on-bors

#70576 Update the description of the ticket to point at RFC 1721
  src/librustc_metadata/native_libs.rs
  src/test/ui/feature-gates/feature-gate-link_cfg.stderr
Labels: S-waiting-on-bors

#69860 Use associated numeric consts in documentation
  src/liballoc/slice.rs
  src/liballoc/str.rs
  src/libcore/cmp.rs
  src/libcore/fmt/mod.rs
  src/libcore/hint.rs
  src/libcore/intrinsics.rs
  src/libcore/iter/traits/iterator.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/mod.rs
  src/libcore/ops/range.rs
  src/libcore/ptr/const_ptr.rs
  src/libcore/ptr/mut_ptr.rs
  src/libcore/slice/mod.rs
  src/libcore/time.rs
  src/librustc_target/abi/mod.rs
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#70156 Make the rustc respect the `-C codegen-units` flag in incremental mode.
  src/doc/rustc/src/codegen-options/index.md
  src/librustc_mir/monomorphize/partitioning.rs
  src/librustc_session/session.rs
  src/test/codegen-units/partitioning/incremental-merging.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors, relnotes

#69718 Add hash of source files in debug info
  Cargo.lock
  src/doc/unstable-book/src/compiler-flags/src-hash-algorithm.md
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_interface/util.rs
  src/librustc_middle/ich/impls_syntax.rs
  src/librustc_session/config.rs
  src/librustc_session/options.rs
  src/librustc_session/session.rs
  src/librustc_span/Cargo.toml
  src/librustc_span/lib.rs
  src/librustc_span/source_map.rs
  src/libserialize/serialize.rs
  src/rustllvm/RustWrapper.cpp
  src/test/codegen/remap_path_prefix/main.rs
  src/test/codegen/remap_path_prefix/xcrate-generic.rs
  src/test/codegen/src-hash-algorithm/src-hash-algorithm-md5.rs
  src/test/codegen/src-hash-algorithm/src-hash-algorithm-sha1.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#70136 add basic IP support in HermitCore
  Cargo.lock
  src/libstd/sys/hermit/mod.rs
  src/libstd/sys/hermit/net.rs
Labels: S-waiting-on-bors, merged-by-bors

#70272 typeck/type_of: let wfcheck handle generics in opaque types' substs.
  src/librustc_middle/ty/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/collect/type_of.rs
  src/test/ui/type-alias-impl-trait/bound_reduction2.rs
  src/test/ui/type-alias-impl-trait/bound_reduction2.stderr
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use.rs
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use.stderr
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use2.rs
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use2.stderr
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use3.rs
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use3.stderr
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use4.rs
  src/test/ui/type-alias-impl-trait/generic_duplicate_param_use4.stderr
  src/test/ui/type-alias-impl-trait/generic_nondefining_use.rs
  src/test/ui/type-alias-impl-trait/generic_nondefining_use.stderr
  src/test/ui/type-alias-impl-trait/issue-60564.rs
  src/test/ui/type-alias-impl-trait/issue-60564.stderr
  src/test/ui/type-alias-impl-trait/issue-68368-non-defining-use.rs
  src/test/ui/type-alias-impl-trait/issue-68368-non-defining-use.stderr
  src/test/ui/type-alias-impl-trait/not_a_defining_use.rs
  src/test/ui/type-alias-impl-trait/not_a_defining_use.stderr
Labels: F-type_alias_impl_trait, S-waiting-on-bors, merged-by-bors

#70683 update openssl-src to 111.8.1+1.1.1f
  Cargo.lock
Labels: S-waiting-on-bors, merged-by-bors

#70800 Rollup of 6 pull requests
  src/liballoc/boxed.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
  src/libcore/slice/mod.rs
  src/librustc_driver/lib.rs
  src/librustc_expand/mbe/macro_parser.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_target/spec/hermit_base.rs
  src/librustc_target/spec/hermit_kernel_base.rs
  src/librustc_target/spec/windows_base.rs
  src/librustc_target/spec/windows_uwp_base.rs
  src/test/ui/macros/issue-70446.rs
  src/test/ui/type-sizes.rs
Labels: S-waiting-on-bors, merged-by-bors

#70783 comment refers to removed type
  src/librustc_driver/lib.rs
Labels: S-waiting-on-bors

#70768 macro_rules: `NtLifetime` cannot start with an identifier
  src/librustc_expand/mbe/macro_parser.rs
  src/test/ui/macros/issue-70446.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#70766 use ManuallyDrop instead of forget inside collections
  src/liballoc/boxed.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/vec_deque.rs
  src/liballoc/raw_vec.rs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#70752 Add slice::fill
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors

#70748 Do not disable field reordering on enums with big discriminant
  src/librustc_middle/ty/layout.rs
  src/test/ui/type-sizes.rs
Labels: S-waiting-on-bors

#70635 rustc_target: Some cleanup to `no_default_libraries`
  src/librustc_target/spec/hermit_base.rs
  src/librustc_target/spec/hermit_kernel_base.rs
  src/librustc_target/spec/windows_base.rs
  src/librustc_target/spec/windows_uwp_base.rs
Labels: S-waiting-on-bors

#70803 Fix performance regression in debuginfo file_metadata.
  src/librustc_codegen_llvm/debuginfo/create_scope_map.rs
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/debuginfo/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#70807 Rollup of 5 pull requests
  src/liballoc/raw_vec.rs
  src/liballoc/tests/vec.rs
  src/liballoc/vec.rs
  src/libcore/result.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/terminator.rs
  src/test/ui/consts/const-eval/issue-70804-fn-subtyping.rs
Labels: S-waiting-on-bors, merged-by-bors

#70806 fix Miri assignment sanity check
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/test/ui/consts/const-eval/issue-70804-fn-subtyping.rs
Labels: S-waiting-on-bors

#70776 clarify comment in RawVec::into_box
  src/liballoc/raw_vec.rs
Labels: S-waiting-on-bors

#70769 Miri: remove an outdated FIXME
  src/librustc_mir/interpret/terminator.rs
Labels: S-waiting-on-bors

#70760 docs: make the description of Result::map_or more clear
  src/libcore/result.rs
Labels: S-waiting-on-bors

#70558 Fix some aliasing issues in Vec
  src/liballoc/tests/vec.rs
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#70816 Rollup of 5 pull requests
  src/etc/test-float-parse/u64-pow2.rs
  src/liballoc/alloc.rs
  src/liballoc/collections/binary_heap.rs
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/node.rs
  src/liballoc/rc.rs
  src/liballoc/slice.rs
  src/liballoc/sync.rs
  src/liballoc/tests.rs
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/libcore/benches/num/flt2dec/strategy/dragon.rs
  src/libcore/benches/num/flt2dec/strategy/grisu.rs
  src/libcore/tests/fmt/num.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/num/dec2flt/mod.rs
  src/libcore/tests/num/flt2dec/mod.rs
  src/libcore/tests/num/flt2dec/random.rs
  src/libcore/tests/num/int_macros.rs
  src/librustc_ast/util/comments.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_data_structures/graph/implementation/mod.rs
  src/librustc_data_structures/profiling.rs
  src/librustc_index/vec.rs
  src/librustc_infer/infer/type_variable.rs
  src/librustc_interface/callbacks.rs
  src/librustc_lint/types.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/ty/instance.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/query/keys.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir_build/build/matches/util.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_passes/layout_test.rs
  src/librustc_passes/liveness.rs
  src/librustc_span/def_id.rs
  src/librustc_ty/instance.rs
  src/librustc_ty/lib.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/passes/unindent_comments.rs
  src/libserialize/tests/json.rs
  src/libstd/primitive_docs.rs
  src/libstd/sync/mpsc/shared.rs
  src/libstd/sync/mpsc/stream.rs
  src/libstd/sync/mpsc/sync.rs
  src/libstd/sys/hermit/thread.rs
  src/test/ui/layout/debug.rs
  src/test/ui/layout/debug.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70815 Enable layout debugging for `impl Trait` type aliases
  src/librustc_passes/layout_test.rs
  src/test/ui/layout/debug.rs
  src/test/ui/layout/debug.stderr
Labels: S-waiting-on-bors

#70812 Do not use "nil" to refer to `()`
  src/libstd/primitive_docs.rs
Labels: S-waiting-on-bors

#70795 Keep track of position when deleting from a BTreeMap
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/node.rs
Labels: S-waiting-on-bors

#70777 Don't import integer and float modules, use assoc consts
  src/etc/test-float-parse/u64-pow2.rs
  src/liballoc/alloc.rs
  src/liballoc/collections/binary_heap.rs
  src/liballoc/rc.rs
  src/liballoc/slice.rs
  src/liballoc/sync.rs
  src/liballoc/tests.rs
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
  src/libcore/benches/num/flt2dec/strategy/dragon.rs
  src/libcore/benches/num/flt2dec/strategy/grisu.rs
  src/libcore/tests/fmt/num.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/num/dec2flt/mod.rs
  src/libcore/tests/num/flt2dec/mod.rs
  src/libcore/tests/num/flt2dec/random.rs
  src/libcore/tests/num/int_macros.rs
  src/librustc_ast/util/comments.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_data_structures/graph/implementation/mod.rs
  src/librustc_data_structures/profiling.rs
  src/librustc_index/vec.rs
  src/librustc_infer/infer/type_variable.rs
  src/librustc_lint/types.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir_build/build/matches/util.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_passes/liveness.rs
  src/librustc_span/def_id.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/passes/unindent_comments.rs
  src/libserialize/tests/json.rs
  src/libstd/sync/mpsc/shared.rs
  src/libstd/sync/mpsc/stream.rs
  src/libstd/sync/mpsc/sync.rs
  src/libstd/sys/hermit/thread.rs
Labels: S-waiting-on-bors

#67797 Query-ify Instance::resolve
  src/librustc_interface/callbacks.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/ty/instance.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/query/keys.rs
  src/librustc_ty/instance.rs
  src/librustc_ty/lib.rs
Labels: S-waiting-on-author

#70826 Rollup of 7 pull requests
  Cargo.lock
  src/libcore/iter/adapters/fuse.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/ops/range.rs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/libstd/Cargo.toml
  src/libstd/f32.rs
  src/libstd/f64.rs
  src/libstd/lib.rs
  src/libstd/sys/hermit/fast_thread_local.rs
  src/libstd/sys/hermit/fs.rs
  src/libstd/sys/hermit/mod.rs
  src/libstd/sys/hermit/thread.rs
  src/libstd/sys/hermit/thread_local.rs
  src/test/run-make-fulldeps/link-args-order/Makefile
  src/test/run-make-fulldeps/link-args-order/empty.rs
  src/test/ui/associated-const/issue-63496.stderr
  src/test/ui/associated-item/issue-48027.stderr
  src/test/ui/associated-types/associated-types-overridden-binding.stderr
  src/test/ui/associated-types/associated-types-unconstrained.stderr
  src/test/ui/error-codes/E0283.stderr
  src/test/ui/issues/issue-12028.stderr
  src/test/ui/issues/issue-21974.stderr
  src/test/ui/issues/issue-24424.stderr
  src/test/ui/issues/issue-29147.stderr
  src/test/ui/issues/issue-54954.stderr
  src/test/ui/issues/issue-58022.stderr
  src/test/ui/question-mark-type-infer.stderr
  src/test/ui/traits/trait-static-method-generic-inference.stderr
  src/test/ui/type/type-annotation-needed.rs
  src/test/ui/type/type-annotation-needed.stderr
  src/test/ui/type/type-check/issue-40294.stderr
Labels: S-waiting-on-bors, merged-by-bors

#70824 Remove marker comments in libstd/lib.rs macro imports
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#70808 Simplify dtor registration for HermitCore by using a list of destructors
  src/libstd/sys/hermit/fast_thread_local.rs
  src/libstd/sys/hermit/mod.rs
  src/libstd/sys/hermit/thread.rs
  src/libstd/sys/hermit/thread_local.rs
Labels: S-waiting-on-bors

#70798 "cannot resolve" → "cannot satisfy"
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/test/ui/associated-const/issue-63496.stderr
  src/test/ui/associated-item/issue-48027.stderr
  src/test/ui/associated-types/associated-types-overridden-binding.stderr
  src/test/ui/associated-types/associated-types-unconstrained.stderr
  src/test/ui/error-codes/E0283.stderr
  src/test/ui/issues/issue-12028.stderr
  src/test/ui/issues/issue-21974.stderr
  src/test/ui/issues/issue-24424.stderr
  src/test/ui/issues/issue-29147.stderr
  src/test/ui/issues/issue-54954.stderr
  src/test/ui/issues/issue-58022.stderr
  src/test/ui/question-mark-type-infer.stderr
  src/test/ui/traits/trait-static-method-generic-inference.stderr
  src/test/ui/type/type-annotation-needed.rs
  src/test/ui/type/type-annotation-needed.stderr
  src/test/ui/type/type-check/issue-40294.stderr
Labels: S-waiting-on-bors

#70782 Stop importing the float modules in documentation
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/ops/range.rs
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#70750 Match options directly in the Fuse implementation
  src/libcore/iter/adapters/fuse.rs
Labels: S-waiting-on-bors

#70665 Do not lose or reorder user-provided linker arguments
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/test/run-make-fulldeps/link-args-order/Makefile
  src/test/run-make-fulldeps/link-args-order/empty.rs
Labels: S-waiting-on-bors

#70553 move OS constants to platform crate
  Cargo.lock
  src/libstd/Cargo.toml
  src/libstd/sys/hermit/fs.rs
  src/libstd/sys/hermit/thread.rs
Labels: S-waiting-on-bors

#70827 Use smaller span for suggestion restricting lifetime
  src/librustc_mir/borrow_check/diagnostics/explain_borrow.rs
  src/test/ui/impl-trait/does-not-live-long-enough.stderr
Labels: S-waiting-on-bors

#70739 def_collector, visit_fn: account for no body
  src/librustc_resolve/def_collector.rs
  src/test/ui/resolve/issue-70736-async-fn-no-body-def-collector.rs
  src/test/ui/resolve/issue-70736-async-fn-no-body-def-collector.stderr
Labels: S-waiting-on-bors

#70713 Prefer sysroot from rustc in same directory as rust-gdb
  src/etc/rust-gdb
  src/etc/rust-gdbgui
Labels: S-waiting-on-bors

#70519 Tweak output of type params and constraints in the wrong order
  Cargo.lock
  src/librustc_ast/ast.rs
  src/librustc_ast_passes/Cargo.toml
  src/librustc_ast_passes/ast_validation.rs
  src/librustc_ast_pretty/pprust.rs
  src/librustc_errors/diagnostic_builder.rs
  src/test/ui/parser/issue-32214.stderr
  src/test/ui/suggestions/suggest-move-types.stderr
Labels: S-waiting-on-bors

#70833 tweak rustc_layout debug output
  src/librustc_passes/layout_test.rs
  src/test/ui/layout/debug.rs
  src/test/ui/layout/debug.stderr
Labels: S-waiting-on-bors, merged-by-bors

#70771 Miri terminator handling: only do progress sanity check for 'Call' terminator
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/step.rs
  src/librustc_mir/interpret/terminator.rs
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/consts/const-eval/issue-70723.rs
  src/test/ui/consts/const-eval/issue-70723.stderr
Labels: S-waiting-on-bors, merged-by-bors

#70737 cleanup `lower_item_id`
  src/librustc_ast_lowering/item.rs
Labels: S-waiting-on-bors, merged-by-bors

#70573 Detailed panic messages for Vec functions
  src/liballoc/vec.rs
Labels: S-waiting-on-bors, merged-by-bors

#70865 Rollup of 5 pull requests
  src/librustc_error_codes/error_codes/E0501.md
  src/librustc_error_codes/error_codes/E0506.md
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/libstd/io/mod.rs
  src/test/ui/sanitize/inline-always.rs
  src/test/ui/sanitize/inline-always.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70859 Move sanitize-inline-always test to sanitize directory
  src/test/ui/sanitize/inline-always.rs
  src/test/ui/sanitize/inline-always.stderr
Labels: S-waiting-on-bors

#70839 clean up E0506 explanation
  src/librustc_error_codes/error_codes/E0506.md
Labels: S-waiting-on-bors

#70821 expose suggestions::InferCtxtExt for clippy
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
Labels: S-waiting-on-bors

#70690 Clean up E0501 explanation
  src/librustc_error_codes/error_codes/E0501.md
Labels: S-waiting-on-bors

#70612 Add io::Write::write_all_vectored
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#70164 ty/walk: iterate `GenericArg`s instead of `Ty`s.
  src/librustc_infer/infer/error_reporting/need_type_info.rs
  src/librustc_infer/infer/outlives/verify.rs
  src/librustc_lint/builtin.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/outlives.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_middle/ty/walk.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_trait_selection/traits/coherence.rs
  src/librustc_trait_selection/traits/fulfill.rs
  src/librustc_trait_selection/traits/object_safety.rs
  src/librustc_trait_selection/traits/select.rs
  src/librustc_trait_selection/traits/wf.rs
  src/librustc_traits/lowering/environment.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/outlives/implicit_infer.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
  src/test/ui/coherence/impl-foreign-for-locally-defined-fundamental.rs
Labels: F-const_generics, S-waiting-on-bors, merged-by-bors

#70837 Speed up path searching with `find_library_crate`.
  src/librustc_metadata/locator.rs
  src/librustc_session/filesearch.rs
  src/librustc_session/search_paths.rs
Labels: S-waiting-on-bors, S-waiting-on-perf, merged-by-bors

#70857 Don't import integer and float modules, use assoc consts 2
  src/liballoc/raw_vec.rs
  src/liballoc/tests/arc.rs
  src/liballoc/tests/btree/map.rs
  src/liballoc/tests/rc.rs
  src/libcore/benches/num/dec2flt/mod.rs
  src/libcore/benches/num/flt2dec/mod.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/num/dec2flt/rawfp.rs
  src/libcore/tests/num/mod.rs
  src/libcore/tests/ops.rs
  src/libcore/tests/slice.rs
  src/libcore/tests/time.rs
  src/libcore/tests/tuple.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_errors/emitter.rs
  src/librustc_index/bit_set.rs
  src/librustc_trait_selection/traits/object_safety.rs
  src/librustc_trait_selection/traits/select.rs
  src/librustc_typeck/collect.rs
  src/libserialize/json.rs
  src/libserialize/tests/opaque.rs
  src/libstd/collections/hash/map.rs
  src/libtest/stats/tests.rs
  src/test/ui/rfc-2627-raw-dylib/link-ordinal-too-large.stderr
Labels: S-waiting-on-bors

#70846 Keep codegen units unmerged when building compiler builtins
  src/librustc_mir/monomorphize/partitioning.rs
  src/test/codegen-units/partitioning/compiler-builtins.rs
Labels: S-waiting-on-bors

#70762 Miri leak check: memory reachable through globals is not leaked
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/util/pretty.rs
Labels: S-waiting-on-bors

#70201 Small tweaks in ToOwned::clone_into
  src/liballoc/slice.rs
  src/libstd/ffi/c_str.rs
  src/libstd/ffi/os_str.rs
  src/libstd/sys/windows/os_str.rs
  src/libstd/sys_common/os_str_bytes.rs
  src/libstd/sys_common/wtf8.rs
Labels: S-waiting-on-bors

#70931 Rollup of 9 pull requests
  src/ci/scripts/symlink-build-dir.sh
  src/doc/rustdoc/src/documentation-tests.md
  src/liballoc/collections/btree/map.rs
  src/librustc_error_codes/error_codes/E0507.md
  src/librustc_error_codes/error_codes/E0510.md
  src/librustc_lint/unused.rs
  src/librustc_middle/mir/cache.rs
  src/librustc_middle/ty/flags.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_trait_selection/traits/wf.rs
  src/test/ui/lint/unused_braces.rs
  src/test/ui/lint/unused_braces.stderr
  src/test/ui/lint/unused_braces_borrow.rs
  src/test/ui/lint/unused_braces_borrow.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70927 Clean up E0510 explanation
  src/librustc_error_codes/error_codes/E0510.md
Labels: S-waiting-on-bors

#70915 Remove unnecessary TypeFlags::NOMINAL_FLAGS
  src/librustc_middle/ty/flags.rs
  src/librustc_middle/ty/mod.rs
Labels: S-waiting-on-bors

#70914 Corrects a typo in rustdoc documentation.
  src/doc/rustdoc/src/documentation-tests.md
Labels: S-waiting-on-bors

#70892 wf: refactor `compute_trait_ref`
  src/librustc_trait_selection/traits/wf.rs
Labels: S-waiting-on-bors

#70883 Clean up E0507 explanation
  src/librustc_error_codes/error_codes/E0507.md
Labels: S-waiting-on-bors

#70876 Use a `SmallVec` for `Cache::predecessors`.
  src/librustc_middle/mir/cache.rs
Labels: S-waiting-on-bors

#70850 BTreeMap first last proposal tweaks
  src/liballoc/collections/btree/map.rs
Labels: S-waiting-on-bors

#70847 ci: move /var/lib/docker to /mnt on GHA
  src/ci/scripts/symlink-build-dir.sh
Labels: S-waiting-on-bors

#70789 remove false positives of unused_braces
  src/librustc_lint/unused.rs
  src/test/ui/lint/unused_braces.rs
  src/test/ui/lint/unused_braces.stderr
  src/test/ui/lint/unused_braces_borrow.rs
  src/test/ui/lint/unused_braces_borrow.stderr
Labels: S-waiting-on-bors

#70936 Rollup of 7 pull requests
  src/liballoc/collections/vec_deque.rs
  src/liballoc/slice.rs
  src/librustc_codegen_llvm/callee.rs
  src/librustc_codegen_llvm/mono_item.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/instance.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/lib.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/librustc_privacy/lib.rs
  src/librustc_query_system/dep_graph/graph.rs
  src/librustc_query_system/query/plumbing.rs
  src/librustc_resolve/lib.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/lib.rs
  src/librustc_typeck/variance/constraints.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/sources.rs
  src/libstd/os/mod.rs
  src/libstd/sys/hermit/ext/ffi.rs
  src/libstd/sys/hermit/ext/mod.rs
  src/libstd/sys/hermit/mod.rs
  src/libstd/thread/local.rs
  src/test/rustdoc/auxiliary/external-macro-src.rs
  src/test/rustdoc/external-macro-src.rs
  src/test/rustdoc/issue-26606.rs
  src/test/rustdoc/thread-local-src.rs
  src/test/ui/async-await/async-borrowck-escaping-block-error.fixed
  src/test/ui/async-await/async-borrowck-escaping-block-error.rs
  src/test/ui/async-await/async-borrowck-escaping-block-error.stderr
  src/test/ui/async-await/async-borrowck-escaping-closure-error.rs
  src/test/ui/impl-trait/does-not-live-long-enough.rs
  src/test/ui/impl-trait/does-not-live-long-enough.stderr
  src/test/ui/privacy/privacy-ns1.stderr
  src/test/ui/suggestions/no-extern-crate-in-type.stderr
Labels: S-waiting-on-bors, merged-by-bors

#70930 add tracking issue to `VecDeque::make_contiguous`
  src/liballoc/collections/vec_deque.rs
Labels: S-waiting-on-bors

#70912 Do not suggest adding type param when `use` is already suggested
  src/librustc_resolve/lib.rs
  src/test/ui/privacy/privacy-ns1.stderr
  src/test/ui/suggestions/no-extern-crate-in-type.stderr
Labels: S-waiting-on-bors

#70906 Suggest move for closures and async blocks in more cases.
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/lib.rs
  src/librustc_mir/util/borrowck_errors.rs
  src/test/ui/async-await/async-borrowck-escaping-block-error.fixed
  src/test/ui/async-await/async-borrowck-escaping-block-error.rs
  src/test/ui/async-await/async-borrowck-escaping-block-error.stderr
  src/test/ui/async-await/async-borrowck-escaping-closure-error.rs
  src/test/ui/impl-trait/does-not-live-long-enough.rs
  src/test/ui/impl-trait/does-not-live-long-enough.stderr
Labels: S-waiting-on-bors

#70870 Fix abuses of tykind::err
  src/librustc_codegen_llvm/callee.rs
  src/librustc_codegen_llvm/mono_item.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/instance.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_privacy/lib.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/lib.rs
  src/librustc_typeck/variance/constraints.rs
Labels: S-waiting-on-bors

#70828 rustdoc: Don't try to load source files from external crates
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/sources.rs
  src/test/rustdoc/auxiliary/external-macro-src.rs
  src/test/rustdoc/external-macro-src.rs
  src/test/rustdoc/issue-26606.rs
  src/test/rustdoc/thread-local-src.rs
Labels: S-waiting-on-bors

#70565 Add inline attributes for functions used in the query system
  src/liballoc/slice.rs
  src/librustc_query_system/dep_graph/graph.rs
  src/librustc_query_system/query/plumbing.rs
  src/libstd/thread/local.rs
Labels: S-waiting-on-bors

#70134 add basic support of OsStrExt for HermitCore
  src/libstd/os/mod.rs
  src/libstd/sys/hermit/ext/ffi.rs
  src/libstd/sys/hermit/ext/mod.rs
  src/libstd/sys/hermit/mod.rs
Labels: S-waiting-on-bors, T-libs

#70860 remove `KEEP_IN_LOCAL_TCX` flag
  src/librustc_infer/infer/canonical/canonicalizer.rs
  src/librustc_infer/infer/resolve.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/erase_regions.rs
  src/librustc_middle/ty/flags.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_mir/borrow_check/region_infer/mod.rs
  src/librustc_trait_selection/infer.rs
  src/librustc_trait_selection/traits/mod.rs
  src/librustc_trait_selection/traits/select.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/check/writeback.rs
Labels: S-waiting-on-bors, merged-by-bors

#70943 Rollup of 7 pull requests
  src/doc/rustc/src/lints/levels.md
  src/libcore/iter/adapters/chain.rs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0738.md
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/lints.rs
  src/librustc_passes/check_attr.rs
  src/librustc_passes/region.rs
  src/librustc_session/config.rs
  src/libstd/sys/windows/mod.rs
  src/test/ui-fulldeps/lint-group-forbid-always-trumps-cli.rs
  src/test/ui-fulldeps/lint-group-forbid-always-trumps-cli.stderr
  src/test/ui/async-await/issues/issue-69307-nested.rs
  src/test/ui/async-await/issues/issue-69307.rs
  src/test/ui/lint/lint-unconditional-recursion.rs
  src/test/ui/rfc-2091-track-caller/error-extern-fn.rs
  src/test/ui/rfc-2091-track-caller/error-extern-fn.stderr
  src/test/ui/rfc-2091-track-caller/error-with-naked.rs
  src/test/ui/rfc-2091-track-caller/error-with-naked.stderr
  src/test/ui/rfc-2091-track-caller/track-caller-ffi.rs
Labels: S-waiting-on-bors, merged-by-bors

#70916 Support `#[track_caller]` on functions in `extern "Rust" { ... }`
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0738.md
  src/librustc_passes/check_attr.rs
  src/test/ui/rfc-2091-track-caller/error-extern-fn.rs
  src/test/ui/rfc-2091-track-caller/error-extern-fn.stderr
  src/test/ui/rfc-2091-track-caller/error-with-naked.rs
  src/test/ui/rfc-2091-track-caller/error-with-naked.stderr
  src/test/ui/rfc-2091-track-caller/track-caller-ffi.rs
Labels: F-track_caller, S-waiting-on-bors

#70918 rustc_session: forbid lints override regardless of position
  src/doc/rustc/src/lints/levels.md
  src/librustc_session/config.rs
  src/test/ui-fulldeps/lint-group-forbid-always-trumps-cli.rs
  src/test/ui-fulldeps/lint-group-forbid-always-trumps-cli.stderr
Labels: S-waiting-on-bors

#70896 Implement Chain with Option fuses
  src/libcore/iter/adapters/chain.rs
Labels: S-waiting-on-bors

#70868 rustc_codegen_ssa: Refactor construction of linker arguments
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/linker.rs
Labels: S-waiting-on-bors, T-compiler

#70822 Don't lint for self-recursion when the function can diverge
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/lints.rs
  src/test/ui/lint/lint-unconditional-recursion.rs
Labels: S-waiting-on-bors

#70367 save/restore `pessimistic_yield` when entering bodies
  src/librustc_passes/region.rs
  src/test/ui/async-await/issues/issue-69307-nested.rs
  src/test/ui/async-await/issues/issue-69307.rs
Labels: S-waiting-on-bors

#67705 Use unrolled loop for searching NULL in [u16] on Windows
  src/libstd/sys/windows/mod.rs
Labels: O-windows, S-waiting-on-author, T-compiler, T-libs

#70958 Disable try_reserve tests on Android
  src/liballoc/tests/string.rs
  src/liballoc/tests/vec.rs
  src/liballoc/tests/vec_deque.rs
Labels: S-waiting-on-bors

#70939 Add two const generics regression tests
  src/test/ui/const-generics/issue-61522-array-len-succ.rs
  src/test/ui/const-generics/issue-61522-array-len-succ.stderr
  src/test/ui/const-generics/issue-66596-impl-trait-for-str-const-arg.rs
  src/test/ui/const-generics/issue-66596-impl-trait-for-str-const-arg.stderr
Labels: F-const_generics, S-waiting-on-bors

#70909 librustc_hir: return LocalDefId instead of DefId in local_def_id
  src/librustc_ast_lowering/item.rs
  src/librustc_ast_lowering/lib.rs
  src/librustc_hir/definitions.rs
  src/librustc_middle/ty/context.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/late.rs
  src/librustc_resolve/lib.rs
  src/librustc_resolve/macros.rs
Labels: S-waiting-on-bors, merged-by-bors

#70447 Add utility to find locals that don't use `StorageLive` annotations and use it for `MaybeStorageLive`
  src/librustc_mir/dataflow/impls/storage_liveness.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/util/mod.rs
  src/librustc_mir/util/storage.rs
Labels: S-waiting-on-bors, merged-by-bors

#70619 Enable rust-lld on dist-x86_64-musl
  src/ci/docker/dist-x86_64-musl/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#70983 Rollup of 8 pull requests
  src/doc/rustc/src/json.md
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/librustc_error_codes/error_codes/E0152.md
  src/librustc_error_codes/error_codes/E0511.md
  src/librustc_error_codes/error_codes/E0718.md
  src/librustc_hir/lang_items.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_mir/borrow_check/diagnostics/mod.rs
  src/librustc_mir/borrow_check/diagnostics/move_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_session/config.rs
  src/librustc_span/symbol.rs
  src/librustc_typeck/check/expr.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/pat.rs
  src/librustc_typeck/check/writeback.rs
  src/test/ui/error-codes/E0152.rs
  src/test/ui/error-codes/E0152.stderr
  src/test/ui/error-codes/E0718.rs
  src/test/ui/error-codes/E0718.stderr
  src/test/ui/issues/issue-29181.rs
  src/test/ui/issues/issue-29181.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#70975 Fix internal doc comment nits.
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/writeback.rs
Labels: S-waiting-on-bors

#70969 Fix JSON file_name documentation for macros.
  src/doc/rustc/src/json.md
Labels: S-waiting-on-bors, relnotes

#70964 rustc_session CLI lint parsing: mark a temporary hack as such
  src/librustc_session/config.rs
Labels: S-waiting-on-bors

#70952 Clean up E0511 explanation
  src/librustc_error_codes/error_codes/E0511.md
Labels: S-waiting-on-bors

#70932 De-abuse TyKind::Error in pattern type checking
  src/librustc_typeck/check/pat.rs
Labels: S-waiting-on-bors

#70913 Replace "rc"/"arc" lang items with Rc/Arc diagnostic items.
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/librustc_error_codes/error_codes/E0152.md
  src/librustc_error_codes/error_codes/E0718.md
  src/librustc_hir/lang_items.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_mir/borrow_check/diagnostics/mod.rs
  src/librustc_mir/borrow_check/diagnostics/move_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_span/symbol.rs
  src/librustc_typeck/check/expr.rs
  src/test/ui/error-codes/E0152.rs
  src/test/ui/error-codes/E0152.stderr
  src/test/ui/error-codes/E0718.rs
  src/test/ui/error-codes/E0718.stderr
Labels: S-waiting-on-bors

#70843 Remove the Ord bound that was plaguing drain_filter
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
Labels: S-waiting-on-bors

#70784 Consider methods on fundamental `impl` when method is not found on numeric type
  src/librustc_typeck/check/method/suggest.rs
  src/test/ui/issues/issue-29181.rs
  src/test/ui/issues/issue-29181.stderr
Labels: S-waiting-on-bors
