Repository rust-lang/rust, pull requests merged in 2020-12, with the labels that each got.

#77875 More intra doc links
  library/core/src/cell.rs
  library/core/src/char/methods.rs
  library/core/src/iter/adapters/flatten.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/ptr/const_ptr.rs
  library/core/src/ptr/mut_ptr.rs
  library/core/src/str/mod.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc, merged-by-bors

#78142 Add built-in support for the armv5te-unknown-linux-uclibcgnueabi target
  compiler/rustc_target/src/spec/armv5te_unknown_linux_uclibceabi.rs
  compiler/rustc_target/src/spec/mod.rs
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors, merged-by-bors

#78725 Remove extra call to upvar_tys
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_trait_selection/src/opaque_types.rs
  compiler/rustc_ty_utils/src/needs_drop.rs
  src/test/ui/issues/issue-78720.rs
  src/test/ui/issues/issue-78720.stderr
Labels: A-closures, S-waiting-on-bors, T-compiler, merged-by-bors

#78876 Make keyboard interactions in the settings menu more pleasant
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/settings.js
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc, merged-by-bors

#79522 Validate lint docs separately.
  compiler/rustc_lint_defs/src/lib.rs
  src/bootstrap/builder.rs
  src/bootstrap/doc.rs
  src/bootstrap/test.rs
  src/tools/lint-docs/src/groups.rs
  src/tools/lint-docs/src/lib.rs
  src/tools/lint-docs/src/main.rs
Labels: A-rustbuild, A-testsuite, S-waiting-on-bors

#79525 Add -Z normalize-docs and enable it for compiler docs
  compiler/rustc_session/src/options.rs
  src/bootstrap/builder.rs
  src/bootstrap/doc.rs
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/normalize-assoc-item.rs
Labels: A-associated-items, A-contributor-roadblock, A-rustbuild, S-waiting-on-bors, T-compiler, T-rustdoc

#79548 Show since when a function is const in stdlib
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc/const-display.rs
Labels: A-const-fn, S-waiting-on-bors, T-rustdoc

#79573 Update with status for various NetBSD ports.
  src/doc/rustc/src/platform-support.md
Labels: O-netbsd, S-waiting-on-bors, T-doc, T-infra

#79184 Stop adding '*' at the end of slice and str typenames for MSVC case
  compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs
Labels: A-debuginfo, O-windows-msvc, S-waiting-on-bors, T-compiler

#79227 Remove const_fn_feature_flags test
  src/test/ui/consts/const-fn-feature-flags.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors

#79444 Move const ip in ui test to unit test
  library/std/src/net/ip/tests.rs
  src/test/ui/consts/std/net/ip.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors, libs-impl

#74967 Implement lazy decoding of DefPathTable during incremental compilation
  compiler/rustc_incremental/src/persist/load.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/dep_graph/mod.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_query_system/src/dep_graph/graph.rs
  compiler/rustc_query_system/src/dep_graph/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#79508 Warn if `dsymutil` returns an error code
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_session/src/config.rs
Labels: S-waiting-on-bors

#79509 Improve attribute message error spans
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_middle/src/middle/limits.rs
  compiler/rustc_passes/src/check_attr.rs
  src/test/rustdoc-ui/check-doc-alias-attr.stderr
  src/test/rustdoc-ui/doc-alias-crate-level.stderr
  src/test/ui/check-doc-alias-attr.stderr
  src/test/ui/doc-alias-crate-level.stderr
Labels: A-diagnostics, S-waiting-on-bors

#79600 std::io: Use sendfile for UnixStream
  library/std/src/sys/unix/kernel_copy.rs
  library/std/src/sys/unix/kernel_copy/tests.rs
Labels: A-io, O-linux, S-waiting-on-bors, libs-impl

#79614 Rollup of 3 pull requests
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_middle/src/middle/limits.rs
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_session/src/config.rs
  library/std/src/sys/unix/kernel_copy.rs
  library/std/src/sys/unix/kernel_copy/tests.rs
  src/test/rustdoc-ui/check-doc-alias-attr.stderr
  src/test/rustdoc-ui/doc-alias-crate-level.stderr
  src/test/ui/check-doc-alias-attr.stderr
  src/test/ui/doc-alias-crate-level.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#78864 Use true previous lint level when detecting overriden forbids
  compiler/rustc_lint/src/levels.rs
  src/test/ui-fulldeps/lint-plugin-forbid-attrs.rs
  src/test/ui-fulldeps/lint-plugin-forbid-attrs.stderr
  src/test/ui-fulldeps/lint-plugin-forbid-cmdline.rs
  src/test/ui-fulldeps/lint-plugin-forbid-cmdline.stderr
  src/test/ui/error-codes/E0453.rs
  src/test/ui/error-codes/E0453.stderr
  src/test/ui/lint/forbid-error-capped.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.stderr
  src/test/ui/lint/lint-forbid-attr.rs
  src/test/ui/lint/lint-forbid-attr.stderr
  src/test/ui/lint/lint-forbid-cmdline.rs
  src/test/ui/lint/lint-forbid-cmdline.stderr
  src/test/ui/lint/outer-forbid.rs
  src/test/ui/lint/outer-forbid.stderr
  src/test/ui/lint/reasons-forbidden.rs
  src/test/ui/lint/reasons-forbidden.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, final-comment-period, merged-by-bors, needs-fcp, relnotes

#79235 Fix zero-sized BTreeMap gdb pretty-printer
  src/etc/gdb_providers.py
Labels: S-waiting-on-bors, merged-by-bors

#79606 Do not show negative polarity trait implementations in diagnostic messages for similar implementations
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  src/test/ui/associated-types/hr-associated-type-bound-1.stderr
  src/test/ui/associated-types/hr-associated-type-bound-object.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-1.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-2.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-3.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-4.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-5.stderr
  src/test/ui/associated-types/hr-associated-type-bound-param-6.stderr
  src/test/ui/async-await/issue-64130-3-other.stderr
  src/test/ui/auto-traits/typeck-default-trait-impl-constituent-types-2.stderr
  src/test/ui/auto-traits/typeck-default-trait-impl-constituent-types.stderr
  src/test/ui/auto-traits/typeck-default-trait-impl-negation.stderr
  src/test/ui/traits/issue-79458.rs
  src/test/ui/traits/issue-79458.stderr
Labels: S-waiting-on-bors, merged-by-bors

#79547 Pass arguments up to 2*usize by value
  compiler/rustc_middle/src/ty/layout.rs
  src/test/codegen/arg-return-value-in-reg.rs
  src/test/codegen/union-abi.rs
Labels: S-waiting-on-bors, merged-by-bors

#69864 unix: Extend UnixStream and UnixDatagram to send and receive file descriptors
  library/std/src/lib.rs
  library/std/src/sys/unix/ext/net.rs
  library/std/src/sys/unix/ext/net/addr.rs
  library/std/src/sys/unix/ext/net/ancillary.rs
  library/std/src/sys/unix/ext/net/datagram.rs
  library/std/src/sys/unix/ext/net/listener.rs
  library/std/src/sys/unix/ext/net/mod.rs
  library/std/src/sys/unix/ext/net/raw_fd.rs
  library/std/src/sys/unix/ext/net/stream.rs
  library/std/src/sys/unix/ext/net/tests.rs
  library/std/src/sys/unix/net.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#79364 Fixes #79357 unstable or-pat suggestions
  compiler/rustc_parse/src/parser/pat.rs
  src/test/ui/did_you_mean/issue-48492-tuple-destructure-missing-parens.stderr
Labels: A-diagnostics, A-patterns, S-waiting-on-bors, merged-by-bors

#79539 Rustdoc: JSON backend experimental impl, with new tests.
  src/bootstrap/builder.rs
  src/bootstrap/test.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/json/types.rs
  src/librustdoc/lib.rs
  src/test/rustdoc-json/check_missing_items.py
  src/test/rustdoc-json/compare.py
  src/test/rustdoc-json/structs.expected
  src/test/rustdoc-json/structs.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#79637 Revert "Auto merge of #79209
  compiler/rustc_infer/src/traits/util.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/keys.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/fn_ctxt/mod.rs
  compiler/rustc_typeck/src/collect.rs
  compiler/rustc_typeck/src/collect/item_bounds.rs
  src/test/incremental/cyclic-trait-hierarchy.rs
  src/test/ui/associated-type-bounds/ambiguous-associated-type2.rs
  src/test/ui/associated-type-bounds/ambiguous-associated-type2.stderr
  src/test/ui/associated-type-bounds/associated-item-through-where-clause.rs
  src/test/ui/associated-type-bounds/handle-predicates-that-can-define-assoc-type.rs
  src/test/ui/associated-type-bounds/missing-trait-bound-for-assoc-fails.rs
  src/test/ui/associated-type-bounds/missing-trait-bound-for-assoc-fails.stderr
  src/test/ui/associated-type-bounds/super-trait-referencing-self.rs
  src/test/ui/associated-type-bounds/super-trait-referencing.rs
  src/test/ui/associated-type-bounds/super-trait-where-referencing-self.rs
  src/test/ui/cycle-projection-based-on-where-clause.rs
  src/test/ui/cycle-projection-based-on-where-clause.stderr
  src/test/ui/cycle-trait/cycle-trait-supertrait-direct.stderr
  src/test/ui/cycle-trait/cycle-trait-supertrait-indirect.stderr
  src/test/ui/issues/issue-12511.stderr
  src/test/ui/issues/issue-20772.stderr
  src/test/ui/issues/issue-20825.stderr
  src/test/ui/issues/issue-22673.rs
  src/test/ui/issues/issue-22673.stderr
Labels: S-waiting-on-bors, merged-by-bors

#79533 Add long explanation of E0546
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0546.md
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: A-error-codes, A-stability, F-rustc_attrs, S-waiting-on-bors, T-doc, merged-by-bors

#79594 add const_allocate intrinsic
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/intern.rs
  compiler/rustc_mir/src/interpret/memory.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/intrinsic.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  src/test/ui/const-generics/const-argument-if-length.full.stderr
  src/test/ui/const-generics/const-argument-if-length.rs
  src/test/ui/consts/const-eval/erroneous-const.rs
  src/test/ui/consts/const-eval/erroneous-const.stderr
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_errors.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_errors.stderr
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_nontransient.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_nontransient_fail.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_nontransient_fail.stderr
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_transient.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_uninit.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_uninit.stderr
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_untyped.rs
  src/test/ui/consts/const-eval/heap/alloc_intrinsic_untyped.stderr
  src/test/ui/consts/const-eval/unwind-abort.rs
  src/test/ui/consts/const-eval/unwind-abort.stderr
  src/test/ui/consts/const-size_of-cycle.stderr
  src/test/ui/consts/uninhabited-const-issue-61744.rs
  src/test/ui/consts/uninhabited-const-issue-61744.stderr
  src/test/ui/infinite/infinite-recursion-const-fn.rs
  src/test/ui/infinite/infinite-recursion-const-fn.stderr
Labels: A-const-eval, A-const-fn, S-waiting-on-bors, merged-by-bors

#79586 Fix `unknown-crate` when using -Z self-profile with rustdoc
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_interface/src/interface.rs
  compiler/rustc_interface/src/queries.rs
  compiler/rustc_session/src/session.rs
  src/librustdoc/core.rs
  src/librustdoc/doctest.rs
  src/test/run-make-fulldeps/issue-19371/foo.rs
Labels: A-driver, S-waiting-on-bors, T-compiler, T-rustdoc, merged-by-bors

#79613 Add checks for #[doc(keyword = "...")] attribute
  Cargo.lock
  compiler/rustc_passes/Cargo.toml
  compiler/rustc_passes/src/check_attr.rs
  src/librustdoc/clean/mod.rs
  src/test/rustdoc-ui/check-doc-alias-attr.stderr
  src/test/ui/check-doc-alias-attr.stderr
  src/test/ui/doc-alias-crate-level.rs
  src/test/ui/doc-alias-crate-level.stderr
  src/test/ui/doc_keyword.rs
  src/test/ui/doc_keyword.stderr
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#79620 Tweak diagnostics on shadowing lifetimes/labels
  compiler/rustc_resolve/src/late/lifetimes.rs
  src/test/ui/error-codes/E0496.stderr
  src/test/ui/generic-associated-types/shadowing.stderr
  src/test/ui/hygiene/hygienic-labels-in-let.stderr
  src/test/ui/hygiene/hygienic-labels.stderr
  src/test/ui/in-band-lifetimes/shadow.stderr
  src/test/ui/lint/unused_labels.stderr
  src/test/ui/loops/loops-reject-duplicate-labels-2.stderr
  src/test/ui/loops/loops-reject-duplicate-labels.stderr
  src/test/ui/loops/loops-reject-labels-shadowing-lifetimes.stderr
  src/test/ui/loops/loops-reject-lifetime-shadowing-label.stderr
  src/test/ui/macros/macro-lifetime-used-with-labels.stderr
  src/test/ui/shadowed/shadowed-lifetime.stderr
Labels: S-waiting-on-bors, merged-by-bors

#79602 Fix SGX CI
  library/std/tests/env.rs
Labels: S-waiting-on-bors

#79611 Use more std:: instead of core:: in docs for consistency
  library/core/src/fmt/mod.rs
  library/core/src/future/pending.rs
  library/core/src/future/poll_fn.rs
  library/core/src/future/ready.rs
  library/core/src/panic.rs
  library/core/src/task/ready.rs
  library/std/src/primitive_docs.rs
Labels: C-cleanup, S-waiting-on-bors, T-doc, T-libs

#79623 Pass around Symbols instead of Idents in doctree
  src/librustdoc/clean/mod.rs
  src/librustdoc/doctree.rs
  src/librustdoc/visit_ast.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#79631 disable a ptr equality test on Miri
  library/alloc/tests/str.rs
Labels: S-waiting-on-bors

#79638 Use `item_name` instead of pretty printing for resolving `Self` on intra-doc links
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc/raw-ident-self.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc

#79646 rustc_metadata: Remove some dead code
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/middle/cstore.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors

#79664 move interpret::MemoryKind::Heap to const eval
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/intern.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/memory.rs
  compiler/rustc_mir/src/transform/const_prop.rs
Labels: S-waiting-on-bors

#79678 Fix some clippy lints
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_lexer/src/lib.rs
  compiler/rustc_serialize/src/json.rs
  compiler/rustc_span/src/analyze_source_file.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
  compiler/rustc_span/src/symbol.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#79541 Doc keyword lint pass
  compiler/rustc_lint/src/internal.rs
  compiler/rustc_lint/src/lib.rs
  library/std/src/lib.rs
  src/test/ui-fulldeps/internal-lints/existing_doc_keyword.rs
  src/test/ui-fulldeps/internal-lints/existing_doc_keyword.stderr
Labels: S-waiting-on-bors

#77686 Render Markdown in search results
  src/librustdoc/clean/mod.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/lib.rs
  src/test/rustdoc-js/basic.rs
  src/test/rustdoc-js/summaries.js
  src/test/rustdoc-js/summaries.rs
  src/test/rustdoc/markdown-summaries.rs
Labels: A-markdown-parsing, A-rustdoc-search, S-waiting-on-bors, T-rustdoc

#78177 A few miscellaneous comment fixes and a tiny code clarification.
  compiler/rustc_infer/src/infer/higher_ranked/mod.rs
  compiler/rustc_typeck/src/bounds.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  compiler/rustc_typeck/src/check/writeback.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#79680 Fix perf regression caused by #79284
  compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs
Labels: A-exhaustiveness-checking, I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#79286 Rename `AllocRef` to `Allocator` and `(de)alloc` to `(de)allocate`
  library/alloc/src/alloc.rs
  library/alloc/src/alloc/tests.rs
  library/alloc/src/boxed.rs
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/raw_vec.rs
  library/alloc/src/raw_vec/tests.rs
  library/alloc/src/rc.rs
  library/alloc/src/slice.rs
  library/alloc/src/sync.rs
  library/alloc/src/vec.rs
  library/alloc/tests/heap.rs
  library/core/src/alloc/layout.rs
  library/core/src/alloc/mod.rs
  library/core/src/ptr/non_null.rs
  library/std/src/alloc.rs
  src/test/ui/allocator/custom.rs
  src/test/ui/allocator/xcrate-use.rs
  src/test/ui/associated-types/defaults-wf.stderr
  src/test/ui/bad/bad-sized.stderr
  src/test/ui/box/leak-alloc.rs
  src/test/ui/error-codes/e0119/conflict-with-std.stderr
  src/test/ui/issues/issue-20433.stderr
  src/test/ui/issues/issue-41974.stderr
  src/test/ui/realloc-16687.rs
  src/test/ui/regions/regions-mock-codegen.rs
  src/test/ui/unique-object-noncopyable.stderr
  src/test/ui/unique-pinned-nocopy.stderr
Labels: A-allocators, S-waiting-on-bors, T-libs, merged-by-bors

#79673 Provide IntoInnerError::into_parts
  library/std/src/io/buffered/mod.rs
  library/std/src/io/impls.rs
Labels: A-io, S-waiting-on-bors, T-libs, merged-by-bors

#76301 Cleanup: move format! ui tests to where they belong
  src/test/ui/fmt/ifmt-bad-arg.rs
  src/test/ui/fmt/ifmt-bad-arg.stderr
  src/test/ui/fmt/ifmt-bad-format-args.rs
  src/test/ui/fmt/ifmt-bad-format-args.stderr
  src/test/ui/fmt/ifmt-unimpl.rs
  src/test/ui/fmt/ifmt-unimpl.stderr
  src/test/ui/fmt/ifmt-unknown-trait.rs
  src/test/ui/fmt/ifmt-unknown-trait.stderr
Labels: A-testsuite, C-cleanup, S-waiting-on-bors, T-libs, merged-by-bors

#78373 Don't leak return value after panic in drop
  compiler/rustc_mir_build/src/build/block.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/expr/as_temp.rs
  compiler/rustc_mir_build/src/build/expr/into.rs
  compiler/rustc_mir_build/src/build/expr/stmt.rs
  compiler/rustc_mir_build/src/build/into.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_mir_build/src/build/scope.rs
  library/alloc/src/collections/btree/map/tests.rs
  src/test/mir-opt/basic_assignment.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/box_expr.main.ElaborateDrops.before.mir
  src/test/mir-opt/inline/inline_diverging.h.Inline.diff
  src/test/mir-opt/issue_41110.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue_41110.test.ElaborateDrops.after.mir
  src/test/mir-opt/issue_41888.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue_62289.test.ElaborateDrops.before.mir
  src/test/mir-opt/no_spurious_drop_after_call.main.ElaborateDrops.before.mir
  src/test/mir-opt/uniform_array_move_out.move_out_by_subslice.mir_map.0.mir
  src/test/mir-opt/uniform_array_move_out.move_out_from_end.mir_map.0.mir
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.uses_crate.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.async.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.generics.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.uses_crate.txt
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.executor-block_on.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.closure/closure.main-{closure#2}.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.closure/closure.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.used_crate/used_crate.use_this_lib_crate.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.uses_crate/uses_crate.main.-------.InstrumentCoverage.0.html
  src/test/ui/drop/dynamic-drop-async.rs
  src/test/ui/drop/dynamic-drop.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors, relnotes

#79445 check the recursion limit when finding a struct's tail
  compiler/rustc_middle/src/ty/util.rs
  src/test/ui/infinite/infinite-struct.rs
  src/test/ui/infinite/infinite-struct.stderr
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#79719 Ping me when nomicon's toolstate is broken
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors, merged-by-bors

#79685 Fix src/test/ui/env-vars.rs on 128-core machines on Windows
  src/test/ui/env-vars.rs
Labels: S-waiting-on-bors, merged-by-bors

#79697 A slightly clearer diagnostic when misusing const
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/generic-associated-types/parse/trait-path-missing-gen_arg.rs
  src/test/ui/generic-associated-types/parse/trait-path-missing-gen_arg.stderr
  src/test/ui/issues/issue-20616-3.rs
  src/test/ui/issues/issue-20616-3.stderr
  src/test/ui/issues/issue-20616-4.rs
  src/test/ui/issues/issue-20616-4.stderr
  src/test/ui/issues/issue-20616-5.rs
  src/test/ui/issues/issue-20616-5.stderr
  src/test/ui/issues/issue-20616-6.rs
  src/test/ui/issues/issue-20616-6.stderr
  src/test/ui/issues/issue-20616-7.rs
  src/test/ui/issues/issue-20616-7.stderr
  src/test/ui/parser/removed-syntax-uniq-mut-ty.rs
  src/test/ui/parser/removed-syntax-uniq-mut-ty.stderr
Labels: A-const-generics, S-waiting-on-bors, const-generics-bad-diagnostics, merged-by-bors

#79650 Fix incorrect io::Take's limit resulting from io::copy specialization
  library/std/src/sys/unix/fs.rs
  library/std/src/sys/unix/kernel_copy.rs
  library/std/src/sys/unix/kernel_copy/tests.rs
Labels: S-waiting-on-bors, merged-by-bors

#79729 remove redundant clones
  compiler/rustc_infer/src/infer/canonical/canonicalizer.rs
  compiler/rustc_middle/src/ty/fold.rs
  compiler/rustc_trait_selection/src/traits/query/normalize.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#79734 Const parameters can not be inferred with `_` help note
  compiler/rustc_typeck/src/astconv/generics.rs
  src/test/ui/const-generics/issues/issue-62878.full.stderr
  src/test/ui/const-generics/min_const_generics/inferred_const.rs
  src/test/ui/const-generics/min_const_generics/inferred_const.stderr
Labels: A-const-generics, S-waiting-on-bors, merged-by-bors

#78609 extend `WithOptConstParam` docs, move rustdoc test
  compiler/rustc_middle/src/ty/mod.rs
  src/test/rustdoc/const-generics/lazy_normalization_consts/const-equate-pred.rs
Labels: S-waiting-on-bors, merged-by-bors

#79641 Add a doctest example of str::split on a slice of chars
  library/core/src/str/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#79772 smarter E0390
  compiler/rustc_error_codes/src/error_codes/E0390.md
  compiler/rustc_typeck/src/coherence/inherent_impls.rs
  src/test/ui/error-codes/E0390.stderr
  src/test/ui/kinds-of-primitive-impl.rs
  src/test/ui/kinds-of-primitive-impl.stderr
  src/test/ui/single-primitive-inherent-impl.stderr
Labels: A-suggestion-diagnostics, S-waiting-on-bors, merged-by-bors

#79773 small `TypeVisitor` refactor
  compiler/rustc_mir/src/interpret/util.rs
  compiler/rustc_typeck/src/check/check.rs
  library/core/src/ops/control_flow.rs
Labels: S-waiting-on-bors, merged-by-bors

#79751 Rustdoc: Use correct def_id for doctree::Import
  src/librustdoc/clean/mod.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/json/types.rs
  src/test/rustdoc-json/nested.expected
  src/test/rustdoc-json/nested.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#79797 Fix SGX CI, take 3
  library/std/tests/env.rs
Labels: S-waiting-on-bors, merged-by-bors

#79653 Validate naked functions definitions
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_hir/src/arena.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_mir_build/src/thir/cx/expr.rs
  compiler/rustc_passes/src/intrinsicck.rs
  compiler/rustc_passes/src/liveness.rs
  compiler/rustc_passes/src/naked_functions.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/expr_use_visitor.rs
  src/test/ui/asm/naked-functions.rs
  src/test/ui/asm/naked-functions.stderr
  src/test/ui/asm/naked-params.rs
  src/test/ui/asm/naked-params.stderr
  src/test/ui/feature-gates/feature-gate-naked_functions.rs
  src/test/ui/feature-gates/feature-gate-naked_functions.stderr
  src/test/ui/rfc-2091-track-caller/error-with-naked.rs
  src/test/ui/rfc-2091-track-caller/error-with-naked.stderr
  src/tools/clippy/clippy_lints/src/loops.rs
  src/tools/clippy/clippy_lints/src/utils/hir_utils.rs
  src/tools/clippy/clippy_lints/src/utils/inspector.rs
Labels: A-inline-assembly, A-naked, S-waiting-on-bors, T-lang, merged-by-bors

#79780 Use `summary_opts()` in another spot
  src/librustdoc/html/markdown.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#79712 Add a regression test for issue-66286
  src/test/ui/proc-macro/auxiliary/issue-66286.rs
  src/test/ui/proc-macro/issue-66286.rs
  src/test/ui/proc-macro/issue-66286.stderr
Labels: S-waiting-on-bors, merged-by-bors

#79806 Fixup: `filter().is_none()` -> `!any()`
  compiler/rustc_typeck/src/check/pat.rs
Labels: A-typesystem, C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#79752 Visit ForeignItems when marking dead code
  compiler/rustc_passes/src/dead.rs
  src/test/ui/lint/dead-code/type-in-foreign.rs
Labels: S-waiting-on-bors, merged-by-bors

#79817 Replace simple `if let` constructs with Option::map
  compiler/rustc_typeck/src/check/demand.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#79727 Compress RWU from at least 32 bits to 4 bits
  compiler/rustc_passes/src/liveness.rs
Labels: S-waiting-on-bors, merged-by-bors

#78768 Use is_write_vectored to optimize the write_vectored implementation for BufWriter
  library/std/src/io/buffered/bufwriter.rs
  library/std/src/io/buffered/linewritershim.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#79575 Don't time `emit_ignored_resolution_errors`
  src/librustdoc/core.rs
Labels: A-contributor-roadblock, S-waiting-on-bors, T-rustdoc, WG-compiler-performance, merged-by-bors

#79767 Don't ICE on malformed `rustc_args_required_const` attribute
  compiler/rustc_passes/src/check_attr.rs
  src/test/ui/invalid-rustc_args_required_const-arguments.rs
  src/test/ui/invalid-rustc_args_required_const-arguments.stderr
Labels: S-waiting-on-bors, merged-by-bors

#78363 remove this weird special case from promotion
  compiler/rustc_mir/src/transform/promote_consts.rs
  src/test/ui/consts/promote-not.rs
  src/test/ui/consts/promote-not.stderr
  src/test/ui/issues/issue-49955-2.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors, to-announce

#78679 Also generate `StorageDead` in constants
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir_build/src/build/expr/as_operand.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/expr/into.rs
  compiler/rustc_mir_build/src/build/scope.rs
  src/test/mir-opt/const-promotion-extern-static.rs
  src/test/mir-opt/const_promotion_extern_static.BAR.PromoteTemps.diff
  src/test/mir-opt/const_promotion_extern_static.BOP.mir_map.0.mir
  src/test/mir-opt/const_promotion_extern_static.FOO.PromoteTemps.diff
  src/test/mir-opt/storage_live_dead_in_statics.XXX.mir_map.0.mir
Labels: S-waiting-on-bors, merged-by-bors

#79721 Properly re-use def path hash in incremental mode
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_query_system/src/dep_graph/dep_node.rs
  compiler/rustc_query_system/src/dep_graph/graph.rs
  compiler/rustc_query_system/src/dep_graph/prev.rs
  src/test/incremental/auxiliary/issue-79661.rs
  src/test/incremental/issue-79661-missing-def-path-hash.rs
Labels: A-incr-comp, S-waiting-on-bors, T-compiler, merged-by-bors

#79387 ext/ucred: Support PID in peer creds on macOS
  library/std/src/sys/unix/ext/ucred.rs
  library/std/src/sys/unix/ext/ucred/tests.rs
Labels: S-waiting-on-bors, merged-by-bors

#77611 Directly use raw pointers in `AtomicPtr` store/load
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_ssa/src/mir/intrinsic.rs
  library/core/src/sync/atomic.rs
  library/std/src/sys/windows/thread_local_key.rs
Labels: A-LLVM, A-codegen, S-waiting-on-bors, T-compiler, merged-by-bors

#79818 Fixes to Rust coverage
  compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs
  compiler/rustc_mir/src/transform/coverage/graph.rs
  compiler/rustc_mir/src/transform/coverage/mod.rs
  compiler/rustc_mir/src/transform/coverage/spans.rs
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
  src/test/run-make-fulldeps/coverage-reports/Makefile
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.uses_crate.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.async.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.generics.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage_counters.uses_crate.txt
Labels: S-waiting-on-bors

#79824 Strip prefix instead of replacing it with empty string
  compiler/rustc_typeck/src/check/demand.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#79826 Simplify visit_{foreign,trait}_item
  compiler/rustc_passes/src/dead.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#79844 Move RWUTable to a separate module
  compiler/rustc_passes/src/liveness.rs
  compiler/rustc_passes/src/liveness/rwu_table.rs
Labels: S-waiting-on-bors

#79862 Remove tab-lock and replace it with ctrl+up/down arrows to switch between search result tabs
  src/librustdoc/html/static/main.js
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#79732 minor stylistic clippy cleanups
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/different_lifetimes.rs
  compiler/rustc_lint/src/nonstandard_style.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/region_name.rs
  src/bootstrap/setup.rs
  src/librustdoc/html/markdown.rs
Labels: S-waiting-on-bors

#79750 Fix trimming of lint docs
  src/tools/lint-docs/src/lib.rs
Labels: A-lint, A-rustbuild, S-waiting-on-bors, T-doc

#79777 Remove `first_merge` from liveness debug logs
  compiler/rustc_passes/src/liveness.rs
Labels: S-waiting-on-bors

#79795 Privatize some of libcore unicode_internals
  library/alloc/src/str.rs
  library/core/src/unicode/mod.rs
Labels: S-waiting-on-bors

#79803 Update xsv to prevent random CI failures
  src/tools/cargotest/main.rs
Labels: A-testsuite, S-waiting-on-bors

#79810 Account for gaps in def path table during decoding
  compiler/rustc_metadata/src/rmeta/decoder.rs
Labels: A-metadata, S-waiting-on-bors, T-compiler

#78837 Accept arbitrary expressions in key-value attributes at parse time
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_span/src/symbol.rs
  src/test/rustdoc/external-doc.rs
  src/test/ui/ast-json/ast-json-noexpand-output.stdout
  src/test/ui/ast-json/ast-json-output.stdout
  src/test/ui/attr-eq-token-tree.rs
  src/test/ui/attr-eq-token-tree.stderr
  src/test/ui/attributes/key-value-expansion.rs
  src/test/ui/attributes/key-value-expansion.stderr
  src/test/ui/feature-gates/feature-gate-extended_key_value_attributes.rs
  src/test/ui/feature-gates/feature-gate-extended_key_value_attributes.stderr
  src/test/ui/macros/macro-attribute.rs
  src/test/ui/macros/macro-attribute.stderr
  src/test/ui/malformed/malformed-interpolated.rs
  src/test/ui/malformed/malformed-interpolated.stderr
  src/test/ui/parser/attr-bad-meta-2.rs
  src/test/ui/parser/attr-bad-meta-2.stderr
  src/test/ui/suffixed-literal-meta.rs
  src/test/ui/suffixed-literal-meta.stderr
Labels: A-attributes, S-waiting-on-bors, T-lang, merged-by-bors

#79274 implement better availability probing for copy_file_range
  library/std/src/sys/unix/kernel_copy.rs
Labels: S-waiting-on-bors, merged-by-bors

#79621 Constier maybe uninit
  compiler/rustc_mir/src/const_eval/error.rs
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/terminator.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/tests/lib.rs
  library/core/tests/mem.rs
  src/test/ui/assume-type-intrinsics.rs
  src/test/ui/assume-type-intrinsics.stderr
Labels: A-const-eval, S-waiting-on-bors, merged-by-bors

#79801 rustc_codegen_ssa: use bitcasts instead of type punning for scalar transmutes.
  compiler/rustc_codegen_ssa/src/mir/block.rs
  src/test/codegen/transmute-scalar.rs
Labels: S-waiting-on-bors, merged-by-bors

#79536 ci: use 20.04 on x86_64-gnu-nopt builder
  src/ci/docker/host-x86_64/x86_64-gnu-nopt/Dockerfile
Labels: A-testsuite, S-waiting-on-bors, T-infra, merged-by-bors

#79814 fix soundness issue in `make_contiguous`
  library/alloc/src/collections/vec_deque/mod.rs
  library/alloc/src/collections/vec_deque/tests.rs
Labels: A-collections, S-waiting-on-bors, T-libs, beta-accepted, libs-impl, merged-by-bors, stable-accepted

#79903 [beta] backports
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs
  compiler/rustc_typeck/src/check/pat.rs
  compiler/rustc_typeck/src/check/writeback.rs
  library/alloc/src/collections/vec_deque.rs
  library/alloc/src/collections/vec_deque/tests.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.stderr
  src/test/ui/match/type_polymorphic_byte_str_literals.rs
  src/test/ui/match/type_polymorphic_byte_str_literals.stderr
  src/test/ui/pattern/usefulness/match-byte-array-patterns-2.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-allowed.rs
Labels: S-waiting-on-bors, merged-by-bors

#77801 Enforce no-move rule of ReentrantMutex using Pin and fix UB in stdio
  library/std/src/io/stdio.rs
  library/std/src/lazy.rs
  library/std/src/lib.rs
  library/std/src/sys_common/remutex.rs
  library/std/src/sys_common/remutex/tests.rs
Labels: I-nominated, S-waiting-on-bors, T-libs, beta-accepted, merged-by-bors

#79656 Add some core::cmp::Ordering helpers
  library/core/src/cmp.rs
Labels: S-waiting-on-bors, merged-by-bors

#79871 Fix small typo in `wrapping_shl` documentation
  library/core/src/num/int_macros.rs
Labels: S-waiting-on-bors

#79896 Make search results tab and help button focusable with keyboard
  src/librustdoc/html/layout.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#79917 Use Symbol for inline asm register class names
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/mod.rs
Labels: S-waiting-on-bors

#79927 Rollup of 11 pull requests
  .github/ISSUE_TEMPLATE/library_tracking_issue.md
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0212.md
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/coverage/debug.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/lib.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/mod.rs
  compiler/rustc_target/src/lib.rs
  compiler/rustc_target/src/spec/apple_base.rs
  compiler/rustc_typeck/src/collect.rs
  library/alloc/src/string.rs
  library/core/src/num/int_macros.rs
  library/std/src/f32.rs
  library/std/src/f64.rs
  library/std/src/lib.rs
  library/std/src/sys/unix/kernel_copy/tests.rs
  library/std/src/sys_common/net.rs
  library/test/src/lib.rs
  library/test/src/time.rs
  src/doc/unstable-book/src/language-features/const-fn.md
  src/librustdoc/config.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.fixed
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-struct.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-struct.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.fixed
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.stderr
  src/test/ui/parser/trait-item-with-defaultness-fail-semantic.rs
  src/test/ui/parser/trait-item-with-defaultness-fail-semantic.stderr
  src/tools/linkchecker/main.rs
  src/tools/tidy/src/cargo.rs
  src/tools/tidy/src/error_codes_check.rs
  src/tools/tidy/src/extdeps.rs
  src/tools/tidy/src/features.rs
  src/tools/tidy/src/lib.rs
  src/tools/tidy/src/ui_tests.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#79639 Add long explanation for E0212
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0212.md
  compiler/rustc_typeck/src/collect.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.fixed
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-struct.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-struct.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.fixed
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.rs
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.stderr
Labels: A-diagnostics, A-lifetimes, S-waiting-on-bors, T-compiler

#79698 Add tracking issue template for library features.
  .github/ISSUE_TEMPLATE/library_tracking_issue.md
Labels: A-meta, S-waiting-on-bors, T-libs

#79809 Dogfood `str_split_once()`
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/coverage/debug.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/lib.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_target/src/lib.rs
  compiler/rustc_target/src/spec/apple_base.rs
  library/std/src/lib.rs
  library/std/src/sys_common/net.rs
  library/test/src/lib.rs
  library/test/src/time.rs
  src/librustdoc/config.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/tools/linkchecker/main.rs
  src/tools/tidy/src/cargo.rs
  src/tools/tidy/src/error_codes_check.rs
  src/tools/tidy/src/extdeps.rs
  src/tools/tidy/src/features.rs
  src/tools/tidy/src/lib.rs
  src/tools/tidy/src/ui_tests.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, libs-impl

#79851 Clarify the 'default is only allowed on...' error
  compiler/rustc_ast_passes/src/ast_validation.rs
  src/test/ui/parser/trait-item-with-defaultness-fail-semantic.rs
  src/test/ui/parser/trait-item-with-defaultness-fail-semantic.stderr
Labels: A-diagnostics, A-specialization, F-specialization, S-waiting-on-bors

#79858 Update const-fn doc in unstable-book
  src/doc/unstable-book/src/language-features/const-fn.md
Labels: S-waiting-on-bors

#79860 Clarify that String::split_at takes a byte index.
  library/alloc/src/string.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#79375 Make the kernel_copy tests more robust/concurrent.
  library/std/src/sys/unix/kernel_copy/tests.rs
Labels: S-waiting-on-bors

#77027 Improve documentation for `std::{f32,f64}::mul_add`
  library/std/src/f32.rs
  library/std/src/f64.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#79893 Windows TLS: ManuallyDrop instead of mem::forget
  library/std/src/sys/windows/thread_local_key.rs
Labels: S-waiting-on-bors, merged-by-bors

#79915 Use `def_path_hash_to_def_id` when re-using a `RawDefId`
  compiler/rustc_middle/src/dep_graph/mod.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_query_system/src/dep_graph/graph.rs
  src/test/incremental/auxiliary/issue-79890.rs
  src/test/incremental/issue-79890-imported-crates-changed.rs
Labels: S-waiting-on-bors, merged-by-bors

#79910 CTFE: tweak abort-on-uninhabited message
  compiler/rustc_mir/src/interpret/intrinsics.rs
  src/test/ui/consts/assume-type-intrinsics.rs
  src/test/ui/consts/assume-type-intrinsics.stderr
Labels: A-const-eval, S-waiting-on-bors, T-compiler, merged-by-bors

#79925 Improve wording of `flatten()` docs
  library/core/src/iter/traits/iterator.rs
  library/core/src/option.rs
  library/core/src/result.rs
Labels: A-iterators, A-result-option, S-waiting-on-bors, T-doc, merged-by-bors

#79349 Apply `doc(cfg)` from parent items while collecting trait impls
  src/librustdoc/clean/inline.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/test/rustdoc/doc-cfg.rs
  src/test/rustdoc/issue-79201.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, merged-by-bors

#79553 Capture precise paths in THIR and MIR
  compiler/rustc_middle/src/hir/place.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir_build/src/build/expr/as_place.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_mir_build/src/thir/cx/expr.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/check/writeback.rs
  compiler/rustc_typeck/src/expr_use_visitor.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/arrays.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/arrays.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/box.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/box.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/multilevel-path.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/multilevel-path.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/simple-struct-min-capture.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/simple-struct-min-capture.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/box.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/box.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-struct.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-struct.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-tuple-mut.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-tuple-mut.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-tuple.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/capture-disjoint-field-tuple.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/disjoint-capture-in-same-closure.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/disjoint-capture-in-same-closure.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/filter-on-struct-member.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/filter-on-struct-member.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-1.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-1.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-2.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-2.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-3.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/multilevel-path-3.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/nested-closure.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/nested-closure.stderr
Labels: A-closures, A-mir, S-waiting-on-bors, merged-by-bors

#79931 make redundant StorageLive UB
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/interpret/step.rs
Labels: A-const-eval, S-waiting-on-bors, T-compiler, merged-by-bors

#79169 Create `rustc_type_ir`
  Cargo.lock
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_type_ir/Cargo.toml
  compiler/rustc_type_ir/src/lib.rs
Labels: A-typesystem, S-waiting-on-bors, T-compiler, WG-compiler-traits, merged-by-bors

#79370 Don't abort rustdoc tests if `tidy` isn't installed
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: A-contributor-roadblock, A-testsuite, S-waiting-on-bors, T-rustdoc, merged-by-bors

#79969 tidy: Re-enable check for inline unit tests
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_feature/src/lib.rs
  compiler/rustc_feature/src/tests.rs
  src/tools/tidy/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#79957 [rustdoc] Calculate span information on demand instead of storing it ahead of time
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
Labels: I-compilemem, S-waiting-on-bors, T-rustdoc, merged-by-bors

#79976 Remove incorrect assert
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc, merged-by-bors

#79988 BTreeMap: capture a recurring use pattern as replace_kv
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/remove.rs
Labels: S-waiting-on-bors, merged-by-bors

#79940 fix more clippy::complexity findings
  compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_llvm/build.rs
  compiler/rustc_mir/src/transform/coverage/debug.rs
  compiler/rustc_mir/src/transform/early_otherwise_branch.rs
  compiler/rustc_mir_build/src/build/scope.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_trait_selection/src/traits/select/confirmation.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/collect.rs
  src/bootstrap/dist.rs
  src/bootstrap/sanity.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#79942 Add post-init hook for static memory for miri.
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/traits.rs
Labels: S-waiting-on-bors

#79954 Fix building compiler docs with stage 0
  src/bootstrap/builder.rs
  src/bootstrap/doc.rs
Labels: A-rustbuild, S-waiting-on-bors, T-compiler, T-rustdoc

#79963 Fix typo in `DebruijnIndex` documentation
  compiler/rustc_type_ir/src/lib.rs
Labels: C-cleanup, S-waiting-on-bors

#79970 Misc rustbuild improvements when the LLVM backend isn't used
  src/bootstrap/bootstrap.py
  src/bootstrap/sanity.rs
Labels: A-rustbuild, S-waiting-on-bors

#79973 rustdoc light theme: Fix CSS for selected buttons
  src/librustdoc/html/static/themes/light.css
Labels: A-rustdoc-search, A-rustdoc-themes, A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#79984 Remove an unused dependency that made `rustdoc` crash
  Cargo.lock
  compiler/rustc_mir/src/transform/coverage/test_macros/Cargo.toml
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#79985 Fixes submit event of the search input
  src/librustdoc/html/layout.rs
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#79994 Rollup of 12 pull requests
  Cargo.lock
  compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_llvm/build.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/traits.rs
  compiler/rustc_mir/src/transform/coverage/debug.rs
  compiler/rustc_mir/src/transform/coverage/test_macros/Cargo.toml
  compiler/rustc_mir/src/transform/early_otherwise_branch.rs
  compiler/rustc_mir_build/src/build/scope.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_trait_selection/src/traits/select/confirmation.rs
  compiler/rustc_type_ir/src/lib.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/collect.rs
  library/alloc/src/collections/linked_list.rs
  library/core/src/iter/mod.rs
  library/std/src/keyword_docs.rs
  src/bootstrap/bootstrap.py
  src/bootstrap/builder.rs
  src/bootstrap/dist.rs
  src/bootstrap/doc.rs
  src/bootstrap/sanity.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/static/themes/light.css
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#79834 Remove deprecated linked_list_extras methods.
  library/alloc/src/collections/linked_list.rs
Labels: A-collections, S-waiting-on-bors, T-libs

#79845 Fix rustup support in default_build_triple for python3
  src/bootstrap/bootstrap.py
Labels: A-rustbuild, S-waiting-on-bors

#79360 std::iter: document iteration over `&T` and `&mut T`
  library/core/src/iter/mod.rs
Labels: A-iterators, S-waiting-on-bors, T-doc, T-libs

#79398 Link loop/for keyword
  library/std/src/keyword_docs.rs
Labels: S-waiting-on-bors, T-doc

#79956 Resolve enum field visibility correctly
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/issues/issue-79593.rs
  src/test/ui/issues/issue-79593.stderr
Labels: A-resolve, A-visibility, S-waiting-on-bors, T-compiler, merged-by-bors

#79668 Recover on `const impl<> X for Y`
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/rfc-2632-const-trait-impl/const-impl-norecover.rs
  src/test/ui/rfc-2632-const-trait-impl/const-impl-norecover.stderr
  src/test/ui/rfc-2632-const-trait-impl/const-impl-recovery.rs
  src/test/ui/rfc-2632-const-trait-impl/const-impl-recovery.stderr
Labels: S-waiting-on-bors, merged-by-bors

#79376 BTreeMap: clarify comments and panics around choose_parent_kv
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/remove.rs
Labels: S-waiting-on-bors, merged-by-bors

#79987 BTreeMap: detect bulk_steal's count-1 underflow in release builds too
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, merged-by-bors

#79978 Properly capture trailing 'unglued' token
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/proc-macro/capture-unglued-token.rs
  src/test/ui/proc-macro/capture-unglued-token.stdout
Labels: S-waiting-on-bors, merged-by-bors

#80005 BTreeMap: declare clear_parent_link directly on the root it needs
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, merged-by-bors

#79944 Improve error handling in `symbols` proc-macro
  compiler/rustc_macros/src/lib.rs
  compiler/rustc_macros/src/symbols.rs
  compiler/rustc_macros/src/symbols/tests.rs
Labels: A-contributor-roadblock, A-proc-macros, S-waiting-on-bors, T-compiler, merged-by-bors

#79959 Check the number of entries in UI test on tidy
  src/tools/tidy/src/ui_tests.rs
Labels: A-testsuite, S-waiting-on-bors, merged-by-bors

#80024 Rollup of 3 pull requests
  library/alloc/src/macros.rs
  library/std/src/primitive_docs.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors, merged-by-bors, rollup

#79918 doc(array,vec): add notes about side effects when empty-initializing
  library/alloc/src/macros.rs
  library/std/src/primitive_docs.rs
Labels: S-waiting-on-bors, T-libs

#79936 Fix item name display on mobile
  src/librustdoc/html/static/rustdoc.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#77618 Add fast futex-based thread parker for Windows.
  library/std/src/sys/windows/c.rs
  library/std/src/sys/windows/compat.rs
  library/std/src/sys/windows/mod.rs
  library/std/src/sys/windows/thread_parker.rs
  library/std/src/sys_common/thread_parker/mod.rs
Labels: A-concurrency, O-windows, S-waiting-on-bors, T-libs, disposition-merge, merged-by-bors, proposed-final-comment-period

#79922 Lower `discriminant_value` intrinsic
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_mir/src/transform/lower_intrinsics.rs
  src/test/mir-opt/lower_intrinsics.discriminant.LowerIntrinsics.diff
  src/test/mir-opt/lower_intrinsics.rs
Labels: S-waiting-on-bors, merged-by-bors

#77700 Rustdoc: Cache resolved links in current module
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-link-self-cache.rs
Labels: A-intra-doc-links, C-cleanup, I-compiletime, S-waiting-on-bors, T-rustdoc, merged-by-bors

#78682 Do not inline finish_grow
  library/alloc/src/raw_vec.rs
  library/alloc/src/vec.rs
Labels: I-heavy, S-waiting-on-bors, T-libs, merged-by-bors

#73210 [mir-opt] Allow debuginfo to be generated for a constant or a Place
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_ssa/src/mir/constant.rs
  compiler/rustc_codegen_ssa/src/mir/debuginfo.rs
  compiler/rustc_codegen_ssa/src/mir/mod.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/visit.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/transform/const_debuginfo.rs
  compiler/rustc_mir/src/transform/mod.rs
  compiler/rustc_mir/src/transform/simplify_try.rs
  compiler/rustc_mir/src/util/graphviz.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/mod.rs
  src/test/mir-opt/const_debuginfo.main.ConstDebugInfo.diff
  src/test/mir-opt/const_debuginfo.rs
Labels: A-mir-opt, S-waiting-on-bors, merged-by-bors

#78068 consider assignments of union field of ManuallyDrop type safe
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_middle/src/mir/tcx.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  src/test/ui/union/union-unsafe.rs
  src/test/ui/union/union-unsafe.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors

#80008 Fix `cargo-binutils` link
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
Labels: S-waiting-on-bors

#80016 Use imports instead of rewriting the type signature of `RustcOptGroup::stable`
  src/librustdoc/lib.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc
