Repository rust-lang/rust, pull requests merged in 2020-05, with the labels that each got.

#71721 Rollup of 8 pull requests
  Cargo.lock
  src/bootstrap/compile.rs
  src/liballoc/vec.rs
  src/librustc_codegen_llvm/consts.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/interpret/pointer.rs
  src/librustc_middle/mir/interpret/value.rs
  src/librustc_middle/ty/util.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/test/compile-fail/consts/const-fn-error.rs
  src/test/compile-fail/issue-52443.rs
  src/test/mir-opt/const_allocation/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation/64bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation2/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation2/64bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation3/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation3/64bit/rustc.main.ConstProp.after.mir
  src/test/ui/consts/const-eval/const-pointer-values-in-various-types.stderr
  src/test/ui/consts/const-eval/double_check2.stderr
  src/test/ui/consts/const-eval/ref_to_int_match.stderr
  src/test/ui/consts/const-eval/transmute-const.stderr
  src/test/ui/consts/const-eval/ub-enum.rs
  src/test/ui/consts/const-eval/ub-enum.stderr
  src/test/ui/consts/const-eval/ub-ref.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/consts/const-eval/union-ub.stderr
  src/test/ui/consts/control-flow/feature-gate-const-if-match.rs
  src/test/ui/consts/control-flow/feature-gate-const-if-match.stock.stderr
  src/test/ui/linkage-attr/linkage3.rs
  src/test/ui/or-patterns/feature-gate-const-fn.rs
  src/test/ui/or-patterns/feature-gate-const-fn.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71719 Update backtrace-sys
  Cargo.lock
Labels: S-waiting-on-bors

#71691 Allow `Unreachable` terminators unconditionally in const-checking
  src/librustc_mir/transform/qualify_min_const_fn.rs
Labels: S-waiting-on-bors

#71688 Allow `Downcast` projections unconditionally in const-checking
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/test/compile-fail/consts/const-fn-error.rs
  src/test/compile-fail/issue-52443.rs
  src/test/ui/consts/control-flow/feature-gate-const-if-match.rs
  src/test/ui/consts/control-flow/feature-gate-const-if-match.stock.stderr
  src/test/ui/or-patterns/feature-gate-const-fn.rs
  src/test/ui/or-patterns/feature-gate-const-fn.stderr
Labels: S-waiting-on-bors

#71682 Bump pulldown-cmark
  Cargo.lock
Labels: S-waiting-on-bors, T-rustdoc, beta-nominated

#71590 MIR dump: print pointers consistently with Miri output
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/interpret/pointer.rs
  src/librustc_middle/mir/interpret/value.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/util/pretty.rs
  src/test/mir-opt/const_allocation/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation/64bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation2/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation2/64bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation3/32bit/rustc.main.ConstProp.after.mir
  src/test/mir-opt/const_allocation3/64bit/rustc.main.ConstProp.after.mir
  src/test/ui/consts/const-eval/const-pointer-values-in-various-types.stderr
  src/test/ui/consts/const-eval/double_check2.stderr
  src/test/ui/consts/const-eval/ref_to_int_match.stderr
  src/test/ui/consts/const-eval/transmute-const.stderr
  src/test/ui/consts/const-eval/ub-enum.rs
  src/test/ui/consts/const-eval/ub-enum.stderr
  src/test/ui/consts/const-eval/ub-ref.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/consts/const-eval/union-ub.stderr
Labels: S-waiting-on-bors

#71567 Handle build completion message from Cargo
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#71465 Add a convenience method on `TyCtxt` for checking for thread locals
  src/librustc_codegen_llvm/consts.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/ty/util.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/test/ui/linkage-attr/linkage3.rs
Labels: S-waiting-on-author

#71148 Vec drop and truncate: drop using raw slice *mut [T]
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#70674 Have the per-query caches store the results on arenas
  Cargo.lock
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_ssa/back/symbol_export.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_lint/levels.rs
  src/librustc_macros/src/query.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/decoder/cstore_impl.rs
  src/librustc_middle/arena.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/query/plumbing.rs
  src/librustc_middle/ty/trait_def.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/lints.rs
  src/librustc_passes/diagnostic_items.rs
  src/librustc_passes/lang_items.rs
  src/librustc_passes/lib_features.rs
  src/librustc_passes/reachable.rs
  src/librustc_passes/stability.rs
  src/librustc_query_system/Cargo.toml
  src/librustc_query_system/query/caches.rs
  src/librustc_query_system/query/config.rs
  src/librustc_query_system/query/mod.rs
  src/librustc_query_system/query/plumbing.rs
  src/librustc_resolve/late/lifetimes.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_ty/ty.rs
  src/librustc_typeck/coherence/inherent_impls.rs
  src/librustc_typeck/collect.rs
  src/librustc_typeck/outlives/mod.rs
  src/librustc_typeck/variance/mod.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: S-waiting-on-bors, merged-by-bors

#71623 Disable localization for all linkers
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_target/spec/msvc_base.rs
Labels: S-waiting-on-bors, merged-by-bors

#71704 Miri: tweak error print
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/interpret/pointer.rs
  src/librustc_mir/interpret/machine.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/consts/const-eval/ub-nonnull.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/consts/offset_from_ub.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71759 Rollup of 5 pull requests
  src/librustc_attr/builtin.rs
  src/librustc_codegen_ssa/mir/constant.rs
  src/librustc_hir/hir.rs
  src/librustc_infer/infer/region_constraints/mod.rs
  src/librustc_middle/mir/interpret/error.rs
Labels: S-waiting-on-bors, merged-by-bors

#71755 fix doc reference
  src/librustc_hir/hir.rs
Labels: S-waiting-on-bors

#71752 make Stability doc a more readable (and fix rustdoc warning)
  src/librustc_attr/builtin.rs
Labels: S-waiting-on-bors

#71749 fix Miri error message padding
  src/librustc_middle/mir/interpret/error.rs
Labels: S-waiting-on-bors

#71747 Remove deadcode in eval_mir_constant_to_operand
  src/librustc_codegen_ssa/mir/constant.rs
Labels: S-waiting-on-bors

#71744 remove obsolete comment
  src/librustc_infer/infer/region_constraints/mod.rs
Labels: S-waiting-on-bors

#69808 Avoid duplicating code for each query
  src/librustc_macros/src/query.rs
  src/librustc_middle/dep_graph/dep_node.rs
  src/librustc_middle/dep_graph/mod.rs
  src/librustc_middle/ty/query/mod.rs
  src/librustc_middle/ty/query/on_disk_cache.rs
  src/librustc_middle/ty/query/plumbing.rs
  src/librustc_query_system/dep_graph/dep_node.rs
  src/librustc_query_system/dep_graph/mod.rs
  src/librustc_query_system/query/config.rs
  src/librustc_query_system/query/plumbing.rs
Labels: S-waiting-on-bors, merged-by-bors

#71776 Rollup of 5 pull requests
  src/libcore/ptr/const_ptr.rs
  src/libcore/ptr/mut_ptr.rs
  src/librustc_ast/ast.rs
  src/librustc_infer/infer/at.rs
  src/librustc_infer/infer/canonical/query_response.rs
  src/librustc_infer/infer/nll_relate/mod.rs
  src/librustc_interface/passes.rs
  src/librustc_middle/dep_graph/dep_node.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/traits/mod.rs
  src/librustc_middle/traits/structural_impls.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/query/keys.rs
  src/librustc_middle/ty/query/mod.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_middle/ty/subst.rs
  src/librustc_mir/borrow_check/type_check/relate_tys.rs
  src/librustc_traits/lib.rs
  src/librustc_traits/lowering/environment.rs
  src/librustc_traits/lowering/mod.rs
  src/librustc_typeck/check/coercion.rs
  src/test/ui/const-generics/different_byref.rs
  src/test/ui/const-generics/different_byref.stderr
  src/test/ui/const-generics/issues/issue-68615-adt.rs
  src/test/ui/const-generics/issues/issue-68615-array.rs
Labels: S-waiting-on-bors, merged-by-bors

#71762 doc: this resulted in a link pointing to a non-existent target
  src/librustc_ast/ast.rs
Labels: S-waiting-on-bors

#71761 doc: reference does not exist, probably a typo
  src/librustc_ast/ast.rs
Labels: S-waiting-on-bors

#71758 Remove leftover chalk types
  src/librustc_infer/infer/canonical/query_response.rs
  src/librustc_infer/infer/nll_relate/mod.rs
  src/librustc_interface/passes.rs
  src/librustc_middle/dep_graph/dep_node.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/traits/mod.rs
  src/librustc_middle/traits/structural_impls.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/query/keys.rs
  src/librustc_middle/ty/query/mod.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_middle/ty/subst.rs
  src/librustc_mir/borrow_check/type_check/relate_tys.rs
  src/librustc_traits/lib.rs
  src/librustc_traits/lowering/environment.rs
  src/librustc_traits/lowering/mod.rs
Labels: S-waiting-on-bors

#71760 Document unsafety for `*const T` and `*mut T`
  src/libcore/ptr/const_ptr.rs
  src/libcore/ptr/mut_ptr.rs
Labels: S-waiting-on-bors

#71018 handle ConstValue::ByRef in relate
  src/librustc_infer/infer/at.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_typeck/check/coercion.rs
  src/test/ui/const-generics/different_byref.rs
  src/test/ui/const-generics/different_byref.stderr
  src/test/ui/const-generics/issues/issue-68615-adt.rs
  src/test/ui/const-generics/issues/issue-68615-array.rs
Labels: S-waiting-on-bors

#71716 Rename `bitcode-in-rlib` option to `embed-bitcode`
  src/bootstrap/compile.rs
  src/doc/rustc/src/codegen-options/index.md
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_interface/tests.rs
  src/librustc_session/config.rs
  src/librustc_session/options.rs
  src/test/ui/lto-and-no-bitcode-in-rlib.rs
  src/test/ui/lto-and-no-bitcode-in-rlib.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#70170 wf: handle "livelock" checking before reaching `WfPredicates::compute`.
  src/librustc_trait_selection/traits/wf.rs
Labels: S-waiting-on-bors, merged-by-bors

#71795 Rollup of 6 pull requests
  Cargo.lock
  src/bootstrap/builder.rs
  src/librustc_middle/Cargo.toml
  src/librustc_middle/lib.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/mir/interpret/pointer.rs
  src/librustc_middle/mir/interpret/value.rs
  src/librustc_mir/const_eval/error.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_trait_selection/traits/util.rs
  src/test/ui/non-ice-error-on-worker-io-fail.rs
  src/test/ui/non-ice-error-on-worker-io-fail.stderr
  src/test/ui/suggestions/expected-boxed-future-isnt-pinned.rs
  src/test/ui/suggestions/expected-boxed-future-isnt-pinned.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71782 Use a non-existent test path instead of clobbering /dev/null
  src/test/ui/non-ice-error-on-worker-io-fail.rs
  src/test/ui/non-ice-error-on-worker-io-fail.stderr
Labels: S-waiting-on-bors

#71781 Uncomment test code for failure to use `Box::pin`
  src/test/ui/suggestions/expected-boxed-future-isnt-pinned.rs
  src/test/ui/suggestions/expected-boxed-future-isnt-pinned.stderr
Labels: S-waiting-on-bors

#71739 remove obsolete comment
  src/librustc_trait_selection/traits/util.rs
Labels: S-waiting-on-bors

#71738 remove AllocId generalization of Pointer
  src/librustc_middle/mir/interpret/pointer.rs
  src/librustc_middle/mir/interpret/value.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
Labels: S-waiting-on-bors

#71736 bootstrap: also apply unused-attributes hack without deny_warnings
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#71712 Miri: port error backtraces to std::backtrace
  Cargo.lock
  src/librustc_middle/Cargo.toml
  src/librustc_middle/lib.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_mir/const_eval/error.rs
Labels: S-waiting-on-bors

#69274 Implement RFC 2396: `#[target_feature]` 1.1
  src/librustc_feature/active.rs
  src/librustc_middle/ty/error.rs
  src/librustc_middle/ty/structural_impls.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_span/symbol.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/collect.rs
  src/test/ui/macros/issue-68060.stderr
  src/test/ui/rfcs/rfc-2396-target_feature-11/check-pass.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/feature-gate-target_feature_11.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/feature-gate-target_feature_11.stderr
  src/test/ui/rfcs/rfc-2396-target_feature-11/fn-ptr.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/fn-ptr.stderr
  src/test/ui/rfcs/rfc-2396-target_feature-11/safe-calls.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/safe-calls.stderr
  src/test/ui/rfcs/rfc-2396-target_feature-11/trait-impl.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/trait-impl.stderr
  src/test/ui/target-feature/invalid-attribute.rs
  src/test/ui/target-feature/invalid-attribute.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71787 fix rustdoc warnings
  src/librustc_builtin_macros/deriving/generic/ty.rs
  src/librustc_builtin_macros/test_harness.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_ssa/traits/declare.rs
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_data_structures/transitive_relation.rs
  src/librustc_hir/arena.rs
  src/librustc_infer/infer/error_reporting/mod.rs
  src/librustc_infer/infer/mod.rs
  src/librustc_infer/infer/region_constraints/mod.rs
  src/librustc_lint/levels.rs
  src/librustc_middle/arena.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/query.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/transform/cleanup_post_borrowck.rs
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/lib.rs
  src/librustc_span/hygiene.rs
  src/librustc_trait_selection/traits/coherence.rs
  src/librustc_ty/ty.rs
  src/librustc_typeck/check/regionck.rs
  src/librustc_typeck/mem_categorization.rs
  src/librustdoc/html/toc.rs
Labels: S-waiting-on-bors

#71785 Update comment regarding SO_REUSEADDR on Windows
  src/libstd/sys/windows/c.rs
  src/libstd/sys_common/net.rs
Labels: O-windows, S-waiting-on-bors, libs-impl

#71784 Remove recommendation for unmaintained dirs crate
  src/libstd/env.rs
Labels: S-waiting-on-bors

#71777 cleanup: `config::CrateType` -> `CrateType`
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/symbol_export.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/util.rs
  src/librustc_metadata/creader.rs
  src/librustc_metadata/dependency_format.rs
  src/librustc_metadata/locator.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_middle/middle/dependency_format.rs
  src/librustc_middle/ty/context.rs
  src/librustc_passes/entry.rs
  src/librustc_passes/reachable.rs
  src/librustc_passes/weak_lang_items.rs
  src/librustc_session/output.rs
  src/librustc_session/session.rs
  src/librustdoc/core.rs
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#71772 Mark query function as must_use.
  src/librustc_codegen_ssa/base.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_middle/ty/query/plumbing.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_passes/check_attr.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/collect.rs
Labels: S-waiting-on-bors

#71767 doc: make Stack and StackElement a little pretty
  src/libserialize/json.rs
Labels: S-waiting-on-bors

#71815 Don't bust caches on x.py check/build switches
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/native.rs
  src/librustc_llvm/build.rs
Labels: S-waiting-on-bors, merged-by-bors

#71828 Rollup of 5 pull requests
  Cargo.lock
  src/doc/unstable-book/src/language-features/cfg-version.md
  src/libcore/slice/mod.rs
  src/librustc_attr/Cargo.toml
  src/librustc_attr/build.rs
  src/librustc_attr/builtin.rs
  src/librustc_attr/lib.rs
  src/librustc_expand/proc_macro_server.rs
  src/librustc_feature/active.rs
  src/librustc_feature/builtin_attrs.rs
  src/librustc_infer/infer/nll_relate/mod.rs
  src/librustc_lint/Cargo.toml
  src/librustc_lint/levels.rs
  src/librustc_lint/non_ascii_idents.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_session/parse.rs
  src/librustc_span/symbol.rs
  src/librustc_trait_selection/traits/on_unimplemented.rs
  src/test/ui/consts/const_in_pattern/auxiliary/consts.rs
  src/test/ui/consts/const_in_pattern/cross-crate-fail.rs
  src/test/ui/consts/const_in_pattern/cross-crate-fail.stderr
  src/test/ui/consts/const_in_pattern/cross-crate-pass.rs
  src/test/ui/feature-gates/feature-gate-cfg-version.rs
  src/test/ui/feature-gates/feature-gate-cfg-version.stderr
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-confusable-idents.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-confusable-idents.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71813 Decode qualifs for associated const defaults
  src/librustc_metadata/rmeta/decoder.rs
  src/test/ui/consts/const_in_pattern/auxiliary/consts.rs
  src/test/ui/consts/const_in_pattern/cross-crate-fail.rs
  src/test/ui/consts/const_in_pattern/cross-crate-fail.stderr
  src/test/ui/consts/const_in_pattern/cross-crate-pass.rs
Labels: S-waiting-on-bors

#71806 typo
  src/librustc_infer/infer/nll_relate/mod.rs
Labels: S-waiting-on-bors

#71542 Implement `confusable_idents` lint.
  Cargo.lock
  src/librustc_expand/proc_macro_server.rs
  src/librustc_lint/Cargo.toml
  src/librustc_lint/levels.rs
  src/librustc_lint/non_ascii_idents.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_session/parse.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-confusable-idents.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-confusable-idents.stderr
Labels: F-non_ascii_idents, S-waiting-on-bors

#71314 Implement RFC 2523, `#[cfg(version(..))]`
  Cargo.lock
  src/doc/unstable-book/src/language-features/cfg-version.md
  src/librustc_attr/Cargo.toml
  src/librustc_attr/build.rs
  src/librustc_attr/builtin.rs
  src/librustc_attr/lib.rs
  src/librustc_feature/active.rs
  src/librustc_feature/builtin_attrs.rs
  src/librustc_span/symbol.rs
  src/librustc_trait_selection/traits/on_unimplemented.rs
  src/test/ui/feature-gates/feature-gate-cfg-version.rs
  src/test/ui/feature-gates/feature-gate-cfg-version.stderr
Labels: S-waiting-on-bors

#71165 `slice::fill`: use `T` instead of generic arg
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, T-libs

#70825 typeck: always expose explicit enum discriminant `AnonConst`s' parent in `generics_of`.
  src/librustc_middle/ty/mod.rs
  src/librustc_typeck/check/wfcheck.rs
  src/librustc_typeck/collect.rs
  src/test/ui/enum-discriminant/issue-70453-generics-in-discr-ice-2.rs
  src/test/ui/enum-discriminant/issue-70453-generics-in-discr-ice-2.stderr
  src/test/ui/enum-discriminant/issue-70453-generics-in-discr-ice.rs
  src/test/ui/enum-discriminant/issue-70453-generics-in-discr-ice.stderr
  src/test/ui/enum-discriminant/issue-70453-polymorphic-ctfe.rs
Labels: S-waiting-on-bors, merged-by-bors

#71853 Rollup of 4 pull requests
  src/libcore/cell.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0539.md
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/libstd/sync/once.rs
  src/test/run-make/wasm-panic-small/foo.rs
  src/test/ui/issues/issue-32122-1.stderr
  src/test/ui/issues/issue-32122-2.stderr
  src/test/ui/issues/issue-71676-1.fixed
  src/test/ui/issues/issue-71676-1.rs
  src/test/ui/issues/issue-71676-1.stderr
  src/test/ui/issues/issue-71676-2.rs
  src/test/ui/issues/issue-71676-2.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.noopt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt_with_overflow_checks.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.rs
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
  src/test/ui/traits/negative-impls/pin-unsound-issue-66544-clone.rs
  src/test/ui/traits/negative-impls/pin-unsound-issue-66544-derefmut.rs
Labels: S-waiting-on-bors, merged-by-bors

#71808 Add long error explanation for E0539
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0539.md
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: S-waiting-on-bors

#71726 Suggest deref when coercing `ty::Ref` to `ty::RawPtr` with arbitrary mutability
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/mod.rs
  src/test/ui/issues/issue-32122-1.stderr
  src/test/ui/issues/issue-32122-2.stderr
  src/test/ui/issues/issue-71676-1.fixed
  src/test/ui/issues/issue-71676-1.rs
  src/test/ui/issues/issue-71676-1.stderr
  src/test/ui/issues/issue-71676-2.rs
  src/test/ui/issues/issue-71676-2.stderr
Labels: S-waiting-on-bors

#71663 Fix exceeding bitshifts not emitting for assoc. consts (properly this time, I swear!)
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/lint/lint-exceeding-bitshifts.noopt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt_with_overflow_checks.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.rs
Labels: S-waiting-on-bors

#71398 Add `RefCell::take`
  src/libcore/cell.rs
  src/libstd/sync/once.rs
  src/test/run-make/wasm-panic-small/foo.rs
  src/test/ui/traits/negative-impls/pin-unsound-issue-66544-clone.rs
  src/test/ui/traits/negative-impls/pin-unsound-issue-66544-derefmut.rs
Labels: S-waiting-on-author

#71006 Use existing framework for backward dataflow analyses
  src/librustc_codegen_ssa/mir/analyze.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/liveness/trace.rs
  src/librustc_mir/dataflow/framework/cursor.rs
  src/librustc_mir/dataflow/framework/direction.rs
  src/librustc_mir/dataflow/framework/engine.rs
  src/librustc_mir/dataflow/framework/graphviz.rs
  src/librustc_mir/dataflow/framework/mod.rs
  src/librustc_mir/dataflow/framework/tests.rs
  src/librustc_mir/dataflow/framework/visitor.rs
  src/librustc_mir/dataflow/impls/liveness.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/dataflow/impls/storage_liveness.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/lib.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/rustc_peek.rs
  src/librustc_mir/util/liveness.rs
  src/librustc_span/symbol.rs
  src/test/ui/mir-dataflow/liveness-ptr.rs
  src/test/ui/mir-dataflow/liveness-ptr.stderr
  src/tools/clippy/clippy_lints/src/redundant_clone.rs
Labels: S-waiting-on-bors, merged-by-bors

#71631 Miri: unleash all feature gates
  src/librustc_interface/interface.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_session/session.rs
  src/test/ui/consts/const-eval/const_fn_ptr.rs
  src/test/ui/consts/const-eval/const_fn_ptr.stderr
  src/test/ui/consts/const-eval/const_fn_ptr_fail.rs
  src/test/ui/consts/const-eval/const_fn_ptr_fail.stderr
  src/test/ui/consts/const-eval/const_fn_ptr_fail2.rs
  src/test/ui/consts/const-eval/const_fn_ptr_fail2.stderr
  src/test/ui/consts/const-points-to-static.rs
  src/test/ui/consts/const-points-to-static.stderr
  src/test/ui/consts/const-prop-read-static-in-const.rs
  src/test/ui/consts/const-prop-read-static-in-const.stderr
  src/test/ui/consts/miri_unleashed/abi-mismatch.rs
  src/test/ui/consts/miri_unleashed/abi-mismatch.stderr
  src/test/ui/consts/miri_unleashed/assoc_const.rs
  src/test/ui/consts/miri_unleashed/assoc_const.stderr
  src/test/ui/consts/miri_unleashed/box.rs
  src/test/ui/consts/miri_unleashed/box.stderr
  src/test/ui/consts/miri_unleashed/const_refers_to_static.rs
  src/test/ui/consts/miri_unleashed/const_refers_to_static.stderr
  src/test/ui/consts/miri_unleashed/const_refers_to_static2.rs
  src/test/ui/consts/miri_unleashed/const_refers_to_static2.stderr
  src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs
  src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.stderr
  src/test/ui/consts/miri_unleashed/drop.rs
  src/test/ui/consts/miri_unleashed/drop.stderr
  src/test/ui/consts/miri_unleashed/inline_asm.rs
  src/test/ui/consts/miri_unleashed/inline_asm.stderr
  src/test/ui/consts/miri_unleashed/mutable_const.rs
  src/test/ui/consts/miri_unleashed/mutable_const.stderr
  src/test/ui/consts/miri_unleashed/mutable_const2.rs
  src/test/ui/consts/miri_unleashed/mutable_const2.stderr
  src/test/ui/consts/miri_unleashed/mutable_references.rs
  src/test/ui/consts/miri_unleashed/mutable_references.stderr
  src/test/ui/consts/miri_unleashed/mutable_references_ice.rs
  src/test/ui/consts/miri_unleashed/mutable_references_ice.stderr
  src/test/ui/consts/miri_unleashed/non_const_fn.rs
  src/test/ui/consts/miri_unleashed/non_const_fn.stderr
  src/test/ui/consts/read_from_static_mut_ref.rs
  src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.rs
  src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71866 Rollup of 4 pull requests
  CONTRIBUTING.md
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/test/ui/nll/type-check-pointer-comparisons.rs
  src/test/ui/nll/type-check-pointer-comparisons.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71864 Update link in contributing.md
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#71844 List Clippy as a subtree, instead of a submodule
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#71801 Correctly check comparison operator in MIR typeck
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/test/ui/nll/type-check-pointer-comparisons.rs
  src/test/ui/nll/type-check-pointer-comparisons.stderr
Labels: S-waiting-on-bors

#71645 Direct contributors to try stage 0 rustdoc first
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#71108 On type mismatch involving associated type, suggest constraint
  src/librustc_infer/infer/error_reporting/mod.rs
  src/librustc_middle/traits/mod.rs
  src/librustc_middle/traits/structural_impls.rs
  src/librustc_middle/ty/error.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/compare_method.rs
  src/test/ui/associated-const/associated-const-generic-obligations.stderr
  src/test/ui/associated-types/associated-types-eq-3.stderr
  src/test/ui/associated-types/associated-types-issue-20346.stderr
  src/test/ui/associated-types/associated-types-multiple-types-one-trait.stderr
  src/test/ui/associated-types/defaults-in-other-trait-items.rs
  src/test/ui/associated-types/defaults-in-other-trait-items.stderr
  src/test/ui/associated-types/defaults-specialization.stderr
  src/test/ui/associated-types/impl-trait-return-missing-constraint.rs
  src/test/ui/associated-types/impl-trait-return-missing-constraint.stderr
  src/test/ui/associated-types/issue-26681.stderr
  src/test/ui/generic-associated-types/iterable.stderr
  src/test/ui/hrtb/issue-62203-hrtb-ice.stderr
  src/test/ui/impl-trait/bound-normalization-fail.stderr
  src/test/ui/impl-trait/equality2.stderr
  src/test/ui/impl-trait/universal-mismatched-type.stderr
  src/test/ui/issues/issue-13853.stderr
  src/test/ui/issues/issue-20225.stderr
  src/test/ui/issues/issue-32323.stderr
  src/test/ui/issues/issue-69306.stderr
  src/test/ui/mismatched_types/issue-35030.stderr
  src/test/ui/specialization/specialization-default-projection.stderr
  src/test/ui/specialization/specialization-default-types.stderr
  src/test/ui/suggestions/expected-boxed-future-isnt-pinned.stderr
  src/test/ui/suggestions/trait-with-missing-associated-type-restriction-fixable.fixed
  src/test/ui/suggestions/trait-with-missing-associated-type-restriction-fixable.rs
  src/test/ui/suggestions/trait-with-missing-associated-type-restriction-fixable.stderr
  src/test/ui/suggestions/trait-with-missing-associated-type-restriction.rs
  src/test/ui/suggestions/trait-with-missing-associated-type-restriction.stderr
  src/test/ui/type-alias-enum-variants/enum-variant-generic-args.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71751 Move recursion check for zsts back to read site instead of access check site
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/test/ui/consts/ice-zst-static-access.rs
Labels: S-waiting-on-bors, merged-by-bors

#71754 Don't copy bytecode files into the incr. comp. cache.
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_incremental/persist/work_product.rs
  src/librustc_middle/dep_graph/mod.rs
  src/librustc_query_system/dep_graph/graph.rs
  src/librustc_query_system/dep_graph/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#71879 Rollup of 5 pull requests
  src/libcore/num/f64.rs
  src/librustc_builtin_macros/test_harness.rs
  src/librustc_lint/lib.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir_build/hair/pattern/const_to_pat.rs
  src/librustc_trait_selection/traits/structural_match.rs
  src/librustc_typeck/check/op.rs
  src/test/mir-opt/const_prop/scalar_literal_propagation/rustc.main.ConstProp.diff
  src/test/mir-opt/simplify-locals-removes-unused-consts/rustc.main.SimplifyLocals.diff
  src/test/ui/const-generics/issues/issue-63322-forbid-dyn.rs
  src/test/ui/const-generics/issues/issue-63322-forbid-dyn.stderr
  src/test/ui/issues-71798.rs
  src/test/ui/issues-71798.stderr
  src/test/ui/match/issue-70972-dyn-trait.rs
  src/test/ui/match/issue-70972-dyn-trait.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71877 Use f64 in f64 examples
  src/libcore/num/f64.rs
Labels: S-waiting-on-bors

#71810 Do not try to find binop method on RHS `TyErr`
  src/librustc_typeck/check/op.rs
  src/test/ui/issues-71798.rs
  src/test/ui/issues-71798.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#71773 doc: misc rustdoc things
  src/librustc_builtin_macros/test_harness.rs
  src/librustc_lint/lib.rs
Labels: S-waiting-on-bors

#71697 Added MIR constant propagation of Scalars into function call arguments
  src/librustc_mir/transform/const_prop.rs
  src/test/mir-opt/const_prop/scalar_literal_propagation/rustc.main.ConstProp.diff
  src/test/mir-opt/simplify-locals-removes-unused-consts/rustc.main.SimplifyLocals.diff
Labels: S-waiting-on-bors

#71038 forbid `dyn Trait` in patterns
  src/librustc_mir_build/hair/pattern/const_to_pat.rs
  src/librustc_trait_selection/traits/structural_match.rs
  src/test/ui/const-generics/issues/issue-63322-forbid-dyn.rs
  src/test/ui/const-generics/issues/issue-63322-forbid-dyn.stderr
  src/test/ui/match/issue-70972-dyn-trait.rs
  src/test/ui/match/issue-70972-dyn-trait.stderr
Labels: F-const_generics, S-waiting-on-bors

#71907 Rollup of 10 pull requests
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/linked_list.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/int_macros.rs
  src/librustc_builtin_macros/deriving/debug.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_typeck/astconv.rs
  src/test/rustdoc/auxiliary/issue-27362-aux.rs
  src/test/rustdoc/issue-27362.rs
  src/test/ui/borrowck/move-error-in-promoted-2.rs
  src/test/ui/borrowck/move-error-in-promoted-2.stderr
  src/test/ui/borrowck/move-error-in-promoted.rs
  src/test/ui/borrowck/move-error-in-promoted.stderr
  src/test/ui/check-static-values-constraints.stderr
  src/test/ui/const-suggest-feature.rs
  src/test/ui/const-suggest-feature.stderr
  src/test/ui/consts/const-eval/assign-to-static-within-other-static-2.stderr
  src/test/ui/consts/const-eval/mod-static-with-const-fn.stderr
  src/test/ui/consts/const_let_assign3.stderr
  src/test/ui/consts/projection_qualif.stock.stderr
  src/test/ui/consts/static_mut_containing_mut_ref2.stock.stderr
  src/test/ui/error-codes/E0010-teach.stderr
  src/test/ui/error-codes/E0010.stderr
  src/test/ui/error-codes/E0017.stderr
  src/test/ui/error-codes/E0388.stderr
  src/test/ui/fully-qualified-type/fully-qualified-type-name3.rs
  src/test/ui/issues/issue-17025.rs
  src/test/ui/issues/issue-7364.stderr
  src/test/ui/static/static-mut-not-constant.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71904 fix typo in function name
  src/librustc_builtin_macros/deriving/debug.rs
Labels: S-waiting-on-bors

#71902 Suggest to add missing feature when using gated const features
  src/librustc_mir/transform/check_consts/ops.rs
  src/test/ui/check-static-values-constraints.stderr
  src/test/ui/const-suggest-feature.rs
  src/test/ui/const-suggest-feature.stderr
  src/test/ui/consts/const-eval/assign-to-static-within-other-static-2.stderr
  src/test/ui/consts/const-eval/mod-static-with-const-fn.stderr
  src/test/ui/consts/const_let_assign3.stderr
  src/test/ui/consts/projection_qualif.stock.stderr
  src/test/ui/consts/static_mut_containing_mut_ref2.stock.stderr
  src/test/ui/error-codes/E0010-teach.stderr
  src/test/ui/error-codes/E0010.stderr
  src/test/ui/error-codes/E0017.stderr
  src/test/ui/error-codes/E0388.stderr
  src/test/ui/issues/issue-7364.stderr
  src/test/ui/static/static-mut-not-constant.stderr
Labels: S-waiting-on-bors

#71892 Update btree_map::VacantEntry::insert docs to actually call insert
  src/liballoc/collections/btree/map.rs
Labels: S-waiting-on-bors

#71891 ¬∃x. ¬y => ∀x. y
  src/librustc_typeck/astconv.rs
Labels: S-waiting-on-bors

#71883 add a missing "at" in a comment
  src/librustc_middle/ty/layout.rs
Labels: S-waiting-on-bors

#71881 Correctly handle UEFI targets as Windows-like when emitting sections for LLVM bitcode
  src/librustc_codegen_llvm/back/write.rs
Labels: S-waiting-on-bors

#71878 Add remove_current_as_list to LinkedList's CursorMut
  src/liballoc/collections/linked_list.rs
Labels: S-waiting-on-bors

#71845 Add const examples
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/int_macros.rs
Labels: S-waiting-on-bors

#71711 Updates to some ignored tests
  src/test/rustdoc/auxiliary/issue-27362-aux.rs
  src/test/rustdoc/issue-27362.rs
  src/test/ui/fully-qualified-type/fully-qualified-type-name3.rs
  src/test/ui/issues/issue-17025.rs
Labels: S-waiting-on-bors

#71587 Report cannot move errors in promoted MIR
  src/librustc_mir/borrow_check/mod.rs
  src/test/ui/borrowck/move-error-in-promoted-2.rs
  src/test/ui/borrowck/move-error-in-promoted-2.stderr
  src/test/ui/borrowck/move-error-in-promoted.rs
  src/test/ui/borrowck/move-error-in-promoted.stderr
Labels: S-waiting-on-bors

#71846 resolve: Relax fresh binding disambiguation slightly to fix regression
  src/librustc_resolve/late.rs
  src/test/ui/binding/ambiguity-item.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#71916 Rollup of 4 pull requests
  src/bootstrap/test.rs
  src/bootstrap/toolstate.rs
  src/doc/rustc/src/codegen-options/index.md
  src/librustc_codegen_llvm/allocator.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/librustc_session/session.rs
  src/librustc_typeck/check/mod.rs
  src/test/codegen/force-unwind-tables.rs
  src/test/compile-fail/unwind-tables-panic-required.rs
  src/test/compile-fail/unwind-tables-target-required.rs
  src/test/ui/issues/issue-43162.stderr
  src/test/ui/typeck/issue-67971.rs
  src/test/ui/typeck/issue-67971.stderr
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors, merged-by-bors

#71897 Improve docs for embed-bitcode and linker-plugin-lto
  src/doc/rustc/src/codegen-options/index.md
Labels: S-waiting-on-bors

#71894 Suggest removing semicolon in last expression only if it's type is known
  src/librustc_typeck/check/mod.rs
  src/test/ui/issues/issue-43162.stderr
  src/test/ui/typeck/issue-67971.rs
  src/test/ui/typeck/issue-67971.stderr
Labels: S-waiting-on-bors

#71830 Remove clippy from some leftover lists of "possibly failing" tools
  src/bootstrap/test.rs
  src/bootstrap/toolstate.rs
  src/tools/publish_toolstate.py
Labels: S-waiting-on-bors

#69984 Add Option to Force Unwind Tables
  src/doc/rustc/src/codegen-options/index.md
  src/librustc_codegen_llvm/allocator.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/librustc_session/session.rs
  src/test/codegen/force-unwind-tables.rs
  src/test/compile-fail/unwind-tables-panic-required.rs
  src/test/compile-fail/unwind-tables-target-required.rs
Labels: S-waiting-on-bors, T-compiler, disposition-merge, finished-final-comment-period, relnotes

#69464 perf: Unify the undo log of all snapshot types
  Cargo.lock
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/snapshot_map/mod.rs
  src/librustc_infer/infer/combine.rs
  src/librustc_infer/infer/equate.rs
  src/librustc_infer/infer/error_reporting/need_type_info.rs
  src/librustc_infer/infer/freshen.rs
  src/librustc_infer/infer/fudge.rs
  src/librustc_infer/infer/lattice.rs
  src/librustc_infer/infer/mod.rs
  src/librustc_infer/infer/nll_relate/mod.rs
  src/librustc_infer/infer/outlives/obligations.rs
  src/librustc_infer/infer/region_constraints/leak_check.rs
  src/librustc_infer/infer/region_constraints/mod.rs
  src/librustc_infer/infer/resolve.rs
  src/librustc_infer/infer/sub.rs
  src/librustc_infer/infer/type_variable.rs
  src/librustc_infer/infer/undo_log.rs
  src/librustc_infer/traits/mod.rs
  src/librustc_infer/traits/project.rs
  src/librustc_middle/infer/unify_key.rs
  src/librustc_trait_selection/traits/auto_trait.rs
  src/librustc_trait_selection/traits/fulfill.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/select.rs
Labels: S-waiting-on-bors, merged-by-bors, relnotes, relnotes-perf

#71949 Rollup of 6 pull requests
  RELEASES.md
  src/bootstrap/flags.rs
  src/liballoc/benches/btree/map.rs
  src/liballoc/collections/btree/map.rs
  src/libstd/sys/unix/fs.rs
  src/libstd/sys/unix/mutex.rs
  src/libstd/sys/unix/rwlock.rs
  src/test/ui/deriving/deriving-hash.rs
  src/test/ui/issues/issue-16530.rs
Labels: S-waiting-on-bors, merged-by-bors

#71921 explain the types used in the open64 call
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#71914 Backport 1.43.1 release notes to master
  RELEASES.md
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#71905 Add command aliases from Cargo to x.py commands
  src/bootstrap/flags.rs
Labels: S-waiting-on-bors

#71889 Explain our RwLock implementation
  src/libstd/sys/unix/mutex.rs
  src/libstd/sys/unix/rwlock.rs
Labels: S-waiting-on-bors

#71727 SipHasher with keys initialized to 0 should just use new()
  src/test/ui/deriving/deriving-hash.rs
  src/test/ui/issues/issue-16530.rs
Labels: S-waiting-on-bors

#71510 Btreemap iter intertwined
  src/liballoc/benches/btree/map.rs
  src/liballoc/collections/btree/map.rs
Labels: S-waiting-on-bors

#71951 Rollup of 7 pull requests
  Cargo.lock
  src/bootstrap/bootstrap.py
  src/libcore/array/mod.rs
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_interface/tests.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/nll.rs
  src/librustc_mir/borrow_check/type_check/liveness/mod.rs
  src/librustc_mir/borrow_check/type_check/liveness/trace.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/rustc_peek.rs
  src/librustc_session/options.rs
  src/librustc_typeck/check/demand.rs
  src/libstd/Cargo.toml
  src/libstd/sys/hermit/thread.rs
  src/libunwind/build.rs
  src/test/codegen/unchecked-float-casts.rs
  src/test/ui/eprint-on-tls-drop.rs
  src/test/ui/issues/issue-15487.rs
  src/test/ui/issues/issue-17546.rs
  src/test/ui/issues/issue-17546.stderr
  src/test/ui/lint/use_suggestion_json.rs
  src/test/ui/lint/use_suggestion_json.stderr
  src/test/ui/numbers-arithmetic/saturating-float-casts.rs
  src/test/ui/proc-macro/crt-static.rs
  src/test/ui/resolve/issue-16058.rs
  src/test/ui/resolve/issue-16058.stderr
  src/test/ui/test-panic-abort-nocapture.rs
  src/test/ui/test-panic-abort-nocapture.run.stderr
  src/test/ui/test-panic-abort.rs
  src/test/ui/test-panic-abort.run.stdout
Labels: S-waiting-on-bors, merged-by-bors

#71944 Add comment for `Ord` implementation for array
  src/libcore/array/mod.rs
Labels: S-waiting-on-bors

#71937 Ignore SGX on a few ui tests
  src/test/ui/eprint-on-tls-drop.rs
  src/test/ui/issues/issue-15487.rs
  src/test/ui/issues/issue-17546.rs
  src/test/ui/issues/issue-17546.stderr
  src/test/ui/lint/use_suggestion_json.rs
  src/test/ui/lint/use_suggestion_json.stderr
  src/test/ui/proc-macro/crt-static.rs
  src/test/ui/resolve/issue-16058.rs
  src/test/ui/resolve/issue-16058.stderr
  src/test/ui/test-panic-abort-nocapture.rs
  src/test/ui/test-panic-abort-nocapture.run.stderr
  src/test/ui/test-panic-abort.rs
  src/test/ui/test-panic-abort.run.stdout
Labels: S-waiting-on-bors

#71929 Use -fvisibility=hidden for libunwind
  src/libunwind/build.rs
Labels: S-waiting-on-bors

#71893 Use the `impls` module to import pre-existing dataflow analyses
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/nll.rs
  src/librustc_mir/borrow_check/type_check/liveness/mod.rs
  src/librustc_mir/borrow_check/type_check/liveness/trace.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/dataflow/mod.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/rustc_peek.rs
Labels: S-waiting-on-bors

#71819 x.py: Give a more helpful error message if curl isn't installed
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#71591 use new interface to create threads on HermitCore
  Cargo.lock
  src/libstd/Cargo.toml
  src/libstd/sys/hermit/thread.rs
Labels: S-waiting-on-bors

#71269 Define UB in float-to-int casts to saturate
  src/librustc_codegen_ssa/mir/rvalue.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/librustc_typeck/check/demand.rs
  src/test/codegen/unchecked-float-casts.rs
  src/test/ui/numbers-arithmetic/saturating-float-casts.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#71958 Rollup of 5 pull requests
  src/bootstrap/toolstate.rs
  src/ci/docker/x86_64-gnu-tools/checktools.sh
  src/librustc_ast_passes/ast_validation.rs
  src/librustc_hir/hir.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/ty/diagnostics.rs
  src/librustc_middle/ty/error.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/traits.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/op.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/test/rustdoc/const-generics/add-impl.rs
  src/test/rustdoc/duplicate_impls/issue-33054.rs
  src/test/rustdoc/issue-21474.rs
  src/test/rustdoc/issue-45584.rs
  src/test/rustdoc/issue-55321.rs
  src/test/rustdoc/negative-impl-sidebar.rs
  src/test/rustdoc/struct-implementations-title.rs
  src/test/rustdoc/synthetic_auto/manual.rs
  src/test/rustdoc/typedef.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/generic-associated-types/construct_with_other_type.stderr
  src/test/ui/generic-associated-types/missing-bounds.fixed
  src/test/ui/generic-associated-types/missing-bounds.rs
  src/test/ui/generic-associated-types/missing-bounds.stderr
  src/test/ui/issues/issue-20005.stderr
  src/test/ui/issues/issue-24204.stderr
  src/test/ui/issues/issue-6738.stderr
  src/test/ui/type/type-check/missing_trait_impl.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71950 Miri validation error handling cleanup
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/traits.rs
  src/librustc_mir/interpret/validity.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
Labels: S-waiting-on-bors

#71918 Rename methods section
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/test/rustdoc/const-generics/add-impl.rs
  src/test/rustdoc/duplicate_impls/issue-33054.rs
  src/test/rustdoc/issue-21474.rs
  src/test/rustdoc/issue-45584.rs
  src/test/rustdoc/issue-55321.rs
  src/test/rustdoc/negative-impl-sidebar.rs
  src/test/rustdoc/struct-implementations-title.rs
  src/test/rustdoc/synthetic_auto/manual.rs
  src/test/rustdoc/typedef.rs
Labels: S-waiting-on-bors

#71888 refactor suggest_traits_to_import
  src/librustc_typeck/check/method/suggest.rs
Labels: S-waiting-on-bors

#71731 Turn off rustc-dev-guide toolstate for now
  src/bootstrap/toolstate.rs
  src/ci/docker/x86_64-gnu-tools/checktools.sh
Labels: S-waiting-on-bors

#70908 Provide suggestions for type parameters missing bounds for associated types
  src/librustc_ast_passes/ast_validation.rs
  src/librustc_hir/hir.rs
  src/librustc_middle/ty/diagnostics.rs
  src/librustc_middle/ty/error.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/op.rs
  src/test/ui/generic-associated-types/construct_with_other_type.stderr
  src/test/ui/generic-associated-types/missing-bounds.fixed
  src/test/ui/generic-associated-types/missing-bounds.rs
  src/test/ui/generic-associated-types/missing-bounds.stderr
  src/test/ui/issues/issue-20005.stderr
  src/test/ui/issues/issue-24204.stderr
  src/test/ui/issues/issue-6738.stderr
  src/test/ui/type/type-check/missing_trait_impl.stderr
Labels: S-waiting-on-bors

#55617 Prevent compiler stack overflow for deeply recursive code
  Cargo.lock
  src/librustc_ast_lowering/expr.rs
  src/librustc_ast_lowering/pat.rs
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/stack.rs
  src/librustc_interface/util.rs
  src/librustc_middle/ty/inhabitedness/mod.rs
  src/librustc_middle/ty/query/plumbing.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/query/normalize.rs
  src/librustc_trait_selection/traits/select.rs
  src/librustc_traits/dropck_outlives.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#71649 Ensure that `./x.py doc --stage 0 src/libstd` works via CI
  src/ci/docker/mingw-check/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#71985 Rollup of 6 pull requests
  src/liballoc/fmt.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_typeck/check/closure.rs
  src/libstd/sys/unix/ext/net.rs
  src/libstd/sys/unix/ext/raw.rs
  src/test/auxiliary/rust_test_helpers.c
  src/test/codegen/ffi-out-of-bounds-loads.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/enum/issue-67945-1.rs
  src/test/ui/enum/issue-67945-1.stderr
  src/test/ui/enum/issue-67945-2.rs
  src/test/ui/enum/issue-67945-2.stderr
  src/test/ui/lifetimes/issue-34979.rs
  src/test/ui/lifetimes/issue-34979.stderr
Labels: S-waiting-on-bors, merged-by-bors

#71980 Allow a few warnings.
  src/libstd/sys/unix/ext/net.rs
  src/libstd/sys/unix/ext/raw.rs
Labels: S-waiting-on-bors

#71972 use hex for pointers in Miri error messages
  src/librustc_mir/interpret/validity.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
Labels: S-waiting-on-bors

#71962 Grammar
  src/liballoc/fmt.rs
Labels: S-waiting-on-bors

#71959 tests: Fix warnings in `rust_test_helpers.c`
  src/test/auxiliary/rust_test_helpers.c
Labels: S-waiting-on-bors

#71952 Add some regression tests
  src/test/codegen/ffi-out-of-bounds-loads.rs
  src/test/ui/enum/issue-67945-1.rs
  src/test/ui/enum/issue-67945-1.stderr
  src/test/ui/enum/issue-67945-2.rs
  src/test/ui/enum/issue-67945-2.stderr
  src/test/ui/lifetimes/issue-34979.rs
  src/test/ui/lifetimes/issue-34979.stderr
Labels: S-waiting-on-bors

#71938 Use trait_object_dummy_self instead of err
  src/librustc_typeck/check/closure.rs
Labels: S-waiting-on-bors

#71995 [CI] Use the latest Python available on Windows
  src/ci/scripts/install-msys2-packages.sh
Labels: S-waiting-on-bors, merged-by-bors

#71960 Fix E0284 to not use incorrect wording
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/test/ui/associated-types/associated-types-overridden-binding.stderr
  src/test/ui/issues/issue-12028.stderr
  src/test/ui/issues/issue-69455.rs
  src/test/ui/issues/issue-69455.stderr
  src/test/ui/issues/issue-69683.rs
  src/test/ui/issues/issue-69683.stderr
  src/test/ui/issues/issue-71584.rs
  src/test/ui/issues/issue-71584.stderr
Labels: S-waiting-on-bors, beta-nominated

#71903 reword "possible candidate" import suggestion
  src/librustc_resolve/diagnostics.rs
  src/librustc_resolve/late/diagnostics.rs
  src/test/ui/class-missing-self.stderr
  src/test/ui/crate-in-paths.stderr
  src/test/ui/did_you_mean/issue-56028-there-is-an-enum-variant.stderr
  src/test/ui/glob-resolve1.stderr
  src/test/ui/hygiene/globs.stderr
  src/test/ui/impl-trait/universal_wrong_bounds.stderr
  src/test/ui/issues/issue-17546.stderr
  src/test/ui/issues/issue-35675.stderr
  src/test/ui/issues/issue-37534.stderr
  src/test/ui/issues/issue-38293.stderr
  src/test/ui/issues/issue-42944.stderr
  src/test/ui/issues/issue-4366-2.stderr
  src/test/ui/issues/issue-4366.stderr
  src/test/ui/issues/issue-50599.stderr
  src/test/ui/lexical-scopes.stderr
  src/test/ui/lint/use_suggestion_json.stderr
  src/test/ui/macros/macro-outer-attributes.stderr
  src/test/ui/namespace/namespace-mix.stderr
  src/test/ui/no-implicit-prelude-nested.stderr
  src/test/ui/no-implicit-prelude.stderr
  src/test/ui/parser/circular_modules_main.stderr
  src/test/ui/privacy/privacy-ns1.stderr
  src/test/ui/privacy/privacy-ns2.stderr
  src/test/ui/proc-macro/attributes-on-modules-fail.stderr
  src/test/ui/proc-macro/generate-mod.stderr
  src/test/ui/proc-macro/mixed-site-span.stderr
  src/test/ui/resolve/enums-are-namespaced-xc.stderr
  src/test/ui/resolve/issue-16058.stderr
  src/test/ui/resolve/issue-17518.stderr
  src/test/ui/resolve/issue-21221-1.stderr
  src/test/ui/resolve/issue-21221-2.stderr
  src/test/ui/resolve/issue-21221-3.stderr
  src/test/ui/resolve/issue-21221-4.stderr
  src/test/ui/resolve/issue-3907.stderr
  src/test/ui/resolve/privacy-enum-ctor.stderr
  src/test/ui/resolve/privacy-struct-ctor.stderr
  src/test/ui/resolve/resolve-primitive-fallback.stderr
  src/test/ui/resolve/use_suggestion_placement.stderr
  src/test/ui/rust-2018/issue-52202-use-suggestions.stderr
  src/test/ui/self/self_type_keyword.stderr
  src/test/ui/span/issue-35987.stderr
  src/test/ui/suggestions/no-extern-crate-in-type.stderr
  src/test/ui/suggestions/raw-name-use-suggestion.stderr
  src/test/ui/use/use-super-global-path.stderr
Labels: S-waiting-on-bors

#71783 Detect errors caused by `async` block in 2015 edition
  src/librustc_parse/parser/expr.rs
  src/librustc_parse/parser/item.rs
  src/librustc_parse/parser/stmt.rs
  src/librustc_resolve/late/diagnostics.rs
  src/test/ui/async-await/edition-deny-async-fns-2015.stderr
  src/test/ui/editions/async-block-2015.rs
  src/test/ui/editions/async-block-2015.stderr
Labels: S-waiting-on-review

#71598 improve Drop documentation
  src/libcore/ops/drop.rs
Labels: S-waiting-on-bors

#70733 Add Arc::{incr,decr}_strong_count
  src/liballoc/sync.rs
  src/liballoc/task.rs
Labels: S-waiting-on-review

#72010 Rollup of 6 pull requests
  .mailmap
  src/librustc_attr/build.rs
  src/librustc_attr/builtin.rs
  src/librustc_hir/hir.rs
  src/librustc_middle/hir/map/mod.rs
  src/librustc_mir/borrow_check/def_use.rs
  src/librustc_mir/borrow_check/diagnostics/find_use.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/liveness/local_use_map.rs
  src/librustc_mir/borrow_check/type_check/liveness/polonius.rs
  src/librustc_mir/dataflow/impls/liveness.rs
  src/librustc_mir/transform/check_consts/mod.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir/util/liveness.rs
  src/librustc_mir/util/mod.rs
  src/librustc_passes/check_const.rs
  src/test/ui/const-generics/trait-const-args.rs
  src/test/ui/lint/lint-exceeding-bitshifts.noopt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt_with_overflow_checks.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.rs
Labels: S-waiting-on-bors, merged-by-bors

#72007 Fix some tests failing in `--pass check` mode
  src/test/ui/lint/lint-exceeding-bitshifts.noopt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.opt_with_overflow_checks.stderr
  src/test/ui/lint/lint-exceeding-bitshifts.rs
Labels: S-waiting-on-bors

#72008 Add const-generics test
  src/test/ui/const-generics/trait-const-args.rs
Labels: S-waiting-on-bors

#72001 Adjust cfg(version) to lang team decision
  src/librustc_attr/build.rs
  src/librustc_attr/builtin.rs
Labels: S-waiting-on-bors

#71999 Add myself to mailmap.
  .mailmap
Labels: S-waiting-on-bors

#71993 Remove old `util/liveness.rs` module
  src/librustc_mir/borrow_check/def_use.rs
  src/librustc_mir/borrow_check/diagnostics/find_use.rs
  src/librustc_mir/borrow_check/mod.rs
  src/librustc_mir/borrow_check/type_check/liveness/local_use_map.rs
  src/librustc_mir/borrow_check/type_check/liveness/polonius.rs
  src/librustc_mir/dataflow/impls/liveness.rs
  src/librustc_mir/util/liveness.rs
  src/librustc_mir/util/mod.rs
Labels: S-waiting-on-bors

#71989 Use a single enum for the kind of a const context
  src/librustc_hir/hir.rs
  src/librustc_middle/hir/map/mod.rs
  src/librustc_mir/transform/check_consts/mod.rs
  src/librustc_mir/transform/check_consts/ops.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_passes/check_const.rs
Labels: S-waiting-on-bors

#72021 Rollup of 6 pull requests
  src/librustc_ast/lib.rs
  src/librustc_attr/lib.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_mir_build/hair/pattern/check_match.rs
  src/librustc_span/lib.rs
  src/librustc_target/lib.rs
  src/librustc_target/spec/aarch64_apple_ios.rs
  src/librustc_target/spec/aarch64_apple_tvos.rs
  src/librustc_target/spec/mod.rs
  src/librustdoc/core.rs
  src/librustdoc/test.rs
  src/test/ui/unsized-locals/issue-30276-feature-flagged.rs
  src/test/ui/unsized-locals/issue-30276-feature-flagged.stderr
  src/test/ui/unsized-locals/issue-30276.rs
  src/test/ui/unsized-locals/issue-30276.stderr
Labels: S-waiting-on-bors, merged-by-bors

#72017 Work around ICEs during cross-compilation for target, ast, & attr
  src/librustc_ast/lib.rs
  src/librustc_attr/lib.rs
  src/librustc_target/lib.rs
Labels: S-waiting-on-bors

#72003 allow wasm target for rustc-ap-rustc_span
  src/librustc_span/lib.rs
Labels: S-waiting-on-bors

#71975 Reduce `TypedArena` creations in `check_match`.
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_mir_build/hair/pattern/check_match.rs
Labels: S-waiting-on-bors

#71970 Improve bitcode generation for Apple platforms
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_target/spec/aarch64_apple_ios.rs
  src/librustc_target/spec/aarch64_apple_tvos.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#71710 Test for zero-sized function items not ICEing
  src/test/ui/unsized-locals/issue-30276-feature-flagged.rs
  src/test/ui/unsized-locals/issue-30276-feature-flagged.stderr
  src/test/ui/unsized-locals/issue-30276.rs
  src/test/ui/unsized-locals/issue-30276.stderr
Labels: A-dst, F-unsized_locals, S-waiting-on-bors

#71581 Unify lints handling in rustdoc
  src/librustdoc/core.rs
  src/librustdoc/test.rs
Labels: S-waiting-on-bors

#71418 Renamed "undef" -> "uninit"
  src/librustc_middle/mir/interpret/allocation.rs
  src/librustc_middle/mir/interpret/error.rs
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/interpret/value.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/interpret/eval_context.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/util/pretty.rs
  src/test/mir-opt/const_prop/control-flow-simplification/rustc.hello.ConstProp.diff
  src/test/mir-opt/inline/inline-into-box-place/32bit/rustc.main.Inline.diff
  src/test/mir-opt/inline/inline-into-box-place/64bit/rustc.main.Inline.diff
  src/test/mir-opt/no-drop-for-inactive-variant/rustc.unwrap.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/no-spurious-drop-after-call/rustc.main.ElaborateDrops.before.mir
  src/test/mir-opt/storage_live_dead_in_statics/rustc.XXX.mir_map.0.mir
  src/test/mir-opt/uninhabited_enum_branching/rustc.main.SimplifyCfg-after-uninhabited-enum-branching.after.mir
  src/test/mir-opt/uninhabited_enum_branching/rustc.main.UninhabitedEnumBranching.diff
  src/test/ui-fulldeps/uninit_mask.rs
Labels: S-waiting-on-bors, merged-by-bors

#72036 Rollup of 8 pull requests
  src/doc/rustdoc/src/passes.md
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/lib.rs
  src/libcore/future/mod.rs
  src/libcore/future/pending.rs
  src/libcore/future/ready.rs
  src/librustc_errors/registry.rs
  src/librustc_infer/infer/canonical/canonicalizer.rs
  src/librustc_infer/infer/canonical/mod.rs
  src/librustc_infer/infer/canonical/query_response.rs
  src/librustc_infer/infer/canonical/substitute.rs
  src/librustc_middle/infer/canonical.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mod.rs
  src/librustc_mir/borrow_check/diagnostics/move_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/framework/tests.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/add_retag.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir/util/patch.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_mir_build/build/expr/as_place.rs
  src/librustc_mir_build/build/expr/as_rvalue.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/build/matches/mod.rs
  src/librustc_mir_build/build/misc.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/build/scope.rs
  src/librustc_passes/dead.rs
  src/librustc_trait_selection/traits/query/type_op/mod.rs
  src/libstd/io/mod.rs
  src/test/ui/collections-const-new.rs
  src/test/ui/lint/dead-code/lint-dead-code-3.stderr
  src/test/ui/lint/dead-code/lint-dead-code-6.rs
  src/test/ui/lint/dead-code/lint-dead-code-6.stderr
Labels: S-waiting-on-bors, merged-by-bors

#72031 Better documentation for io::Read::read() return value
  src/libstd/io/mod.rs
Labels: S-waiting-on-bors

#72018 Fix canonicalization links
  src/librustc_infer/infer/canonical/canonicalizer.rs
  src/librustc_infer/infer/canonical/mod.rs
  src/librustc_infer/infer/canonical/query_response.rs
  src/librustc_infer/infer/canonical/substitute.rs
  src/librustc_middle/infer/canonical.rs
  src/librustc_trait_selection/traits/query/type_op/mod.rs
Labels: S-waiting-on-bors

#71981 Fix `strip-priv-imports` pass name in the rustdoc documentation
  src/doc/rustdoc/src/passes.md
Labels: S-waiting-on-bors

#71947 Dead-code pass highlights too much of impl functions
  src/librustc_passes/dead.rs
  src/test/ui/lint/dead-code/lint-dead-code-3.stderr
  src/test/ui/lint/dead-code/lint-dead-code-6.rs
  src/test/ui/lint/dead-code/lint-dead-code-6.stderr
Labels: S-waiting-on-bors

#71942 Shrink `LocalDecl`
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/visit.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mod.rs
  src/librustc_mir/borrow_check/diagnostics/move_errors.rs
  src/librustc_mir/borrow_check/diagnostics/mutability_errors.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/dataflow/framework/tests.rs
  src/librustc_mir/shim.rs
  src/librustc_mir/transform/add_retag.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/check_unsafety.rs
  src/librustc_mir/transform/generator.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_mir/util/patch.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_mir_build/build/expr/as_place.rs
  src/librustc_mir_build/build/expr/as_rvalue.rs
  src/librustc_mir_build/build/expr/as_temp.rs
  src/librustc_mir_build/build/expr/into.rs
  src/librustc_mir_build/build/matches/mod.rs
  src/librustc_mir_build/build/misc.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_mir_build/build/scope.rs
Labels: S-waiting-on-bors

#71890 Simplify the error Registry methods a little
  src/librustc_errors/registry.rs
Labels: S-waiting-on-bors

#71839 Make BTreeMap::new and BTreeSet::new const
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/set.rs
  src/liballoc/lib.rs
  src/test/ui/collections-const-new.rs
Labels: S-waiting-on-bors

#70834 Add core::future::{pending,ready}
  src/libcore/future/mod.rs
  src/libcore/future/pending.rs
  src/libcore/future/ready.rs
Labels: S-waiting-on-bors, T-libs

#71994 x.py: allow configuring the build directory
  config.toml.example
  src/bootstrap/bootstrap.py
  src/bootstrap/config.rs
Labels: S-waiting-on-bors, merged-by-bors

#71508 Simplify the `tcx.alloc_map` API
  src/librustc_codegen_llvm/common.rs
  src/librustc_codegen_ssa/mir/operand.rs
  src/librustc_middle/ich/impls_ty.rs
  src/librustc_middle/lib.rs
  src/librustc_middle/mir/interpret/mod.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/ty/context.rs
  src/librustc_middle/ty/print/pretty.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/interpret/intern.rs
  src/librustc_mir/interpret/memory.rs
  src/librustc_mir/interpret/operand.rs
  src/librustc_mir/interpret/place.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/util/pretty.rs
  src/librustc_mir_build/hair/cx/expr.rs
  src/librustc_mir_build/hair/pattern/_match.rs
Labels: S-waiting-on-bors
