Repository rust-lang/rust, pull requests merged in 2020-11, with the labels that each got.

#78147 Assert that locals have storage when used
  compiler/rustc_mir/src/transform/validate.rs
  src/test/codegen/avr/avr-func-addrspace.rs
  src/test/run-make-fulldeps/min-global-align/min_global_align.rs
Labels: S-waiting-on-bors, merged-by-bors

#78420 Suggest calling associated `fn` inside `trait`s
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  src/test/ui/resolve/associated-fn-called-as-fn.rs
  src/test/ui/resolve/associated-fn-called-as-fn.stderr
  src/test/ui/resolve/issue-14254.stderr
  src/test/ui/resolve/issue-2356.stderr
  src/test/ui/resolve/resolve-assoc-suggestions.stderr
  src/test/ui/resolve/resolve-speculative-adjustment.stderr
  src/test/ui/suggestions/assoc-type-in-method-return.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-compiler, merged-by-bors

#78531 rustc_llvm: unwrap LLVMMetadataRef before casting
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
Labels: A-LLVM, S-waiting-on-bors, T-compiler, merged-by-bors

#78623 Rollup of 6 pull requests
  compiler/rustc_expand/src/mbe/transcribe.rs
  library/alloc/src/collections/binary_heap.rs
  library/alloc/src/macros.rs
  library/core/src/fmt/num.rs
  library/core/src/hash/sip.rs
  library/core/src/macros/mod.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/str/error.rs
  library/core/src/str/iter.rs
  library/core/src/str/mod.rs
  library/core/src/sync/atomic.rs
  library/std/src/process.rs
  library/std/src/sys/unix/thread.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#78621 Inline Default::default() for atomics
  library/core/src/sync/atomic.rs
Labels: S-waiting-on-bors

#78603 expand: Tweak a comment in implementation of `macro_rules`
  compiler/rustc_expand/src/mbe/transcribe.rs
Labels: S-waiting-on-bors

#78602 fix various aliasing issues in the standard library
  library/alloc/src/collections/binary_heap.rs
  library/core/src/fmt/num.rs
  library/core/src/hash/sip.rs
  library/core/src/mem/maybe_uninit.rs
  library/std/src/sys/unix/thread.rs
Labels: S-waiting-on-bors

#78599 Add note to process::arg[s] that args shouldn't be escaped or quoted
  library/std/src/process.rs
Labels: S-waiting-on-bors

#78596 Fix doc links to std::fmt
  library/alloc/src/macros.rs
  library/core/src/macros/mod.rs
Labels: S-waiting-on-bors

#78073 Add #[inline] to some functions in core::str.
  library/core/src/str/error.rs
  library/core/src/str/iter.rs
  library/core/src/str/mod.rs
Labels: S-waiting-on-bors, T-libs

#78553 Fix #78549
  compiler/rustc_mir_build/src/thir/pattern/_match.rs
  src/test/ui/issues/issue-30240.rs
  src/test/ui/issues/issue-30240.stderr
  src/test/ui/pattern/usefulness/issue-78549-ref-pat-and-str.rs
Labels: A-exhaustiveness-checking, S-waiting-on-bors, T-compiler, merged-by-bors

#75534 Implement rustc side of report-future-incompat
  Cargo.lock
  compiler/rustc_ast_lowering/src/path.rs
  compiler/rustc_errors/Cargo.toml
  compiler/rustc_errors/src/annotate_snippet_emitter_writer.rs
  compiler/rustc_errors/src/diagnostic.rs
  compiler/rustc_errors/src/diagnostic_builder.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_errors/src/json.rs
  compiler/rustc_errors/src/lib.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_lint/src/array_into_iter.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint_defs/Cargo.toml
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_lint_defs/src/lib.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_session/Cargo.toml
  compiler/rustc_session/src/lib.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
  src/test/ui/iterators/into-iter-on-arrays-lint.fixed
  src/test/ui/iterators/into-iter-on-arrays-lint.rs
  src/test/ui/iterators/into-iter-on-arrays-lint.stderr
  src/tools/clippy/clippy_lints/src/utils/paths.rs
  src/tools/compiletest/src/json.rs
  src/tools/compiletest/src/runtest.rs
Labels: C-future-compatibility, S-waiting-on-bors, T-compiler, merged-by-bors

#78605 Implement -Z relax-elf-relocations=yes|no
  compiler/rustc_codegen_llvm/src/back/write.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors, merged-by-bors

#78645 Add delay_span_bug to no longer ICE
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/issues/issue-78622.rs
  src/test/ui/issues/issue-78622.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#78592 Add option to customize the nll-facts' folder location
  compiler/rustc_mir/src/borrow_check/nll.rs
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors, merged-by-bors

#75020 Avoid complex diagnostics in snippets which contain newlines
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  src/test/ui/async-await/issue-70935-complex-spans.rs
  src/test/ui/async-await/issue-70935-complex-spans.stderr
  src/test/ui/async-await/issues/issue-65436-raw-ptr-not-send.stderr
Labels: S-waiting-on-bors, merged-by-bors

#78661 Rollup of 5 pull requests
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_interface/src/passes.rs
  library/core/src/num/f32.rs
  library/core/src/num/f64.rs
  library/core/src/ops/bit.rs
  library/core/src/str/mod.rs
  library/core/src/sync/atomic.rs
  src/test/ui/ast-json/ast-json-ice.rs
  src/test/ui/ast-json/ast-json-noexpand-output.stdout
  src/test/ui/ast-json/ast-json-output.stdout
  src/test/ui/ast-json/issue-78398-foreign-ice.rs
  src/test/ui/ast-json/issue-78398-foreign-ice.stdout
  src/test/ui/ast-json/issue-78510-assoc-ice.rs
  src/test/ui/ast-json/issue-78510-assoc-ice.stderr
  src/test/ui/ast-json/issue-78510-assoc-ice.stdout
Labels: S-waiting-on-bors, merged-by-bors, rollup

#78637 Add fetch_update methods to AtomicBool and AtomicPtr
  library/core/src/sync/atomic.rs
Labels: S-waiting-on-bors, T-libs

#78627 Point out that total_cmp is no strict superset of partial comparison
  library/core/src/num/f32.rs
  library/core/src/num/f64.rs
Labels: S-waiting-on-bors

#78620 Trivial fixes to bitwise operator documentation
  library/core/src/ops/bit.rs
Labels: S-waiting-on-bors, T-doc

#78610 Do not remove tokens before AST json serialization
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_interface/src/passes.rs
  src/test/ui/ast-json/ast-json-ice.rs
  src/test/ui/ast-json/ast-json-noexpand-output.stdout
  src/test/ui/ast-json/ast-json-output.stdout
  src/test/ui/ast-json/issue-78398-foreign-ice.rs
  src/test/ui/ast-json/issue-78398-foreign-ice.stdout
  src/test/ui/ast-json/issue-78510-assoc-ice.rs
  src/test/ui/ast-json/issue-78510-assoc-ice.stderr
  src/test/ui/ast-json/issue-78510-assoc-ice.stdout
Labels: S-waiting-on-bors

#78606 Clarify handling of final line ending in str::lines()
  library/core/src/str/mod.rs
Labels: S-waiting-on-bors

#78667 Try running lldb_batchmode.py with PYTHONUNBUFFERED
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, merged-by-bors

#78607 Transform post order walk to an iterative approach
  compiler/rustc_data_structures/src/graph/iterate/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#77271 Expand `NtExpr` tokens only in key-value attributes
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_expand/src/mbe/transcribe.rs
  compiler/rustc_expand/src/mut_visit/tests.rs
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/def_collector.rs
  library/core/src/sync/atomic.rs
  src/test/ui/attributes/auxiliary/key-value-expansion.rs
  src/test/ui/attributes/key-value-expansion.rs
  src/test/ui/attributes/key-value-expansion.stderr
  src/test/ui/attributes/nonterminal-expansion.rs
  src/test/ui/attributes/nonterminal-expansion.stderr
  src/test/ui/conditional-compilation/cfg-attr-syntax-validation.rs
  src/test/ui/conditional-compilation/cfg-attr-syntax-validation.stderr
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/nonterminal-expansion.rs
  src/test/ui/proc-macro/nonterminal-expansion.stdout
Labels: A-attributes, S-waiting-on-bors, merged-by-bors, relnotes

#78448 foreign_modules query hash table lookups
  compiler/rustc_codegen_llvm/src/attributes.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_passes/src/diagnostic_items.rs
Labels: I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#78697 Rollup of 8 pull requests
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_lint/src/redundant_semicolon.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_target/src/spec/mipsel_unknown_none.rs
  compiler/rustc_target/src/spec/mod.rs
  library/core/src/intrinsics.rs
  src/doc/rustc/src/platform-support.md
  src/doc/unstable-book/src/compiler-flags/img/llvm-cov-show-01.png
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
  src/librustdoc/passes/unindent_comments.rs
  src/librustdoc/passes/unindent_comments/tests.rs
  src/test/rustdoc/unindent.md
  src/test/rustdoc/unindent.rs
  src/test/ui/lint/issue-78660-cap-lints-future-compat.rs
  src/test/ui/lint/issue-78660-cap-lints-future-compat.stderr
  src/test/ui/macros/empty-trailing-stmt.rs
  src/test/ui/macros/empty-trailing-stmt.stderr
  src/test/ui/meta/auxiliary/env.rs
  src/test/ui/meta/expected-error-correct-rev.a.stderr
  src/test/ui/meta/expected-error-correct-rev.rs
  src/test/ui/meta/revision-bad.rs
  src/test/ui/meta/revision-ok.rs
  src/test/ui/meta/rustc-env.rs
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
Labels: S-waiting-on-bors, merged-by-bors, rollup

#78676 add mipsel-unknown-none target
  compiler/rustc_target/src/spec/mipsel_unknown_none.rs
  compiler/rustc_target/src/spec/mod.rs
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors

#78668 inliner: Remove redundant loop
  compiler/rustc_mir/src/transform/inline.rs
Labels: S-waiting-on-bors

#78664 Fix intrinsic size_of stable link
  library/core/src/intrinsics.rs
Labels: S-waiting-on-bors

#78663 Fix ICE when a future-incompat-report has its command-line level capped
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_middle/src/lint.rs
  src/test/ui/lint/issue-78660-cap-lints-future-compat.rs
  src/test/ui/lint/issue-78660-cap-lints-future-compat.stderr
Labels: A-lint, S-waiting-on-bors, T-compiler

#78616 Document -Zinstrument-coverage
  src/doc/unstable-book/src/compiler-flags/img/llvm-cov-show-01.png
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
Labels: S-waiting-on-bors

#78575 Add a test for compiletest rustc-env & unset-rustc-env directives
  src/test/ui/meta/auxiliary/env.rs
  src/test/ui/meta/expected-error-correct-rev.a.stderr
  src/test/ui/meta/expected-error-correct-rev.rs
  src/test/ui/meta/revision-bad.rs
  src/test/ui/meta/revision-ok.rs
  src/test/ui/meta/rustc-env.rs
Labels: S-waiting-on-bors

#78400 Fix unindent in doc comments
  src/librustdoc/passes/unindent_comments.rs
  src/librustdoc/passes/unindent_comments/tests.rs
  src/test/rustdoc/unindent.md
  src/test/rustdoc/unindent.rs
Labels: S-waiting-on-bors, T-rustdoc

#78376 Treat trailing semicolon as a statement in macro call
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_lint/src/redundant_semicolon.rs
  src/test/ui/macros/empty-trailing-stmt.rs
  src/test/ui/macros/empty-trailing-stmt.stderr
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
Labels: A-proc-macros, S-waiting-on-bors, relnotes

#78489 Minor cleanup around incremental compilation
  compiler/rustc_graphviz/src/lib.rs
  compiler/rustc_incremental/src/assert_module_sources.rs
  compiler/rustc_incremental/src/persist/dirty_clean.rs
  compiler/rustc_incremental/src/persist/fs.rs
  compiler/rustc_incremental/src/persist/save.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#78597 Retagging: do not retag 'raw reborrows'
  compiler/rustc_mir/src/transform/add_retag.rs
Labels: A-mir, S-waiting-on-bors, merged-by-bors

#76931 Properly handle lint spans after MIR inlining
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_span/src/hygiene.rs
  src/test/mir-opt/dest-prop/cycle.main.DestinationPropagation.diff
  src/test/mir-opt/dest-prop/union.main.DestinationPropagation.diff
  src/test/mir-opt/generator_drop_cleanup.main-{closure#0}.generator_drop.0.mir
  src/test/mir-opt/inline/inline_any_operand.bar.Inline.after.mir
  src/test/mir-opt/inline/inline_closure.foo.Inline.after.mir
  src/test/mir-opt/inline/inline_closure_borrows_arg.foo.Inline.after.mir
  src/test/mir-opt/inline/inline_closure_captures.foo.Inline.after.mir
  src/test/mir-opt/inline/inline_compatibility.inlined_no_sanitize.Inline.diff
  src/test/mir-opt/inline/inline_compatibility.inlined_target_feature.Inline.diff
  src/test/mir-opt/inline/inline_into_box_place.main.Inline.32bit.diff
  src/test/mir-opt/inline/inline_into_box_place.main.Inline.64bit.diff
  src/test/mir-opt/inline/inline_retag.bar.Inline.after.mir
  src/test/mir-opt/inline/inline_specialization.main.Inline.diff
  src/test/mir-opt/inline/inline_trait_method_2.test2.Inline.after.mir
  src/test/mir-opt/inline/issue_58867_inline_as_ref_as_mut.a.Inline.after.mir
  src/test/mir-opt/inline/issue_58867_inline_as_ref_as_mut.b.Inline.after.mir
  src/test/mir-opt/inline/issue_58867_inline_as_ref_as_mut.c.Inline.after.mir
  src/test/mir-opt/inline/issue_58867_inline_as_ref_as_mut.d.Inline.after.mir
  src/test/mir-opt/inline/issue_76997_inline_scopes_parenting.main.Inline.after.mir
  src/test/mir-opt/issue_73223.main.PreCodegen.32bit.diff
  src/test/mir-opt/issue_73223.main.PreCodegen.64bit.diff
  src/test/mir-opt/issue_73223.main.SimplifyArmIdentity.32bit.diff
  src/test/mir-opt/issue_73223.main.SimplifyArmIdentity.64bit.diff
  src/test/mir-opt/remove_unneeded_drops.cannot_opt_generic.RemoveUnneededDrops.diff
  src/test/mir-opt/remove_unneeded_drops.dont_opt.RemoveUnneededDrops.diff
  src/test/mir-opt/remove_unneeded_drops.opt.RemoveUnneededDrops.diff
  src/test/mir-opt/remove_unneeded_drops.opt_generic_copy.RemoveUnneededDrops.diff
  src/test/mir-opt/simplify_arm.id_try.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify_arm.id_try.SimplifyBranchSame.diff
  src/test/mir-opt/simplify_try.try_identity.DestinationPropagation.diff
  src/test/mir-opt/simplify_try.try_identity.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify_try.try_identity.SimplifyBranchSame.after.mir
  src/test/mir-opt/simplify_try.try_identity.SimplifyLocals.after.mir
  src/test/ui/const_prop/inline_spans.rs
  src/test/ui/const_prop/inline_spans.stderr
Labels: S-waiting-on-bors, merged-by-bors

#78709 Fix panic in bootstrap for non-workspace path dependencies.
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#78699 Show more error information in lldb_batchmode
  src/etc/lldb_batchmode.py
Labels: S-waiting-on-bors

#78687 Suggest library/std when running all stage 0 tests
  src/bootstrap/test.rs
Labels: A-contributor-roadblock, A-rustbuild, C-enhancement, S-waiting-on-bors

#78659 Corrected suggestion for generic parameters in `function_item_references` lint
  compiler/rustc_mir/src/transform/function_item_references.rs
  src/test/ui/lint/function-item-references.rs
  src/test/ui/lint/function-item-references.stderr
Labels: S-waiting-on-bors

#78626 Improve errors about #[deprecated] attribute
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_passes/src/stability.rs
  src/test/ui/deprecation/deprecation-sanity.rs
  src/test/ui/deprecation/deprecation-sanity.stderr
  src/test/ui/stability-attribute/stability-attribute-sanity.rs
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: A-diagnostics, D-papercut, S-waiting-on-bors

#77950 Add support for SHA256 source file hashing
  Cargo.lock
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
  compiler/rustc_session/src/options.rs
  compiler/rustc_span/Cargo.toml
  compiler/rustc_span/src/lib.rs
  src/doc/unstable-book/src/compiler-flags/src-hash-algorithm.md
  src/test/codegen/src-hash-algorithm/src-hash-algorithm-sha256.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors

#78677 Use reparsed `TokenStream` if we captured any inner attributes
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/proc-macro/issue-78675-captured-inner-attrs.rs
  src/test/ui/proc-macro/issue-78675-captured-inner-attrs.stdout
Labels: S-waiting-on-bors, merged-by-bors

#77227 Refactorings in preparation for const value trees
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/constant.rs
  compiler/rustc_codegen_cranelift/src/discriminant.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_cranelift/src/value_and_place.rs
  compiler/rustc_codegen_llvm/src/common.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_lint/src/types.rs
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_middle/src/mir/interpret/mod.rs
  compiler/rustc_middle/src/mir/interpret/value.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/consts.rs
  compiler/rustc_middle/src/ty/consts/int.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/util.rs
  compiler/rustc_mir/src/const_eval/eval_queries.rs
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/cast.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/interpret/operand.rs
  compiler/rustc_mir/src/interpret/place.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  compiler/rustc_mir/src/transform/simplify_comparison_integral.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir_build/src/build/matches/simplify.rs
  compiler/rustc_mir_build/src/thir/constant.rs
  compiler/rustc_mir_build/src/thir/pattern/_match.rs
  compiler/rustc_mir_build/src/thir/pattern/mod.rs
  compiler/rustc_symbol_mangling/src/legacy.rs
  compiler/rustc_symbol_mangling/src/v0.rs
  compiler/rustc_target/src/abi/mod.rs
  src/librustdoc/clean/utils.rs
  src/tools/clippy/clippy_lints/src/consts.rs
Labels: S-waiting-on-bors, merged-by-bors

#78280 Codegen: Query span as late as possible
  compiler/rustc_codegen_llvm/src/consts.rs
  compiler/rustc_codegen_ssa/src/base.rs
Labels: S-waiting-on-bors, merged-by-bors

#78740 Remove legacy promote-release support from build-manifestg
  src/bootstrap/builder.rs
  src/bootstrap/dist.rs
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#78662 Provide diagnostic suggestion in ExprUseVisitor Delegate
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/expr_use_visitor.rs
  src/test/ui/borrowck/borrowck-closures-slice-patterns.stderr
  src/tools/clippy/clippy_lints/src/escape.rs
  src/tools/clippy/clippy_lints/src/loops.rs
  src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs
  src/tools/clippy/clippy_lints/src/utils/usage.rs
Labels: A-diagnostics, S-waiting-on-bors, merged-by-bors

#78754 Bump actions/checkout to version 2
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
Labels: S-waiting-on-bors, T-infra, merged-by-bors

#78758 Fixed typo in comment
  compiler/rustc_middle/src/ty/mod.rs
Labels: C-cleanup, S-waiting-on-bors

#78757 Improve and clean up some intra-doc links
  library/core/src/intrinsics.rs
  library/std/src/primitive_docs.rs
Labels: C-cleanup, S-waiting-on-bors, T-doc

#78739 Fix ICE on type error in async function
  compiler/rustc_typeck/src/check/closure.rs
  src/test/ui/async-await/issues/issue-78654.full.stderr
  src/test/ui/async-await/issues/issue-78654.min.stderr
  src/test/ui/async-await/issues/issue-78654.rs
Labels: S-waiting-on-bors, T-compiler

#78742 make intern_const_alloc_recursive return error
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_mir/src/const_eval/error.rs
  compiler/rustc_mir/src/const_eval/eval_queries.rs
  compiler/rustc_mir/src/const_eval/mod.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/interpret/intern.rs
  compiler/rustc_mir/src/interpret/operand.rs
  src/test/ui/consts/dangling-alloc-id-ice.rs
  src/test/ui/consts/dangling-alloc-id-ice.stderr
  src/test/ui/consts/issue-78655.rs
  src/test/ui/consts/issue-78655.stderr
Labels: S-waiting-on-bors

#78738 Move range in ui test to ops test in library/core
  library/core/tests/ops.rs
  src/test/ui/range.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors, libs-impl

#78735 Simplify the implementation of `get_mut` (no unsafe)
  library/core/src/cell.rs
Labels: S-waiting-on-bors

#78733 fix a couple of clippy warnings:
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_middle/src/middle/stability.rs
  compiler/rustc_middle/src/mir/terminator.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_mir/src/transform/match_branches.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/fulfill.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#78727 (rustdoc) fix test for trait impl display
  src/test/rustdoc/impl-everywhere.rs
Labels: A-testsuite, S-waiting-on-bors, T-rustdoc

#78716 Array trait impl comment/doc fixes
  library/core/src/array/mod.rs
  library/std/src/primitive_docs.rs
Labels: S-waiting-on-bors, T-doc

#78584 Add keyboard handling to the theme picker menu
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#78465 Change as_str → to_string in proc_macro::Ident::span() docs
  library/proc_macro/src/lib.rs
Labels: C-cleanup, S-waiting-on-bors, T-doc, T-libs

#78425 Move f64::NAN ui tests into `library`
  library/core/tests/num/mod.rs
  library/core/tests/num/nan.rs
Labels: A-testsuite, S-waiting-on-bors, T-libs

#78093 Clean up docs for 'as' keyword
  library/std/src/keyword_docs.rs
Labels: C-cleanup, S-waiting-on-bors, T-doc

#76718 Move Vec UI tests to unit tests when possible
  library/alloc/tests/slice.rs
  library/alloc/tests/vec.rs
  library/alloc/tests/vec_deque.rs
  src/test/ui/array-slice-vec/subslice-patterns-pass.rs
  src/test/ui/array-slice-vec/vec-macro-repeat.rs
  src/test/ui/swap-2.rs
  src/test/ui/zero-sized/zero-sized-vec-deque-push.rs
  src/test/ui/zero-sized/zero-sized-vec-push.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors, T-libs

#78638 reverse binding order in matches to allow the subbinding of copyable fields in bindings after @
  compiler/rustc_mir_build/src/build/matches/simplify.rs
  src/test/ui/pattern/bindings-after-at/bind-by-copy.rs
  src/test/ui/pattern/bindings-after-at/bind-by-move-neither-can-live-while-the-other-survives-1.rs
  src/test/ui/pattern/bindings-after-at/bind-by-move-neither-can-live-while-the-other-survives-1.stderr
  src/test/ui/pattern/bindings-after-at/bind-by-move-no-subbindings-fun-param.rs
  src/test/ui/pattern/bindings-after-at/bind-by-move-no-subbindings-fun-param.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-move-and-move.rs
  src/test/ui/pattern/bindings-after-at/borrowck-move-and-move.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-pat-at-and-box.rs
  src/test/ui/pattern/bindings-after-at/borrowck-pat-at-and-box.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-pat-by-move-and-ref-inverse.rs
  src/test/ui/pattern/bindings-after-at/borrowck-pat-by-move-and-ref-inverse.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-pat-by-move-and-ref.rs
  src/test/ui/pattern/bindings-after-at/borrowck-pat-by-move-and-ref.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-pat-ref-mut-and-ref.rs
  src/test/ui/pattern/bindings-after-at/borrowck-pat-ref-mut-and-ref.stderr
  src/test/ui/pattern/bindings-after-at/borrowck-pat-ref-mut-twice.rs
  src/test/ui/pattern/bindings-after-at/borrowck-pat-ref-mut-twice.stderr
  src/test/ui/pattern/bindings-after-at/copy-and-move-mixed.rs
  src/test/ui/pattern/bindings-after-at/copy-and-move-mixed.stderr
  src/test/ui/pattern/bindings-after-at/default-binding-modes-both-sides-independent.rs
  src/test/ui/pattern/bindings-after-at/default-binding-modes-both-sides-independent.stderr
Labels: S-waiting-on-bors, merged-by-bors

#77856 Add non_autolinks lint
  Cargo.lock
  compiler/rustc_codegen_cranelift/src/discriminant.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_lint_defs/src/lib.rs
  compiler/rustc_middle/src/mir/coverage.rs
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_mir/src/borrow_check/region_infer/mod.rs
  compiler/rustc_mir/src/transform/dest_prop.rs
  compiler/rustc_mir_build/src/thir/pattern/_match.rs
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_target/src/spec/crt_objects.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/wasm32_unknown_unknown.rs
  compiler/rustc_target/src/spec/wasm32_wasi.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  library/core/src/future/mod.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/core/src/num/dec2flt/mod.rs
  library/core/src/slice/sort.rs
  library/panic_unwind/src/dwarf/eh.rs
  library/panic_unwind/src/gcc.rs
  src/bootstrap/toolstate.rs
  src/build_helper/lib.rs
  src/doc/rustdoc/src/lints.md
  src/librustdoc/Cargo.toml
  src/librustdoc/core.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/non_autolinks.rs
  src/test/rustdoc-ui/url-improvements.rs
  src/test/rustdoc-ui/url-improvements.stderr
Labels: A-lint, S-waiting-on-bors, T-rustdoc, merged-by-bors

#77351 Fix `x.py clippy`
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
  src/bootstrap/flags.rs
Labels: A-rustbuild, S-waiting-on-bors, merged-by-bors

#78798 Fixing Spelling Typos
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_typeck/src/check/pat.rs
  src/test/ui/error-codes/E0027.stderr
  src/test/ui/structs/struct-field-cfg.stderr
  src/test/ui/structs/struct-pat-derived-error.stderr
Labels: S-waiting-on-bors

#78795 The renumber pass is long gone
  compiler/rustc_ast/src/node_id.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#78794 rustc_expand: use collect_bang helper instead of manual reimplementation
  compiler/rustc_expand/src/expand.rs
Labels: A-macros, C-cleanup, S-waiting-on-bors, T-compiler

#78771 inliner: Copy unevaluated constants only after successful inlining
  compiler/rustc_mir/src/transform/inline.rs
Labels: S-waiting-on-bors

#78760 `deny(invalid_codeblock_attributes)` for rustc_error_codes
  compiler/rustc_error_codes/src/lib.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#78730 Expand explanation of reverse_bits
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
Labels: S-waiting-on-bors

#78726 Add link to rust website
  src/doc/index.md
Labels: S-waiting-on-bors, T-doc

#78705 Print a summary of which test suite failed
  src/bootstrap/test.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header/tests.rs
  src/tools/compiletest/src/main.rs
Labels: A-contributor-roadblock, A-rustbuild, A-testsuite, C-enhancement, S-waiting-on-bors

#78666 Fix shellcheck error
  compiler/rustc_codegen_cranelift/scripts/cargo.sh
  compiler/rustc_codegen_cranelift/scripts/config.sh
  compiler/rustc_codegen_cranelift/test.sh
  src/ci/docker/host-x86_64/disabled/dist-x86_64-dragonfly/build-toolchain.sh
  src/ci/docker/host-x86_64/disabled/dist-x86_64-haiku/build-toolchain.sh
  src/ci/docker/host-x86_64/dist-aarch64-linux/build-toolchains.sh
  src/ci/docker/host-x86_64/dist-arm-linux/build-toolchains.sh
  src/ci/docker/host-x86_64/dist-armhf-linux/build-toolchains.sh
  src/ci/docker/host-x86_64/dist-armv7-linux/build-toolchains.sh
  src/ci/docker/host-x86_64/dist-powerpc-linux/build-powerpc-toolchain.sh
  src/ci/docker/host-x86_64/dist-powerpc64-linux/shared.sh
  src/ci/docker/host-x86_64/dist-powerpc64le-linux/shared.sh
  src/ci/docker/host-x86_64/dist-riscv64-linux/build-toolchains.sh
  src/ci/docker/host-x86_64/dist-riscv64-linux/crosstool-ng.sh
  src/ci/docker/host-x86_64/dist-s390x-linux/build-s390x-toolchain.sh
  src/ci/docker/host-x86_64/dist-various-1/build-rumprun.sh
  src/ci/docker/host-x86_64/dist-various-1/install-mips-musl.sh
  src/ci/docker/host-x86_64/dist-various-1/install-mipsel-musl.sh
  src/ci/docker/host-x86_64/dist-various-2/shared.sh
  src/ci/docker/host-x86_64/dist-x86_64-linux/shared.sh
  src/ci/docker/host-x86_64/dist-x86_64-netbsd/build-netbsd-toolchain.sh
  src/ci/docker/scripts/android-base-apt-get.sh
  src/ci/docker/scripts/android-ndk.sh
  src/ci/docker/scripts/android-sdk.sh
  src/ci/docker/scripts/cross-apt-packages.sh
  src/ci/docker/scripts/crosstool-ng-1.24.sh
  src/ci/docker/scripts/crosstool-ng.sh
  src/ci/docker/scripts/emscripten.sh
  src/ci/docker/scripts/freebsd-toolchain.sh
  src/ci/docker/scripts/make3.sh
  src/ci/docker/scripts/musl-toolchain.sh
  src/ci/docker/scripts/musl.sh
  src/ci/docker/scripts/rustbuild-setup.sh
  src/ci/docker/scripts/sccache.sh
  src/ci/init_repo.sh
  src/ci/shared.sh
  src/test/run-make/thumb-none-qemu/script.sh
  src/test/run-make/x86_64-fortanix-unknown-sgx-lvi/script.sh
Labels: S-waiting-on-bors, T-infra

#78559 Add LLVM upgrades from 7 to 10 to RELEASES.md
  RELEASES.md
Labels: S-waiting-on-bors

#78538 BTreeMap: document a curious assumption in test cases
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/mod.rs
  library/alloc/src/collections/btree/set/tests.rs
Labels: A-testsuite, S-waiting-on-bors, libs-impl

#78514 Allow using 1/2/3/4 for `x.py setup` options
  src/bootstrap/setup.rs
Labels: A-rustbuild, C-enhancement, S-waiting-on-bors

#78167 Fix unreachable sub-branch detection in or-patterns
  compiler/rustc_mir_build/src/thir/pattern/_match.rs
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.stderr
Labels: A-exhaustiveness-checking, S-waiting-on-bors

#78006 Use Intra-doc links for std::io::buffered
  library/std/src/io/buffered/bufreader.rs
  library/std/src/io/buffered/bufwriter.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#74979 `#![deny(unsafe_op_in_unsafe_fn)]` in sys/hermit
  library/std/src/sys/hermit/mod.rs
Labels: S-waiting-on-bors

#75778 75521 rustdoc book improvements
  src/doc/rustdoc/src/SUMMARY.md
  src/doc/rustdoc/src/how-to-write-documentation.md
  src/doc/rustdoc/src/references.md
  src/doc/rustdoc/src/what-is-rustdoc.md
  src/doc/rustdoc/src/what-to-include.md
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors, T-doc, T-rustdoc, merged-by-bors

#78783 [beta] backports
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/static_impl_trait.rs
  compiler/rustc_mir/src/transform/instcombine.rs
  compiler/rustc_mir/src/transform/match_branches.rs
  compiler/rustc_mir/src/transform/validate.rs
  compiler/rustc_trait_selection/src/traits/codegen/mod.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/query/normalize.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  src/ci/docker/host-x86_64/armhf-gnu/Dockerfile
  src/test/mir-opt/const_prop/ref_deref.main.ConstProp.diff
  src/test/mir-opt/const_prop/ref_deref_project.main.ConstProp.diff
  src/test/mir-opt/inst_combine_deref.rs
  src/test/mir-opt/matches_reduce_branches.bar.MatchBranchSimplification.32bit.diff
  src/test/mir-opt/matches_reduce_branches.bar.MatchBranchSimplification.64bit.diff
  src/test/mir-opt/matches_reduce_branches.foo.MatchBranchSimplification.32bit.diff
  src/test/mir-opt/matches_reduce_branches.foo.MatchBranchSimplification.64bit.diff
  src/test/mir-opt/matches_reduce_branches.rs
  src/test/mir-opt/not_equal_false.opt.InstCombine.diff
  src/test/ui/issues/issue-77218.rs
  src/test/ui/issues/issue-77218.stderr
  src/test/ui/issues/issue-77919.rs
  src/test/ui/issues/issue-77919.stderr
  src/test/ui/issues/issue-78372.rs
  src/test/ui/issues/issue-78372.stderr
  src/test/ui/issues/issue-78622.rs
  src/test/ui/issues/issue-78622.stderr
  src/test/ui/regions/issue-78262.default.stderr
  src/test/ui/regions/issue-78262.nll.stderr
  src/test/ui/regions/issue-78262.rs
  src/test/ui/suggestions/if-let-typo.rs
  src/test/ui/suggestions/if-let-typo.stderr
  src/test/ui/type-alias-impl-trait/issue-72793.rs
Labels: S-waiting-on-bors, merged-by-bors

#75199 Re-enable debug and LLVM assertions
  .github/workflows/ci.yml
  src/ci/docker/host-x86_64/i686-gnu-nopt/Dockerfile
  src/ci/docker/host-x86_64/i686-gnu/Dockerfile
  src/ci/docker/host-x86_64/x86_64-gnu-distcheck/Dockerfile
  src/ci/docker/host-x86_64/x86_64-gnu-llvm-8/Dockerfile
  src/ci/github-actions/ci.yml
Labels: A-testsuite, S-waiting-on-bors, T-compiler, T-infra, merged-by-bors

#78784 Revert "Revert "resolve: Avoid "self-confirming" import resolutions in one more case""
  compiler/rustc_resolve/src/imports.rs
  src/test/ui/imports/issue-62767.rs
  src/test/ui/imports/issue-62767.stderr
Labels: A-resolve, S-waiting-on-bors, T-compiler, T-lang, beta-nominated, merged-by-bors

#78845 [beta] try to work around type normalization regression
  library/alloc/src/vec.rs
Labels: S-waiting-on-bors, merged-by-bors

#78410 revert #75443, update mir validator
  compiler/rustc_mir/src/transform/validate.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/query/normalize.rs
  src/test/ui/type-alias-impl-trait/issue-72793.rs
Labels: A-mir-opt, A-typesystem, S-waiting-on-bors, T-compiler, beta-accepted, merged-by-bors, relnotes

#78865 Don't fire `CONST_ITEM_MUTATION` lint when borrowing a deref
  compiler/rustc_mir/src/transform/check_const_item_mutation.rs
  src/test/ui/lint/lint-const-item-mutation.rs
  src/test/ui/lint/lint-const-item-mutation.stderr
Labels: S-waiting-on-bors

#78861 typo and formatting
  compiler/rustc_expand/src/placeholders.rs
Labels: S-waiting-on-bors

#78860 rustc_resolve: Use `#![feature(format_args_capture)]`
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
Labels: S-waiting-on-bors

#78852 Convert a bunch of intra-doc links
  library/alloc/src/fmt.rs
  library/core/src/cell.rs
  library/core/src/cmp.rs
  library/core/src/fmt/builders.rs
  library/core/src/iter/adapters/flatten.rs
  library/core/src/iter/adapters/mod.rs
  library/std/src/collections/hash/map.rs
  library/std/src/sync/mpsc/mod.rs
  library/std/src/sys/cloudabi/abi/cloudabi.rs
  library/std/src/sys/sgx/ext/io.rs
  library/std/src/thread/local.rs
  library/std/src/thread/mod.rs
Labels: A-intra-doc-links, C-cleanup, S-waiting-on-bors, T-doc

#78843 Less verbose debug logging from inlining integrator
  compiler/rustc_mir/src/transform/inline.rs
Labels: A-mir-opt, S-waiting-on-bors, T-compiler

#78842 Honor the rustfmt setting in config.toml
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#78841 Small cleanup in `TypeFoldable` derive macro
  compiler/rustc_macros/src/type_foldable.rs
Labels: C-cleanup, S-waiting-on-bors

#78828 use single char patterns for split() (clippy::single_char_pattern)
  compiler/rustc_mir/src/transform/coverage/debug.rs
  compiler/rustc_mir/src/util/generic_graphviz.rs
Labels: S-waiting-on-bors

#78811 Make some std::io functions `const`
  library/std/src/io/cursor.rs
  library/std/src/io/cursor/tests.rs
  library/std/src/io/util.rs
  library/std/src/io/util/tests.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors

#78788 Correct unsigned equivalent of isize to be usize
  library/core/src/num/mod.rs
Labels: S-waiting-on-bors, T-libs

#78728 Constantify `UnsafeCell::into_inner` and related
  library/core/src/cell.rs
  library/core/src/lib.rs
  library/core/src/sync/atomic.rs
  library/core/tests/cell.rs
  library/core/tests/lib.rs
Labels: A-const-fn, S-waiting-on-bors, T-libs

#78706 Fix run-make tests running when LLVM is disabled
  src/bootstrap/test.rs
Labels: A-cranelift, A-rustbuild, A-testsuite, S-waiting-on-bors, T-compiler

#78658 Add a tool to run `x.py` from any subdirectory
  .gitignore
  Cargo.toml
  src/tools/x/Cargo.lock
  src/tools/x/Cargo.toml
  src/tools/x/README.md
  src/tools/x/src/main.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#78570 Remove FIXME comment in print_type_sizes ui test suite
  src/test/ui/print_type_sizes/anonymous.rs
  src/test/ui/print_type_sizes/generics.rs
  src/test/ui/print_type_sizes/multiple_types.rs
  src/test/ui/print_type_sizes/niche-filling.rs
  src/test/ui/print_type_sizes/no_duplicates.rs
  src/test/ui/print_type_sizes/packed.rs
  src/test/ui/print_type_sizes/padding.rs
  src/test/ui/print_type_sizes/repr-align.rs
  src/test/ui/print_type_sizes/repr_int_c.rs
  src/test/ui/print_type_sizes/uninhabited.rs
  src/test/ui/print_type_sizes/variants.rs
  src/test/ui/print_type_sizes/zero-sized-fields.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors

#78572 Use SOCK_CLOEXEC and accept4() on more platforms.
  library/std/src/sys/unix/net.rs
Labels: O-android, O-dragonfly, O-freebsd, O-netbsd, O-openbsd, S-waiting-on-bors, libs-impl

#78065 make concurrency helper more pleasant to read
  library/test/src/helpers/concurrency.rs
Labels: S-waiting-on-bors, libs-impl

#76227 Stabilize `Poll::is_ready` and `is_pending` as const
  library/core/src/task/poll.rs
  library/core/tests/lib.rs
  library/core/tests/task.rs
Labels: A-const-fn, S-waiting-on-bors, S-waiting-on-fcp, T-libs, disposition-merge, finished-final-comment-period, relnotes

#76097 Stabilize hint::spin_loop
  library/alloc/src/lib.rs
  library/core/src/hint.rs
  library/core/src/sync/atomic.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#78712 rustc_ast: Visit tokens stored in AST nodes in mutable visitor
  compiler/rustc_ast/src/mut_visit.rs
  src/test/ui/proc-macro/nonterminal-token-hygiene.rs
  src/test/ui/proc-macro/nonterminal-token-hygiene.stdout
Labels: S-waiting-on-bors, merged-by-bors

#78889 Rollup of 12 pull requests
  .gitattributes
  .github/workflows/ci.yml
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_lowering/src/pat.rs
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_ssa/src/mir/mod.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/middle/limits.rs
  compiler/rustc_middle/src/ty/instance.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/monomorphize/collector.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/pat.rs
  compiler/rustc_typeck/src/check/regionck.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/node/tests.rs
  library/core/src/lib.rs
  library/core/src/num/error.rs
  library/core/src/num/mod.rs
  library/core/tests/nonzero.rs
  library/core/tests/num/mod.rs
  library/std/src/fs.rs
  library/std/src/fs/tests.rs
  library/std/src/sys/unix/fs.rs
  library/std/src/sys/unix/process/process_common/tests.rs
  src/ci/docker/host-x86_64/dist-aarch64-linux/Dockerfile
  src/ci/github-actions/ci.yml
  src/doc/rustc/src/platform-support.md
  src/librustdoc/core.rs
  src/librustdoc/html/static/settings.css
  src/test/mir-opt/inline/inline-shims.rs
  src/test/mir-opt/inline/inline_shims.clone.Inline.diff
  src/test/mir-opt/inline/inline_shims.drop.Inline.diff
  src/test/ui/bad/bad-expr-lhs.rs
  src/test/ui/bad/bad-expr-lhs.stderr
  src/test/ui/destructuring-assignment/default-match-bindings-forbidden.rs
  src/test/ui/destructuring-assignment/default-match-bindings-forbidden.stderr
  src/test/ui/destructuring-assignment/note-unsupported.rs
  src/test/ui/destructuring-assignment/note-unsupported.stderr
  src/test/ui/destructuring-assignment/tuple_destructure.rs
  src/test/ui/destructuring-assignment/tuple_destructure_fail.rs
  src/test/ui/destructuring-assignment/tuple_destructure_fail.stderr
  src/test/ui/destructuring-assignment/warn-unused-duplication.rs
  src/test/ui/destructuring-assignment/warn-unused-duplication.stderr
  src/test/ui/feature-gates/feature-gate-destructuring_assignment.rs
  src/test/ui/feature-gates/feature-gate-destructuring_assignment.stderr
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#78882 Nicer hunk headers for rust files
  .gitattributes
Labels: A-meta, S-waiting-on-bors

#78878 Avoid overlapping cfg attributes when both macOS and aarch64
  library/std/src/sys/unix/process/process_common/tests.rs
Labels: S-waiting-on-bors

#78868 Fix tab focus on restyled switches
  src/librustdoc/html/static/settings.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#78748 Implement destructuring assignment for tuples
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_lowering/src/pat.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/pat.rs
  compiler/rustc_typeck/src/check/regionck.rs
  src/test/ui/bad/bad-expr-lhs.rs
  src/test/ui/bad/bad-expr-lhs.stderr
  src/test/ui/destructuring-assignment/default-match-bindings-forbidden.rs
  src/test/ui/destructuring-assignment/default-match-bindings-forbidden.stderr
  src/test/ui/destructuring-assignment/note-unsupported.rs
  src/test/ui/destructuring-assignment/note-unsupported.stderr
  src/test/ui/destructuring-assignment/tuple_destructure.rs
  src/test/ui/destructuring-assignment/tuple_destructure_fail.rs
  src/test/ui/destructuring-assignment/tuple_destructure_fail.stderr
  src/test/ui/destructuring-assignment/warn-unused-duplication.rs
  src/test/ui/destructuring-assignment/warn-unused-duplication.stderr
  src/test/ui/feature-gates/feature-gate-destructuring_assignment.rs
  src/test/ui/feature-gates/feature-gate-destructuring_assignment.stderr
Labels: S-waiting-on-bors, T-compiler

#78674 inliner: Use substs_for_mir_body
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_ssa/src/mir/mod.rs
  compiler/rustc_middle/src/ty/instance.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/monomorphize/collector.rs
  compiler/rustc_mir/src/transform/inline.rs
  src/test/mir-opt/inline/inline-shims.rs
  src/test/mir-opt/inline/inline_shims.clone.Inline.diff
  src/test/mir-opt/inline/inline_shims.drop.Inline.diff
Labels: S-waiting-on-bors

#78476 fix some incorrect aliasing in the BTree
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, libs-impl

#78437 BTreeMap: stop mistaking node for an orderly place
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/node/tests.rs
Labels: S-waiting-on-bors

#78345 Fix handling of item names for HIR
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/ty/mod.rs
Labels: A-hir, S-waiting-on-bors, T-compiler

#78228 Promote aarch64-unknown-linux-gnu to Tier 1
  .github/workflows/ci.yml
  src/ci/docker/host-x86_64/dist-aarch64-linux/Dockerfile
  src/ci/github-actions/ci.yml
  src/doc/rustc/src/platform-support.md
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors, T-infra, relnotes

#78114 Recognize `private_intra_doc_links` as a lint
  compiler/rustc_lint_defs/src/builtin.rs
  src/librustdoc/core.rs
Labels: A-intra-doc-links, C-bug, S-waiting-on-bors, T-rustdoc

#78026 Define `fs::hard_link` to not follow symlinks.
  library/std/src/fs.rs
  library/std/src/fs/tests.rs
  library/std/src/sys/unix/fs.rs
Labels: A-io, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#77640 Refactor IntErrorKind to avoid "underflow" terminology
  compiler/rustc_middle/src/middle/limits.rs
  library/core/src/lib.rs
  library/core/src/num/error.rs
  library/core/src/num/mod.rs
  library/core/tests/nonzero.rs
  library/core/tests/num/mod.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#78201 Compile rustc crates with the initial-exec TLS model
  src/bootstrap/builder.rs
  src/bootstrap/lib.rs
Labels: A-codegen, A-thread-locals, I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors, relnotes

#78844 Monomorphize a type argument of size-of operation during codegen
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
Labels: S-waiting-on-bors

#78830 fix `super_visit_with` for `Terminator`
  compiler/rustc_middle/src/mir/type_foldable.rs
Labels: S-waiting-on-bors

#78746 Demote i686-unknown-freebsd to tier 2 compiler target
  .github/workflows/ci.yml
  src/ci/docker/host-x86_64/dist-i686-freebsd/Dockerfile
  src/ci/docker/host-x86_64/dist-various-2/Dockerfile
  src/ci/github-actions/ci.yml
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors, T-release, relnotes

#78710 rustc_ast: Do not panic by default when visiting macro calls
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_passes/src/node_count.rs
  compiler/rustc_ast_passes/src/show_span.rs
  compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
  compiler/rustc_builtin_macros/src/proc_macro_harness.rs
  compiler/rustc_builtin_macros/src/test_harness.rs
  compiler/rustc_expand/src/config.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/mbe/transcribe.rs
  compiler/rustc_expand/src/mut_visit/tests.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_lint/src/early.rs
  compiler/rustc_parse/src/parser/pat.rs
  compiler/rustc_passes/src/hir_stats.rs
  src/test/ui/parser/issue-65122-mac-invoc-in-mut-patterns.rs
  src/tools/clippy/clippy_lints/src/non_expressive_names.rs
Labels: S-waiting-on-bors

#78580 inliner: Break inlining cycles
  compiler/rustc_mir/src/transform/inline.rs
  src/test/mir-opt/inline/inline-cycle.rs
  src/test/mir-opt/inline/inline_cycle.one.Inline.diff
  src/test/mir-opt/inline/inline_cycle.two.Inline.diff
Labels: A-mir-opt-inlining, S-waiting-on-bors

#78566 Enable LLVM Polly via llvm-args.
  config.toml.example
  src/bootstrap/config.rs
  src/bootstrap/native.rs
Labels: S-waiting-on-bors

#78513 Infer the default host target from the host toolchain if possible
  src/bootstrap/CHANGELOG.md
  src/bootstrap/bootstrap.py
  src/bootstrap/configure.py
Labels: A-rustbuild, S-waiting-on-bors

#78502 Update Chalk to 0.36.0
  Cargo.lock
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/traits/chalk.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_traits/Cargo.toml
  compiler/rustc_traits/src/chalk/db.rs
  compiler/rustc_traits/src/chalk/lowering.rs
  compiler/rustc_traits/src/chalk/mod.rs
  compiler/rustc_typeck/src/collect/item_bounds.rs
  src/test/ui/chalkify/arithmetic.rs
  src/test/ui/chalkify/trait-objects.rs
Labels: S-waiting-on-bors

#78480 BTreeMap: fix pointer provenance rules
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/search.rs
  library/alloc/src/lib.rs
Labels: S-waiting-on-bors

#77016 Test clippy on PR CI on changes
  src/ci/scripts/should-skip-this.sh
Labels: A-testsuite, S-waiting-on-bors, T-infra

#76468 Improve lifetime name annotations for closures & async functions
  compiler/rustc_mir/src/borrow_check/diagnostics/region_name.rs
  src/test/ui/async-await/issue-74072-lifetime-name-annotations.rs
  src/test/ui/async-await/issue-74072-lifetime-name-annotations.stderr
  src/test/ui/async-await/issue-74497-lifetime-in-opaque.rs
  src/test/ui/async-await/issue-74497-lifetime-in-opaque.stderr
  src/test/ui/borrowck/issue-53432-nested-closure-outlives-borrowed-value.stderr
  src/test/ui/nll/issue-58053.stderr
Labels: A-async-await, A-closures, A-diagnostics, S-waiting-on-bors, T-compiler

#74754 Add `#[cfg(panic = '...')]`
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/spec/mod.rs
  src/doc/unstable-book/src/language-features/cfg-panic.md
  src/test/ui/cfg/cfg-panic-abort.rs
  src/test/ui/cfg/cfg-panic.rs
  src/test/ui/consts/control-flow/assert.const_panic.stderr
  src/test/ui/consts/control-flow/assert.rs
  src/test/ui/feature-gates/feature-gate-cfg-panic.rs
  src/test/ui/feature-gates/feature-gate-cfg-panic.stderr
  src/test/ui/fmt/format-args-capture.rs
  src/test/ui/issues/issue-68696-catch-during-unwind.rs
  src/test/ui/test-attrs/test-allow-fail-attr.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, needs-fcp

#78910 Fix links to stabilized versions of some intrinsics
  library/core/src/intrinsics.rs
Labels: C-bug, S-waiting-on-bors, T-doc

#78912 Add macro test for min-const-generics
  src/test/ui/const-generics/min_const_generics/macro-fail.rs
  src/test/ui/const-generics/min_const_generics/macro-fail.stderr
  src/test/ui/const-generics/min_const_generics/macro.rs
Labels: S-waiting-on-bors

#78908 (rustdoc) [src] link for types defined by macros shows invocation, not defintion
  src/librustdoc/clean/mod.rs
  src/test/rustdoc/external-macro-src.rs
  src/test/rustdoc/issue-26606.rs
  src/test/rustdoc/thread-local-src.rs
Labels: A-macros, S-waiting-on-bors, T-rustdoc

#78898 add regression test for #78892
  src/test/ui/macros/issue-78892-substitution-in-statement-attr.rs
Labels: S-waiting-on-bors

#78897 Add missing newline to error message of the default OOM hook
  library/std/src/alloc.rs
  src/test/ui/default-alloc-error-hook.rs
Labels: S-waiting-on-bors, libs-impl

#78896 Clarified description of write! macro
  library/core/src/macros/mod.rs
Labels: S-waiting-on-bors

#78890 comment attribution fix
  compiler/rustc_middle/src/ty/consts/int.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#78887 Add comments to explain memory usage optimization
  compiler/rustc_mir/src/dataflow/framework/engine.rs
Labels: A-mir-opt, S-waiting-on-bors, T-doc

#78854 Workaround for "could not fully normalize" ICE
  library/alloc/src/vec.rs
Labels: S-waiting-on-bors, beta-accepted

#78847 Assert that a return place is not used for indexing during integration
  compiler/rustc_mir/src/transform/inline.rs
Labels: S-waiting-on-bors

#78669 Use check-pass instead of build-pass in some consts ui test suits
  src/test/ui/consts/const-block-non-item-statement.rs
  src/test/ui/consts/const-fn-destructuring-arg.rs
  src/test/ui/consts/const_let_assign.rs
  src/test/ui/consts/const_let_assign2.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors

#78574 Use check-pass instead of build-pass in regions ui test suite
  src/test/ui/regions/region-bound-extra-bound-in-inherent-impl.rs
  src/test/ui/regions/region-bound-same-bounds-in-trait-and-impl.rs
  src/test/ui/regions/region-object-lifetime-1.rs
  src/test/ui/regions/region-object-lifetime-3.rs
  src/test/ui/regions/regions-implied-bounds-projection-gap-2.rs
  src/test/ui/regions/regions-implied-bounds-projection-gap-3.rs
  src/test/ui/regions/regions-implied-bounds-projection-gap-4.rs
  src/test/ui/regions/regions-outlives-nominal-type-enum-region-rev.rs
  src/test/ui/regions/regions-outlives-nominal-type-enum-region.rs
  src/test/ui/regions/regions-outlives-nominal-type-enum-type-rev.rs
  src/test/ui/regions/regions-outlives-nominal-type-enum-type.rs
  src/test/ui/regions/regions-outlives-nominal-type-struct-region-rev.rs
  src/test/ui/regions/regions-outlives-nominal-type-struct-region.rs
  src/test/ui/regions/regions-outlives-nominal-type-struct-type-rev.rs
  src/test/ui/regions/regions-outlives-nominal-type-struct-type.rs
  src/test/ui/regions/regions-outlives-projection-hrtype.rs
  src/test/ui/regions/regions-outlives-projection-trait-def.rs
  src/test/ui/regions/regions-outlives-scalar.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors

#76765 Make it more clear what an about async fn's returns when referring to what it returns
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/different_lifetimes.rs
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs
  src/test/ui/async-await/issues/issue-63388-1.stderr
  src/test/ui/async-await/multiple-lifetimes/ret-impl-trait-one.stderr
  src/test/ui/issues/issue-76547.nll.stderr
  src/test/ui/issues/issue-76547.rs
  src/test/ui/issues/issue-76547.stderr
  src/test/ui/self/arbitrary_self_types_pin_lifetime_mismatch-async.stderr
  src/test/ui/self/elision/lt-ref-self-async.stderr
  src/test/ui/self/elision/ref-mut-self-async.stderr
  src/test/ui/self/elision/ref-mut-struct-async.stderr
  src/test/ui/self/elision/ref-self-async.stderr
  src/test/ui/self/elision/ref-struct-async.stderr
Labels: A-async-await, A-diagnostics, S-waiting-on-bors, T-compiler

#78825 `unwrap_or` lint corrected
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_builtin_macros/src/test_harness.rs
  compiler/rustc_codegen_cranelift/src/bin/cg_clif.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_mir/src/borrow_check/region_infer/mod.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  library/std/src/time.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/html/render/cache.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#78790 Vendor libtest's dependencies in the rust-src component
  src/bootstrap/dist.rs
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#78946 Linux dist: don't include unique symbols in libLLVM
  src/ci/docker/host-x86_64/dist-x86_64-linux/build-gcc.sh
Labels: S-waiting-on-bors, merged-by-bors

#78947 Ship llvm-cov through llvm-tools
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors
