Repository rust-lang/rust, pull requests merged in 2020-01, with the labels that each got.

#67471 Revert parts of #66405.
  src/librustc_data_structures/obligation_forest/mod.rs
Labels: S-waiting-on-bors, beta-nominated, merged-by-bors

#67729 Bump smallvec
  Cargo.lock
  src/librustc_codegen_llvm/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#67700 Move stability queries to librustc_passes.
  src/librustc/middle/stability.rs
  src/librustc/ty/context.rs
  src/librustc_interface/passes.rs
  src/librustc_passes/lib.rs
  src/librustc_passes/stability.rs
Labels: S-waiting-on-bors, merged-by-bors

#67779 Update the barrier cache during ARM EHABI unwinding
  src/libpanic_unwind/gcc.rs
  src/libunwind/libunwind.rs
Labels: S-waiting-on-bors, merged-by-bors

#63177 Add Iterator::try_find
  src/libcore/iter/traits/iterator.rs
  src/libcore/lib.rs
  src/libcore/tests/iter.rs
  src/libcore/tests/lib.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#67768 Revert #65244 for performance reasons
  src/libcore/future/future.rs
  src/libcore/future/mod.rs
  src/librustc_ast_lowering/expr.rs
  src/librustc_ast_lowering/lib.rs
  src/librustc_span/symbol.rs
  src/libstd/future.rs
  src/libstd/lib.rs
  src/test/ui/async-await/async-fn-size-moved-locals.rs
  src/test/ui/async-await/await-into-future.rs
  src/test/ui/async-await/issues/issue-62009-1.stderr
Labels: S-waiting-on-bors, merged-by-bors

#67825 Minor: change take() docs grammar to match other docs
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#67807 Use drop instead of the toilet closure `|_| ()`
  src/liballoc/tests/arc.rs
  src/liballoc/tests/rc.rs
  src/librustc_parse/parser/diagnostics.rs
  src/libstd/io/buffered.rs
  src/libstd/sys/unix/android.rs
  src/libstd/sys/unix/fs.rs
  src/libstd/sys/unix/net.rs
  src/libstd/sys/unix/os.rs
  src/libstd/sys/unix/pipe.rs
  src/libstd/sys/unix/process/process_unix.rs
  src/libstd/sys/vxworks/fs.rs
  src/libstd/sys/vxworks/net.rs
  src/libstd/sys/vxworks/os.rs
  src/libstd/sys/vxworks/pipe.rs
  src/libstd/sys/vxworks/process/process_vxworks.rs
  src/libstd/sys/wasi/os.rs
  src/libstd/sys/windows/fs.rs
  src/libstd/sys/windows/handle.rs
  src/libstd/sys/windows/net.rs
  src/libstd/sys/windows/os.rs
  src/libstd/sys_common/mod.rs
  src/libstd/sys_common/net.rs
  src/test/ui/async-await/issues/issue-64433.rs
  src/test/ui/nll/issue-50343.rs
  src/test/ui/paths-containing-nul.rs
Labels: S-waiting-on-bors

#67796 Ensure that we process projections during MIR inlining
  src/librustc_mir/transform/inline.rs
  src/test/ui/mir/issue-67710-inline-projection.rs
Labels: S-waiting-on-bors

#67762 Add missing links for insecure_time
  src/libstd/time.rs
Labels: S-waiting-on-bors

#67736 Less-than is asymmetric, not antisymmetric
  src/libcore/cmp.rs
Labels: S-waiting-on-bors

#67829 Attempt to fix intermittent failures of pgo-branch-weights test.
  src/test/run-make-fulldeps/pgo-branch-weights/Makefile
Labels: S-waiting-on-bors, merged-by-bors

#67835 tweak wording of mismatched delimiter errors
  src/librustc_parse/lexer/tokentrees.rs
  src/librustc_parse/parser/mod.rs
  src/test/ui/issues/issue-62554.rs
  src/test/ui/issues/issue-62554.stderr
  src/test/ui/parser-recovery-1.rs
  src/test/ui/parser-recovery-1.stderr
  src/test/ui/parser-recovery-2.rs
  src/test/ui/parser-recovery-2.stderr
  src/test/ui/parser/issue-10636-1.rs
  src/test/ui/parser/issue-10636-1.stderr
  src/test/ui/parser/issue-2354-1.rs
  src/test/ui/parser/issue-2354-1.stderr
  src/test/ui/parser/issue-2354.rs
  src/test/ui/parser/issue-2354.stderr
  src/test/ui/parser/issue-58094-missing-right-square-bracket.stderr
  src/test/ui/parser/issue-62524.stderr
  src/test/ui/parser/issue-62546.rs
  src/test/ui/parser/issue-62546.stderr
  src/test/ui/parser/issue-62881.rs
  src/test/ui/parser/issue-62881.stderr
  src/test/ui/parser/issue-62973.stderr
  src/test/ui/parser/issue-63116.stderr
  src/test/ui/parser/issue-63135.stderr
  src/test/ui/parser/macro-mismatched-delim-brace-paren.rs
  src/test/ui/parser/macro-mismatched-delim-brace-paren.stderr
  src/test/ui/parser/macro-mismatched-delim-paren-brace.rs
  src/test/ui/parser/macro-mismatched-delim-paren-brace.stderr
  src/test/ui/parser/mbe_missing_right_paren.stderr
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-impl-trait.rs
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-impl-trait.stderr
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-struct.rs
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-struct.stderr
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-trait.rs
  src/test/ui/parser/mismatched-braces/missing-close-brace-in-trait.stderr
  src/test/ui/parser/mismatched-delim-brace-empty-block.rs
  src/test/ui/parser/mismatched-delim-brace-empty-block.stderr
  src/test/ui/parser/missing_right_paren.stderr
  src/test/ui/parser/unclosed-braces.rs
  src/test/ui/parser/unclosed-braces.stderr
  src/test/ui/parser/unclosed-delimiter-in-dep.stderr
  src/test/ui/parser/unclosed_delim_mod.rs
  src/test/ui/parser/unclosed_delim_mod.stderr
  src/test/ui/parser/unmatched-delimiter-at-end-of-file.rs
  src/test/ui/parser/unmatched-delimiter-at-end-of-file.stderr
  src/test/ui/proc-macro/invalid-punct-ident-4.rs
  src/test/ui/proc-macro/invalid-punct-ident-4.stderr
  src/test/ui/resolve/token-error-correct-2.rs
  src/test/ui/resolve/token-error-correct-2.stderr
  src/test/ui/resolve/token-error-correct.rs
  src/test/ui/resolve/token-error-correct.stderr
Labels: S-waiting-on-bors

#67810 Implement uncommon_codepoints lint.
  Cargo.lock
  src/librustc_lint/Cargo.toml
  src/librustc_lint/non_ascii_idents.rs
  src/test/ui/issues/issue-48508.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-uncommon-codepoints.rs
  src/test/ui/lint/rfc-2457-non-ascii-idents/lint-uncommon-codepoints.stderr
  src/tools/tidy/src/deps.rs
Labels: F-non_ascii_idents, S-waiting-on-bors

#67789 Cleanup linkchecker whitelist
  src/tools/linkchecker/main.rs
Labels: S-waiting-on-bors

#67773 Add a test for #37333
  src/test/incremental/change_implementation_cross_crate/auxiliary/a.rs
  src/test/incremental/change_implementation_cross_crate/main.rs
Labels: S-waiting-on-bors

#67531 no longer promote non-pattern const functions
  src/libcore/time.rs
Labels: I-nominated, S-waiting-on-bors, T-lang, T-libs

#67848 Remove unused `#[link_name = "m"]` attributes
  src/libstd/sys/unix/cmath.rs
  src/libstd/sys/vxworks/cmath.rs
  src/libstd/sys/windows/cmath.rs
Labels: S-waiting-on-bors

#67822 Revert `const_err` lint checking of casts
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/consts/const-prop-overflowing-casts.rs
  src/test/ui/consts/const-prop-overflowing-casts.stderr
  src/test/ui/simd/simd-intrinsic-generic-cast.rs
Labels: S-waiting-on-bors

#67812 Tweak and extend internal BTreeMap documentation, including debug asserts.
  src/liballoc/collections/btree/map.rs
  src/liballoc/collections/btree/node.rs
Labels: S-waiting-on-bors

#67808 perf: Don't recurse into types that do not need normalizing
  src/librustc/traits/project.rs
Labels: S-waiting-on-bors, merged-by-bors

#67777 Use self profile infrastructure for -Z time and -Z time-passes
  src/librustc/hir/map/mod.rs
  src/librustc/lib.rs
  src/librustc/ty/query/on_disk_cache.rs
  src/librustc/util/common.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/back/write.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/profiling.rs
  src/librustc_driver/lib.rs
  src/librustc_incremental/persist/load.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/queries.rs
  src/librustc_lint/early.rs
  src/librustc_lint/late.rs
  src/librustc_mir/monomorphize/collector.rs
  src/librustc_mir/monomorphize/partitioning.rs
  src/librustc_session/session.rs
  src/librustc_session/utils.rs
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#67882 remove bespoke flock bindings
  src/librustc_data_structures/flock.rs
Labels: S-waiting-on-bors

#67879 Remove negative number check from float sqrt
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#67845 Also remove const-hack for abs
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#67818 rustdoc: Avoid panic when parsing codeblocks for playground links
  src/librustdoc/test.rs
  src/test/rustdoc/playground-syntax-error.rs
Labels: S-waiting-on-bors

#67563 buffer lexer errors in rustdoc syntax checking
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
Labels: S-waiting-on-bors, merged-by-bors

#67915 Use Self instead of $type
  src/libcore/convert/num.rs
  src/libcore/fmt/num.rs
  src/libcore/iter/traits/accum.rs
  src/libcore/marker.rs
  src/libcore/num/bignum.rs
  src/test/ui/issues/issue-8460.rs
Labels: S-waiting-on-bors

#67912 macros: typo fix
  src/libcore/macros/mod.rs
Labels: S-waiting-on-bors

#67906 Silence `TooGeneric` error
  src/librustc/traits/error_reporting.rs
  src/librustc_typeck/impl_wf_check.rs
  src/test/ui/const-generics/array-size-in-generic-struct-param.rs
  src/test/ui/const-generics/array-size-in-generic-struct-param.stderr
Labels: F-const_generics, S-waiting-on-bors

#67897 Use `as_deref()` to replace `as_ref().map(...)`
  src/librustdoc/html/render.rs
Labels: S-waiting-on-bors

#67943 Missing module std in example.
  src/libstd/net/tcp.rs
Labels: S-waiting-on-bors

#67936 fire "non_camel_case_types" for associated types
  src/librustc_lint/nonstandard_style.rs
  src/test/ui/issues/issue-17732.rs
  src/test/ui/issues/issue-35600.rs
  src/test/ui/lint/lint-non-camel-case-types.rs
  src/test/ui/lint/lint-non-camel-case-types.stderr
Labels: S-waiting-on-bors

#67934 Clean up E0178 explanation
  src/librustc_error_codes/error_codes/E0178.md
Labels: S-waiting-on-bors

#67929 Formatting an example for method Vec.retain
  src/liballoc/vec.rs
Labels: S-waiting-on-bors

#67909 Fix ICE in const pretty printing and resolve FIXME
  src/librustc/ty/print/obsolete.rs
Labels: F-const_generics, S-waiting-on-bors

#67908 rustdoc: HTML escape const values
  src/librustdoc/html/format.rs
  src/librustdoc/html/render.rs
  src/test/rustdoc/const-generics/const-impl.rs
  src/test/rustdoc/show-const-contents.rs
Labels: S-waiting-on-bors

#67898 Improve hygiene of `newtype_index`
  src/librustc/dep_graph/serialized.rs
  src/librustc/middle/region.rs
  src/librustc_hir/hir_id.rs
  src/librustc_index/vec.rs
  src/librustc_index/vec/tests.rs
  src/librustc_mir/borrow_check/constraints/mod.rs
  src/librustc_mir/borrow_check/member_constraints.rs
  src/librustc_mir/borrow_check/type_check/liveness/local_use_map.rs
  src/librustc_mir/dataflow/impls/borrows.rs
  src/librustc_mir/dataflow/move_paths/mod.rs
  src/librustc_session/node_id.rs
  src/librustc_span/symbol.rs
  src/test/ui-fulldeps/newtype_index.rs
Labels: S-waiting-on-bors

#67880 Handle multiple error fix suggestions carefuly
  src/librustc_errors/emitter.rs
  src/test/ui/type/issue-67690-type-alias-bound-diagnostic-crash.rs
  src/test/ui/type/issue-67690-type-alias-bound-diagnostic-crash.stderr
  src/test/ui/type/type-alias-bounds.rs
  src/test/ui/type/type-alias-bounds.stderr
Labels: S-waiting-on-bors

#67877 Omit underscore constants from rustdoc
  src/librustdoc/visit_ast.rs
  src/test/rustdoc/const-underscore.rs
Labels: S-waiting-on-bors, T-rustdoc

#67671 Account for `type X = impl Trait;` in lifetime suggestion
  src/librustc_mir/borrow_check/diagnostics/region_errors.rs
  src/test/ui/impl-trait/multiple-lifetimes/error-handling.stderr
Labels: S-waiting-on-author

#67566 Add an unstable conversion from thread ID to u64
  src/libstd/thread/mod.rs
Labels: S-waiting-on-bors, T-libs

#67732 ci: remove 32-bit Apple targets
  src/ci/azure-pipelines/auto.yml
Labels: S-waiting-on-bors, merged-by-bors

#67312 Simplify Clone for Box<[T]>
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors, merged-by-bors

#67760 Clear out target directory if compiler has changed
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors, merged-by-bors

#68003 ci: fix wrong shared.sh import for publish_toolstate
  src/ci/publish_toolstate.sh
Labels: S-waiting-on-bors

#67985 Remove insignificant notes from CStr documentation
  src/libstd/ffi/c_str.rs
Labels: S-waiting-on-bors

#67955 rustdoc: Remove more `#[doc(cfg(..))]` duplicates
  src/librustdoc/clean/cfg.rs
  src/librustdoc/clean/cfg/tests.rs
  src/test/rustdoc/duplicate-cfg.rs
Labels: S-waiting-on-bors

#67875 Distinguish between private items and hidden items in rustdoc
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collapse_docs.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/private_items_doc_tests.rs
  src/librustdoc/passes/propagate_doc_cfg.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/passes/strip_priv_imports.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/passes/unindent_comments.rs
  src/test/rustdoc/issue-46380.rs
  src/test/rustdoc/issue-67851-both.rs
  src/test/rustdoc/issue-67851-hidden.rs
  src/test/rustdoc/issue-67851-neither.rs
  src/test/rustdoc/issue-67851-private.rs
Labels: S-waiting-on-bors, T-rustdoc, beta-nominated

#67798 Remove wrong advice about spin locks from `spin_loop_hint` docs
  src/libcore/sync/atomic.rs
Labels: S-waiting-on-bors

#67774 Try statx for all linux-gnu target.
  src/libstd/sys/unix/fs.rs
Labels: S-waiting-on-bors

#68024 Remove `-Z continue-parse-after-error`
  src/librustc_codegen_ssa/back/write.rs
  src/librustc_driver/lib.rs
  src/librustc_errors/lib.rs
  src/librustc_interface/passes.rs
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
  src/test/ui/consts/miri_unleashed/mutable_const2.stderr
  src/test/ui/parse-error-correct.rs
  src/test/ui/parse-error-correct.stderr
  src/test/ui/parser-recovery-1.rs
  src/test/ui/parser-recovery-1.stderr
  src/test/ui/parser-recovery-2.rs
  src/test/ui/parser-recovery-2.stderr
  src/test/ui/parser/ascii-only-character-escape.rs
  src/test/ui/parser/ascii-only-character-escape.stderr
  src/test/ui/parser/bad-char-literals.rs
  src/test/ui/parser/bad-char-literals.stderr
  src/test/ui/parser/byte-literals.rs
  src/test/ui/parser/byte-literals.stderr
  src/test/ui/parser/byte-string-literals.rs
  src/test/ui/parser/byte-string-literals.stderr
  src/test/ui/parser/impl-parsing.rs
  src/test/ui/parser/impl-parsing.stderr
  src/test/ui/parser/issue-23620-invalid-escapes.rs
  src/test/ui/parser/issue-23620-invalid-escapes.stderr
  src/test/ui/parser/issue-62913.rs
  src/test/ui/parser/issue-62913.stderr
  src/test/ui/parser/lex-bad-char-literals-1.rs
  src/test/ui/parser/lex-bad-char-literals-1.stderr
  src/test/ui/parser/lex-bad-char-literals-7.rs
  src/test/ui/parser/lex-bad-char-literals-7.stderr
  src/test/ui/parser/lex-bare-cr-string-literal-doc-comment.rs
  src/test/ui/parser/lex-bare-cr-string-literal-doc-comment.stderr
  src/test/ui/parser/raw-byte-string-literals.rs
  src/test/ui/parser/type-parameters-in-field-exprs.rs
  src/test/ui/parser/type-parameters-in-field-exprs.stderr
Labels: S-waiting-on-bors

#68026 Small improvements in lexical_region_resolve
  src/librustc/infer/lexical_region_resolve/mod.rs
Labels: S-waiting-on-bors

#68023 Fix issue #68008
  src/librustc_typeck/check/op.rs
  src/test/ui/issues/issue-28837.rs
  src/test/ui/issues/issue-28837.stderr
Labels: S-waiting-on-bors

#68009 Spell check librustc_error_codes
  src/librustc_error_codes/error_codes/E0038.md
  src/librustc_error_codes/error_codes/E0084.md
  src/librustc_error_codes/error_codes/E0307.md
  src/librustc_error_codes/error_codes/E0373.md
  src/librustc_error_codes/error_codes/E0426.md
Labels: S-waiting-on-bors

#68005 Improve E0184 explanation
  src/librustc_error_codes/error_codes/E0184.md
Labels: S-waiting-on-bors

#67990 slice patterns: harden match-based borrowck tests
  src/test/ui/borrowck/borrowck-move-out-from-array-match.rs
  src/test/ui/borrowck/borrowck-move-out-from-array-match.stderr
  src/test/ui/borrowck/borrowck-move-out-from-array-no-overlap-match.rs
  src/test/ui/borrowck/borrowck-move-out-from-array-no-overlap-match.stderr
  src/test/ui/borrowck/borrowck-move-out-from-array-use-match.rs
  src/test/ui/borrowck/borrowck-move-out-from-array-use-match.stderr
  src/test/ui/borrowck/borrowck-move-out-from-array-use-no-overlap-match.rs
  src/test/ui/borrowck/borrowck-move-out-from-array-use-no-overlap-match.stderr
Labels: F-slice_patterns, S-waiting-on-bors

#67986 Display more informative ICE
  src/librustc/ty/layout.rs
Labels: S-waiting-on-bors

#67966 Use matches macro in libcore and libstd
  src/libcore/cmp.rs
  src/libcore/iter/traits/iterator.rs
  src/libcore/num/mod.rs
  src/libcore/option.rs
  src/libcore/result.rs
  src/libcore/str/pattern.rs
  src/libcore/task/poll.rs
  src/libstd/net/addr.rs
  src/libstd/net/ip.rs
  src/libstd/path.rs
  src/libstd/sync/barrier.rs
  src/libstd/sync/mpsc/oneshot.rs
Labels: S-waiting-on-bors

#67884 Fix incremental builds of core by allowing unused attribute.
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#67630 Treat extern statics just like statics in the "const pointer to static" representation
  src/librustc/ty/util.rs
  src/test/mir-opt/const-promotion-extern-static.rs
Labels: I-nominated, S-waiting-on-bors, T-compiler, T-lang, beta-nominated

#68047 ci: another take at fixing toolstate
  src/ci/shared.sh
Labels: S-waiting-on-bors, merged-by-bors

#68054 doc: add Null-unchecked version section to mut pointer as_mut method
  src/libcore/ptr/mut_ptr.rs
Labels: S-waiting-on-bors

#68006 Recognise riscv64 in compiletest
  src/tools/compiletest/src/util.rs
Labels: S-waiting-on-bors

#67967 Delay bug to prevent ICE in MIR borrowck
  src/librustc_mir/transform/elaborate_drops.rs
  src/test/ui/mir/issue-67947.rs
  src/test/ui/mir/issue-67947.stderr
Labels: S-waiting-on-bors

#67935 Relax the Sized bounds on Pin::map_unchecked(_mut)
  src/libcore/pin.rs
Labels: S-waiting-on-bors

#67725 Simplify into_key_slice_mut
  src/liballoc/collections/btree/node.rs
  src/liballoc/collections/btree/search.rs
Labels: S-waiting-on-bors

#67358 Add HashSet::get_or_insert_owned
  src/libstd/collections/hash/set.rs
Labels: S-waiting-on-bors

#66254 Make Layout::new const
  src/libcore/alloc.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, needs-fcp, relnotes

#68073 expect `fn` after `const unsafe` / `const extern`
  src/librustc_parse/parser/item.rs
  src/test/ui/consts/const-extern-fn/issue-68062-const-extern-fns-dont-need-fn-specifier-2.rs
  src/test/ui/consts/const-extern-fn/issue-68062-const-extern-fns-dont-need-fn-specifier-2.stderr
  src/test/ui/consts/const-extern-fn/issue-68062-const-extern-fns-dont-need-fn-specifier.rs
  src/test/ui/consts/const-extern-fn/issue-68062-const-extern-fns-dont-need-fn-specifier.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated, stable-nominated

#68075 rustbuild: Cleanup book generation
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors

#68059 Allow specifying LLVM args in target specifications
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_target/spec/mod.rs
Labels: S-waiting-on-bors

#68039 remove explicit strip-hidden pass from compiler doc generation
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors

#68106 Fix issue with using `self` module via indirection
  src/librustc_privacy/lib.rs
  src/test/ui/issues/issue-68103.rs
Labels: S-waiting-on-bors

#68079 Clarify suggestion for E0013
  src/librustc_mir/transform/check_consts/ops.rs
  src/test/ui/consts/const-fn-not-safe-for-const.stderr
  src/test/ui/issues/issue-17718-const-bad-values.stderr
  src/test/ui/issues/issue-17718-references.stderr
  src/test/ui/issues/issue-18118-2.rs
  src/test/ui/issues/issue-18118-2.stderr
  src/test/ui/issues/issue-52060.stderr
Labels: S-waiting-on-bors

#67666 make use of pointer::is_null
  src/libpanic_unwind/emcc.rs
  src/libstd/sys/hermit/os.rs
  src/libstd/sys/hermit/thread_local.rs
  src/libstd/sys/sgx/abi/tls.rs
  src/libstd/sys/unix/os.rs
  src/libstd/sys/vxworks/os.rs
  src/libstd/sys/wasi/os.rs
  src/libstd/sys/windows/os.rs
Labels: S-waiting-on-author

#68120 Ban `...X` pats, harden tests, and improve diagnostics
  src/librustc_parse/parser/expr.rs
  src/librustc_parse/parser/pat.rs
  src/test/ui/error-codes/E0586.stderr
  src/test/ui/half-open-range-patterns/feature-gate-half-open-range-patterns.rs
  src/test/ui/half-open-range-patterns/feature-gate-half-open-range-patterns.stderr
  src/test/ui/half-open-range-patterns/half-open-range-pats-inclusive-dotdotdot-bad-syntax.rs
  src/test/ui/half-open-range-patterns/half-open-range-pats-inclusive-dotdotdot-bad-syntax.stderr
  src/test/ui/half-open-range-patterns/half-open-range-pats-inclusive-no-end.rs
  src/test/ui/half-open-range-patterns/half-open-range-pats-inclusive-no-end.stderr
  src/test/ui/half-open-range-patterns/half-open-range-pats-ref-ambiguous-interp.rs
  src/test/ui/half-open-range-patterns/half-open-range-pats-ref-ambiguous-interp.stderr
  src/test/ui/half-open-range-patterns/half-open-range-pats-syntactic-pass.rs
  src/test/ui/impossible_range.rs
  src/test/ui/impossible_range.stderr
  src/test/ui/parser/attr-stmt-expr-attr-bad.stderr
  src/test/ui/parser/range_inclusive.rs
  src/test/ui/parser/range_inclusive.stderr
  src/test/ui/parser/recover-range-pats.rs
  src/test/ui/parser/recover-range-pats.stderr
Labels: F-half_open_range_patterns, S-waiting-on-bors

#68070 clean up E0185 explanation
  src/librustc_error_codes/error_codes/E0185.md
Labels: S-waiting-on-bors

#68018 feature_gate: Remove `GateStrength`
  src/librustc_ast_passes/feature_gate.rs
  src/librustc_session/parse.rs
Labels: S-waiting-on-bors

#68108 Add suggestions when encountering chained comparisons
  src/librustc_parse/parser/diagnostics.rs
  src/librustc_parse/parser/expr.rs
  src/test/ui/did_you_mean/issue-40396.rs
  src/test/ui/did_you_mean/issue-40396.stderr
  src/test/ui/parser/chained-comparison-suggestion.rs
  src/test/ui/parser/chained-comparison-suggestion.stderr
  src/test/ui/parser/require-parens-for-chained-comparison.rs
  src/test/ui/parser/require-parens-for-chained-comparison.stderr
Labels: S-waiting-on-bors

#68089 Unstabilize `Vec::remove_item`
  src/liballoc/tests/lib.rs
  src/liballoc/vec.rs
  src/librustc/lib.rs
  src/librustdoc/lib.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors

#67948 Galloping search for binary_search_util
  src/librustc_data_structures/binary_search_util/mod.rs
Labels: S-waiting-on-bors

#67867 Correctly check for opaque types in `assoc_ty_def`
  src/librustc/traits/project.rs
  src/test/ui/type-alias-impl-trait/incoherent-assoc-imp-trait.rs
  src/test/ui/type-alias-impl-trait/incoherent-assoc-imp-trait.stderr
Labels: F-type_alias_impl_trait, S-waiting-on-bors

#67494 Constify more of alloc::Layout
  src/libcore/alloc.rs
  src/libcore/lib.rs
Labels: S-waiting-on-bors

#67831 ci: bump ubuntu 19.04 images to 19.10
  src/ci/docker/x86_64-gnu-debug/Dockerfile
  src/ci/docker/x86_64-gnu/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#68157 Clean up E0186 explanation
  src/librustc_error_codes/error_codes/E0186.md
Labels: S-waiting-on-bors

#68161 Fix system call docs for time::Instant
  src/libstd/time.rs
Labels: S-waiting-on-bors

#68156 Fix crate paths in comments
  src/librustc_feature/lib.rs
  src/librustc_lint/builtin.rs
  src/test/ui/feature-gate/issue-43106-gating-of-builtin-attrs.rs
Labels: S-waiting-on-bors

#68145 Expose `context::CheckLintNameResult`
  src/librustc_lint/lib.rs
Labels: S-waiting-on-bors

#68135 restore some rustc_parse visibilities for rustfmt
  src/librustc_parse/parser/mod.rs
  src/librustc_parse/parser/module.rs
Labels: S-waiting-on-bors

#68097 Specify units for test timeout environment variables
  src/libtest/cli.rs
Labels: S-waiting-on-bors

#67313 Document more use cases of dataflow
  src/librustc_mir/dataflow/mod.rs
Labels: S-waiting-on-bors

#68088 Don't try to force_ptr pointers to zsts
  src/librustc_mir/interpret/validity.rs
Labels: S-waiting-on-bors, merged-by-bors

#68188 Tweak assertion note in format check
  src/bootstrap/format.rs
Labels: S-waiting-on-bors

#68179 Remove unneeded scope
  src/librustdoc/clean/auto_trait.rs
Labels: S-waiting-on-bors

#68166 rustdoc: HTML escape arrows on help popup
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#68150 Document behavior of set_nonblocking on UnixListener
  src/libstd/sys/unix/ext/net.rs
Labels: S-waiting-on-bors

#68127 Clarify the relationship between `extended` and `tools` in `config.toml`
  config.toml.example
Labels: S-waiting-on-bors

#68036 libterm: parse extended terminfo format
  src/libterm/lib.rs
  src/libterm/terminfo/mod.rs
  src/libterm/terminfo/parser/compiled.rs
  src/libterm/win.rs
Labels: S-waiting-on-bors

#67989 rustdoc: Don't allow `#![feature(...)]` on stable or beta
  src/librustdoc/core.rs
Labels: S-waiting-on-bors, T-rustdoc, beta-nominated

#67854 Use `report_in_external_macro` for internal lints
  src/librustc_lint/internal.rs
  src/librustc_span/symbol.rs
Labels: S-waiting-on-bors

#67076 Stabilize Condvar::wait_while and wait_timeout_while (previously wait_until, wait_timeout_until)
  src/libstd/sync/condvar.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, needs-fcp, relnotes

#66329 Add unreachable propagation mir optimization pass
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/unreachable_prop.rs
  src/test/mir-opt/simplify_try.rs
  src/test/mir-opt/uninhabited_enum_branching.rs
  src/test/mir-opt/unreachable.rs
  src/test/mir-opt/unreachable_asm.rs
  src/test/mir-opt/unreachable_asm_2.rs
  src/test/mir-opt/unreachable_diverging.rs
Labels: S-waiting-on-bors, merged-by-bors

#68233 Update compiler_builtins with changes to fix 128 bit integer remainder for aarch64 windows.
  Cargo.lock
Labels: S-waiting-on-bors

#68231 Better support for cross compilation on Windows.
  src/bootstrap/native.rs
  src/librustc_llvm/build.rs
Labels: S-waiting-on-bors

#68230 Update libssh2-sys to a version that can build for aarch64-pc-windows…
  Cargo.lock
Labels: S-waiting-on-bors

#68229 Update iovec to a version with no winapi dependency
  Cargo.lock
Labels: S-waiting-on-bors

#68227 Update to a version of cmake with windows arm64 support
  Cargo.lock
Labels: S-waiting-on-bors

#68226 Avoid calling tcx.hir().get() on CRATE_HIR_ID
  src/librustc/infer/opaque_types/mod.rs
Labels: S-waiting-on-bors

#68222 Update the wasi-libc bundled with libstd
  src/ci/docker/dist-various-2/build-wasi-toolchain.sh
Labels: S-waiting-on-bors

#68211 Add failing example for E0170 explanation
  src/librustc_error_codes/error_codes/E0170.md
Labels: S-waiting-on-bors

#68141 use winapi for non-stdlib Windows bindings
  Cargo.lock
  src/bootstrap/Cargo.toml
  src/bootstrap/job.rs
  src/bootstrap/util.rs
  src/librustc/lib.rs
  src/librustc_data_structures/Cargo.toml
  src/librustc_data_structures/flock.rs
  src/librustc_data_structures/lib.rs
  src/librustc_data_structures/profiling.rs
  src/librustc_driver/Cargo.toml
  src/librustc_driver/lib.rs
  src/librustc_errors/Cargo.toml
  src/librustc_errors/lock.rs
  src/librustc_interface/Cargo.toml
  src/librustc_interface/util.rs
  src/librustc_metadata/Cargo.toml
  src/librustc_metadata/dynamic_lib.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#67784 Reset Formatter flags on exit from pad_integral
  src/libcore/fmt/mod.rs
  src/libcore/tests/fmt/mod.rs
Labels: S-waiting-on-bors

#68252 remove redundant clones, found by clippy
  src/librustc_driver/pretty.rs
  src/librustc_parse/parser/ty.rs
  src/librustc_resolve/imports.rs
  src/librustdoc/test.rs
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#68237 Account for `Path`s in `is_suggestable_infer_ty`
  src/librustc_typeck/collect.rs
  src/test/ui/typeck/typeck_type_placeholder_item.rs
  src/test/ui/typeck/typeck_type_placeholder_item.stderr
Labels: S-waiting-on-bors

#68123 Implement Cursor for linked lists. (RFC 2570).
  src/liballoc/collections/linked_list.rs
  src/liballoc/collections/linked_list/tests.rs
Labels: A-collections, S-waiting-on-bors, T-libs

#68223 Use 3.6 instead of 3.5 in float fract() documentation
  src/libstd/f32.rs
  src/libstd/f64.rs
Labels: S-waiting-on-bors

#68274 remove dead code
  src/librustc/traits/select.rs
Labels: S-waiting-on-bors

#68263 rustdoc: HTML escape codeblocks which fail syntax highlighting
  src/librustdoc/html/highlight.rs
  src/test/rustdoc/bad-codeblock-syntax.rs
Labels: S-waiting-on-bors

#68255 Remove unused auxiliary file that was replaced with rust_test_helpers
  src/test/ui/rfcs/rfc1717/auxiliary/clibrary.rs
Labels: S-waiting-on-bors

#68244 Enable leak sanitizer test case
  src/test/run-make-fulldeps/sanitizer-leak/Makefile
  src/test/run-make-fulldeps/sanitizer-leak/leak.rs
Labels: S-waiting-on-bors

#68033 Don't use f64 shims for f32 cmath functions on non 32-bit x86 MSVC
  src/libstd/f32.rs
  src/libstd/sys/windows/cmath.rs
Labels: S-waiting-on-bors

#67731 Handle recursive instantiation of drop shims
  src/librustc_mir/monomorphize/collector.rs
  src/test/ui/issues/issue-38591.rs
  src/test/ui/recursion/issue-26548-recursion-via-normalize.rs
  src/test/ui/recursion/issue-26548-recursion-via-normalize.stderr
  src/test/ui/recursion/issue-38591-non-regular-dropck-recursion.rs
  src/test/ui/recursion/issue-38591-non-regular-dropck-recursion.stderr
Labels: S-waiting-on-bors, merged-by-bors

#68301 Don't propagate __RUST_TEST_INVOKE to subprocess
  src/libtest/lib.rs
  src/test/ui/test-panic-abort.rs
  src/test/ui/test-panic-abort.run.stdout
Labels: S-waiting-on-bors

#68292 don't clone types that are copy
  src/librustc/infer/error_reporting/mod.rs
  src/librustc_ast_lowering/expr.rs
  src/librustc_builtin_macros/deriving/generic/mod.rs
  src/librustc_errors/annotate_snippet_emitter_writer.rs
  src/librustc_incremental/persist/save.rs
  src/librustc_lint/context.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_mir/borrow_check/borrow_set.rs
  src/librustc_mir_build/build/mod.rs
  src/librustc_passes/stability.rs
  src/librustc_traits/chalk_context/mod.rs
  src/librustc_typeck/check/closure.rs
  src/librustdoc/clean/auto_trait.rs
  src/libtest/lib.rs
Labels: S-waiting-on-bors

#67956 Detail transitive containment in E0588 diagnostic
  src/librustc_typeck/check/mod.rs
  src/test/ui/repr/repr-packed-contains-align.rs
  src/test/ui/repr/repr-packed-contains-align.stderr
Labels: S-waiting-on-bors

#68285 Array repeat expression lengths must be monomorphic at MIR building time
  src/librustc_mir_build/hair/cx/expr.rs
  src/test/ui/consts/associated_const_generic.rs
Labels: S-waiting-on-bors, merged-by-bors

#68300 Allow added string.insert benchmarks to compile
  src/liballoc/benches/string.rs
Labels: S-waiting-on-bors

#68278 [self-profiler] Add example to `-Z help` to turn on query key recording
  src/librustc_data_structures/profiling.rs
  src/librustc_session/options.rs
Labels: S-waiting-on-bors

#68317 Clean up E0199 explanation
  src/librustc_error_codes/error_codes/E0199.md
Labels: S-waiting-on-bors

#68314 Stop treating `FalseEdges` and `FalseUnwind` as having semantic value for const eval
  src/librustc_mir/transform/qualify_min_const_fn.rs
Labels: S-waiting-on-bors

#68312 Add regression test for integer literals in generic arguments in where clauses
  src/test/ui/const-generics/integer-literal-generic-arg-in-where-clause.rs
  src/test/ui/const-generics/integer-literal-generic-arg-in-where-clause.stderr
Labels: F-const_generics, S-waiting-on-bors

#68291 Update sanitizer tests
  src/test/run-make-fulldeps/sanitizer-address/Makefile
  src/test/run-make-fulldeps/sanitizer-address/overflow.rs
  src/test/run-make-fulldeps/sanitizer-invalid-target/Makefile
  src/test/run-make-fulldeps/sanitizer-invalid-target/hello.rs
  src/test/run-make-fulldeps/sanitizer-leak/Makefile
  src/test/run-make-fulldeps/sanitizer-memory/Makefile
  src/test/run-make-fulldeps/sanitizer-memory/maybeuninit.rs
  src/test/run-make-fulldeps/sanitizer-memory/uninit.rs
  src/test/ui/sanitizer-address.rs
  src/test/ui/sanitizer-leak.rs
  src/test/ui/sanitizer-memory.rs
  src/test/ui/sanitizer-unsupported-target.rs
  src/test/ui/sanitizer-unsupported-target.stderr
Labels: S-waiting-on-bors

#68279 Clean up E0198 explanation
  src/librustc_error_codes/error_codes/E0198.md
Labels: S-waiting-on-bors

#66660 Don't warn about snake case for field puns.
  src/librustc_lint/nonstandard_style.rs
  src/test/ui/lint/issue-66362-no-snake-case-warning-for-field-puns.rs
  src/test/ui/lint/issue-66362-no-snake-case-warning-for-field-puns.stderr
Labels: S-waiting-on-bors

#68037 Distribution CI for riscv64gc-unknown-linux-gnu
  src/ci/docker/dist-various-1/Dockerfile
  src/ci/docker/dist-various-1/build-riscv-toolchain.sh
  src/ci/docker/dist-various-1/crosstool-ng.sh
  src/ci/docker/dist-various-1/riscv64-unknown-linux-gnu.config
Labels: O-linux, O-riscv, S-waiting-on-bors, T-infra, merged-by-bors, relnotes

#68170 Turn off const propagation of ref taking
  src/librustc_mir/transform/const_prop.rs
  src/test/mir-opt/const_prop/ref_deref_project.rs
  src/test/ui/consts/issue-67529.rs
  src/test/ui/consts/issue-67640.rs
  src/test/ui/consts/issue-67641.rs
  src/test/ui/consts/issue-67862.rs
Labels: S-waiting-on-bors, merged-by-bors

#68001 perf: Only search potentially changed constraints in lexical_region_resolve
  src/librustc/infer/lexical_region_resolve/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#68342 improve type_name_of_val docs
  src/libcore/any.rs
Labels: S-waiting-on-bors

#68340 clean up e0200 explanation
  src/librustc_error_codes/error_codes/E0200.md
Labels: S-waiting-on-bors

#68341 Fix syscalls tables in docs of std::time.
  src/libstd/time.rs
Labels: S-waiting-on-bors

#67758 More thorough testing of BTreeMap::range
  src/liballoc/tests/btree/map.rs
Labels: S-waiting-on-bors, merged-by-bors

#67682 [const-prop] Remove useless typedef
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-author

#68057 Don't discard marker trait impls when inference variables are present
  src/librustc/traits/select.rs
  src/librustc/traits/specialize/specialization_graph.rs
  src/librustc/ty/mod.rs
  src/test/ui/marker_trait_attr/issue-61651-type-mismatch.rs
Labels: F-marker_trait_attr, S-waiting-on-bors, merged-by-bors

#68357 rustdoc: Fix handling of compile errors when running `rustdoc --test`
  src/librustdoc/test.rs
  src/test/rustdoc-ui/test-compile-fail1.rs
  src/test/rustdoc-ui/test-compile-fail1.stderr
  src/test/rustdoc-ui/test-compile-fail2.rs
  src/test/rustdoc-ui/test-compile-fail2.stderr
  src/test/rustdoc-ui/test-compile-fail3.rs
  src/test/rustdoc-ui/test-compile-fail3.stderr
  src/test/rustdoc-ui/test-no_std.rs
  src/test/rustdoc-ui/test-no_std.stdout
Labels: S-waiting-on-bors

#68326 rustdoc: Catch fatal errors when syntax highlighting
  src/librustdoc/html/highlight.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/invalid-syntax.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
  src/test/rustdoc/bad-codeblock-syntax.rs
Labels: S-waiting-on-bors

#68066 Stabilize ManuallyDrop::take
  src/libcore/mem/manually_drop.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors, relnotes

#68397 rustdoc: Correct order of `async` and `unsafe` in `async unsafe fn`s
  src/librustdoc/html/render.rs
  src/test/rustdoc/async-fn.rs
Labels: S-waiting-on-bors

#68381 Added minor clarification to specification of GlobalAlloc::realloc.
  src/libcore/alloc.rs
Labels: S-waiting-on-bors

#68339 Add `riscv64gc-unknown-linux-gnu` into target list in build-manifest
  src/tools/build-manifest/src/main.rs
Labels: O-riscv, S-waiting-on-bors, T-infra
