Repository rust-lang/rust, pull requests merged in 2020-07, with the labels that each got.

#73706 Serialize all foreign `SourceFile`s into proc-macro crate metadata
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_metadata/rmeta/encoder.rs
  src/librustc_metadata/rmeta/mod.rs
  src/librustc_span/hygiene.rs
  src/librustc_span/source_map.rs
  src/test/ui/hygiene/unpretty-debug.stdout
  src/test/ui/proc-macro/auxiliary/make-macro.rs
  src/test/ui/proc-macro/auxiliary/meta-macro.rs
  src/test/ui/proc-macro/disappearing-resolution.stderr
  src/test/ui/proc-macro/meta-macro-hygiene.rs
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
  src/test/ui/proc-macro/meta-macro.rs
  src/test/ui/proc-macro/meta-macro.stdout
Labels: S-waiting-on-bors, merged-by-bors

#73863 Revert "ci: allow gating gha on everything but macOS"
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
Labels: S-waiting-on-bors, merged-by-bors

#73847 Edit cursor.prev() method docs in lexer
  src/librustc_lexer/src/cursor.rs
Labels: S-waiting-on-bors

#73846 Fix comma in debug_assert! docs
  src/libcore/macros/mod.rs
Labels: S-waiting-on-bors

#73828 Fix wording for anonymous parameter name help
  src/librustc_parse/parser/diagnostics.rs
  src/test/ui/anon-params/anon-params-denied-2018.stderr
  src/test/ui/parser/inverted-parameters.rs
  src/test/ui/parser/inverted-parameters.stderr
  src/test/ui/parser/omitted-arg-in-item-fn.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-2018.stderr
  src/test/ui/span/issue-34264.stderr
Labels: S-waiting-on-bors

#73806 Use an 'approximate' universal upper bound when reporting region errors
  src/librustc_mir/borrow_check/diagnostics/region_errors.rs
  src/librustc_mir/borrow_check/region_infer/mod.rs
  src/librustc_mir/borrow_check/region_infer/opaque_types.rs
  src/test/ui/async-await/issue-67765-async-diagnostic.rs
  src/test/ui/async-await/issue-67765-async-diagnostic.stderr
  src/test/ui/lifetimes/unnamed-closure-doesnt-life-long-enough-issue-67634.rs
  src/test/ui/lifetimes/unnamed-closure-doesnt-life-long-enough-issue-67634.stderr
  src/test/ui/return-disjoint-regions.rs
  src/test/ui/return-disjoint-regions.stderr
Labels: S-waiting-on-bors

#73805 Document the type keyword
  src/libstd/keyword_docs.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#73778 Make `likely` and `unlikely` const, gated by feature `const_unlikely`
  src/libcore/intrinsics.rs
  src/libcore/lib.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_span/symbol.rs
Labels: S-waiting-on-bors, T-lang

#73776 Move terminator to new module
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/terminator/mod.rs
Labels: S-waiting-on-bors

#73752 Remap Windows ERROR_INVALID_PARAMETER to ErrorKind::InvalidInput from Other
  src/libstd/sys/windows/mod.rs
Labels: S-waiting-on-bors

#73716 Document the static keyword
  src/libstd/keyword_docs.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#73705 stop taking references in Relate
  src/librustc_infer/infer/at.rs
  src/librustc_infer/infer/canonical/query_response.rs
  src/librustc_infer/infer/combine.rs
  src/librustc_infer/infer/equate.rs
  src/librustc_infer/infer/glb.rs
  src/librustc_infer/infer/higher_ranked/mod.rs
  src/librustc_infer/infer/lub.rs
  src/librustc_infer/infer/nll_relate/mod.rs
  src/librustc_infer/infer/sub.rs
  src/librustc_lint/builtin.rs
  src/librustc_middle/ich/impls_ty.rs
  src/librustc_middle/ty/_match.rs
  src/librustc_middle/ty/error.rs
  src/librustc_middle/ty/flags.rs
  src/librustc_middle/ty/fold.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_middle/ty/print/pretty.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_middle/ty/structural_impls.rs
  src/librustc_middle/ty/sty.rs
  src/librustc_middle/ty/walk.rs
  src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs
  src/librustc_mir/borrow_check/type_check/relate_tys.rs
  src/librustc_mir/transform/validate.rs
  src/librustc_passes/intrinsicck.rs
  src/librustc_privacy/lib.rs
  src/librustc_symbol_mangling/v0.rs
  src/librustc_trait_selection/opaque_types.rs
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/error_reporting/on_unimplemented.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/confirmation.rs
  src/librustc_trait_selection/traits/select/mod.rs
  src/librustc_trait_selection/traits/wf.rs
  src/librustc_traits/chalk/lowering.rs
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/check/closure.rs
  src/librustc_typeck/check/coercion.rs
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/check/dropck.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/op.rs
  src/librustc_typeck/coherence/mod.rs
  src/librustc_typeck/collect.rs
  src/librustdoc/clean/mod.rs
Labels: S-waiting-on-bors

#73678 Update Box::from_raw example to generalize better
  src/liballoc/boxed.rs
Labels: S-waiting-on-bors

#73649 Fix sentence structure
  README.md
Labels: S-waiting-on-bors

#73548 remove rustdoc warnings
  src/librustc_mir_build/hair/pattern/_match.rs
Labels: S-waiting-on-bors

#73466 impl From<char> for String
  src/liballoc/string.rs
  src/liballoc/tests/string.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, final-comment-period, relnotes

#72445 Stabilize `#[track_caller]`.
  src/doc/unstable-book/src/language-features/track-caller.md
  src/libcore/lib.rs
  src/libcore/macros/mod.rs
  src/libcore/panic.rs
  src/librustc_error_codes/error_codes/E0736.md
  src/librustc_error_codes/error_codes/E0737.md
  src/librustc_error_codes/error_codes/E0739.md
  src/librustc_errors/lib.rs
  src/librustc_feature/accepted.rs
  src/librustc_feature/active.rs
  src/librustc_feature/builtin_attrs.rs
  src/librustc_middle/lib.rs
  src/libstd/lib.rs
  src/test/ui/asm/sym.rs
  src/test/ui/feature-gates/feature-gate-track_caller.rs
  src/test/ui/feature-gates/feature-gate-track_caller.stderr
  src/test/ui/macros/issue-68060.rs
  src/test/ui/macros/issue-68060.stderr
  src/test/ui/numbers-arithmetic/saturating-float-casts.rs
  src/test/ui/rfc-2091-track-caller/call-chain.rs
  src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.rs
  src/test/ui/rfc-2091-track-caller/caller-location-intrinsic.rs
  src/test/ui/rfc-2091-track-caller/const-caller-location.rs
  src/test/ui/rfc-2091-track-caller/diverging-caller-location.rs
  src/test/ui/rfc-2091-track-caller/error-odd-syntax.rs
  src/test/ui/rfc-2091-track-caller/error-odd-syntax.stderr
  src/test/ui/rfc-2091-track-caller/error-with-invalid-abi.rs
  src/test/ui/rfc-2091-track-caller/error-with-invalid-abi.stderr
  src/test/ui/rfc-2091-track-caller/error-with-naked.rs
  src/test/ui/rfc-2091-track-caller/intrinsic-wrapper.rs
  src/test/ui/rfc-2091-track-caller/only-for-fns.rs
  src/test/ui/rfc-2091-track-caller/only-for-fns.stderr
  src/test/ui/rfc-2091-track-caller/pass.rs
  src/test/ui/rfc-2091-track-caller/track-caller-attribute.rs
  src/test/ui/rfc-2091-track-caller/track-caller-ffi.rs
  src/test/ui/rfc-2091-track-caller/tracked-fn-ptr-with-arg.rs
  src/test/ui/rfc-2091-track-caller/tracked-fn-ptr.rs
  src/test/ui/rfc-2091-track-caller/tracked-trait-impls.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#72369 Bring net/parser.rs up to modern up to date with modern rust patterns
  src/libstd/net/parser.rs
Labels: S-waiting-on-bors, libs-impl

#72071 Added detailed error code explanation for issue E0687 in Rust compiler.
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0687.md
  src/test/ui/in-band-lifetimes/E0687.stderr
  src/test/ui/in-band-lifetimes/E0687_where.stderr
Labels: S-waiting-on-bors

#72053 Test UI tests for pass=check
  src/ci/docker/x86_64-gnu-llvm-8/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#73929 Fix comment typo
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#73909 `#[deny(unsafe_op_in_unsafe_fn)]` in libstd/fs.rs
  src/libstd/fs.rs
  src/libstd/lib.rs
Labels: S-waiting-on-bors

#73910 Rewrite a few manual index loops with while-let
  src/librustc_data_structures/obligation_forest/mod.rs
  src/librustc_data_structures/transitive_relation.rs
Labels: S-waiting-on-bors

#73906 Add missing backtick in `ty_error_with_message`
  src/librustc_middle/ty/context.rs
Labels: S-waiting-on-bors

#73898 remove duplicate test for #61935
  src/test/ui/const-generics/lazy-normalization/issue-71922.rs
  src/test/ui/const-generics/lazy-normalization/issue-71922.stderr
Labels: S-waiting-on-bors

#73892 Clean up E0712 explanation
  src/librustc_error_codes/error_codes/E0712.md
Labels: S-waiting-on-bors

#73865 Fix Zulip topic format
  triagebot.toml
Labels: S-waiting-on-bors

#73848 Fix markdown rendering in librustc_lexer docs
  src/librustc_lexer/src/lib.rs
Labels: S-waiting-on-bors

#73841 Remove defunct `-Z print-region-graph`
  src/librustc_interface/tests.rs
  src/librustc_session/options.rs
Labels: S-waiting-on-bors

#73839 Split and expand nonstandard-style lints unicode unit test.
  src/test/ui/lint/lint-nonstandard-style-unicode-1.rs
  src/test/ui/lint/lint-nonstandard-style-unicode-1.stderr
  src/test/ui/lint/lint-nonstandard-style-unicode-2.rs
  src/test/ui/lint/lint-nonstandard-style-unicode-2.stderr
  src/test/ui/lint/lint-nonstandard-style-unicode-3.rs
  src/test/ui/lint/lint-nonstandard-style-unicode-3.stderr
  src/test/ui/lint/lint-nonstandard-style-unicode.rs
Labels: F-non_ascii_idents, S-waiting-on-bors

#73803 Recover extra trailing angle brackets in struct definition
  src/librustc_parse/parser/diagnostics.rs
  src/librustc_parse/parser/expr.rs
  src/librustc_parse/parser/item.rs
  src/librustc_parse/parser/path.rs
  src/test/ui/parser/recover-field-extra-angle-brackets.rs
  src/test/ui/parser/recover-field-extra-angle-brackets.stderr
Labels: S-waiting-on-bors

#73569 Handle `macro_rules!` tokens consistently across crates
  src/librustc_ast/attr/mod.rs
  src/librustc_ast_lowering/lib.rs
  src/librustc_ast_pretty/pprust.rs
  src/librustc_expand/mbe/macro_rules.rs
  src/librustc_expand/mbe/quoted.rs
  src/librustc_middle/ty/context.rs
  src/test/ui/macros/doc-comment.rs
  src/test/ui/proc-macro/auxiliary/meta-delim.rs
  src/test/ui/proc-macro/auxiliary/nested-macro-rules.rs
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/input-interpolated.stdout
  src/test/ui/proc-macro/meta-delim.rs
  src/test/ui/proc-macro/nested-macro-rules.rs
  src/test/ui/proc-macro/nested-macro-rules.stdout
  src/test/ui/proc-macro/nodelim-groups.rs
  src/test/ui/proc-macro/nodelim-groups.stdout
  src/test/ui/unsafe/ranged_ints_macro.rs
Labels: S-waiting-on-bors

#73449 Provide more information on duplicate lang item error.
  src/librustc_metadata/rmeta/decoder/cstore_impl.rs
  src/librustc_middle/query/mod.rs
  src/librustc_middle/ty/query/mod.rs
  src/librustc_passes/lang_items.rs
  src/test/ui/duplicate_entry_error.rs
  src/test/ui/duplicate_entry_error.stderr
  src/test/ui/error-codes/E0152.rs
  src/test/ui/error-codes/E0152.stderr
  src/test/ui/panic-handler/panic-handler-std.rs
  src/test/ui/panic-handler/panic-handler-std.stderr
Labels: S-waiting-on-bors

#73345 expand: Stop using nonterminals for passing tokens to attribute and derive macros
  src/librustc_ast/attr/mod.rs
  src/librustc_ast/mut_visit.rs
  src/librustc_ast/token.rs
  src/librustc_ast/util/literal.rs
  src/librustc_ast_lowering/lib.rs
  src/librustc_ast_pretty/pprust.rs
  src/librustc_expand/base.rs
  src/librustc_expand/expand.rs
  src/librustc_expand/mbe/macro_parser.rs
  src/librustc_expand/mbe/transcribe.rs
  src/librustc_expand/proc_macro.rs
  src/librustc_expand/proc_macro_server.rs
  src/librustc_parse/parser/attr.rs
  src/librustc_parse/parser/expr.rs
  src/librustc_parse/parser/item.rs
  src/librustc_parse/parser/mod.rs
  src/librustc_parse/parser/pat.rs
  src/librustc_resolve/build_reduced_graph.rs
  src/librustc_resolve/def_collector.rs
  src/librustc_span/symbol.rs
  src/test/run-make/rustc-macro-dep-files/foo.rs
  src/test/ui/async-await/issues/issue-60674.stdout
  src/test/ui/proc-macro/auxiliary/attr-cfg.rs
  src/test/ui/proc-macro/auxiliary/attr-stmt-expr-rpass.rs
  src/test/ui/proc-macro/auxiliary/attr-stmt-expr.rs
  src/test/ui/proc-macro/auxiliary/derive-a.rs
  src/test/ui/proc-macro/auxiliary/derive-atob.rs
  src/test/ui/proc-macro/auxiliary/derive-b-rpass.rs
  src/test/ui/proc-macro/auxiliary/derive-ctod.rs
  src/test/ui/proc-macro/auxiliary/derive-same-struct.rs
  src/test/ui/proc-macro/auxiliary/derive-union.rs
  src/test/ui/proc-macro/auxiliary/double.rs
  src/test/ui/proc-macro/auxiliary/expand-with-a-macro.rs
  src/test/ui/proc-macro/derive-same-struct.stdout
  src/test/ui/proc-macro/dollar-crate-issue-57089.stdout
  src/test/ui/proc-macro/dollar-crate-issue-62325.stdout
  src/test/ui/proc-macro/dollar-crate.stdout
  src/test/ui/proc-macro/input-interpolated.stdout
  src/test/ui/rfc-2565-param-attrs/auxiliary/param-attrs.rs
Labels: S-waiting-on-bors

#73306 Don't implement Fn* traits for #[target_feature] functions
  src/librustc_trait_selection/traits/error_reporting/mod.rs
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/fn-traits.rs
  src/test/ui/rfcs/rfc-2396-target_feature-11/fn-traits.stderr
Labels: S-waiting-on-bors, T-lang

#72569 Remove legacy InnoSetup GUI installer
  .github/workflows/ci.yml
  src/bootstrap/dist.rs
  src/ci/azure-pipelines/steps/run.yml
  src/ci/github-actions/ci.yml
  src/ci/scripts/install-innosetup.sh
  src/etc/installer/exe/modpath.iss
  src/etc/installer/exe/rust.iss
  src/etc/installer/exe/upgrade.iss
Labels: O-windows, S-waiting-on-bors, T-release, relnotes

#73938 Optimise fast path of checked_ops with `unlikely`
  src/libcore/num/mod.rs
Labels: S-waiting-on-bors

#73885 Fix wasm32 being broken due to a NodeJS version bump
  src/ci/docker/wasm32/Dockerfile
Labels: S-waiting-on-bors

#73883 Compile rustdoc less often.
  src/bootstrap/builder/tests.rs
  src/bootstrap/doc.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors

#73853 Add newline to rustc MultiSpan docs
  src/librustc_span/lib.rs
Labels: S-waiting-on-bors

#73812 ast_pretty: Pass some token streams and trees by reference
  src/librustc_ast_pretty/pprust.rs
  src/librustc_builtin_macros/log_syntax.rs
  src/librustc_builtin_macros/source_util.rs
  src/librustc_expand/mbe/macro_rules.rs
  src/librustc_expand/proc_macro_server.rs
Labels: S-waiting-on-bors

#73684 add spans to injected coverage counters, extract with CoverageData query
  src/libcore/intrinsics.rs
  src/librustc_codegen_llvm/base.rs
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_llvm/coverageinfo/mod.rs
  src/librustc_codegen_llvm/intrinsic.rs
  src/librustc_codegen_llvm/lib.rs
  src/librustc_codegen_ssa/coverageinfo/map.rs
  src/librustc_codegen_ssa/coverageinfo/mod.rs
  src/librustc_codegen_ssa/lib.rs
  src/librustc_codegen_ssa/mir/block.rs
  src/librustc_codegen_ssa/traits/builder.rs
  src/librustc_codegen_ssa/traits/coverageinfo.rs
  src/librustc_codegen_ssa/traits/intrinsic.rs
  src/librustc_codegen_ssa/traits/mod.rs
  src/librustc_index/vec.rs
  src/librustc_middle/mir/coverage/mod.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_middle/mir/query.rs
  src/librustc_middle/query/mod.rs
  src/librustc_mir/interpret/intrinsics.rs
  src/librustc_mir/transform/inline.rs
  src/librustc_mir/transform/instrument_coverage.rs
  src/librustc_session/options.rs
  src/librustc_span/symbol.rs
  src/librustc_typeck/check/intrinsic.rs
  src/test/mir-opt/instrument_coverage/rustc.bar.InstrumentCoverage.diff
  src/test/mir-opt/instrument_coverage/rustc.main.InstrumentCoverage.diff
Labels: S-waiting-on-bors

#73622 Deny unsafe ops in unsafe fns in libcore
  src/libcore/alloc/global.rs
  src/libcore/alloc/layout.rs
  src/libcore/alloc/mod.rs
  src/libcore/cell.rs
  src/libcore/char/convert.rs
  src/libcore/char/methods.rs
  src/libcore/convert/num.rs
  src/libcore/ffi.rs
  src/libcore/future/mod.rs
  src/libcore/hash/sip.rs
  src/libcore/hint.rs
  src/libcore/intrinsics.rs
  src/libcore/iter/adapters/fuse.rs
  src/libcore/iter/adapters/mod.rs
  src/libcore/iter/adapters/zip.rs
  src/libcore/iter/range.rs
  src/libcore/lib.rs
  src/libcore/mem/manually_drop.rs
  src/libcore/mem/maybe_uninit.rs
  src/libcore/mem/mod.rs
  src/libcore/num/f32.rs
  src/libcore/num/f64.rs
  src/libcore/num/mod.rs
  src/libcore/pin.rs
  src/libcore/ptr/const_ptr.rs
  src/libcore/ptr/mod.rs
  src/libcore/ptr/mut_ptr.rs
  src/libcore/ptr/non_null.rs
  src/libcore/ptr/unique.rs
  src/libcore/slice/mod.rs
  src/libcore/slice/rotate.rs
  src/libcore/str/mod.rs
  src/libcore/sync/atomic.rs
  src/libcore/tests/lib.rs
  src/test/ui/consts/miri_unleashed/drop.stderr
  src/test/ui/consts/offset_from_ub.stderr
  src/test/ui/consts/offset_ub.stderr
  src/test/ui/recursion/issue-38591-non-regular-dropck-recursion.stderr
Labels: S-waiting-on-bors

#73564 linker: Create GNU_EH_FRAME header by default when producing ELFs
  src/librustc_codegen_ssa/back/link.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_target/spec/cloudabi_base.rs
  src/librustc_target/spec/fuchsia_base.rs
  src/librustc_target/spec/linux_musl_base.rs
  src/librustc_target/spec/mipsel_sony_psp.rs
  src/librustc_target/spec/x86_64_fortanix_unknown_sgx.rs
Labels: S-waiting-on-bors

#73414 Implement `slice_strip` feature
  src/libcore/slice/mod.rs
Labels: S-waiting-on-bors, T-libs

#73751 Remove `TypeckTables::empty(None)` and make hir_owner non-optional.
  src/librustc_driver/lib.rs
  src/librustc_driver/pretty.rs
  src/librustc_infer/infer/error_reporting/mod.rs
  src/librustc_infer/infer/mod.rs
  src/librustc_lint/builtin.rs
  src/librustc_lint/context.rs
  src/librustc_lint/late.rs
  src/librustc_lint/lib.rs
  src/librustc_lint/unused.rs
  src/librustc_middle/ty/context.rs
  src/librustc_passes/dead.rs
  src/librustc_passes/lib.rs
  src/librustc_passes/reachable.rs
  src/librustc_privacy/lib.rs
  src/librustc_save_analysis/dump_visitor.rs
  src/librustc_save_analysis/lib.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/method/suggest.rs
  src/librustc_typeck/check/mod.rs
  src/librustc_typeck/check/writeback.rs
  src/tools/clippy/clippy_lints/src/atomic_ordering.rs
  src/tools/clippy/clippy_lints/src/copies.rs
  src/tools/clippy/clippy_lints/src/default_trait_access.rs
  src/tools/clippy/clippy_lints/src/eval_order_dependence.rs
  src/tools/clippy/clippy_lints/src/format.rs
  src/tools/clippy/clippy_lints/src/implicit_return.rs
  src/tools/clippy/clippy_lints/src/let_and_return.rs
  src/tools/clippy/clippy_lints/src/lifetimes.rs
  src/tools/clippy/clippy_lints/src/map_unit_fn.rs
  src/tools/clippy/clippy_lints/src/mem_discriminant.rs
  src/tools/clippy/clippy_lints/src/mem_replace.rs
  src/tools/clippy/clippy_lints/src/methods/mod.rs
  src/tools/clippy/clippy_lints/src/methods/unnecessary_filter_map.rs
  src/tools/clippy/clippy_lints/src/misc.rs
  src/tools/clippy/clippy_lints/src/question_mark.rs
  src/tools/clippy/clippy_lints/src/regex.rs
  src/tools/clippy/clippy_lints/src/temporary_assignment.rs
  src/tools/clippy/clippy_lints/src/to_digit_is_some.rs
  src/tools/clippy/clippy_lints/src/trait_bounds.rs
  src/tools/clippy/clippy_lints/src/transmute.rs
  src/tools/clippy/clippy_lints/src/types.rs
  src/tools/clippy/clippy_lints/src/unnamed_address.rs
  src/tools/clippy/clippy_lints/src/useless_conversion.rs
  src/tools/clippy/clippy_lints/src/utils/higher.rs
  src/tools/clippy/clippy_lints/src/utils/hir_utils.rs
  src/tools/clippy/clippy_lints/src/utils/internal_lints.rs
  src/tools/clippy/clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#73975 Document rustc_ast::ast::Pat
  src/librustc_ast/ast.rs
Labels: S-waiting-on-bors

#73957 disable BTree min_max test in Miri for now
  src/liballoc/tests/btree/map.rs
Labels: S-waiting-on-bors

#73952 Add option for local docker testing.
  src/ci/docker/run.sh
Labels: S-waiting-on-bors

#73781 Update psm version
  Cargo.lock
Labels: S-waiting-on-bors

#73454 Move contributing.md to rustc-dev-guide and point at getting started
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-bors

#73882 Avoid `unwrap_or_else` in `RawVec::allocate_in`.
  src/liballoc/raw_vec.rs
Labels: S-waiting-on-bors, merged-by-bors

#74019 Rollup of 12 pull requests
  CONTRIBUTING.md
  README.md
  src/ci/docker/host-x86_64/mingw-check/Dockerfile
  src/doc/unstable-book/src/library-features/format-args-capture.md
  src/etc/htmldocck.py
  src/liballoc/lib.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
  src/libcore/marker.rs
  src/librustc_ast_pretty/pp.rs
  src/librustc_builtin_macros/format.rs
  src/librustc_data_structures/graph/dominators/mod.rs
  src/librustc_data_structures/graph/scc/mod.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0768.md
  src/librustc_feature/active.rs
  src/librustc_middle/mir/mod.rs
  src/librustc_mir/transform/const_prop.rs
  src/librustc_mir/transform/simplify_try.rs
  src/librustc_parse/lexer/mod.rs
  src/librustc_parse_format/lib.rs
  src/librustc_span/hygiene.rs
  src/librustc_span/symbol.rs
  src/libstd/panicking.rs
  src/test/mir-opt/issue-73223.rs
  src/test/mir-opt/issue-73223/32bit/rustc.main.PreCodegen.diff
  src/test/mir-opt/issue-73223/32bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/issue-73223/64bit/rustc.main.PreCodegen.diff
  src/test/mir-opt/issue-73223/64bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/32bit/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/64bit/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyBranchSame.after.mir
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyLocals.after.mir
  src/test/ui/fmt/feature-gate-format-args-capture.rs
  src/test/ui/fmt/feature-gate-format-args-capture.stderr
  src/test/ui/fmt/format-args-capture-macro-hygiene.rs
  src/test/ui/fmt/format-args-capture-macro-hygiene.stderr
  src/test/ui/fmt/format-args-capture-missing-variables.rs
  src/test/ui/fmt/format-args-capture-missing-variables.stderr
  src/test/ui/fmt/format-args-capture.rs
  src/test/ui/if/ifmt-bad-arg.stderr
  src/test/ui/parser/issue-1802-1.stderr
  src/test/ui/parser/issue-1802-2.stderr
  src/test/ui/parser/lex-bad-numeric-literals.stderr
Labels: S-waiting-on-author, merged-by-bors, rollup

#73999 Bump mingw-check CI image from Ubuntu 16.04 to 18.04.
  src/ci/docker/mingw-check/Dockerfile
Labels: S-waiting-on-author

#73997 fix typo
  src/libcore/marker.rs
Labels: S-waiting-on-bors

#73985 Fix "getting started" link
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-bors

#73984 Edit docs for rustc_data_structures::graph::scc
  src/librustc_data_structures/graph/scc/mod.rs
Labels: S-waiting-on-bors

#73949 [mir-opt] Fix mis-optimization and other issues with the SimplifyArmIdentity pass
  src/librustc_middle/mir/mod.rs
  src/librustc_mir/transform/simplify_try.rs
  src/test/mir-opt/issue-73223.rs
  src/test/mir-opt/issue-73223/32bit/rustc.main.PreCodegen.diff
  src/test/mir-opt/issue-73223/32bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/issue-73223/64bit/rustc.main.PreCodegen.diff
  src/test/mir-opt/issue-73223/64bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/32bit/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/64bit/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyBranchSame.after.mir
  src/test/mir-opt/simplify_try/rustc.try_identity.SimplifyLocals.after.mir
Labels: S-waiting-on-bors

#73925 Improve comments from #72617, as suggested by RalfJung
  src/libstd/panicking.rs
Labels: S-waiting-on-bors

#73881 Standardize bibliographic citations in rustc API docs
  src/librustc_ast_pretty/pp.rs
  src/librustc_data_structures/graph/dominators/mod.rs
  src/librustc_span/hygiene.rs
Labels: S-waiting-on-bors

#73861 Create E0768
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0768.md
  src/librustc_parse/lexer/mod.rs
  src/test/ui/parser/issue-1802-1.stderr
  src/test/ui/parser/issue-1802-2.stderr
  src/test/ui/parser/lex-bad-numeric-literals.stderr
Labels: S-waiting-on-bors

#73845 Use &raw in A|Rc::as_ptr
  src/liballoc/lib.rs
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#73693 Use exhaustive match in const_prop.rs
  src/librustc_mir/transform/const_prop.rs
Labels: S-waiting-on-bors

#73670 Add `format_args_capture` feature
  src/doc/unstable-book/src/library-features/format-args-capture.md
  src/librustc_builtin_macros/format.rs
  src/librustc_feature/active.rs
  src/librustc_parse_format/lib.rs
  src/librustc_span/symbol.rs
  src/test/ui/fmt/feature-gate-format-args-capture.rs
  src/test/ui/fmt/feature-gate-format-args-capture.stderr
  src/test/ui/fmt/format-args-capture-macro-hygiene.rs
  src/test/ui/fmt/format-args-capture-macro-hygiene.stderr
  src/test/ui/fmt/format-args-capture-missing-variables.rs
  src/test/ui/fmt/format-args-capture-missing-variables.stderr
  src/test/ui/fmt/format-args-capture.rs
  src/test/ui/if/ifmt-bad-arg.stderr
Labels: S-waiting-on-bors

#73140 Fallback to xml.etree.ElementTree
  src/etc/htmldocck.py
Labels: S-waiting-on-bors

#73879 Handle inactive enum variants in `MaybeUninitializedPlaces`
  src/librustc_mir/dataflow/drop_flag_effects.rs
  src/librustc_mir/dataflow/impls/mod.rs
  src/librustc_mir/transform/elaborate_drops.rs
  src/test/mir-opt/no-drop-for-inactive-variant/rustc.unwrap.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/32bit/rustc.map.SimplifyLocals.diff
  src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/64bit/rustc.map.SimplifyLocals.diff
Labels: S-waiting-on-bors, merged-by-bors

#74064 variant_count: avoid incorrect dummy implementation
  src/libcore/intrinsics.rs
  src/libcore/lib.rs
  src/libcore/mem/mod.rs
Labels: S-waiting-on-bors

#74057 expected_found `&T` -> `T`
  src/librustc_infer/infer/combine.rs
  src/librustc_middle/ty/relate.rs
Labels: S-waiting-on-bors

#74055 Fix spacing in Iterator fold doc
  src/libcore/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#74027 Convert more `DefId`s to `LocalDefId`s
  src/librustc_mir/borrow_check/type_check/input_output.rs
  src/librustc_mir/borrow_check/type_check/mod.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/transform/check_consts/mod.rs
  src/librustc_mir/transform/check_consts/post_drop_elaboration.rs
  src/librustc_mir/transform/check_consts/qualifs.rs
  src/librustc_mir/transform/check_consts/validation.rs
  src/librustc_mir/transform/mod.rs
  src/librustc_mir/transform/promote_consts.rs
  src/librustc_trait_selection/opaque_types.rs
  src/librustc_typeck/check/mod.rs
Labels: S-waiting-on-bors

#74025 Remove unnecessary release from Arc::try_unwrap
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#74000 add `lazy_normalization_consts` feature gate
  src/librustc_feature/active.rs
  src/librustc_middle/ty/context.rs
  src/librustc_span/symbol.rs
  src/test/ui/const-generics/issue-71986.rs
  src/test/ui/lazy_normalization_consts/feature-gate-lazy_normalization_consts.rs
  src/test/ui/lazy_normalization_consts/feature-gate-lazy_normalization_consts.stderr
  src/test/ui/lazy_normalization_consts/issue-47814.rs
  src/test/ui/lazy_normalization_consts/issue-57739.rs
  src/test/ui/lazy_normalization_consts/issue-57739.stderr
  src/test/ui/lazy_normalization_consts/issue-73980.rs
Labels: S-waiting-on-bors

#73973 Use `Span`s to identify unreachable subpatterns in or-patterns
  src/librustc_mir_build/hair/pattern/_match.rs
  src/librustc_mir_build/hair/pattern/check_match.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.stderr
  src/test/ui/or-patterns/search-via-bindings.rs
Labels: S-waiting-on-bors

#73871 Fix try_print_visible_def_path for Rust 2018
  src/librustc_middle/ty/print/pretty.rs
  src/test/ui/issues/auxiliary/reexported-trait.rs
  src/test/ui/issues/issue-56175.rs
  src/test/ui/issues/issue-56175.stderr
Labels: S-waiting-on-bors

#73834 Some refactoring around intrinsic type checking
  src/librustc_span/symbol.rs
  src/librustc_typeck/check/intrinsic.rs
  src/librustc_typeck/collect.rs
  src/test/ui/mir-dataflow/def-inits-1.rs
  src/test/ui/mir-dataflow/def-inits-1.stderr
  src/test/ui/mir-dataflow/indirect-mutation-offset.rs
  src/test/ui/mir-dataflow/indirect-mutation-offset.stderr
  src/test/ui/mir-dataflow/inits-1.rs
  src/test/ui/mir-dataflow/inits-1.stderr
  src/test/ui/mir-dataflow/liveness-ptr.rs
  src/test/ui/mir-dataflow/liveness-ptr.stderr
  src/test/ui/mir-dataflow/uninits-1.rs
  src/test/ui/mir-dataflow/uninits-1.stderr
  src/test/ui/mir-dataflow/uninits-2.rs
  src/test/ui/mir-dataflow/uninits-2.stderr
Labels: S-waiting-on-bors

#73787 Add unstable docs for rustc_attrs
  src/doc/unstable-book/src/language-features/rustc-attrs.md
Labels: S-waiting-on-bors

#72688 added .collect() into String from Box<str>
  src/liballoc/string.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period

#73978 Shrink ParamEnv to 16 bytes
  src/librustc_infer/infer/outlives/mod.rs
  src/librustc_infer/infer/outlives/verify.rs
  src/librustc_infer/traits/mod.rs
  src/librustc_middle/ty/layout.rs
  src/librustc_middle/ty/mod.rs
  src/librustc_middle/ty/structural_impls.rs
  src/librustc_mir/const_eval/eval_queries.rs
  src/librustc_mir/util/elaborate_drops.rs
  src/librustc_trait_selection/traits/auto_trait.rs
  src/librustc_trait_selection/traits/chalk_fulfill.rs
  src/librustc_trait_selection/traits/fulfill.rs
  src/librustc_trait_selection/traits/mod.rs
  src/librustc_trait_selection/traits/object_safety.rs
  src/librustc_trait_selection/traits/project.rs
  src/librustc_trait_selection/traits/query/normalize.rs
  src/librustc_trait_selection/traits/select/candidate_assembly.rs
  src/librustc_trait_selection/traits/select/mod.rs
  src/librustc_trait_selection/traits/specialize/mod.rs
  src/librustc_ty/instance.rs
  src/librustc_typeck/check/compare_method.rs
  src/librustc_typeck/check/method/probe.rs
  src/librustc_typeck/check/mod.rs
  src/librustdoc/clean/auto_trait.rs
  src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs
Labels: S-waiting-on-bors, merged-by-bors

#74112 Expand abbreviation in core::ffi description
  src/libcore/ffi.rs
Labels: S-waiting-on-bors

#74102 Fix const prop ICE
  src/librustc_mir/transform/const_prop.rs
  src/test/ui/const_prop/ice-assert-fail-div-by-zero.rs
Labels: S-waiting-on-bors

#74090 Remove unused RUSTC_DEBUG_ASSERTIONS
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#74089 Add rust-analyzer to the build manifest
  src/tools/build-manifest/README.md
  src/tools/build-manifest/src/main.rs
Labels: S-waiting-on-bors

#74078 Always resolve type@primitive as a primitive, not a module
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-link-prim-precedence.rs
Labels: S-waiting-on-bors

#74074 Fix the return type of Windows' `OpenOptionsExt::security_qos_flags`.
  src/libstd/sys/windows/ext/fs.rs
Labels: S-waiting-on-bors

#74067 rustdoc: Restore underline text decoration on hover for FQN in header
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#73974 Move A|Rc::as_ptr from feature(weak_into_raw) to feature(rc_as_ptr)
  src/liballoc/rc.rs
  src/liballoc/sync.rs
Labels: S-waiting-on-bors

#73969 mir: mark mir construction temporaries as internal
  src/librustc_mir_build/build/misc.rs
  src/test/ui/issue-73914.rs
Labels: S-waiting-on-bors

#73962 libstd/net/tcp.rs: #![deny(unsafe_op_in_unsafe_fn)]
  src/libstd/net/tcp.rs
Labels: S-waiting-on-bors

#73870 typeck: adding type information to projection
  src/librustc_typeck/check/regionck.rs
  src/librustc_typeck/expr_use_visitor.rs
  src/librustc_typeck/mem_categorization.rs
  src/tools/clippy/clippy_lints/src/escape.rs
Labels: S-waiting-on-bors

#73856 Edit librustc_lexer top-level docs
  src/librustc_lexer/src/lib.rs
Labels: S-waiting-on-bors

#70563 [rustdoc] Page hash handling
  src/bootstrap/bin/rustdoc.rs
  src/bootstrap/doc.rs
  src/librustdoc/config.rs
  src/librustdoc/html/item_type.rs
  src/librustdoc/html/render.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/libstd/sys/unix/ext/fs.rs
  src/libstd/sys/vxworks/ext/fs.rs
  src/test/rustdoc/assoc-types.rs
  src/test/rustdoc/const.rs
  src/test/rustdoc/inline_cross/impl_trait.rs
  src/test/rustdoc/intra-link-self.rs
  src/test/rustdoc/intra-links.rs
  src/test/rustdoc/issue-19190.rs
  src/test/rustdoc/issue-25001.rs
  src/test/rustdoc/issue-35169-2.rs
  src/test/rustdoc/issue-35169.rs
  src/test/rustdoc/struct-field.rs
  src/test/rustdoc/structfields.rs
Labels: S-waiting-on-author, T-rustdoc

#73562 Update E0432 long description with the separate behaviors of editions 2015 and 2018
  src/librustc_error_codes/error_codes/E0432.md
Labels: A-resolve, C-bug, S-waiting-on-bors, T-compiler, T-doc, merged-by-bors

#74059 Miri value validation: fix handling of uninit memory
  src/librustc_mir/interpret/validity.rs
  src/librustc_mir/interpret/visitor.rs
  src/test/ui/consts/const-eval/double_check2.stderr
  src/test/ui/consts/const-eval/ub-enum.stderr
  src/test/ui/consts/const-eval/union-ub.rs
  src/test/ui/consts/const-eval/union-ub.stderr
Labels: S-waiting-on-bors, merged-by-bors

#74006 libstd: remove some mutable statics in sys::unix
  src/libstd/sys/unix/args.rs
  src/libstd/sys/unix/stack_overflow.rs
  src/libstd/sys/unix/thread.rs
Labels: S-waiting-on-bors, libs-impl, merged-by-bors

#74124 Fix occasional bootstrap panic in docs.
  src/bootstrap/doc.rs
Labels: S-waiting-on-bors, merged-by-bors

#74153 Fix x.py test for librustc crates.
  src/bootstrap/test.rs
  src/librustc_errors/json/tests.rs
Labels: S-waiting-on-bors, merged-by-bors

#74131 rustdoc: Rename invalid_codeblock_attribute lint to be plural
  src/librustc_lint/lib.rs
  src/librustc_session/lint/builtin.rs
  src/librustdoc/core.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/test.rs
  src/test/rustdoc-ui/check-attr-test.rs
  src/test/rustdoc-ui/check-attr-test.stderr
  src/test/rustdoc-ui/check-attr.rs
  src/test/rustdoc-ui/check-attr.stderr
Labels: S-waiting-on-bors, T-rustdoc, beta-nominated, merged-by-bors

#74188 Tweak `::` -> `:` typo heuristic and reduce verbosity
  src/librustc_parse/parser/diagnostics.rs
  src/librustc_resolve/diagnostics.rs
  src/test/ui/lifetime_starts_expressions.stderr
  src/test/ui/parser/issue-35813-postfix-after-cast.stderr
  src/test/ui/suggestions/type-ascription-instead-of-method.stderr
  src/test/ui/suggestions/type-ascription-instead-of-path-2.stderr
  src/test/ui/suggestions/type-ascription-instead-of-variant.stderr
  src/test/ui/type/ascription/issue-47666.stderr
  src/test/ui/type/ascription/issue-54516.stderr
  src/test/ui/type/ascription/issue-60933.stderr
Labels: S-waiting-on-bors

#74184 Add docs for intra-doc-links
  src/doc/rustdoc/src/unstable-features.md
Labels: S-waiting-on-bors

#74143 Try remove unneeded ToString import in liballoc slice
  src/liballoc/slice.rs
Labels: S-waiting-on-bors

#74142 Liballoc use vec instead of vector
  src/liballoc/slice.rs
Labels: S-waiting-on-bors, libs-impl

#74136 Fix broken link in rustdocdoc
  src/doc/rustdoc/src/unstable-features.md
Labels: S-waiting-on-bors

#74107 Hide `&mut self` methods from Deref in sidebar if there are no `DerefMut` impl for the type.
  src/librustdoc/html/render.rs
  src/test/rustdoc/issue-74083.rs
Labels: S-waiting-on-bors

#74079 Eliminate confusing "globals" terminology.
  src/librustc_ast/attr/mod.rs
  src/librustc_ast/lib.rs
  src/librustc_ast/util/lev_distance/tests.rs
  src/librustc_ast_pretty/pprust/tests.rs
  src/librustc_errors/json/tests.rs
  src/librustc_expand/mut_visit/tests.rs
  src/librustc_expand/parse/lexer/tests.rs
  src/librustc_expand/parse/tests.rs
  src/librustc_expand/tests.rs
  src/librustc_expand/tokenstream/tests.rs
  src/librustc_interface/interface.rs
  src/librustc_interface/tests.rs
  src/librustc_interface/util.rs
  src/librustc_middle/ty/query/job.rs
  src/librustc_parse_format/tests.rs
  src/librustc_span/hygiene.rs
  src/librustc_span/lib.rs
  src/librustc_span/span_encoding.rs
  src/librustc_span/symbol.rs
  src/librustc_span/symbol/tests.rs
  src/librustdoc/clean/cfg/tests.rs
  src/librustdoc/test.rs
  src/test/ui-fulldeps/mod_dir_path_canonicalized.rs
  src/test/ui-fulldeps/pprust-expr-roundtrip.rs
  src/tools/error_index_generator/main.rs
Labels: S-waiting-on-bors

#73791 Allow for parentheses after macro intra-doc-links
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-links.rs
Labels: S-waiting-on-bors

#73292 Fixing broken link for the Eq trait
  src/libcore/cmp.rs
Labels: S-waiting-on-bors, T-doc

#74181 Gate GHA on everything but macOS
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
Labels: S-waiting-on-bors, merged-by-bors

#74162 take self by value in ToPredicate
  src/librustc_middle/ty/mod.rs
Labels: S-waiting-on-bors

#74161 Fix disabled dockerfiles
  src/ci/docker/host-x86_64/disabled/riscv64gc-linux/Dockerfile
  src/ci/docker/run.sh
Labels: S-waiting-on-bors

#74127 Avoid "whitelist"
  src/bootstrap/doc.rs
  src/etc/test-float-parse/runtests.py
  src/libcore/ffi.rs
  src/librustc_codegen_llvm/attributes.rs
  src/librustc_codegen_llvm/back/lto.rs
  src/librustc_codegen_llvm/llvm_util.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/librustc_codegen_ssa/base.rs
  src/librustc_expand/base.rs
  src/librustc_feature/builtin_attrs.rs
  src/librustc_incremental/persist/dirty_clean.rs
  src/librustc_interface/util.rs
  src/librustc_lint/unused.rs
  src/librustc_metadata/rmeta/decoder.rs
  src/librustc_middle/lint.rs
  src/librustc_middle/middle/lang_items.rs
  src/librustc_middle/query/mod.rs
  src/librustc_mir/const_eval/fn_queries.rs
  src/librustc_mir/interpret/validity.rs
  src/librustc_passes/weak_lang_items.rs
  src/librustc_resolve/late/lifetimes.rs
  src/librustc_target/spec/tests/tests_impl.rs
  src/librustc_target/spec/wasm32_base.rs
  src/librustc_trait_selection/traits/error_reporting/suggestions.rs
  src/librustc_typeck/check/demand.rs
  src/librustc_typeck/check/expr.rs
  src/librustc_typeck/collect.rs
  src/librustdoc/core.rs
  src/librustdoc/html/render.rs
  src/librustdoc/test.rs
  src/libstd/time.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
  src/test/run-make-fulldeps/sysroot-crates-are-unstable/test.py
  src/test/ui-fulldeps/auxiliary/issue-40001-plugin.rs
  src/test/ui-fulldeps/issue-40001.rs
  src/test/ui/asm/type-check-3.rs
  src/test/ui/rfc-2126-extern-absolute-paths/meta.rs
  src/test/ui/rfc-2126-extern-absolute-paths/not-allowed.rs
  src/test/ui/rfc-2126-extern-absolute-paths/not-allowed.stderr
  src/test/ui/sse2.rs
  src/tools/clippy/clippy_lints/src/attrs.rs
  src/tools/clippy/clippy_lints/src/eq_op.rs
  src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs
  src/tools/clippy/clippy_lints/src/non_expressive_names.rs
  src/tools/clippy/clippy_lints/src/precedence.rs
  src/tools/clippy/clippy_lints/src/types.rs
  src/tools/clippy/tests/ui/crashes/third-party/clippy.toml
  src/tools/clippy/tests/ui/crashes/third-party/conf_allowlisted.rs
  src/tools/clippy/tests/ui/needless_pass_by_value.rs
  src/tools/clippy/tests/ui/neg_cmp_op_on_partial_ord.rs
  src/tools/linkchecker/main.rs
  src/tools/tidy/src/cargo.rs
  src/tools/tidy/src/deps.rs
  src/tools/tidy/src/error_codes_check.rs
  src/tools/tidy/src/extdeps.rs
Labels: S-waiting-on-bors, T-compiler

#74125 Correctly mark the ending span of a match arm
  src/librustc_parse/parser/expr.rs
  src/test/mir-opt/exponential-or/rustc.match_tuple.SimplifyCfg-initial.after.mir
  src/test/mir-opt/issue-73223/32bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/issue-73223/64bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.ElaborateDrops.after.mir
  src/test/mir-opt/match-arm-scopes/rustc.complicated_match.SimplifyCfg-initial.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match.PromoteTemps.after.mir
  src/test/mir-opt/match_false_edges/rustc.full_tested_match2.PromoteTemps.before.mir
  src/test/mir-opt/match_false_edges/rustc.main.PromoteTemps.before.mir
  src/test/mir-opt/match_test/rustc.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/no-drop-for-inactive-variant/rustc.unwrap.SimplifyCfg-elaborate-drops.after.mir
  src/test/mir-opt/remove_fake_borrows/rustc.match_guard.CleanupNonCodegenStatements.diff
  src/test/mir-opt/simplify-arm-identity/32bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-arm-identity/64bit/rustc.main.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-arm/rustc.id.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-arm/rustc.id.SimplifyBranchSame.diff
  src/test/mir-opt/simplify-arm/rustc.id_result.SimplifyArmIdentity.diff
  src/test/mir-opt/simplify-arm/rustc.id_result.SimplifyBranchSame.diff
  src/test/mir-opt/simplify_try_if_let/rustc.{{impl}}-append.SimplifyArmIdentity.diff
  src/test/ui/match/issue-74050-end-span.rs
  src/test/ui/match/issue-74050-end-span.stderr
Labels: S-waiting-on-bors

#74122 Start-up clean-up
  src/librustc_interface/interface.rs
  src/librustc_interface/util.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
Labels: S-waiting-on-bors

#74109 Only allow `repr(i128/u128)` on enum
  src/librustc_passes/check_attr.rs
  src/test/ui/issues/issue-74082.rs
  src/test/ui/issues/issue-74082.stderr
Labels: S-waiting-on-bors, relnotes

#74103 Only add CFGuard on `windows-msvc` targets
  src/librustc_codegen_llvm/context.rs
  src/librustc_codegen_ssa/back/linker.rs
  src/test/codegen/cfguard-checks.rs
  src/test/codegen/cfguard-disabled.rs
  src/test/codegen/cfguard-nochecks.rs
  src/test/codegen/cfguard-non-msvc.rs
  src/test/ui/cfguard-run.rs
Labels: S-waiting-on-bors

#74100 Use str::strip* in bootstrap
  src/bootstrap/compile.rs
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#74099 Add VecDeque::range* methods
  src/liballoc/collections/vec_deque.rs
  src/liballoc/collections/vec_deque/tests.rs
  src/liballoc/lib.rs
Labels: S-waiting-on-bors, T-libs

#74076 Add `read_exact_at` and `write_all_at` to WASI's `FileExt`
  src/libstd/sys/wasi/ext/fs.rs
Labels: S-waiting-on-review

#74045 Explain effects of debugging options from config.toml
  config.toml.example
Labels: S-waiting-on-bors

#73989 adjust ub-enum test to be endianess-independent
  src/test/ui/consts/const-eval/ub-enum.rs
  src/test/ui/consts/const-eval/ub-enum.stderr
Labels: S-waiting-on-bors

#73887 stabilize const mem::forget
  src/libcore/mem/mod.rs
  src/libcore/tests/lib.rs
  src/test/ui/consts/const_forget.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#73862 Stabilize casts and coercions to `&[T]` in const fn
  src/librustc_middle/ty/layout.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/test/ui/consts/array-to-slice-cast.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.stderr
  src/test/ui/consts/min_const_fn/cast_errors.rs
  src/test/ui/consts/min_const_fn/cast_errors.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#72303 Add core::future::{poll_fn, PollFn}
  src/libcore/future/mod.rs
  src/libcore/future/poll_fn.rs
Labels: S-waiting-on-bors, T-libs

#71322 Accept tuple.0.0 as tuple indexing (take 2)
  src/librustc_parse/parser/expr.rs
  src/test/ui/parser/float-field-interpolated.rs
  src/test/ui/parser/float-field-interpolated.stderr
  src/test/ui/parser/float-field.rs
  src/test/ui/parser/float-field.stderr
  src/test/ui/tuple/index-float.rs
  src/test/ui/tuple/index-invalid.rs
  src/test/ui/tuple/index-invalid.stderr
  src/test/ui/tuple/indexing-in-macro.rs
  src/test/ui/tuple/nested-index.rs
  src/test/ui/tuple/tuple-float-index.fixed
  src/test/ui/tuple/tuple-float-index.rs
  src/test/ui/tuple/tuple-float-index.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#74240 Fix #74081 and add the test case from #74236
  src/librustc_middle/ty/print/pretty.rs
  src/test/ui/issues/issue-74236/auxiliary/dep.rs
  src/test/ui/issues/issue-74236/main.rs
  src/test/ui/issues/issue-74236/main.stderr
Labels: S-waiting-on-bors

#74213 Minor refactor for rustc_resolve diagnostics match
  src/librustc_resolve/late/diagnostics.rs
Labels: S-waiting-on-bors

#74197 Reword incorrect `self` token suggestion
  src/librustc_resolve/late/diagnostics.rs
  src/test/ui/self/suggest-self.stderr
Labels: S-waiting-on-bors

#74167 linker: illumos ld does not support --eh-frame-hdr
  src/librustc_codegen_ssa/back/linker.rs
Labels: S-waiting-on-bors

#74168 Add a help to use `in_band_lifetimes` in nightly
  src/librustc_resolve/late/diagnostics.rs
  src/test/ui/error-codes/E0261.stderr
  src/test/ui/feature-gates/feature-gate-in_band_lifetimes.stderr
  src/test/ui/generic-associated-types/generic_associated_type_undeclared_lifetimes.stderr
  src/test/ui/methods/method-call-lifetime-args-unresolved.stderr
  src/test/ui/regions/regions-in-enums.stderr
  src/test/ui/regions/regions-in-structs.stderr
  src/test/ui/regions/regions-name-undeclared.stderr
  src/test/ui/regions/regions-undeclared.stderr
  src/test/ui/where-clauses/where-lifetime-resolution.stderr
Labels: S-waiting-on-bors

#74066 Optimize is_ascii for str and [u8].
  src/libcore/benches/ascii.rs
  src/libcore/benches/ascii/is_ascii.rs
  src/libcore/slice/mod.rs
  src/libcore/str/mod.rs
  src/libcore/tests/ascii.rs
Labels: S-waiting-on-bors

#73715 debuginfo: Mangle tuples to be natvis friendly, typedef basic types
  src/etc/natvis/intrinsic.natvis
  src/librustc_codegen_llvm/debuginfo/metadata.rs
  src/librustc_codegen_llvm/llvm/ffi.rs
  src/librustc_codegen_ssa/debuginfo/type_names.rs
  src/rustllvm/RustWrapper.cpp
  src/test/debuginfo/simple-tuple.rs
  src/test/debuginfo/tuple-in-tuple.rs
Labels: O-windows, S-waiting-on-bors

#72920 Stabilize `transmute` in constants and statics but not const fn
  src/libcore/intrinsics.rs
  src/libcore/lib.rs
  src/librustc_ast/lib.rs
  src/librustc_feature/active.rs
  src/librustc_middle/lib.rs
  src/librustc_mir/transform/qualify_min_const_fn.rs
  src/librustc_span/symbol.rs
  src/test/ui/consts/const-eval/dangling.rs
  src/test/ui/consts/const-eval/double_check.rs
  src/test/ui/consts/const-eval/double_check2.rs
  src/test/ui/consts/const-eval/double_check2.stderr
  src/test/ui/consts/const-eval/issue-55541.rs
  src/test/ui/consts/const-eval/transmute-const.rs
  src/test/ui/consts/const-eval/transmute-const.stderr
  src/test/ui/consts/const-eval/ub-enum.rs
  src/test/ui/consts/const-eval/ub-int-array.rs
  src/test/ui/consts/const-eval/ub-int-array.stderr
  src/test/ui/consts/const-eval/ub-nonnull.rs
  src/test/ui/consts/const-eval/ub-ref.rs
  src/test/ui/consts/const-eval/ub-ref.stderr
  src/test/ui/consts/const-eval/ub-uninhabit.rs
  src/test/ui/consts/const-eval/ub-uninhabit.stderr
  src/test/ui/consts/const-eval/ub-upvars.rs
  src/test/ui/consts/const-eval/ub-upvars.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.stderr
  src/test/ui/consts/const-eval/valid-const.rs
  src/test/ui/consts/const-eval/validate_uninhabited_zsts.rs
  src/test/ui/consts/consts-in-patterns.rs
  src/test/ui/consts/miri_unleashed/abi-mismatch.stderr
  src/test/ui/consts/miri_unleashed/ptr_arith.stderr
  src/test/ui/consts/transmute-const.rs
  src/test/ui/feature-gates/feature-gate-const_fn_transmute.rs
  src/test/ui/feature-gates/feature-gate-const_fn_transmute.stderr
  src/test/ui/feature-gates/feature-gate-const_transmute.rs
  src/test/ui/feature-gates/feature-gate-const_transmute.stderr
  src/test/ui/internal/internal-unstable-const.rs
  src/test/ui/internal/internal-unstable-const.stderr
  src/tools/clippy/tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, relnotes

#74219 [beta] next
  src/bootstrap/bin/rustc.rs
  src/ci/docker/wasm32/Dockerfile
  src/librustc_lexer/src/lib.rs
  src/librustc_lint/lib.rs
  src/librustc_middle/ty/relate.rs
  src/librustc_mir/monomorphize/partitioning.rs
  src/librustc_session/lint/builtin.rs
  src/librustc_target/spec/windows_gnu_base.rs
  src/librustdoc/core.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/test.rs
  src/test/codegen-units/partitioning/compiler-builtins.rs
  src/test/rustdoc-js/doc-alias-filter-out.js
  src/test/rustdoc-js/doc-alias-filter-out.rs
  src/test/rustdoc-js/doc-alias-filter.js
  src/test/rustdoc-js/doc-alias-filter.rs
  src/test/rustdoc-ui/check-attr-test.rs
  src/test/rustdoc-ui/check-attr-test.stderr
  src/test/rustdoc-ui/check-attr.rs
  src/test/rustdoc-ui/check-attr.stderr
  src/test/ui/issues/issue-59326.rs
  src/test/ui/parser/shebang/shebang-empty.rs
  src/test/ui/parser/shebang/shebang-space.rs
  src/test/ui/shebang.rs
  src/tools/rustdoc-js/tester.js
Labels: S-waiting-on-bors, merged-by-bors

#74297 [stable] 1.45 release
  RELEASES.md
  src/ci/run.sh
Labels: S-waiting-on-bors, merged-by-bors

#74313 Rollup of 8 pull requests
  RELEASES.md
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0688.md
  src/librustc_error_codes/error_codes/E0718.md
  src/librustdoc/html/render.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/libstd/keyword_docs.rs
  src/test/codegen/intrinsics/nearby.rs
  src/test/codegen/intrinsics/volatile.rs
  src/test/codegen/intrinsics/volatile_order.rs
  src/test/rustdoc-ui/issue-74134.public.stderr
  src/test/rustdoc-ui/issue-74134.rs
  src/test/rustdoc/attributes.rs
  src/test/ui/in-band-lifetimes/E0688.stderr
  src/test/ui/intrinsics/intrinsic-nearby.rs
  src/test/ui/intrinsics/intrinsic-volatile.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#74286 Added detailed error code explanation for issue E0688 in Rust compiler.
  src/librustc_error_codes/error_codes.rs
  src/librustc_error_codes/error_codes/E0688.md
  src/test/ui/in-band-lifetimes/E0688.stderr
Labels: S-waiting-on-bors

#74285 #71669: add ui, codegen tests for volatile + nearby int intrinsics
  src/test/codegen/intrinsics/nearby.rs
  src/test/codegen/intrinsics/volatile.rs
  src/test/codegen/intrinsics/volatile_order.rs
  src/test/ui/intrinsics/intrinsic-nearby.rs
  src/test/ui/intrinsics/intrinsic-volatile.rs
Labels: S-waiting-on-bors

#74147 rustdoc: Allow linking from private items to private types
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/issue-74134.public.stderr
  src/test/rustdoc-ui/issue-74134.rs
Labels: S-waiting-on-bors

#74123 clean up E0718 explanation
  src/librustc_error_codes/error_codes/E0718.md
Labels: S-waiting-on-bors

#74046 Fix caching issue when building tools.
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors

#73867 Document the union keyword
  src/libstd/keyword_docs.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#73852 rustdoc: insert newlines between attributes
  src/librustdoc/html/render.rs
  src/test/rustdoc/attributes.rs
Labels: S-waiting-on-bors

#73354 Update RELEASES.md for 1.45.0
  RELEASES.md
Labels: S-waiting-on-bors, T-release

#73490 Use step_unchecked more liberally in range iter impls
  src/libcore/iter/range.rs
Labels: S-waiting-on-bors, libs-impl, merged-by-bors

#74316 Remove unnecessary type hints from Wake internals
  src/liballoc/task.rs
Labels: S-waiting-on-bors

#74310 Use `ArrayVec` in `SparseBitSet`.
  Cargo.lock
  src/librustc_index/Cargo.toml
  src/librustc_index/bit_set.rs
Labels: S-waiting-on-bors

#74296 Clarify the description for rfind
  src/libcore/str/mod.rs
Labels: S-waiting-on-bors

#74270 typeck: report placeholder type error w/out span
  src/librustc_typeck/astconv.rs
  src/librustc_typeck/collect.rs
  src/test/ui/issues/issue-74086.rs
  src/test/ui/issues/issue-74086.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.rs
  src/test/ui/typeck/typeck_type_placeholder_item.stderr
Labels: S-waiting-on-bors

#74257 don't mark linux kernel module targets as a unix environment
  src/librustc_target/spec/linux_kernel_base.rs
Labels: S-waiting-on-bors

#74227 Remove an unwrap in layout computation
  src/librustc_middle/ty/layout.rs
Labels: S-waiting-on-bors

#74220 Refactor Windows `parse_prefix`
  src/libstd/lib.rs
  src/libstd/sys/windows/path.rs
  src/libstd/sys/windows/path/tests.rs
  src/libstd/thread/mod.rs
Labels: S-waiting-on-author
