Repository rust-lang/rust, pull requests merged in 2021-03, with the labels that each got.

#82601 Fixed support for macOS Catalyst on ARM64
  compiler/rustc_target/src/spec/aarch64_apple_ios_macabi.rs
Labels: S-waiting-on-bors, merged-by-bors

#81094 BTreeMap: split up range_search into two stages
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/node.rs
  library/alloc/src/collections/btree/node/tests.rs
  library/alloc/src/collections/btree/search.rs
  library/alloc/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#82440 BTree: no longer define impossible casts
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, merged-by-bors

#82507 Rename the `tidy` binary to `rust-tidy`
  src/bootstrap/tool.rs
  src/tools/tidy/Cargo.toml
Labels: A-contributor-roadblock, A-testsuite, S-waiting-on-bors

#82531 Add GUI tests
  src/test/rustdoc-gui/search-input-mobile.goml
  src/test/rustdoc-gui/shortcuts.goml
Labels: A-testsuite, S-waiting-on-bors, T-rustdoc

#82532 Add `build.print_step_rusage` to config.toml
  config.toml.example
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
Labels: A-rustbuild, S-waiting-on-bors

#82543 fix env var name in CI
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
Labels: S-waiting-on-bors

#82622 Propagate `--test-args` for `x.py test src/tools/cargo`
  src/bootstrap/test.rs
Labels: A-rustbuild, A-testsuite, S-waiting-on-bors

#82628 Try to clarify GlobalAlloc::realloc documentation comment.
  library/core/src/alloc/global.rs
Labels: S-waiting-on-bors

#82630 Fix a typo in the `find_anon_type` doc
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/find_anon_type.rs
Labels: S-waiting-on-bors

#82643 Add more proc-macro attribute tests
  src/test/ui/proc-macro/attr-complex-fn.rs
  src/test/ui/proc-macro/attr-complex-fn.stdout
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/expand-to-derive.rs
  src/test/ui/proc-macro/expand-to-derive.stdout
  src/test/ui/proc-macro/inner-attrs.rs
  src/test/ui/proc-macro/inner-attrs.stdout
  src/test/ui/proc-macro/issue-75930-derive-cfg.rs
  src/test/ui/proc-macro/issue-75930-derive-cfg.stderr
  src/test/ui/proc-macro/issue-75930-derive-cfg.stdout
  src/test/ui/proc-macro/macro-rules-derive-cfg.rs
  src/test/ui/proc-macro/macro-rules-derive-cfg.stdout
  src/test/ui/proc-macro/nested-derive-cfg.rs
  src/test/ui/proc-macro/nested-derive-cfg.stdout
  src/test/ui/proc-macro/weird-braces.rs
  src/test/ui/proc-macro/weird-braces.stdout
Labels: S-waiting-on-bors

#82654 Rollup of 10 pull requests
  .github/workflows/ci.yml
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/find_anon_type.rs
  config.toml.example
  library/core/src/alloc/global.rs
  src/bootstrap/bin/rustc.rs
  src/bootstrap/builder.rs
  src/bootstrap/config.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/ci/github-actions/ci.yml
  src/test/rustdoc-gui/search-input-mobile.goml
  src/test/rustdoc-gui/shortcuts.goml
  src/test/ui/proc-macro/attr-complex-fn.rs
  src/test/ui/proc-macro/attr-complex-fn.stdout
  src/test/ui/proc-macro/auxiliary/test-macros.rs
  src/test/ui/proc-macro/expand-to-derive.rs
  src/test/ui/proc-macro/expand-to-derive.stdout
  src/test/ui/proc-macro/inner-attrs.rs
  src/test/ui/proc-macro/inner-attrs.stdout
  src/test/ui/proc-macro/issue-75930-derive-cfg.rs
  src/test/ui/proc-macro/issue-75930-derive-cfg.stderr
  src/test/ui/proc-macro/issue-75930-derive-cfg.stdout
  src/test/ui/proc-macro/macro-rules-derive-cfg.rs
  src/test/ui/proc-macro/macro-rules-derive-cfg.stdout
  src/test/ui/proc-macro/nested-derive-cfg.rs
  src/test/ui/proc-macro/nested-derive-cfg.stdout
  src/test/ui/proc-macro/weird-braces.rs
  src/test/ui/proc-macro/weird-braces.stdout
  src/tools/tidy/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82309 Propagate RUSTDOCFLAGS in the environment when documenting
  src/bootstrap/builder.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#82403 rustbuild: print out env vars on verbose rustc invocations
  src/bootstrap/bin/rustc.rs
Labels: A-rustbuild, S-waiting-on-bors

#78360 Remove storage markers if they won't be used during code generation
  compiler/rustc_mir/src/transform/mod.rs
  compiler/rustc_mir/src/transform/remove_storage_markers.rs
  src/test/codegen/try_identity.rs
  src/test/mir-opt/remove_storage_markers.main.RemoveStorageMarkers.diff
  src/test/mir-opt/remove_storage_markers.rs
  src/test/run-make/const_fn_mir/dump.mir
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, merged-by-bors

#82587 Enable report_in_external_macro in unaligned_references
  compiler/rustc_lint_defs/src/builtin.rs
  src/test/ui/lint/auxiliary/unaligned_references_external_crate.rs
  src/test/ui/lint/unaligned_references_external_macro.rs
  src/test/ui/lint/unaligned_references_external_macro.stderr
Labels: S-waiting-on-bors, merged-by-bors

#82578 Add some diagnostic items for Clippy
  compiler/rustc_span/src/symbol.rs
  library/alloc/src/collections/binary_heap.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/linked_list.rs
  library/std/src/sync/mpsc/mod.rs
  src/tools/clippy/clippy_lints/src/entry.rs
  src/tools/clippy/clippy_lints/src/loops.rs
  src/tools/clippy/clippy_lints/src/methods/mod.rs
  src/tools/clippy/clippy_lints/src/swap.rs
  src/tools/clippy/clippy_lints/src/types.rs
  src/tools/clippy/clippy_lints/src/zero_sized_map_values.rs
  src/tools/clippy/clippy_utils/src/eager_or_lazy.rs
  src/tools/clippy/clippy_utils/src/lib.rs
  src/tools/clippy/clippy_utils/src/paths.rs
Labels: S-waiting-on-bors

#82620 Apply lint restrictions from renamed lints
  compiler/rustc_lint/src/levels.rs
  src/test/ui/lint/renamed-lints-still-apply.rs
  src/test/ui/lint/renamed-lints-still-apply.stderr
Labels: A-lint, S-waiting-on-bors, T-compiler

#82635 Fix typos in rustc_infer::infer::nll_relate
  compiler/rustc_infer/src/infer/nll_relate/mod.rs
Labels: S-waiting-on-bors

#82645 Clarify that SyncOnceCell::set blocks.
  library/std/src/lazy.rs
Labels: S-waiting-on-bors

#82663 Rollup of 8 pull requests
  Cargo.lock
  compiler/rustc_infer/src/infer/nll_relate/mod.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_span/src/symbol.rs
  config.toml.example
  library/alloc/benches/btree/map.rs
  library/alloc/src/collections/binary_heap.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/node/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/linked_list.rs
  library/std/src/lazy.rs
  library/std/src/sync/mpsc/mod.rs
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/tool.rs
  src/test/ui/lint/renamed-lints-still-apply.rs
  src/test/ui/lint/renamed-lints-still-apply.stderr
  src/tools/clippy/clippy_lints/src/entry.rs
  src/tools/clippy/clippy_lints/src/loops.rs
  src/tools/clippy/clippy_lints/src/methods/mod.rs
  src/tools/clippy/clippy_lints/src/swap.rs
  src/tools/clippy/clippy_lints/src/types.rs
  src/tools/clippy/clippy_lints/src/zero_sized_map_values.rs
  src/tools/clippy/clippy_utils/src/eager_or_lazy.rs
  src/tools/clippy/clippy_utils/src/lib.rs
  src/tools/clippy/clippy_utils/src/paths.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82360 config.toml parsing error improvements
  config.toml.example
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#82428 Update mdbook
  Cargo.lock
Labels: S-waiting-on-bors

#82480 Remove `ENABLE_DOWNLOAD_RUSTC` constant
  src/bootstrap/builder.rs
  src/bootstrap/check.rs
  src/bootstrap/compile.rs
  src/bootstrap/tool.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors, T-dev-tools

#81210 BTreeMap: correct node size test case for choices of B
  library/alloc/benches/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/node/tests.rs
Labels: S-waiting-on-bors

#82598 Check stability and feature attributes in rustdoc
  library/std/src/os/mod.rs
  library/std/src/sys/mod.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/test/rustdoc-ui/rustc-check-passes.rs
  src/test/rustdoc-ui/rustc-check-passes.stderr
  src/test/rustdoc/implementor-stable-version.rs
Labels: S-waiting-on-bors, T-rustdoc

#82655 Highlight identifier span instead of whole pattern span in `unused` lint
  compiler/rustc_passes/src/liveness.rs
  src/test/ui/lint/issue-47390-unused-variable-in-struct-pattern.stderr
  src/test/ui/lint/issue-81314-unused-span-ident.fixed
  src/test/ui/lint/issue-81314-unused-span-ident.rs
  src/test/ui/lint/issue-81314-unused-span-ident.stderr
  src/test/ui/liveness/liveness-consts.stderr
  src/test/ui/liveness/liveness-dead.stderr
  src/test/ui/liveness/liveness-unused.stderr
Labels: S-waiting-on-bors

#82662 Warn about unknown doc attributes
  compiler/rustc_passes/src/check_attr.rs
  src/test/rustdoc-ui/doc-attr.rs
  src/test/rustdoc-ui/doc-attr.stderr
  src/test/ui/attributes/doc-attr.rs
  src/test/ui/attributes/doc-attr.stderr
Labels: S-waiting-on-bors, T-rustdoc

#82676 Change twice used large const table to static
  library/core/src/num/dec2flt/table.rs
  src/etc/dec2flt_table.py
Labels: S-waiting-on-bors

#82688 Rollup of 7 pull requests
  Cargo.lock
  compiler/rustc_mir/src/transform/check_consts/ops.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_passes/src/liveness.rs
  library/core/src/num/dec2flt/table.rs
  library/std/src/os/mod.rs
  library/std/src/sys/mod.rs
  src/etc/dec2flt_table.py
  src/librustdoc/Cargo.toml
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/visit_ast.rs
  src/librustdoc/visit_lib.rs
  src/test/rustdoc-json/nested.rs
  src/test/rustdoc-ui/deprecated-attrs.rs
  src/test/rustdoc-ui/doc-attr.rs
  src/test/rustdoc-ui/doc-attr.stderr
  src/test/rustdoc-ui/rustc-check-passes.rs
  src/test/rustdoc-ui/rustc-check-passes.stderr
  src/test/rustdoc/implementor-stable-version.rs
  src/test/ui/attributes/doc-attr.rs
  src/test/ui/attributes/doc-attr.stderr
  src/test/ui/consts/issue-66693-panic-in-array-len.rs
  src/test/ui/consts/issue-66693-panic-in-array-len.stderr
  src/test/ui/consts/issue-66693.rs
  src/test/ui/consts/issue-66693.stderr
  src/test/ui/consts/issue-76064.rs
  src/test/ui/consts/issue-76064.stderr
  src/test/ui/lint/issue-47390-unused-variable-in-struct-pattern.stderr
  src/test/ui/lint/issue-81314-unused-span-ident.fixed
  src/test/ui/lint/issue-81314-unused-span-ident.rs
  src/test/ui/lint/issue-81314-unused-span-ident.stderr
  src/test/ui/liveness/liveness-consts.stderr
  src/test/ui/liveness/liveness-dead.stderr
  src/test/ui/liveness/liveness-unused.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82018 Remove the dummy cache in `DocContext`; delete RenderInfo
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/visit_ast.rs
  src/librustdoc/visit_lib.rs
  src/test/rustdoc-json/nested.rs
Labels: S-waiting-on-bors, T-rustdoc

#81932 Always compile rustdoc with debug logging enabled when `download-rustc` is set
  Cargo.lock
  src/librustdoc/Cargo.toml
  src/librustdoc/lib.rs
  src/test/rustdoc-ui/deprecated-attrs.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors, T-rustdoc

#80734 check that first arg to `panic!()` in const is `&str`
  compiler/rustc_mir/src/transform/check_consts/ops.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  src/test/ui/consts/issue-66693-panic-in-array-len.rs
  src/test/ui/consts/issue-66693-panic-in-array-len.stderr
  src/test/ui/consts/issue-66693.rs
  src/test/ui/consts/issue-66693.stderr
  src/test/ui/consts/issue-76064.rs
  src/test/ui/consts/issue-76064.stderr
Labels: S-waiting-on-bors

#82634 Remove an old FIXME comment and inline attribute
  compiler/rustc_trait_selection/src/traits/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#82376 Add option to enable MIR inlining independently of mir-opt-level
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_mir/src/transform/mod.rs
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors

#82516 Add incomplete feature gate for inherent associate types.
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0202.md
  compiler/rustc_feature/src/active.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  compiler/rustc_typeck/src/errors.rs
  src/test/ui/assoc-inherent.rs
  src/test/ui/assoc-inherent.stderr
  src/test/ui/feature-gates/feature-gate-inherent_associated_types.rs
  src/test/ui/feature-gates/feature-gate-inherent_associated_types.stderr
  src/test/ui/parser/impl-item-type-no-body-semantic-fail.rs
  src/test/ui/parser/impl-item-type-no-body-semantic-fail.stderr
Labels: F-inherent_associated_types, S-waiting-on-bors

#82579 Fix turbofish recovery with multiple generic args
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_parse/src/parser/path.rs
  compiler/rustc_parse/src/parser/ty.rs
  src/test/ui/suggestions/issue-82566-1.rs
  src/test/ui/suggestions/issue-82566-1.stderr
  src/test/ui/suggestions/issue-82566-2.rs
  src/test/ui/suggestions/issue-82566-2.stderr
Labels: A-const-generics, A-diagnostics, S-waiting-on-bors

#82593 Teach rustdoc how to display WASI.
  src/librustdoc/clean/cfg.rs
  src/librustdoc/clean/cfg/tests.rs
  src/test/rustdoc/doc-cfg.rs
Labels: S-waiting-on-bors, T-rustdoc

#82597 Get TyCtxt from self instead of passing as argument in AutoTraitFinder
  compiler/rustc_trait_selection/src/traits/auto_trait.rs
  src/librustdoc/clean/auto_trait.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, T-rustdoc

#82627 Erase late bound regions to avoid ICE
  compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs
  src/test/ui/return/issue-82612-return-mutable-reference.rs
  src/test/ui/return/issue-82612-return-mutable-reference.stderr
Labels: S-waiting-on-bors

#80189 Convert primitives in the standard library to intra-doc links
  library/alloc/src/lib.rs
  library/alloc/src/slice.rs
  library/alloc/src/str.rs
  library/alloc/src/string.rs
  library/alloc/src/vec/mod.rs
  library/core/src/alloc/layout.rs
  library/core/src/array/iter.rs
  library/core/src/array/mod.rs
  library/core/src/char/mod.rs
  library/core/src/convert/mod.rs
  library/core/src/ffi.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/mem/mod.rs
  library/core/src/num/f32.rs
  library/core/src/num/f64.rs
  library/core/src/num/shells/i128.rs
  library/core/src/num/shells/i16.rs
  library/core/src/num/shells/i32.rs
  library/core/src/num/shells/i64.rs
  library/core/src/num/shells/i8.rs
  library/core/src/num/shells/int_macros.rs
  library/core/src/num/shells/isize.rs
  library/core/src/num/shells/u128.rs
  library/core/src/num/shells/u16.rs
  library/core/src/num/shells/u32.rs
  library/core/src/num/shells/u64.rs
  library/core/src/num/shells/u8.rs
  library/core/src/num/shells/usize.rs
  library/core/src/ops/function.rs
  library/core/src/ptr/const_ptr.rs
  library/core/src/ptr/mod.rs
  library/core/src/ptr/mut_ptr.rs
  library/core/src/ptr/non_null.rs
  library/core/src/result.rs
  library/core/src/slice/index.rs
  library/core/src/slice/iter.rs
  library/core/src/slice/raw.rs
  library/core/src/str/converts.rs
  library/core/src/str/traits.rs
  library/core/src/sync/atomic.rs
  library/std/src/ffi/c_str.rs
  library/std/src/io/mod.rs
  library/std/src/keyword_docs.rs
  library/std/src/lib.rs
  library/std/src/primitive_docs.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc

#80874 Update intra-doc link documentation to match the implementation
  src/doc/rustdoc/src/linking-to-items-by-name.md
Labels: A-intra-doc-links, S-waiting-on-bors, T-doc, T-rustdoc

#82043 Turn may_have_side_effect into an associated constant
  library/alloc/src/vec/into_iter.rs
  library/core/src/iter/adapters/cloned.rs
  library/core/src/iter/adapters/copied.rs
  library/core/src/iter/adapters/enumerate.rs
  library/core/src/iter/adapters/fuse.rs
  library/core/src/iter/adapters/map.rs
  library/core/src/iter/adapters/zip.rs
  library/core/src/slice/iter.rs
  library/core/src/str/iter.rs
Labels: S-waiting-on-bors, merged-by-bors

#82562 Optimize counting digits in line numbers during error reporting further
  compiler/rustc_errors/src/emitter.rs
Labels: S-waiting-on-bors, merged-by-bors

#76345 Add is_enclave_range/is_user_range overflow checks
  library/std/src/sys/sgx/abi/mem.rs
Labels: S-waiting-on-bors, T-libs, T-libs-impl, merged-by-bors

#82689 meta: Notify Zulip for rustdoc nominated issues
  triagebot.toml
Labels: A-meta, S-waiting-on-bors, T-rustdoc

#82695 Revert non-power-of-two vector restriction
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/simd/issue-17170.rs
  src/test/ui/simd/issue-17170.stderr
  src/test/ui/simd/issue-39720.rs
  src/test/ui/simd/issue-39720.stderr
  src/test/ui/simd/simd-type-generic-monomorphisation-power-of-two.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-power-of-two.stderr
  src/test/ui/simd/simd-type.rs
  src/test/ui/simd/simd-type.stderr
Labels: C-enhancement, S-waiting-on-bors

#82706 use outer_expn_data() instead of outer_expn().expn_data()
  compiler/rustc_resolve/src/lib.rs
Labels: S-waiting-on-bors

#82710 FloatToInit: Replacing round_unchecked_to --> to_int_unchecked
  library/core/src/convert/num.rs
Labels: S-waiting-on-bors

#82712 Remove unnecessary conditional `cfg(target_os)` for `redox` and `vxworks`
  library/std/src/os/mod.rs
Labels: S-waiting-on-bors

#82439 BTree: fix untrue safety
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors

#82469 Use a crate to produce rustdoc tree comparisons instead of the `diff` command
  Cargo.lock
  src/tools/compiletest/Cargo.toml
  src/tools/compiletest/src/runtest.rs
Labels: A-contributor-roadblock, A-testsuite, S-waiting-on-bors, T-rustdoc

#82589 unix: Non-mutable bufs in send_vectored_with_ancillary_to
  library/std/src/sys/unix/ext/net/ancillary.rs
  library/std/src/sys/unix/ext/net/datagram.rs
  library/std/src/sys/unix/ext/net/stream.rs
  library/std/src/sys/unix/ext/net/tests.rs
Labels: S-waiting-on-bors

#81223 [rustdoc] Generate redirect map file
  src/librustdoc/config.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/lib.rs
  src/test/run-make-fulldeps/rustdoc-map-file/Makefile
  src/test/run-make-fulldeps/rustdoc-map-file/expected.json
  src/test/run-make-fulldeps/rustdoc-map-file/foo.rs
  src/test/run-make-fulldeps/rustdoc-map-file/validate_json.py
  src/test/rustdoc/redirect-map-empty.rs
  src/test/rustdoc/redirect-map.rs
Labels: S-waiting-on-bors, T-rustdoc

#82553 Update tracing to 0.1.25
  Cargo.lock
  compiler/rustc_driver/Cargo.toml
  src/tools/compiletest/Cargo.toml
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, merged-by-bors

#82702 Change error about unknown attributes to a warning
  compiler/rustc_passes/src/check_attr.rs
  src/test/rustdoc-ui/doc-attr.rs
  src/test/rustdoc-ui/doc-attr.stderr
  src/test/ui/attributes/doc-attr.rs
  src/test/ui/attributes/doc-attr.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81114 Box generator-related Body fields
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/visit.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/input_output.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/shim.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  compiler/rustc_mir/src/transform/generator.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_mir/src/transform/promote_consts.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir_build/src/build/mod.rs
Labels: I-compilemem, S-waiting-on-bors, merged-by-bors

#82304 Add `-Z unpretty` flags for the AST
  compiler/rustc_driver/src/pretty.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
Labels: A-pretty, S-waiting-on-bors, T-compiler, merged-by-bors

#82697 Fix stabilization version of move_ref_pattern
  compiler/rustc_feature/src/accepted.rs
Labels: S-waiting-on-bors

#82717 Account for macros when suggesting adding lifetime
  compiler/rustc_resolve/src/late/diagnostics.rs
  src/test/ui/lifetimes/undeclared-lifetime-used-in-debug-macro-issue-70152.rs
  src/test/ui/lifetimes/undeclared-lifetime-used-in-debug-macro-issue-70152.stderr
Labels: S-waiting-on-bors

#82740 Fix commit detected when using `download-rustc`
  src/bootstrap/bootstrap.py
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#82744 Pass `CrateNum` by value instead of by reference
  src/librustdoc/clean/types.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#82310 Load rustdoc's JS search index on-demand.
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#82315 Improve page load performance in rustdoc
  src/doc/rust.css
  src/librustdoc/html/layout.rs
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#82564 Revert `Vec::spare_capacity_mut` impl to prevent pointers invalidation
  library/alloc/src/vec/mod.rs
  library/alloc/tests/lib.rs
  library/alloc/tests/vec.rs
Labels: S-waiting-on-bors

#82747 Pin es-check version to prevent unrelated CI failures
  src/ci/docker/host-x86_64/mingw-check/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#71481 Inherit `#[stable(..)]` annotations in enum variants and fields from its item
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_passes/src/lib_features.rs
  compiler/rustc_passes/src/stability.rs
  src/test/ui/attributes/const-stability-on-macro.rs
  src/test/ui/attributes/const-stability-on-macro.stderr
  src/test/ui/deprecation/deprecation-in-staged-api.rs
  src/test/ui/deprecation/deprecation-in-staged-api.stderr
  src/test/ui/lint/auxiliary/lint_stability_fields.rs
  src/test/ui/lint/lint-stability-fields-deprecated.rs
  src/test/ui/lint/lint-stability-fields-deprecated.stderr
  src/test/ui/lint/lint-stability-fields.rs
  src/test/ui/lint/lint-stability-fields.stderr
  src/test/ui/stability-attribute/stability-attribute-issue-43027.rs
  src/test/ui/stability-attribute/stability-attribute-issue-43027.stderr
  src/test/ui/stability-attribute/stability-attribute-sanity.rs
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: A-stability, S-waiting-on-bors, T-compiler, merged-by-bors

#82752 Add a regression test for issue-81712
  src/test/ui/generic-associated-types/issue-81712-cyclic-traits.rs
  src/test/ui/generic-associated-types/issue-81712-cyclic-traits.stderr
Labels: S-waiting-on-bors

#82765 Fix polymorphization ICE on associated types in trait decls using const generics in bounds
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_middle/src/ty/instance.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/monomorphize/polymorphize.rs
Labels: S-waiting-on-bors

#82777 Rollup of 5 pull requests
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_middle/src/ty/instance.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/monomorphize/polymorphize.rs
  src/doc/rustdoc/src/SUMMARY.md
  src/doc/rustdoc/src/command-line-arguments.md
  src/doc/rustdoc/src/passes.md
  src/doc/rustdoc/src/unstable-features.md
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/render/tests.rs
  src/librustdoc/html/render/write_shared.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/visit_ast.rs
  src/test/rustdoc-ui/lint-missing-doc-code-example.rs
  src/test/rustdoc-ui/lint-missing-doc-code-example.stderr
  src/test/ui/generic-associated-types/issue-81712-cyclic-traits.rs
  src/test/ui/generic-associated-types/issue-81712-cyclic-traits.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82690 Update rustdoc documentation
  src/doc/rustdoc/src/SUMMARY.md
  src/doc/rustdoc/src/command-line-arguments.md
  src/doc/rustdoc/src/passes.md
  src/doc/rustdoc/src/unstable-features.md
Labels: S-waiting-on-bors, T-doc, T-rustdoc

#82088 Shorten html::render
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/render/tests.rs
  src/librustdoc/html/render/write_shared.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#76716 Don't warn for `missing_doc_examples` when item is #[doc(hidden)]
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/visit_ast.rs
  src/test/rustdoc-ui/lint-missing-doc-code-example.rs
  src/test/rustdoc-ui/lint-missing-doc-code-example.stderr
Labels: A-lint, S-waiting-on-bors, T-rustdoc

#82728 Avoid unnecessary Vec construction in BufReader
  library/std/src/io/buffered/bufreader.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs-impl

#82764 Add {BTreeMap,HashMap}::try_insert
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/entry.rs
  library/std/src/collections/hash/map.rs
  library/std/src/error.rs
  library/std/src/lib.rs
Labels: A-collections, S-waiting-on-bors, T-libs

#82770 Add assert_matches macro.
  library/core/src/macros/mod.rs
  library/core/src/panicking.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs

#82773 Add diagnostic item to `Default` trait
  compiler/rustc_span/src/symbol.rs
  library/core/src/default.rs
Labels: S-waiting-on-bors

#82787 Remove unused code from main.js
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors

#82795 Rollup of 10 pull requests
  compiler/rustc_codegen_ssa/src/back/rpath.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_lint/src/noop_method_call.rs
  compiler/rustc_middle/src/ty/error.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_mir/src/borrow_check/invalidation.rs
  compiler/rustc_mir_build/src/build/matches/test.rs
  compiler/rustc_resolve/src/imports.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_traits/src/chalk/mod.rs
  compiler/rustc_typeck/src/check/callee.rs
  compiler/rustc_typeck/src/check/expr.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/entry.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/core/src/borrow.rs
  library/core/src/clone.rs
  library/core/src/default.rs
  library/core/src/iter/adapters/zip.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/macros/mod.rs
  library/core/src/ops/deref.rs
  library/core/src/panicking.rs
  library/core/tests/iter/adapters/intersperse.rs
  library/core/tests/iter/adapters/zip.rs
  library/std/src/collections/hash/map.rs
  library/std/src/collections/hash/map/tests.rs
  library/std/src/error.rs
  library/std/src/io/buffered/bufreader.rs
  library/std/src/io/mod.rs
  library/std/src/io/tests.rs
  library/std/src/io/util.rs
  library/std/src/lib.rs
  src/librustdoc/html/static/main.js
  src/test/rustdoc/extern-links.rs
  src/test/rustdoc/issue-28927.rs
  src/test/ui/issues/issue-81584.fixed
  src/test/ui/issues/issue-81584.rs
  src/test/ui/issues/issue-81584.stderr
  src/test/ui/lint/noop-method-call.rs
  src/test/ui/lint/noop-method-call.stderr
  src/test/ui/pub/pub-reexport-priv-extern-crate.rs
  src/test/ui/pub/pub-reexport-priv-extern-crate.stderr
  src/test/ui/static/static-reference-to-fn-2.stderr
  src/test/ui/underscore-imports/hygiene-2.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82289 Fix underflow in specialized ZipImpl::size_hint
  library/core/src/iter/adapters/zip.rs
  library/core/tests/iter/adapters/zip.rs
Labels: A-iterators, S-waiting-on-bors, T-libs-impl

#81939 Add suggestion `.collect()` for iterators in iterators
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  library/core/src/iter/traits/iterator.rs
  src/test/ui/issues/issue-81584.fixed
  src/test/ui/issues/issue-81584.rs
  src/test/ui/issues/issue-81584.stderr
  src/test/ui/static/static-reference-to-fn-2.stderr
Labels: A-borrow-checker, A-diagnostics, A-suggestion-diagnostics, S-waiting-on-bors, T-compiler

#80723 Implement NOOP_METHOD_CALL lint
  compiler/rustc_codegen_ssa/src/back/rpath.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_lint/src/noop_method_call.rs
  compiler/rustc_middle/src/ty/error.rs
  compiler/rustc_mir/src/borrow_check/invalidation.rs
  compiler/rustc_mir_build/src/build/matches/test.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_traits/src/chalk/mod.rs
  compiler/rustc_typeck/src/check/callee.rs
  compiler/rustc_typeck/src/check/expr.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/core/src/borrow.rs
  library/core/src/clone.rs
  library/core/src/ops/deref.rs
  library/core/tests/iter/adapters/intersperse.rs
  library/std/src/collections/hash/map/tests.rs
  src/test/ui/lint/noop-method-call.rs
  src/test/ui/lint/noop-method-call.stderr
  src/test/ui/underscore-imports/hygiene-2.rs
Labels: A-lint, S-waiting-on-bors

#80763 resolve: Reduce scope of `pub_use_of_private_extern_crate` deprecation lint
  compiler/rustc_resolve/src/imports.rs
  src/test/rustdoc/extern-links.rs
  src/test/rustdoc/issue-28927.rs
  src/test/ui/pub/pub-reexport-priv-extern-crate.rs
  src/test/ui/pub/pub-reexport-priv-extern-crate.stderr
Labels: S-waiting-on-bors

#81136 Improved IO Bytes Size Hint
  library/std/src/io/buffered/bufreader.rs
  library/std/src/io/mod.rs
  library/std/src/io/tests.rs
  library/std/src/io/util.rs
Labels: S-waiting-on-bors

#82476 [beta] Fix TcpListener::accept() on x86 Android on beta by disabling the use of accept4.
  library/std/src/sys/unix/net.rs
Labels: O-android, S-waiting-on-bors, T-libs-impl, beta-accepted, beta-nominated, merged-by-bors

#74024 Improve slice.binary_search_by()'s best-case performance to O(1)
  library/core/benches/slice.rs
  library/core/src/slice/mod.rs
  library/core/tests/slice.rs
Labels: S-waiting-on-bors, T-libs-impl, merged-by-bors

#82782 Make rustc shim's verbose output include crate_name being compiled.
  src/bootstrap/bin/rustc.rs
Labels: S-waiting-on-bors

#82797 Update tests names to start with `issue-`
  src/test/ui/structs/issue-80853.rs
  src/test/ui/structs/issue-80853.stderr
Labels: C-cleanup, S-waiting-on-bors

#82809 rustdoc: Use substrings instead of split to grab enum variant paths
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, T-rustdoc

#82714 Detect match arm body without braces
  compiler/rustc_parse/src/parser/expr.rs
  compiler/rustc_parse/src/parser/stmt.rs
  src/test/ui/parser/match-arm-without-braces.rs
  src/test/ui/parser/match-arm-without-braces.stderr
Labels: S-waiting-on-bors

#80845 Make ItemKind::ExternCrate looks like hir::ItemKind::ExternCrate to make transition over hir::ItemKind simpler
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/formats/item_type.rs
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/stripper.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#82738 Move check only relevant in error case out of critical path
  compiler/rustc_typeck/src/check/_match.rs
Labels: S-waiting-on-bors, merged-by-bors

#82592 Improve transmute docs with further clarifications
  library/core/src/intrinsics.rs
Labels: S-waiting-on-bors

#82651 Cleanup rustdoc warnings
  compiler/rustc_passes/src/check_attr.rs
  src/librustdoc/config.rs
  src/librustdoc/core.rs
  src/test/rustdoc-ui/deprecated-attrs.rs
  src/test/rustdoc-ui/deprecated-attrs.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-rustdoc

#82720 Fix diagnostic suggests adding type `[type error]`
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/parser/item-free-const-no-body-semantic-fail.rs
  src/test/ui/parser/item-free-const-no-body-semantic-fail.stderr
  src/test/ui/parser/item-free-static-no-body-semantic-fail.rs
  src/test/ui/parser/item-free-static-no-body-semantic-fail.stderr
  src/test/ui/typeck/issue-79040.rs
  src/test/ui/typeck/issue-79040.stderr
Labels: S-waiting-on-bors

#82751 improve offset_from docs
  library/core/src/ptr/const_ptr.rs
  library/core/src/ptr/mut_ptr.rs
Labels: S-waiting-on-bors

#82793 Move some tests to more suitable subdirs
  src/test/ui/abi/nullable-pointer-ffi-compat.rs
  src/test/ui/associated-types/issue-76179.rs
  src/test/ui/async-await/issue-74047.rs
  src/test/ui/async-await/issue-74047.stderr
  src/test/ui/borrowck/issue-42344.rs
  src/test/ui/borrowck/issue-42344.stderr
  src/test/ui/consts/auxiliary/issue-17718-aux.rs
  src/test/ui/consts/issue-17718.rs
  src/test/ui/consts/issue-3521.fixed
  src/test/ui/consts/issue-3521.rs
  src/test/ui/consts/issue-3521.stderr
  src/test/ui/issues/issue-2633-2.rs
  src/test/ui/issues/issue-2633.rs
  src/test/ui/lint/lint-expr-stmt-attrs-for-early-lints.rs
  src/test/ui/nll/issue-52992.rs
  src/test/ui/parser/issue-7222.rs
  src/test/ui/regions/issue-6157.rs
  src/test/ui/resolve/issue-2330.rs
  src/test/ui/resolve/issue-2330.stderr
  src/test/ui/statics/issue-15261.rs
  src/test/ui/statics/issue-44373-2.rs
  src/test/ui/statics/issue-44373.rs
  src/test/ui/statics/issue-44373.stderr
  src/test/ui/traits/impl-bounds-checking.rs
  src/test/ui/traits/impl-bounds-checking.stderr
  src/test/ui/traits/issue-28576.rs
  src/test/ui/traits/issue-28576.stderr
  src/test/ui/traits/issue-33140.rs
  src/test/ui/traits/issue-33140.stderr
  src/test/ui/traits/object/issue-33140-traitobject-crate.rs
  src/test/ui/traits/object/issue-33140-traitobject-crate.stderr
  src/test/ui/try-block/try-block.rs
  src/test/ui/tuple/tup.rs
  src/test/ui/unboxed-closures/issue-18661.rs
  src/tools/tidy/src/ui_tests.rs
Labels: S-waiting-on-bors

#82803 rustdoc: Add an unstable option to print all unversioned files
  src/librustdoc/clean/types.rs
  src/librustdoc/config.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/write_shared.rs
  src/librustdoc/lib.rs
  src/test/run-make-fulldeps/print-unversioned-files/Makefile
  src/test/run-make-fulldeps/print-unversioned-files/unversioned-files.txt
Labels: S-waiting-on-bors, T-docs-rs, T-rustdoc, requires-nightly

#82822 Fix typo
  compiler/rustc/src/main.rs
Labels: C-cleanup, S-waiting-on-bors

#82837 tweak MaybeUninit docs
  library/core/src/mem/maybe_uninit.rs
Labels: S-waiting-on-bors

#82130 Make some Option, Result methods unstably const
  library/core/src/option.rs
  library/core/src/result.rs
Labels: A-const-fn, S-waiting-on-bors, T-libs

#82292 Prevent specialized ZipImpl from calling `__iterator_get_unchecked` twice with the same index
  library/core/src/iter/adapters/zip.rs
  library/core/tests/iter/adapters/zip.rs
Labels: A-iterators, S-waiting-on-bors

#82402 Remove RefCell around `module_trait_cache`
  src/librustdoc/core.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/html_tags.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/non_autolinks.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#77916 Change built-in kernel targets to be os = none throughout
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/x86_64_unknown_none_hermitkernel.rs
  compiler/rustc_target/src/spec/x86_64_unknown_none_linuxkernel.rs
  library/unwind/src/lib.rs
  src/doc/rustc/src/platform-support.md
Labels: I-needs-decision, S-waiting-on-bors

#82285 Use u32 over Option<u32> in DebugLoc
  compiler/rustc_codegen_llvm/src/debuginfo/create_scope_map.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/debuginfo/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#81635 Let a portion of DefPathHash uniquely identify the DefPath's crate.
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_data_structures/src/fingerprint.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_hir/src/lib.rs
  compiler/rustc_hir/src/tests.rs
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_metadata/src/locator.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/src/crate_disambiguator.rs
  compiler/rustc_span/src/def_id.rs
  compiler/rustc_span/src/lib.rs
  src/test/ui/single-use-lifetime/one-use-in-fn-argument-in-band.stderr
  src/test/ui/symbol-names/basic.legacy.stderr
  src/test/ui/symbol-names/basic.rs
  src/test/ui/symbol-names/basic.v0.stderr
  src/test/ui/symbol-names/const-generics-demangling.rs
  src/test/ui/symbol-names/const-generics-demangling.stderr
  src/test/ui/symbol-names/impl1.legacy.stderr
  src/test/ui/symbol-names/impl1.rs
  src/test/ui/symbol-names/impl1.v0.stderr
  src/test/ui/symbol-names/issue-60925.legacy.stderr
  src/test/ui/symbol-names/issue-60925.rs
  src/test/ui/symbol-names/issue-60925.v0.stderr
  src/test/ui/symbol-names/issue-75326.legacy.stderr
  src/test/ui/symbol-names/issue-75326.rs
  src/test/ui/symbol-names/issue-75326.v0.stderr
Labels: A-diagnostics, A-incr-comp, A-query-system, C-enhancement, S-waiting-on-bors, merged-by-bors

#82727 Test the effect of shrinking the size of Rvalue by 16 bytes
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/tcx.rs
  compiler/rustc_middle/src/mir/type_foldable.rs
  compiler/rustc_middle/src/mir/visit.rs
  compiler/rustc_mir/src/borrow_check/invalidation.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/dataflow/move_paths/builder.rs
  compiler/rustc_mir/src/interpret/step.rs
  compiler/rustc_mir/src/shim.rs
  compiler/rustc_mir/src/transform/check_consts/qualifs.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  compiler/rustc_mir/src/transform/early_otherwise_branch.rs
  compiler/rustc_mir/src/transform/instcombine.rs
  compiler/rustc_mir/src/transform/lower_intrinsics.rs
  compiler/rustc_mir/src/transform/match_branches.rs
  compiler/rustc_mir/src/transform/promote_consts.rs
  compiler/rustc_mir/src/transform/simplify_comparison_integral.rs
  compiler/rustc_mir/src/util/elaborate_drops.rs
  compiler/rustc_mir_build/src/build/expr/as_place.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/matches/test.rs
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  src/tools/clippy/clippy_lints/src/redundant_clone.rs
  src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs
Labels: S-experimental, S-waiting-on-bors, merged-by-bors

#82857 Edit ructc_ast_lowering docs
  compiler/rustc_ast_lowering/src/lib.rs
Labels: S-waiting-on-bors

#82862 Generalize Write impl for Vec<u8> to Vec<u8, A>
  library/std/src/io/impls.rs
Labels: S-waiting-on-bors

#82557 Add natvis for Result, NonNull, CString, CStr, and Cow
  src/etc/natvis/liballoc.natvis
  src/etc/natvis/libcore.natvis
  src/etc/natvis/libstd.natvis
Labels: S-waiting-on-bors

#82613 Remove Item::kind, use tagged enum. Rename variants to match
  Cargo.lock
  src/bootstrap/builder.rs
  src/bootstrap/test.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/rustdoc-json-types/Cargo.toml
  src/rustdoc-json-types/lib.rs
  src/rustdoc-json-types/tests.rs
Labels: A-rustdoc-json, S-waiting-on-bors, T-rustdoc

#82642 Fix jemalloc usage on OSX
  compiler/rustc/src/main.rs
Labels: S-waiting-on-bors

#82682 Implement built-in attribute macro `#[cfg_eval]` + some refactoring
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/ast_like.rs
  compiler/rustc_builtin_macros/src/cfg_eval.rs
  compiler/rustc_builtin_macros/src/derive.rs
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/config.rs
  compiler/rustc_parse/src/parser/attr_wrapper.rs
  compiler/rustc_span/src/symbol.rs
  library/core/src/macros/mod.rs
  library/core/src/prelude/v1.rs
  library/std/src/lib.rs
  library/std/src/prelude/v1.rs
  src/test/ui/proc-macro/cfg-eval-fail.rs
  src/test/ui/proc-macro/cfg-eval-fail.stderr
  src/test/ui/proc-macro/cfg-eval.rs
  src/test/ui/proc-macro/cfg-eval.stdout
Labels: S-waiting-on-bors

#82684 Disable destination propagation on all mir-opt-levels
  compiler/rustc_mir/src/transform/dest_prop.rs
  src/test/mir-opt/deduplicate_blocks.is_line_doc_comment_2.DeduplicateBlocks.diff
  src/test/mir-opt/dest-prop/branch.rs
  src/test/mir-opt/dest-prop/copy_propagation_arg.rs
  src/test/mir-opt/dest-prop/cycle.rs
  src/test/mir-opt/dest-prop/simple.rs
  src/test/mir-opt/dest-prop/union.rs
  src/test/mir-opt/inline/inline_closure_captures.foo.Inline.after.mir
  src/test/mir-opt/inline/inline_diverging.h.Inline.diff
  src/test/mir-opt/inline/inline_generator.main.Inline.diff
  src/test/mir-opt/issue_73223.main.PreCodegen.32bit.diff
  src/test/mir-opt/issue_73223.main.PreCodegen.64bit.diff
  src/test/mir-opt/issues/issue_59352.num_to_digit.PreCodegen.after.mir
  src/test/mir-opt/lower_intrinsics.f_u64.PreCodegen.before.mir
  src/test/mir-opt/simplify_locals.c.SimplifyLocals.diff
Labels: S-waiting-on-bors

#82755 Refactor confirm_builtin_call, remove partial if
  compiler/rustc_typeck/src/check/callee.rs
Labels: S-waiting-on-bors

#82047 bypass auto_da_alloc for metadata files
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/util.rs
Labels: S-waiting-on-bors

#82415 expand: Refactor module loading
  compiler/rustc_builtin_macros/src/source_util.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_expand/src/module.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_session/src/parse.rs
  src/test/ui/directory_ownership/macro-expanded-mod.rs
  src/test/ui/directory_ownership/macro-expanded-mod.stderr
  src/test/ui/directory_ownership/non-inline-mod-restriction.rs
  src/test/ui/directory_ownership/non-inline-mod-restriction.stderr
  src/test/ui/modules/path-no-file-name.rs
  src/test/ui/modules/path-no-file-name.stderr
  src/test/ui/parser/circular_modules_main.rs
  src/test/ui/parser/circular_modules_main.stderr
Labels: S-waiting-on-bors

#82877 Revert switch of env locking to rwlock, to fix deadlock in process spawning
  library/std/src/sys/unix/os.rs
  library/std/src/sys/unix/process/process_unix.rs
  library/std/src/sys_common/rwlock.rs
Labels: S-waiting-on-bors, merged-by-bors

#82881 diagnostics: Be clear about "crate root" and `::foo` paths in resolve diagnostics
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
  src/test/ui/editions-crate-root-2015.rs
  src/test/ui/editions-crate-root-2015.stderr
  src/test/ui/editions-crate-root-2018.rs
  src/test/ui/editions-crate-root-2018.stderr
  src/test/ui/editions/edition-imports-virtual-2015-gated.stderr
  src/test/ui/resolve/raw-ident-in-path.rs
  src/test/ui/resolve/raw-ident-in-path.stderr
  src/test/ui/rfc-2126-extern-absolute-paths/non-existent-2.rs
  src/test/ui/rfc-2126-extern-absolute-paths/non-existent-2.stderr
Labels: S-waiting-on-bors

#82911 Rollup of 11 pull requests
  .mailmap
  Cargo.lock
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_lint/src/types.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
  library/alloc/src/string.rs
  library/core/src/array/mod.rs
  library/std/src/lib.rs
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
  src/librustdoc/Cargo.toml
  src/test/codegen/issue-73031.rs
  src/test/codegen/issue-75546.rs
  src/test/codegen/issue-77812.rs
  src/test/ui/editions-crate-root-2015.rs
  src/test/ui/editions-crate-root-2015.stderr
  src/test/ui/editions-crate-root-2018.rs
  src/test/ui/editions-crate-root-2018.stderr
  src/test/ui/editions/edition-imports-virtual-2015-gated.stderr
  src/test/ui/lint/type-overflow.stderr
  src/test/ui/parser/lex-bare-cr-nondoc-comment.rs
  src/test/ui/parser/lexer-crlf-line-endings-string-literal-doc-comment.rs
  src/test/ui/pattern/issue-82290.stderr
  src/test/ui/resolve/raw-ident-in-path.rs
  src/test/ui/resolve/raw-ident-in-path.stderr
  src/test/ui/rfc-2126-extern-absolute-paths/non-existent-2.rs
  src/test/ui/rfc-2126-extern-absolute-paths/non-existent-2.stderr
  src/test/ui/rfc-2294-if-let-guard/feature-gate.stderr
  src/test/ui/rfc-2497-if-let-chains/disallowed-positions.stderr
  src/test/ui/rfc-2497-if-let-chains/feature-gate.rs
  src/test/ui/rfc-2497-if-let-chains/feature-gate.stderr
  src/test/ui/rustdoc/README.md
  src/test/ui/rustdoc/cfg-rustdoc.rs
  src/test/ui/rustdoc/cfg-rustdoc.stderr
  src/test/ui/rustdoc/check-doc-alias-attr-location.rs
  src/test/ui/rustdoc/check-doc-alias-attr-location.stderr
  src/test/ui/rustdoc/check-doc-alias-attr.rs
  src/test/ui/rustdoc/check-doc-alias-attr.stderr
  src/test/ui/rustdoc/doc-alias-crate-level.rs
  src/test/ui/rustdoc/doc-alias-crate-level.stderr
  src/test/ui/rustdoc/doc-alias-same-name.rs
  src/test/ui/rustdoc/doc-alias-same-name.stderr
  src/test/ui/rustdoc/doc_keyword.rs
  src/test/ui/rustdoc/doc_keyword.stderr
  src/test/ui/rustdoc/unterminated-doc-comment.rs
  src/test/ui/rustdoc/unterminated-doc-comment.stderr
  src/tools/tidy/src/ui_tests.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82711 Add documentation for string->Cow conversions
  library/alloc/src/string.rs
Labels: S-waiting-on-bors

#82767 Update minifier dependency version
  Cargo.lock
  src/librustdoc/Cargo.toml
Labels: S-waiting-on-bors, T-rustdoc

#82800 Move rustdoc UI tests into a subdirectory
  src/test/ui/parser/lex-bare-cr-nondoc-comment.rs
  src/test/ui/parser/lexer-crlf-line-endings-string-literal-doc-comment.rs
  src/test/ui/rustdoc/README.md
  src/test/ui/rustdoc/cfg-rustdoc.rs
  src/test/ui/rustdoc/cfg-rustdoc.stderr
  src/test/ui/rustdoc/check-doc-alias-attr-location.rs
  src/test/ui/rustdoc/check-doc-alias-attr-location.stderr
  src/test/ui/rustdoc/check-doc-alias-attr.rs
  src/test/ui/rustdoc/check-doc-alias-attr.stderr
  src/test/ui/rustdoc/doc-alias-crate-level.rs
  src/test/ui/rustdoc/doc-alias-crate-level.stderr
  src/test/ui/rustdoc/doc-alias-same-name.rs
  src/test/ui/rustdoc/doc-alias-same-name.stderr
  src/test/ui/rustdoc/doc_keyword.rs
  src/test/ui/rustdoc/doc_keyword.stderr
  src/test/ui/rustdoc/unterminated-doc-comment.rs
  src/test/ui/rustdoc/unterminated-doc-comment.stderr
  src/tools/tidy/src/ui_tests.rs
Labels: A-testsuite, S-waiting-on-bors

#82810 Typo fix in Unstable book: `cargo cov` -> `cargo profdata`
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
Labels: S-waiting-on-bors

#82829 Handle negative literals in cast overflow warning
  compiler/rustc_lint/src/types.rs
  src/test/ui/lint/type-overflow.stderr
Labels: S-waiting-on-bors

#82854 Account for `if (let pat = expr) {}`
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_lint/src/unused.rs
  src/test/ui/pattern/issue-82290.stderr
  src/test/ui/rfc-2294-if-let-guard/feature-gate.stderr
  src/test/ui/rfc-2497-if-let-chains/disallowed-positions.stderr
  src/test/ui/rfc-2497-if-let-chains/feature-gate.rs
  src/test/ui/rfc-2497-if-let-chains/feature-gate.stderr
Labels: S-waiting-on-bors

#82870 Add note about the `#[doc(no-inline)]` usage
  library/std/src/lib.rs
Labels: S-waiting-on-bors

#82874 Add codegen tests for some issues closed by LLVM 12
  src/test/codegen/issue-73031.rs
  src/test/codegen/issue-75546.rs
  src/test/codegen/issue-77812.rs
Labels: S-waiting-on-bors

#82888 Grammar Fixes
  library/core/src/array/mod.rs
Labels: C-enhancement, S-waiting-on-bors, T-doc

#82897 [.mailmap] Add entry for Ramkumar Ramachandra
  .mailmap
Labels: S-waiting-on-bors

#82356 rustdoc: Cleanup `html::render::Context`
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/json/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81879 Added #[repr(transparent)] to core::cmp::Reverse
  library/core/src/cmp.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, final-comment-period

#82048 or-patterns: disallow in `let` bindings
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_parse/src/parser/pat.rs
  compiler/rustc_parse/src/parser/stmt.rs
  src/test/ui/or-patterns/already-bound-name.rs
  src/test/ui/or-patterns/already-bound-name.stderr
  src/test/ui/or-patterns/consistent-bindings.rs
  src/test/ui/or-patterns/const-fn.rs
  src/test/ui/or-patterns/feature-gate-or_patterns-leading-let.rs
  src/test/ui/or-patterns/feature-gate-or_patterns-leading-let.stderr
  src/test/ui/or-patterns/feature-gate-or_patterns.rs
  src/test/ui/or-patterns/feature-gate-or_patterns.stderr
  src/test/ui/or-patterns/fn-param-wrap-parens.fixed
  src/test/ui/or-patterns/fn-param-wrap-parens.rs
  src/test/ui/or-patterns/fn-param-wrap-parens.stderr
  src/test/ui/or-patterns/inconsistent-modes.rs
  src/test/ui/or-patterns/inconsistent-modes.stderr
  src/test/ui/or-patterns/issue-69875-should-have-been-expanded-earlier-non-exhaustive.rs
  src/test/ui/or-patterns/issue-69875-should-have-been-expanded-earlier-non-exhaustive.stderr
  src/test/ui/or-patterns/issue-69875-should-have-been-expanded-earlier.rs
  src/test/ui/or-patterns/let-pattern.rs
  src/test/ui/or-patterns/mismatched-bindings-async-fn.rs
  src/test/ui/or-patterns/mismatched-bindings-async-fn.stderr
  src/test/ui/or-patterns/missing-bindings.rs
  src/test/ui/or-patterns/missing-bindings.stderr
  src/test/ui/or-patterns/nested-undelimited-precedence.rs
  src/test/ui/or-patterns/nested-undelimited-precedence.stderr
  src/test/ui/or-patterns/or-patterns-binding-type-mismatch.rs
  src/test/ui/or-patterns/or-patterns-binding-type-mismatch.stderr
  src/test/ui/or-patterns/or-patterns-default-binding-modes.rs
  src/test/ui/or-patterns/or-patterns-syntactic-fail.rs
  src/test/ui/or-patterns/or-patterns-syntactic-fail.stderr
  src/test/ui/or-patterns/or-patterns-syntactic-pass.rs
  src/test/ui/or-patterns/remove-leading-vert.fixed
  src/test/ui/or-patterns/remove-leading-vert.rs
  src/test/ui/or-patterns/remove-leading-vert.stderr
  src/tools/clippy/clippy_lints/src/loops.rs
Labels: S-waiting-on-bors

#81127 Improve sift_down performance in BinaryHeap
  library/alloc/src/collections/binary_heap.rs
Labels: S-waiting-on-bors

#82849 Add Option::get_or_default
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/coverage/graph.rs
  library/core/src/option.rs
Labels: S-waiting-on-bors

#82937 Update README.md to use the correct cmake version number
  README.md
Labels: S-waiting-on-bors

#82938 Bump tracing-tree dependency
  Cargo.lock
  compiler/rustc_driver/Cargo.toml
  src/librustdoc/Cargo.toml
Labels: S-waiting-on-bors

#82942 Don't hardcode the `v1` prelude in diagnostics, to allow for new preludes.
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_typeck/src/check/demand.rs
Labels: A-suggestion-diagnostics, S-waiting-on-bors, T-compiler

#82411 Fixes to ExitStatus and its docs
  library/std/src/process.rs
  library/std/src/sys/unix/ext/process.rs
  library/std/src/sys/unix/process/process_unix.rs
  library/std/src/sys/unix/process/process_unix/tests.rs
Labels: S-waiting-on-bors

#82733 Add powerpc-unknown-openbsd target
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/powerpc_unknown_openbsd.rs
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors

#82802 Build rustdoc for run-make tests, not just run-make-fulldeps
  src/bootstrap/test.rs
Labels: A-testsuite, S-waiting-on-bors, T-rustdoc

#77511 Add StatementKind::CopyNonOverlapping
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_codegen_ssa/src/mir/intrinsic.rs
  compiler/rustc_codegen_ssa/src/mir/statement.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/visit.rs
  compiler/rustc_mir/src/borrow_check/invalidation.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/dataflow/impls/borrows.rs
  compiler/rustc_mir/src/dataflow/impls/storage_liveness.rs
  compiler/rustc_mir/src/dataflow/move_paths/builder.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/step.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_mir/src/transform/coverage/spans.rs
  compiler/rustc_mir/src/transform/dest_prop.rs
  compiler/rustc_mir/src/transform/generator.rs
  compiler/rustc_mir/src/transform/lower_intrinsics.rs
  compiler/rustc_mir/src/transform/remove_noop_landing_pads.rs
  compiler/rustc_mir/src/transform/simplify.rs
  compiler/rustc_mir/src/transform/validate.rs
  compiler/rustc_mir/src/util/spanview.rs
  src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs
Labels: S-waiting-on-bors

#79208 Stabilize `unsafe_op_in_unsafe_fn` lint
  compiler/rustc_feature/src/accepted.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  library/alloc/src/lib.rs
  library/core/src/lib.rs
  library/core/tests/lib.rs
  library/std/src/lib.rs
  src/test/ui/feature-gates/feature-gate-unsafe_block_in_unsafe_fn.rs
  src/test/ui/feature-gates/feature-gate-unsafe_block_in_unsafe_fn.stderr
  src/test/ui/unsafe/rfc-2585-unsafe_op_in_unsafe_fn.rs
  src/test/ui/unsafe/rfc-2585-unsafe_op_in_unsafe_fn.stderr
Labels: F-unsafe-block-in-unsafe-fn, S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, needs-fcp, relnotes

#76570 Implement RFC 2945: "C-unwind" ABI
  compiler/rustc_ast_lowering/src/item.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_codegen_cranelift/src/abi/mod.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_mir/src/interpret/terminator.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_symbol_mangling/src/v0.rs
  compiler/rustc_target/src/spec/abi.rs
  compiler/rustc_target/src/spec/arm_base.rs
  compiler/rustc_target/src/spec/mipsel_unknown_none.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/nvptx64_nvidia_cuda.rs
  compiler/rustc_target/src/spec/riscv_base.rs
  compiler/rustc_typeck/src/collect.rs
  compiler/rustc_typeck/src/lib.rs
  src/doc/unstable-book/src/language-features/c-unwind.md
  src/test/codegen/unwind-abis/c-unwind-abi-panic-abort.rs
  src/test/codegen/unwind-abis/c-unwind-abi.rs
  src/test/codegen/unwind-abis/stdcall-unwind-abi.rs
  src/test/codegen/unwind-abis/system-unwind-abi.rs
  src/test/codegen/unwind-abis/thiscall-unwind-abi.rs
  src/test/run-make-fulldeps/c-unwind-abi-catch-lib-panic/Makefile
  src/test/run-make-fulldeps/c-unwind-abi-catch-lib-panic/add.c
  src/test/run-make-fulldeps/c-unwind-abi-catch-lib-panic/main.rs
  src/test/run-make-fulldeps/c-unwind-abi-catch-lib-panic/panic.rs
  src/test/run-make-fulldeps/c-unwind-abi-catch-panic/Makefile
  src/test/run-make-fulldeps/c-unwind-abi-catch-panic/add.c
  src/test/run-make-fulldeps/c-unwind-abi-catch-panic/main.rs
  src/test/ui/allocator/no_std-alloc-error-handler-custom.rs
  src/test/ui/allocator/no_std-alloc-error-handler-default.rs
  src/test/ui/codemap_tests/unicode.stderr
  src/test/ui/parser/issue-8537.stderr
  src/test/ui/unwind-abis/feature-gate-c-unwind-enabled.rs
  src/test/ui/unwind-abis/feature-gate-c-unwind.rs
  src/test/ui/unwind-abis/feature-gate-c-unwind.stderr
  src/test/ui/unwind-abis/feature-gate-stdcall-unwind.rs
  src/test/ui/unwind-abis/feature-gate-stdcall-unwind.stderr
  src/test/ui/unwind-abis/feature-gate-system-unwind.rs
  src/test/ui/unwind-abis/feature-gate-system-unwind.stderr
  src/test/ui/unwind-abis/feature-gate-thiscall-unwind.rs
  src/test/ui/unwind-abis/feature-gate-thiscall-unwind.stderr
Labels: S-waiting-on-bors, merged-by-bors

#82962 Treat header as first paragraph for shortened markdown descriptions
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/mod.rs
Labels: C-enhancement, S-waiting-on-bors, T-rustdoc

#82976 fix error message for copy(_nonoverlapping) overflow
  compiler/rustc_mir/src/interpret/step.rs
  src/test/ui/consts/copy-intrinsic.rs
  src/test/ui/consts/copy-intrinsic.stderr
Labels: S-waiting-on-bors

#82977 Rename `Option::get_or_default` to `get_or_insert_default`
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/coverage/graph.rs
  library/core/src/option.rs
Labels: S-waiting-on-bors

#82982 Rollup of 9 pull requests
  compiler/rustc_builtin_macros/src/standard_library_imports.rs
  compiler/rustc_middle/src/ty/relate.rs
  compiler/rustc_mir/src/interpret/step.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/coverage/graph.rs
  compiler/rustc_span/src/edition.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/spec/crt_objects.rs
  library/core/src/option.rs
  library/core/src/prelude/mod.rs
  library/core/src/prelude/v1.rs
  library/std/src/lib.rs
  library/std/src/prelude/mod.rs
  library/std/src/prelude/v1.rs
  library/std/src/sys/unix/ext/process.rs
  library/std/src/sys/unix/process/process_unix.rs
  src/bootstrap/compile.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
  src/test/pretty/asm.pp
  src/test/pretty/cast-lt.pp
  src/test/pretty/dollar-crate.pp
  src/test/pretty/expanded-and-path-remap-80832.pp
  src/test/pretty/issue-12590-c.pp
  src/test/pretty/issue-4264.pp
  src/test/ui/ast-json/ast-json-output.stdout
  src/test/ui/command/command-pre-exec.rs
  src/test/ui/const-generics/const-argument-cross-crate-mismatch.full.stderr
  src/test/ui/const-generics/const-argument-cross-crate-mismatch.min.stderr
  src/test/ui/const-generics/const-argument-cross-crate-mismatch.rs
  src/test/ui/consts/copy-intrinsic.rs
  src/test/ui/consts/copy-intrinsic.stderr
  src/test/ui/imports/extern-prelude-extern-crate-restricted-shadowing.stderr
  src/test/ui/issues/issue-27033.stderr
  src/test/ui/issues/issue-60662.stdout
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
  src/test/ui/proc-macro/nonterminal-token-hygiene.stdout
  src/test/ui/rfc-2497-if-let-chains/ast-pretty-check.stdout
Labels: S-waiting-on-bors, merged-by-bors, rollup

#82924 WASI: Switch to crt1-command.o to enable support for new-style commands
  compiler/rustc_target/src/spec/crt_objects.rs
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#82949 Do not attempt to unlock envlock in child process after a fork.
  library/std/src/sys/unix/ext/process.rs
  library/std/src/sys/unix/process/process_unix.rs
  src/test/ui/command/command-pre-exec.rs
Labels: S-waiting-on-bors, T-libs
