Repository rust-lang/rust, pull requests merged in 2021-02, with the labels that each got.

#81480 Add suggestion for nested fields
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/suggestions/non-existent-field-present-in-subfield-recursion-limit.rs
  src/test/ui/suggestions/non-existent-field-present-in-subfield-recursion-limit.stderr
  src/test/ui/suggestions/non-existent-field-present-in-subfield.fixed
  src/test/ui/suggestions/non-existent-field-present-in-subfield.rs
  src/test/ui/suggestions/non-existent-field-present-in-subfield.stderr
Labels: S-waiting-on-bors

#81549 Misc ip documentation fixes
  library/std/src/net/ip.rs
Labels: S-waiting-on-bors

#81566 Add a test for #71202
  src/test/ui/const-generics/issue-71202.rs
Labels: S-waiting-on-bors

#81568 Fix an old FIXME in redundant paren lint
  compiler/rustc_lint/src/unused.rs
Labels: S-waiting-on-bors

#81571 Fix typo in E0759
  compiler/rustc_error_codes/src/error_codes/E0759.md
Labels: S-waiting-on-bors

#81572 Edit multiple error code Markdown files
  compiler/rustc_error_codes/src/error_codes/E0013.md
  compiler/rustc_error_codes/src/error_codes/E0038.md
  compiler/rustc_error_codes/src/error_codes/E0107.md
  compiler/rustc_error_codes/src/error_codes/E0116.md
  compiler/rustc_error_codes/src/error_codes/E0277.md
  compiler/rustc_error_codes/src/error_codes/E0309.md
  compiler/rustc_error_codes/src/error_codes/E0597.md
  compiler/rustc_error_codes/src/error_codes/E0658.md
  compiler/rustc_error_codes/src/error_codes/E0754.md
Labels: S-waiting-on-bors

#81589 Fix small typo in string.rs
  library/alloc/src/string.rs
Labels: S-waiting-on-bors

#81590 Stabilize int_bits_const
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_serialize/tests/leb128.rs
  library/alloc/src/lib.rs
  library/alloc/tests/lib.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/lib.rs
  library/panic_unwind/src/lib.rs
Labels: S-waiting-on-bors, T-libs

#81255 Don't link with --export-dynamic on wasm32-wasi
  compiler/rustc_target/src/spec/wasm32_base.rs
  compiler/rustc_target/src/spec/wasm32_unknown_emscripten.rs
  compiler/rustc_target/src/spec/wasm32_unknown_unknown.rs
Labels: A-linkage, O-wasm, S-waiting-on-bors, T-compiler

#80092 2229: Fix issues with move closures and mutability
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/move_errors.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/var_name.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/nll.rs
  compiler/rustc_mir/src/borrow_check/path_utils.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/by_value.rs
  src/test/ui/closures/2229_closure_analysis/by_value.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm-borrow.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm-borrow.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/mut_ref.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/mut_ref.stderr
  src/test/ui/closures/2229_closure_analysis/move_closure.rs
  src/test/ui/closures/2229_closure_analysis/move_closure.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/by_value.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/by_value.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/move_closure.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/move_closure.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/mut_ref.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/mut_ref.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/mut_ref_struct_mem.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/mut_ref_struct_mem.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/unsafe_ptr.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/unsafe_ptr.stderr
  src/test/ui/closures/2229_closure_analysis/unsafe_ptr.rs
  src/test/ui/closures/2229_closure_analysis/unsafe_ptr.stderr
Labels: S-waiting-on-bors

#80404 Remove const_in_array_repeat
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_middle/src/traits/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/transform/promote_consts.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  library/alloc/src/lib.rs
  src/doc/unstable-book/src/language-features/const-in-array-repeat-expressions.md
  src/test/ui/array-slice-vec/repeat_empty_ok.rs
  src/test/ui/array-slice-vec/repeat_empty_ok.stderr
  src/test/ui/consts/const-blocks/const-repeat.rs
  src/test/ui/consts/const-blocks/fn-call-in-const.rs
  src/test/ui/consts/const-blocks/fn-call-in-non-const.rs
  src/test/ui/consts/const-blocks/fn-call-in-non-const.stderr
  src/test/ui/consts/const-blocks/migrate-fail.rs
  src/test/ui/consts/const-blocks/migrate-fail.stderr
  src/test/ui/consts/const-blocks/migrate-pass.rs
  src/test/ui/consts/const-blocks/nll-fail.rs
  src/test/ui/consts/const-blocks/nll-fail.stderr
  src/test/ui/consts/const-blocks/nll-pass.rs
  src/test/ui/consts/const-blocks/run-pass.rs
  src/test/ui/consts/const-blocks/trait-error.rs
  src/test/ui/consts/const-blocks/trait-error.stderr
  src/test/ui/feature-gates/feature-gate-const_in_array_repeat_expressions.rs
  src/test/ui/feature-gates/feature-gate-const_in_array_repeat_expressions.stderr
  src/test/ui/unused/unused-closure.rs
  src/test/ui/unused/unused-closure.stderr
Labels: S-waiting-on-bors

#80851 Implement Rust 2021 panic
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_builtin_macros/src/panic.rs
  compiler/rustc_lint/src/panic_fmt.rs
  compiler/rustc_span/src/symbol.rs
  library/core/src/macros/mod.rs
  library/core/src/panic.rs
  library/std/src/lib.rs
  library/std/src/macros.rs
  library/std/src/panic.rs
  src/test/mir-opt/const_prop/control_flow_simplification.hello.ConstProp.diff
  src/test/mir-opt/issue_73223.main.PreCodegen.32bit.diff
  src/test/mir-opt/issue_73223.main.PreCodegen.64bit.diff
  src/test/mir-opt/issue_73223.main.SimplifyArmIdentity.32bit.diff
  src/test/mir-opt/issue_73223.main.SimplifyArmIdentity.64bit.diff
  src/test/mir-opt/issue_76432.test.SimplifyComparisonIntegral.diff
  src/test/mir-opt/no_drop_for_inactive_variant.unwrap.SimplifyCfg-elaborate-drops.after.mir
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.executor-block_on-VTABLE-{closure#0}.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.executor-block_on-VTABLE-{closure#1}.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.executor-block_on-VTABLE-{closure#2}.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.closure/closure.main-{closure#5}.-------.InstrumentCoverage.0.html
  src/test/ui/consts/const-eval/feature-gate-const_panic.stderr
  src/test/ui/consts/const-eval/unwind-abort.stderr
  src/test/ui/consts/const-unwrap.stderr
  src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs
  src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.stderr
  src/tools/clippy/tests/ui/panicking_macros.stderr
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#81504 Suggest accessing field when appropriate
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  src/test/ui/suggestions/field-access.fixed
  src/test/ui/suggestions/field-access.rs
  src/test/ui/suggestions/field-access.stderr
Labels: S-waiting-on-bors

#81529 Fix invalid camel case suggestion involving unicode idents
  compiler/rustc_lint/src/nonstandard_style.rs
  src/test/ui/lint/special-upper-lower-cases.stderr
Labels: A-diagnostics, A-suggestion-diagnostics, D-invalid-suggestion, S-waiting-on-bors

#81592 Rustdoc UI fixes
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#81594 Avoid building LLVM just for llvm-dwp
  src/bootstrap/compile.rs
Labels: A-cranelift, A-rustbuild, S-waiting-on-bors

#81598 Fix calling convention for CRT startup
  library/std/src/sys/windows/compat.rs
Labels: S-waiting-on-bors

#81618 Sync rustc_codegen_cranelift
  compiler/rustc_codegen_cranelift/.github/workflows/main.yml
  compiler/rustc_codegen_cranelift/.gitignore
  compiler/rustc_codegen_cranelift/.vscode/settings.json
  compiler/rustc_codegen_cranelift/Cargo.lock
  compiler/rustc_codegen_cranelift/Cargo.toml
  compiler/rustc_codegen_cranelift/Readme.md
  compiler/rustc_codegen_cranelift/build.sh
  compiler/rustc_codegen_cranelift/build_sysroot/Cargo.lock
  compiler/rustc_codegen_cranelift/build_sysroot/Cargo.toml
  compiler/rustc_codegen_cranelift/build_sysroot/build_sysroot.sh
  compiler/rustc_codegen_cranelift/build_sysroot/prepare_sysroot_src.sh
  compiler/rustc_codegen_cranelift/clean_all.sh
  compiler/rustc_codegen_cranelift/crate_patches/0001-compiler-builtins-Remove-rotate_left-from-Int.patch
  compiler/rustc_codegen_cranelift/example/alloc_example.rs
  compiler/rustc_codegen_cranelift/example/mini_core.rs
  compiler/rustc_codegen_cranelift/example/mod_bench.rs
  compiler/rustc_codegen_cranelift/patches/0022-core-Disable-not-compiling-tests.patch
  compiler/rustc_codegen_cranelift/rust-toolchain
  compiler/rustc_codegen_cranelift/scripts/config.sh
  compiler/rustc_codegen_cranelift/scripts/ext_config.sh
  compiler/rustc_codegen_cranelift/scripts/tests.sh
  compiler/rustc_codegen_cranelift/src/abi/comments.rs
  compiler/rustc_codegen_cranelift/src/abi/mod.rs
  compiler/rustc_codegen_cranelift/src/abi/pass_mode.rs
  compiler/rustc_codegen_cranelift/src/abi/returning.rs
  compiler/rustc_codegen_cranelift/src/analyze.rs
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/bin/cg_clif_build_sysroot.rs
  compiler/rustc_codegen_cranelift/src/codegen_i128.rs
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/driver/jit.rs
  compiler/rustc_codegen_cranelift/src/driver/mod.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/main_shim.rs
  compiler/rustc_codegen_cranelift/src/num.rs
  compiler/rustc_codegen_cranelift/src/pretty_clif.rs
  compiler/rustc_codegen_cranelift/src/value_and_place.rs
  compiler/rustc_codegen_cranelift/test.sh
Labels: A-codegen, A-cranelift, S-waiting-on-bors, T-compiler

#81364 Improve `rustc_mir_build::matches` docs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/matches/test.rs
Labels: A-mir, A-patterns, C-enhancement, S-waiting-on-bors, T-compiler, T-doc

#81463 Rename NLL* to Nll* accordingly to C-CASE
  compiler/rustc_infer/src/infer/canonical/query_response.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_infer/src/infer/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/region_errors.rs
  compiler/rustc_mir/src/borrow_check/region_infer/dump_mir.rs
  compiler/rustc_mir/src/borrow_check/region_infer/mod.rs
  compiler/rustc_mir/src/borrow_check/renumber.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/relate_tys.rs
  compiler/rustc_mir/src/borrow_check/universal_regions.rs
Labels: S-waiting-on-bors

#81536 Indicate both start and end of pass RSS in time-passes output
  compiler/rustc_codegen_cranelift/src/bin/cg_clif.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_data_structures/src/profiling.rs
  compiler/rustc_driver/src/lib.rs
Labels: S-waiting-on-bors, T-compiler

#78641 Let io::copy reuse BufWriter buffers
  library/std/src/io/buffered/bufwriter.rs
  library/std/src/io/copy.rs
  library/std/src/io/util/tests.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs

#79291 Add error message for private fn
  Cargo.lock
  compiler/rustc_privacy/Cargo.toml
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  src/test/ui/const-generics/const_evaluatable_checked/eval-privacy.rs
  src/test/ui/const-generics/const_evaluatable_checked/eval-privacy.stderr
Labels: S-waiting-on-bors

#80641 Add visitors for checking #[inline]
  compiler/rustc_hir/src/target.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_passes/src/check_attr.rs
  src/test/ui/attr-usage-inline.rs
  src/test/ui/attr-usage-inline.stderr
  src/test/ui/internal/internal-unstable.rs
  src/test/ui/internal/internal-unstable.stderr
  src/test/ui/proc-macro/ambiguous-builtin-attrs.rs
  src/test/ui/proc-macro/ambiguous-builtin-attrs.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81557 Fix primitive search in parameters and returned values
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/formats/item_type.rs
  src/librustdoc/html/render/cache.rs
  src/test/rustdoc-js/primitive.js
  src/test/rustdoc-js/primitive.rs
  src/tools/rustdoc-js/tester.js
Labels: A-rustdoc-search, A-type-based-search, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81539 Update armhf-gnu to Ubuntu 20.04
  src/ci/docker/host-x86_64/armhf-gnu/Dockerfile
  src/ci/docker/host-x86_64/armhf-gnu/vexpress_config
  src/tools/remote-test-client/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#79015 add `Vec::extend_from_within` method under `vec_extend_from_within` feature gate
  library/alloc/src/lib.rs
  library/alloc/src/vec/mod.rs
  library/alloc/tests/lib.rs
  library/alloc/tests/vec.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#81577 const_evaluatable: consider sub-expressions to be evaluatable
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  src/test/ui/const-generics/const_evaluatable_checked/nested_uneval_unification-1.rs
  src/test/ui/const-generics/const_evaluatable_checked/subexprs_are_const_evalutable.rs
Labels: A-const-generics, F-const_evaluatable_checked, S-waiting-on-bors

#81599 Implement `TrustedLen` for `Fuse<I: TrustedLen>`
  library/core/src/iter/adapters/fuse.rs
Labels: S-waiting-on-bors

#81608 Improve handling of spans around macro result parse errors
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_span/src/source_map.rs
  src/test/ui/proc-macro/issue-81543-item-parse-err.rs
  src/test/ui/proc-macro/issue-81543-item-parse-err.stderr
  src/test/ui/proc-macro/lifetimes.stderr
Labels: S-waiting-on-bors

#81609 Remove the remains of query categories
  compiler/rustc_macros/src/query.rs
  compiler/rustc_middle/src/query/mod.rs
Labels: S-waiting-on-bors

#81630 Fix overflowing text on mobile when sidebar is displayed
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#81631 Remove unneeded `mut` variable
  compiler/rustc_resolve/src/late/lifetimes.rs
Labels: S-waiting-on-bors

#81660 Rollup of 11 pull requests
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_macros/src/query.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_resolve/src/late/lifetimes.rs
  compiler/rustc_span/src/source_map.rs
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/check/writeback.rs
  library/core/src/iter/adapters/fuse.rs
  library/std/src/backtrace.rs
  library/std/src/backtrace/tests.rs
  src/librustdoc/html/mod.rs
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/lib.rs
  src/test/ui/associated-types/issue-38917.rs
  src/test/ui/associated-types/issue-40093.rs
  src/test/ui/associated-types/issue-43475.rs
  src/test/ui/associated-types/issue-63591.rs
  src/test/ui/cast/fat-ptr-cast-rpass.rs
  src/test/ui/cast/fat-ptr-cast.rs
  src/test/ui/cast/fat-ptr-cast.stderr
  src/test/ui/cast/issue-17444.rs
  src/test/ui/cast/issue-17444.stderr
  src/test/ui/cast/unsupported-cast.rs
  src/test/ui/cast/unsupported-cast.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/no_migrations.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.stderr
  src/test/ui/const-generics/const_evaluatable_checked/nested_uneval_unification-1.rs
  src/test/ui/const-generics/const_evaluatable_checked/subexprs_are_const_evalutable.rs
  src/test/ui/nll/closure-requirements/escape-upvar-nested.stderr
  src/test/ui/nll/closure-requirements/escape-upvar-ref.stderr
  src/test/ui/proc-macro/issue-81543-item-parse-err.rs
  src/test/ui/proc-macro/issue-81543-item-parse-err.stderr
  src/test/ui/proc-macro/lifetimes.stderr
  src/test/ui/unsupported-cast.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#81485 Add some tests for associated-type-bounds issues
  src/test/ui/associated-types/issue-38917.rs
  src/test/ui/associated-types/issue-40093.rs
  src/test/ui/associated-types/issue-43475.rs
  src/test/ui/associated-types/issue-63591.rs
Labels: S-waiting-on-bors

#81492 rustdoc: Note why `rustdoc::html::markdown` is public
  src/librustdoc/html/mod.rs
  src/librustdoc/lib.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#81022 Add Frames Iterator for Backtrace
  library/std/src/backtrace.rs
  library/std/src/backtrace/tests.rs
Labels: S-waiting-on-bors

#81481 move some tests
  src/test/ui/cast/fat-ptr-cast-rpass.rs
  src/test/ui/cast/fat-ptr-cast.rs
  src/test/ui/cast/fat-ptr-cast.stderr
  src/test/ui/cast/issue-17444.rs
  src/test/ui/cast/issue-17444.stderr
  src/test/ui/cast/unsupported-cast.rs
  src/test/ui/cast/unsupported-cast.stderr
  src/test/ui/unsupported-cast.rs
Labels: S-waiting-on-bors

#80629 Add lint for 2229 migrations
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/check/writeback.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/no_migrations.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.stderr
  src/test/ui/nll/closure-requirements/escape-upvar-nested.stderr
  src/test/ui/nll/closure-requirements/escape-upvar-ref.stderr
Labels: A-closures, A-lint, S-waiting-on-bors

#80843 Bump rustfmt version
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
  compiler/rustc_errors/src/diagnostic_builder.rs
  compiler/rustc_errors/src/snippet.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/trait_impl_difference.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/diagnostics.rs
  compiler/rustc_middle/src/ty/error.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_mir_build/src/build/expr/as_place.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/expr/into.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/matches/util.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_mir_build/src/build/scope.rs
  compiler/rustc_parse/src/parser/nonterminal.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_target/src/abi/call/mod.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_typeck/src/astconv/generics.rs
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  library/core/src/default.rs
  rustfmt.toml
  src/bootstrap/bin/main.rs
  src/stage0.txt
Labels: S-waiting-on-bors, merged-by-bors

#81405 Box the biggest ast::ItemKind variants
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_lowering/src/item.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_ast_passes/src/lib.rs
  compiler/rustc_ast_passes/src/node_count.rs
  compiler/rustc_ast_pretty/src/lib.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
  compiler/rustc_builtin_macros/src/deriving/mod.rs
  compiler/rustc_builtin_macros/src/global_allocator.rs
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_builtin_macros/src/test.rs
  compiler/rustc_builtin_macros/src/test_harness.rs
  compiler/rustc_interface/src/lib.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_lint/src/internal.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
  src/tools/clippy/clippy_lints/src/doc.rs
  src/tools/clippy/clippy_lints/src/excessive_bools.rs
  src/tools/clippy/clippy_lints/src/non_expressive_names.rs
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
  src/tools/clippy/clippy_lints/src/write.rs
Labels: S-waiting-on-bors, merged-by-bors

#81541 Fix early lints inside an async desugaring
  compiler/rustc_lint/src/early.rs
  src/test/ui/lint/semicolon-in-expressions-from-macros/semicolon-in-expressions-from-macros.rs
  src/test/ui/lint/semicolon-in-expressions-from-macros/semicolon-in-expressions-from-macros.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81517 Remove remnants of the santizer runtime crates from bootstrap
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#81530 sys: use `process::abort()` instead of `arch::wasm32::unreachable()`
  library/std/src/sys/wasm/thread.rs
Labels: S-waiting-on-bors

#81544 Add better diagnostic for unbounded Abst. Const
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  src/test/ui/const-generics/const_evaluatable_checked/cross_crate_predicate.stderr
  src/test/ui/const-generics/const_evaluatable_checked/different-fn.stderr
  src/test/ui/const_evaluatable/needs_where_clause.rs
  src/test/ui/const_evaluatable/needs_where_clause.stderr
  src/test/ui/const_evaluatable/no_where_clause.rs
  src/test/ui/const_evaluatable/no_where_clause.stderr
Labels: S-waiting-on-bors

#81588 Add doc aliases for "delete"
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/set.rs
  library/core/src/mem/mod.rs
  library/std/src/collections/hash/map.rs
  library/std/src/collections/hash/set.rs
  library/std/src/fs.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#81603 rustbuild: Don't build compiler twice for error-index-generator.
  src/bootstrap/builder/tests.rs
  src/bootstrap/doc.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
Labels: S-waiting-on-bors

#81634 Add long explanation e0521
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0521.md
  src/test/ui/async-await/issues/issue-62097.nll.stderr
  src/test/ui/borrowck/issue-45983.stderr
  src/test/ui/borrowck/issue-7573.stderr
  src/test/ui/borrowck/regions-escape-bound-fn-2.stderr
  src/test/ui/borrowck/regions-escape-bound-fn.stderr
  src/test/ui/borrowck/regions-escape-unboxed-closure.stderr
  src/test/ui/closures/closure-expected-type/expect-region-supply-region.stderr
  src/test/ui/generator/ref-escapes-but-not-over-yield.stderr
  src/test/ui/impl-header-lifetime-elision/dyn-trait.nll.stderr
  src/test/ui/issues/issue-16683.nll.stderr
  src/test/ui/issues/issue-17758.nll.stderr
  src/test/ui/lifetimes/lifetime-bound-will-change-warning.nll.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-shorter-to-static-comparing-against-free.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-shorter-to-static-no-bound.stderr
  src/test/ui/nll/closure-requirements/propagate-approximated-shorter-to-static-wrong-bound.stderr
  src/test/ui/nll/outlives-suggestion-simple.stderr
  src/test/ui/nll/user-annotations/closure-substs.stderr
  src/test/ui/object-lifetime/object-lifetime-default-mybox.nll.stderr
  src/test/ui/regions/issue-78262.nll.stderr
  src/test/ui/regions/region-invariant-static-error-reporting.nll.stderr
  src/test/ui/regions/regions-bounded-method-type-parameters-trait-bound.nll.stderr
  src/test/ui/regions/regions-nested-fns.nll.stderr
  src/test/ui/suggestions/impl-on-dyn-trait-with-implicit-static-bound.nll.stderr
Labels: S-waiting-on-bors

#81636 Directly use `Option<&[T]>` instead of converting from `Option<&Vec<T>>` later on
  compiler/rustc_resolve/src/late/lifetimes.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#81647 Fix bug with assert!() calling the wrong edition of panic!().
  compiler/rustc_builtin_macros/src/assert.rs
  library/core/src/macros/mod.rs
  src/test/ui/panics/panic-2021.rs
  src/test/ui/panics/panic-2021.stderr
Labels: S-waiting-on-bors

#81655 Improve wording of suggestion about accessing field
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  src/test/ui/suggestions/field-access.fixed
  src/test/ui/suggestions/field-access.rs
  src/test/ui/suggestions/field-access.stderr
Labels: S-waiting-on-bors

#81665 Fix out of date `Scalar` documentation
  compiler/rustc_middle/src/mir/interpret/value.rs
Labels: S-waiting-on-bors

#81671 Add more associated type tests
  src/test/ui/associated-types/issue-24159.rs
  src/test/ui/associated-types/issue-37808.rs
  src/test/ui/associated-types/issue-37883.rs
  src/test/ui/associated-types/issue-39532.rs
Labels: S-waiting-on-bors

#80593 Upgrade Chalk
  Cargo.lock
  compiler/rustc_infer/src/infer/canonical/canonicalizer.rs
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_middle/src/traits/chalk.rs
  compiler/rustc_traits/Cargo.toml
  compiler/rustc_traits/src/chalk/db.rs
  compiler/rustc_traits/src/chalk/lowering.rs
  compiler/rustc_traits/src/chalk/mod.rs
Labels: S-waiting-on-bors

#81535 Update test-various to Ubuntu 20.04
  src/ci/docker/host-x86_64/test-various/Dockerfile
  src/test/ui/command/command-setgroups.rs
Labels: S-waiting-on-bors, merged-by-bors

#81346 Add a new ABI to support cmse_nonsecure_call
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_codegen_cranelift/src/abi/mod.rs
  compiler/rustc_codegen_llvm/src/abi.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_llvm/src/llvm/mod.rs
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0781.md
  compiler/rustc_feature/src/active.rs
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/abi/call/mod.rs
  compiler/rustc_target/src/spec/abi.rs
  compiler/rustc_typeck/src/check/check.rs
  src/doc/unstable-book/src/language-features/abi-c-cmse-nonsecure-call.md
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/gate_test.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/gate_test.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-registers.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/wrong-abi-location-1.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/wrong-abi-location-1.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/wrong-abi-location-2.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-call/wrong-abi-location-2.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/gate_test.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/gate_test.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/params-on-registers.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/params-on-stack.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/params-on-stack.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/trustzone-only.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/trustzone-only.stderr
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/wrong-abi.rs
  src/test/ui/cmse-nonsecure/cmse-nonsecure-entry/wrong-abi.stderr
  src/test/ui/codemap_tests/unicode.stderr
  src/test/ui/parser/issue-8537.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81573 Add some links to the cell docs.
  library/core/src/cell.rs
Labels: S-waiting-on-bors

#81679 Bind all clean::Type variants and remove FIXME
  src/librustdoc/html/render/cache.rs
Labels: S-waiting-on-bors, T-rustdoc

#81681 Better styling of "Switch result tab" shortcut
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
Labels: S-waiting-on-bors

#81694 Rollup of 4 pull requests
  library/core/src/cell.rs
  library/core/src/iter/traits/iterator.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/dark.css
Labels: S-waiting-on-bors, merged-by-bors, rollup

#81144 Fixed formatting typo in map_while docs
  library/core/src/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#81699 Really fix early lints inside an async desugaring
  compiler/rustc_lint/src/early.rs
  src/test/ui/lint/semicolon-in-expressions-from-macros/semicolon-in-expressions-from-macros.rs
Labels: S-waiting-on-bors, merged-by-bors

#81294 Use ufcs in derive(Debug)
  compiler/rustc_builtin_macros/src/deriving/debug.rs
  compiler/rustc_span/src/symbol.rs
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.partial_eq/partial_eq.{impl#7}-fmt.-------.InstrumentCoverage.0.html
  src/test/ui/derives/derive-Debug-use-ufcs-struct.rs
  src/test/ui/derives/derive-Debug-use-ufcs-tuple.rs
  src/test/ui/methods/method-lookup-order.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#81532 Remove incorrect `delay_span_bug`
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/typeck/issue-80207-unsized-return.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated, stable-nominated

#81692 Update clippy
  src/tools/clippy/CHANGELOG.md
  src/tools/clippy/CONTRIBUTING.md
  src/tools/clippy/clippy_dev/src/bless.rs
  src/tools/clippy/clippy_dev/src/fmt.rs
  src/tools/clippy/clippy_dev/src/lib.rs
  src/tools/clippy/clippy_dev/src/ra_setup.rs
  src/tools/clippy/clippy_dev/src/serve.rs
  src/tools/clippy/clippy_lints/src/doc.rs
  src/tools/clippy/clippy_lints/src/excessive_bools.rs
  src/tools/clippy/clippy_lints/src/exhaustive_items.rs
  src/tools/clippy/clippy_lints/src/lib.rs
  src/tools/clippy/clippy_lints/src/matches.rs
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
  src/tools/clippy/clippy_lints/src/utils/diagnostics.rs
  src/tools/clippy/clippy_lints/src/utils/internal_lints.rs
  src/tools/clippy/clippy_lints/src/utils/mod.rs
  src/tools/clippy/clippy_lints/src/write.rs
  src/tools/clippy/doc/adding_lints.md
  src/tools/clippy/doc/basics.md
  src/tools/clippy/mini-macro/src/lib.rs
  src/tools/clippy/rust-toolchain
  src/tools/clippy/tests/ui/doc_panics.rs
  src/tools/clippy/tests/ui/doc_panics.stderr
  src/tools/clippy/tests/ui/exhaustive_items.fixed
  src/tools/clippy/tests/ui/exhaustive_items.rs
  src/tools/clippy/tests/ui/exhaustive_items.stderr
  src/tools/clippy/tests/ui/let_and_return.rs
  src/tools/clippy/tests/ui/let_and_return.stderr
  src/tools/clippy/tests/ui/match_overlapping_arm.rs
  src/tools/clippy/tests/ui/match_overlapping_arm.stderr
  src/tools/clippy/tests/ui/should_impl_trait/corner_cases.rs
  src/tools/clippy/tests/ui/should_impl_trait/method_list_1.rs
  src/tools/clippy/tests/ui/should_impl_trait/method_list_1.stderr
  src/tools/clippy/tests/ui/should_impl_trait/method_list_2.rs
  src/tools/clippy/tests/ui/should_impl_trait/method_list_2.stderr
Labels: S-waiting-on-bors

#81715 Reduce tab formatting assertions to debug only
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_errors/src/styled_buffer.rs
Labels: A-diagnostics, S-waiting-on-bors

#81716 Fix non-existent-field ICE for generic fields.
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/suggestions/non-existent-field-present-in-subfield.fixed
  src/test/ui/suggestions/non-existent-field-present-in-subfield.rs
Labels: I-ICE, S-waiting-on-bors, T-compiler

#81717 Fix panic when emitting diagnostic for closure mutable binding error
  compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs
  src/test/ui/closures/issue-81700-mut-borrow.rs
  src/test/ui/closures/issue-81700-mut-borrow.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81762 CI: only copy python.exe to python3.exe if the latter does not exist
  src/ci/scripts/install-msys2.sh
Labels: S-waiting-on-bors, merged-by-bors

#81556 introduce future-compatibility warning for forbidden lint groups
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_middle/src/lint.rs
  src/test/ui/lint/forbid-group-group-1.rs
  src/test/ui/lint/forbid-group-group-1.stderr
  src/test/ui/lint/forbid-group-group-2.rs
  src/test/ui/lint/forbid-group-group-2.stderr
  src/test/ui/lint/forbid-group-member.rs
  src/test/ui/lint/forbid-group-member.stderr
  src/test/ui/lint/forbid-member-group.rs
  src/test/ui/lint/forbid-member-group.stderr
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.stderr
  src/test/ui/lint/issue-80988.rs
  src/test/ui/lint/issue-80988.stderr
  src/test/ui/lint/issue-81218.rs
  src/test/ui/lint/outer-forbid.rs
  src/test/ui/lint/outer-forbid.stderr
Labels: C-future-compatibility, S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated

#81710 OsStr eq_ignore_ascii_case takes arg by value
  library/std/src/ffi/os_str.rs
Labels: S-waiting-on-bors

#81711 add #[inline] to all the public IpAddr functions
  library/std/src/net/ip.rs
Labels: A-io, S-waiting-on-bors, T-libs-impl

#81725 Move test to be with the others
  src/test/ui/or-patterns/macro-pat.rs
Labels: S-waiting-on-bors

#81727 Revert stabilizing integer::BITS.
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_serialize/tests/leb128.rs
  library/alloc/src/lib.rs
  library/alloc/tests/lib.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/lib.rs
  library/panic_unwind/src/lib.rs
Labels: S-waiting-on-bors, T-libs

#81745 Stabilize poison API of Once, rename poisoned()
  library/std/src/sync/once.rs
  library/std/src/sync/once/tests.rs
Labels: S-waiting-on-bors, T-libs

#79805 Rename Iterator::fold_first to reduce and stabilize it
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/lib.rs
  library/core/src/iter/traits/iterator.rs
Labels: A-iterators, S-waiting-on-bors, S-waiting-on-fcp, T-libs, disposition-merge, finished-final-comment-period, needs-fcp, to-announce

#74304 Stabilize the Wake trait
  library/alloc/src/task.rs
  library/std/src/lib.rs
  src/test/ui/async-await/issue-73137.rs
Labels: A-async-await, I-nominated, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, relnotes

#81688 Use `# min-llvm-version: 11.0` to force a minimum LLVM version
  src/test/run-make-fulldeps/coverage-llvmir/Makefile
  src/test/run-make-fulldeps/coverage-reports/Makefile
  src/test/run-make-fulldeps/coverage-spanview/Makefile
  src/test/run-make-fulldeps/coverage/coverage_tools.mk
Labels: A-testsuite, S-waiting-on-bors, T-compiler, merged-by-bors

#81736 rustc_codegen_ssa: tune codegen scheduling to reduce memory usage
  Cargo.lock
  compiler/rustc_codegen_ssa/Cargo.toml
  compiler/rustc_codegen_ssa/src/base.rs
Labels: I-compilemem, S-waiting-on-bors, T-compiler, merged-by-bors

#81497 rustdoc: Move `display_fn` struct inside `display_fn`
  src/librustdoc/html/format.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#81500 Remove struct_type from union output
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/rustdoc-json-types/lib.rs
  src/test/rustdoc-json/unions/union.rs
Labels: A-rustdoc-json, S-waiting-on-bors, T-rustdoc

#81542 Expose correct symlink API on WASI
  library/std/src/sys/wasi/ext/fs.rs
Labels: S-waiting-on-bors

#81676 Add more information to the error code for 'crate not found'
  compiler/rustc_error_codes/src/error_codes/E0463.md
Labels: A-error-codes, S-waiting-on-bors

#81682 Add additional bitset benchmarks
  compiler/rustc_index/src/bit_set/tests.rs
Labels: S-waiting-on-bors

#81730 Make `Allocator` object-safe
  library/core/src/alloc/mod.rs
  src/test/ui/allocator/object-safe.rs
Labels: S-waiting-on-bors

#81763 Cleanup rustdoc pass descriptions a bit
  src/librustdoc/core.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/non_autolinks.rs
  src/librustdoc/passes/strip_hidden.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#81767 Update LayoutError/LayoutErr stability attributes
  library/core/src/alloc/layout.rs
  library/core/src/alloc/mod.rs
Labels: S-waiting-on-bors, T-libs, beta-accepted, beta-nominated

#81771 Indicate change in RSS from start to end of pass in time-passes output
  compiler/rustc_data_structures/src/profiling.rs
Labels: S-waiting-on-bors, T-compiler

#81781 Fix `install-awscli.sh` error in CI
  src/ci/scripts/install-awscli.sh
Labels: S-waiting-on-bors

#80726 relax adt unsizing requirements
  compiler/rustc_feature/src/active.rs
  compiler/rustc_index/src/bit_set.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_trait_selection/src/traits/select/confirmation.rs
  src/test/ui/feature-gates/feature-gate-relaxed_struct_unsize.rs
  src/test/ui/feature-gates/feature-gate-relaxed_struct_unsize.stderr
  src/test/ui/unsized/unchanged-param.rs
Labels: I-nominated, S-waiting-on-bors, T-lang, needs-fcp

#81307 Handle `Span`s for byte and raw strings and add more detail
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_parse/src/lexer/unescape_error_reporting.rs
  src/test/ui/attributes/key-value-non-ascii.rs
  src/test/ui/attributes/key-value-non-ascii.stderr
  src/test/ui/parser/ascii-only-character-escape.rs
  src/test/ui/parser/ascii-only-character-escape.stderr
  src/test/ui/parser/bad-char-literals.rs
  src/test/ui/parser/bad-char-literals.stderr
  src/test/ui/parser/byte-literals.rs
  src/test/ui/parser/byte-literals.stderr
  src/test/ui/parser/byte-string-literals.rs
  src/test/ui/parser/byte-string-literals.stderr
  src/test/ui/parser/issue-23620-invalid-escapes.rs
  src/test/ui/parser/issue-23620-invalid-escapes.stderr
  src/test/ui/parser/issue-43692.stderr
  src/test/ui/parser/issue-62913.stderr
  src/test/ui/parser/issue-64732.stderr
  src/test/ui/parser/lex-bad-char-literals-1.stderr
  src/test/ui/parser/lex-bad-char-literals-7.rs
  src/test/ui/parser/lex-bad-char-literals-7.stderr
  src/test/ui/parser/lex-bare-cr-string-literal-doc-comment.rs
  src/test/ui/parser/lex-bare-cr-string-literal-doc-comment.stderr
  src/test/ui/parser/macro/literals-are-validated-before-expansion.stderr
  src/test/ui/parser/new-unicode-escapes-1.rs
  src/test/ui/parser/new-unicode-escapes-1.stderr
  src/test/ui/parser/new-unicode-escapes-2.rs
  src/test/ui/parser/new-unicode-escapes-2.stderr
  src/test/ui/parser/new-unicode-escapes-3.stderr
  src/test/ui/parser/new-unicode-escapes-4.rs
  src/test/ui/parser/new-unicode-escapes-4.stderr
  src/test/ui/parser/raw/raw-byte-string-literals.stderr
  src/test/ui/parser/trailing-carriage-return-in-string.rs
  src/test/ui/parser/trailing-carriage-return-in-string.stderr
  src/test/ui/parser/wrong-escape-of-curly-braces.rs
  src/test/ui/parser/wrong-escape-of-curly-braces.stderr
Labels: A-diagnostics, S-waiting-on-bors

#81318 rustdoc-json: Fix has_body
  src/librustdoc/json/conversions.rs
  src/test/rustdoc-json/traits/has_body.rs
Labels: A-rustdoc-json, S-waiting-on-bors, T-rustdoc

#81456 Make remote-test-server easier to use with new targets
  src/bootstrap/test.rs
  src/tools/remote-test-server/src/main.rs
Labels: S-waiting-on-bors

#79554 Generic associated types in trait paths
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_lowering/src/path.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  src/test/ui/generic-associated-types/gat-in-trait-path-undeclared-lifetime.rs
  src/test/ui/generic-associated-types/gat-in-trait-path-undeclared-lifetime.stderr
  src/test/ui/generic-associated-types/gat-in-trait-path.rs
  src/test/ui/generic-associated-types/gat-in-trait-path.stderr
  src/test/ui/generic-associated-types/gat-trait-path-generic-type-arg.rs
  src/test/ui/generic-associated-types/gat-trait-path-generic-type-arg.stderr
  src/test/ui/generic-associated-types/gat-trait-path-missing-lifetime.rs
  src/test/ui/generic-associated-types/gat-trait-path-missing-lifetime.stderr
  src/test/ui/generic-associated-types/gat-trait-path-parenthesised-args.rs
  src/test/ui/generic-associated-types/gat-trait-path-parenthesised-args.stderr
  src/test/ui/generic-associated-types/issue-67510-pass.rs
  src/test/ui/generic-associated-types/issue-67510-pass.stderr
  src/test/ui/generic-associated-types/issue-67510.rs
  src/test/ui/generic-associated-types/issue-67510.stderr
  src/test/ui/generic-associated-types/issue-68648-1.rs
  src/test/ui/generic-associated-types/issue-68648-1.stderr
  src/test/ui/generic-associated-types/issue-68648-2.rs
  src/test/ui/generic-associated-types/issue-68648-2.stderr
  src/test/ui/generic-associated-types/issue-68649-pass.rs
  src/test/ui/generic-associated-types/issue-68649-pass.stderr
  src/test/ui/generic-associated-types/issue-74684-1.rs
  src/test/ui/generic-associated-types/issue-74684-1.stderr
  src/test/ui/generic-associated-types/issue-74684-2.rs
  src/test/ui/generic-associated-types/issue-74684-2.stderr
  src/test/ui/generic-associated-types/issue-76535.rs
  src/test/ui/generic-associated-types/issue-76535.stderr
  src/test/ui/generic-associated-types/issue-79422.rs
  src/test/ui/generic-associated-types/issue-79422.stderr
  src/test/ui/generic-associated-types/issue-80433-reduced.rs
  src/test/ui/generic-associated-types/issue-80433.rs
  src/test/ui/generic-associated-types/issue-80433.stderr
  src/test/ui/generic-associated-types/parse/trait-path-type-error-once-implemented.rs
  src/test/ui/generic-associated-types/parse/trait-path-type-error-once-implemented.stderr
  src/test/ui/generic-associated-types/parse/trait-path-unimplemented.rs
  src/test/ui/generic-associated-types/parse/trait-path-unimplemented.stderr
Labels: A-traits, F-generic_associated_types, S-waiting-on-bors

#81257 Revert 78373 ("dont leak return value after panic in drop")
  compiler/rustc_mir_build/src/build/block.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_mir_build/src/build/expr/as_temp.rs
  compiler/rustc_mir_build/src/build/expr/into.rs
  compiler/rustc_mir_build/src/build/expr/stmt.rs
  compiler/rustc_mir_build/src/build/into.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_mir_build/src/build/scope.rs
  library/alloc/src/collections/btree/map/tests.rs
  src/test/mir-opt/basic_assignment.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/box_expr.main.ElaborateDrops.before.mir
  src/test/mir-opt/inline/inline_diverging.h.Inline.diff
  src/test/mir-opt/issue_41110.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue_41110.test.ElaborateDrops.after.mir
  src/test/mir-opt/issue_41888.main.ElaborateDrops.after.mir
  src/test/mir-opt/issue_62289.test.ElaborateDrops.before.mir
  src/test/mir-opt/no_spurious_drop_after_call.main.ElaborateDrops.before.mir
  src/test/mir-opt/uniform_array_move_out.move_out_by_subslice.mir_map.0.mir
  src/test/mir-opt/uniform_array_move_out.move_out_from_end.mir_map.0.mir
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.uses_crate.txt
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.executor-block_on.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.async/async.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.closure/closure.main-{closure#2}.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.closure/closure.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.used_crate/used_crate.use_this_lib_crate.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.uses_crate/uses_crate.main.-------.InstrumentCoverage.0.html
  src/test/ui/drop/dynamic-drop-async.rs
  src/test/ui/drop/dynamic-drop.rs
  src/test/ui/mir/issue-80949.rs
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated, merged-by-bors

#81215 Encode MIR metadata by iterating on DefId instead of traversing the HIR tree
  compiler/rustc_metadata/src/rmeta/encoder.rs
Labels: S-waiting-on-bors, merged-by-bors

#79253 Fix rustc sysroot in systems using CAS
  compiler/rustc_session/src/filesearch.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#81795 Small refactor with Iterator::reduce
  compiler/rustc_resolve/src/diagnostics.rs
Labels: S-waiting-on-bors

#81810 Rollup of 7 pull requests
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_codegen_llvm/src/consts.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_resolve/src/diagnostics.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/btree/set/tests.rs
  library/core/src/iter/adapters/peekable.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/tests/lib.rs
  src/librustdoc/doctest.rs
  src/librustdoc/lib.rs
  src/test/mir-opt/inline/inline-instruction-set.rs
  src/test/mir-opt/inline/inline_instruction_set.default.Inline.diff
  src/test/mir-opt/inline/inline_instruction_set.t32.Inline.diff
  src/test/rustdoc-ui/issue-81662-shortness.rs
  src/test/rustdoc-ui/issue-81662-shortness.stdout
Labels: S-waiting-on-bors, merged-by-bors, rollup

#81580 Document how `MaybeUninit<Struct>` can be initialized.
  library/core/src/mem/maybe_uninit.rs
Labels: S-waiting-on-bors

#81610 BTreeMap: make Ord bound explicit, compile-test its absence
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/btree/set/tests.rs
Labels: S-waiting-on-bors

#81664 Avoid a hir access inside get_static
  compiler/rustc_codegen_llvm/src/consts.rs
Labels: A-codegen, C-cleanup, S-waiting-on-bors, T-compiler

#81675 Make rustdoc respect `--error-format short` in doctests
  src/librustdoc/doctest.rs
  src/test/rustdoc-ui/issue-81662-shortness.rs
  src/test/rustdoc-ui/issue-81662-shortness.stdout
Labels: A-doctests, S-waiting-on-bors, T-rustdoc

#81753 Never MIR inline functions with a different instruction set
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_mir/src/transform/inline.rs
  src/test/mir-opt/inline/inline-instruction-set.rs
  src/test/mir-opt/inline/inline_instruction_set.default.Inline.diff
  src/test/mir-opt/inline/inline_instruction_set.t32.Inline.diff
Labels: S-waiting-on-bors

#80011 Stabilize `peekable_next_if`
  library/core/src/iter/adapters/peekable.rs
  library/core/tests/lib.rs
  src/librustdoc/lib.rs
Labels: A-iterators, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, needs-fcp, to-announce

#81792 Bump nightly version to 1.52.0
  Cargo.lock
  src/tools/clippy/Cargo.toml
  src/tools/clippy/clippy_lints/Cargo.toml
  src/version
Labels: S-waiting-on-bors, merged-by-bors

#81680 Refactor `PrimitiveTypeTable` for Clippy
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  src/tools/clippy/clippy_lints/src/misc_early.rs
  src/tools/clippy/clippy_lints/src/utils/constants.rs
  src/tools/clippy/clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-bors

#81737 typeck: Emit structured suggestions for tuple struct syntax
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/issues/issue-4736.stderr
  src/test/ui/issues/issue-80607.stderr
  src/test/ui/numeric/numeric-fields.stderr
Labels: A-diagnostics, A-suggestion-diagnostics, C-enhancement, S-waiting-on-bors

#81738 Miscellaneous small diagnostics cleanup
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_typeck/src/check/mod.rs
  src/test/ui/const-generics/const_evaluatable_checked/cross_crate_predicate.stderr
  src/test/ui/const-generics/const_evaluatable_checked/different-fn.stderr
  src/test/ui/const_evaluatable/needs_where_clause.stderr
  src/test/ui/const_evaluatable/no_where_clause.stderr
  src/test/ui/issues/issue-18919.stderr
  src/test/ui/issues/issue-23281.stderr
  src/test/ui/suggestions/adt-param-with-implicit-sized-bound.stderr
  src/test/ui/unsized/unsized-enum.stderr
  src/test/ui/unsized/unsized-inherent-impl-self-type.stderr
  src/test/ui/unsized/unsized-struct.stderr
  src/test/ui/unsized/unsized-trait-impl-self-type.stderr
  src/test/ui/wf/wf-fn-where-clause.stderr
Labels: A-diagnostics, S-waiting-on-bors

#81766 Enable 'task list' markdown extension
  src/doc/rustdoc/src/how-to-write-documentation.md
  src/librustdoc/html/markdown.rs
  src/test/rustdoc/task-lists.rs
Labels: A-markdown-parsing, S-waiting-on-bors, T-rustdoc

#81812 Add a test for escaping LLVMisms in inline asm
  src/test/codegen/asm-sanitize-llvm.rs
Labels: S-waiting-on-bors

#81402 tidy: Run tidy style against markdown files.
  compiler/rustc_infer/src/infer/lexical_region_resolve/README.md
  src/doc/rustc/src/exploit-mitigations.md
  src/doc/rustc/src/lints/levels.md
  src/doc/rustc/src/lints/listing/index.md
  src/doc/rustc/src/what-is-rustc.md
  src/doc/rustdoc/src/advanced-features.md
  src/doc/rustdoc/src/documentation-tests.md
  src/doc/rustdoc/src/how-to-write-documentation.md
  src/doc/rustdoc/src/lints.md
  src/doc/rustdoc/src/passes.md
  src/doc/rustdoc/src/references.md
  src/doc/rustdoc/src/the-doc-attribute.md
  src/doc/rustdoc/src/what-is-rustdoc.md
  src/doc/rustdoc/src/what-to-include.md
  src/doc/unstable-book/src/compiler-flags/codegen-backend.md
  src/doc/unstable-book/src/compiler-flags/control-flow-guard.md
  src/doc/unstable-book/src/compiler-flags/profile.md
  src/doc/unstable-book/src/compiler-flags/report-time.md
  src/doc/unstable-book/src/compiler-flags/tls-model.md
  src/doc/unstable-book/src/language-features/auto-traits.md
  src/doc/unstable-book/src/language-features/custom-test-frameworks.md
  src/doc/unstable-book/src/language-features/infer-static-outlives-requirements.md
  src/doc/unstable-book/src/language-features/intrinsics.md
  src/doc/unstable-book/src/language-features/lang-items.md
  src/doc/unstable-book/src/language-features/non-ascii-idents.md
  src/doc/unstable-book/src/language-features/or-patterns.md
  src/doc/unstable-book/src/language-features/plugin.md
  src/doc/unstable-book/src/language-features/rustc-attrs.md
  src/doc/unstable-book/src/language-features/unboxed-closures.md
  src/doc/unstable-book/src/language-features/unsized-locals.md
  src/doc/unstable-book/src/language-features/unsized-tuple-coercion.md
  src/doc/unstable-book/src/library-features/asm.md
  src/doc/unstable-book/src/library-features/concat-idents.md
  src/doc/unstable-book/src/library-features/global-asm.md
  src/doc/unstable-book/src/library-features/llvm-asm.md
  src/doc/unstable-book/src/library-features/test.md
  src/doc/unstable-book/src/library-features/try-trait.md
  src/tools/tidy/src/style.rs
Labels: A-testsuite, C-cleanup, S-waiting-on-bors

#81434 BTree: fix documentation of unstable public members
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/set.rs
Labels: S-waiting-on-bors

#80883 Remove some function fields
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/formats/renderer.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/json/conversions.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81821 Upgrade wasm32 image to Ubuntu 20.04
  library/std/src/lazy/tests.rs
  library/test/src/tests.rs
  src/ci/docker/host-x86_64/wasm32/Dockerfile
Labels: S-waiting-on-bors, merged-by-bors

#81462 Add test for #75158
  src/test/ui/limits/huge-array-simple-32.rs
  src/test/ui/limits/huge-array-simple-32.stderr
  src/test/ui/limits/huge-array-simple-64.rs
  src/test/ui/limits/huge-array-simple-64.stderr
  src/test/ui/limits/huge-array.rs
  src/test/ui/limits/huge-array.stderr
  src/test/ui/limits/huge-enum.rs
  src/test/ui/limits/huge-enum.stderr
  src/test/ui/limits/huge-struct.rs
  src/test/ui/limits/huge-struct.stderr
  src/test/ui/limits/issue-15919-32.rs
  src/test/ui/limits/issue-15919-32.stderr
  src/test/ui/limits/issue-15919-64.rs
  src/test/ui/limits/issue-15919-64.stderr
  src/test/ui/limits/issue-17913.rs
  src/test/ui/limits/issue-17913.stderr
  src/test/ui/limits/issue-55878.rs
  src/test/ui/limits/issue-55878.stderr
  src/test/ui/limits/issue-56762.rs
  src/test/ui/limits/issue-56762.stderr
  src/test/ui/limits/issue-69485-var-size-diffs-too-large.rs
  src/test/ui/limits/issue-69485-var-size-diffs-too-large.stderr
  src/test/ui/limits/issue-75158-64.rs
  src/test/ui/limits/issue-75158-64.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81498 Apply workaround from #72003 for #56935 to allow for cross-compilation of `rustc_index` crate
  compiler/rustc_index/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#81502 Add abi field to `Method`
  src/librustdoc/json/conversions.rs
  src/rustdoc-json-types/lib.rs
  src/test/rustdoc-json/method_abi.rs
Labels: A-rustdoc-json, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81742 Add a note about the correctness and the effect on unsafe code to the `ExactSizeIterator` docs
  library/core/src/iter/traits/exact_size.rs
Labels: S-waiting-on-bors

#81830 Add long error explanation for E0542
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0542.md
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: S-waiting-on-bors

#81835 Improve long explanation for E0546
  compiler/rustc_error_codes/src/error_codes/E0546.md
Labels: S-waiting-on-bors

#81843 Add regression test for #29821
  src/test/ui/issues/issue-29821.rs
Labels: S-waiting-on-bors

#81853 Rollup of 5 pull requests
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0542.md
  compiler/rustc_error_codes/src/error_codes/E0546.md
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/mod.rs
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/remove.rs
  library/alloc/src/lib.rs
  library/core/src/iter/traits/exact_size.rs
  src/test/ui/issues/issue-29821.rs
  src/test/ui/stability-attribute/stability-attribute-sanity.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#81526 btree: use Option's unwrap_unchecked()
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/mod.rs
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/remove.rs
  library/alloc/src/lib.rs
Labels: S-waiting-on-bors

#80632 Identify unreachable subpatterns more reliably
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs
  compiler/rustc_mir_build/src/thir/pattern/usefulness.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs
  src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.stderr
  src/test/ui/pattern/usefulness/issue-80501-or-pat-and-macro.rs
Labels: A-exhaustiveness-checking, F-or_patterns, S-waiting-on-bors, merged-by-bors

#80652 Improve SIMD type element count validation
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_codegen_llvm/src/declare.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_error_codes/src/error_codes/E0074.md
  compiler/rustc_error_codes/src/error_codes/E0076.md
  compiler/rustc_error_codes/src/error_codes/E0077.md
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/consts/const-eval/simd/insert_extract.rs
  src/test/ui/simd-intrinsic/simd-intrinsic-generic-elements.rs
  src/test/ui/simd-intrinsic/simd-intrinsic-generic-elements.stderr
  src/test/ui/simd-type.rs
  src/test/ui/simd/issue-17170.rs
  src/test/ui/simd/issue-17170.stderr
  src/test/ui/simd/issue-39720.rs
  src/test/ui/simd/issue-39720.stderr
  src/test/ui/simd/simd-intrinsic-generic-elements.rs
  src/test/ui/simd/simd-size-align.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-empty.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-empty.stderr
  src/test/ui/simd/simd-type-generic-monomorphisation-oversized.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-oversized.stderr
  src/test/ui/simd/simd-type-generic-monomorphisation-power-of-two.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-power-of-two.stderr
  src/test/ui/simd/simd-type-generic-monomorphisation.rs
  src/test/ui/simd/simd-type-generic-monomorphisation.stderr
  src/test/ui/simd/simd-type.rs
  src/test/ui/simd/simd-type.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80962 Stabilize remaining integer methods as `const fn`
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  src/test/ui/consts/const-int-arithmetic.rs
Labels: A-const-fn, S-waiting-on-bors, S-waiting-on-fcp, T-lang, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, to-announce

#79245 BTree: remove Ord bound where it is absent elsewhere
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/btree/set/tests.rs
Labels: A-collections, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, needs-fcp, proposed-final-comment-period

#81313 Restore linking to itself in implementors section of trait page
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc/trait-self-link.rs
Labels: A-traits, C-enhancement, S-waiting-on-bors, T-rustdoc, merged-by-bors

#81878 Rust 1.50.0 stable release
  RELEASES.md
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_parse/src/lexer/unescape_error_reporting.rs
  src/ci/run.sh
  src/test/ui/attributes/key-value-non-ascii.rs
  src/test/ui/attributes/key-value-non-ascii.stderr
Labels: S-waiting-on-bors, merged-by-bors

#81828 parse_format: treat r" as a literal
  compiler/rustc_parse_format/src/lib.rs
  src/test/ui/fmt/format-args-capture.rs
  src/test/ui/issues/issue-75307.stderr
Labels: S-waiting-on-bors

#81840 fix formatting of std::iter::Map
  library/core/src/iter/adapters/map.rs
Labels: S-waiting-on-bors

#81861 Show MIR bytes separately in -Zmeta-stats output
  compiler/rustc_metadata/src/rmeta/encoder.rs
Labels: S-waiting-on-bors

#81865 Clean up weird Option mapping
  compiler/rustc_typeck/src/check/expr.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#81356 libtest: allow multiple filters
  library/test/src/cli.rs
  library/test/src/lib.rs
  library/test/src/tests.rs
  src/test/ui/test-attrs/test-filter-multiple.rs
  src/test/ui/test-attrs/test-filter-multiple.run.stdout
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, to-announce

#81735 faster few span methods
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
Labels: S-waiting-on-bors

#81817 Add option to emit compiler stderr per bitwidth.
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#71531 Move treat err as bug tests to ui
  src/test/run-make-fulldeps/treat-err-as-bug/Makefile
  src/test/run-make-fulldeps/treat-err-as-bug/delay_span_bug.rs
  src/test/run-make-fulldeps/treat-err-as-bug/err.rs
  src/test/ui/treat-err-as-bug/delay_span_bug.rs
  src/test/ui/treat-err-as-bug/delay_span_bug.stderr
  src/test/ui/treat-err-as-bug/err.rs
  src/test/ui/treat-err-as-bug/err.stderr
Labels: A-const-eval, A-testsuite, S-waiting-on-bors

#81361 BTreeMap: lightly refactor the split_off implementation
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/split.rs
Labels: S-waiting-on-bors, merged-by-bors

#81901 Switch query descriptions to just String
  compiler/rustc_macros/src/query.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_middle/src/ty/query/plumbing.rs
  compiler/rustc_query_system/src/query/config.rs
Labels: S-waiting-on-bors, merged-by-bors

#81826 Prefer match over combinators to make some Box methods inlineable
  library/alloc/src/boxed.rs
Labels: S-waiting-on-bors

#81834 Resolve typedef in HashMap lldb pretty-printer only if possible
  src/etc/lldb_providers.py
Labels: S-waiting-on-bors

#81841 [rustbuild] Output rustdoc-json-types docs
  src/bootstrap/doc.rs
Labels: A-contributor-roadblock, A-rustbuild, A-rustdoc-json, S-waiting-on-bors, T-doc, T-rustdoc

#81849 Expand the docs for ops::ControlFlow a bit
  library/core/src/ops/control_flow.rs
  library/core/tests/lib.rs
  library/core/tests/ops.rs
  library/core/tests/ops/control_flow.rs
Labels: S-waiting-on-bors, T-libs

#81876 parser: Fix panic in 'const impl' recovery
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/parser/issue-81806.rs
  src/test/ui/parser/issue-81806.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#81888 Fix pretty printer macro_rules with semicolon.
  compiler/rustc_ast_pretty/src/pprust/state.rs
  src/test/pretty/macro_rules.rs
Labels: S-waiting-on-bors

#81896 Remove outdated comment in windows' mutex.rs
  library/std/src/sys/windows/mutex.rs
Labels: O-windows, S-waiting-on-bors, T-libs-impl

#81697 Add "every" as a doc alias for "all".
  library/core/src/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#80732 Allow Trait inheritance with cycles on associated types take 2
  compiler/rustc_infer/src/traits/util.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/keys.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/fn_ctxt/mod.rs
  compiler/rustc_typeck/src/collect.rs
  compiler/rustc_typeck/src/collect/item_bounds.rs
  src/test/incremental/cyclic-trait-hierarchy.rs
  src/test/ui/associated-type-bounds/ambiguous-associated-type2.rs
  src/test/ui/associated-type-bounds/ambiguous-associated-type2.stderr
  src/test/ui/associated-type-bounds/associated-item-through-where-clause.rs
  src/test/ui/associated-type-bounds/handle-predicates-that-can-define-assoc-type.rs
  src/test/ui/associated-type-bounds/missing-trait-bound-for-assoc-fails.rs
  src/test/ui/associated-type-bounds/missing-trait-bound-for-assoc-fails.stderr
  src/test/ui/associated-type-bounds/super-trait-referencing-self.rs
  src/test/ui/associated-type-bounds/super-trait-referencing.rs
  src/test/ui/associated-type-bounds/super-trait-where-referencing-self.rs
  src/test/ui/associated-type-bounds/traits-assoc-anonymized.rs
  src/test/ui/associated-type-bounds/traits-assoc-type-macros.rs
  src/test/ui/cycle-projection-based-on-where-clause.rs
  src/test/ui/cycle-projection-based-on-where-clause.stderr
  src/test/ui/cycle-trait/cycle-trait-supertrait-direct.stderr
  src/test/ui/cycle-trait/cycle-trait-supertrait-indirect.stderr
  src/test/ui/issues/issue-12511.stderr
  src/test/ui/issues/issue-20772.stderr
  src/test/ui/issues/issue-20825.stderr
  src/test/ui/issues/issue-22673.rs
  src/test/ui/issues/issue-22673.stderr
Labels: A-traits, S-waiting-on-bors, T-compiler

#72209 Add checking for no_mangle to unsafe_code lint
  compiler/rustc_lint/src/builtin.rs
  src/test/ui/lint/lint-unsafe-code.rs
  src/test/ui/lint/lint-unsafe-code.stderr
Labels: A-linkage, A-lint, S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period
