Repository rust-lang/rust, pull requests merged in 2021-09, with the labels that each got.

#88533 Concrete regions can show up in mir borrowck if the originated from there
  compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs
Labels: beta-nominated, beta-accepted, S-waiting-on-bors, merged-by-bors, ICEBreaker-Cleanup-Crew

#87688 Introduce `let...else`
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/util/classify.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_lowering/src/block.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_builtin_macros/src/deriving/debug.rs
  compiler/rustc_expand/src/build.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_middle/src/traits/mod.rs
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  compiler/rustc_parse/src/parser/stmt.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/did_you_mean/issue-40396.stderr
  src/test/ui/feature-gates/feature-gate-let_else.rs
  src/test/ui/feature-gates/feature-gate-let_else.stderr
  src/test/ui/let-else/let-else-bool-binop-init.fixed
  src/test/ui/let-else/let-else-bool-binop-init.rs
  src/test/ui/let-else/let-else-bool-binop-init.stderr
  src/test/ui/let-else/let-else-brace-before-else.fixed
  src/test/ui/let-else/let-else-brace-before-else.rs
  src/test/ui/let-else/let-else-brace-before-else.stderr
  src/test/ui/let-else/let-else-check.rs
  src/test/ui/let-else/let-else-check.stderr
  src/test/ui/let-else/let-else-irrefutable.rs
  src/test/ui/let-else/let-else-irrefutable.stderr
  src/test/ui/let-else/let-else-missing-semicolon.rs
  src/test/ui/let-else/let-else-missing-semicolon.stderr
  src/test/ui/let-else/let-else-non-diverging.rs
  src/test/ui/let-else/let-else-non-diverging.stderr
  src/test/ui/let-else/let-else-run-pass.rs
  src/test/ui/let-else/let-else-scope.rs
  src/test/ui/let-else/let-else-scope.stderr
  src/test/ui/parser/attr-stmt-expr-attr-bad.stderr
  src/test/ui/parser/issue-72253.rs
  src/test/ui/parser/issue-72253.stderr
  src/test/ui/parser/issue-84117.rs
  src/test/ui/parser/issue-84117.stderr
  src/test/ui/parser/macro/issue-37234.stderr
  src/test/ui/parser/missing-semicolon.rs
  src/test/ui/parser/missing-semicolon.stderr
  src/test/ui/parser/range-3.rs
  src/test/ui/parser/range-3.stderr
  src/test/ui/parser/range-4.rs
  src/test/ui/parser/range-4.stderr
  src/test/ui/pattern/usefulness/top-level-alternation.rs
  src/test/ui/pattern/usefulness/top-level-alternation.stderr
  src/tools/clippy/clippy_lints/src/non_expressive_names.rs
  src/tools/clippy/clippy_utils/src/ast_utils.rs
  src/tools/rustfmt/src/items.rs
  src/tools/rustfmt/tests/source/let_else.rs
  src/tools/rustfmt/tests/target/let_else.rs
Labels: T-lang, T-compiler, S-waiting-on-bors, merged-by-bors

#88121 Improve errors for recursive type aliases
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_query_impl/src/keys.rs
  compiler/rustc_query_impl/src/lib.rs
  compiler/rustc_query_impl/src/plumbing.rs
  compiler/rustc_query_impl/src/util.rs
  compiler/rustc_query_system/src/query/job.rs
  compiler/rustc_query_system/src/query/mod.rs
  src/test/ui/associated-type-bounds/ambiguous-associated-type2.stderr
  src/test/ui/coherence/coherence-inherited-assoc-ty-cycle-err.stderr
  src/test/ui/cycle-trait/cycle-trait-default-type-trait.stderr
  src/test/ui/infinite/infinite-struct.stderr
  src/test/ui/infinite/infinite-tag-type-recursion.stderr
  src/test/ui/infinite/infinite-trait-alias-recursion.rs
  src/test/ui/infinite/infinite-trait-alias-recursion.stderr
  src/test/ui/infinite/infinite-type-alias-mutual-recursion.rs
  src/test/ui/infinite/infinite-type-alias-mutual-recursion.stderr
  src/test/ui/infinite/infinite-vec-type-recursion.stderr
  src/test/ui/issues/issue-20772.stderr
  src/test/ui/issues/issue-20825.stderr
  src/test/ui/issues/issue-21177.stderr
  src/test/ui/issues/issue-34373.stderr
  src/test/ui/resolve/issue-23305.stderr
  src/test/ui/resolve/resolve-self-in-impl.stderr
Labels: C-enhancement, A-diagnostics, T-compiler, S-waiting-on-bors, merged-by-bors

#88272 Add bit removal methods to SparseBitMatrix and factor *BitSet relational methods into more extensible trait
  compiler/rustc_index/src/bit_set.rs
  compiler/rustc_index/src/bit_set/tests.rs
  compiler/rustc_mir/src/borrow_check/region_infer/values.rs
  compiler/rustc_mir/src/transform/generator.rs
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88350 add support for clobbering xer, cr, and cr[0-7] for asm! on OpenPower/PowerPC
  compiler/rustc_codegen_llvm/src/asm.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/mod.rs
  compiler/rustc_target/src/asm/powerpc.rs
  src/doc/unstable-book/src/library-features/asm.md
  src/test/assembly/asm/powerpc-types.rs
  src/test/codegen/asm-powerpc-clobbers.rs
Labels: A-inline-assembly, O-PowerPC, S-waiting-on-bors

#88410 Remove bolding on associated constants
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc-gui/font-weight.goml
Labels: T-rustdoc, A-associated-items, S-waiting-on-bors, A-rustdoc-ui

#88525 fix(rustc_typeck): produce better errors for dyn auto trait
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0785.md
  compiler/rustc_typeck/src/coherence/inherent_impls.rs
  src/test/ui/coherence/issue-85026.rs
  src/test/ui/coherence/issue-85026.stderr
Labels: S-waiting-on-bors

#88542 Use the return value of readdir_r() instead of errno
  library/std/src/sys/unix/fs.rs
Labels: S-waiting-on-bors

#88548 Stabilize `Iterator::intersperse()`
  library/core/src/iter/adapters/intersperse.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/mod.rs
  library/core/src/iter/traits/iterator.rs
  library/core/tests/lib.rs
  src/librustdoc/lib.rs
Labels: T-libs-api, relnotes, S-waiting-on-bors

#88551 Stabilize `UnsafeCell::raw_get()`
  library/core/src/cell.rs
  library/core/tests/cell.rs
  library/std/src/lib.rs
Labels: T-libs-api, relnotes, S-waiting-on-bors

#88556 Rollup of 9 pull requests
  compiler/rustc_codegen_llvm/src/asm.rs
  compiler/rustc_data_structures/src/flock.rs
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0785.md
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/mod.rs
  compiler/rustc_target/src/asm/powerpc.rs
  compiler/rustc_typeck/src/coherence/inherent_impls.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/btree/set/tests.rs
  library/alloc/tests/const_fns.rs
  library/core/src/cell.rs
  library/core/src/iter/adapters/intersperse.rs
  library/core/src/iter/adapters/mod.rs
  library/core/src/iter/mod.rs
  library/core/src/iter/traits/iterator.rs
  library/core/tests/cell.rs
  library/core/tests/lib.rs
  library/std/src/lib.rs
  library/std/src/sys/unix/fs.rs
  src/doc/unstable-book/src/library-features/asm.md
  src/librustdoc/html/render/mod.rs
  src/librustdoc/lib.rs
  src/test/assembly/asm/powerpc-types.rs
  src/test/codegen/asm-powerpc-clobbers.rs
  src/test/rustdoc-gui/font-weight.goml
  src/test/ui/coherence/issue-85026.rs
  src/test/ui/coherence/issue-85026.stderr
  src/test/ui/extern/extern-no-mangle.rs
  src/test/ui/extern/extern-no-mangle.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#88040 BTree: remove Ord bound from new
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/map/tests.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/btree/set/tests.rs
  library/alloc/tests/const_fns.rs
Labels: T-libs-api, S-waiting-on-bors, disposition-merge, finished-final-comment-period, to-announce

#88053 Fix the flock fallback implementation
  compiler/rustc_data_structures/src/flock.rs
Labels: T-compiler, S-waiting-on-bors

#86376 Emit specific warning to clarify that `#[no_mangle]` should not be applied on foreign statics or functions
  compiler/rustc_passes/src/check_attr.rs
  src/test/ui/extern/extern-no-mangle.rs
  src/test/ui/extern/extern-no-mangle.stderr
Labels: S-waiting-on-bors

#88269 Doctest persist full binaries when persisting
  src/librustdoc/doctest.rs
  src/test/run-make-fulldeps/doctests-keep-binaries/Makefile
  src/test/run-make-fulldeps/doctests-keep-binaries/t.rs
Labels: T-rustdoc, S-waiting-on-bors, A-doctests, merged-by-bors

#88490 Display associated types of implementors
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc-gui/implementors.goml
  src/test/rustdoc-gui/src/lib2/implementors/lib.rs
  src/test/rustdoc-gui/src/lib2/lib.rs
  src/test/rustdoc-gui/toggle-implementors.goml
  src/test/rustdoc/trait-impl-items-links-and-anchors.rs
Labels: T-rustdoc, beta-nominated, beta-accepted, S-waiting-on-bors, merged-by-bors, A-rustdoc-ui

#83342 Allow writing of incomplete UTF-8 sequences to the Windows console via stdout/stderr
  library/core/src/str/mod.rs
  library/std/src/sys/windows/stdio.rs
Labels: O-windows, A-unicode, T-libs-api, relnotes, S-waiting-on-bors, disposition-merge, finished-final-comment-period, merged-by-bors, to-announce

#87114 Lint missing Abi in ast validation instead of lowering.
  Cargo.lock
  compiler/rustc_ast_lowering/src/item.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_passes/Cargo.toml
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_target/src/spec/abi.rs
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88516 some low hanging clippy::perf fixes
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_resolve/src/late/lifetimes.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/pat.rs
  src/librustdoc/html/sources.rs
Labels: S-waiting-on-bors, merged-by-bors

#88530 Shrink Session a bit
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_session/src/session.rs
Labels: C-cleanup, T-compiler, S-waiting-on-bors, merged-by-bors

#87580 Update Windows Argument Parsing
  library/std/src/lib.rs
  library/std/src/sys/windows/args.rs
  library/std/src/sys/windows/args/tests.rs
  library/std/src/sys/windows/c.rs
Labels: O-windows, T-libs-api, relnotes, S-waiting-on-bors, disposition-merge, finished-final-comment-period, merged-by-bors, T-libs, to-announce

#88505 Use `unwrap_unchecked` where possible
  library/alloc/src/collections/linked_list.rs
  library/core/src/array/mod.rs
  library/core/src/option.rs
Labels: S-waiting-on-bors

#88512 Upgrade array_into_iter lint to include Deref-to-array types.
  compiler/rustc_lint/src/array_into_iter.rs
  src/test/ui/iterators/into-iter-on-arrays-2018.rs
  src/test/ui/iterators/into-iter-on-arrays-2018.stderr
  src/test/ui/iterators/into-iter-on-arrays-lint.stderr
Labels: T-compiler, S-waiting-on-bors, A-suggestion-diagnostics, A-edition-2021

#88532 Remove single use variables
  compiler/rustc_middle/src/mir/mod.rs
Labels: S-waiting-on-bors

#88543 Improve closure dummy capture suggestion in macros.
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.rs
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.stderr
Labels: T-compiler, S-waiting-on-bors, A-suggestion-diagnostics, D-invalid-suggestion, A-edition-2021

#88560 `fmt::Formatter::pad`: don't call chars().count() more than one time
  library/core/src/fmt/mod.rs
Labels: S-waiting-on-bors

#88565 Add regression test for issue 83190
  src/test/ui/issues/issue-83190.rs
Labels: S-waiting-on-bors

#88567 Remove redundant `Span` in `QueryJobInfo`
  compiler/rustc_query_system/src/query/job.rs
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: C-cleanup, I-compiletime, T-compiler, S-waiting-on-bors, I-compilemem, A-query-system

#88573 rustdoc: Don't panic on ambiguous inherent associated types
  src/librustdoc/clean/mod.rs
  src/test/rustdoc-ui/ambiguous-inherent-assoc-ty.rs
  src/test/rustdoc-ui/ambiguous-inherent-assoc-ty.stderr
Labels: T-rustdoc, S-waiting-on-bors, F-inherent_associated_types

#88582 Implement #88581
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/lib.rs
  library/core/tests/num/int_macros.rs
  library/core/tests/num/uint_macros.rs
Labels: T-libs-api, S-waiting-on-bors

#88589 Correct doc comments inside `use_expr_visitor.rs`
  compiler/rustc_typeck/src/expr_use_visitor.rs
Labels: S-waiting-on-bors

#88592 Fix ICE in const check
  compiler/rustc_mir/src/transform/check_consts/check.rs
  src/test/ui/const-generics/const_trait_fn-issue-88433.rs
Labels: S-waiting-on-bors

#88596 Rollup of 12 pull requests
  compiler/rustc_lint/src/array_into_iter.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir/src/transform/check_consts/check.rs
  compiler/rustc_query_system/src/query/job.rs
  compiler/rustc_query_system/src/query/plumbing.rs
  compiler/rustc_typeck/src/check/upvar.rs
  compiler/rustc_typeck/src/expr_use_visitor.rs
  library/alloc/src/collections/linked_list.rs
  library/core/src/array/mod.rs
  library/core/src/fmt/mod.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/src/option.rs
  library/core/tests/lib.rs
  library/core/tests/num/int_macros.rs
  library/core/tests/num/uint_macros.rs
  library/std/src/os/unix/fs.rs
  src/librustdoc/clean/mod.rs
  src/test/rustdoc-ui/ambiguous-inherent-assoc-ty.rs
  src/test/rustdoc-ui/ambiguous-inherent-assoc-ty.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.rs
  src/test/ui/closures/2229_closure_analysis/migrations/closure-body-macro-fragment.stderr
  src/test/ui/const-generics/const_trait_fn-issue-88433.rs
  src/test/ui/issues/issue-83190.rs
  src/test/ui/iterators/into-iter-on-arrays-2018.rs
  src/test/ui/iterators/into-iter-on-arrays-2018.stderr
  src/test/ui/iterators/into-iter-on-arrays-lint.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#88177 Stabilize std::os::unix::fs::chroot
  library/std/src/os/unix/fs.rs
Labels: T-libs-api, relnotes, S-waiting-on-bors, disposition-merge, finished-final-comment-period, to-announce

#85868 Preserve most sub-obligations in the projection cache
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/query/evaluate_obligation.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/incremental/const-generics/hash-tyvid-regression-1.rs
  src/test/ui/impl-trait/auto-trait-leak.stderr
  src/test/ui/traits/cycle-cache-err-60010.rs
  src/test/ui/traits/cycle-cache-err-60010.stderr
  src/test/ui/traits/inductive-overflow/lifetime.rs
  src/test/ui/traits/inductive-overflow/lifetime.stderr
  src/test/ui/traits/inductive-overflow/simultaneous.stderr
  src/test/ui/type-alias-impl-trait/auto-trait-leakage3.stderr
  src/test/ui/type-alias-impl-trait/inference-cycle.stderr
Labels: beta-nominated, T-compiler, S-waiting-on-bors, merged-by-bors, perf-regression, perf-regression-triaged

#88363 Path remapping: Make behavior of diagnostics output dependent on presence of --remap-path-prefix.
  compiler/rustc_codegen_cranelift/src/debuginfo/mod.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_errors/src/annotate_snippet_emitter_writer.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_errors/src/json.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
  src/test/ui/remap-path-prefix.rs
  src/test/ui/remap-path-prefix.stderr
  src/tools/clippy/clippy_lints/src/macro_use.rs
Labels: S-waiting-on-bors, merged-by-bors

#88386 Point at unclosed delimiters as part of the primary MultiSpan
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/parser/issue-10636-1.stderr
  src/test/ui/parser/issue-10636-2.stderr
  src/test/ui/parser/issue-58856-1.stderr
  src/test/ui/parser/issue-58856-2.stderr
  src/test/ui/parser/issue-60075.stderr
  src/test/ui/parser/issue-62973.stderr
  src/test/ui/parser/issue-63116.stderr
  src/test/ui/parser/issue-66357-unexpected-unreachable.stderr
  src/test/ui/parser/issue-67377-invalid-syntax-in-enum-discriminant.stderr
  src/test/ui/parser/macro-mismatched-delim-brace-paren.stderr
  src/test/ui/parser/macro-mismatched-delim-paren-brace.stderr
  src/test/ui/parser/parser-recovery-2.stderr
  src/test/ui/parser/unclosed-delimiter-in-dep.stderr
  src/test/ui/parser/unclosed_delim_mod.stderr
  src/test/ui/parser/use-unclosed-brace.stderr
  src/test/ui/resolve/token-error-correct-2.stderr
  src/test/ui/resolve/token-error-correct-3.stderr
  src/test/ui/resolve/token-error-correct-4.stderr
  src/test/ui/resolve/token-error-correct.stderr
Labels: S-waiting-on-bors, merged-by-bors

#88428 expand: Treat more macro calls as statement macro calls
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_expand/src/placeholders.rs
  src/test/ui/macros/issue-87877.rs
Labels: S-waiting-on-bors, merged-by-bors

#86454 Refactor unsized suggestions
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
Labels: C-cleanup, A-typesystem, A-diagnostics, A-traits, T-compiler, S-waiting-on-bors, merged-by-bors

#88610 Update outdated docs of array::IntoIter::new.
  library/core/src/array/iter.rs
Labels: A-docs, S-waiting-on-bors, A-iterators, T-libs, A-edition-2021

#88618 Rollup of 7 pull requests
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_typeck/src/outlives/implicit_infer.rs
  library/core/src/array/iter.rs
  library/core/src/cmp.rs
  library/core/src/ptr/mod.rs
  library/core/tests/slice.rs
  library/std/src/primitive_docs.rs
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#88483 Fix LLVM libunwind build for non-musl targets
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#88507 Add test case for using `slice::fill` with MaybeUninit
  library/core/tests/slice.rs
Labels: S-waiting-on-bors

#88557 small const generics cleanup
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_typeck/src/outlives/implicit_infer.rs
Labels: S-waiting-on-bors

#88579 remove redundant / misplaced sentence from docs
  library/core/src/ptr/mod.rs
Labels: S-waiting-on-bors

#88613 Update primitive docs for rust 2021.
  library/std/src/primitive_docs.rs
Labels: A-docs, S-waiting-on-bors, A-edition-2021

#88202 Add an example for deriving PartialOrd on enums
  library/core/src/cmp.rs
Labels: A-docs, S-waiting-on-bors, T-libs

#88597 Move global analyses from lowering to resolution
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast_lowering/src/item.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_lowering/src/path.rs
  compiler/rustc_builtin_macros/src/proc_macro_harness.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/hir/mod.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_typeck/src/check_unused.rs
  compiler/rustc_typeck/src/coherence/mod.rs
  src/test/ui/asm/type-check-1.stderr
  src/test/ui/ast-json/ast-json-noexpand-output.stdout
  src/test/ui/ast-json/ast-json-output.stdout
  src/test/ui/borrowck/issue-64453.stderr
  src/test/ui/const-generics/type_mismatch.stderr
  src/test/ui/consts/const-extern-fn/const-extern-fn-requires-unsafe.mir.stderr
  src/test/ui/consts/issue-66693.stderr
  src/test/ui/issues/issue-47486.stderr
  src/test/ui/liveness/liveness-return-last-stmt-semi.stderr
  src/test/ui/proc-macro/attribute-with-error.stderr
  src/test/ui/repeat_count.stderr
  src/test/ui/suggestions/impl-trait-with-missing-bounds.stderr
  src/test/ui/suggestions/suggest-ref-macro.stderr
  src/test/ui/union/union-derive-clone.mirunsafeck.stderr
  src/test/ui/union/union-derive-clone.thirunsafeck.stderr
Labels: S-waiting-on-bors, merged-by-bors, perf-regression

#88454 sunos systems add sanitizer supported.
  compiler/rustc_target/src/spec/x86_64_pc_solaris.rs
  compiler/rustc_target/src/spec/x86_64_unknown_illumos.rs
  src/bootstrap/native.rs
Labels: S-waiting-on-bors, merged-by-bors

#88482 Add regression test for a spurious import
  src/test/run-make/wasm-spurious-import/Makefile
  src/test/run-make/wasm-spurious-import/main.rs
  src/test/run-make/wasm-spurious-import/verify.js
Labels: S-waiting-on-bors, merged-by-bors

#88598 Detect bare blocks with type ascription that were meant to be a `struct` literal
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_builtin_macros/src/deriving/mod.rs
  compiler/rustc_builtin_macros/src/format.rs
  compiler/rustc_expand/src/build.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_parse/src/parser/stmt.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  src/test/ui-fulldeps/pprust-expr-roundtrip.rs
  src/test/ui/type/ascription/issue-34255-1.stderr
  src/tools/rustfmt/src/closures.rs
Labels: S-waiting-on-bors, merged-by-bors

#88633 Bump version to 1.57
  src/version
Labels: S-waiting-on-bors, merged-by-bors

#88538 CrateLocator refactorings
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_metadata/src/locator.rs
Labels: C-cleanup, A-metadata, T-compiler, S-waiting-on-bors, merged-by-bors

#88547 fix(rustc_lint): better detect when parens are necessary
  compiler/rustc_lint/src/unused.rs
  src/test/ui/lint/unused/issue-88519-unused-paren.rs
Labels: S-waiting-on-bors, merged-by-bors

#88550 Include debug info for the allocator shim
  compiler/rustc_codegen_llvm/src/allocator.rs
  compiler/rustc_codegen_llvm/src/debuginfo/mod.rs
  compiler/rustc_codegen_llvm/src/lib.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/traits/backend.rs
Labels: S-waiting-on-bors, merged-by-bors

#88641 [beta] backports
  Cargo.lock
  compiler/rustc_codegen_ssa/Cargo.toml
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc-gui/implementors.goml
  src/test/rustdoc-gui/src/lib2/implementors/lib.rs
  src/test/rustdoc-gui/src/lib2/lib.rs
  src/test/rustdoc-gui/toggle-implementors.goml
  src/test/rustdoc/trait-impl-items-links-and-anchors.rs
  src/test/ui/abi/unsupported.aarch64.stderr
  src/test/ui/abi/unsupported.x64.stderr
Labels: S-waiting-on-bors, merged-by-bors

#88574 rustdoc: Box `GenericArg::Const` to reduce enum size
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/json/conversions.rs
Labels: T-rustdoc, S-waiting-on-bors, I-compilemem, merged-by-bors

#88364 Make sure FileCheck is copied in the LLVM output directory
  src/bootstrap/native.rs
Labels: S-waiting-on-bors, merged-by-bors

#88626 Simplify lifetimes_from_impl_trait_bounds
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_lowering/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#88469 Add links in docs for some primitive types
  library/core/src/array/mod.rs
  library/core/src/bool.rs
  library/core/src/char/methods.rs
  library/std/src/primitive_docs.rs
Labels: T-libs-api, S-waiting-on-bors, merged-by-bors

#88559 Move add_rlib and add_native_library to cg_ssa
  compiler/rustc_codegen_cranelift/src/archive.rs
  compiler/rustc_codegen_llvm/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
Labels: C-cleanup, T-compiler, S-waiting-on-bors, merged-by-bors, A-cranelift, A-gcc

#88432 Fix a typo in raw_vec
  library/alloc/src/raw_vec.rs
Labels: S-waiting-on-bors

#88511 x.py clippy: don't run with --all-targets by default
  src/bootstrap/check.rs
Labels: A-rustbuild, S-waiting-on-bors

#88657 Fix 2021 `dyn` suggestion that used code as label
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  src/test/ui/editions/dyn-trait-sugg-2021.rs
  src/test/ui/editions/dyn-trait-sugg-2021.stderr
Labels: S-waiting-on-bors, A-suggestion-diagnostics, D-invalid-suggestion, A-edition-2021

#88604 rustdoc: Clean up handling of lifetime bounds
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/format.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/lib.rs
  src/rustdoc-json-types/lib.rs
  src/test/rustdoc-json/structs/with_primitives.rs
  src/test/rustdoc-ui/bounded-hr-lifetime.rs
  src/test/rustdoc-ui/bounded-hr-lifetime.stderr
Labels: C-cleanup, T-rustdoc, A-lifetimes, S-waiting-on-bors, merged-by-bors

#88499 Provide `layout_of` automatically (given tcx + param_env + error handling).
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_llvm/src/abi.rs
  compiler/rustc_codegen_llvm/src/builder.rs
  compiler/rustc_codegen_llvm/src/common.rs
  compiler/rustc_codegen_llvm/src/consts.rs
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/debuginfo/mod.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_llvm/src/mono_item.rs
  compiler/rustc_codegen_llvm/src/type_of.rs
  compiler/rustc_codegen_llvm/src/va_arg.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_codegen_ssa/src/mir/operand.rs
  compiler/rustc_codegen_ssa/src/mir/place.rs
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_codegen_ssa/src/mono_item.rs
  compiler/rustc_codegen_ssa/src/traits/backend.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint/src/types.rs
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_mir/src/const_eval/eval_queries.rs
  compiler/rustc_mir/src/interpret/cast.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/intrinsics/caller_location.rs
  compiler/rustc_mir/src/interpret/operand.rs
  compiler/rustc_mir/src/interpret/operator.rs
  compiler/rustc_mir/src/interpret/place.rs
  compiler/rustc_mir/src/interpret/step.rs
  compiler/rustc_mir/src/interpret/terminator.rs
  compiler/rustc_mir/src/interpret/validity.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  compiler/rustc_passes/src/layout_test.rs
  compiler/rustc_target/src/abi/mod.rs
  src/tools/clippy/clippy_lints/src/casts/cast_ptr_alignment.rs
  src/tools/clippy/clippy_lints/src/escape.rs
  src/tools/clippy/clippy_lints/src/invalid_upcast_comparisons.rs
  src/tools/clippy/clippy_lints/src/large_const_arrays.rs
  src/tools/clippy/clippy_lints/src/large_enum_variant.rs
  src/tools/clippy/clippy_lints/src/large_stack_arrays.rs
  src/tools/clippy/clippy_lints/src/methods/manual_saturating_arithmetic.rs
  src/tools/clippy/clippy_lints/src/pass_by_ref_or_value.rs
  src/tools/clippy/clippy_lints/src/types/vec_box.rs
  src/tools/clippy/clippy_lints/src/vec.rs
  src/tools/clippy/clippy_lints/src/zero_sized_map_values.rs
Labels: S-waiting-on-bors, merged-by-bors

#88552 Stop allocating vtable entries for non-object-safe methods
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_query_impl/src/keys.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_trait_selection/src/traits/util.rs
  src/test/ui/traits/vtable/vtable-non-object-safe.rs
  src/test/ui/traits/vtable/vtable-non-object-safe.stderr
  src/test/ui/traits/vtable/vtable-vacant.rs
  src/test/ui/traits/vtable/vtable-vacant.stderr
Labels: S-waiting-on-bors, I-heavy, merged-by-bors, perf-regression

#88435 Avoid invoking the hir_crate query to traverse the HIR
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_incremental/src/persist/dirty_clean.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_lint/src/late.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_passes/src/dead.rs
  compiler/rustc_passes/src/hir_id_validator.rs
  compiler/rustc_passes/src/hir_stats.rs
  compiler/rustc_passes/src/lib_features.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/render/span_map.rs
  src/test/ui/coherence/coherence_inherent.stderr
  src/test/ui/coherence/coherence_inherent_cc.stderr
  src/test/ui/hygiene/no_implicit_prelude.stderr
  src/test/ui/hygiene/trait_items.stderr
  src/test/ui/issues/issue-10465.stderr
  src/test/ui/rust-2018/trait-import-suggestions.stderr
  src/test/ui/rust-2021/future-prelude-collision-shadow.stderr
  src/test/ui/underscore-imports/shadow.stderr
Labels: S-waiting-on-bors, merged-by-bors

#88493 Fix #88256 remove duplicated diagnostics
  compiler/rustc_errors/src/diagnostic.rs
  compiler/rustc_errors/src/diagnostic_builder.rs
  compiler/rustc_middle/src/lint.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.rs
  src/test/ui/lint/issue-70819-dont-override-forbid-in-same-scope.stderr
  src/test/ui/lint/outer-forbid.rs
  src/test/ui/lint/outer-forbid.stderr
  src/tools/clippy/tests/ui/match_same_arms.stderr
  src/tools/clippy/tests/ui/modulo_one.stderr
  src/tools/clippy/tests/ui/suspicious_operation_groupings.stderr
  src/tools/rustfmt/src/syntux/session.rs
Labels: S-waiting-on-bors, merged-by-bors

#88640 Add tests for issues fixed by #85499
  src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-80706.rs
  src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-80956.rs
  src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-81809.rs
  src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-85455.rs
  src/test/ui/higher-rank-trait-bounds/normalize-under-binder/issue-85455.stderr
Labels: S-waiting-on-bors, merged-by-bors

#88665 Change return type for T::{log,log2,log10} to u32.
  library/core/src/num/int_log10.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/num/int_log.rs
Labels: S-waiting-on-bors, merged-by-bors

#88631 Improve structured tuple struct suggestion
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/issues/issue-4736.stderr
  src/test/ui/issues/issue-80607.stderr
  src/test/ui/numeric/numeric-fields.stderr
  src/test/ui/suggestions/nested-non-tuple-tuple-struct.rs
  src/test/ui/suggestions/nested-non-tuple-tuple-struct.stderr
Labels: S-waiting-on-bors, A-suggestion-diagnostics, merged-by-bors, D-invalid-suggestion

#88678 Change scope of temporaries in match guards
  compiler/rustc_mir_build/src/build/expr/into.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  src/test/mir-opt/match_arm_scopes.complicated_match.SimplifyCfg-initial.after-ElaborateDrops.after.diff
  src/test/mir-opt/match_false_edges.full_tested_match.PromoteTemps.after.mir
  src/test/mir-opt/match_false_edges.full_tested_match2.PromoteTemps.before.mir
  src/test/mir-opt/match_false_edges.main.PromoteTemps.before.mir
  src/test/mir-opt/match_test.main.SimplifyCfg-initial.after.mir
  src/test/mir-opt/matches_reduce_branches.match_nested_if.MatchBranchSimplification.32bit.diff
  src/test/mir-opt/matches_reduce_branches.match_nested_if.MatchBranchSimplification.64bit.diff
  src/test/mir-opt/remove_fake_borrows.match_guard.CleanupNonCodegenStatements.diff
Labels: S-waiting-on-bors, merged-by-bors

#88602 Add tests for some const generics issues
  src/test/ui/const-generics/issues/issue-82956.rs
  src/test/ui/const-generics/issues/issue-82956.stderr
  src/test/ui/const-generics/issues/issue-84659.rs
  src/test/ui/const-generics/issues/issue-84659.stderr
  src/test/ui/const-generics/issues/issue-86530.rs
  src/test/ui/const-generics/issues/issue-86530.stderr
  src/test/ui/const-generics/issues/issue-86535-2.rs
  src/test/ui/const-generics/issues/issue-86535.rs
  src/test/ui/const-generics/sneaky-array-repeat-expr.rs
  src/test/ui/const-generics/sneaky-array-repeat-expr.stderr
Labels: S-waiting-on-bors

#88647 Document when to use Windows' `symlink_dir` vs. `symlink_file`
  library/std/src/os/windows/fs.rs
Labels: S-waiting-on-bors

#88659 Remove SmallVector mention
  compiler/rustc_data_structures/src/thin_vec.rs
Labels: S-waiting-on-bors

#88661 Correct typo
  src/test/ui/moves/move-guard-same-consts.rs
Labels: S-waiting-on-bors

#88673 Fix typo: needede -> needed
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors

#88362 Pin bootstrap checksums and add a tool to update it automatically
  Cargo.lock
  Cargo.toml
  src/bootstrap/bootstrap.py
  src/bootstrap/bootstrap_test.py
  src/bootstrap/builder.rs
  src/bootstrap/lib.rs
  src/bootstrap/run.rs
  src/bootstrap/sanity.rs
  src/bootstrap/tool.rs
  src/stage0.json
  src/stage0.txt
  src/tools/bump-stage0/Cargo.toml
  src/tools/bump-stage0/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#88695 [stable] 1.55.0 stable release
  RELEASES.md
  src/ci/channel
Labels: S-waiting-on-bors, merged-by-bors

#83214 Mmap the incremental data instead of reading it.
  compiler/rustc_incremental/src/persist/file_format.rs
  compiler/rustc_incremental/src/persist/load.rs
  compiler/rustc_incremental/src/persist/save.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_query_impl/src/on_disk_cache.rs
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88448 BTreeMap/BTreeSet::from_iter: use bulk building to improve the performance
  library/alloc/benches/btree/map.rs
  library/alloc/src/collections/btree/dedup_sorted_iter.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/mod.rs
  library/alloc/src/collections/btree/set.rs
Labels: S-waiting-on-bors, merged-by-bors, perf-regression, perf-regression-triaged

#88689 Move `confused_type_with_std_module` to `ResolverOutputs`
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
Labels: S-waiting-on-bors, merged-by-bors

#88161 Fix handling of +whole-archive native link modifier.
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  src/test/run-make/native-link-modifier-whole-archive/Makefile
  src/test/run-make/native-link-modifier-whole-archive/c_static_lib_with_constructor.cpp
  src/test/run-make/native-link-modifier-whole-archive/directly_linked.rs
  src/test/run-make/native-link-modifier-whole-archive/indirectly_linked.rs
  src/test/run-make/native-link-modifier-whole-archive/indirectly_linked_via_attr.rs
  src/test/run-make/native-link-modifier-whole-archive/native_lib_in_src.rs
  src/test/run-make/native-link-modifier-whole-archive/rlib_with_cmdline_native_lib.rs
  src/test/ui/native-library-link-flags/mix-bundle-and-whole-archive-link-attr.rs
  src/test/ui/native-library-link-flags/mix-bundle-and-whole-archive-link-attr.stderr
  src/test/ui/native-library-link-flags/mix-bundle-and-whole-archive.rs
  src/test/ui/native-library-link-flags/mix-bundle-and-whole-archive.stderr
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88710 Use index newtyping for TyVid
  compiler/rustc_infer/src/infer/fudge.rs
  compiler/rustc_infer/src/infer/type_variable.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_type_ir/src/lib.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
Labels: S-waiting-on-bors, merged-by-bors

#88477 2229: Don't move out of drop type
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/issue-88476.rs
  src/test/ui/closures/2229_closure_analysis/issue-88476.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/issue-88476.rs
Labels: beta-nominated, T-lang, T-compiler, final-comment-period, S-waiting-on-bors, disposition-merge, merged-by-bors

#88061 Remove `hir::GenericBound::Unsized`
  compiler/rustc_ast_lowering/src/item.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_middle/src/ty/diagnostics.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/collect.rs
  compiler/rustc_typeck/src/collect/item_bounds.rs
  src/librustdoc/clean/mod.rs
  src/test/ui/error-codes/e0119/complex-impl.stderr
  src/test/ui/generics/wrong-number-of-args.stderr
  src/test/ui/maybe-bounds-where.rs
  src/test/ui/maybe-bounds-where.stderr
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#86943 Suggest deriving traits if possible
  compiler/rustc_typeck/src/check/method/suggest.rs
  library/core/src/cmp.rs
  library/core/src/hash/mod.rs
  library/core/src/marker.rs
  src/test/ui/derives/derive-assoc-type-not-impl.stderr
  src/test/ui/mismatched_types/method-help-unsatisfied-bound.stderr
  src/test/ui/suggestions/derive-trait-for-method-call.rs
  src/test/ui/suggestions/derive-trait-for-method-call.stderr
  src/test/ui/union/union-derive-clone.mirunsafeck.stderr
  src/test/ui/union/union-derive-clone.thirunsafeck.stderr
  src/test/ui/unique-pinned-nocopy.stderr
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#87489 `rustdoc`: compute correct line number for indented rust code blocks.
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/markdown/tests.rs
Labels: T-rustdoc, S-waiting-on-bors, merged-by-bors

#88691 Add a regression test for #88649
  src/test/ui/consts/issue-88649.rs
Labels: A-testsuite, beta-nominated, S-waiting-on-bors

#88712 Fix docs for `uX::checked_next_multiple_of`
  library/core/src/num/uint_macros.rs
Labels: A-docs, S-waiting-on-bors, T-libs

#88726 Fix typo in `const_generics` replaced with `adt_const_params` note
  compiler/rustc_feature/src/removed.rs
Labels: S-waiting-on-bors

#88750 Rollup of 9 pull requests
  RELEASES.md
  compiler/rustc_ast/src/token.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_parse/src/parser/expr.rs
  library/core/src/num/uint_macros.rs
  library/core/src/ops/bit.rs
  library/core/src/option.rs
  library/std/src/keyword_docs.rs
  library/std/src/primitive_docs.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc/type-layout.rs
  src/test/ui/associated-types/issue-36499.stderr
  src/test/ui/consts/issue-88649.rs
  src/test/ui/lifetimes/lifetime-errors/issue_74400.nll.stderr
  src/test/ui/lifetimes/lifetime-errors/issue_74400.rs
  src/test/ui/lifetimes/lifetime-errors/issue_74400.stderr
  src/test/ui/parser/expr-as-stmt.fixed
  src/test/ui/parser/expr-as-stmt.rs
  src/test/ui/parser/expr-as-stmt.stderr
  src/test/ui/parser/issue-88276-unary-plus.fixed
  src/test/ui/parser/issue-88276-unary-plus.rs
  src/test/ui/parser/issue-88276-unary-plus.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#88541 Add regression test for #74400
  src/test/ui/lifetimes/lifetime-errors/issue_74400.nll.stderr
  src/test/ui/lifetimes/lifetime-errors/issue_74400.rs
  src/test/ui/lifetimes/lifetime-errors/issue_74400.stderr
Labels: S-waiting-on-bors

#88553 Improve diagnostics for unary plus operators (#88276)
  compiler/rustc_ast/src/token.rs
  compiler/rustc_parse/src/parser/expr.rs
  src/test/ui/associated-types/issue-36499.stderr
  src/test/ui/parser/expr-as-stmt.fixed
  src/test/ui/parser/expr-as-stmt.rs
  src/test/ui/parser/expr-as-stmt.stderr
  src/test/ui/parser/issue-88276-unary-plus.fixed
  src/test/ui/parser/issue-88276-unary-plus.rs
  src/test/ui/parser/issue-88276-unary-plus.stderr
Labels: S-waiting-on-bors

#88594 More symbolic doc aliases
  library/core/src/ops/bit.rs
  library/std/src/keyword_docs.rs
  library/std/src/primitive_docs.rs
Labels: S-waiting-on-bors, T-libs

#88648 Correct “copies” to “moves” in `<Option<T> as From<T>>::from` doc, and other copyediting
  library/core/src/option.rs
Labels: S-waiting-on-bors, T-libs

#88694 Drop 1.56 stabilizations from 1.55 release notes
  RELEASES.md
Labels: beta-nominated, beta-accepted, S-waiting-on-bors

#86263 Rustdoc: Report Layout of enum variants
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc/type-layout.rs
Labels: T-rustdoc, S-waiting-on-bors, requires-nightly, A-layout

#88752 Bump stage0 compiler to 1.56
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_ast_passes/src/lib.rs
  compiler/rustc_const_eval/src/lib.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_errors/src/lib.rs
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_mir_transform/src/lib.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_typeck/src/lib.rs
  library/alloc/src/lib.rs
  library/core/src/fmt/mod.rs
  library/core/src/hint.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/core/src/macros/mod.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/src/panicking.rs
  library/core/src/slice/mod.rs
  library/core/src/str/converts.rs
  library/core/src/str/mod.rs
  library/std/src/lib.rs
  library/std/src/net/ip.rs
  library/std/src/panicking.rs
  library/std/src/primitive_docs.rs
  src/stage0.json
Labels: S-waiting-on-bors, merged-by-bors

#88748 Revert "Remove optimization_fuel_crate from Session"
  compiler/rustc_session/src/session.rs
Labels: S-waiting-on-bors, merged-by-bors

#88676 update of the CI freebsd toolchain
  src/ci/docker/scripts/freebsd-toolchain.sh
Labels: S-waiting-on-bors, merged-by-bors

#88797 Work around CI issue with windows sdk 10.0.20348.0.
  .github/workflows/ci.yml
  src/ci/github-actions/ci.yml
  src/ci/scripts/install-clang.sh
  src/test/debuginfo/basic-types.rs
  src/test/debuginfo/msvc-pretty-enums.rs
  src/test/debuginfo/pretty-std.rs
Labels: S-waiting-on-bors, merged-by-bors

#88732 RustWrapper: avoid deleted unclear attribute methods
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
Labels: S-waiting-on-bors

#88742 Fix table in docblocks
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/static/css/rustdoc.css
  src/test/rustdoc-gui/docblock-table-overflow.goml
  src/test/rustdoc-gui/src/lib2/lib.rs
  src/test/rustdoc/table-in-docblock.rs
Labels: T-rustdoc, S-waiting-on-bors, A-rustdoc-ui

#88776 Workaround blink/chromium grid layout limitation of 1000 rows
  src/librustdoc/html/render/print_item.rs
Labels: T-rustdoc, beta-nominated, S-waiting-on-bors, A-rustdoc-ui

#88807 Fix typo in docs for iterators
  library/std/src/collections/mod.rs
Labels: S-waiting-on-bors

#88812 Fix typo `option` -> `options`.
  src/doc/unstable-book/src/library-features/asm.md
Labels: S-waiting-on-bors

#88546 Emit proper errors when on missing closure braces
  compiler/rustc_parse/src/parser/expr.rs
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/expr/malformed_closure/missing_braces_around_block.fixed
  src/test/ui/expr/malformed_closure/missing_braces_around_block.rs
  src/test/ui/expr/malformed_closure/missing_braces_around_block.stderr
  src/test/ui/expr/malformed_closure/ruby_style_closure.rs
  src/test/ui/expr/malformed_closure/ruby_style_closure.stderr
Labels: S-waiting-on-bors

#88578 fix(rustc): suggest `items` be borrowed in `for i in items[x..]`
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  src/test/ui/issues/issue-20605.stderr
  src/test/ui/suggestions/slice-issue-87994.rs
  src/test/ui/suggestions/slice-issue-87994.stderr
Labels: S-waiting-on-bors

#88632 Fix issues with Markdown summary options
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/bare_urls.rs
  src/librustdoc/passes/html_tags.rs
Labels: T-rustdoc, S-waiting-on-bors, A-markdown-parsing

#88639 rustdoc: Fix ICE with `doc(hidden)` on tuple variant fields
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc/issue-88600.rs
Labels: T-rustdoc, beta-nominated, beta-accepted, S-waiting-on-bors

#88667 Tweak `write_fmt` doc.
  library/std/src/io/mod.rs
Labels: S-waiting-on-bors, T-libs

#87088 Fix stray notes when the source code is not available
  compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs
Labels: T-compiler, S-waiting-on-bors

#87441 Emit suggestion when passing byte literal to format macro
  compiler/rustc_builtin_macros/src/asm.rs
  compiler/rustc_builtin_macros/src/format.rs
  compiler/rustc_expand/src/base.rs
  src/test/ui/issues/issue-86865.rs
  src/test/ui/issues/issue-86865.stderr
Labels: T-compiler, S-waiting-on-bors

#85200 Ignore derived Clone and Debug implementations during dead code analysis
  compiler/rustc_feature/src/accepted.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_feature/src/lib.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_middle/src/hir/map/collector.rs
  compiler/rustc_middle/src/ich/hcx.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_build/src/build/matches/simplify.rs
  compiler/rustc_mir_build/src/build/scope.rs
  compiler/rustc_mir_transform/src/coverage/mod.rs
  compiler/rustc_passes/src/dead.rs
  compiler/rustc_span/src/symbol.rs
  library/core/src/clone.rs
  library/core/src/fmt/mod.rs
  library/core/tests/fmt/builders.rs
  library/std/src/io/buffered/tests.rs
  library/test/src/term/terminfo/mod.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render/mod.rs
  src/test/ui/array-slice-vec/slice_binary_search.rs
  src/test/ui/borrowck/borrowck-unused-mut-locals.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/liveness.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/liveness.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/liveness_unintentional_copy.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/liveness_unintentional_copy.stderr
  src/test/ui/closures/2229_closure_analysis/run_pass/struct-pattern-matching-with-methods.rs
  src/test/ui/closures/2229_closure_analysis/run_pass/unsafe_ptr.rs
  src/test/ui/const-generics/broken-mir-2.rs
  src/test/ui/derives/clone-debug-dead-code.rs
  src/test/ui/derives/clone-debug-dead-code.stderr
  src/test/ui/deriving/deriving-clone-generic-struct.rs
  src/test/ui/deriving/deriving-clone-struct.rs
  src/test/ui/deriving/deriving-clone-tuple-struct.rs
  src/test/ui/deriving/deriving-in-fn.rs
  src/test/ui/issues/issue-19358.rs
  src/test/ui/issues/issue-3794.rs
  src/test/ui/monomorphize-abi-alignment.rs
  src/test/ui/moves/move-1-unique.rs
  src/test/ui/moves/move-3-unique.rs
  src/test/ui/overloaded/overloaded-autoderef-order.rs
  src/test/ui/self/ufcs-explicit-self.rs
  src/test/ui/structs-enums/class-cast-to-trait-multiple-types.rs
  src/test/ui/structs-enums/class-implement-traits.rs
  src/test/ui/structs-enums/functional-struct-upd.rs
  src/test/ui/structs-enums/tag-align-shape.rs
  src/tools/clippy/clippy_lints/src/macro_use.rs
  src/tools/clippy/clippy_lints/src/regex.rs
  src/tools/clippy/tests/ui/default_trait_access.fixed
  src/tools/clippy/tests/ui/default_trait_access.rs
  src/tools/rustfmt/src/macros.rs
  src/tools/rustfmt/src/modules.rs
Labels: T-lang, S-waiting-on-bors, disposition-merge, finished-final-comment-period

#86165 Add proc_macro::Span::{before, after}.
  compiler/rustc_expand/src/proc_macro_server.rs
  library/proc_macro/src/bridge/mod.rs
  library/proc_macro/src/lib.rs
Labels: T-libs-api, S-waiting-on-bors, A-proc-macros

#88214 rustc: use more correct span data in for loop desugaring
  compiler/rustc_ast_lowering/src/expr.rs
  src/test/mir-opt/remove_storage_markers.main.RemoveStorageMarkers.diff
  src/test/ui/borrowck/issue-82462.nll.stderr
  src/test/ui/borrowck/issue-82462.rs
  src/test/ui/borrowck/issue-82462.stderr
  src/tools/clippy/clippy_lints/src/loops/for_kv_map.rs
  src/tools/clippy/clippy_lints/src/loops/iter_next_loop.rs
  src/tools/clippy/clippy_lints/src/loops/mod.rs
  src/tools/clippy/clippy_lints/src/loops/needless_range_loop.rs
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88327 `WrappingRange` (#88242) follow-up (`is_full_for`, `Scalar: Copy`, etc.)
  compiler/rustc_codegen_cranelift/src/abi/pass_mode.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_cranelift/src/value_and_place.rs
  compiler/rustc_codegen_llvm/src/abi.rs
  compiler/rustc_codegen_llvm/src/asm.rs
  compiler/rustc_codegen_llvm/src/builder.rs
  compiler/rustc_codegen_llvm/src/common.rs
  compiler/rustc_codegen_llvm/src/consts.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_llvm/src/type_of.rs
  compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_codegen_ssa/src/mir/constant.rs
  compiler/rustc_codegen_ssa/src/mir/operand.rs
  compiler/rustc_codegen_ssa/src/mir/place.rs
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_codegen_ssa/src/traits/builder.rs
  compiler/rustc_codegen_ssa/src/traits/consts.rs
  compiler/rustc_const_eval/src/interpret/intrinsics.rs
  compiler/rustc_const_eval/src/interpret/operand.rs
  compiler/rustc_const_eval/src/interpret/place.rs
  compiler/rustc_const_eval/src/interpret/terminator.rs
  compiler/rustc_const_eval/src/interpret/validity.rs
  compiler/rustc_lint/src/types.rs
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_middle/src/ty/util.rs
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_target/src/abi/call/mips64.rs
  compiler/rustc_target/src/abi/call/mod.rs
  compiler/rustc_target/src/abi/call/riscv.rs
  compiler/rustc_target/src/abi/call/s390x.rs
  compiler/rustc_target/src/abi/call/x86.rs
  compiler/rustc_target/src/abi/call/x86_64.rs
  compiler/rustc_target/src/abi/mod.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
Labels: S-waiting-on-bors, merged-by-bors

#88757 Suggest wapping expr in parentheses on invalid unary negation
  compiler/rustc_typeck/src/check/op.rs
  src/test/ui/parser/expr-as-stmt.fixed
  src/test/ui/parser/expr-as-stmt.rs
  src/test/ui/parser/expr-as-stmt.stderr
Labels: S-waiting-on-bors

#88779 Use more accurate spans for "unused delimiter" lint
  compiler/rustc_lint/src/unused.rs
  src/test/ui/async-await/issues/issue-54752-async-block.stderr
  src/test/ui/const-generics/unused_braces.stderr
  src/test/ui/lint/lint-unnecessary-parens.stderr
  src/test/ui/lint/suggestions.stderr
  src/test/ui/lint/unused/issue-54538-unused-parens-lint.stderr
  src/test/ui/lint/unused/issue-74883-unused-paren-baren-yield.stderr
  src/test/ui/lint/unused_braces.stderr
  src/test/ui/lint/unused_braces_borrow.stderr
  src/test/ui/lint/unused_parens_json_suggestion.stderr
  src/test/ui/lint/unused_parens_remove_json_suggestion.stderr
  src/test/ui/path-lookahead.stderr
  src/test/ui/try-block/try-block-unused-delims.stderr
Labels: S-waiting-on-bors

#88830 Add help for E0463
  compiler/rustc_metadata/src/locator.rs
Labels: A-diagnostics, S-waiting-on-bors, A-suggestion-diagnostics

#88849 don't clone types that are Copy (clippy::clone_on_copy)
  compiler/rustc_borrowck/src/region_infer/mod.rs
  compiler/rustc_infer/src/infer/nll_relate/mod.rs
  compiler/rustc_macros/src/session_diagnostic.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_transform/src/lower_slice_len.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  library/test/src/formatters/junit.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/doctest.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: S-waiting-on-bors

#88850 don't convert types into identical types
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_passes/src/liveness.rs
  compiler/rustc_passes/src/region.rs
Labels: S-waiting-on-bors

#88857 Rollup of 10 pull requests
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_borrowck/src/region_infer/mod.rs
  compiler/rustc_builtin_macros/src/asm.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_infer/src/infer/nll_relate/mod.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_macros/src/session_diagnostic.rs
  compiler/rustc_metadata/src/locator.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir_build/src/build/matches/mod.rs
  compiler/rustc_mir_transform/src/lower_slice_len.rs
  compiler/rustc_parse/src/parser/attr_wrapper.rs
  compiler/rustc_passes/src/liveness.rs
  compiler/rustc_passes/src/region.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/check/coercion.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  compiler/rustc_typeck/src/check/op.rs
  library/core/src/marker.rs
  library/test/src/formatters/junit.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/ui/asm/parse-error.rs
  src/test/ui/asm/parse-error.stderr
  src/test/ui/async-await/issues/issue-54752-async-block.stderr
  src/test/ui/coercion/issue-88097.rs
  src/test/ui/const-generics/unused_braces.stderr
  src/test/ui/lint/lint-unnecessary-parens.stderr
  src/test/ui/lint/suggestions.stderr
  src/test/ui/lint/unused/issue-54538-unused-parens-lint.stderr
  src/test/ui/lint/unused/issue-74883-unused-paren-baren-yield.stderr
  src/test/ui/lint/unused_braces.stderr
  src/test/ui/lint/unused_braces_borrow.stderr
  src/test/ui/lint/unused_parens_json_suggestion.stderr
  src/test/ui/lint/unused_parens_remove_json_suggestion.stderr
  src/test/ui/parser/expr-as-stmt.fixed
  src/test/ui/parser/expr-as-stmt.rs
  src/test/ui/parser/expr-as-stmt.stderr
  src/test/ui/path-lookahead.stderr
  src/test/ui/try-block/try-block-unused-delims.stderr
  src/test/ui/type/type-check/issue-88577-check-fn-with-more-than-65535-arguments.rs
  src/test/ui/type/type-check/issue-88577-check-fn-with-more-than-65535-arguments.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#88209 Improve error message when _ is used for in/inout asm operands
  compiler/rustc_builtin_macros/src/asm.rs
  src/test/ui/asm/parse-error.rs
  src/test/ui/asm/parse-error.stderr
Labels: A-inline-assembly, T-lang, T-compiler, S-waiting-on-bors

#88668 Change more x64 size checks to not apply to x32.
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_parse/src/parser/attr_wrapper.rs
  src/librustdoc/html/render/context.rs
Labels: S-waiting-on-bors

#88733 Fix ICE for functions with more than 65535 arguments
  compiler/rustc_ast_passes/src/ast_validation.rs
  src/test/ui/type/type-check/issue-88577-check-fn-with-more-than-65535-arguments.rs
  src/test/ui/type/type-check/issue-88577-check-fn-with-more-than-65535-arguments.stderr
Labels: T-lang, S-waiting-on-bors

#87904 Reword description of automatic impls of `Unsize`.
  library/core/src/marker.rs
Labels: T-libs-api, S-waiting-on-bors

#88147 Fix non-capturing closure return type coercion
  compiler/rustc_typeck/src/check/coercion.rs
  src/test/ui/coercion/issue-88097.rs
Labels: T-compiler, S-waiting-on-bors

#78780 Refactor query forcing
  compiler/rustc_query_system/src/dep_graph/graph.rs
  compiler/rustc_query_system/src/query/job.rs
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: C-cleanup, T-compiler, S-waiting-on-bors, merged-by-bors, A-query-system, perf-regression, perf-regression-triaged

#88771 Use FxHashSet instead of Vec for well formed tys
  compiler/rustc_borrowck/src/type_check/free_region_relations.rs
  compiler/rustc_trait_selection/src/infer.rs
  compiler/rustc_typeck/src/check/check.rs
  compiler/rustc_typeck/src/check/compare_method.rs
  compiler/rustc_typeck/src/check/mod.rs
  compiler/rustc_typeck/src/check/regionck.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
Labels: S-waiting-on-bors, merged-by-bors

#88677 rustc: Remove local variable IDs from `Export`s
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_data_structures/src/stable_hasher.rs
  compiler/rustc_hir/src/def.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/hir/exports.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/imports.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_serialize/src/serialize.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/visit_lib.rs
  src/tools/clippy/clippy_utils/src/lib.rs
Labels: S-waiting-on-bors

#88699 Remove extra unshallow from cherry-pick checker
  src/ci/scripts/verify-backported-commits.sh
Labels: S-waiting-on-bors

#88709 generic_const_exprs: use thir for abstract consts instead of mir
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/mir/abstract_const.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/thir.rs
  compiler/rustc_middle/src/thir/abstract_const.rs
  compiler/rustc_middle/src/thir/visit.rs
  compiler/rustc_middle/src/traits/mod.rs
  compiler/rustc_middle/src/ty/codec.rs
  compiler/rustc_mir_build/src/build/mod.rs
  compiler/rustc_mir_build/src/check_unsafety.rs
  compiler/rustc_mir_build/src/thir/mod.rs
  compiler/rustc_mir_transform/src/lib.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_query_impl/src/on_disk_cache.rs
  compiler/rustc_trait_selection/src/traits/const_evaluatable.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/fulfill.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_trait_selection/src/traits/object_safety.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/ui/const-generics/generic_const_exprs/abstract-consts-as-cast-5.rs
  src/test/ui/const-generics/generic_const_exprs/abstract-consts-as-cast-5.stderr
  src/test/ui/const-generics/generic_const_exprs/array-size-in-generic-struct-param.full.stderr
  src/test/ui/const-generics/generic_const_exprs/closures.stderr
  src/test/ui/const-generics/generic_const_exprs/let-bindings.stderr
  src/test/ui/const-generics/generic_const_exprs/unify-op-with-fn-call.rs
  src/test/ui/const-generics/generic_const_exprs/unify-op-with-fn-call.stderr
  src/test/ui/const-generics/generic_const_exprs/unused_expr.stderr
  src/test/ui/const-generics/issues/issue-67375.full.stderr
  src/test/ui/const-generics/issues/issue-67945-2.full.stderr
Labels: S-waiting-on-bors

#88711 Rework DepthFirstSearch API
  compiler/rustc_data_structures/src/graph/iterate/mod.rs
  compiler/rustc_data_structures/src/graph/iterate/tests.rs
  compiler/rustc_data_structures/src/graph/mod.rs
Labels: S-waiting-on-bors

#88810 rustdoc: Cleanup `clean` part 1
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc/synthetic_auto/no-redundancy.rs
Labels: C-cleanup, T-rustdoc, S-waiting-on-bors

#88813 explicitly link to external `ena` docs
  src/bootstrap/doc.rs
Labels: A-rustbuild, A-docs, S-waiting-on-bors

#88336 Detect stricter constraints on gats where clauses in impls vs trait
  compiler/rustc_infer/src/infer/error_reporting/nice_region_error/trait_impl_difference.rs
  compiler/rustc_infer/src/infer/error_reporting/note.rs
  compiler/rustc_infer/src/infer/mod.rs
  src/test/ui/generic-associated-types/impl_bounds.rs
  src/test/ui/generic-associated-types/impl_bounds.stderr
  src/test/ui/generic-associated-types/issue-86787.stderr
  src/test/ui/generic-associated-types/missing-where-clause-on-trait.rs
  src/test/ui/generic-associated-types/missing-where-clause-on-trait.stderr
Labels: S-waiting-on-bors

#88811 Use a HashMap for UniverseInfo in mir borrowck
  compiler/rustc_borrowck/src/region_infer/mod.rs
  compiler/rustc_borrowck/src/type_check/canonical.rs
  compiler/rustc_borrowck/src/type_check/input_output.rs
  compiler/rustc_borrowck/src/type_check/mod.rs
  compiler/rustc_borrowck/src/type_check/relate_tys.rs
  src/test/ui/hrtb/issue-88446.rs
Labels: S-waiting-on-bors, merged-by-bors, perf-regression

#88759 Add -Z panic-in-drop={unwind,abort} command-line option
  compiler/rustc_codegen_llvm/src/abi.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_metadata/src/dependency_format.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_mir_transform/src/abort_unwinding_calls.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_typeck/src/collect.rs
  src/test/codegen/panic-in-drop-abort.rs
Labels: S-waiting-on-bors, merged-by-bors, perf-regression

#88839 Introduce NullOp::AlignOf
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_ssa/src/mir/intrinsic.rs
  compiler/rustc_codegen_ssa/src/mir/rvalue.rs
  compiler/rustc_const_eval/src/interpret/intrinsics.rs
  compiler/rustc_const_eval/src/interpret/step.rs
  compiler/rustc_const_eval/src/transform/check_consts/check.rs
  compiler/rustc_const_eval/src/transform/promote_consts.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/tcx.rs
  compiler/rustc_mir_dataflow/src/move_paths/builder.rs
  compiler/rustc_mir_transform/src/lower_intrinsics.rs
  src/test/mir-opt/lower_intrinsics.align_of.LowerIntrinsics.diff
  src/test/mir-opt/lower_intrinsics.discriminant.LowerIntrinsics.diff
  src/test/mir-opt/lower_intrinsics.f_u64.PreCodegen.before.mir
  src/test/mir-opt/lower_intrinsics.f_unit.PreCodegen.before.mir
  src/test/mir-opt/lower_intrinsics.forget.LowerIntrinsics.diff
  src/test/mir-opt/lower_intrinsics.non_const.LowerIntrinsics.diff
  src/test/mir-opt/lower_intrinsics.rs
  src/test/mir-opt/lower_intrinsics.unreachable.LowerIntrinsics.diff
  src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs
Labels: S-waiting-on-bors, merged-by-bors

#88517 Update Clippy dependencies without patch versions
  Cargo.lock
  src/tools/clippy/Cargo.toml
  src/tools/clippy/clippy_dev/Cargo.toml
  src/tools/clippy/clippy_dummy/Cargo.toml
  src/tools/clippy/clippy_lints/Cargo.toml
  src/tools/clippy/clippy_lints/src/cargo_common_metadata.rs
  src/tools/clippy/clippy_utils/Cargo.toml
  src/tools/clippy/lintcheck/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#88529 ARMv6K Nintendo 3DS Tier 3 target added
  compiler/rustc_target/src/spec/armv6k_nintendo_3ds.rs
  compiler/rustc_target/src/spec/mod.rs
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors, A-target-specs, merged-by-bors

#88745 Allow missing code examples in trait impls.
  src/librustdoc/passes/doc_test_lints.rs
  src/test/rustdoc-ui/lint-missing-doc-code-example.rs
Labels: T-rustdoc, A-lint, S-waiting-on-bors, merged-by-bors

#87915 Use smaller spans for some structured suggestions
  compiler/rustc_errors/src/diagnostic.rs
  compiler/rustc_errors/src/diagnostic_builder.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/demand.rs
  compiler/rustc_typeck/src/collect.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
  src/test/ui/anon-params/anon-params-denied-2018.stderr
  src/test/ui/associated-types/associated-type-projection-ambig-between-bound-and-where-clause.stderr
  src/test/ui/associated-types/associated-type-projection-from-multiple-supertraits.stderr
  src/test/ui/associated-types/associated-types-path-1.stderr
  src/test/ui/associated-types/associated-types-path-2.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-fn.stderr
  src/test/ui/associated-types/associated-types-project-from-hrtb-in-trait-method.stderr
  src/test/ui/const-generics/type-dependent/type-mismatch.full.stderr
  src/test/ui/const-generics/type-dependent/type-mismatch.min.stderr
  src/test/ui/discrim/discrim-ill-typed.stderr
  src/test/ui/error-codes/E0221.stderr
  src/test/ui/float-literal-inference-restrictions.stderr
  src/test/ui/indexing-requires-a-uint.stderr
  src/test/ui/integer-literal-suffix-inference.stderr
  src/test/ui/issues/issue-13359.stderr
  src/test/ui/issues/issue-1362.stderr
  src/test/ui/issues/issue-1448-2.stderr
  src/test/ui/issues/issue-8761.stderr
  src/test/ui/meta/expected-error-correct-rev.a.stderr
  src/test/ui/meta/meta-expected-error-wrong-rev.a.stderr
  src/test/ui/methods/method-ambig-one-trait-unknown-int-type.stderr
  src/test/ui/mismatched_types/issue-26480.stderr
  src/test/ui/mismatched_types/numeric-literal-cast.stderr
  src/test/ui/numeric/const-scope.stderr
  src/test/ui/numeric/len.stderr
  src/test/ui/numeric/numeric-cast-2.stderr
  src/test/ui/numeric/numeric-cast-binop.stderr
  src/test/ui/numeric/numeric-cast-no-fix.stderr
  src/test/ui/numeric/numeric-cast.stderr
  src/test/ui/numeric/numeric-suffix.stderr
  src/test/ui/parser/inverted-parameters.stderr
  src/test/ui/parser/lifetime-in-pattern.stderr
  src/test/ui/parser/omitted-arg-in-item-fn.stderr
  src/test/ui/parser/pat-lt-bracket-2.stderr
  src/test/ui/pptypedef.stderr
  src/test/ui/proc-macro/span-preservation.stderr
  src/test/ui/repeat_count.stderr
  src/test/ui/rfc-2565-param-attrs/param-attrs-2018.stderr
  src/test/ui/shift-various-bad-types.stderr
  src/test/ui/span/issue-34264.stderr
  src/test/ui/suggestions/issue-64252-self-type.stderr
  src/test/ui/suggestions/type-mismatch-struct-field-shorthand-2.stderr
  src/test/ui/suggestions/type-mismatch-struct-field-shorthand.stderr
  src/test/ui/tail-typeck.stderr
  src/test/ui/traits/multidispatch-bad.stderr
  src/test/ui/trivial-bounds/trivial-bounds-inconsistent-projection-error.stderr
  src/test/ui/tutorial-suffix-inference-test.stderr
  src/test/ui/typeof/type_mismatch.stderr
  src/test/ui/ufcs/ufcs-qpath-self-mismatch.stderr
  src/test/ui/unboxed-closures/unboxed-closures-type-mismatch.stderr
  src/test/ui/wrong-ret-type.stderr
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#87794 Enum should prefer discriminant zero for niche
  compiler/rustc_target/src/abi/mod.rs
  src/test/assembly/niche-prefer-zero.rs
  src/test/ui/enum-discriminant/niche-prefer-zero.rs
Labels: T-compiler, S-waiting-on-bors, merged-by-bors

#88722 Make `UnsafeCell::get_mut` const
  library/core/src/cell.rs
Labels: T-libs-api, S-waiting-on-bors

#88851 Fix duplicate bounds for const_trait_impl
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/ui/rfc-2632-const-trait-impl/call-generic-method-dup-bound.rs
Labels: S-waiting-on-bors

#88859 interpreter PointerArithmetic: use new Size helper methods
  compiler/rustc_middle/src/mir/interpret/pointer.rs
Labels: S-waiting-on-bors
