Repository rust-lang/rust, pull requests merged in 2021-05, with the labels that each got.

#84719 Move iter_results to dyn FnMut rather than a generic
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_query_impl/src/profiling_support.rs
  compiler/rustc_query_impl/src/stats.rs
  compiler/rustc_query_system/src/query/caches.rs
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: S-waiting-on-bors, merged-by-bors

#84747 Bump version to 1.54.0
  src/version
Labels: S-waiting-on-bors, merged-by-bors

#84463 rustdoc: Remove unnecessary `provided_trait_methods` field from Impl
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/json/conversions.rs
Labels: A-rustdoc, C-cleanup, I-compilemem, S-waiting-on-bors, merged-by-bors

#84582 Vastly improves coverage spans for macros
  compiler/rustc_mir/src/transform/coverage/spans.rs
  compiler/rustc_mir/src/transform/coverage/tests.rs
  compiler/rustc_mir/src/util/spanview.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.closure_macro.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.closure_macro_async.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.inner_items.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.issue-83601.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.issue-84561.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.uses_crate.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.uses_inline_crate.txt
  src/test/run-make-fulldeps/coverage/closure_macro.rs
  src/test/run-make-fulldeps/coverage/closure_macro_async.rs
  src/test/run-make-fulldeps/coverage/issue-84561.rs
Labels: S-waiting-on-bors, merged-by-bors

#84704 platform-support.md: Update for consistency with Target Tier Policy
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors

#84724 Replace llvm::sys::fs::F_None with llvm::sys::fs::OF_None
  compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp
Labels: S-waiting-on-bors

#84740 Reset the docs' copy path button after 1 second
  src/librustdoc/html/static/main.js
Labels: A-rustdoc, A-rustdoc-js, S-waiting-on-bors

#84749 Sync `rustc_codegen_cranelift`
  compiler/rustc_codegen_cranelift/.github/workflows/main.yml
  compiler/rustc_codegen_cranelift/.vscode/settings.json
  compiler/rustc_codegen_cranelift/Cargo.lock
  compiler/rustc_codegen_cranelift/Cargo.toml
  compiler/rustc_codegen_cranelift/Readme.md
  compiler/rustc_codegen_cranelift/build_sysroot/Cargo.lock
  compiler/rustc_codegen_cranelift/build_sysroot/prepare_sysroot_src.sh
  compiler/rustc_codegen_cranelift/crate_patches/0001-compiler-builtins-Remove-rotate_left-from-Int.patch
  compiler/rustc_codegen_cranelift/docs/env_vars.md
  compiler/rustc_codegen_cranelift/example/mini_core_hello_world.rs
  compiler/rustc_codegen_cranelift/example/std_example.rs
  compiler/rustc_codegen_cranelift/rust-toolchain
  compiler/rustc_codegen_cranelift/scripts/ext_config.sh
  compiler/rustc_codegen_cranelift/scripts/setup_rust_fork.sh
  compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh
  compiler/rustc_codegen_cranelift/src/abi/mod.rs
  compiler/rustc_codegen_cranelift/src/allocator.rs
  compiler/rustc_codegen_cranelift/src/backend.rs
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_cranelift/src/config.rs
  compiler/rustc_codegen_cranelift/src/constant.rs
  compiler/rustc_codegen_cranelift/src/debuginfo/unwind.rs
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/driver/jit.rs
  compiler/rustc_codegen_cranelift/src/driver/mod.rs
  compiler/rustc_codegen_cranelift/src/inline_asm.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/cpuid.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/llvm.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/simd.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/linkage.rs
  compiler/rustc_codegen_cranelift/src/main_shim.rs
  compiler/rustc_codegen_cranelift/src/metadata.rs
  compiler/rustc_codegen_cranelift/src/num.rs
  compiler/rustc_codegen_cranelift/src/optimize/code_layout.rs
  compiler/rustc_codegen_cranelift/src/optimize/mod.rs
  compiler/rustc_codegen_cranelift/src/optimize/stack2reg.rs
  compiler/rustc_codegen_cranelift/src/pretty_clif.rs
  compiler/rustc_codegen_cranelift/src/trap.rs
  compiler/rustc_codegen_cranelift/src/value_and_place.rs
  compiler/rustc_codegen_cranelift/src/vtable.rs
Labels: A-codegen, A-cranelift, S-waiting-on-bors, T-compiler

#84756 Add a ToC to the Target Tier Policy documentation
  src/doc/rustc/src/target-tier-policy.md
Labels: S-waiting-on-bors

#84774 Fix misspelling
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
Labels: S-waiting-on-bors

#84601 rustdoc: Only store locations in Cache::extern_locations and calculate the other info on-demand
  src/librustdoc/clean/types.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/json/mod.rs
Labels: A-rustdoc, C-cleanup, I-compilemem, S-waiting-on-bors

#84658 Be stricter about rejecting LLVM reserved registers in asm!
  compiler/rustc_target/src/asm/aarch64.rs
  compiler/rustc_target/src/asm/arm.rs
  compiler/rustc_target/src/asm/hexagon.rs
  compiler/rustc_target/src/asm/riscv.rs
  compiler/rustc_target/src/asm/x86.rs
  library/std/src/sys/sgx/ext/arch.rs
  src/doc/unstable-book/src/library-features/asm.md
  src/test/codegen/asm-multiple-options.rs
  src/test/codegen/asm-options.rs
  src/test/pretty/asm.pp
  src/test/pretty/asm.rs
Labels: S-waiting-on-bors, merged-by-bors

#83857 added --no-run option for rustdoc
  src/librustdoc/config.rs
  src/librustdoc/doctest.rs
  src/librustdoc/lib.rs
  src/test/rustdoc-ui/no-run-flag-error.rs
  src/test/rustdoc-ui/no-run-flag-error.stderr
  src/test/rustdoc-ui/no-run-flag.rs
  src/test/rustdoc-ui/no-run-flag.stdout
Labels: A-rustdoc, S-waiting-on-bors, merged-by-bors

#83114 Move HIR parenting information out of hir_owner
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_middle/src/arena.rs
  compiler/rustc_middle/src/hir/map/collector.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/hir/mod.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_ty_utils/src/ty.rs
  src/test/incremental/hashes/inherent_impls.rs
  src/test/incremental/hashes/type_defs.rs
  src/test/incremental/ich_nested_items.rs
Labels: S-waiting-on-bors, merged-by-bors

#84410 Fix generic arg mismatch errors being ignored with explicit late bound lifetimes
  compiler/rustc_typeck/src/astconv/generics.rs
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  src/test/ui/const-generics/issues/issue-83466.rs
  src/test/ui/const-generics/issues/issue-83466.stderr
Labels: F-const_generics, S-waiting-on-bors, merged-by-bors

#84471 Allow running `x.py test --stage 2 src/tools/linkchecker` with `download-rustc = true`
  src/bootstrap/tool.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors, merged-by-bors

#84638 Unignore a couple of tests
  src/test/ui/or-patterns/macro-pat.rs
  src/test/ui/or-patterns/or-patterns-syntactic-pass-2021.rs
Labels: S-waiting-on-bors, merged-by-bors

#84725 [Arm64] use isb instruction instead of yield in spin loops
  library/core/src/hint.rs
Labels: S-waiting-on-bors, merged-by-bors

#84750 Don't download cargo twice when download-rustc is set
  src/bootstrap/bootstrap.py
Labels: A-rustbuild, O-NixOS, S-waiting-on-bors, merged-by-bors

#84805 Avoid generating QueryMap::extend for each key type
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: S-waiting-on-bors, merged-by-bors

#84802 Remove dead code in `rustc_session::Options`
  compiler/rustc_session/src/options.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#84752 Fix debuginfo for generators
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  src/test/codegen/async-fn-debug-msvc.rs
  src/test/codegen/async-fn-debug.rs
  src/test/codegen/generator-debug-msvc.rs
  src/test/codegen/generator-debug.rs
  src/test/debuginfo/generator-objects.rs
  src/test/debuginfo/issue-57822.rs
Labels: S-waiting-on-bors

#84763 shrink doctree::Module
  src/librustdoc/clean/mod.rs
  src/librustdoc/doctree.rs
  src/librustdoc/visit_ast.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors

#84821 Fix nit in rustc_session::options
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors

#84358 Update closure capture error logging for disjoint captures for disjoint captures
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/closure.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/move_errors.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/region_errors.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_typeck/src/expr_use_visitor.rs
  src/test/ui/async-await/async-borrowck-escaping-block-error.stderr
  src/test/ui/borrowck/borrowck-closures-mut-and-imm.stderr
  src/test/ui/borrowck/borrowck-closures-mut-of-imm.stderr
  src/test/ui/borrowck/borrowck-closures-mut-of-mut.stderr
  src/test/ui/borrowck/borrowck-closures-slice-patterns.stderr
  src/test/ui/borrowck/borrowck-closures-two-mut-fail.stderr
  src/test/ui/borrowck/borrowck-closures-two-mut.stderr
  src/test/ui/borrowck/borrowck-closures-unique.stderr
  src/test/ui/borrowck/borrowck-closures-use-after-free.stderr
  src/test/ui/borrowck/borrowck-insert-during-each.stderr
  src/test/ui/borrowck/borrowck-loan-blocks-move-cc.stderr
  src/test/ui/borrowck/borrowck-loan-rcvr.stderr
  src/test/ui/borrowck/borrowck-move-by-capture.stderr
  src/test/ui/borrowck/borrowck-move-moved-value-into-closure.stderr
  src/test/ui/borrowck/issue-27282-mutate-before-diverging-arm-2.stderr
  src/test/ui/borrowck/issue-27282-reborrow-ref-mut-in-guard.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-1.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-1.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-2.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-2.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-3.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-3.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-4.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-4.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-closures-mut-and-imm.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/borrowck/borrowck-closures-mut-and-imm.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/box.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm-borrow.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/multilevel-path.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/mut_ref.stderr
  src/test/ui/closures/2229_closure_analysis/diagnostics/simple-struct-min-capture.stderr
  src/test/ui/error-codes/E0504.stderr
  src/test/ui/generator/yield-while-ref-reborrowed.stderr
  src/test/ui/issues/issue-11192.stderr
  src/test/ui/issues/issue-27282-mutate-before-diverging-arm-1.stderr
  src/test/ui/issues/issue-27282-mutate-before-diverging-arm-3.stderr
  src/test/ui/issues/issue-61623.stderr
  src/test/ui/issues/issue-6801.stderr
  src/test/ui/nll/closure-access-spans.stderr
  src/test/ui/nll/closure-borrow-spans.stderr
  src/test/ui/nll/closure-captures.stderr
  src/test/ui/nll/closure-use-spans.stderr
  src/test/ui/nll/closures-in-loops.stderr
  src/test/ui/nll/issue-51268.stderr
  src/test/ui/regions/regions-addr-of-upvar-self.nll.stderr
Labels: S-waiting-on-bors

#84392 Make AssertKind::fmt_assert_args public
  compiler/rustc_middle/src/mir/mod.rs
Labels: S-waiting-on-bors

#84754 Migrate trait and impl blocks' toggles into
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
  src/test/rustdoc/assoc-consts.rs
  src/test/rustdoc/inline_cross/assoc-items.rs
  src/test/rustdoc/inline_cross/impl-inline-without-trait.rs
  src/test/rustdoc/manual_impl.rs
  src/test/rustdoc/trait-impl.rs
Labels: A-rustdoc, A-rustdoc-js, A-rustdoc-ui, S-waiting-on-bors, merged-by-bors

#82576 i8 and u8::to_string() specialisation (far less asm).
  library/alloc/src/string.rs
Labels: S-waiting-on-bors, T-libs-impl, merged-by-bors

#84744 Add ErrorKind::OutOfMemory
  library/std/src/io/error.rs
  library/std/src/sys/unix/mod.rs
  library/std/src/sys/wasi/mod.rs
  library/std/src/sys/windows/c.rs
  library/std/src/sys/windows/mod.rs
  src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed
  src/tools/clippy/tests/ui/wildcard_enum_match_arm.rs
  src/tools/clippy/tests/ui/wildcard_enum_match_arm.stderr
Labels: S-waiting-on-bors, T-libs

#84784 Add help message to suggest const for unused type param
  compiler/rustc_typeck/src/check/wfcheck.rs
  src/test/ui/const-generics/const-param-type-depends-on-type-param.full.stderr
  src/test/ui/const-generics/const-param-type-depends-on-type-param.min.stderr
  src/test/ui/const-generics/issue-67375.full.stderr
  src/test/ui/const-generics/issue-67375.min.stderr
  src/test/ui/const-generics/issue-67945-1.full.stderr
  src/test/ui/const-generics/issue-67945-1.min.stderr
  src/test/ui/const-generics/issue-67945-2.full.stderr
  src/test/ui/const-generics/issue-67945-2.min.stderr
  src/test/ui/const-generics/unused-type-param-suggestion.rs
  src/test/ui/const-generics/unused-type-param-suggestion.stderr
  src/test/ui/enum-discriminant/issue-70453-generics-in-discr-ice.stderr
  src/test/ui/enum/issue-67945-1.stderr
  src/test/ui/enum/issue-67945-2.stderr
  src/test/ui/error-codes/E0392.stderr
  src/test/ui/inner-static-type-parameter.stderr
  src/test/ui/issues/issue-17904-2.stderr
  src/test/ui/issues/issue-20413.stderr
  src/test/ui/issues/issue-36299.stderr
  src/test/ui/issues/issue-36638.stderr
  src/test/ui/issues/issue-37534.stderr
  src/test/ui/variance/variance-unused-type-param.stderr
Labels: S-waiting-on-bors

#84811 RustDoc: Fix bounds linking trait.Foo instead of traitalias.Foo
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/formats/cache.rs
  src/test/rustdoc/auxiliary/trait-alias-mention.rs
  src/test/rustdoc/trait-alias-mention.rs
  src/test/rustdoc/trait_alias.rs
Labels: A-rustdoc, S-waiting-on-bors

#84818 suggestion for unit enum variant when matched with a patern
  compiler/rustc_resolve/src/late/diagnostics.rs
  src/test/ui/empty/empty-struct-unit-pat.stderr
  src/test/ui/issues/issue-32004.stderr
  src/test/ui/issues/issue-pr29383.stderr
  src/test/ui/match/match-pattern-field-mismatch-2.stderr
  src/test/ui/pattern/pattern-error-continue.stderr
  src/test/ui/suggestions/issue-84700.rs
  src/test/ui/suggestions/issue-84700.stderr
Labels: S-waiting-on-bors

#84832 Do not print visibility in external traits
  src/librustdoc/clean/inline.rs
  src/test/rustdoc/auxiliary/trait-visibility.rs
  src/test/rustdoc/trait-visibility.rs
Labels: A-cross-crate-reexports, A-rustdoc, S-waiting-on-bors

#84072 Allow setting `target_family` to multiple values, and implement `target_family="wasm"`
  compiler/rustc_session/src/config.rs
  compiler/rustc_target/src/spec/apple_base.rs
  compiler/rustc_target/src/spec/dragonfly_base.rs
  compiler/rustc_target/src/spec/freebsd_base.rs
  compiler/rustc_target/src/spec/fuchsia_base.rs
  compiler/rustc_target/src/spec/haiku_base.rs
  compiler/rustc_target/src/spec/illumos_base.rs
  compiler/rustc_target/src/spec/l4re_base.rs
  compiler/rustc_target/src/spec/linux_base.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/netbsd_base.rs
  compiler/rustc_target/src/spec/openbsd_base.rs
  compiler/rustc_target/src/spec/redox_base.rs
  compiler/rustc_target/src/spec/solaris_base.rs
  compiler/rustc_target/src/spec/vxworks_base.rs
  compiler/rustc_target/src/spec/wasm32_unknown_emscripten.rs
  compiler/rustc_target/src/spec/wasm_base.rs
  compiler/rustc_target/src/spec/windows_gnu_base.rs
  compiler/rustc_target/src/spec/windows_msvc_base.rs
  src/test/ui/cfg/cfg-family.rs
  src/test/ui/cfg/cfg-target-family.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period

#84842 Replace 'NULL' with 'null'
  compiler/rustc_codegen_llvm/src/metadata.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_metadata/src/dynamic_lib.rs
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/memory.rs
  compiler/rustc_mir/src/interpret/place.rs
  compiler/rustc_mir/src/interpret/validity.rs
  library/alloc/src/boxed.rs
  library/core/src/intrinsics.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/ptr/const_ptr.rs
  library/core/src/ptr/mod.rs
  library/core/src/ptr/mut_ptr.rs
  library/core/src/ptr/non_null.rs
  library/panic_unwind/src/seh.rs
  library/std/src/ffi/c_str.rs
  library/std/src/sys/unix/ext/net/ancillary.rs
  library/std/src/sys/unix/fs.rs
  library/std/src/sys/unix/process/process_common.rs
  library/std/src/thread/local.rs
  src/test/ui/consts/const-eval/ub-nonnull.32bit.stderr
  src/test/ui/consts/const-eval/ub-nonnull.64bit.stderr
  src/test/ui/consts/const-eval/ub-nonnull.rs
  src/test/ui/consts/const-eval/ub-ref-ptr.32bit.stderr
  src/test/ui/consts/const-eval/ub-ref-ptr.64bit.stderr
  src/test/ui/consts/const-eval/ub-upvars.32bit.stderr
  src/test/ui/consts/const-eval/ub-upvars.64bit.stderr
  src/test/ui/generator/issue-45729-unsafe-in-generator.stderr
  src/test/ui/issues/issue-47412.stderr
  src/test/ui/traits/safety-fn-body.stderr
  src/test/ui/unsafe/issue-45087-unreachable-unsafe.stderr
  src/test/ui/unsafe/rfc-2585-unsafe_op_in_unsafe_fn.stderr
  src/test/ui/unsafe/unsafe-fn-assign-deref-ptr.stderr
  src/test/ui/unsafe/unsafe-fn-deref-ptr.stderr
  src/test/ui/unsafe/unsafe-unstable-const-fn.stderr
Labels: S-waiting-on-bors, merged-by-bors

#84845 [clippy] remove redundant field names
  library/core/src/num/bignum.rs
Labels: S-waiting-on-bors, merged-by-bors

#83312 parser: Remove support for inner attributes on non-block expressions
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_parse/src/parser/expr.rs
  src/test/pretty/ast-stmt-expr-attr.rs
  src/test/pretty/stmt_expr_attributes.rs
  src/test/ui/lint/expr_attr_paren_order.rs
  src/test/ui/lint/expr_attr_paren_order.stderr
  src/test/ui/parser/stmt_expr_attrs_placement.rs
  src/test/ui/parser/stmt_expr_attrs_placement.stderr
  src/test/ui/proc-macro/inner-attrs.rs
  src/test/ui/proc-macro/inner-attrs.stderr
  src/test/ui/proc-macro/inner-attrs.stdout
  src/test/ui/proc-macro/simple-tuple.rs
  src/test/ui/proc-macro/simple-tuple.stdout
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors

#84835 Add link to Issue #34202 in udp docs
  library/std/src/net/udp.rs
Labels: S-waiting-on-bors

#84852 Change librustdoc write!(.. \n) to writeln!(..); fix comment grammar
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/theme.rs
Labels: S-waiting-on-bors

#84854 use double quotes and full path for E0761
  compiler/rustc_expand/src/module.rs
  src/test/ui/modules_and_files_visibility/mod_file_disambig.stderr
Labels: S-waiting-on-bors

#84856 Correct stability of ErrorKind::OutOfMemory
  library/std/src/io/error.rs
Labels: S-waiting-on-bors

#84858 Fix stability attributes of byte-to-string specialization
  library/alloc/src/string.rs
Labels: S-waiting-on-bors

#84860 Link to MCP from target tier policy
  src/doc/rustc/src/target-tier-policy.md
Labels: S-waiting-on-bors

#84862 Rollup of 6 pull requests
  compiler/rustc_expand/src/module.rs
  library/alloc/src/string.rs
  library/std/src/io/error.rs
  library/std/src/net/udp.rs
  src/doc/rustc/src/target-tier-policy.md
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/theme.rs
  src/test/ui/modules_and_files_visibility/mod_file_disambig.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84472 Be more conservative about discarding caller_bound in `ParamEnv::and`
  compiler/rustc_middle/src/ty/flags.rs
  compiler/rustc_type_ir/src/lib.rs
  src/test/ui/traits/issue-84399-bad-fresh-caching.rs
Labels: S-waiting-on-bors, merged-by-bors

#84833 "const" initialized thread locals in rustc
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#84874 CI: Extract LLVM win64 installer directly, using 7z
  src/ci/scripts/install-clang.sh
Labels: S-waiting-on-bors, merged-by-bors

#84017 Valid underscores in hex/octal/binary literal docs
  src/librustdoc/clean/utils.rs
  src/librustdoc/clean/utils/tests.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#84894 Update clang to 12.0.0 on Windows and macOS
  src/ci/scripts/install-clang.sh
Labels: S-waiting-on-bors, merged-by-bors

#84707 Get rid of fake `DefId`s in rustdoc
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/core.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/formats/mod.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/render/write_shared.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/passes/stripper.rs
  src/librustdoc/visit_ast.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors, merged-by-bors

#84915 Retain data in vectorized registers for longer
  compiler/rustc_index/src/bit_set.rs
Labels: S-waiting-on-bors, merged-by-bors

#84794 Deduplicate native libs before they are passed to the linker
  compiler/rustc_codegen_ssa/src/back/link.rs
Labels: S-waiting-on-bors, merged-by-bors

#84200 Move all `sys::ext` modules to `os`
  library/std/src/os/fortanix_sgx/arch.rs
  library/std/src/os/fortanix_sgx/ffi.rs
  library/std/src/os/fortanix_sgx/io.rs
  library/std/src/os/fortanix_sgx/mod.rs
  library/std/src/os/hermit/ffi.rs
  library/std/src/os/hermit/mod.rs
  library/std/src/os/linux/mod.rs
  library/std/src/os/linux/raw.rs
  library/std/src/os/mod.rs
  library/std/src/os/redox/raw.rs
  library/std/src/os/unix/ffi.rs
  library/std/src/os/unix/fs.rs
  library/std/src/os/unix/io.rs
  library/std/src/os/unix/mod.rs
  library/std/src/os/unix/net/addr.rs
  library/std/src/os/unix/net/ancillary.rs
  library/std/src/os/unix/net/datagram.rs
  library/std/src/os/unix/net/listener.rs
  library/std/src/os/unix/net/mod.rs
  library/std/src/os/unix/net/raw_fd.rs
  library/std/src/os/unix/net/stream.rs
  library/std/src/os/unix/net/tests.rs
  library/std/src/os/unix/process.rs
  library/std/src/os/unix/raw.rs
  library/std/src/os/unix/thread.rs
  library/std/src/os/unix/ucred.rs
  library/std/src/os/unix/ucred/tests.rs
  library/std/src/os/wasi.rs
  library/std/src/os/wasi/ffi.rs
  library/std/src/os/wasi/fs.rs
  library/std/src/os/wasi/io.rs
  library/std/src/os/wasi/mod.rs
  library/std/src/os/windows/ffi.rs
  library/std/src/os/windows/fs.rs
  library/std/src/os/windows/io.rs
  library/std/src/os/windows/mod.rs
  library/std/src/os/windows/process.rs
  library/std/src/os/windows/raw.rs
  library/std/src/os/windows/thread.rs
  library/std/src/sys/hermit/mod.rs
  library/std/src/sys/mod.rs
  library/std/src/sys/sgx/ext/mod.rs
  library/std/src/sys/sgx/mod.rs
  library/std/src/sys/unix/mod.rs
  library/std/src/sys/wasi/mod.rs
  library/std/src/sys/windows/mod.rs
  src/tools/clippy/clippy_utils/src/paths.rs
Labels: S-waiting-on-bors, T-libs-impl, merged-by-bors

#84843 use else if in std library
  library/core/src/time.rs
Labels: S-waiting-on-bors

#84865 rustbuild: Pass a `threads` flag that works to windows-gnu lld
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#84878 Clarify documentation for `[T]::contains`
  library/core/src/slice/mod.rs
Labels: S-waiting-on-bors

#84882 platform-support: Center the contents of the `std` and `host` columns
  src/doc/rustc/src/platform-support.md
Labels: S-waiting-on-bors

#84903 Remove `rustc_middle::mir::interpret::CheckInAllocMsg::NullPointerTest`
  compiler/rustc_middle/src/mir/interpret/error.rs
Labels: S-waiting-on-bors

#84913 Do not ICE on invalid const param
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/typeck/issue-84831.rs
  src/test/ui/typeck/issue-84831.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#84956 Rollup of 11 pull requests
  RELEASES.md
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  library/core/src/ptr/mod.rs
  library/core/src/slice/mod.rs
  library/core/src/time.rs
  library/std/src/env.rs
  library/std/src/primitive_docs.rs
  src/bootstrap/test.rs
  src/doc/rustc/src/platform-support.md
  src/test/ui/suggestions/import-trait-for-method-call.rs
  src/test/ui/suggestions/import-trait-for-method-call.stderr
  src/test/ui/typeck/issue-84831.rs
  src/test/ui/typeck/issue-84831.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84709 Add doc alias for `chdir` to `std::env::set_current_dir`
  library/std/src/env.rs
Labels: S-waiting-on-bors

#84803 Reduce duplication in `impl_dep_tracking_hash` macros
  compiler/rustc_session/src/config.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#84808 Account for unsatisfied bounds in E0599
  compiler/rustc_typeck/src/check/method/suggest.rs
  src/test/ui/suggestions/import-trait-for-method-call.rs
  src/test/ui/suggestions/import-trait-for-method-call.stderr
Labels: S-waiting-on-bors, T-compiler, beta-nominated

#83553 Update `ptr` docs with regards to `ptr::addr_of!`
  library/core/src/ptr/mod.rs
  library/std/src/primitive_docs.rs
Labels: S-waiting-on-bors, T-doc

#84183 Update RELEASES.md for 1.52.0
  RELEASES.md
Labels: S-waiting-on-bors, T-release

#84266 alloc: Add unstable Cfg feature `no-global_oom_handling
  library/alloc/src/alloc.rs
  library/alloc/src/borrow.rs
  library/alloc/src/boxed.rs
  library/alloc/src/collections/mod.rs
  library/alloc/src/fmt.rs
  library/alloc/src/lib.rs
  library/alloc/src/raw_vec.rs
  library/alloc/src/rc.rs
  library/alloc/src/slice.rs
  library/alloc/src/str.rs
  library/alloc/src/string.rs
  library/alloc/src/sync.rs
  library/alloc/src/vec/into_iter.rs
  library/alloc/src/vec/mod.rs
  library/alloc/src/vec/partial_eq.rs
  src/test/run-make-fulldeps/alloc-extern-crates/Makefile
  src/test/run-make-fulldeps/alloc-extern-crates/fakealloc.rs
  src/test/run-make-fulldeps/alloc-no-oom-handling/Makefile
Labels: I-nominated, S-waiting-on-bors, T-libs, merged-by-bors

#84468 Fix#84467 linker_args with --target=sparcv9-sun-solaris
  compiler/rustc_codegen_ssa/src/back/linker.rs
Labels: S-waiting-on-bors, merged-by-bors

#84965 lazify backtrace formatting for delayed diagnostics
  compiler/rustc_errors/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#84712 Simplify chdir implementation and minimize unsafe block
  library/std/src/sys/unix/os.rs
Labels: S-waiting-on-bors, T-libs-impl

#84923 Only compute Obligation `cache_key` once in `register_obligation_at`
  compiler/rustc_data_structures/src/obligation_forest/mod.rs
Labels: S-waiting-on-bors

#84945 E0583: Include secondary path in error message
  compiler/rustc_expand/src/module.rs
  src/test/ui/error-codes/E0583.stderr
  src/test/ui/invalid-module-declaration/invalid-module-declaration.stderr
  src/test/ui/missing_non_modrs_mod/missing_non_modrs_mod.stderr
  src/test/ui/missing_non_modrs_mod/missing_non_modrs_mod_inline.stderr
  src/test/ui/parser/mod_file_not_exist.stderr
  src/test/ui/parser/mod_file_not_exist_windows.stderr
  src/test/ui/parser/unsafe-mod.stderr
  src/test/ui/rfc-2457/mod_file_nonascii_forbidden.stderr
Labels: S-waiting-on-bors

#84949 Fix typo in `MaybeUninit::array_assume_init` safety comment
  library/core/src/mem/maybe_uninit.rs
Labels: S-waiting-on-bors

#84950 Revert PR 83866
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/intra-doc/email-address-localhost.stderr
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.stderr
Labels: S-waiting-on-bors

#84328 Stablize {HashMap,BTreeMap}::into_{keys,values}
  library/alloc/src/collections/btree/map.rs
  library/std/src/collections/hash/map.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#83507 Implement RFC 2951: Native link modifiers
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_codegen_cranelift/src/archive.rs
  compiler/rustc_codegen_llvm/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_metadata/src/native_libs.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/utils.rs
  compiler/rustc_span/src/symbol.rs
  src/doc/unstable-book/src/language-features/native-link-modifiers-as-needed.md
  src/doc/unstable-book/src/language-features/native-link-modifiers-bundle.md
  src/doc/unstable-book/src/language-features/native-link-modifiers-verbatim.md
  src/doc/unstable-book/src/language-features/native-link-modifiers-whole-archive.md
  src/doc/unstable-book/src/language-features/native-link-modifiers.md
  src/test/ui/feature-gates/feature-gate-native_link_modifiers.rs
  src/test/ui/feature-gates/feature-gate-native_link_modifiers.stderr
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_as_needed.rs
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_as_needed.stderr
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_bundle.rs
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_bundle.stderr
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_verbatim.rs
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_verbatim.stderr
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_whole_archive.rs
  src/test/ui/feature-gates/feature-gate-native_link_modifiers_whole_archive.stderr
  src/test/ui/feature-gates/feature-gate-static-nobundle-2.stderr
  src/test/ui/feature-gates/feature-gate-static-nobundle.rs
  src/test/ui/feature-gates/feature-gate-static-nobundle.stderr
  src/test/ui/native-library-link-flags/empty-kind-1.rs
  src/test/ui/native-library-link-flags/empty-kind-1.stderr
  src/test/ui/native-library-link-flags/empty-kind-2.rs
  src/test/ui/native-library-link-flags/empty-kind-2.stderr
Labels: S-waiting-on-bors

#84559 Deduplicate ParamCandidates with the same value except for bound vars
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/ui/lifetimes/issue-84398.rs
Labels: S-waiting-on-bors, T-compiler, WG-compiler-traits, beta-accepted, merged-by-bors

#79930 Optimize BufWriter
  library/std/src/io/buffered/bufwriter.rs
Labels: I-slow, S-waiting-on-bors, T-libs-impl, merged-by-bors

#84806 Streamline try_start code
  compiler/rustc_query_system/src/query/caches.rs
  compiler/rustc_query_system/src/query/config.rs
  compiler/rustc_query_system/src/query/job.rs
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: S-waiting-on-bors, merged-by-bors

#84871 Disallows `#![feature(no_coverage)]` on stable and beta (using standard crate-level gating)
  compiler/rustc_builtin_macros/src/deriving/cmp/eq.rs
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_typeck/src/collect.rs
  library/core/src/cmp.rs
  library/core/src/lib.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.no_cov_func.txt
  src/test/run-make-fulldeps/coverage/no_cov_func.rs
  src/test/ui/feature-gates/feature-gate-no_coverage.rs
  src/test/ui/feature-gates/feature-gate-no_coverage.stderr
Labels: S-waiting-on-bors

#84872 Wire up tidy dependency checks for cg_clif
  src/tools/tidy/src/deps.rs
Labels: A-cranelift, C-enhancement, S-waiting-on-bors

#84896 Handle incorrect placement of parentheses in trait bounds more gracefully
  compiler/rustc_parse/src/parser/ty.rs
  src/test/ui/parser/trait-object-delimiters.rs
  src/test/ui/parser/trait-object-delimiters.stderr
Labels: S-waiting-on-bors

#84905 CTFE engine: rename copy → copy_intrinsic, move to intrinsics.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/step.rs
Labels: S-waiting-on-bors

#84953 Remove unneeded call to with_default_session_globals in rustdoc highlight
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/highlight/tests.rs
Labels: A-rustdoc, S-waiting-on-bors

#84987 small nits
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_infer/src/infer/mod.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
Labels: S-waiting-on-bors

#85014 Rollup of 11 pull requests
  compiler/rustc_builtin_macros/src/deriving/cmp/eq.rs
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_infer/src/infer/mod.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/step.rs
  compiler/rustc_parse/src/parser/ty.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/collect.rs
  library/core/src/cmp.rs
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
  library/std/src/sys/sgx/abi/mod.rs
  library/std/src/sys/sgx/thread.rs
  library/std/src/thread/local/tests.rs
  src/bootstrap/builder/tests.rs
  src/bootstrap/flags.rs
  src/bootstrap/test.rs
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/highlight/tests.rs
  src/test/debuginfo/should-fail.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.no_cov_func.txt
  src/test/run-make-fulldeps/coverage/no_cov_func.rs
  src/test/ui/cfg/cfg-panic.rs
  src/test/ui/feature-gates/feature-gate-no_coverage.rs
  src/test/ui/feature-gates/feature-gate-no_coverage.stderr
  src/test/ui/intrinsics/intrinsic-alignment.rs
  src/test/ui/issues/issue-70093.rs
  src/test/ui/meta/revision-bad.rs
  src/test/ui/panic-handler/weak-lang-item.rs
  src/test/ui/panic-handler/weak-lang-item.stderr
  src/test/ui/panic-runtime/abort-link-to-unwind-dylib.rs
  src/test/ui/panic-runtime/lto-unwind.rs
  src/test/ui/panic-runtime/transitive-link-a-bunch.rs
  src/test/ui/panic-runtime/want-unwind-got-abort.rs
  src/test/ui/panic-runtime/want-unwind-got-abort2.rs
  src/test/ui/parser/trait-object-delimiters.rs
  src/test/ui/parser/trait-object-delimiters.stderr
  src/test/ui/structs-enums/rec-align-u64.rs
  src/test/ui/suggestions/unsized-function-parameter.fixed
  src/test/ui/suggestions/unsized-function-parameter.rs
  src/test/ui/suggestions/unsized-function-parameter.stderr
  src/test/ui/test-panic-abort-disabled.rs
  src/test/ui/unwind-no-uwtable.rs
  src/test/ui/x86stdcall.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84409 Ensure TLS destructors run before thread joins in SGX
  library/std/src/sys/sgx/abi/mod.rs
  library/std/src/sys/sgx/thread.rs
  library/std/src/thread/local/tests.rs
Labels: S-waiting-on-bors

#84500 Add --run flag to compiletest
  src/bootstrap/builder/tests.rs
  src/bootstrap/flags.rs
  src/bootstrap/test.rs
  src/test/debuginfo/should-fail.rs
  src/test/ui/meta/revision-bad.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors

#84728 Add test for suggestion to borrow unsized function parameters
  src/test/ui/suggestions/unsized-function-parameter.fixed
  src/test/ui/suggestions/unsized-function-parameter.rs
  src/test/ui/suggestions/unsized-function-parameter.stderr
Labels: A-diagnostics, A-suggestion-diagnostics, A-testsuite, S-waiting-on-bors

#84734 Add `needs-unwind` and beginning of support for testing `panic=abort` std to compiletest
  src/test/ui/cfg/cfg-panic.rs
  src/test/ui/intrinsics/intrinsic-alignment.rs
  src/test/ui/issues/issue-70093.rs
  src/test/ui/panic-handler/weak-lang-item.rs
  src/test/ui/panic-handler/weak-lang-item.stderr
  src/test/ui/panic-runtime/abort-link-to-unwind-dylib.rs
  src/test/ui/panic-runtime/lto-unwind.rs
  src/test/ui/panic-runtime/transitive-link-a-bunch.rs
  src/test/ui/panic-runtime/want-unwind-got-abort.rs
  src/test/ui/panic-runtime/want-unwind-got-abort2.rs
  src/test/ui/structs-enums/rec-align-u64.rs
  src/test/ui/test-panic-abort-disabled.rs
  src/test/ui/unwind-no-uwtable.rs
  src/test/ui/x86stdcall.rs
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors

#84755 Allow using `core::` in intra-doc links within core itself
  library/core/src/intrinsics.rs
  library/core/src/lib.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-libs

#84781 Don't check bootstrap artifacts by default
  src/bootstrap/check.rs
Labels: S-waiting-on-bors

#84787 bump deps
  Cargo.lock
Labels: S-waiting-on-bors

#84815 Update coverage docs and command line help
  compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs
  compiler/rustc_session/src/options.rs
  src/doc/unstable-book/src/compiler-flags/instrument-coverage.md
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
  src/doc/unstable-book/src/language-features/no-coverage.md
Labels: S-waiting-on-bors

#84897 Coverage instruments closure bodies in macros (not the macro body)
  compiler/rustc_mir/src/transform/coverage/mod.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.closure.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.closure_macro.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.closure_macro_async.txt
  src/test/run-make-fulldeps/coverage/closure.rs
  src/test/run-make-fulldeps/coverage/closure_macro.rs
  src/test/run-make-fulldeps/coverage/closure_macro_async.rs
Labels: S-waiting-on-bors

#84911 Retry clang+llvm download
  src/ci/scripts/install-clang.sh
Labels: S-waiting-on-bors

#84972 CTFE inbounds-error-messages tweak
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/validity.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.32bit.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.64bit.stderr
  src/test/ui/consts/offset_from_ub.stderr
  src/test/ui/consts/offset_ub.stderr
  src/test/ui/consts/ptr_comparisons.stderr
Labels: S-waiting-on-bors

#84779 Add support for --test-args to cargotest
  src/bootstrap/test.rs
  src/tools/cargotest/main.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#84930 rename LLVM target for RustyHermit
  compiler/rustc_target/src/spec/x86_64_unknown_none_hermitkernel.rs
Labels: S-waiting-on-bors

#84991 rustc: Support Rust-specific features in -Ctarget-feature
  compiler/rustc_codegen_llvm/src/llvm_util.rs
  src/test/ui/target-feature/rust-specific-name-no-warnings.rs
Labels: S-waiting-on-bors

#85029 SGX mutex is movable
  library/std/src/sys/sgx/mutex.rs
Labels: O-SGX, S-waiting-on-bors, T-libs-impl

#85030 Rearrange SGX split module files
  library/std/src/sys/sgx/abi/tls/mod.rs
  library/std/src/sys/sgx/waitqueue/mod.rs
  library/std/src/sys/sgx/waitqueue/spin_mutex.rs
  library/std/src/sys/sgx/waitqueue/unsafe_list.rs
Labels: S-waiting-on-bors

#85033 some further small cleanups
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  compiler/rustc_typeck/src/check/fn_ctxt/checks.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
Labels: S-waiting-on-bors

#85036 Rollup of 9 pull requests
  compiler/rustc_codegen_llvm/src/llvm_util.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_expand/src/config.rs
  compiler/rustc_target/src/spec/illumos_base.rs
  compiler/rustc_target/src/spec/x86_64_unknown_none_hermitkernel.rs
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  compiler/rustc_typeck/src/check/fn_ctxt/checks.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
  library/std/src/sys/sgx/abi/tls/mod.rs
  library/std/src/sys/sgx/mutex.rs
  library/std/src/sys/sgx/waitqueue/mod.rs
  library/std/src/sys/sgx/waitqueue/spin_mutex.rs
  library/std/src/sys/sgx/waitqueue/unsafe_list.rs
  library/std/src/sys/unsupported/args.rs
  library/std/src/sys/wasm/args.rs
  library/std/src/sys/wasm/atomics/condvar.rs
  library/std/src/sys/wasm/atomics/futex.rs
  library/std/src/sys/wasm/atomics/mutex.rs
  library/std/src/sys/wasm/atomics/rwlock.rs
  library/std/src/sys/wasm/atomics/thread.rs
  library/std/src/sys/wasm/mod.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc-ui/invalid-cfg.rs
  src/test/rustdoc-ui/invalid-cfg.stderr
  src/test/rustdoc/doc-cfg.rs
  src/test/ui/target-feature/rust-specific-name-no-warnings.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84442 Unify rustc and rustdoc parsing of `cfg()`
  compiler/rustc_expand/src/config.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc-ui/invalid-cfg.rs
  src/test/rustdoc-ui/invalid-cfg.stderr
  src/test/rustdoc/doc-cfg.rs
Labels: A-attributes, A-rustdoc, F-doc_cfg, S-waiting-on-bors

#84655 Cleanup of `wasm`
  library/std/src/sys/unsupported/args.rs
  library/std/src/sys/wasm/args.rs
  library/std/src/sys/wasm/atomics/condvar.rs
  library/std/src/sys/wasm/atomics/futex.rs
  library/std/src/sys/wasm/atomics/mutex.rs
  library/std/src/sys/wasm/atomics/rwlock.rs
  library/std/src/sys/wasm/atomics/thread.rs
  library/std/src/sys/wasm/mod.rs
Labels: S-waiting-on-bors, T-libs-impl

#84866 linker: Avoid library duplication with `/WHOLEARCHIVE`
  compiler/rustc_codegen_ssa/src/back/linker.rs
Labels: S-waiting-on-bors

#84254 illumos should put libc last in library search order
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_target/src/spec/illumos_base.rs
Labels: S-waiting-on-bors

#83901 Integrate attributes as part of the crate hash
  compiler/rustc_middle/src/hir/map/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#84887 Remove SpanInterner::get
  compiler/rustc_span/src/span_encoding.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#85034 fix null pointer error messages
  compiler/rustc_middle/src/mir/interpret/error.rs
  src/test/ui/consts/const-eval/ub-wide-ptr.32bit.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.64bit.stderr
  src/test/ui/consts/offset_from_ub.stderr
Labels: S-waiting-on-bors

#85038 Don't stop running rustdoc-gui tests at first failure
  src/bootstrap/test.rs
  src/tools/rustdoc-gui/tester.js
Labels: S-waiting-on-bors

#85044 Use `path.exists()` instead of `fs::metadata(path).is_ok()`
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_span/src/source_map.rs
Labels: S-waiting-on-bors

#85052 rustdoc: Link to the docs on namespaces when an unknown disambiguator is found
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/intra-doc/email-address-localhost.stderr
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.stderr
Labels: A-intra-doc-links, A-rustdoc, S-waiting-on-bors

#85057 Rollup of 6 pull requests
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_span/src/source_map.rs
  compiler/rustc_span/src/span_encoding.rs
  src/bootstrap/test.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/intra-doc/email-address-localhost.stderr
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.32bit.stderr
  src/test/ui/consts/const-eval/ub-wide-ptr.64bit.stderr
  src/test/ui/consts/offset_from_ub.stderr
  src/test/ui/structs/struct-fn-in-definition.rs
  src/test/ui/structs/struct-fn-in-definition.stderr
  src/tools/rustdoc-gui/tester.js
Labels: S-waiting-on-bors, merged-by-bors, rollup

#76808 Improve diagnostics for functions in `struct` definitions
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_parse/src/parser/mod.rs
  src/test/ui/structs/struct-fn-in-definition.rs
  src/test/ui/structs/struct-fn-in-definition.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-compiler

#83089 Enable `-W semicolon_in_expressions_from_macros` in bootstrap
  src/bootstrap/bootstrap.py
  src/bootstrap/builder.rs
Labels: S-waiting-on-bors, merged-by-bors

#85097 [stable] 1.52.1 release
  RELEASES.md
  compiler/rustc_query_system/src/query/plumbing.rs
  compiler/rustc_session/src/config.rs
  src/doc/rustc/src/codegen-options/index.md
  src/tools/compiletest/src/runtest.rs
  src/version
Labels: S-waiting-on-bors, merged-by-bors

#85093 Remove `FakeDefId::expect_local()`
  src/librustdoc/clean/types.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/doc_test_lints.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors, merged-by-bors

#83596 Remove dead or useless code from Session
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_errors/src/lib.rs
  compiler/rustc_parse/src/lexer/mod.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_parse/src/parser/stmt.rs
  compiler/rustc_session/src/cgu_reuse_tracker.rs
  compiler/rustc_session/src/session.rs
Labels: A-diagnostics, C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#85065 Avoid predecessors having Drop impls
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir/src/transform/coverage/graph.rs
Labels: S-waiting-on-bors, merged-by-bors

#84507 Add primary marker on codegen unit and generate main wrapper on primary codegen.
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_mir/src/monomorphize/partitioning/mod.rs
  src/test/ui/entry-point/imported_main_from_extern_crate.rs
  src/test/ui/entry-point/imported_main_from_extern_crate.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85104 Fix typo
  compiler/rustc_parse/src/parser/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#85053 Fix duplicate unknown lint errors
  compiler/rustc_lint/src/early.rs
  src/tools/clippy/tests/ui/deprecated.stderr
  src/tools/clippy/tests/ui/deprecated_old.stderr
  src/tools/clippy/tests/ui/rename.stderr
  src/tools/clippy/tests/ui/unknown_clippy_lints.stderr
Labels: A-lint, S-waiting-on-bors, merged-by-bors

#85096 Make unchecked_{add,sub,mul} inherent methods unstably const
  library/core/src/iter/range.rs
  library/core/src/lib.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  src/tools/tidy/src/features.rs
Labels: S-waiting-on-bors

#85118 Use an SVG image for clipboard instead of unicode character
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/render/write_shared.rs
  src/librustdoc/html/static/clipboard.svg
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static_files.rs
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#85148 Fix source code line number display and make it clickable again
  src/librustdoc/html/highlight.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
  src/test/rustdoc-gui/source-code-page.goml
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#85152 Adjust target search algorithm for rustlib path
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_session/src/filesearch.rs
  compiler/rustc_target/src/lib.rs
  compiler/rustc_target/src/spec/mod.rs
Labels: S-waiting-on-bors

#84465 rustdoc: Implement `is_primitive` in terms of `primitive_type()`
  src/librustdoc/clean/types.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors

#84677 Fix `tidy` platform-specific code check
  src/tools/tidy/src/pal.rs
Labels: S-waiting-on-bors, merged-by-bors

#85012 Fix stack overflow when checking for structural recursion
  compiler/rustc_ty_utils/src/representability.rs
  src/test/ui/structs-enums/struct-rec/issue-74224.rs
  src/test/ui/structs-enums/struct-rec/issue-74224.stderr
  src/test/ui/structs-enums/struct-rec/issue-84611.rs
  src/test/ui/structs-enums/struct-rec/issue-84611.stderr
  src/test/ui/structs-enums/struct-rec/mutual-struct-recursion.rs
  src/test/ui/structs-enums/struct-rec/mutual-struct-recursion.stderr
Labels: S-waiting-on-bors, merged-by-bors

#84777 Apply `--cfg parallel_compiler` when documenting
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_query_impl/src/plumbing.rs
  src/bootstrap/compile.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#84783 Allow formatting specific subdirectories
  src/bootstrap/flags.rs
  src/bootstrap/format.rs
  src/bootstrap/lib.rs
  src/bootstrap/test.rs
Labels: A-rustbuild, C-enhancement, S-waiting-on-bors

#80300 Emit errors/warns on some wrong uses of rustdoc attributes
  compiler/rustc_passes/src/check_attr.rs
  library/std/src/os/emscripten/raw.rs
  src/test/rustdoc-ui/doc-attr2.rs
  src/test/rustdoc-ui/doc-attr2.stderr
  src/test/rustdoc-ui/invalid-doc-attr.rs
  src/test/rustdoc-ui/invalid-doc-attr.stderr
  src/test/ui/attributes/doc-attr2.rs
  src/test/ui/attributes/doc-attr2.stderr
  src/test/ui/attributes/invalid-doc-attr.rs
  src/test/ui/attributes/invalid-doc-attr.stderr
Labels: A-attributes, A-diagnostics, A-rustdoc, S-waiting-on-bors, disposition-merge, finished-final-comment-period, merged-by-bors

#85109 remove const_fn feature gate
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/removed.rs
  library/std/src/lib.rs
  src/ci/pgo.sh
  src/doc/unstable-book/src/language-features/const-fn.md
  src/test/ui/feature-gates/feature-gate-const_fn.rs
  src/test/ui/feature-gates/feature-gate-const_fn.stderr
  src/test/ui/feature-gates/feature-gate-rustc_const_unstable.rs
  src/test/ui/feature-gates/feature-gate-rustc_const_unstable.stderr
  src/test/ui/internal/internal-unstable-const.rs
  src/test/ui/issues/issue-54954.rs
  src/test/ui/issues/issue-54954.stderr
  src/test/ui/mismatched_types/const-fn-in-trait.rs
  src/test/ui/mismatched_types/const-fn-in-trait.stderr
  src/test/ui/parser/fn-header-semantic-fail.rs
  src/test/ui/parser/fn-header-semantic-fail.stderr
  src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.rs
  src/test/ui/rfc-2091-track-caller/const-caller-location.rs
  src/test/ui/rustc-args-required-const2.rs
  src/test/ui/stability-attribute/stability-attribute-sanity.rs
  src/test/ui/static/static-drop-scope.rs
  src/test/ui/static/static-drop-scope.stderr
  src/test/ui/thread-local-in-ctfe.rs
  src/test/ui/threads-sendsync/auxiliary/thread-local-extern-static.rs
  src/test/ui/threads-sendsync/issue-43733.rs
  src/test/ui/threads-sendsync/issue-43733.stderr
  src/test/ui/union/union-const-eval-field.rs
  src/test/ui/unsafe/unsafe-unstable-const-fn.rs
  src/test/ui/unsafe/unsafe-unstable-const-fn.stderr
  src/tools/clippy/tests/ui/new_without_default.rs
  src/tools/clippy/tests/ui/new_without_default.stderr
Labels: S-waiting-on-bors, merged-by-bors

#84904 BTree: no longer copy keys and values before dropping them
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/navigate.rs
  library/alloc/src/collections/btree/node.rs
Labels: I-slow, S-waiting-on-bors, T-libs-impl, merged-by-bors

#85018 shrinking the deprecated method span
  compiler/rustc_middle/src/middle/stability.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/method/mod.rs
  compiler/rustc_typeck/src/check/method/probe.rs
  compiler/rustc_typeck/src/check/pat.rs
  src/test/ui/deprecation/deprecation-lint.stderr
  src/test/ui/deprecation/issue-84637-deprecated-associated-function.fixed
  src/test/ui/deprecation/issue-84637-deprecated-associated-function.rs
  src/test/ui/deprecation/issue-84637-deprecated-associated-function.stderr
  src/test/ui/lint/lint-stability-deprecated.stderr
Labels: S-waiting-on-bors

#85192 updated deps
  Cargo.lock
  src/tools/tidy/src/deps.rs
Labels: S-waiting-on-bors, merged-by-bors

#84278 Implement span quoting for proc-macros
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/proc_macro.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_lint/src/internal.rs
  compiler/rustc_lint/src/non_fmt_panic.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_mir/src/transform/coverage/mod.rs
  compiler/rustc_mir/src/transform/coverage/spans.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_session/src/parse.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lib.rs
  library/proc_macro/src/bridge/mod.rs
  library/proc_macro/src/lib.rs
  library/proc_macro/src/quote.rs
  src/test/ui/hygiene/unpretty-debug.stdout
  src/test/ui/macros/auxiliary/proc_macro_sequence.rs
  src/test/ui/macros/same-sequence-span.stderr
  src/test/ui/proc-macro/auxiliary/custom-quote.rs
  src/test/ui/proc-macro/auxiliary/span-from-proc-macro.rs
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
  src/test/ui/proc-macro/nonterminal-token-hygiene.stdout
  src/test/ui/proc-macro/quote-debug.rs
  src/test/ui/proc-macro/quote-debug.stdout
  src/test/ui/proc-macro/span-from-proc-macro.rs
  src/test/ui/proc-macro/span-from-proc-macro.stderr
  src/tools/clippy/clippy_lints/src/misc.rs
  src/tools/clippy/clippy_lints/src/unit_types/unit_cmp.rs
  src/tools/clippy/clippy_utils/src/lib.rs
Labels: A-proc-macros, S-waiting-on-review, merged-by-bors

#83610 rustc_driver cleanup
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_llvm/src/attributes.rs
  compiler/rustc_codegen_llvm/src/lib.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_codegen_ssa/src/back/symbol_export.rs
  compiler/rustc_codegen_ssa/src/back/write.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_incremental/src/persist/load.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_session/src/session.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: A-driver, C-cleanup, S-waiting-on-bors, merged-by-bors

#83813 Fix `--remap-path-prefix` not correctly remapping `rust-src` component paths and unify handling of path mapping with virtualized paths
  compiler/rustc_builtin_macros/src/source_util.rs
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_cranelift/src/debuginfo/line_info.rs
  compiler/rustc_codegen_cranelift/src/debuginfo/mod.rs
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_errors/src/annotate_snippet_emitter_writer.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_errors/src/json.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/hir/map/collector.rs
  compiler/rustc_middle/src/ich/impls_syntax.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_mir/src/borrow_check/region_infer/dump_mir.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/interpret/intrinsics/caller_location.rs
  compiler/rustc_mir/src/transform/coverage/mod.rs
  compiler/rustc_mir/src/util/pretty.rs
  compiler/rustc_mir/src/util/spanview.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_passes/src/liveness.rs
  compiler/rustc_passes/src/region.rs
  compiler/rustc_resolve/src/late/lifetimes.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_save_analysis/src/span_utils.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/source_map.rs
  compiler/rustc_span/src/source_map/tests.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/sources.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs
  src/tools/clippy/clippy_lints/src/macro_use.rs
  src/tools/compiletest/src/runtest.rs
Labels: A-reproducibility, A-rustdoc, S-waiting-on-bors, T-compiler, merged-by-bors

#84730 Add auto traits and clone trait migrations for RFC2229
  compiler/rustc_hir/src/lang_items.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/upvar.rs
  library/core/src/marker.rs
  library/std/src/panic.rs
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.rs
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/issue-78720.rs
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.rs
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.rs
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/no_migrations.rs
  src/test/ui/closures/2229_closure_analysis/migrations/precise.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/precise.rs
  src/test/ui/closures/2229_closure_analysis/migrations/precise.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/precise_no_migrations.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85117 Move global click handlers to per-element ones.
  src/librustdoc/html/layout.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/source-script.js
  src/librustdoc/html/static/themes/ayu.css
  src/librustdoc/html/static/themes/dark.css
  src/librustdoc/html/static/themes/light.css
Labels: S-waiting-on-bors

#85141 Update documentation for SharedContext::maybe_collapsed_doc_value
  src/librustdoc/html/render/context.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors

#85174 Fix border radius for doc code blocks in rustdoc
  src/librustdoc/html/static/rustdoc.css
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#84793 Recover from invalid `struct` item syntax
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/parser/struct-default-values-and-missing-field-separator.fixed
  src/test/ui/parser/struct-default-values-and-missing-field-separator.rs
  src/test/ui/parser/struct-default-values-and-missing-field-separator.stderr
Labels: S-waiting-on-bors

#85218 #[inline(always)] on basic pointer methods
  library/core/src/ptr/mut_ptr.rs
Labels: S-waiting-on-bors, merged-by-bors

#83759 Handle more span edge cases in generics diagnostics
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_lowering/src/path.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_typeck/src/structured_errors/wrong_number_of_generic_args.rs
  src/test/ui/generic-associated-types/gat-trait-path-parenthesised-args.stderr
  src/test/ui/generics/wrong-number-of-args.rs
  src/test/ui/generics/wrong-number-of-args.stderr
  src/test/ui/unboxed-closures/unboxed-closure-sugar-used-on-struct-1.rs
  src/test/ui/unboxed-closures/unboxed-closure-sugar-used-on-struct-1.stderr
  src/test/ui/unboxed-closures/unboxed-closure-sugar-used-on-struct.rs
  src/test/ui/unboxed-closures/unboxed-closure-sugar-used-on-struct.stderr
Labels: S-waiting-on-bors, merged-by-bors

#84732 Add asm!() support for PowerPC
  compiler/rustc_codegen_llvm/src/asm.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/mod.rs
  compiler/rustc_target/src/asm/powerpc.rs
  src/doc/unstable-book/src/library-features/asm.md
  src/test/assembly/asm/powerpc-types.rs
Labels: S-waiting-on-bors, merged-by-bors

#85041 Suggest adding a type parameter for impls
  compiler/rustc_resolve/src/late/diagnostics.rs
  src/test/ui/const-generics/diagnostics.stderr
  src/test/ui/missing/missing-items/missing-type-parameter2.rs
  src/test/ui/missing/missing-items/missing-type-parameter2.stderr
  src/test/ui/traits/issue-75627.stderr
  src/test/ui/traits/issue-78372.stderr
Labels: S-waiting-on-bors, merged-by-bors

#83129 Introduce the beginning of a THIR unsafety checker
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_mir_build/src/check_unsafety.rs
  compiler/rustc_mir_build/src/lib.rs
  compiler/rustc_mir_build/src/thir/mod.rs
  compiler/rustc_mir_build/src/thir/visit.rs
  compiler/rustc_session/src/options.rs
  src/test/ui/async-await/async-unsafe-fn-call-in-safe.mir.stderr
  src/test/ui/async-await/async-unsafe-fn-call-in-safe.rs
  src/test/ui/async-await/async-unsafe-fn-call-in-safe.thir.stderr
  src/test/ui/closures/closure_no_cap_coerce_many_unsafe_0.mir.stderr
  src/test/ui/closures/closure_no_cap_coerce_many_unsafe_0.rs
  src/test/ui/closures/closure_no_cap_coerce_many_unsafe_0.thir.stderr
  src/test/ui/closures/coerce-unsafe-closure-to-unsafe-fn-ptr.mir.stderr
  src/test/ui/closures/coerce-unsafe-closure-to-unsafe-fn-ptr.rs
  src/test/ui/closures/coerce-unsafe-closure-to-unsafe-fn-ptr.thir.stderr
  src/test/ui/consts/const-extern-fn/const-extern-fn-requires-unsafe.mir.stderr
  src/test/ui/consts/const-extern-fn/const-extern-fn-requires-unsafe.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-requires-unsafe.thir.stderr
  src/test/ui/error-codes/E0133.mir.stderr
  src/test/ui/error-codes/E0133.rs
  src/test/ui/error-codes/E0133.thir.stderr
  src/test/ui/feature-gates/feature-gate-const_fn_transmute.mir.stderr
  src/test/ui/feature-gates/feature-gate-const_fn_transmute.rs
  src/test/ui/feature-gates/feature-gate-const_fn_transmute.thir.stderr
  src/test/ui/foreign-unsafe-fn-called.mir.stderr
  src/test/ui/foreign-unsafe-fn-called.rs
  src/test/ui/foreign-unsafe-fn-called.thir.stderr
  src/test/ui/intrinsics/unchecked_math_unsafe.mir.stderr
  src/test/ui/intrinsics/unchecked_math_unsafe.rs
  src/test/ui/intrinsics/unchecked_math_unsafe.thir.stderr
  src/test/ui/issues/issue-28776.mir.stderr
  src/test/ui/issues/issue-28776.rs
  src/test/ui/issues/issue-28776.thir.stderr
  src/test/ui/issues/issue-3080.mir.stderr
  src/test/ui/issues/issue-3080.rs
  src/test/ui/issues/issue-3080.thir.stderr
  src/test/ui/issues/issue-48131.mir.stderr
  src/test/ui/issues/issue-48131.rs
  src/test/ui/issues/issue-48131.thir.stderr
  src/test/ui/issues/issue-5844.mir.stderr
  src/test/ui/issues/issue-5844.rs
  src/test/ui/issues/issue-5844.thir.stderr
  src/test/ui/threads-sendsync/issue-43733.mir.stderr
  src/test/ui/threads-sendsync/issue-43733.rs
  src/test/ui/threads-sendsync/issue-43733.thir.stderr
  src/test/ui/unsafe/unsafe-around-compiler-generated-unsafe.mir.stderr
  src/test/ui/unsafe/unsafe-around-compiler-generated-unsafe.rs
  src/test/ui/unsafe/unsafe-around-compiler-generated-unsafe.thir.stderr
  src/test/ui/unsafe/unsafe-const-fn.mir.stderr
  src/test/ui/unsafe/unsafe-const-fn.rs
  src/test/ui/unsafe/unsafe-const-fn.thir.stderr
  src/test/ui/unsafe/unsafe-fn-called-from-safe.mir.stderr
  src/test/ui/unsafe/unsafe-fn-called-from-safe.rs
  src/test/ui/unsafe/unsafe-fn-called-from-safe.thir.stderr
  src/test/ui/unsafe/unsafe-fn-used-as-value.mir.stderr
  src/test/ui/unsafe/unsafe-fn-used-as-value.rs
  src/test/ui/unsafe/unsafe-fn-used-as-value.thir.stderr
  src/tools/tidy/src/ui_tests.rs
Labels: S-waiting-on-bors, merged-by-bors
