Repository rust-lang/rust, pull requests merged in 2021-07, with the labels that each got.

#86489 Simplify early compilation interface
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_incremental/src/persist/load.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/queries.rs
  src/librustdoc/core.rs
  src/librustdoc/doctest.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#86680 Improve error for missing -Z with debugging option
  compiler/rustc_driver/src/lib.rs
  src/test/ui/invalid-compile-flags/codegen-option-without-group.rs
  src/test/ui/invalid-compile-flags/codegen-option-without-group.stderr
  src/test/ui/invalid-compile-flags/debug-option-without-group.rs
  src/test/ui/invalid-compile-flags/debug-option-without-group.stderr
Labels: S-waiting-on-bors

#86728 Check node kind to avoid ICE in `check_expr_return()`
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/return/issue-86188-return-not-in-fn-body.rs
  src/test/ui/return/issue-86188-return-not-in-fn-body.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rev1.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rev2.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rs
Labels: S-waiting-on-bors

#86740 copy rust-lld as ld in dist
  src/bootstrap/dist.rs
Labels: S-waiting-on-bors

#86746 Fix rustdoc query type filter
  src/librustdoc/html/static/search.js
  src/test/rustdoc-js-std/typed-query.js
Labels: A-rustdoc-js, A-type-based-search, S-waiting-on-bors, T-rustdoc

#86750 Test cross-crate usage of `feature(const_trait_impl)`
  compiler/rustc_metadata/src/rmeta/encoder.rs
  src/test/ui/rfc-2632-const-trait-impl/auxiliary/cross-crate.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-disabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-disabled.stderr
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.stderr
Labels: S-waiting-on-bors

#86755 alloc: `RawVec<T, A>::shrink` can be in `no_global_oom_handling`.
  library/alloc/src/raw_vec.rs
Labels: S-waiting-on-bors

#86757 Rollup of 8 pull requests
  README.md
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0632.md
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_typeck/src/check/expr.rs
  library/alloc/src/raw_vec.rs
  src/bootstrap/dist.rs
  src/librustdoc/html/static/search.js
  src/test/rustdoc-js-std/typed-query.js
  src/test/ui/const-generics/impl-trait-with-const-arguments.full.stderr
  src/test/ui/const-generics/impl-trait-with-const-arguments.min.stderr
  src/test/ui/impl-trait/issues/universal-issue-48703.stderr
  src/test/ui/impl-trait/issues/universal-turbofish-in-method-issue-50950.stderr
  src/test/ui/invalid-compile-flags/codegen-option-without-group.rs
  src/test/ui/invalid-compile-flags/codegen-option-without-group.stderr
  src/test/ui/invalid-compile-flags/debug-option-without-group.rs
  src/test/ui/invalid-compile-flags/debug-option-without-group.stderr
  src/test/ui/return/issue-86188-return-not-in-fn-body.rs
  src/test/ui/return/issue-86188-return-not-in-fn-body.stderr
  src/test/ui/rfc-2632-const-trait-impl/auxiliary/cross-crate.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-disabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-disabled.stderr
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.stderr
  src/test/ui/synthetic-param.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rev1.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rev2.stderr
  src/test/ui/typeck/issue-86721-return-expr-ice.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85504 the foundation owns rust trademarks
  README.md
Labels: S-waiting-on-bors

#85520 Fix typo and improve documentation for E0632
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0632.md
  compiler/rustc_lint/src/builtin.rs
  src/test/ui/const-generics/impl-trait-with-const-arguments.full.stderr
  src/test/ui/const-generics/impl-trait-with-const-arguments.min.stderr
  src/test/ui/impl-trait/issues/universal-issue-48703.stderr
  src/test/ui/impl-trait/issues/universal-turbofish-in-method-issue-50950.stderr
  src/test/ui/synthetic-param.stderr
Labels: S-waiting-on-bors

#86617 Remove unused dependencies from compiler crates
  Cargo.lock
  compiler/rustc_codegen_llvm/Cargo.toml
  compiler/rustc_data_structures/Cargo.toml
  compiler/rustc_driver/Cargo.toml
  compiler/rustc_infer/Cargo.toml
  compiler/rustc_interface/Cargo.toml
  compiler/rustc_lint_defs/Cargo.toml
  compiler/rustc_metadata/Cargo.toml
  compiler/rustc_middle/Cargo.toml
  compiler/rustc_parse/Cargo.toml
  compiler/rustc_passes/Cargo.toml
  compiler/rustc_query_impl/Cargo.toml
  compiler/rustc_session/Cargo.toml
  compiler/rustc_symbol_mangling/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#86190 Fix ICE when `main` is declared in an `extern` block
  compiler/rustc_ast/src/entry.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_passes/src/entry.rs
  src/test/ui/extern/extern-main-issue-86110.rs
  src/test/ui/extern/extern-main-issue-86110.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86762 mailmap: Add my work email address
  .mailmap
Labels: S-waiting-on-bors

#86773 Enable the tests developed with #86594
  src/ci/docker/host-x86_64/x86_64-gnu-tools/Dockerfile
  src/test/rustdoc-gui/label-next-to-symbol.goml
Labels: S-waiting-on-bors

#86774 Rollup of 6 pull requests
  .mailmap
  compiler/rustc_codegen_llvm/src/attributes.rs
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/traits/misc.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/Cargo.toml
  compiler/rustc_target/src/spec/aarch64_apple_darwin.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_macabi.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_sim.rs
  compiler/rustc_target/src/spec/aarch64_apple_tvos.rs
  compiler/rustc_target/src/spec/apple_base.rs
  compiler/rustc_target/src/spec/freebsd_base.rs
  compiler/rustc_target/src/spec/i686_apple_darwin.rs
  compiler/rustc_target/src/spec/i686_pc_windows_gnu.rs
  compiler/rustc_target/src/spec/i686_unknown_linux_musl.rs
  compiler/rustc_target/src/spec/i686_uwp_windows_gnu.rs
  compiler/rustc_target/src/spec/illumos_base.rs
  compiler/rustc_target/src/spec/linux_kernel_base.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/openbsd_base.rs
  compiler/rustc_target/src/spec/thumb_base.rs
  compiler/rustc_target/src/spec/x86_64_apple_darwin.rs
  compiler/rustc_typeck/src/check/coercion.rs
  compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs
  src/ci/docker/host-x86_64/x86_64-gnu-tools/Dockerfile
  src/test/codegen/frame-pointer.rs
  src/test/rustdoc-gui/label-next-to-symbol.goml
  src/test/ui/extern/extern-types-distinct-types.stderr
  src/test/ui/retslot-cast.stderr
  src/test/ui/typeck/issue-84160.rs
  src/test/ui/typeck/issue-84160.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86616 rustc_span: Explicitly handle crates that differ from package names
  compiler/rustc_span/Cargo.toml
Labels: S-waiting-on-bors

#86652 Add support for leaf function frame pointer elimination
  compiler/rustc_codegen_llvm/src/attributes.rs
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/traits/misc.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_target/src/spec/aarch64_apple_darwin.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_macabi.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_sim.rs
  compiler/rustc_target/src/spec/aarch64_apple_tvos.rs
  compiler/rustc_target/src/spec/apple_base.rs
  compiler/rustc_target/src/spec/freebsd_base.rs
  compiler/rustc_target/src/spec/i686_apple_darwin.rs
  compiler/rustc_target/src/spec/i686_pc_windows_gnu.rs
  compiler/rustc_target/src/spec/i686_unknown_linux_musl.rs
  compiler/rustc_target/src/spec/i686_uwp_windows_gnu.rs
  compiler/rustc_target/src/spec/illumos_base.rs
  compiler/rustc_target/src/spec/linux_kernel_base.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/openbsd_base.rs
  compiler/rustc_target/src/spec/thumb_base.rs
  compiler/rustc_target/src/spec/x86_64_apple_darwin.rs
  src/test/codegen/frame-pointer.rs
Labels: S-waiting-on-bors

#86666 Fix misleading "impl Trait" error
  compiler/rustc_typeck/src/check/coercion.rs
  compiler/rustc_typeck/src/check/fn_ctxt/suggestions.rs
  src/test/ui/extern/extern-types-distinct-types.stderr
  src/test/ui/retslot-cast.stderr
  src/test/ui/typeck/issue-84160.rs
  src/test/ui/typeck/issue-84160.stderr
Labels: S-waiting-on-bors

#86304 rustc_mir: calc hex number length without string allocation
  compiler/rustc_mir/src/util/pretty.rs
Labels: S-waiting-on-bors, merged-by-bors

#86749 Rename all_crate_nums query to crates and remove useless wrapper
  compiler/rustc_codegen_ssa/src/back/symbol_export.rs
  compiler/rustc_codegen_ssa/src/back/write.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_metadata/src/dependency_format.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_middle/src/ty/trait_def.rs
  compiler/rustc_passes/src/diagnostic_items.rs
  compiler/rustc_passes/src/lang_items.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_passes/src/weak_lang_items.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/tools/clippy/clippy_utils/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#86768 Add myself to mailmap
  .mailmap
Labels: S-waiting-on-bors

#86775 Test for const trait impls behind feature gates
  src/test/ui/rfc-2632-const-trait-impl/auxiliary/staged-api.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.gated.stderr
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.stock.stderr
  src/test/ui/rfc-2632-const-trait-impl/staged-api.rs
  src/test/ui/rfc-2632-const-trait-impl/staged-api.staged.stderr
  src/test/ui/rfc-2632-const-trait-impl/staged-api.stock.stderr
Labels: S-waiting-on-bors

#86779 Allow anyone to add or remove any label starting with perf-
  triagebot.toml
Labels: S-waiting-on-bors

#86783 Move Mutex::unlock to T: ?Sized
  library/std/src/sync/mutex.rs
Labels: S-waiting-on-bors

#86785 proc_macro/bridge: Remove dead code Slice type
  library/proc_macro/src/bridge/buffer.rs
Labels: S-waiting-on-bors

#86791 Rollup of 7 pull requests
  .mailmap
  compiler/rustc_error_codes/src/error_codes/E0094.md
  compiler/rustc_typeck/src/check/intrinsic.rs
  compiler/rustc_typeck/src/errors.rs
  library/proc_macro/src/bridge/buffer.rs
  library/std/src/sync/mutex.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/search.js
  src/test/rustdoc-js-std/alias-4.js
  src/test/rustdoc-js/generics-trait.js
  src/test/rustdoc-js/generics-trait.rs
  src/test/rustdoc-js/generics.js
  src/test/rustdoc-js/generics.rs
  src/test/ui/rfc-2632-const-trait-impl/auxiliary/staged-api.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate-feature-enabled.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.gated.stderr
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.rs
  src/test/ui/rfc-2632-const-trait-impl/cross-crate.stock.stderr
  src/test/ui/rfc-2632-const-trait-impl/staged-api.rs
  src/test/ui/rfc-2632-const-trait-impl/staged-api.staged.stderr
  src/test/ui/rfc-2632-const-trait-impl/staged-api.stock.stderr
  src/test/ui/simd-intrinsic/issue-85855.rs
  src/test/ui/simd-intrinsic/issue-85855.stderr
  triagebot.toml
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86148 Check the number of generic lifetime and const parameters of intrinsics
  compiler/rustc_error_codes/src/error_codes/E0094.md
  compiler/rustc_typeck/src/check/intrinsic.rs
  compiler/rustc_typeck/src/errors.rs
  src/test/ui/simd-intrinsic/issue-85855.rs
  src/test/ui/simd-intrinsic/issue-85855.stderr
Labels: S-waiting-on-bors

#86659 fix(rustdoc): generics search
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/search.js
  src/test/rustdoc-js-std/alias-4.js
  src/test/rustdoc-js/generics-trait.js
  src/test/rustdoc-js/generics-trait.rs
  src/test/rustdoc-js/generics.js
  src/test/rustdoc-js/generics.rs
Labels: A-rustdoc-js, S-waiting-on-bors, T-rustdoc

#86777 Include terminators in instance size estimate
  compiler/rustc_ty_utils/src/ty.rs
Labels: S-waiting-on-bors, merged-by-bors

#80182 Implement printing of stack traces on LLVM segfaults and aborts
  compiler/rustc_driver/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#85746 Redefine `ErrorKind::Other` and stop using it in std.
  library/std/src/fs.rs
  library/std/src/fs/tests.rs
  library/std/src/io/error.rs
  library/std/src/io/mod.rs
  library/std/src/net/tcp/tests.rs
  library/std/src/os/wasi/fs.rs
  library/std/src/process.rs
  library/std/src/sys/hermit/mod.rs
  library/std/src/sys/hermit/net.rs
  library/std/src/sys/hermit/stdio.rs
  library/std/src/sys/hermit/thread.rs
  library/std/src/sys/sgx/mod.rs
  library/std/src/sys/sgx/net.rs
  library/std/src/sys/sgx/stdio.rs
  library/std/src/sys/unix/fs.rs
  library/std/src/sys/unix/mod.rs
  library/std/src/sys/unix/net.rs
  library/std/src/sys/unix/os.rs
  library/std/src/sys/unsupported/common.rs
  library/std/src/sys/wasi/fs.rs
  library/std/src/sys/wasi/mod.rs
  library/std/src/sys/windows/fs.rs
  library/std/src/sys/windows/mod.rs
  src/test/ui/write-fmt-errors.rs
Labels: A-io, S-waiting-on-bors, T-libs-api, disposition-merge, finished-final-comment-period, merged-by-bors, needs-fcp, relnotes

#86714 Add linked list cursor end methods
  library/alloc/src/collections/linked_list.rs
  library/alloc/src/collections/linked_list/tests.rs
Labels: S-waiting-on-bors

#86737 Document rustfmt on nightly-rustc
  src/bootstrap/builder.rs
  src/bootstrap/doc.rs
  src/tools/rustfmt/src/lib.rs
Labels: A-contributor-roadblock, A-rustbuild, A-rustfmt, S-waiting-on-bors

#86776 Skip layout query when computing integer type size during mangling
  compiler/rustc_symbol_mangling/src/v0.rs
Labels: S-waiting-on-bors

#86797 Stabilize `Bound::cloned()`
  library/core/src/ops/range.rs
  library/core/tests/lib.rs
  library/proc_macro/src/lib.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#86806 Rollup of 5 pull requests
  compiler/rustc_symbol_mangling/src/v0.rs
  library/alloc/src/collections/linked_list.rs
  library/alloc/src/collections/linked_list/tests.rs
  library/core/src/ops/range.rs
  library/core/tests/lib.rs
  library/proc_macro/src/lib.rs
  src/bootstrap/builder.rs
  src/bootstrap/doc.rs
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_intra_doc_links/early.rs
  src/librustdoc/passes/mod.rs
  src/test/rustdoc-ui/auxiliary/panic-item.rs
  src/test/rustdoc-ui/unused-extern-crate.rs
  src/test/rustdoc/auxiliary/issue-66159-1.rs
  src/test/rustdoc/issue-66159.rs
  src/tools/rustfmt/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85749 Revert "Don't load all extern crates unconditionally"
  src/librustdoc/core.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_intra_doc_links/early.rs
  src/librustdoc/passes/mod.rs
  src/test/rustdoc-ui/auxiliary/panic-item.rs
  src/test/rustdoc-ui/unused-extern-crate.rs
  src/test/rustdoc/auxiliary/issue-66159-1.rs
  src/test/rustdoc/issue-66159.rs
Labels: A-metadata, S-waiting-on-bors, T-rustdoc, beta-accepted, beta-nominated

#85269 Improve debug symbol names to avoid ambiguity and work better with MSVC's debugger
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/debuginfo/mod.rs
  compiler/rustc_codegen_llvm/src/debuginfo/namespace.rs
  compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs
  src/etc/natvis/intrinsic.natvis
  src/etc/natvis/libstd.natvis
  src/test/codegen/async-fn-debug-msvc.rs
  src/test/codegen/async-fn-debug.rs
  src/test/codegen/fn-impl-trait-self.rs
  src/test/codegen/generator-debug-msvc.rs
  src/test/codegen/generator-debug.rs
  src/test/debuginfo/basic-types.rs
  src/test/debuginfo/function-names.rs
  src/test/debuginfo/generator-objects.rs
  src/test/debuginfo/generic-struct.rs
  src/test/debuginfo/issue-57822.rs
  src/test/debuginfo/msvc-pretty-enums.rs
  src/test/debuginfo/mutex.rs
  src/test/debuginfo/pretty-std-collections-hash.rs
  src/test/debuginfo/pretty-std.rs
  src/test/debuginfo/rc_arc.rs
  src/test/debuginfo/result-types.rs
  src/test/debuginfo/simple-tuple.rs
  src/test/debuginfo/thread.rs
  src/test/debuginfo/tuple-in-tuple.rs
  src/test/debuginfo/type-names.cdb.js
  src/test/debuginfo/type-names.rs
  src/test/debuginfo/var-captured-in-nested-closure.rs
  src/tools/compiletest/src/runtest.rs
  src/tools/tidy/src/style.rs
Labels: A-debuginfo, S-waiting-on-bors, T-compiler, merged-by-bors

#86796 Add a regression test for issue-70703
  src/test/ui/inference/issue-70703.rs
Labels: S-waiting-on-bors

#86803 Remove & from Command::args calls in documentation
  library/std/src/process.rs
Labels: S-waiting-on-bors

#86807 Fix double import in wasm thread
  library/std/src/sys/wasm/atomics/thread.rs
Labels: S-waiting-on-bors

#86813 Add a help message to `unused_doc_comments` lint
  compiler/rustc_lint/src/builtin.rs
  src/test/ui/unused/unused-doc-comments-edge-cases.rs
  src/test/ui/unused/unused-doc-comments-edge-cases.stderr
  src/test/ui/unused/useless-comment.stderr
Labels: S-waiting-on-bors

#86817 Rollup of 7 pull requests
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_session/src/parse.rs
  compiler/rustc_typeck/src/check/intrinsic.rs
  library/core/src/intrinsics.rs
  library/proc_macro/src/bridge/mod.rs
  library/proc_macro/src/lib.rs
  library/std/src/process.rs
  library/std/src/sys/wasm/atomics/thread.rs
  library/std/src/sys_common/bytestring.rs
  library/std/src/sys_common/bytestring/tests.rs
  library/std/src/sys_common/mod.rs
  library/std/src/sys_common/os_str_bytes.rs
  library/std/src/sys_common/os_str_bytes/tests.rs
  src/test/run-make/track-path-dep-info/Makefile
  src/test/run-make/track-path-dep-info/emojis.txt
  src/test/run-make/track-path-dep-info/macro_def.rs
  src/test/run-make/track-path-dep-info/macro_use.rs
  src/test/ui/inference/issue-70703.rs
  src/test/ui/unused/unused-doc-comments-edge-cases.rs
  src/test/ui/unused/unused-doc-comments-edge-cases.stderr
  src/test/ui/unused/useless-comment.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86308 Docs: clarify that certain intrinsics are not unsafe
  compiler/rustc_typeck/src/check/intrinsic.rs
  library/core/src/intrinsics.rs
Labels: S-waiting-on-bors

#84029 add `track_path::path` fn for usage in `proc_macro`s
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_session/src/parse.rs
  library/proc_macro/src/bridge/mod.rs
  library/proc_macro/src/lib.rs
  src/test/run-make/track-path-dep-info/Makefile
  src/test/run-make/track-path-dep-info/emojis.txt
  src/test/run-make/track-path-dep-info/macro_def.rs
  src/test/run-make/track-path-dep-info/macro_use.rs
Labels: S-waiting-on-bors

#85001 Merge `sys_common::bytestring` back into `os_str_bytes`
  library/std/src/sys_common/bytestring.rs
  library/std/src/sys_common/bytestring/tests.rs
  library/std/src/sys_common/mod.rs
  library/std/src/sys_common/os_str_bytes.rs
  library/std/src/sys_common/os_str_bytes/tests.rs
Labels: S-waiting-on-bors, T-libs

#86821 [beta] backports
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_parse/src/parser/expr.rs
  src/librustdoc/core.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_intra_doc_links/early.rs
  src/librustdoc/passes/mod.rs
  src/test/pretty/ast-stmt-expr-attr.rs
  src/test/pretty/stmt_expr_attributes.rs
  src/test/rustdoc-ui/auxiliary/panic-item.rs
  src/test/rustdoc-ui/unused-extern-crate.rs
  src/test/rustdoc/auxiliary/issue-66159-1.rs
  src/test/rustdoc/issue-66159.rs
  src/test/ui/parser/stmt_expr_attrs_placement.rs
  src/test/ui/parser/stmt_expr_attrs_placement.stderr
  src/tools/rustfmt/src/modules.rs
  src/tools/rustfmt/src/test/mod.rs
  src/tools/rustfmt/src/test/mod_resolver.rs
  src/tools/rustfmt/tests/mod-resolver/issue-4874/bar/baz.rs
  src/tools/rustfmt/tests/mod-resolver/issue-4874/foo.rs
  src/tools/rustfmt/tests/mod-resolver/issue-4874/foo/qux.rs
  src/tools/rustfmt/tests/mod-resolver/issue-4874/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#86795 Fix const-generics ICE related to binding
  compiler/rustc_middle/src/ty/fold.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_middle/src/ty/util.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_ty_utils/src/instance.rs
  compiler/rustc_ty_utils/src/lib.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/compare_method.rs
  compiler/rustc_typeck/src/check/method/confirm.rs
  compiler/rustc_typeck/src/check/method/mod.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
  compiler/rustc_typeck/src/collect.rs
  src/test/ui/const-generics/issues/issue-83765.rs
  src/test/ui/const-generics/issues/issue-83765.stderr
  src/test/ui/const-generics/issues/issue-85848.rs
  src/test/ui/const-generics/issues/issue-85848.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86571 deny using default function in impl const Trait
  compiler/rustc_passes/src/check_const.rs
  compiler/rustc_passes/src/lib.rs
  src/test/ui/consts/const-float-classify.rs
  src/test/ui/rfc-2632-const-trait-impl/call-const-trait-method-pass.rs
  src/test/ui/rfc-2632-const-trait-impl/call-generic-method-chain.rs
  src/test/ui/rfc-2632-const-trait-impl/call-generic-method-dup-bound.rs
  src/test/ui/rfc-2632-const-trait-impl/call-generic-method-pass.rs
  src/test/ui/rfc-2632-const-trait-impl/impl-with-default-fn.rs
  src/test/ui/rfc-2632-const-trait-impl/impl-with-default-fn.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86799 add owned locked stdio handles
  library/std/src/io/mod.rs
  library/std/src/io/stdio.rs
  library/std/src/io/stdio/tests.rs
Labels: A-io, C-enhancement, D-newcomer-roadblock, S-waiting-on-bors, T-libs-api, merged-by-bors

#86810 alloc: `no_global_oom_handling`: disable `new()`s, `pin()`s, etc.
  library/alloc/src/rc.rs
  library/alloc/src/sync.rs
Labels: S-waiting-on-bors, merged-by-bors

#86778 Avoid byte to char position conversions in `is_multiline`
  compiler/rustc_span/src/source_map.rs
Labels: S-waiting-on-bors, merged-by-bors

#85090 Return `EvaluatedToOk` when type in outlives predicate is global
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  src/test/ui/traits/issue-83538-tainted-cache-after-cycle.rs
  src/test/ui/traits/issue-83538-tainted-cache-after-cycle.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85270 When using `process::Command` on Windows, environment variable names must be case-preserving but case-insensitive
  library/std/src/sys/windows/c.rs
  library/std/src/sys/windows/process.rs
  library/std/src/sys/windows/process/tests.rs
Labels: O-windows, S-waiting-on-bors, T-libs-api, disposition-merge, finished-final-comment-period, merged-by-bors, relnotes

#86833 Remove the deprecated `core::raw` and `std::raw` module.
  library/core/src/lib.rs
  library/core/src/raw.rs
  library/core/tests/lib.rs
  library/core/tests/mem.rs
  library/panic_unwind/src/lib.rs
  library/std/src/lib.rs
  src/test/ui/cast/fat-ptr-cast-rpass.rs
  src/test/ui/unsized/unsized3-rpass.rs
Labels: S-waiting-on-bors, T-libs, T-libs-api, merged-by-bors

#86849 Warn when `rustdoc::` group is omitted from lint names
  compiler/rustc_lint/src/context.rs
  src/librustdoc/lint.rs
  src/test/rustdoc-ui/renamed-lint-still-applies.rs
  src/test/rustdoc-ui/renamed-lint-still-applies.stderr
  src/test/rustdoc-ui/unknown-renamed-lints.rs
  src/test/rustdoc-ui/unknown-renamed-lints.stderr
Labels: A-lint, S-waiting-on-bors, T-rustdoc, merged-by-bors

#86255 Support allocation failures when interpreting MIR
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_middle/src/mir/interpret/allocation.rs
  compiler/rustc_middle/src/mir/interpret/error.rs
  compiler/rustc_middle/src/ty/vtable.rs
  compiler/rustc_mir/src/const_eval/eval_queries.rs
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/intern.rs
  compiler/rustc_mir/src/interpret/intrinsics/caller_location.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/memory.rs
  compiler/rustc_mir/src/interpret/place.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  src/test/ui/consts/large_const_alloc.rs
  src/test/ui/consts/large_const_alloc.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86213 Stabilize `str::from_utf8_unchecked` as `const`
  library/core/src/str/converts.rs
Labels: A-const-fn, A-str, C-feature-accepted, S-waiting-on-bors, T-libs-api, merged-by-bors, relnotes

#86048 core: add unstable no_fp_fmt_parse to disable float formatting code
  library/core/src/fmt/float.rs
  library/core/src/fmt/mod.rs
  library/core/src/fmt/nofloat.rs
  library/core/src/fmt/num.rs
  library/core/src/num/flt2dec/mod.rs
  library/core/src/num/fmt.rs
  library/core/src/num/mod.rs
  library/core/tests/lib.rs
  library/core/tests/num/flt2dec/mod.rs
  src/test/run-make-fulldeps/core-no-fp-fmt-parse/Makefile
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#86866 Hack: Ignore inference variables in certain queries
  compiler/rustc_infer/src/infer/canonical/canonicalizer.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/normalize_erasing_regions.rs
  compiler/rustc_middle/src/ty/util.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_typeck/src/check/cast.rs
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/async-await/issue-84841.rs
  src/test/ui/async-await/issue-84841.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/issue-86753.rs
  src/tools/clippy/clippy_utils/src/ty.rs
Labels: S-waiting-on-bors, merged-by-bors

#86598 Add examples to the various methods of `core::task::Poll`
  library/core/src/task/poll.rs
Labels: A-async-await, S-waiting-on-bors, merged-by-bors

#86623 Add check to ensure error code explanations are not removed anymore even if not emitted
  src/ci/docker/host-x86_64/mingw-check/Dockerfile
  src/ci/docker/host-x86_64/mingw-check/validate-error-codes.sh
  src/ci/docker/run.sh
Labels: S-waiting-on-bors, T-infra

#86856 Make x.py less verbose on failures
  src/bootstrap/bootstrap.py
  src/bootstrap/compile.rs
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#86858 Stabilize `string_drain_as_str`
  library/alloc/src/string.rs
Labels: S-waiting-on-bors, T-libs, relnotes

#86859 Add a regression test for issue-69323
  src/test/ui/type-alias-impl-trait/issue-69323.full.stderr
  src/test/ui/type-alias-impl-trait/issue-69323.rs
Labels: S-waiting-on-bors

#86862 re-export SwitchIntEdgeEffects
  compiler/rustc_mir/src/dataflow/mod.rs
Labels: S-waiting-on-bors

#86864 Add missing code example for Write::write_vectored
  library/std/src/io/mod.rs
Labels: A-docs, S-waiting-on-bors

#86874 Bump deps
  Cargo.lock
  src/tools/tidy/Cargo.toml
Labels: S-waiting-on-bors

#86875 Rollup of 8 pull requests
  Cargo.lock
  compiler/rustc_error_codes/src/error_codes/E0716.md
  compiler/rustc_mir/src/dataflow/mod.rs
  library/alloc/src/string.rs
  library/std/src/io/mod.rs
  src/bootstrap/bootstrap.py
  src/bootstrap/compile.rs
  src/ci/docker/host-x86_64/mingw-check/Dockerfile
  src/ci/docker/host-x86_64/mingw-check/validate-error-codes.sh
  src/ci/docker/run.sh
  src/test/ui/type-alias-impl-trait/issue-69323.full.stderr
  src/test/ui/type-alias-impl-trait/issue-69323.rs
  src/tools/tidy/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86477 E0716: clarify that equivalent code example is erroneous
  compiler/rustc_error_codes/src/error_codes/E0716.md
Labels: A-diagnostics, D-newcomer-roadblock, S-waiting-on-bors, T-compiler

#86867 Convert `debug_assert!` to `assert!` in `Binder::dummy`
  compiler/rustc_middle/src/ty/sty.rs
Labels: S-waiting-on-bors, merged-by-bors

#86282 Pretty-print macro matchers instead of using source code
  compiler/rustc_ast_pretty/src/pprust/state.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/utils.rs
  src/test/pretty/cast-lt.pp
  src/test/pretty/delimited-token-groups.rs
  src/test/pretty/macro.rs
  src/test/pretty/macro_rules.rs
  src/test/rustdoc/decl_macro.rs
  src/test/rustdoc/macro_rules-matchers.rs
  src/test/rustdoc/macros.rs
  src/test/ui/hygiene/unpretty-debug.stdout
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
  src/test/ui/proc-macro/nonterminal-token-hygiene.stdout
Labels: A-macros, S-waiting-on-bors, T-rustdoc, merged-by-bors

#86663 Use rustdoc.css for error index
  src/bootstrap/doc.rs
  src/doc/rust.css
  src/librustdoc/html/static/themes/light.css
  src/tools/error_index_generator/main.rs
Labels: S-waiting-on-bors, T-infra, T-rustdoc, merged-by-bors

#84560 Inline Iterator as IntoIterator.
  library/core/src/iter/traits/collect.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#86674 Query-ify global limit attribute handling
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_middle/src/ich/hcx.rs
  compiler/rustc_middle/src/middle/limits.rs
  compiler/rustc_middle/src/middle/mod.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_middle/src/ty/util.rs
  compiler/rustc_mir/src/const_eval/eval_queries.rs
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_mir/src/monomorphize/collector.rs
  compiler/rustc_mir/src/transform/inline/cycle.rs
  compiler/rustc_session/src/lib.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_trait_selection/src/autoderef.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_trait_selection/src/traits/project.rs
  compiler/rustc_trait_selection/src/traits/query/normalize.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_traits/src/dropck_outlives.rs
  compiler/rustc_ty_utils/src/needs_drop.rs
  src/test/ui/recursion_limit/empty.rs
  src/test/ui/recursion_limit/empty.stderr
  src/test/ui/recursion_limit/invalid_digit.rs
  src/test/ui/recursion_limit/invalid_digit.stderr
  src/test/ui/recursion_limit/overflow.rs
  src/test/ui/recursion_limit/overflow.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86794 Stabilize `Seek::rewind()`
  library/std/src/io/mod.rs
  library/std/src/io/tests.rs
Labels: S-waiting-on-bors, T-libs-api, relnotes

#86852 Remove some doc aliases
  library/alloc/src/boxed.rs
  library/alloc/src/collections/binary_heap.rs
  library/alloc/src/collections/btree/map.rs
  library/alloc/src/collections/btree/set.rs
  library/alloc/src/collections/linked_list.rs
  library/alloc/src/collections/vec_deque/mod.rs
  library/alloc/src/macros.rs
  library/alloc/src/string.rs
  library/alloc/src/vec/mod.rs
  library/core/src/iter/traits/exact_size.rs
  library/core/src/slice/mod.rs
  library/core/src/str/mod.rs
  library/std/src/collections/hash/map.rs
  library/std/src/collections/hash/set.rs
  library/std/src/ffi/os_str.rs
  library/std/src/fs.rs
Labels: S-waiting-on-bors

#86886 Remove `impl Clean for {Ident, Symbol}`
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#86685 double-check mutability inside Allocation
  compiler/rustc_middle/src/mir/interpret/allocation.rs
Labels: S-waiting-on-bors

#85377 aborts: Clarify documentation and comments
  library/core/src/intrinsics.rs
  library/std/src/process.rs
  library/std/src/sys/unix/mod.rs
Labels: S-waiting-on-bors

#83581 Add std::os::unix::fs::DirEntryExt2::file_name_ref(&self) -> &OsStr
  library/std/src/os/unix/fs.rs
  library/std/src/sys/unix/fs.rs
Labels: S-waiting-on-bors

#86877 Remove LibSource
  compiler/rustc_codegen_cranelift/src/driver/jit.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/rpath.rs
  compiler/rustc_codegen_ssa/src/back/rpath/tests.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_metadata/src/dependency_format.rs
  compiler/rustc_middle/src/middle/cstore.rs
Labels: S-waiting-on-bors, merged-by-bors

#82985 Cleanup the computation of lint levels
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_middle/src/lint.rs
Labels: S-waiting-on-bors, merged-by-bors

#86644 rustdoc: Replace `FakeDefId` with new `ItemId` type
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/core.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/librustdoc/passes/doc_test_lints.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/passes/strip_private.rs
  src/librustdoc/passes/stripper.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#86694 Store macro parent module in ExpnData.
  compiler/rustc_expand/src/base.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_span/src/hygiene.rs
Labels: S-waiting-on-bors, merged-by-bors

#86572 Force warnings even when can_emit_warnings == false
  compiler/rustc_errors/src/annotate_snippet_emitter_writer.rs
  compiler/rustc_errors/src/diagnostic.rs
  compiler/rustc_errors/src/json.rs
  compiler/rustc_errors/src/lib.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_session/src/session.rs
  src/test/ui/lint/force-warn/force-warn-cap-lints-warn.rs
  src/test/ui/lint/force-warn/force-warn-cap-lints-warn.stderr
  src/test/ui/lint/force-warn/force-warns-cap-lints-allow.rs
  src/test/ui/lint/force-warn/force-warns-cap-lints-allow.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86636 [msvc] Consistently show active variant and fix visualization for single variant enums
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs
  src/etc/natvis/intrinsic.natvis
  src/etc/natvis/libcore.natvis
  src/test/codegen/async-fn-debug-msvc.rs
  src/test/codegen/generator-debug-msvc.rs
  src/test/debuginfo/msvc-pretty-enums.rs
  src/test/debuginfo/pretty-std.rs
Labels: A-debuginfo, O-windows-msvc, S-waiting-on-bors, merged-by-bors

#86911 Refactor linker code
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/driver/jit.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_llvm/src/lib.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_codegen_ssa/src/back/write.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#86901 Make type_implements_trait not a query
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_trait_selection/src/infer.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_trait_selection/src/traits/mod.rs
  compiler/rustc_typeck/src/check/cast.rs
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/incremental/issue-86753.rs
  src/test/ui/issues/issue-73886.stderr
  src/tools/clippy/clippy_utils/src/ty.rs
Labels: S-waiting-on-bors, merged-by-bors

#86906 Replace deprecated compare_and_swap and fix typo in core::sync::atomic::{fence, compiler_fence} docs
  library/core/src/sync/atomic.rs
Labels: S-waiting-on-bors

#86907 Migrate `cpu-usage-over-time.py` to Python 3
  src/ci/cpu-usage-over-time.py
  src/ci/scripts/collect-cpu-stats.sh
Labels: S-waiting-on-bors

#86916 rewrote documentation for thread::yield_now()
  library/std/src/thread/mod.rs
Labels: S-waiting-on-bors

#86819 Clean up rustdoc IDs
  src/librustdoc/html/markdown.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#86880 Test ManuallyDrop::clone_from.
  library/core/tests/manually_drop.rs
Labels: S-waiting-on-bors, T-libs

#80918 Add Integer::log variants
  library/core/src/num/int_macros.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/lib.rs
  library/core/tests/num/int_log.rs
  library/core/tests/num/mod.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs-api

#86105 Refactor the generation of the metadata for linking
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_middle/src/middle/cstore.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#86812 Recover from `&dyn mut ...` parse errors
  compiler/rustc_parse/src/parser/ty.rs
  src/test/ui/parser/recover-ref-dyn-mut.rs
  src/test/ui/parser/recover-ref-dyn-mut.stderr
Labels: S-waiting-on-bors

#86917 Add doc comment for `impl From<LayoutError> for TryReserveError`
  library/alloc/src/collections/mod.rs
Labels: S-waiting-on-bors

#86925 Add self to mailmap
  .mailmap
Labels: S-waiting-on-bors

#86927 Sync rustc_codegen_cranelift
  compiler/rustc_codegen_cranelift/.cirrus.yml
  compiler/rustc_codegen_cranelift/.github/workflows/main.yml
  compiler/rustc_codegen_cranelift/.github/workflows/rustc.yml
  compiler/rustc_codegen_cranelift/.gitignore
  compiler/rustc_codegen_cranelift/.vscode/settings.json
  compiler/rustc_codegen_cranelift/Cargo.lock
  compiler/rustc_codegen_cranelift/Cargo.toml
  compiler/rustc_codegen_cranelift/Readme.md
  compiler/rustc_codegen_cranelift/build.sh
  compiler/rustc_codegen_cranelift/build_sysroot/Cargo.lock
  compiler/rustc_codegen_cranelift/build_sysroot/build_sysroot.sh
  compiler/rustc_codegen_cranelift/build_sysroot/prepare_sysroot_src.sh
  compiler/rustc_codegen_cranelift/build_system/build_backend.rs
  compiler/rustc_codegen_cranelift/build_system/build_sysroot.rs
  compiler/rustc_codegen_cranelift/build_system/config.rs
  compiler/rustc_codegen_cranelift/build_system/prepare.rs
  compiler/rustc_codegen_cranelift/build_system/rustc_info.rs
  compiler/rustc_codegen_cranelift/build_system/utils.rs
  compiler/rustc_codegen_cranelift/clean_all.sh
  compiler/rustc_codegen_cranelift/config.txt
  compiler/rustc_codegen_cranelift/docs/usage.md
  compiler/rustc_codegen_cranelift/example/mini_core_hello_world.rs
  compiler/rustc_codegen_cranelift/example/std_example.rs
  compiler/rustc_codegen_cranelift/patches/0001-compiler-builtins-Disable-128bit-atomic-operations.patch
  compiler/rustc_codegen_cranelift/patches/0001-rand-Enable-c2-chacha-simd-feature.patch
  compiler/rustc_codegen_cranelift/patches/0002-rand-Disable-failing-test.patch
  compiler/rustc_codegen_cranelift/patches/0022-sysroot-Disable-not-compiling-tests.patch
  compiler/rustc_codegen_cranelift/patches/0023-sysroot-Ignore-failing-tests.patch
  compiler/rustc_codegen_cranelift/patches/0027-sysroot-128bit-atomic-operations.patch
  compiler/rustc_codegen_cranelift/prepare.sh
  compiler/rustc_codegen_cranelift/rust-toolchain
  compiler/rustc_codegen_cranelift/scripts/cargo.rs
  compiler/rustc_codegen_cranelift/scripts/cargo.sh
  compiler/rustc_codegen_cranelift/scripts/config.sh
  compiler/rustc_codegen_cranelift/scripts/ext_config.sh
  compiler/rustc_codegen_cranelift/scripts/filter_profile.rs
  compiler/rustc_codegen_cranelift/scripts/rustup.sh
  compiler/rustc_codegen_cranelift/scripts/setup_rust_fork.sh
  compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh
  compiler/rustc_codegen_cranelift/scripts/tests.sh
  compiler/rustc_codegen_cranelift/src/base.rs
  compiler/rustc_codegen_cranelift/src/bin/cg_clif.rs
  compiler/rustc_codegen_cranelift/src/common.rs
  compiler/rustc_codegen_cranelift/src/constant.rs
  compiler/rustc_codegen_cranelift/src/debuginfo/line_info.rs
  compiler/rustc_codegen_cranelift/src/debuginfo/mod.rs
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/driver/jit.rs
  compiler/rustc_codegen_cranelift/src/intrinsics/llvm.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/optimize/mod.rs
  compiler/rustc_codegen_cranelift/src/pretty_clif.rs
  compiler/rustc_codegen_cranelift/src/vtable.rs
  compiler/rustc_codegen_cranelift/test.sh
  compiler/rustc_codegen_cranelift/y.rs
  src/tools/tidy/src/deps.rs
Labels: A-codegen, A-cranelift, S-waiting-on-bors, T-compiler

#86932 Fix ICE when misplaced visibility cannot be properly parsed
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/parser/issue-86895.rs
  src/test/ui/parser/issue-86895.stderr
Labels: S-waiting-on-bors

#86933 Clean up rustdoc static files
  src/bootstrap/test.rs
  src/ci/docker/host-x86_64/mingw-check/Dockerfile
  src/librustdoc/config.rs
  src/librustdoc/html/static/css/normalize.css
  src/librustdoc/html/static/css/noscript.css
  src/librustdoc/html/static/css/rustdoc.css
  src/librustdoc/html/static/css/settings.css
  src/librustdoc/html/static/css/themes/ayu.css
  src/librustdoc/html/static/css/themes/dark.css
  src/librustdoc/html/static/css/themes/light.css
  src/librustdoc/html/static/fonts/FiraSans-LICENSE.txt
  src/librustdoc/html/static/fonts/FiraSans-Medium.woff
  src/librustdoc/html/static/fonts/FiraSans-Medium.woff2
  src/librustdoc/html/static/fonts/FiraSans-Regular.woff
  src/librustdoc/html/static/fonts/FiraSans-Regular.woff2
  src/librustdoc/html/static/fonts/SourceCodePro-It.ttf.woff
  src/librustdoc/html/static/fonts/SourceCodePro-It.ttf.woff2
  src/librustdoc/html/static/fonts/SourceCodePro-LICENSE.txt
  src/librustdoc/html/static/fonts/SourceCodePro-Regular.ttf.woff
  src/librustdoc/html/static/fonts/SourceCodePro-Regular.ttf.woff2
  src/librustdoc/html/static/fonts/SourceCodePro-Semibold.ttf.woff
  src/librustdoc/html/static/fonts/SourceCodePro-Semibold.ttf.woff2
  src/librustdoc/html/static/fonts/SourceSerif4-Bold.ttf.woff
  src/librustdoc/html/static/fonts/SourceSerif4-Bold.ttf.woff2
  src/librustdoc/html/static/fonts/SourceSerif4-It.ttf.woff
  src/librustdoc/html/static/fonts/SourceSerif4-It.ttf.woff2
  src/librustdoc/html/static/fonts/SourceSerif4-LICENSE.md
  src/librustdoc/html/static/fonts/SourceSerif4-Regular.ttf.woff
  src/librustdoc/html/static/fonts/SourceSerif4-Regular.ttf.woff2
  src/librustdoc/html/static/fonts/noto-sans-kr-v13-korean-regular-LICENSE.txt
  src/librustdoc/html/static/fonts/noto-sans-kr-v13-korean-regular.woff
  src/librustdoc/html/static/images/brush.svg
  src/librustdoc/html/static/images/clipboard.svg
  src/librustdoc/html/static/images/down-arrow.svg
  src/librustdoc/html/static/images/favicon-16x16.png
  src/librustdoc/html/static/images/favicon-32x32.png
  src/librustdoc/html/static/images/favicon.svg
  src/librustdoc/html/static/images/rust-logo.png
  src/librustdoc/html/static/images/wheel.svg
  src/librustdoc/html/static/js/main.js
  src/librustdoc/html/static/js/search.js
  src/librustdoc/html/static/js/settings.js
  src/librustdoc/html/static/js/source-script.js
  src/librustdoc/html/static/js/storage.js
  src/librustdoc/html/static_files.rs
  src/librustdoc/theme/tests.rs
  src/test/run-make-fulldeps/rustdoc-themes/Makefile
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#86955 Fix typo in `ops::Drop` docs
  library/core/src/ops/drop.rs
Labels: S-waiting-on-bors

#86956 Revert "Add "every" as a doc alias for "all"."
  library/core/src/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#86639 Support lint tool names in rustc command line options
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_lint/src/tests.rs
  src/test/ui/lint/command-line-register-lint-tool.rs
  src/test/ui/lint/command-line-register-unknown-lint-tool.rs
  src/test/ui/lint/command-line-register-unknown-lint-tool.stderr
Labels: S-waiting-on-bors

#86823 Optimize unchecked indexing into chunks and chunks_mut
  library/core/src/slice/iter.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#85363 Support pretty printing slices using GDB
  src/etc/gdb_lookup.py
  src/etc/gdb_providers.py
  src/etc/lldb_commands
  src/etc/rust_types.py
  src/test/debuginfo/pretty-huge-vec.rs
  src/test/debuginfo/pretty-slices.rs
  src/tools/compiletest/src/runtest.rs
Labels: S-waiting-on-bors, merged-by-bors

#86520 BTree: consistently avoid unwrap_unchecked in iterators
  library/alloc/src/collections/btree/navigate.rs
Labels: S-waiting-on-bors, merged-by-bors

#86726 Use diagnostic items instead of lang items for rfc2229 migrations
  compiler/rustc_hir/src/lang_items.rs
  compiler/rustc_passes/src/lang_items.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_typeck/src/check/upvar.rs
  library/core/src/marker.rs
  library/std/src/panic.rs
Labels: S-waiting-on-bors

#86789 Update BTreeSet::drain_filter documentation
  library/alloc/src/collections/btree/set.rs
Labels: S-waiting-on-bors

#86838 Checking that function is const if marked with rustc_const_unstable
  compiler/rustc_error_codes/src/error_codes/E0542.md
  compiler/rustc_error_codes/src/error_codes/E0545.md
  compiler/rustc_error_codes/src/error_codes/E0547.md
  compiler/rustc_passes/src/stability.rs
  src/test/ui/consts/rustc-const-stability-require-const.rs
  src/test/ui/consts/rustc-const-stability-require-const.stderr
  src/test/ui/consts/rustc-impl-const-stability.rs
Labels: S-waiting-on-bors

#86903 Fix small headers display
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/css/rustdoc.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#86913 Document rustdoc with `--document-private-items`
  src/bootstrap/doc.rs
Labels: A-rustbuild, S-waiting-on-bors, T-rustdoc

#86957 Update .mailmap file
  .mailmap
Labels: S-waiting-on-bors

#86971 mailmap: Add alternative addresses for myself
  .mailmap
Labels: S-waiting-on-bors

#86982 Rollup of 8 pull requests
  .mailmap
  compiler/rustc_ast/src/util/comments/tests.rs
  compiler/rustc_ast_pretty/src/pprust/tests.rs
  compiler/rustc_error_codes/src/error_codes/E0542.md
  compiler/rustc_error_codes/src/error_codes/E0545.md
  compiler/rustc_error_codes/src/error_codes/E0547.md
  compiler/rustc_errors/src/json/tests.rs
  compiler/rustc_expand/src/mut_visit/tests.rs
  compiler/rustc_expand/src/parse/tests.rs
  compiler/rustc_expand/src/tests.rs
  compiler/rustc_expand/src/tokenstream/tests.rs
  compiler/rustc_hir/src/lang_items.rs
  compiler/rustc_interface/src/interface.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_lint/src/tests.rs
  compiler/rustc_mir/src/transform/coverage/tests.rs
  compiler/rustc_parse_format/src/tests.rs
  compiler/rustc_passes/src/lang_items.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lev_distance/tests.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/span_encoding.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_span/src/symbol/tests.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_typeck/src/check/upvar.rs
  library/alloc/src/collections/btree/set.rs
  library/core/src/marker.rs
  library/std/src/panic.rs
  src/bootstrap/doc.rs
  src/librustdoc/clean/cfg/tests.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/highlight/tests.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/css/rustdoc.css
  src/librustdoc/passes/unindent_comments/tests.rs
  src/test/ui-fulldeps/mod_dir_path_canonicalized.rs
  src/test/ui-fulldeps/pprust-expr-roundtrip.rs
  src/test/ui/consts/rustc-const-stability-require-const.rs
  src/test/ui/consts/rustc-const-stability-require-const.stderr
  src/test/ui/consts/rustc-impl-const-stability.rs
  src/tools/clippy/clippy_lints/src/doc.rs
  src/tools/error_index_generator/main.rs
  src/tools/rustfmt/src/formatting.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84961 Rework SESSION_GLOBALS API
  compiler/rustc_ast/src/util/comments/tests.rs
  compiler/rustc_ast_pretty/src/pprust/tests.rs
  compiler/rustc_errors/src/json/tests.rs
  compiler/rustc_expand/src/mut_visit/tests.rs
  compiler/rustc_expand/src/parse/tests.rs
  compiler/rustc_expand/src/tests.rs
  compiler/rustc_expand/src/tokenstream/tests.rs
  compiler/rustc_interface/src/interface.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_interface/src/util.rs
  compiler/rustc_lint/src/tests.rs
  compiler/rustc_mir/src/transform/coverage/tests.rs
  compiler/rustc_parse_format/src/tests.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lev_distance/tests.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/span_encoding.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_span/src/symbol/tests.rs
  src/librustdoc/clean/cfg/tests.rs
  src/librustdoc/doctest.rs
  src/librustdoc/html/highlight/tests.rs
  src/librustdoc/passes/unindent_comments/tests.rs
  src/test/ui-fulldeps/mod_dir_path_canonicalized.rs
  src/test/ui-fulldeps/pprust-expr-roundtrip.rs
  src/tools/clippy/clippy_lints/src/doc.rs
  src/tools/error_index_generator/main.rs
  src/tools/rustfmt/src/formatting.rs
Labels: S-waiting-on-bors, T-compiler

#86930 special case for integer log10
  library/core/src/num/int_log10.rs
  library/core/src/num/int_macros.rs
  library/core/src/num/mod.rs
  library/core/src/num/uint_macros.rs
  library/core/tests/num/int_log.rs
Labels: S-waiting-on-bors, merged-by-bors

#86701 2229: Reduce the size of closures with `capture_disjoint_fields`
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm-borrow.rs
  src/test/ui/closures/2229_closure_analysis/diagnostics/cant-mutate-imm-borrow.stderr
  src/test/ui/closures/2229_closure_analysis/move_closure.rs
  src/test/ui/closures/2229_closure_analysis/move_closure.stderr
  src/test/ui/closures/2229_closure_analysis/optimization/edge_case.rs
  src/test/ui/closures/2229_closure_analysis/optimization/edge_case.stderr
  src/test/ui/closures/2229_closure_analysis/optimization/edge_case_run_pass.rs
Labels: S-waiting-on-bors, merged-by-bors

#86869 Account for capture kind in auto traits migration
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/migrations/unpin_no_migration.rs
Labels: S-waiting-on-bors, merged-by-bors

#86904 Check FromIterator trait impl in prelude collision check.
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/method/prelude2021.rs
  library/core/src/iter/traits/collect.rs
  src/test/ui/rust-2021/future-prelude-collision-unneeded.rs
Labels: A-edition-2021, D-edition, S-waiting-on-bors, T-compiler, merged-by-bors

#85828 Stop generating `alloca`s & `memcmp` for simple short array equality
  compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs
  compiler/rustc_codegen_cranelift/src/value_and_place.rs
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_mir/src/interpret/intrinsics.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/intrinsic.rs
  library/core/src/array/equality.rs
  library/core/src/array/mod.rs
  library/core/src/intrinsics.rs
  src/test/codegen/array-equality.rs
  src/test/codegen/slice-ref-equality.rs
  src/test/ui/intrinsics/intrinsic-raw_eq-const-padding.rs
  src/test/ui/intrinsics/intrinsic-raw_eq-const-padding.stderr
  src/test/ui/intrinsics/intrinsic-raw_eq-const.rs
Labels: S-waiting-on-bors, merged-by-bors

#86994 Update the comment on `lower_expr_try`
  compiler/rustc_ast_lowering/src/expr.rs
Labels: S-waiting-on-bors

#87000 Use #[track_caller] in const panic diagnostics.
  compiler/rustc_mir/src/interpret/eval_context.rs
  src/test/ui/consts/const-eval/const_panic_track_caller.rs
  src/test/ui/consts/const-eval/const_panic_track_caller.stderr
  src/test/ui/consts/const-unwrap.rs
  src/test/ui/consts/const-unwrap.stderr
Labels: A-const-eval, A-diagnostics, S-waiting-on-bors, T-compiler

#87003 Rollup of 5 pull requests
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/closure.rs
  compiler/rustc_mir/src/interpret/eval_context.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/tests.rs
  src/test/ui/consts/const-eval/const_panic_track_caller.rs
  src/test/ui/consts/const-eval/const_panic_track_caller.stderr
  src/test/ui/consts/const-unwrap.rs
  src/test/ui/consts/const-unwrap.stderr
  src/test/ui/feature-gates/feature-gate-more-qualified-paths.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86855 Fix comments about unique borrows
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/ty/closure.rs
Labels: S-waiting-on-bors

#86881 Inline implementation of lookup_line
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/tests.rs
Labels: S-waiting-on-bors

#86937 Change linked tracking issue for more_qualified_paths
  compiler/rustc_feature/src/active.rs
  src/test/ui/feature-gates/feature-gate-more-qualified-paths.stderr
Labels: S-waiting-on-bors

#85832 Unescaped command-line arguments for Windows
  library/std/src/os/windows/process.rs
  library/std/src/sys/windows/process.rs
  library/std/src/sys/windows/process/tests.rs
Labels: S-waiting-on-bors, merged-by-bors

#86419 Add support for raw-dylib with stdcall, fastcall functions
  compiler/rustc_codegen_llvm/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_metadata/src/native_libs.rs
  compiler/rustc_middle/src/middle/cstore.rs
  src/test/run-make/raw-dylib-alt-calling-convention/Makefile
  src/test/run-make/raw-dylib-alt-calling-convention/driver.rs
  src/test/run-make/raw-dylib-alt-calling-convention/extern.c
  src/test/run-make/raw-dylib-alt-calling-convention/lib.rs
  src/test/run-make/raw-dylib-alt-calling-convention/output.txt
  src/test/run-make/raw-dylib-c/Makefile
  src/test/run-make/raw-dylib-c/driver.rs
  src/test/run-make/raw-dylib-c/extern_1.c
  src/test/run-make/raw-dylib-c/extern_2.c
  src/test/run-make/raw-dylib-c/lib.rs
  src/test/run-make/raw-dylib-c/output.txt
  src/test/ui/rfc-2627-raw-dylib/multiple-definitions.rs
  src/test/ui/rfc-2627-raw-dylib/multiple-definitions.stderr
  src/test/ui/rfc-2627-raw-dylib/unsupported-abi.rs
  src/test/ui/rfc-2627-raw-dylib/unsupported-abi.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86968 Remove `missing_docs` lint on private 2.0 macros
  compiler/rustc_lint/src/builtin.rs
  src/test/ui/lint/missing-doc-private-macro.rs
  src/test/ui/lint/missing-doc-private-macro.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86987 only check cg defaults wf once instantiated
  compiler/rustc_typeck/src/check/wfcheck.rs
  compiler/rustc_typeck/src/collect.rs
  src/test/ui/const-generics/const_evaluatable_checked/unused-complex-default-expr.rs
  src/test/ui/const-generics/defaults/complex-generic-default-expr.full.stderr
  src/test/ui/const-generics/defaults/complex-generic-default-expr.min.stderr
  src/test/ui/const-generics/defaults/complex-generic-default-expr.rs
Labels: F-const_evaluatable_checked, F-const_generics_defaults, S-waiting-on-bors, merged-by-bors

#81360 Support forwarding caller location through trait object method call
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/instance.rs
  compiler/rustc_typeck/src/collect.rs
  src/test/ui/rfc-2091-track-caller/tracked-trait-obj.rs
Labels: F-track_caller, S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors

#87006 Revert the revert of renaming traits::VTable to ImplSource
  compiler/rustc_middle/src/traits/mod.rs
Labels: S-waiting-on-bors

#87011 avoid reentrant lock acquire when ThreadIds run out
  library/std/src/thread/mod.rs
Labels: S-waiting-on-bors

#87013 Fix several ICEs related to malformed `#[repr(...)]` attributes
  compiler/rustc_attr/src/builtin.rs
  src/test/ui/attributes/nonterminal-expansion.rs
  src/test/ui/attributes/nonterminal-expansion.stderr
  src/test/ui/repr/issue-83921-ice.rs
  src/test/ui/repr/issue-83921-ice.stderr
  src/test/ui/repr/issue-83921-pretty.normal.stderr
  src/test/ui/repr/issue-83921-pretty.pretty.stdout
  src/test/ui/repr/issue-83921-pretty.rs
Labels: S-waiting-on-bors

#87020 remove const_raw_ptr_to_usize_cast feature
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_mir/src/transform/check_consts/ops.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_mir_build/src/check_unsafety.rs
  src/test/ui/cast/cast-ptr-to-int-const.mir.stderr
  src/test/ui/cast/cast-ptr-to-int-const.rs
  src/test/ui/cast/cast-ptr-to-int-const.thir.stderr
  src/test/ui/cast/feature-gate-const_raw_ptr_to_usize_cast.rs
  src/test/ui/cast/feature-gate-const_raw_ptr_to_usize_cast.stderr
  src/test/ui/const-ptr/ptr_to_usize_cast.rs
  src/test/ui/const-ptr/ptr_to_usize_cast.stderr
  src/test/ui/consts/const-eval/const_raw_ptr_ops2.rs
  src/test/ui/consts/const-eval/const_raw_ptr_ops2.stderr
  src/test/ui/consts/const-eval/issue-52442.rs
  src/test/ui/consts/const-eval/issue-52442.stderr
  src/test/ui/consts/const-eval/match-test-ptr-null.rs
  src/test/ui/consts/const-eval/match-test-ptr-null.stderr
  src/test/ui/consts/const-eval/promoted_raw_ptr_ops.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.stderr
  src/test/ui/consts/issue-17458.rs
  src/test/ui/consts/issue-17458.stderr
  src/test/ui/consts/issue-51559.rs
  src/test/ui/consts/issue-51559.stderr
  src/test/ui/consts/issue-52023-array-size-pointer-cast.rs
  src/test/ui/consts/issue-52023-array-size-pointer-cast.stderr
  src/test/ui/consts/issue-52432.rs
  src/test/ui/consts/issue-52432.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.rs
  src/test/ui/consts/min_const_fn/min_const_fn.stderr
  src/test/ui/issues/issue-18294.rs
  src/test/ui/issues/issue-18294.stderr
Labels: S-waiting-on-bors

#87028 Fix type: `'satic` -> `'static`
  compiler/rustc_mir/src/transform/inline.rs
Labels: S-waiting-on-bors

#87029 Rollup of 5 pull requests
  compiler/rustc_attr/src/builtin.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_middle/src/traits/mod.rs
  compiler/rustc_mir/src/transform/check_consts/ops.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_mir_build/src/check_unsafety.rs
  library/std/src/thread/mod.rs
  src/test/ui/attributes/nonterminal-expansion.rs
  src/test/ui/attributes/nonterminal-expansion.stderr
  src/test/ui/cast/cast-ptr-to-int-const.mir.stderr
  src/test/ui/cast/cast-ptr-to-int-const.rs
  src/test/ui/cast/cast-ptr-to-int-const.thir.stderr
  src/test/ui/cast/feature-gate-const_raw_ptr_to_usize_cast.rs
  src/test/ui/cast/feature-gate-const_raw_ptr_to_usize_cast.stderr
  src/test/ui/const-ptr/ptr_to_usize_cast.rs
  src/test/ui/const-ptr/ptr_to_usize_cast.stderr
  src/test/ui/consts/const-eval/const_raw_ptr_ops2.rs
  src/test/ui/consts/const-eval/const_raw_ptr_ops2.stderr
  src/test/ui/consts/const-eval/issue-52442.rs
  src/test/ui/consts/const-eval/issue-52442.stderr
  src/test/ui/consts/const-eval/match-test-ptr-null.rs
  src/test/ui/consts/const-eval/match-test-ptr-null.stderr
  src/test/ui/consts/const-eval/promoted_raw_ptr_ops.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.rs
  src/test/ui/consts/const-extern-fn/const-extern-fn-min-const-fn.stderr
  src/test/ui/consts/issue-17458.rs
  src/test/ui/consts/issue-17458.stderr
  src/test/ui/consts/issue-51559.rs
  src/test/ui/consts/issue-51559.stderr
  src/test/ui/consts/issue-52023-array-size-pointer-cast.rs
  src/test/ui/consts/issue-52023-array-size-pointer-cast.stderr
  src/test/ui/consts/issue-52432.rs
  src/test/ui/consts/issue-52432.stderr
  src/test/ui/consts/min_const_fn/min_const_fn.rs
  src/test/ui/consts/min_const_fn/min_const_fn.stderr
  src/test/ui/issues/issue-18294.rs
  src/test/ui/issues/issue-18294.stderr
  src/test/ui/repr/issue-83921-ice.rs
  src/test/ui/repr/issue-83921-ice.stderr
  src/test/ui/repr/issue-83921-pretty.normal.stderr
  src/test/ui/repr/issue-83921-pretty.pretty.stdout
  src/test/ui/repr/issue-83921-pretty.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#86873 Improve opaque pointers support
  compiler/rustc_codegen_llvm/src/builder.rs
  compiler/rustc_codegen_llvm/src/debuginfo/gdb.rs
  compiler/rustc_codegen_llvm/src/intrinsic.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_llvm/src/va_arg.rs
  compiler/rustc_codegen_ssa/src/meth.rs
  compiler/rustc_codegen_ssa/src/mir/block.rs
  compiler/rustc_codegen_ssa/src/mir/debuginfo.rs
  compiler/rustc_codegen_ssa/src/mir/intrinsic.rs
  compiler/rustc_codegen_ssa/src/mir/operand.rs
  compiler/rustc_codegen_ssa/src/mir/place.rs
  compiler/rustc_codegen_ssa/src/traits/builder.rs
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
Labels: S-waiting-on-bors, merged-by-bors

#85953 Fix linker error
  library/std/src/fs.rs
  library/std/src/fs/tests.rs
  library/std/src/sys/unix/android.rs
  library/std/src/sys/unix/fs.rs
  library/std/src/sys/unix/kernel_copy.rs
  library/std/src/sys/unix/os.rs
  library/std/src/sys/unix/process/process_unix.rs
  library/std/src/sys/unix/rand.rs
  library/std/src/sys/unix/thread.rs
  library/std/src/sys/unix/weak.rs
Labels: S-waiting-on-bors, T-libs, beta-nominated, merged-by-bors

#86416 Add clobber-only register classes for asm!
  compiler/rustc_ast_lowering/src/asm.rs
  compiler/rustc_codegen_llvm/src/asm.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_target/src/asm/aarch64.rs
  compiler/rustc_target/src/asm/mod.rs
  compiler/rustc_target/src/asm/riscv.rs
  compiler/rustc_target/src/asm/x86.rs
  src/doc/unstable-book/src/library-features/asm.md
  src/test/codegen/asm-clobbers.rs
  src/test/ui/asm/bad-reg.rs
  src/test/ui/asm/bad-reg.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86965 Improves migrations lint for RFC2229
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.rs
  src/test/ui/closures/2229_closure_analysis/migrations/auto_traits.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop_attr_migrations.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop_attr_migrations.rs
  src/test/ui/closures/2229_closure_analysis/migrations/insignificant_drop_attr_migrations.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.rs
  src/test/ui/closures/2229_closure_analysis/migrations/migrations_rustfix.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.rs
  src/test/ui/closures/2229_closure_analysis/migrations/mir_calls_to_shims.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/multi_diagnostics.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/multi_diagnostics.rs
  src/test/ui/closures/2229_closure_analysis/migrations/multi_diagnostics.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/precise.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/precise.rs
  src/test/ui/closures/2229_closure_analysis/migrations/precise.stderr
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.fixed
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.rs
  src/test/ui/closures/2229_closure_analysis/migrations/significant_drop.stderr
Labels: S-waiting-on-bors, merged-by-bors

#83918 Stabilize "RangeFrom" patterns in 1.55
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_parse/src/parser/pat.rs
  src/doc/unstable-book/src/language-features/exclusive-range-pattern.md
  src/doc/unstable-book/src/language-features/half-open-range-patterns.md
  src/test/ui/half-open-range-patterns/feature-gate-half-open-range-patterns.rs
  src/test/ui/half-open-range-patterns/feature-gate-half-open-range-patterns.stderr
  src/test/ui/half-open-range-patterns/range_pat_interactions0.rs
  src/test/ui/half-open-range-patterns/range_pat_interactions1.rs
  src/test/ui/half-open-range-patterns/range_pat_interactions1.stderr
  src/test/ui/half-open-range-patterns/range_pat_interactions2.rs
  src/test/ui/half-open-range-patterns/range_pat_interactions2.stderr
  src/test/ui/half-open-range-patterns/range_pat_interactions3.rs
  src/test/ui/half-open-range-patterns/range_pat_interactions3.stderr
  src/test/ui/half-open-range-patterns/slice_pattern_syntax_problem0.rs
  src/test/ui/half-open-range-patterns/slice_pattern_syntax_problem0.stderr
  src/test/ui/half-open-range-patterns/slice_pattern_syntax_problem1.rs
  src/test/ui/half-open-range-patterns/slice_pattern_syntax_problem1.stderr
  src/test/ui/half-open-range-patterns/slice_pattern_syntax_problem2.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, final-comment-period, finished-final-comment-period, merged-by-bors, needs-fcp, relnotes

#87042 Cleanup span quoting
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/proc_macro.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_lint/src/internal.rs
  compiler/rustc_lint/src/non_fmt_panic.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_mir/src/transform/coverage/spans.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_save_analysis/src/lib.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lib.rs
  src/test/ui/hygiene/unpretty-debug.stdout
  src/test/ui/proc-macro/meta-macro-hygiene.stdout
  src/test/ui/proc-macro/nonterminal-token-hygiene.stdout
  src/test/ui/proc-macro/span-from-proc-macro.stderr
  src/tools/clippy/clippy_lints/src/misc.rs
  src/tools/clippy/clippy_lints/src/unit_types/unit_cmp.rs
  src/tools/clippy/clippy_utils/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#86995 2229: Rewrite/Refactor Closure Capture Analaysis
  compiler/rustc_typeck/src/check/upvar.rs
  src/test/ui/closures/2229_closure_analysis/by_value.rs
  src/test/ui/closures/2229_closure_analysis/by_value.stderr
  src/test/ui/closures/2229_closure_analysis/move_closure.rs
  src/test/ui/closures/2229_closure_analysis/move_closure.stderr
  src/test/ui/closures/2229_closure_analysis/optimization/edge_case.rs
  src/test/ui/closures/2229_closure_analysis/optimization/edge_case.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85941 Reduce the amount of untracked state in TyCtxt -- Take 2
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/hir/mod.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_passes/src/entry.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_query_impl/src/stats.rs
  compiler/rustc_typeck/src/check_unused.rs
Labels: S-waiting-on-bors, merged-by-bors

#87037 cleanup(rustdoc): remove unused function getObjectNameById
  src/librustdoc/html/static/js/search.js
Labels: S-waiting-on-bors

#87045 Fix tracking issue for `bool_to_option`
  library/core/src/bool.rs
Labels: S-waiting-on-bors

#87049 Account for `submodules = false` in config.toml when updating LLVM submodule
  src/bootstrap/native.rs
Labels: A-LLVM, A-contributor-roadblock, A-rustbuild, S-waiting-on-bors
