Repository rust-lang/rust, pull requests merged in 2021-01, with the labels that each got.

#80514 Fix broken ./x.py install
  src/bootstrap/dist.rs
  src/bootstrap/install.rs
  src/bootstrap/tarball.rs
  src/bootstrap/test.rs
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated

#80519 Take type defaults into account in suggestions to reorder generic parameters
  compiler/rustc_ast_passes/src/ast_validation.rs
  src/test/ui/const-generics/defaults/complex-unord-param.min.stderr
  src/test/ui/const-generics/defaults/intermixed-lifetime.full.stderr
  src/test/ui/const-generics/defaults/intermixed-lifetime.min.stderr
  src/test/ui/const-generics/defaults/needs-feature.min.stderr
  src/test/ui/const-generics/defaults/needs-feature.none.stderr
  src/test/ui/const-generics/defaults/simple-defaults.min.stderr
  src/test/ui/issues/issue-80512-param-reordering-with-defaults.rs
  src/test/ui/issues/issue-80512-param-reordering-with-defaults.stderr
Labels: S-waiting-on-bors

#80532 remove unnecessary trailing semicolon from bootstrap
  src/bootstrap/config.rs
Labels: S-waiting-on-bors

#80548 FIx ICE on wf check for foreign fns
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
  src/test/ui/wf/wf-in-foreign-fn-decls-issue-80468.rs
  src/test/ui/wf/wf-in-foreign-fn-decls-issue-80468.stderr
Labels: S-waiting-on-bors

#80551 support pattern as const parents in type_of
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/const-generics/arg-in-pat-1.rs
  src/test/ui/const-generics/arg-in-pat-2.rs
  src/test/ui/const-generics/arg-in-pat-3.rs
Labels: A-const-generics, A-patterns, S-waiting-on-bors

#80323 Update and improve `rustc_codegen_{llvm,ssa}` docs
  compiler/rustc_codegen_llvm/src/base.rs
  compiler/rustc_codegen_llvm/src/common.rs
  compiler/rustc_codegen_ssa/src/base.rs
Labels: A-LLVM, A-codegen, C-cleanup, S-waiting-on-bors, T-compiler, T-doc

#80368 rustdoc: Render visibilities succinctly
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/pub-restricted.rs
  src/test/rustdoc/visibility.rs
Labels: A-visibility, S-waiting-on-bors, T-rustdoc, beta-nominated

#79576 Add edition 2021.
  compiler/rustc_ast/src/token.rs
  compiler/rustc_parse/src/parser/expr.rs
  compiler/rustc_parse/src/parser/item.rs
  compiler/rustc_resolve/src/late/diagnostics.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/src/edition.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/async-await/edition-deny-async-fns-2015.rs
  src/test/ui/async-await/edition-deny-async-fns-2015.stderr
  src/test/ui/async-await/suggest-switching-edition-on-await.stderr
  src/test/ui/editions/async-block-2015.rs
  src/test/ui/editions/async-block-2015.stderr
  src/test/ui/hello2021.rs
  src/test/ui/try-block/try-block-in-edition2015.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80310 Add fallible Box, Arc, and Rc allocator APIs
  library/alloc/src/boxed.rs
  library/alloc/src/rc.rs
  library/alloc/src/sync.rs
Labels: S-waiting-on-bors, merged-by-bors

#80547 In which we start to parse const generics defaults
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_builtin_macros/src/deriving/mod.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/ty/print/mod.rs
  compiler/rustc_parse/src/parser/generics.rs
  compiler/rustc_parse/src/parser/path.rs
  compiler/rustc_passes/src/stability.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_save_analysis/src/sig.rs
  compiler/rustc_span/src/symbol.rs
  compiler/rustc_typeck/src/astconv/generics.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs
  compiler/rustc_typeck/src/check/wfcheck.rs
  compiler/rustc_typeck/src/collect.rs
  src/librustdoc/clean/mod.rs
  src/test/ui/const-generics/min_const_generics/default_function_param.rs
  src/test/ui/const-generics/min_const_generics/default_function_param.stderr
  src/test/ui/const-generics/min_const_generics/default_trait_param.rs
  src/test/ui/const-generics/min_const_generics/default_trait_param.stderr
  src/test/ui/const-generics/params-in-ct-in-ty-param-lazy-norm.rs
  src/test/ui/feature-gates/feature-gate-const_generics_defaults.rs
  src/test/ui/feature-gates/feature-gate-const_generics_defaults.stderr
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
Labels: A-const-generics, S-waiting-on-bors, merged-by-bors

#80565 Fix tests that incorrectly used `!@has` instead of `@!has`
  src/test/rustdoc/inline_local/trait-vis.rs
  src/test/rustdoc/issue-74083.rs
  src/test/rustdoc/remove-url-from-headings.rs
Labels: A-testsuite, C-bug, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80569 Use Array.prototype.filter instead of open-coding
  src/librustdoc/html/static/main.js
Labels: S-waiting-on-bors, merged-by-bors

#80581 Give a better error for download-ci-llvm if .xz is not supported
  src/bootstrap/bootstrap.py
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors, merged-by-bors

#77832 Remove many unnecessary manual link resolves from library
  library/alloc/src/boxed.rs
  library/alloc/src/str.rs
  library/core/src/borrow.rs
  library/core/src/convert/mod.rs
  library/core/src/iter/traits/iterator.rs
  library/core/src/mem/mod.rs
  library/core/src/option.rs
  library/core/src/pin.rs
  library/core/src/result.rs
  library/std/src/error.rs
  library/std/src/io/mod.rs
  library/std/src/path.rs
  library/std/src/primitive_docs.rs
Labels: A-intra-doc-links, C-cleanup, S-waiting-on-bors, T-doc, T-libs, merged-by-bors

#79870 Add docs note about `Any::type_id` on smart pointers
  library/core/src/any.rs
Labels: S-waiting-on-bors, T-doc, T-libs, merged-by-bors

#79883 Enable ASan, TSan, UBSan for aarch64-apple-darwin.
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_session/src/session.rs
  src/bootstrap/compile.rs
  src/bootstrap/native.rs
  src/doc/unstable-book/src/compiler-flags/sanitizer.md
  src/test/codegen/sanitizer-no-sanitize.rs
  src/test/ui/sanitize/unsupported-target.stderr
  src/tools/compiletest/src/util.rs
Labels: A-sanitizers, O-macos, S-waiting-on-bors, merged-by-bors

#80115 rustc_serialize: specialize opaque encoding and decoding of some u8 sequences
  compiler/rustc_data_structures/src/fingerprint.rs
  compiler/rustc_macros/src/serialize.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_serialize/src/collection_impls.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_serialize/src/opaque.rs
  compiler/rustc_serialize/src/serialize.rs
Labels: I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#80615 Rollup of 6 pull requests
  .github/ISSUE_TEMPLATE/library_tracking_issue.md
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_save_analysis/src/sig.rs
  compiler/rustc_typeck/src/check/expr.rs
  src/bootstrap/clean.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/cfg.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/config.rs
  src/librustdoc/doctest.rs
  src/librustdoc/fold.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/toc.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/html_tags.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/theme.rs
  src/test/ui/issues/issue-80607.rs
  src/test/ui/issues/issue-80607.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80546 clippy fixes for librustdoc
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/cfg.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/config.rs
  src/librustdoc/doctest.rs
  src/librustdoc/fold.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/toc.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/html_tags.rs
  src/librustdoc/passes/strip_hidden.rs
  src/librustdoc/theme.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#80555 Improve library tracking issue template
  .github/ISSUE_TEMPLATE/library_tracking_issue.md
Labels: A-meta, S-waiting-on-bors, T-libs

#80574 Clean bootstrap artifacts on `x.py clean`
  src/bootstrap/clean.rs
Labels: A-rustbuild, S-waiting-on-bors

#80578 improve unconditional_panic description
  compiler/rustc_lint_defs/src/builtin.rs
Labels: S-waiting-on-bors

#80599 `const_generics_defaults`: don't ICE in the unimplemented parts
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_save_analysis/src/sig.rs
Labels: S-waiting-on-bors

#80613 Diag: print enum variant instead of enum type
  compiler/rustc_typeck/src/check/expr.rs
  src/test/ui/issues/issue-80607.rs
  src/test/ui/issues/issue-80607.stderr
Labels: S-waiting-on-bors

#80550 Cleanup markdown span handling, take 2
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: A-diagnostics, A-intra-doc-links, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80412 Fix search section position on small devices
  src/librustdoc/html/static/rustdoc.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80592 Suggest renaming or escaping when fixing non-snake-case identifiers which would conflict with keywords
  compiler/rustc_lint/src/nonstandard_style.rs
  src/test/ui/lint/lint-non-snake-case-identifiers-suggestion-reserved.rs
  src/test/ui/lint/lint-non-snake-case-identifiers-suggestion-reserved.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80623 Update Clippy
  Cargo.lock
  src/tools/clippy/.github/ISSUE_TEMPLATE/false_negative.md
  src/tools/clippy/.github/ISSUE_TEMPLATE/false_positive.md
  src/tools/clippy/.github/workflows/clippy.yml
  src/tools/clippy/CHANGELOG.md
  src/tools/clippy/Cargo.toml
  src/tools/clippy/README.md
  src/tools/clippy/clippy_dev/src/ra_setup.rs
  src/tools/clippy/clippy_lints/Cargo.toml
  src/tools/clippy/clippy_lints/src/default.rs
  src/tools/clippy/clippy_lints/src/from_over_into.rs
  src/tools/clippy/clippy_lints/src/large_enum_variant.rs
  src/tools/clippy/clippy_lints/src/lib.rs
  src/tools/clippy/clippy_lints/src/macro_use.rs
  src/tools/clippy/clippy_lints/src/manual_async_fn.rs
  src/tools/clippy/clippy_lints/src/map_err_ignore.rs
  src/tools/clippy/clippy_lints/src/ptr.rs
  src/tools/clippy/clippy_lints/src/single_component_path_imports.rs
  src/tools/clippy/clippy_lints/src/unused_unit.rs
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
  src/tools/clippy/clippy_lints/src/utils/mod.rs
  src/tools/clippy/clippy_lints/src/utils/ptr.rs
  src/tools/clippy/rust-toolchain
  src/tools/clippy/tests/ui/auxiliary/macro_rules.rs
  src/tools/clippy/tests/ui/field_reassign_with_default.rs
  src/tools/clippy/tests/ui/field_reassign_with_default.stderr
  src/tools/clippy/tests/ui/from_over_into.rs
  src/tools/clippy/tests/ui/from_over_into.stderr
  src/tools/clippy/tests/ui/large_enum_variant.rs
  src/tools/clippy/tests/ui/large_enum_variant.stderr
  src/tools/clippy/tests/ui/map_err.stderr
  src/tools/clippy/tests/ui/min_rust_version_attr.rs
  src/tools/clippy/tests/ui/min_rust_version_attr.stderr
  src/tools/clippy/tests/ui/ptr_arg.rs
  src/tools/clippy/tests/ui/ptr_arg.stderr
  src/tools/clippy/tests/ui/unused_unit.fixed
  src/tools/clippy/tests/ui/unused_unit.rs
  src/tools/clippy/tests/ui/unused_unit.stderr
  src/tools/clippy/tests/versioncheck.rs
  src/tools/clippy/util/gh-pages/index.html
Labels: S-waiting-on-bors, merged-by-bors

#79827 Describe why `size_align` have not been inlined so far
  library/core/src/alloc/layout.rs
Labels: S-waiting-on-bors, merged-by-bors

#80261 rustdoc DocFragment rework
  src/librustdoc/clean/types.rs
  src/librustdoc/core.rs
  src/librustdoc/doctest.rs
  src/librustdoc/formats/cache.rs
  src/librustdoc/html/render/cache.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/passes/calculate_doc_coverage.rs
  src/librustdoc/passes/collapse_docs.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/librustdoc/passes/mod.rs
  src/librustdoc/passes/unindent_comments.rs
  src/librustdoc/passes/unindent_comments/tests.rs
  src/test/rustdoc-ui/invalid-syntax.stderr
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#80247 Fix indentation of -Z meta-stats output
  compiler/rustc_metadata/src/rmeta/encoder.rs
Labels: S-waiting-on-bors, merged-by-bors

#80590 Update `bool` and `!` docs
  library/std/src/primitive_docs.rs
Labels: C-cleanup, S-waiting-on-bors, T-doc, T-lang, merged-by-bors

#80591 remove allow(incomplete_features) from std
  library/alloc/src/lib.rs
  library/core/src/lib.rs
Labels: S-waiting-on-bors

#80617 Detect invalid rustdoc test commands
  src/etc/htmldocck.py
Labels: A-doctests, S-waiting-on-bors, T-rustdoc

#80628 reduce borrowing and (de)referencing around match patterns (clippy::match_ref_pats)
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_builtin_macros/src/deriving/hash.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_incremental/src/assert_dep_graph.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_lint/src/nonstandard_style.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_metadata/src/native_libs.rs
  compiler/rustc_middle/src/ty/diagnostics.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/move_errors.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_passes/src/naked_functions.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_trait_selection/src/traits/auto_trait.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/callee.rs
  compiler/rustc_typeck/src/check/coercion.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  compiler/rustc_typeck/src/collect.rs
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/utils.rs
Labels: S-waiting-on-bors

#80646 Clean up in `each_child_of_item`
  compiler/rustc_metadata/src/rmeta/decoder.rs
Labels: S-waiting-on-bors

#80655 Rollup of 5 pull requests
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_builtin_macros/src/deriving/hash.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_hir/src/intravisit.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_incremental/src/assert_dep_graph.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_lint/src/nonstandard_style.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_metadata/src/native_libs.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_middle/src/ty/diagnostics.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/move_errors.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_passes/src/naked_functions.rs
  compiler/rustc_save_analysis/src/dump_visitor.rs
  compiler/rustc_trait_selection/src/traits/auto_trait.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_trait_selection/src/traits/select/mod.rs
  compiler/rustc_typeck/src/astconv/mod.rs
  compiler/rustc_typeck/src/check/callee.rs
  compiler/rustc_typeck/src/check/coercion.rs
  compiler/rustc_typeck/src/check/expr.rs
  compiler/rustc_typeck/src/check/method/suggest.rs
  compiler/rustc_typeck/src/collect.rs
  library/alloc/src/lib.rs
  library/core/src/lib.rs
  src/etc/htmldocck.py
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/ignore-block-help.rs
  src/test/rustdoc-ui/ignore-block-help.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80580 Add suggestion for "ignore" doc code block
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/check_code_block_syntax.rs
  src/test/rustdoc-ui/ignore-block-help.rs
  src/test/rustdoc-ui/ignore-block-help.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-rustdoc

#77859 Rustdoc: only report broken ref-style links once
  src/librustdoc/html/markdown.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/reference-link-reports-error-once.rs
  src/test/rustdoc-ui/reference-link-reports-error-once.stderr
  src/test/rustdoc-ui/reference-links.rs
  src/test/rustdoc-ui/reference-links.stderr
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80418 Allow references to interior mutable data behind a feature gate
  compiler/rustc_error_codes/src/error_codes/E0492.md
  compiler/rustc_feature/src/active.rs
  compiler/rustc_mir/src/transform/check_consts/ops.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_span/src/symbol.rs
  src/test/ui/consts/const-address-of-interior-mut.stderr
  src/test/ui/consts/const-multi-ref.rs
  src/test/ui/consts/const-multi-ref.stderr
  src/test/ui/consts/partial_qualif.rs
  src/test/ui/consts/partial_qualif.stderr
  src/test/ui/consts/qualif_overwrite.rs
  src/test/ui/consts/qualif_overwrite.stderr
  src/test/ui/consts/qualif_overwrite_2.rs
  src/test/ui/consts/qualif_overwrite_2.stderr
  src/test/ui/consts/std/cell.rs
  src/test/ui/consts/std/cell.stderr
  src/test/ui/error-codes/E0492.rs
  src/test/ui/error-codes/E0492.stderr
  src/test/ui/feature-gate/feature-gate-const_refs_to_cell.rs
  src/test/ui/issues/issue-17718-const-borrow.rs
  src/test/ui/issues/issue-17718-const-borrow.stderr
  src/test/ui/panic-handler/weak-lang-item.stderr
  src/test/ui/unsafe/ranged_ints3_const.rs
  src/test/ui/unsafe/ranged_ints3_const.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80554 More js cleanup
  src/librustdoc/html/static/main.js
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80610 Use `UnhashMap` whenever we have a key of `DefPathHash`
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
Labels: S-waiting-on-bors, merged-by-bors

#80661 Cleanup rustdoc handling of associated types
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc/deref-typedef.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80651 Add note to non-exhaustive match on reference to empty
  compiler/rustc_mir_build/src/thir/pattern/check_match.rs
  src/test/ui/pattern/usefulness/always-inhabited-union-ref.stderr
  src/test/ui/pattern/usefulness/issue-78123-non-exhaustive-reference.rs
  src/test/ui/pattern/usefulness/issue-78123-non-exhaustive-reference.stderr
  src/test/ui/uninhabited/uninhabited-matches-feature-gated.stderr
Labels: A-diagnostics, A-exhaustiveness-checking, S-waiting-on-bors, merged-by-bors

#80688 [security] Update mdbook
  Cargo.lock
  src/tools/rustbook/Cargo.toml
Labels: S-waiting-on-bors, T-release, beta-accepted, beta-nominated, merged-by-bors, stable-accepted, stable-nominated

#80624 use PlaceRef more consistently instead of loosely coupled local+projection
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
  compiler/rustc_codegen_ssa/src/mir/place.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/prefixes.rs
Labels: S-waiting-on-bors, merged-by-bors

#80426 Don't use `self.date` unconditionally for `program_out_of_date()`
  src/bootstrap/bootstrap.py
  src/bootstrap/bootstrap_test.py
Labels: A-rustbuild, C-cleanup, S-waiting-on-bors, merged-by-bors

#80612 Remove reverted change from relnotes
  RELEASES.md
Labels: S-waiting-on-bors

#80627 Builder: Warn if test file does not exist
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#80637 Use Option::filter instead of open-coding it
  compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#80643 Move variable into the only branch where it is relevant
  compiler/rustc_metadata/src/rmeta/decoder.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#80656 Fixed documentation error for `std::hint::spin_loop`
  library/core/src/hint.rs
Labels: S-waiting-on-bors

#80666 Fix missing link for "fully qualified syntax"
  library/alloc/src/rc.rs
Labels: S-waiting-on-bors

#80672 ./x.py clippy: allow the most noisy lints
  src/bootstrap/check.rs
Labels: A-rustbuild, S-waiting-on-bors

#80677 doc -- list edit for consistency
  library/core/src/iter/adapters/zip.rs
Labels: S-waiting-on-bors

#80696 make sure that promoteds which fail to evaluate in dead const code behave correctly
  src/test/ui/consts/promotion.rs
Labels: S-waiting-on-bors

#80708 Rollup of 12 pull requests
  Cargo.lock
  RELEASES.md
  compiler/rustc_hir/Cargo.toml
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_typeck/src/astconv/generics.rs
  library/alloc/src/borrow.rs
  library/alloc/src/rc.rs
  library/core/src/hint.rs
  library/core/src/iter/adapters/zip.rs
  src/bootstrap/builder.rs
  src/bootstrap/channel.rs
  src/bootstrap/check.rs
  src/bootstrap/dist.rs
  src/bootstrap/lib.rs
  src/bootstrap/sanity.rs
  src/bootstrap/setup.rs
  src/bootstrap/test.rs
  src/test/ui/const-generics/suggest_const_for_array.rs
  src/test/ui/const-generics/suggest_const_for_array.stderr
  src/test/ui/consts/promotion.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80442 Mention Arc::make_mut and Rc::make_mut in the documentation of Cow
  library/alloc/src/borrow.rs
Labels: S-waiting-on-bors, T-doc, T-libs

#80538 Add check for `[T;N]`/`usize` mismatch in astconv
  Cargo.lock
  compiler/rustc_hir/Cargo.toml
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_typeck/src/astconv/generics.rs
  src/test/ui/const-generics/suggest_const_for_array.rs
  src/test/ui/const-generics/suggest_const_for_array.stderr
Labels: S-waiting-on-bors

#80680 [beta] Clippy backport field_reassign_with_default fix
  src/tools/clippy/clippy_lints/src/default.rs
  src/tools/clippy/tests/ui/field_reassign_with_default.rs
  src/tools/clippy/tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80686 Error when #[doc(alias)] has same name as the item
  compiler/rustc_passes/src/check_attr.rs
  src/test/rustdoc-ui/doc-alias-same-name.rs
  src/test/rustdoc-ui/doc-alias-same-name.stderr
  src/test/ui/doc-alias-same-name.rs
  src/test/ui/doc-alias-same-name.stderr
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#80699 const_intrinsic_copy - Add Reference to tracking issue
  library/core/src/intrinsics.rs
Labels: S-waiting-on-bors, merged-by-bors

#80717 Add more code spans to docs in intrinsics.rs
  library/core/src/intrinsics.rs
Labels: S-waiting-on-bors, merged-by-bors

#80711 Make `size_of_val` and `min_align_of_val` intrinsics unsafe
  compiler/rustc_typeck/src/check/intrinsic.rs
  library/core/src/mem/mod.rs
Labels: A-intrinsics, S-waiting-on-bors, merged-by-bors

#80415 Compute parent module when collecting hir::MacroDef.
  compiler/rustc_middle/src/hir/map/collector.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  src/test/rustdoc/macros.rs
Labels: A-hir, A-macros, S-waiting-on-bors, merged-by-bors

#80724 Remove useless doc_alias feature gate
  src/test/rustdoc-ui/doc-alias-crate-level.rs
  src/test/rustdoc-ui/doc-alias-crate-level.stderr
  src/test/ui/check-doc-alias-attr-location.rs
  src/test/ui/check-doc-alias-attr-location.stderr
  src/test/ui/check-doc-alias-attr.rs
  src/test/ui/check-doc-alias-attr.stderr
  src/test/ui/doc-alias-crate-level.rs
  src/test/ui/doc-alias-crate-level.stderr
Labels: A-doc-alias, A-testsuite, C-cleanup, S-waiting-on-bors, merged-by-bors

#80714 fixed const_generics error help
  compiler/rustc_typeck/src/check/wfcheck.rs
  src/test/ui/const-generics/array-size-in-generic-struct-param.min.stderr
  src/test/ui/const-generics/const-param-before-other-params.min.stderr
  src/test/ui/const-generics/const-param-elided-lifetime.min.stderr
  src/test/ui/const-generics/const-param-type-depends-on-const-param.min.stderr
  src/test/ui/const-generics/different_byref.min.stderr
  src/test/ui/const-generics/forbid-non-structural_match-types.min.stderr
  src/test/ui/const-generics/intrinsics-type_name-as-const-argument.min.stderr
  src/test/ui/const-generics/issue-66596-impl-trait-for-str-const-arg.min.stderr
  src/test/ui/const-generics/issues/issue-62579-no-match.min.stderr
  src/test/ui/const-generics/issues/issue-62878.min.stderr
  src/test/ui/const-generics/issues/issue-63322-forbid-dyn.min.stderr
  src/test/ui/const-generics/issues/issue-68615-adt.min.stderr
  src/test/ui/const-generics/issues/issue-68615-array.min.stderr
  src/test/ui/const-generics/issues/issue-71169.min.stderr
  src/test/ui/const-generics/issues/issue-73491.min.stderr
  src/test/ui/const-generics/issues/issue-74101.min.stderr
  src/test/ui/const-generics/issues/issue-74255.min.stderr
  src/test/ui/const-generics/issues/issue-74950.min.stderr
  src/test/ui/const-generics/issues/issue-75047.min.stderr
  src/test/ui/const-generics/min_const_generics/complex-types.stderr
  src/test/ui/const-generics/min_const_generics/static-reference-array-const-param.stderr
  src/test/ui/const-generics/min_const_generics/transmute-const-param-static-reference.stderr
  src/test/ui/const-generics/nested-type.min.stderr
  src/test/ui/const-generics/slice-const-param-mismatch.min.stderr
  src/test/ui/const-generics/slice-const-param.min.stderr
  src/test/ui/const-generics/std/const-generics-range.min.stderr
  src/test/ui/const-generics/type-dependent/issue-71348.min.stderr
  src/test/ui/feature-gates/feature-gate-const_generics.stderr
Labels: F-const_generics, S-waiting-on-bors, merged-by-bors

#80754 Optimize away a `fs::metadata` call.
  compiler/rustc_fs_util/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#80425 Document `ModuleData` and improve names
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
Labels: A-resolve, S-waiting-on-bors, T-compiler, T-doc, merged-by-bors

#80200 Optimize DST field access
  compiler/rustc_codegen_ssa/src/mir/place.rs
Labels: S-waiting-on-bors, merged-by-bors

#80648 Make `ExpnData` fields `krate` and `orig_id` private
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_span/src/hygiene.rs
Labels: S-waiting-on-bors, merged-by-bors

#79863 Update `compiler_builtins` to 0.1.39
  Cargo.lock
  library/alloc/Cargo.toml
  library/std/Cargo.toml
  library/test/Cargo.toml
Labels: S-waiting-on-bors, merged-by-bors

#77853 Stabilize slice::strip_prefix and slice::strip_suffix
  library/core/src/slice/mod.rs
  library/std/src/lib.rs
Labels: S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, needs-fcp, relnotes, to-announce

#80659 Edit rustc_ast::tokenstream docs
  compiler/rustc_ast/src/tokenstream.rs
Labels: S-waiting-on-bors

#80660 Properly handle primitive disambiguators in rustdoc
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/intra-doc/incompatible-primitive-disambiguator.rs
  src/test/rustdoc-ui/intra-doc/incompatible-primitive-disambiguator.stderr
  src/test/rustdoc/intra-doc/primitive-disambiguators.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc

#80738 Remove bottom margin from crate version when the docs sidebar is collapsed
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#80744 rustdoc: Turn `next_def_id` comments into docs
  src/librustdoc/clean/types.rs
  src/librustdoc/core.rs
Labels: S-waiting-on-bors, T-doc, T-rustdoc

#80750 Don't use to_string on Symbol in rustc_passes/check_attr.rs
  compiler/rustc_passes/src/check_attr.rs
Labels: S-waiting-on-bors

#80769 Improve wording of parse doc
  library/core/src/str/mod.rs
Labels: S-waiting-on-bors

#80780 Return EOF_CHAR constant instead of magic char.
  compiler/rustc_lexer/src/cursor.rs
Labels: S-waiting-on-bors

#80784 rustc_parse: Better spans for synthesized token streams
  compiler/rustc_ast/src/token.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/proc_macro.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_parse/src/lib.rs
  src/test/ui/proc-macro/issue-75930-derive-cfg.stdout
  src/test/ui/proc-macro/issue-78675-captured-inner-attrs.stdout
Labels: S-waiting-on-bors

#80790 Rollup of 10 pull requests
  compiler/rustc_ast/src/token.rs
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_error_codes/src/error_codes/E0435.md
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/proc_macro.rs
  compiler/rustc_expand/src/proc_macro_server.rs
  compiler/rustc_lexer/src/cursor.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_session/src/config.rs
  library/core/src/str/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/core.rs
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.doctest.txt
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.doctest/doctest.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage/doctest.rs
  src/test/rustdoc-ui/intra-doc/incompatible-primitive-disambiguator.rs
  src/test/rustdoc-ui/intra-doc/incompatible-primitive-disambiguator.stderr
  src/test/rustdoc/intra-doc/primitive-disambiguators.rs
  src/test/ui/error-codes/E0435.stderr
  src/test/ui/impl-trait/bindings.stderr
  src/test/ui/issues/issue-27433.stderr
  src/test/ui/issues/issue-3521-2.stderr
  src/test/ui/issues/issue-3521.stderr
  src/test/ui/issues/issue-3668-2.stderr
  src/test/ui/issues/issue-3668.stderr
  src/test/ui/issues/issue-42060.stderr
  src/test/ui/issues/issue-44239.stderr
  src/test/ui/mir/mir-inlining/inline-instrument-coverage-fail.rs
  src/test/ui/mir/mir-inlining/inline-instrument-coverage-fail.stderr
  src/test/ui/non-constant-expr-for-arr-len.stderr
  src/test/ui/proc-macro/issue-75930-derive-cfg.stdout
  src/test/ui/proc-macro/issue-78675-captured-inner-attrs.stdout
  src/test/ui/repeat_count.stderr
  src/test/ui/type/type-dependent-def-issue-49241.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80521 MIR Inline is incompatible with coverage
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_session/src/config.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.doctest.txt
  src/test/run-make-fulldeps/coverage-spanview/expected_mir_dump.doctest/doctest.main.-------.InstrumentCoverage.0.html
  src/test/run-make-fulldeps/coverage/doctest.rs
  src/test/ui/mir/mir-inlining/inline-instrument-coverage-fail.rs
  src/test/ui/mir/mir-inlining/inline-instrument-coverage-fail.stderr
Labels: S-waiting-on-bors

#80012 Add pointing const identifier when emitting E0435
  compiler/rustc_error_codes/src/error_codes/E0435.md
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  src/test/ui/error-codes/E0435.stderr
  src/test/ui/impl-trait/bindings.stderr
  src/test/ui/issues/issue-27433.stderr
  src/test/ui/issues/issue-3521-2.stderr
  src/test/ui/issues/issue-3521.stderr
  src/test/ui/issues/issue-3668-2.stderr
  src/test/ui/issues/issue-3668.stderr
  src/test/ui/issues/issue-42060.stderr
  src/test/ui/issues/issue-44239.stderr
  src/test/ui/non-constant-expr-for-arr-len.stderr
  src/test/ui/repeat_count.stderr
  src/test/ui/type/type-dependent-def-issue-49241.stderr
Labels: A-diagnostics, S-waiting-on-bors, T-compiler

#80709 Limit target endian to an enum instead of free string
  compiler/rustc_codegen_llvm/src/va_arg.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_target/src/abi/mod.rs
  compiler/rustc_target/src/spec/armebv7r_none_eabi.rs
  compiler/rustc_target/src/spec/armebv7r_none_eabihf.rs
  compiler/rustc_target/src/spec/mips64_unknown_linux_gnuabi64.rs
  compiler/rustc_target/src/spec/mips64_unknown_linux_muslabi64.rs
  compiler/rustc_target/src/spec/mips_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/mips_unknown_linux_musl.rs
  compiler/rustc_target/src/spec/mips_unknown_linux_uclibc.rs
  compiler/rustc_target/src/spec/mipsisa32r6_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/mipsisa64r6_unknown_linux_gnuabi64.rs
  compiler/rustc_target/src/spec/mod.rs
  compiler/rustc_target/src/spec/powerpc64_unknown_freebsd.rs
  compiler/rustc_target/src/spec/powerpc64_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/powerpc64_unknown_linux_musl.rs
  compiler/rustc_target/src/spec/powerpc64_wrs_vxworks.rs
  compiler/rustc_target/src/spec/powerpc_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/powerpc_unknown_linux_gnuspe.rs
  compiler/rustc_target/src/spec/powerpc_unknown_linux_musl.rs
  compiler/rustc_target/src/spec/powerpc_unknown_netbsd.rs
  compiler/rustc_target/src/spec/powerpc_wrs_vxworks.rs
  compiler/rustc_target/src/spec/powerpc_wrs_vxworks_spe.rs
  compiler/rustc_target/src/spec/s390x_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/sparc64_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/sparc64_unknown_netbsd.rs
  compiler/rustc_target/src/spec/sparc64_unknown_openbsd.rs
  compiler/rustc_target/src/spec/sparc_unknown_linux_gnu.rs
  compiler/rustc_target/src/spec/sparcv9_sun_solaris.rs
Labels: S-waiting-on-bors, merged-by-bors

#80761 handle generic trait methods in coverage-report tests
  src/test/run-make-fulldeps/coverage-reports/Makefile
Labels: S-waiting-on-bors

#80785 rustc_ast_pretty: Remove `PrintState::insert_extra_parens`
  compiler/rustc_ast_pretty/src/pprust/mod.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_parse/src/lib.rs
Labels: S-waiting-on-bors

#80791 Fix type name in doc example for Iter and IterMut
  library/core/src/slice/iter.rs
Labels: S-waiting-on-bors

#80794 Use Option::map_or instead of `.map(..).unwrap_or(..)`
  src/librustdoc/clean/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#80799 Get rid of custom pretty-printing in rustdoc
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/utils.rs
  src/test/rustdoc-ui/range-pattern.rs
  src/test/rustdoc/range-arg-pattern.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#80806 Rollup of 7 pull requests
  compiler/rustc_ast_pretty/src/pprust/mod.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_hir_pretty/src/lib.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_typeck/src/check/check.rs
  library/core/src/slice/iter.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/core.rs
  src/test/run-make-fulldeps/coverage-reports/Makefile
  src/test/rustdoc-ui/intra-doc/unused-extern-crate.rs
  src/test/rustdoc-ui/intra-doc/unused-extern-crate.stderr
  src/test/rustdoc-ui/range-pattern.rs
  src/test/rustdoc/range-arg-pattern.rs
  src/test/ui/abi/issues/issue-22565-rust-call.rs
  src/test/ui/abi/issues/issue-22565-rust-call.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80372 Don't panic when an external crate can't be resolved
  src/librustdoc/core.rs
  src/test/rustdoc-ui/intra-doc/unused-extern-crate.rs
  src/test/rustdoc-ui/intra-doc/unused-extern-crate.stderr
Labels: A-intra-doc-links, A-resolve, S-waiting-on-bors, T-rustdoc

#79675 Make sure rust-call errors occur correctly for traits
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/abi/issues/issue-22565-rust-call.rs
  src/test/ui/abi/issues/issue-22565-rust-call.stderr
Labels: S-waiting-on-bors, T-compiler

#80756 Optimize away some `fs::metadata` calls.
  compiler/rustc_incremental/src/persist/file_format.rs
  compiler/rustc_incremental/src/persist/fs.rs
  compiler/rustc_incremental/src/persist/save.rs
Labels: S-waiting-on-bors, merged-by-bors

#80535 Add a note for `*` and `{}` usage on `use`
  compiler/rustc_parse/src/parser/item.rs
  src/test/ui/parser/import-from-path.stderr
  src/test/ui/parser/import-from-rename.stderr
  src/test/ui/parser/import-glob-path.stderr
  src/test/ui/parser/import-glob-rename.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80653 Recursively document methods via `Deref` traits
  src/librustdoc/html/markdown.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/passes/collect_trait_impls.rs
  src/test/rustdoc-ui/deref-recursive-cycle.rs
  src/test/rustdoc/deref-recursive-pathbuf.rs
  src/test/rustdoc/deref-recursive.rs
  src/test/rustdoc/deref-typedef.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#76896 Do not make local copies of inline fns in debug mode
  compiler/rustc_middle/src/mir/mono.rs
  src/test/incremental/hygiene/load_cached_hygiene.rs
  src/test/incremental/remapped_paths_cc/main.rs
  src/test/run-make-fulldeps/inline-always-many-cgu/Makefile
Labels: S-waiting-on-bors, merged-by-bors

#78452 Access query (DepKind) metadata through fields
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/dep_graph/mod.rs
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_query_system/src/dep_graph/dep_node.rs
  compiler/rustc_query_system/src/dep_graph/mod.rs
Labels: A-query-system, S-waiting-on-bors, merged-by-bors

#80749 Make target-cpu=native detect individual features
  compiler/rustc_codegen_llvm/src/back/write.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_llvm/src/llvm_util.rs
Labels: S-waiting-on-bors, merged-by-bors

#80755 Optimize away some path lookups in the generic `fs::copy` implementation
  library/std/src/sys_common/fs.rs
Labels: S-waiting-on-bors, merged-by-bors

#80797 Fix x.py install not working with relative prefix
  src/bootstrap/install.rs
Labels: A-rustbuild, S-waiting-on-bors, T-infra, beta-accepted, beta-nominated, merged-by-bors

#80808 Fix typo in Step trait
  library/core/src/iter/range.rs
Labels: S-waiting-on-bors, merged-by-bors

#80563 resolve/expand: Improve attribute expansion on macro definitions and calls
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_expand/src/placeholders.rs
  compiler/rustc_resolve/src/build_reduced_graph.rs
  compiler/rustc_resolve/src/def_collector.rs
  src/test/ui/attributes/key-value-expansion-on-mac.rs
  src/test/ui/attributes/key-value-expansion-on-mac.stderr
  src/test/ui/feature-gates/issue-43106-gating-of-builtin-attrs.stderr
  src/test/ui/feature-gates/issue-43106-gating-of-macro_use.stderr
Labels: A-macros, S-waiting-on-bors, T-compiler, merged-by-bors

#80830 Use an empty `TokenCursorFrame` stack when capturing tokens
  compiler/rustc_parse/src/parser/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#80441 ast: Remove some indirection layers from values in key-value attributes
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/attr/mod.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/util/literal.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_parse/src/validate_attr.rs
  src/test/ui/ast-json/ast-json-noexpand-output.stdout
  src/test/ui/ast-json/ast-json-output.stdout
  src/tools/clippy/clippy_lints/src/utils/ast_utils.rs
Labels: S-waiting-on-bors, merged-by-bors

#80831 Don't mark `force_query_with_job` as `inline(always)`
  compiler/rustc_query_system/src/query/plumbing.rs
Labels: A-query-system, I-compiletime, S-waiting-on-bors, merged-by-bors

#77862 Rustdoc: Fix macros 2.0 and built-in derives being shown at the wrong path
  compiler/rustc_privacy/src/lib.rs
  library/std/src/prelude/v1.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/visit_ast.rs
  src/test/rustdoc/auxiliary/macro_pub_in_module.rs
  src/test/rustdoc/macro_pub_in_module.rs
Labels: A-macros, A-visibility, S-waiting-on-bors, T-rustdoc, merged-by-bors

#80803 Remove useless `fill_in` function
  src/librustdoc/clean/inline.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#80820 Support `download-ci-llvm` on NixOS
  src/bootstrap/bootstrap.py
Labels: S-waiting-on-bors

#80825 Remove under-used ImplPolarity enum
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/blanket_impl.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/format.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/theme.rs
Labels: C-cleanup, S-waiting-on-bors, T-rustdoc

#80850 Allow #[rustc_builtin_macro = "name"]
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
Labels: S-waiting-on-bors

#80857 Add comment to `Vec::truncate` explaining `>` vs `>=`
  library/alloc/src/vec/mod.rs
Labels: A-collections, S-waiting-on-bors, T-libs, libs-impl

#80774 Fix safety comment
  library/std/src/alloc.rs
Labels: S-waiting-on-bors

#79968 Improve core::ptr::drop_in_place debuginfo
  compiler/rustc_symbol_mangling/src/legacy.rs
Labels: A-debuginfo, S-waiting-on-bors, T-compiler

#79502 Implement From<char> for u64 and u128.
  library/core/src/char/convert.rs
Labels: C-enhancement, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, needs-fcp

#80391 BTreeMap: tougher checking on most uses of copy_nonoverlapping
  library/alloc/src/collections/btree/node.rs
Labels: S-waiting-on-bors, merged-by-bors

#80789 Synthesize a `TokenStream` for `StmtKind::Empty`
  compiler/rustc_parse/src/lib.rs
  src/test/ui/proc-macro/issue-80760-empty-stmt.rs
  src/test/ui/proc-macro/issue-80760-empty-stmt.stdout
Labels: S-waiting-on-bors, merged-by-bors

#79414 Add suggestion for PATTERNS_IN_FNS_WITHOUT_BODY
  compiler/rustc_ast_passes/src/ast_validation.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint_defs/src/lib.rs
  src/test/ui/no-patterns-in-args-2.stderr
Labels: S-waiting-on-bors, merged-by-bors

#80782 resolve: Scope visiting doesn't need an `Ident`
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_span/src/hygiene.rs
  compiler/rustc_span/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#80818 Don't build in-tree llvm-libunwind if system-llvm-libunwind is enable
  library/unwind/build.rs
Labels: S-waiting-on-bors, merged-by-bors

#80872 Fix typo in source-based-code-coverage.md
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
Labels: S-waiting-on-bors

#80878 Add ABI argument to `find_mir_or_eval_fn`
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/terminator.rs
  compiler/rustc_mir/src/transform/const_prop.rs
Labels: S-waiting-on-bors

#80881 Fix intra-doc links to `Self` and `crate`
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc-crate/auxiliary/self.rs
  src/test/rustdoc/intra-doc-crate/self.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc

#80887 log-color: Detect TTY based on stderr, not stdout
  compiler/rustc_driver/src/lib.rs
Labels: A-driver, S-waiting-on-bors, T-compiler

#80892 rustdoc: Remove `*` intra-doc alias for `pointer`
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
Labels: A-intra-doc-links, S-waiting-on-bors, T-rustdoc

#80905 Rollup of 6 pull requests
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_mir/src/const_eval/machine.rs
  compiler/rustc_mir/src/interpret/machine.rs
  compiler/rustc_mir/src/interpret/terminator.rs
  compiler/rustc_mir/src/transform/const_prop.rs
  compiler/rustc_typeck/src/check/check.rs
  src/doc/unstable-book/src/compiler-flags/source-based-code-coverage.md
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc-crate/auxiliary/self.rs
  src/test/rustdoc/intra-doc-crate/self.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
  src/test/ui/abi/issues/issue-22565-rust-call.rs
  src/test/ui/abi/issues/issue-22565-rust-call.stderr
  src/test/ui/overloaded-calls-nontuple.rs
  src/test/ui/overloaded-calls-nontuple.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80809 Use standard formatting for "rust-call" ABI message
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/abi/issues/issue-22565-rust-call.rs
  src/test/ui/abi/issues/issue-22565-rust-call.stderr
  src/test/ui/overloaded-calls-nontuple.rs
  src/test/ui/overloaded-calls-nontuple.stderr
Labels: A-diagnostics, D-inconsistent, S-waiting-on-bors

#80889 Do not query the HIR directly in `opt_associated_item`.
  compiler/rustc_middle/src/ty/mod.rs
Labels: A-incr-comp, I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#75490 Add `[T; N]::each_ref` and `[T; N]::each_mut`
  library/core/src/array/mod.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#79012 rustc_span: add span_data_to_lines_and_cols to caching source map view
  compiler/rustc_middle/src/ich/hcx.rs
  compiler/rustc_span/src/caching_source_map_view.rs
  compiler/rustc_span/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#80864 std/core docs: fix wrong link in PartialEq
  library/core/src/cmp.rs
Labels: A-intra-doc-links, S-waiting-on-bors

#80870 resolve: Simplify built-in macro table
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
Labels: S-waiting-on-bors

#80885 rustdoc: Resolve `&str` as `str`
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
Labels: A-intra-doc-links, C-enhancement, S-waiting-on-bors, T-rustdoc

#80904 Fix small typo
  compiler/rustc_passes/src/intrinsicck.rs
Labels: S-waiting-on-bors

#80923 Merge different function exits
  compiler/rustc_middle/src/hir/map/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#80928 Rollup of 9 pull requests
  compiler/rustc_builtin_macros/src/lib.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  compiler/rustc_passes/src/intrinsicck.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_resolve/src/macros.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_target/src/abi/call/mod.rs
  compiler/rustc_target/src/abi/mod.rs
  compiler/rustc_target/src/spec/crt_objects.rs
  compiler/rustc_target/src/spec/mod.rs
  library/core/src/cmp.rs
  src/bootstrap/compile.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
  src/test/ui/codemap_tests/tab_3.stderr
  src/test/ui/issues/issue-34721.stderr
  src/test/ui/issues/issue-61108.stderr
  src/test/ui/issues/issue-64559.stderr
  src/test/ui/moves/move-fn-self-receiver.rs
  src/test/ui/moves/move-fn-self-receiver.stderr
  src/test/ui/moves/moves-based-on-type-access-to-field.stderr
  src/test/ui/moves/moves-based-on-type-exprs.stderr
  src/test/ui/suggestions/borrow-for-loop-head.stderr
  src/test/ui/unsized-locals/borrow-after-move.stderr
  src/test/ui/unsized-locals/double-move.stderr
  src/test/ui/use/use-after-move-self-based-on-type.stderr
  src/test/ui/use/use-after-move-self.stderr
  src/test/ui/walk-struct-literal-with.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#79997 Emit a reactor for cdylib target on wasi
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_interface/src/tests.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_target/src/spec/crt_objects.rs
  compiler/rustc_target/src/spec/mod.rs
  src/bootstrap/compile.rs
Labels: S-waiting-on-bors

#79998 Use correct ABI for wasm32 by default
  compiler/rustc_target/src/abi/call/mod.rs
Labels: S-waiting-on-bors, T-compiler

#80042 Split a func into cold/hot parts, reducing binary size
  compiler/rustc_target/src/abi/mod.rs
Labels: I-heavy, S-waiting-on-bors, T-compiler

#80324 Explain method-call move errors in loops
  compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
  src/test/ui/codemap_tests/tab_3.stderr
  src/test/ui/issues/issue-34721.stderr
  src/test/ui/issues/issue-61108.stderr
  src/test/ui/issues/issue-64559.stderr
  src/test/ui/moves/move-fn-self-receiver.rs
  src/test/ui/moves/move-fn-self-receiver.stderr
  src/test/ui/moves/moves-based-on-type-access-to-field.stderr
  src/test/ui/moves/moves-based-on-type-exprs.stderr
  src/test/ui/suggestions/borrow-for-loop-head.stderr
  src/test/ui/unsized-locals/borrow-after-move.stderr
  src/test/ui/unsized-locals/double-move.stderr
  src/test/ui/use/use-after-move-self-based-on-type.stderr
  src/test/ui/use/use-after-move-self.stderr
  src/test/ui/walk-struct-literal-with.stderr
Labels: A-diagnostics, S-waiting-on-bors

#76580 Suggest async {} for async || {}
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_parse/src/parser/expr.rs
  src/test/ui/async-await/feature-async-closure.stderr
  src/test/ui/parser/block-no-opening-brace.rs
  src/test/ui/parser/block-no-opening-brace.stderr
Labels: A-diagnostics, A-suggestion-diagnostics, S-waiting-on-bors, T-compiler, merged-by-bors

#80463 Serialize incr comp structures to file via fixed-size buffer
  compiler/rustc_data_structures/src/fingerprint.rs
  compiler/rustc_incremental/src/persist/file_format.rs
  compiler/rustc_incremental/src/persist/save.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/ty/codec.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_serialize/src/leb128.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_serialize/src/opaque.rs
  compiler/rustc_serialize/tests/leb128.rs
Labels: A-incr-comp, I-compilemem, I-compiletime, S-waiting-on-bors, T-compiler, merged-by-bors

#80939 Rollup of 8 pull requests
  Cargo.lock
  compiler/rustc_driver/Cargo.toml
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_errors/src/emitter.rs
  compiler/rustc_errors/src/styled_buffer.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_typeck/src/check/compare_method.rs
  library/alloc/src/collections/vec_deque/tests.rs
  library/core/src/mem/maybe_uninit.rs
  library/core/src/slice/mod.rs
  library/core/tests/lib.rs
  library/core/tests/mem.rs
  src/test/ui/drop/auxiliary/issue-10028.rs
  src/test/ui/drop/issue-10028.rs
  src/test/ui/extern/issue-10025.rs
  src/test/ui/issues/auxiliary/issue-10031-aux.rs
  src/test/ui/issues/issue-10031.rs
  src/test/ui/issues/issue-13033.stderr
  src/test/ui/mismatched_types/E0053.stderr
  src/test/ui/mismatched_types/trait-impl-fn-incompatibility.stderr
  src/test/ui/never_type/issue-10176.rs
  src/test/ui/never_type/issue-10176.stderr
  src/test/ui/resolve/issue-10200.rs
  src/test/ui/resolve/issue-10200.stderr
  src/test/ui/terminal-width/tabs-trimming.rs
  src/test/ui/terminal-width/tabs-trimming.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#80880 Move some tests to more reasonable directories
  src/test/ui/drop/auxiliary/issue-10028.rs
  src/test/ui/drop/issue-10028.rs
  src/test/ui/extern/issue-10025.rs
  src/test/ui/issues/auxiliary/issue-10031-aux.rs
  src/test/ui/issues/issue-10031.rs
  src/test/ui/never_type/issue-10176.rs
  src/test/ui/never_type/issue-10176.stderr
  src/test/ui/resolve/issue-10200.rs
  src/test/ui/resolve/issue-10200.stderr
Labels: S-waiting-on-bors

#80897 driver: Use `atty` instead of rolling our own
  Cargo.lock
  compiler/rustc_driver/Cargo.toml
  compiler/rustc_driver/src/lib.rs
Labels: A-driver, C-cleanup, S-waiting-on-bors, T-compiler

#80898 Add another test case for #79808
  library/alloc/src/collections/vec_deque/tests.rs
Labels: S-waiting-on-bors

#80917 core/slice: remove doc comment about scoped borrow
  library/core/src/slice/mod.rs
Labels: S-waiting-on-bors

#80927 Replace a simple `if let` with the `matches` macro
  compiler/rustc_resolve/src/late.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#80930 fix typo in trait method mutability mismatch help
  compiler/rustc_typeck/src/check/compare_method.rs
  src/test/ui/issues/issue-13033.stderr
  src/test/ui/mismatched_types/E0053.stderr
  src/test/ui/mismatched_types/trait-impl-fn-incompatibility.stderr
Labels: S-waiting-on-bors

#80600 Add `MaybeUninit` method `array_assume_init`
  library/core/src/mem/maybe_uninit.rs
  library/core/tests/lib.rs
  library/core/tests/mem.rs
Labels: S-waiting-on-bors
