Repository rust-lang/rust, pull requests merged in 2021-06, with the labels that each got.

#85153 Reduce the amount of untracked state in TyCtxt
  Cargo.lock
  compiler/rustc_ast/src/expand/allocator.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_codegen_cranelift/src/allocator.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/metadata.rs
  compiler/rustc_codegen_llvm/Cargo.toml
  compiler/rustc_codegen_llvm/src/base.rs
  compiler/rustc_codegen_ssa/src/back/symbol_export.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_data_structures/src/stable_hasher.rs
  compiler/rustc_hir/src/arena.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_metadata/src/lib.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/middle/exported_symbols.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_mir/src/interpret/intrinsics/type_name.rs
  compiler/rustc_passes/src/entry.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_query_impl/src/profiling_support.rs
  compiler/rustc_query_impl/src/stats.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_symbol_mangling/src/legacy.rs
  compiler/rustc_symbol_mangling/src/v0.rs
  compiler/rustc_trait_selection/src/autoderef.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_ty_utils/src/ty.rs
  compiler/rustc_typeck/src/check_unused.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/visit_ast.rs
  src/test/incremental/hashes/extern_mods.rs
  src/test/incremental/hashes/inherent_impls.rs
  src/test/incremental/hashes/type_defs.rs
Labels: S-waiting-on-bors, merged-by-bors

#85859 Add title for copy to clipboard button in rustdoc
  src/librustdoc/html/render/print_item.rs
Labels: S-waiting-on-bors, merged-by-bors

#85884 Revert "Reduce the amount of untracked state in TyCtxt"
  Cargo.lock
  compiler/rustc_ast/src/expand/allocator.rs
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_codegen_cranelift/src/allocator.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/metadata.rs
  compiler/rustc_codegen_llvm/Cargo.toml
  compiler/rustc_codegen_llvm/src/base.rs
  compiler/rustc_codegen_ssa/src/back/symbol_export.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_data_structures/src/stable_hasher.rs
  compiler/rustc_hir/src/arena.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_metadata/src/lib.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/hir/map/mod.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/middle/exported_symbols.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
  compiler/rustc_mir/src/interpret/intrinsics/type_name.rs
  compiler/rustc_passes/src/entry.rs
  compiler/rustc_privacy/src/lib.rs
  compiler/rustc_query_impl/src/profiling_support.rs
  compiler/rustc_query_impl/src/stats.rs
  compiler/rustc_resolve/src/lib.rs
  compiler/rustc_symbol_mangling/src/legacy.rs
  compiler/rustc_symbol_mangling/src/v0.rs
  compiler/rustc_trait_selection/src/autoderef.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_ty_utils/src/ty.rs
  compiler/rustc_typeck/src/check_unused.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/visit_ast.rs
  src/test/incremental/hashes/extern_mods.rs
  src/test/incremental/hashes/inherent_impls.rs
  src/test/incremental/hashes/type_defs.rs
Labels: S-waiting-on-bors, merged-by-bors

#85886 Rollup of 4 pull requests
  compiler/rustc_session/src/options.rs
  library/core/src/option.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/static/rustdoc.css
  src/test/rustdoc/assoc-consts.rs
  src/test/rustdoc/inline_cross/assoc-items.rs
  src/test/rustdoc/inline_cross/impl-inline-without-trait.rs
  src/test/rustdoc/manual_impl.rs
  src/test/rustdoc/toggle-item-contents.rs
  src/test/rustdoc/toggle-method.rs
  src/test/rustdoc/toggle-trait-fn.rs
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85622 Remove toggle for "undocumented items."
  src/librustdoc/html/render/mod.rs
  src/test/rustdoc/assoc-consts.rs
  src/test/rustdoc/inline_cross/assoc-items.rs
  src/test/rustdoc/inline_cross/impl-inline-without-trait.rs
  src/test/rustdoc/manual_impl.rs
  src/test/rustdoc/toggle-item-contents.rs
  src/test/rustdoc/toggle-method.rs
  src/test/rustdoc/toggle-trait-fn.rs
Labels: S-waiting-on-bors

#85826 Mention "null pointer optimization" in option docs.
  library/core/src/option.rs
Labels: S-waiting-on-bors

#85860 Fix details rustdoc toggle for blanket impl
  src/librustdoc/html/static/rustdoc.css
Labels: S-waiting-on-bors

#85473 fix split-debuginfo error message
  compiler/rustc_session/src/options.rs
Labels: S-waiting-on-bors

#85331 Make rustc_dirty/clean annotations exhaustive by default
  compiler/rustc_feature/src/builtin_attrs.rs
  compiler/rustc_incremental/src/persist/dirty_clean.rs
  src/test/incremental/add_private_fn_at_krate_root_cc/struct_point.rs
  src/test/incremental/callee_caller_cross_crate/b.rs
  src/test/incremental/change_add_field/struct_point.rs
  src/test/incremental/change_private_fn/struct_point.rs
  src/test/incremental/change_private_fn_cc/struct_point.rs
  src/test/incremental/change_private_impl_method/struct_point.rs
  src/test/incremental/change_private_impl_method_cc/struct_point.rs
  src/test/incremental/change_pub_inherent_method_body/struct_point.rs
  src/test/incremental/change_pub_inherent_method_sig/struct_point.rs
  src/test/incremental/crate_hash_reorder.rs
  src/test/incremental/dirty_clean.rs
  src/test/incremental/hashes/call_expressions.rs
  src/test/incremental/hashes/enum_defs.rs
  src/test/incremental/hashes/extern_mods.rs
  src/test/incremental/hashes/indexing_expressions.rs
  src/test/incremental/hashes/inherent_impls.rs
  src/test/incremental/hashes/struct_defs.rs
  src/test/incremental/hashes/trait_defs.rs
  src/test/incremental/hashes/trait_impls.rs
  src/test/incremental/hello_world.rs
  src/test/incremental/hygiene/auxiliary/cached_hygiene.rs
  src/test/incremental/ich_method_call_trait_scope.rs
  src/test/incremental/ich_nested_items.rs
  src/test/incremental/ich_resolve_results.rs
  src/test/incremental/rlib_cross_crate/b.rs
  src/test/incremental/source_loc_macros.rs
  src/test/incremental/span_hash_stable/auxiliary/sub1.rs
  src/test/incremental/span_hash_stable/auxiliary/sub2.rs
  src/test/incremental/spans_significant_w_debuginfo.rs
  src/test/incremental/spans_significant_w_panic.rs
  src/test/incremental/string_constant.rs
  src/test/incremental/struct_add_field.rs
  src/test/incremental/struct_change_field_name.rs
  src/test/incremental/struct_change_field_type.rs
  src/test/incremental/struct_change_field_type_cross_crate/b.rs
  src/test/incremental/struct_change_nothing.rs
  src/test/incremental/struct_remove_field.rs
  src/test/incremental/type_alias_cross_crate/b.rs
  src/test/incremental/unchecked_dirty_clean.rs
  src/test/ui/dep-graph/dep-graph-check-attr.rs
  src/test/ui/dep-graph/dep-graph-check-attr.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85687 New prelude
  library/core/src/prelude/mod.rs
  library/std/src/prelude/mod.rs
  src/test/ui/prelude2021.rs
Labels: S-waiting-on-bors, T-libs, merged-by-bors

#85905 Only compute the trait map once
  compiler/rustc_ast_lowering/src/lib.rs
  compiler/rustc_data_structures/src/stable_hasher.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/query/mod.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_resolve/src/lib.rs
Labels: S-waiting-on-bors, merged-by-bors

#85908 Make is_private_dep a query.
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
Labels: S-waiting-on-bors, merged-by-bors

#85892 Miscellaneous inlining improvements
  compiler/rustc_codegen_llvm/src/builder.rs
  compiler/rustc_codegen_llvm/src/context.rs
  compiler/rustc_data_structures/src/tagged_ptr.rs
  compiler/rustc_errors/src/lib.rs
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_hir/src/hir.rs
  compiler/rustc_middle/src/infer/canonical.rs
  compiler/rustc_middle/src/mir/interpret/mod.rs
  compiler/rustc_middle/src/mir/mod.rs
  compiler/rustc_middle/src/mir/mono.rs
  compiler/rustc_middle/src/ty/generics.rs
  compiler/rustc_middle/src/ty/list.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_session/src/session.rs
  compiler/rustc_span/src/def_id.rs
  compiler/rustc_target/src/abi/mod.rs
  compiler/rustc_target/src/spec/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#85337 Avoid creating anonymous nodes with zero or one dependency.
  compiler/rustc_incremental/src/persist/save.rs
  compiler/rustc_query_system/src/dep_graph/graph.rs
Labels: S-waiting-on-bors, merged-by-bors

#85904 Restrict access to crate_name.
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  compiler/rustc_lint/src/context.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/dep_graph/dep_node.rs
  compiler/rustc_middle/src/middle/exported_symbols.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/print/pretty.rs
  compiler/rustc_mir/src/interpret/intrinsics/type_name.rs
  compiler/rustc_query_impl/src/profiling_support.rs
  compiler/rustc_symbol_mangling/src/legacy.rs
  compiler/rustc_symbol_mangling/src/v0.rs
  compiler/rustc_trait_selection/src/autoderef.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
  compiler/rustc_ty_utils/src/ty.rs
  src/librustdoc/clean/inline.rs
  src/librustdoc/visit_ast.rs
Labels: S-waiting-on-bors, merged-by-bors

#84834 Sidebar unification
  src/librustdoc/clean/types.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/context.rs
  src/librustdoc/html/render/mod.rs
  src/librustdoc/html/render/print_item.rs
  src/librustdoc/html/render/write_shared.rs
  src/librustdoc/html/static/main.js
  src/librustdoc/html/static/rustdoc.css
  src/librustdoc/html/static/sidebar-items.js
  src/librustdoc/html/static_files.rs
  src/test/rustdoc-gui/sidebar.goml
  src/test/rustdoc-gui/src/lib2.rs
  src/test/rustdoc/keyword.rs
  src/tools/rustdoc-gui/tester.js
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors, merged-by-bors

#84988 rustc: Allow safe #[target_feature] on wasm
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_mir_build/src/check_unsafety.rs
  compiler/rustc_typeck/src/collect.rs
  src/test/ui/target-feature/wasm-safe.rs
Labels: I-nominated, S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors, to-announce

#85877 Intra doc link-ify a reference to a function
  library/core/src/num/f32.rs
  library/core/src/num/f64.rs
Labels: S-waiting-on-bors

#85880 convert assertion on rvalue::threadlocalref to delay bug
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  src/test/ui/thread-local-static.rs
  src/test/ui/thread-local-static.stderr
Labels: S-waiting-on-bors

#85896 Add test for forward declared const param defaults
  compiler/rustc_resolve/src/diagnostics.rs
  compiler/rustc_resolve/src/lib.rs
  src/test/ui/const-generics/defaults/forward-declared.rs
  src/test/ui/const-generics/defaults/forward-declared.stderr
Labels: S-waiting-on-bors

#85897 Update I-unsound label for triagebot
  triagebot.toml
Labels: S-waiting-on-bors

#85900 Use pattern matching instead of checking lengths explicitly
  compiler/rustc_lint/src/types.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#85911 Avoid a clone of output_filenames.
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_middle/src/ty/context.rs
Labels: S-waiting-on-bors

#85934 Add `Ty::is_union` predicate
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_mir/src/borrow_check/mod.rs
  compiler/rustc_mir/src/borrow_check/places_conflict.rs
  compiler/rustc_mir/src/dataflow/move_paths/builder.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_mir/src/transform/check_unsafety.rs
  compiler/rustc_mir/src/transform/dest_prop.rs
  compiler/rustc_mir/src/transform/promote_consts.rs
  compiler/rustc_mir/src/transform/remove_zsts.rs
  compiler/rustc_typeck/src/check/place_op.rs
Labels: S-waiting-on-bors

#85935 Validate type of locals used as indices
  compiler/rustc_mir/src/transform/validate.rs
Labels: S-waiting-on-bors

#85706 Turn off frame pointer elimination on all Apple platforms.
  compiler/rustc_target/src/spec/aarch64_apple_ios.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_macabi.rs
  compiler/rustc_target/src/spec/aarch64_apple_ios_sim.rs
  compiler/rustc_target/src/spec/aarch64_apple_tvos.rs
  compiler/rustc_target/src/spec/apple_base.rs
  compiler/rustc_target/src/spec/apple_sdk_base.rs
Labels: S-waiting-on-bors

#85724 Fix issue 85435 by restricting Fake Read precision
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  compiler/rustc_typeck/src/check/upvar.rs
Labels: S-waiting-on-bors

#85852 Clarify meaning of MachineApplicable suggestions.
  compiler/rustc_lint_defs/src/lib.rs
Labels: S-waiting-on-bors

#83362 Stabilize `vecdeque_binary_search`
  library/alloc/src/collections/vec_deque/mod.rs
  library/alloc/tests/lib.rs
Labels: A-collections, S-waiting-on-bors, T-libs, needs-fcp, relnotes

#85292 Improve debugging experience for enums on windows-msvc
  compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs
  src/etc/natvis/intrinsic.natvis
  src/etc/natvis/libcore.natvis
  src/test/codegen/async-fn-debug-msvc.rs
  src/test/codegen/generator-debug-msvc.rs
  src/test/debuginfo/msvc-pretty-enums.rs
  src/test/debuginfo/pretty-std.rs
Labels: A-debuginfo, O-windows-msvc, S-waiting-on-bors, merged-by-bors

#85617 shrinking the deprecated method span
  compiler/rustc_passes/src/stability.rs
  src/test/ui/deprecation/deprecation-lint.stderr
  src/test/ui/deprecation/suggestion.fixed
  src/test/ui/deprecation/suggestion.rs
  src/test/ui/deprecation/suggestion.stderr
  src/test/ui/lint/lint-stability-deprecated.stderr
  src/test/ui/stability-attribute/generics-default-stability.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85867 Remove unnecessary SpecFromIter impls
  library/alloc/src/vec/spec_from_iter.rs
Labels: S-waiting-on-bors, merged-by-bors

#85850 Remove unused feature gates
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_ast_passes/src/lib.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_data_structures/src/obligation_forest/mod.rs
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_hir/src/lib.rs
  compiler/rustc_index/src/lib.rs
  compiler/rustc_index/src/vec.rs
  compiler/rustc_infer/src/lib.rs
  compiler/rustc_interface/src/lib.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_metadata/src/lib.rs
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir_build/src/lib.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_passes/src/lib.rs
  compiler/rustc_query_impl/src/lib.rs
  compiler/rustc_query_system/src/lib.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_target/src/lib.rs
  compiler/rustc_type_ir/src/lib.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#85888 Fix typo in internal documentation for `TrustedRandomAccess`
  library/core/src/iter/adapters/zip.rs
Labels: S-waiting-on-bors

#85889 Restoring the `num_def_ids` function in the CStore API
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
Labels: S-waiting-on-bors, T-compiler

#85899 jsondocck small cleanup
  Cargo.lock
  src/tools/jsondocck/Cargo.toml
  src/tools/jsondocck/src/main.rs
Labels: S-waiting-on-bors

#85937 Fix bad suggestions for code from proc_macro
  compiler/rustc_typeck/src/check/demand.rs
  src/test/ui/suggestions/auxiliary/proc-macro-type-error.rs
  src/test/ui/suggestions/suggest-ref-macro.rs
  src/test/ui/suggestions/suggest-ref-macro.stderr
Labels: A-suggestion-diagnostics, S-waiting-on-bors, T-compiler

#85963 Show `::{{constructor}}` in std::any::type_name().
  compiler/rustc_mir/src/interpret/intrinsics/type_name.rs
  library/core/tests/any.rs
Labels: S-waiting-on-bors

#85977 Fix linkcheck script from getting out of sync.
  src/tools/linkchecker/linkcheck.sh
Labels: S-waiting-on-bors

#85984 Rollup of 8 pull requests
  Cargo.lock
  compiler/rustc_ast/src/lib.rs
  compiler/rustc_ast_passes/src/lib.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_data_structures/src/obligation_forest/mod.rs
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_hir/src/lib.rs
  compiler/rustc_index/src/lib.rs
  compiler/rustc_index/src/vec.rs
  compiler/rustc_infer/src/lib.rs
  compiler/rustc_interface/src/lib.rs
  compiler/rustc_lint/src/lib.rs
  compiler/rustc_metadata/src/lib.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_middle/src/lib.rs
  compiler/rustc_mir/src/interpret/intrinsics/type_name.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_mir_build/src/lib.rs
  compiler/rustc_parse/src/lib.rs
  compiler/rustc_passes/src/lib.rs
  compiler/rustc_query_impl/src/lib.rs
  compiler/rustc_query_system/src/lib.rs
  compiler/rustc_serialize/src/lib.rs
  compiler/rustc_span/src/lib.rs
  compiler/rustc_target/src/lib.rs
  compiler/rustc_type_ir/src/lib.rs
  compiler/rustc_typeck/src/check/demand.rs
  library/alloc/src/vec/cow.rs
  library/core/src/iter/adapters/zip.rs
  library/core/tests/any.rs
  src/test/ui/suggestions/auxiliary/proc-macro-type-error.rs
  src/test/ui/suggestions/suggest-ref-macro.rs
  src/test/ui/suggestions/suggest-ref-macro.stderr
  src/tools/jsondocck/Cargo.toml
  src/tools/jsondocck/src/main.rs
  src/tools/linkchecker/linkcheck.sh
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85717 Document `From` impls for cow.rs
  library/alloc/src/vec/cow.rs
Labels: S-waiting-on-bors

#85959 fix testing Miri with --stage 0
  src/bootstrap/builder.rs
  src/bootstrap/test.rs
  src/bootstrap/util.rs
Labels: S-waiting-on-bors, merged-by-bors

#85385 Reland - Report coverage `0` of dead blocks
  compiler/rustc_codegen_ssa/src/coverageinfo/map.rs
  compiler/rustc_mir/src/transform/const_goto.rs
  compiler/rustc_mir/src/transform/deduplicate_blocks.rs
  compiler/rustc_mir/src/transform/early_otherwise_branch.rs
  compiler/rustc_mir/src/transform/generator.rs
  compiler/rustc_mir/src/transform/inline.rs
  compiler/rustc_mir/src/transform/match_branches.rs
  compiler/rustc_mir/src/transform/multiple_return_terminators.rs
  compiler/rustc_mir/src/transform/remove_unneeded_drops.rs
  compiler/rustc_mir/src/transform/simplify.rs
  compiler/rustc_mir/src/transform/simplify_try.rs
  compiler/rustc_mir/src/transform/unreachable_prop.rs
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.async2.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.conditions.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.doctest.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.drop_trait.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.generator.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.generics.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.loops_branches.txt
  src/test/run-make-fulldeps/coverage-reports/expected_show_coverage.tight_inf_loop.txt
  src/test/run-make-fulldeps/coverage/conditions.rs
  src/test/run-make-fulldeps/coverage/generator.rs
  src/test/run-make-fulldeps/coverage/generics.rs
  src/test/run-make-fulldeps/coverage/loops_branches.rs
Labels: S-waiting-on-bors, merged-by-bors

#85788 Support for force-warns
  compiler/rustc_lint/src/context.rs
  compiler/rustc_lint/src/levels.rs
  compiler/rustc_middle/src/lint.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  src/doc/unstable-book/src/compiler-flags/force-warns.md
  src/librustdoc/config.rs
  src/librustdoc/lib.rs
  src/test/run-make/unstable-flag-required/Makefile
  src/test/run-make/unstable-flag-required/force-warns.stderr
  src/test/ui/lint/force-warn/force-allowed-by-default-lint.rs
  src/test/ui/lint/force-warn/force-allowed-by-default-lint.stderr
  src/test/ui/lint/force-warn/force-allowed-deny-by-default-lint.rs
  src/test/ui/lint/force-warn/force-allowed-deny-by-default-lint.stderr
  src/test/ui/lint/force-warn/force-allowed-warning.rs
  src/test/ui/lint/force-warn/force-allowed-warning.stderr
  src/test/ui/lint/force-warn/force-deny-by-default-lint.rs
  src/test/ui/lint/force-warn/force-deny-by-default-lint.stderr
  src/test/ui/lint/force-warn/force-lint-allow-all-warnings.rs
  src/test/ui/lint/force-warn/force-lint-allow-all-warnings.stderr
  src/test/ui/lint/force-warn/force-lint-group-allow-all-warnings.rs
  src/test/ui/lint/force-warn/force-lint-group-allow-all-warnings.stderr
  src/test/ui/lint/force-warn/force-lint-in-allowed-group.rs
  src/test/ui/lint/force-warn/force-lint-in-allowed-group.stderr
  src/test/ui/lint/force-warn/force-warn-group-allow-warning.rs
  src/test/ui/lint/force-warn/force-warn-group-allow-warning.stderr
  src/test/ui/lint/force-warn/force-warn-group.rs
  src/test/ui/lint/force-warn/force-warn-group.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85806 Support Android ndk versions `r23-beta3` and up
  Cargo.lock
  library/std/Cargo.toml
  library/std/src/sys/unix/mod.rs
  library/unwind/build.rs
Labels: S-waiting-on-bors, merged-by-bors

#84449 rustc: Store metadata-in-rlibs in object files
  Cargo.lock
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_llvm/src/llvm/mod.rs
  compiler/rustc_codegen_ssa/Cargo.toml
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/metadata.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
Labels: S-waiting-on-bors, merged-by-bors

#85966 wasm: Make simd types passed via indirection again
  compiler/rustc_target/src/spec/wasm_base.rs
  src/test/ui/simd/wasm-simd-indirect.rs
Labels: S-waiting-on-bors

#85979 don't suggest unsized indirection in where-clauses
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  src/test/ui/suggestions/issue-85943-no-suggest-unsized-indirection-in-where-clause.rs
  src/test/ui/suggestions/issue-85943-no-suggest-unsized-indirection-in-where-clause.stderr
Labels: S-waiting-on-bors

#85983 Update to semver 1.0.3
  Cargo.lock
Labels: S-waiting-on-bors

#85988 Note that `ninja = false` goes under `[llvm]`
  src/bootstrap/lib.rs
Labels: S-waiting-on-bors

#86006 Rollup of 10 pull requests
  Cargo.lock
  compiler/rustc_data_structures/src/sync.rs
  compiler/rustc_lint/src/types.rs
  compiler/rustc_target/src/spec/wasm_base.rs
  compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs
  compiler/rustc_typeck/src/check/demand.rs
  library/alloc/src/lib.rs
  library/core/src/lib.rs
  library/panic_abort/src/lib.rs
  library/panic_unwind/src/lib.rs
  library/proc_macro/src/lib.rs
  library/std/src/lib.rs
  library/term/src/lib.rs
  library/test/src/lib.rs
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/lib.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/etc/htmldocck.py
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/html/format.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/lib.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
  src/test/rustdoc-ui/check.rs
  src/test/rustdoc-ui/check.stderr
  src/test/rustdoc-ui/intra-doc/email-address-localhost.rs
  src/test/rustdoc-ui/intra-doc/email-address-localhost.stderr
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.rs
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.stderr
  src/test/rustdoc-ui/no-crate-level-doc-lint.rs
  src/test/rustdoc-ui/no-crate-level-doc-lint.stderr
  src/test/rustdoc/intra-doc/associated-items.rs
  src/test/rustdoc/intra-doc/builtin-macros.rs
  src/test/rustdoc/intra-doc/field.rs
  src/test/rustdoc/intra-doc/generic-params.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
  src/test/rustdoc/intra-doc/prim-assoc.rs
  src/test/rustdoc/intra-doc/prim-methods-external-core.rs
  src/test/rustdoc/intra-doc/prim-methods-local.rs
  src/test/rustdoc/intra-doc/prim-methods.rs
  src/test/rustdoc/intra-doc/prim-precedence.rs
  src/test/rustdoc/intra-doc/primitive-disambiguators.rs
  src/test/rustdoc/intra-doc/primitive-non-default-impl.rs
  src/test/rustdoc/intra-doc/pub-use.rs
  src/test/rustdoc/intra-doc/trait-item.rs
  src/test/rustdoc/intra-doc/true-false.rs
  src/test/rustdoc/intra-link-prim-self.rs
  src/test/rustdoc/primitive-link.rs
  src/test/rustdoc/primitive-reexport.rs
  src/test/ui/lint/lint-ctypes-fn.rs
  src/test/ui/lint/lint-ctypes-fn.stderr
  src/test/ui/simd/wasm-simd-indirect.rs
  src/test/ui/suggestions/format-borrow.rs
  src/test/ui/suggestions/format-borrow.stderr
  src/test/ui/suggestions/issue-85943-no-suggest-unsized-indirection-in-where-clause.rs
  src/test/ui/suggestions/issue-85943-no-suggest-unsized-indirection-in-where-clause.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85853 Warn against boxed DST in `improper_ctypes_definitions` lint
  compiler/rustc_lint/src/types.rs
  src/test/ui/lint/lint-ctypes-fn.rs
  src/test/ui/lint/lint-ctypes-fn.stderr
Labels: S-waiting-on-bors

#85939 Fix suggestion for removing &mut from &mut macro!().
  compiler/rustc_typeck/src/check/demand.rs
  src/test/ui/suggestions/format-borrow.rs
  src/test/ui/suggestions/format-borrow.stderr
Labels: S-waiting-on-bors

#83653 Remove unused code from `rustc_data_structures::sync`
  compiler/rustc_data_structures/src/sync.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#84466 rustdoc: Remove `PrimitiveType::{to_url_str, as_str}`
  src/librustdoc/clean/types.rs
  src/librustdoc/html/format.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/passes/collect_intra_doc_links.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors

#84880 Make match in `register_res` easier to read
  src/librustdoc/clean/utils.rs
  src/test/rustdoc/intra-doc/field.rs
Labels: A-rustdoc, C-cleanup, S-waiting-on-bors

#84942 rustdoc: link to stable/beta docs consistently in documentation
  library/alloc/src/lib.rs
  library/core/src/lib.rs
  library/panic_abort/src/lib.rs
  library/panic_unwind/src/lib.rs
  library/proc_macro/src/lib.rs
  library/std/src/lib.rs
  library/term/src/lib.rs
  library/test/src/lib.rs
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/test.rs
  src/bootstrap/tool.rs
  src/etc/htmldocck.py
  src/librustdoc/clean/types.rs
  src/librustdoc/clean/utils.rs
  src/librustdoc/lib.rs
  src/test/rustdoc-ui/check.rs
  src/test/rustdoc-ui/check.stderr
  src/test/rustdoc-ui/intra-doc/email-address-localhost.rs
  src/test/rustdoc-ui/intra-doc/email-address-localhost.stderr
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.rs
  src/test/rustdoc-ui/intra-doc/unknown-disambiguator.stderr
  src/test/rustdoc-ui/no-crate-level-doc-lint.rs
  src/test/rustdoc-ui/no-crate-level-doc-lint.stderr
  src/test/rustdoc/intra-doc/associated-items.rs
  src/test/rustdoc/intra-doc/builtin-macros.rs
  src/test/rustdoc/intra-doc/generic-params.rs
  src/test/rustdoc/intra-doc/non-path-primitives.rs
  src/test/rustdoc/intra-doc/prim-assoc.rs
  src/test/rustdoc/intra-doc/prim-methods-external-core.rs
  src/test/rustdoc/intra-doc/prim-methods-local.rs
  src/test/rustdoc/intra-doc/prim-methods.rs
  src/test/rustdoc/intra-doc/prim-precedence.rs
  src/test/rustdoc/intra-doc/primitive-disambiguators.rs
  src/test/rustdoc/intra-doc/primitive-non-default-impl.rs
  src/test/rustdoc/intra-doc/pub-use.rs
  src/test/rustdoc/intra-doc/trait-item.rs
  src/test/rustdoc/intra-doc/true-false.rs
  src/test/rustdoc/intra-link-prim-self.rs
  src/test/rustdoc/primitive-link.rs
  src/test/rustdoc/primitive-reexport.rs
Labels: A-rustdoc, S-waiting-on-bors, T-libs

#84234 Implement DepTrackingHash for `Option` through blanket impls instead of macros
  compiler/rustc_session/src/config.rs
Labels: A-incr-comp, S-waiting-on-bors, T-compiler, merged-by-bors

#85457 Remove `doc(include)`
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_expand/src/base.rs
  compiler/rustc_expand/src/expand.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_feature/src/removed.rs
  compiler/rustc_lint/src/builtin.rs
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_save_analysis/src/lib.rs
  library/core/src/lib.rs
  src/doc/rustdoc/src/documentation-tests.md
  src/doc/rustdoc/src/unstable-features.md
  src/doc/unstable-book/src/language-features/external-doc.md
  src/librustdoc/clean/types.rs
  src/test/run-make-fulldeps/include_bytes_deps/main.rs
  src/test/run-make-fulldeps/save-analysis/foo.rs
  src/test/rustdoc-ui/doc-include-suggestion.rs
  src/test/rustdoc-ui/doc-include-suggestion.stderr
  src/test/rustdoc/auxiliary/external-cross-doc.md
  src/test/rustdoc/auxiliary/external-cross.rs
  src/test/rustdoc/auxiliary/external-doc.md
  src/test/rustdoc/external-doc.rs
  src/test/rustdoc/unindent.rs
  src/test/ui/extern/external-doc-error.rs
  src/test/ui/extern/external-doc-error.stderr
  src/test/ui/feature-gates/feature-gate-external_doc.rs
  src/test/ui/feature-gates/feature-gate-external_doc.stderr
  src/tools/clippy/clippy_lints/src/missing_doc.rs
  src/tools/clippy/tests/ui/missing-doc-crate.rs
Labels: S-waiting-on-bors, T-rustdoc, merged-by-bors

#85919 Allow raw pointers in SIMD types
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_typeck/src/check/check.rs
  src/test/ui/simd/issue-85915-simd-ptrs.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-extern-nonnull-ptr.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-wide-ptr.rs
  src/test/ui/simd/simd-type-generic-monomorphisation-wide-ptr.stderr
  src/test/ui/simd/simd-type-wide-ptr.rs
  src/test/ui/simd/simd-type-wide-ptr.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86001 Revert "shrinking the deprecated method span"
  compiler/rustc_passes/src/stability.rs
  src/test/ui/deprecation/deprecation-lint.rs
  src/test/ui/deprecation/deprecation-lint.stderr
  src/test/ui/deprecation/suggestion.fixed
  src/test/ui/deprecation/suggestion.rs
  src/test/ui/deprecation/suggestion.stderr
  src/test/ui/lint/lint-stability-deprecated.stderr
  src/test/ui/stability-attribute/generics-default-stability.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85869 Remove special handling of `box_free` from `LocalAnalyzer`
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
Labels: S-waiting-on-bors, merged-by-bors

#86014 msp430 linker does not accept -znoexecstack. Set linker_is_gnu to fal…
  compiler/rustc_target/src/spec/msp430_none_elf.rs
Labels: S-waiting-on-bors

#86032 Rollup of 7 pull requests
  compiler/rustc_lint_defs/src/builtin.rs
  compiler/rustc_target/src/spec/msp430_none_elf.rs
  library/core/src/ops/range.rs
  library/std/src/path.rs
  library/std/src/time.rs
  src/librustdoc/core.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/print_item.rs
  src/test/rustdoc-ui/doc-spotlight.fixed
  src/test/rustdoc-ui/doc-spotlight.rs
  src/test/rustdoc-ui/doc-spotlight.stderr
  src/test/ui/rustdoc/deny-invalid-doc-attrs.rs
  src/test/ui/rustdoc/deny-invalid-doc-attrs.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85501 Fix `deny(invalid_doc_attributes)`
  compiler/rustc_lint_defs/src/builtin.rs
  src/librustdoc/core.rs
  src/test/rustdoc-ui/doc-spotlight.fixed
  src/test/rustdoc-ui/doc-spotlight.rs
  src/test/rustdoc-ui/doc-spotlight.stderr
  src/test/ui/rustdoc/deny-invalid-doc-attrs.rs
  src/test/ui/rustdoc/deny-invalid-doc-attrs.stderr
Labels: A-lint, A-rustdoc, S-waiting-on-bors

#85503 rustdoc: add tooltips to some buttons
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/print_item.rs
Labels: S-waiting-on-bors

#85710 Document `From` impls in path.rs
  library/std/src/path.rs
Labels: S-waiting-on-bors

#85760 Possible errors when accessing file metadata are platform specific
  library/std/src/path.rs
Labels: S-waiting-on-bors

#85974 td align attribute
  library/std/src/time.rs
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#83646 Add a map method to Bound
  library/core/src/ops/range.rs
Labels: S-waiting-on-bors, T-libs

#86002 Always go through the expn_that_defined query.
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_middle/src/hir/mod.rs
  compiler/rustc_middle/src/query/mod.rs
  compiler/rustc_middle/src/ty/mod.rs
Labels: S-waiting-on-bors, merged-by-bors

#84171 Partial support for raw-dylib linkage
  compiler/rustc_codegen_cranelift/src/archive.rs
  compiler/rustc_codegen_llvm/src/back/archive.rs
  compiler/rustc_codegen_llvm/src/llvm/ffi.rs
  compiler/rustc_codegen_ssa/src/back/archive.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp
  compiler/rustc_metadata/src/native_libs.rs
  compiler/rustc_middle/src/middle/cstore.rs
  src/test/run-make/raw-dylib/Makefile
  src/test/run-make/raw-dylib/driver.rs
  src/test/run-make/raw-dylib/extern_1.c
  src/test/run-make/raw-dylib/extern_2.c
  src/test/run-make/raw-dylib/lib.rs
  src/test/run-make/raw-dylib/output.txt
  src/test/ui/feature-gates/feature-gate-raw-dylib-2.rs
  src/test/ui/feature-gates/feature-gate-raw-dylib-2.stderr
  src/test/ui/feature-gates/feature-gate-raw-dylib-windows-gnu.rs
  src/test/ui/feature-gates/feature-gate-raw-dylib-windows-gnu.stderr
  src/test/ui/feature-gates/feature-gate-raw-dylib-windows-msvc.rs
  src/test/ui/feature-gates/feature-gate-raw-dylib-windows-msvc.stderr
  src/test/ui/manual/manual-link-unsupported-kind.rs
  src/test/ui/manual/manual-link-unsupported-kind.stderr
  src/test/ui/rfc-2627-raw-dylib/raw-dylib-msvc-only.rs
  src/test/ui/rfc-2627-raw-dylib/raw-dylib-msvc-only.stderr
  src/test/ui/rfc-2627-raw-dylib/raw-dylib-windows-only.rs
  src/test/ui/rfc-2627-raw-dylib/raw-dylib-windows-only.stderr
Labels: S-waiting-on-bors, merged-by-bors

#84863 Show test type during prints
  compiler/rustc_builtin_macros/src/test.rs
  library/test/src/formatters/pretty.rs
  library/test/src/formatters/terse.rs
  library/test/src/tests.rs
  library/test/src/types.rs
  src/librustdoc/doctest.rs
  src/test/rustdoc-ui/failed-doctest-compile-fail.stdout
  src/test/rustdoc-ui/failed-doctest-missing-codes.stdout
  src/test/rustdoc-ui/issue-80992.stdout
  src/test/rustdoc-ui/no-run-flag.stdout
  src/test/rustdoc-ui/test-type.rs
  src/test/rustdoc-ui/test-type.stdout
  src/test/ui/test-attrs/test-type.rs
  src/test/ui/test-attrs/test-type.run.stdout
  src/test/ui/test-panic-abort-nocapture.run.stdout
  src/test/ui/test-panic-abort.run.stdout
  src/tools/compiletest/src/main.rs
  src/tools/compiletest/src/runtest.rs
Labels: A-libtest, S-waiting-on-bors, T-libs, disposition-merge, finished-final-comment-period, merged-by-bors, needs-fcp, to-announce

#85920 Tweak wasm_base target spec to indicate linker is not GNU and update linker inferring logic for wasm-ld.
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_target/src/spec/wasm_base.rs
Labels: S-waiting-on-bors

#85930 Update standard library for IntoIterator implementation of arrays
  library/alloc/benches/vec.rs
  library/alloc/src/collections/vec_deque/pair_slices.rs
  library/alloc/src/vec/mod.rs
  library/alloc/src/vec/splice.rs
  library/alloc/tests/vec.rs
  library/core/src/array/mod.rs
  library/core/src/char/methods.rs
  library/core/tests/array.rs
  library/core/tests/iter/adapters/zip.rs
  src/test/ui/const-generics/array-impls/into-iter-impls-length-32.rs
  src/test/ui/const-generics/array-impls/into-iter-impls-length-33.rs
Labels: S-waiting-on-bors

#85972 Rustdoc html fixes
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/mod.rs
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#86028 Drop an `if let` that will always succeed
  compiler/rustc_mir/src/transform/check_consts/validation.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#86043 don't clone attrs
  compiler/rustc_ast/src/tokenstream.rs
Labels: A-parser, S-waiting-on-bors, T-compiler

#86047 Don't fire `invalid_doc_attributes` on `extern crate` items
  compiler/rustc_passes/src/check_attr.rs
  src/test/ui/rustdoc/doc-inline-extern-crate.rs
  src/test/ui/rustdoc/doc-inline-extern-crate.stderr
Labels: A-lint, S-waiting-on-bors, T-compiler

#86054 Rollup of 8 pull requests
  compiler/rustc_ast/src/tokenstream.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
  compiler/rustc_data_structures/src/obligation_forest/mod.rs
  compiler/rustc_mir/src/transform/check_consts/validation.rs
  compiler/rustc_passes/src/check_attr.rs
  compiler/rustc_target/src/spec/wasm_base.rs
  library/alloc/benches/vec.rs
  library/alloc/src/collections/vec_deque/pair_slices.rs
  library/alloc/src/vec/mod.rs
  library/alloc/src/vec/splice.rs
  library/alloc/tests/vec.rs
  library/core/src/array/mod.rs
  library/core/src/char/methods.rs
  library/core/tests/array.rs
  library/core/tests/iter/adapters/zip.rs
  src/librustdoc/html/layout.rs
  src/librustdoc/html/render/mod.rs
  src/test/ui/const-generics/array-impls/into-iter-impls-length-32.rs
  src/test/ui/const-generics/array-impls/into-iter-impls-length-33.rs
  src/test/ui/rustdoc/doc-inline-extern-crate.rs
  src/test/ui/rustdoc/doc-inline-extern-crate.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85436 Avoid cloning cache key
  compiler/rustc_data_structures/src/obligation_forest/mod.rs
Labels: S-waiting-on-bors

#85772 Preserve metadata w/ Solaris-like linkers.
  compiler/rustc_codegen_ssa/src/back/link.rs
Labels: S-waiting-on-bors

#84995 parser: Ensure that all nonterminals have tokens after parsing
  compiler/rustc_ast/src/ast_like.rs
  compiler/rustc_parse/src/parser/attr_wrapper.rs
  compiler/rustc_parse/src/parser/expr.rs
  compiler/rustc_parse/src/parser/mod.rs
  compiler/rustc_parse/src/parser/nonterminal.rs
  compiler/rustc_parse/src/parser/stmt.rs
  src/test/ui/proc-macro/expr-stmt-nonterminal-tokens.rs
  src/test/ui/proc-macro/expr-stmt-nonterminal-tokens.stdout
Labels: S-waiting-on-bors, merged-by-bors

#85086 linker: Reorder linker arguments
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
Labels: S-waiting-on-bors, merged-by-bors

#85343 Add variance-related information to lifetime error messages
  compiler/rustc_infer/src/infer/canonical/query_response.rs
  compiler/rustc_infer/src/infer/combine.rs
  compiler/rustc_infer/src/infer/equate.rs
  compiler/rustc_infer/src/infer/glb.rs
  compiler/rustc_infer/src/infer/lub.rs
  compiler/rustc_infer/src/infer/nll_relate/mod.rs
  compiler/rustc_infer/src/infer/sub.rs
  compiler/rustc_middle/src/ty/_match.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_middle/src/ty/relate.rs
  compiler/rustc_middle/src/ty/sty.rs
  compiler/rustc_mir/src/borrow_check/constraints/graph.rs
  compiler/rustc_mir/src/borrow_check/constraints/mod.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
  compiler/rustc_mir/src/borrow_check/diagnostics/region_errors.rs
  compiler/rustc_mir/src/borrow_check/region_infer/dump_mir.rs
  compiler/rustc_mir/src/borrow_check/region_infer/graphviz.rs
  compiler/rustc_mir/src/borrow_check/region_infer/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/constraint_conversion.rs
  compiler/rustc_mir/src/borrow_check/type_check/liveness/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_mir/src/borrow_check/type_check/relate_tys.rs
  compiler/rustc_mir/src/lib.rs
  compiler/rustc_typeck/src/check/dropck.rs
  src/test/ui/c-variadic/variadic-ffi-4.stderr
  src/test/ui/match/match-ref-mut-invariance.nll.stderr
  src/test/ui/match/match-ref-mut-let-invariance.nll.stderr
  src/test/ui/nll/type-check-pointer-coercions.stderr
  src/test/ui/nll/type-check-pointer-comparisons.stderr
  src/test/ui/regions/region-lifetime-bounds-on-fns-where-clause.nll.stderr
  src/test/ui/regions/region-multiple-lifetime-bounds-on-fns-where-clause.nll.stderr
  src/test/ui/regions/regions-lifetime-bounds-on-fns.nll.stderr
  src/test/ui/regions/regions-trait-object-subtyping.nll.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85965 Remove dead code from `LocalAnalyzer`
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
Labels: S-waiting-on-bors

#86010 Fix two ICEs in the parser
  compiler/rustc_parse/src/parser/path.rs
  compiler/rustc_parse/src/parser/ty.rs
  src/test/ui/parser/issue-84104.rs
  src/test/ui/parser/issue-84104.stderr
  src/test/ui/parser/issue-84148-1.rs
  src/test/ui/parser/issue-84148-1.stderr
  src/test/ui/parser/issue-84148-2.rs
  src/test/ui/parser/issue-84148-2.stderr
  src/test/ui/parser/unmatched-langle-1.rs
  src/test/ui/parser/unmatched-langle-1.stderr
  src/test/ui/parser/unmatched-langle-2.rs
  src/test/ui/parser/unmatched-langle-2.stderr
Labels: S-waiting-on-bors

#86040 Fix display for search results
  src/librustdoc/html/static/rustdoc.css
Labels: A-rustdoc-ui, S-waiting-on-bors, T-rustdoc

#86058 Remove `_` from E0121 diagnostic suggestions
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/error-codes/E0121.stderr
  src/test/ui/issues/issue-69396-const-no-type-in-macro.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.full_tait.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.min_tait.stderr
  src/test/ui/typeck/typeck_type_placeholder_item_help.stderr
Labels: S-waiting-on-bors

#86077 Fix corrected example in E0759.md
  compiler/rustc_error_codes/src/error_codes/E0759.md
Labels: S-waiting-on-bors

#86080 Rollup of 8 pull requests
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
  compiler/rustc_error_codes/src/error_codes/E0759.md
  compiler/rustc_lint/src/types.rs
  compiler/rustc_parse/src/parser/path.rs
  compiler/rustc_parse/src/parser/ty.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  src/bootstrap/bin/rustc.rs
  src/bootstrap/lib.rs
  src/librustdoc/html/static/rustdoc.css
  src/test/ui/error-codes/E0121.stderr
  src/test/ui/issues/issue-69396-const-no-type-in-macro.stderr
  src/test/ui/parser/issue-84104.rs
  src/test/ui/parser/issue-84104.stderr
  src/test/ui/parser/issue-84148-1.rs
  src/test/ui/parser/issue-84148-1.stderr
  src/test/ui/parser/issue-84148-2.rs
  src/test/ui/parser/issue-84148-2.stderr
  src/test/ui/parser/unmatched-langle-1.rs
  src/test/ui/parser/unmatched-langle-1.stderr
  src/test/ui/parser/unmatched-langle-2.rs
  src/test/ui/parser/unmatched-langle-2.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.full_tait.stderr
  src/test/ui/typeck/typeck_type_placeholder_item.min_tait.stderr
  src/test/ui/typeck/typeck_type_placeholder_item_help.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#85912 Use `Iterator::any` and `filter_map` instead of open-coding them
  compiler/rustc_lint/src/types.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#84940 Don't run sanity checks for `x.py setup`
  src/bootstrap/lib.rs
Labels: A-LLVM, A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#83433 Pass --cfg=bootstrap for proc macros built by stage0
  src/bootstrap/bin/rustc.rs
Labels: A-contributor-roadblock, A-proc-macros, A-rustbuild, S-waiting-on-bors, T-compiler

#85810 Driver improvements
  compiler/rustc_codegen_cranelift/src/driver/aot.rs
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_llvm/src/lib.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/symbol_export.rs
  compiler/rustc_codegen_ssa/src/back/write.rs
  compiler/rustc_codegen_ssa/src/base.rs
  compiler/rustc_codegen_ssa/src/lib.rs
  compiler/rustc_codegen_ssa/src/traits/backend.rs
  compiler/rustc_driver/src/lib.rs
  compiler/rustc_interface/src/queries.rs
  compiler/rustc_interface/src/util.rs
  src/test/run-make-fulldeps/hotplug_codegen_backend/the_backend.rs
Labels: A-driver, C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#85973 Replace a `match` with an `if let`
  compiler/rustc_mir/src/transform/remove_zsts.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#85996 rustbuild: take changes to the standard library into account for `download-rustc`
  src/bootstrap/bootstrap.py
Labels: A-contributor-roadblock, A-rustbuild, S-waiting-on-bors

#86016 Unify duplicate linker_and_flavor methods in rustc_codegen_{cranelift,ssa}.
  compiler/rustc_codegen_cranelift/src/toolchain.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
Labels: S-waiting-on-bors

#86025 Remove the install prefix from the rpath set when using -Crpath
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/rpath.rs
  compiler/rustc_codegen_ssa/src/back/rpath/tests.rs
  src/bootstrap/compile.rs
Labels: A-linkage, C-cleanup, S-waiting-on-bors, T-compiler

#86081 Use `try_into` instead of asserting manually
  compiler/rustc_target/src/abi/mod.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#86091 Rollup of 6 pull requests
  compiler/rustc_codegen_cranelift/src/toolchain.rs
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/rpath.rs
  compiler/rustc_codegen_ssa/src/back/rpath/tests.rs
  compiler/rustc_middle/src/ty/layout.rs
  compiler/rustc_mir/src/transform/remove_zsts.rs
  compiler/rustc_target/src/abi/mod.rs
  src/bootstrap/bootstrap.py
  src/bootstrap/compile.rs
  src/test/ui/layout/issue-84108.rs
  src/test/ui/layout/issue-84108.stderr
Labels: S-waiting-on-bors, merged-by-bors, rollup

#84262 Fix ICE during type layout when there's a `[type error]`
  compiler/rustc_middle/src/ty/layout.rs
  src/test/ui/layout/issue-84108.rs
  src/test/ui/layout/issue-84108.stderr
Labels: A-layout, S-waiting-on-bors

#85903 Remove unused functions and arguments from rustc_serialize
  compiler/rustc_errors/src/json.rs
  compiler/rustc_macros/src/serialize.rs
  compiler/rustc_query_system/src/dep_graph/serialized.rs
  compiler/rustc_serialize/src/collection_impls.rs
  compiler/rustc_serialize/src/json.rs
  compiler/rustc_serialize/src/serialize.rs
  compiler/rustc_span/src/def_id.rs
  compiler/rustc_span/src/lib.rs
Labels: S-waiting-on-bors, T-compiler, merged-by-bors

#85985 Clarify documentation of slice sorting methods
  library/core/src/slice/mod.rs
Labels: S-waiting-on-bors

#86074 Default panic message should print Box<dyn Any>
  library/std/src/panicking.rs
  src/test/ui/panics/panic-macro-any-wrapped.rs
  src/test/ui/panics/panic-macro-any.rs
Labels: S-waiting-on-bors

#86078 Type page font weight
  src/librustdoc/html/static/rustdoc.css
  src/test/rustdoc-gui/sidebar.goml
  src/test/rustdoc-gui/src/lib.rs
  src/test/rustdoc-gui/type-weight.rs
Labels: A-rustdoc, A-rustdoc-ui, S-waiting-on-bors

#86095 Search description codeblock
  src/librustdoc/html/static/search.js
  src/test/rustdoc-gui/search-result-description.goml
Labels: A-rustdoc, A-rustdoc-js, A-rustdoc-ui, S-waiting-on-bors

#86096 Comment out unused error codes and add description for E0316
  compiler/rustc_error_codes/src/error_codes.rs
  compiler/rustc_error_codes/src/error_codes/E0316.md
  src/test/ui/where-clauses/where-for-self.stderr
Labels: S-waiting-on-bors

#86103 Remove lifetime hack
  compiler/rustc_resolve/src/late/lifetimes.rs
Labels: S-waiting-on-bors

#85906 Use `Iterator::find` instead of open-coding it
  compiler/rustc_lint/src/types.rs
Labels: C-cleanup, S-waiting-on-bors, T-compiler

#85951 Update the documentation of `-C force-unwind-tables` for #83482
  src/doc/rustc/src/codegen-options/index.md
Labels: S-waiting-on-bors

#85989 Remove rustfmt tests from top-level .gitattributes
  .gitattributes
Labels: C-cleanup, S-waiting-on-bors

#86092 [beta] Backport #84894 to fix beta CI
  src/ci/scripts/install-clang.sh
Labels: S-waiting-on-bors, merged-by-bors

#85740 [Beta] Backport ICE fix in Clippy
  src/tools/clippy/clippy_lints/src/matches.rs
  src/tools/clippy/tests/ui/crashes/ice-7169.rs
  src/tools/clippy/tests/ui/crashes/ice-7169.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85893 [beta] backport of readd capture disjoint fields gate
  compiler/rustc_mir_build/src/build/expr/as_rvalue.rs
  src/test/ui/unsafe/issue-85435-unsafe-op-in-let-under-unsafe-under-closure.rs
Labels: S-waiting-on-bors, merged-by-bors

#86036 [beta] Disable mutable noalias for Rust 1.53
  compiler/rustc_codegen_llvm/src/abi.rs
  src/test/codegen/function-arguments.rs
Labels: S-waiting-on-bors, merged-by-bors

#86121 Forwarding implementation for Seek trait's stream_position method
  library/std/src/io/impls.rs
Labels: S-waiting-on-bors

#86124 Include macro name in 'local ambiguity' error
  compiler/rustc_expand/src/lib.rs
  compiler/rustc_expand/src/mbe/macro_parser.rs
  compiler/rustc_expand/src/mbe/macro_rules.rs
  src/test/ui/macros/local-ambiguity-multiple-parsing-options.stderr
Labels: S-waiting-on-bors

#86128 Refactor: Extract render_summary from render_impl.
  src/librustdoc/html/render/mod.rs
Labels: A-rustdoc, S-waiting-on-bors

#86142 Simplify proc_macro code using Bound::cloned().
  library/proc_macro/src/lib.rs
Labels: A-proc-macros, C-cleanup, S-waiting-on-bors, T-libs-impl

#85715 Document `From` impls in string.rs
  library/alloc/src/string.rs
Labels: S-waiting-on-bors

#85791 Add `Ipv6Addr::is_unicast`
  library/std/src/net/ip.rs
Labels: S-waiting-on-bors, T-libs

#85957 Display defaults on const params- rustdoc
  src/librustdoc/clean/auto_trait.rs
  src/librustdoc/clean/mod.rs
  src/librustdoc/clean/types.rs
  src/librustdoc/html/format.rs
  src/librustdoc/json/conversions.rs
  src/librustdoc/json/mod.rs
  src/rustdoc-json-types/lib.rs
  src/test/rustdoc/const-generics/const-generic-defaults.rs
Labels: S-waiting-on-bors

#85982 Enable rustdoc to document safe wasm intrinsics
  compiler/rustc_typeck/src/collect.rs
  src/test/rustdoc-ui/wasm-safe.rs
Labels: A-rustdoc, O-wasm, S-waiting-on-bors

#85676 Fix documentation style inconsistencies for IP addresses
  library/std/src/net/ip.rs
Labels: S-waiting-on-bors

#86107 Peephole optimize `x == false` and `x != true`
  compiler/rustc_mir/src/transform/instcombine.rs
  src/test/mir-opt/bool_compare.opt1.InstCombine.diff
  src/test/mir-opt/bool_compare.opt2.InstCombine.diff
  src/test/mir-opt/bool_compare.opt3.InstCombine.diff
  src/test/mir-opt/bool_compare.opt4.InstCombine.diff
  src/test/mir-opt/bool_compare.rs
Labels: S-waiting-on-bors, merged-by-bors

#86118 Create different inference variables for different defining uses of TAITs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_data_structures/src/vec_map.rs
  compiler/rustc_data_structures/src/vec_map/tests.rs
  compiler/rustc_middle/src/mir/query.rs
  compiler/rustc_middle/src/ty/context.rs
  compiler/rustc_middle/src/ty/mod.rs
  compiler/rustc_mir/src/borrow_check/nll.rs
  compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs
  compiler/rustc_mir/src/borrow_check/type_check/mod.rs
  compiler/rustc_trait_selection/src/opaque_types.rs
  compiler/rustc_typeck/src/check/check.rs
  compiler/rustc_typeck/src/check/inherited.rs
  compiler/rustc_typeck/src/check/writeback.rs
  compiler/rustc_typeck/src/collect/type_of.rs
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn-pass.rs
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn.rs
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn.stderr
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn2.rs
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn2.stderr
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn3.rs
  src/test/ui/type-alias-impl-trait/multiple-def-uses-in-one-fn3.stderr
Labels: S-waiting-on-bors, merged-by-bors

#85975 Revert "implement TrustedRandomAccess for Take iterator adapter"
  library/core/src/iter/adapters/take.rs
Labels: S-waiting-on-bors, T-libs-impl, merged-by-bors

#86150 Do not require the DefPathTable to construct the on-disk cache.
  compiler/rustc_hir/src/definitions.rs
  compiler/rustc_incremental/src/persist/load.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_middle/src/ty/query/on_disk_cache.rs
Labels: S-waiting-on-bors, merged-by-bors

#86003 Make copy/copy_nonoverlapping fn's again
  library/core/src/intrinsics.rs
  library/core/src/mem/mod.rs
  library/core/src/ptr/mod.rs
  library/core/src/ptr/mut_ptr.rs
  library/core/tests/const_ptr.rs
  src/test/ui/const-ptr/out_of_bounds_read.rs
  src/test/ui/const-ptr/out_of_bounds_read.stderr
  src/test/ui/consts/copy-intrinsic.rs
  src/test/ui/consts/copy-intrinsic.stderr
  src/test/ui/intrinsics/issue-84297-reifying-copy.rs
  src/test/ui/reify-intrinsic.rs
  src/test/ui/reify-intrinsic.stderr
  src/test/ui/thread-local-static.rs
  src/test/ui/thread-local-static.stderr
  src/tools/clippy/clippy_utils/src/paths.rs
Labels: S-waiting-on-bors, T-compiler, beta-nominated, merged-by-bors

#85910 Drop metadata_encoding_version.
  Cargo.lock
  compiler/rustc_codegen_cranelift/src/lib.rs
  compiler/rustc_codegen_cranelift/src/metadata.rs
  compiler/rustc_codegen_llvm/Cargo.toml
  compiler/rustc_codegen_llvm/src/base.rs
  compiler/rustc_metadata/src/lib.rs
  compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_middle/src/middle/cstore.rs
  compiler/rustc_middle/src/ty/context.rs
Labels: S-waiting-on-bors, merged-by-bors

#85997 rustdoc: Print a warning if the diff when comparing to old nightlies is empty
  src/tools/compiletest/src/runtest.rs
Labels: A-contributor-roadblock, A-rustdoc, A-testsuite, S-waiting-on-bors

#86051 Updated code examples and wording in move keyword documentation
  library/std/src/keyword_docs.rs
Labels: S-waiting-on-bors

#86111 fix off by one in `std::iter::Iterator` documentation
  library/core/src/iter/traits/iterator.rs
Labels: S-waiting-on-bors

#86113 build doctests with lld if use-lld = true
  src/bootstrap/bin/rustdoc.rs
  src/bootstrap/builder.rs
  src/bootstrap/lib.rs
  src/bootstrap/test.rs
Labels: S-waiting-on-bors

#84687 Multiple improvements to RwLocks
  library/std/src/panicking.rs
  library/std/src/sync/rwlock.rs
  library/std/src/sys/hermit/rwlock.rs
  library/std/src/sys/sgx/rwlock.rs
  library/std/src/sys/unix/os.rs
  library/std/src/sys/unix/rwlock.rs
  library/std/src/sys/unsupported/rwlock.rs
  library/std/src/sys/wasm/atomics/rwlock.rs
  library/std/src/sys/windows/rwlock.rs
  library/std/src/sys_common/rwlock.rs
Labels: S-waiting-on-bors, T-libs-impl

#82037 Make symbols stripping work on MacOS X
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_codegen_ssa/src/back/linker.rs
Labels: S-waiting-on-bors, T-compiler

#85741 Use preorder traversal when checking for SSA locals
  compiler/rustc_codegen_ssa/src/mir/analyze.rs
Labels: S-waiting-on-bors, merged-by-bors

#86020 Disable the machine outliner by default
  compiler/rustc_codegen_llvm/src/llvm_util.rs
Labels: S-waiting-on-bors, T-compiler, beta-accepted, beta-nominated, merged-by-bors

#86098 Add the x86_64-gnu-stable builder
  .github/workflows/ci.yml
  src/bootstrap/test.rs
  src/ci/docker/run.sh
  src/ci/github-actions/ci.yml
  src/ci/run.sh
  src/test/rustdoc/intra-doc/field.rs
  src/test/ui-fulldeps/session-derive-errors.rs
  src/test/ui-fulldeps/session-derive-errors.stderr
  src/tools/compiletest/src/common.rs
  src/tools/compiletest/src/header.rs
  src/tools/compiletest/src/header/tests.rs
  src/tools/compiletest/src/main.rs
Labels: S-waiting-on-bors, merged-by-bors

#80080 Allow qualified paths in struct construction (both expressions and patterns)
  compiler/rustc_ast/src/ast.rs
  compiler/rustc_ast/src/mut_visit.rs
  compiler/rustc_ast/src/visit.rs
  compiler/rustc_ast_lowering/src/expr.rs
  compiler/rustc_ast_lowering/src/pat.rs
  compiler/rustc_ast_passes/src/feature_gate.rs
  compiler/rustc_ast_pretty/src/pprust/state.rs
  compiler/rustc_expand/src/build.rs
  compiler/rustc_feature/src/active.rs
  compiler/rustc_lint/src/unused.rs
  compiler/rustc_parse/src/parser/attr.rs
  compiler/rustc_parse/src/parser/diagnostics.rs
  compiler/rustc_parse/src/parser/expr.rs
  compiler/rustc_parse/src/parser/pat.rs
  compiler/rustc_parse/src/parser/stmt.rs
  compiler/rustc_resolve/src/late.rs
  compiler/rustc_span/src/symbol.rs
  src/doc/unstable-book/src/language-features/more-qualified-paths.md
  src/test/ui-fulldeps/pprust-expr-roundtrip.rs
  src/test/ui/associated-types/associated-type-destructuring-assignment.rs
  src/test/ui/associated-types/associated-type-macro.rs
  src/test/ui/associated-types/associated-type-macro.stderr
  src/test/ui/associated-types/associated-type-struct-construction.rs
  src/test/ui/associated-types/associated-type-tuple-struct-construction.rs
  src/test/ui/associated-types/associated-type-tuple-struct-construction.stderr
  src/test/ui/feature-gates/feature-gate-more-qualified-paths.rs
  src/test/ui/feature-gates/feature-gate-more-qualified-paths.stderr
  src/test/ui/parser/brace-after-qualified-path-in-match.rs
  src/test/ui/parser/brace-after-qualified-path-in-match.stderr
  src/test/ui/parser/paren-after-qualified-path-in-match.rs
  src/test/ui/parser/paren-after-qualified-path-in-match.stderr
  src/tools/clippy/clippy_lints/src/misc_early/unneeded_field_pattern.rs
  src/tools/clippy/clippy_lints/src/misc_early/unneeded_wildcard_pattern.rs
  src/tools/clippy/clippy_lints/src/non_expressive_names.rs
  src/tools/clippy/clippy_lints/src/unnested_or_patterns.rs
  src/tools/clippy/clippy_utils/src/ast_utils.rs
  src/tools/rustfmt/src/expr.rs
  src/tools/rustfmt/src/patterns.rs
Labels: S-waiting-on-bors, T-lang, disposition-merge, finished-final-comment-period, merged-by-bors

#85630 to_digit simplification (less jumps)
  library/core/src/char/methods.rs
  library/core/src/lib.rs
  library/core/tests/char.rs
Labels: S-waiting-on-bors, merged-by-bors

#85961 MVP for using rust-lld as part of cc
  compiler/rustc_codegen_ssa/src/back/link.rs
  compiler/rustc_session/src/config.rs
  compiler/rustc_session/src/options.rs
  src/bootstrap/compile.rs
  src/bootstrap/dist.rs
  src/test/run-make/issue-71519/Makefile
  src/test/run-make/issue-71519/main.rs
  src/tools/compiletest/src/header.rs
Labels: S-waiting-on-bors, merged-by-bors

#85994 Disallow non-monomorphic calls to `needs_drop` in interpreter
  compiler/rustc_mir/src/interpret/intrinsics.rs
  src/test/ui/consts/const-needs_drop-monomorphic.rs
  src/test/ui/consts/const-needs_drop-monomorphic.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86116 Suggest a trailing comma if a 1-tuple is expected and a parenthesized expression is found
  compiler/rustc_infer/src/infer/error_reporting/mod.rs
  src/test/ui/suggestions/issue-86100-tuple-paren-comma.rs
  src/test/ui/suggestions/issue-86100-tuple-paren-comma.stderr
Labels: S-waiting-on-bors, merged-by-bors

#86203 Beta targetted Make copy/copy_nonoverlapping fn's again
  library/core/src/intrinsics.rs
  library/core/src/mem/mod.rs
  library/core/src/ptr/mod.rs
  library/core/src/ptr/mut_ptr.rs
  library/core/tests/const_ptr.rs
  src/test/ui/const-ptr/out_of_bounds_read.rs
  src/test/ui/const-ptr/out_of_bounds_read.stderr
  src/test/ui/consts/copy-intrinsic.rs
  src/test/ui/consts/copy-intrinsic.stderr
  src/test/ui/intrinsics/issue-84297-reifying-copy.rs
  src/test/ui/reify-intrinsic.rs
  src/test/ui/reify-intrinsic.stderr
  src/tools/clippy/clippy_utils/src/paths.rs
Labels: S-waiting-on-bors, merged-by-bors

#85885 Don't use a generator for BoxedResolver
  compiler/rustc_data_structures/src/box_region.rs
  compiler/rustc_data_structures/src/lib.rs
  compiler/rustc_interface/src/lib.rs
  compiler/rustc_interface/src/passes.rs
  compiler/rustc_metadata/src/creader.rs
  compiler/rustc_resolve/src/lib.rs
Labels: A-driver, C-cleanup, S-waiting-on-bors, T-compiler, merged-by-bors

#86225 [beta] backports
  compiler/rustc_codegen_llvm/src/llvm_util.rs
  compiler/rustc_metadata/src/rmeta/decoder.rs
  compiler/rustc_metadata/src/rmeta/encoder.rs
  compiler/rustc_metadata/src/rmeta/mod.rs
  compiler/rustc_parse/src/parser/mod.rs
  library/alloc/src/collections/vec_deque/into_iter.rs
  library/core/src/array/iter.rs
  src/bootstrap/builder.rs
  src/bootstrap/compile.rs
  src/bootstrap/native.rs
  src/ci/docker/host-x86_64/dist-various-1/Dockerfile
  src/ci/docker/host-x86_64/dist-various-2/Dockerfile
  src/ci/docker/host-x86_64/dist-various-2/build-solaris-toolchain.sh
  src/test/incremental/issue-85197-invalid-span/auxiliary/invalid-span-helper-lib.rs
  src/test/incremental/issue-85197-invalid-span/auxiliary/invalid-span-helper-mod.rs
  src/test/incremental/issue-85197-invalid-span/auxiliary/respan.rs
  src/test/incremental/issue-85197-invalid-span/invalid_span_main.rs
  src/test/run-make-fulldeps/issue-47551/Makefile
  src/test/run-make-fulldeps/issue-47551/eh_frame-terminator.rs
  src/test/ui/macros/issue-85432-ungated-attr-macro.rs
Labels: S-waiting-on-bors, merged-by-bors

#86153 Print dummy spans as `no-location`
  compiler/rustc_span/src/source_map.rs
  src/test/mir-opt/generator_storage_dead_unwind.main-{closure#0}.StateTransform.before.mir
  src/test/mir-opt/loop_test.main.SimplifyCfg-promote-consts.after.mir
  src/test/mir-opt/match_arm_scopes.complicated_match.SimplifyCfg-initial.after-ElaborateDrops.after.diff
  src/test/mir-opt/while_storage.while_loop.PreCodegen.after.mir
Labels: S-waiting-on-bors

#86174 Detect incorrect vtable alignment during const eval
  compiler/rustc_mir/src/interpret/traits.rs
  src/test/ui/consts/const-eval/ub-incorrect-vtable.rs
  src/test/ui/consts/const-eval/ub-incorrect-vtable.stderr
Labels: S-waiting-on-bors
